#%RAML 1.0 DataType
type: object
properties:
  status:
    type: number
    required: true
  code:
    type: string
    required: true
  response:
    type: object
    required: true
    properties:
      consultInventoryDetailOutput:
        type: object
        required: true
        properties:
          wsResponseHeader:
            type: object
            required: true
            properties:
              system:
                type: object
                required: true
                properties:
                  correlationId:
                    type: string | nil
                    required: false
                  name:
                    type: string | nil
                    required: false
                  processingServer:
                    type: string | nil
                    required: false
              service:
                type: object
                required: true
                properties:
                  responseDate:
                    type: string | nil
                    required: false
                  status:
                    type: string | nil
                    required: false
                  statusDetail:
                    type: string | nil
                    required: false
              property:
                type: array
                required: false
                items: 
                  type: object
                  properties: 
                    property:
                      type: object
                      required: true
                      properties: 
                        name:
                          type: string | nil
                          required: false
                        value:
                          type: string | nil
                          required: false
          bodyResponse:
            type: object
            required: false
            properties:
              consult_inventory_detailResponse:
                type: object
                required: true
                properties:
                  inventory_actions:
                    type: array
                    required: true
                    items:
                      type: object
                      properties:
                        inventory_action:
                          type: object
                          required: true
                          properties:
                            quantity:
                              type: number
                              required: false
                            final_state:
                              type: string | nil
                              required: false
                            initial_state:
                              type: string | nil
                              required: false
                            provisioning_id: 
                              type: string | nil
                              required: false
                            final_state_id:
                              type: string | nil
                              required: false
                            initial_state_id:
                              type: string | nil
                              required: false
                            action_type_id:
                              type: string | nil
                              required: false
                            observation:
                              type: string | nil
                              required: false
                            action_type:
                              type: string | nil
                              required: false
                  inventory_attributes:
                    type: array
                    required: true
                    items:
                      type: object
                      properties:
                        inventory_attribute:
                          type: object
                          required: true
                          properties:
                            description: 
                              type: string | nil
                              required: false
                            attribute_id: 
                              type: string | nil
                              required: false
                            name: 
                              type: string | nil
                              required: false
                            order: 
                              type: number
                              required: false
                            data_type:
                              type: string | nil
                              required: false
                            value:
                              type: string | nil
                              required: false
                  cellar:
                    type: string | nil
                    required: false
                  quantity:
                    type: number
                    required: false
                  reservation_quantity:
                     type: number
                     required: false
                  cost_center:
                    type: string | nil
                    required: false
                  appreciation_class: 
                    type: string | nil
                    required: false
                  document:
                    type: string | nil
                    required: false
                  is_active:
                    type: boolean | nil
                    required: false
                  state:
                    type: string | nil
                    required: false
                  up_date:
                    type: string | nil
                    required: false
                  cellar_id:
                    type: string | nil
                    required: false
                  state_id:
                    type: string | nil
                    required: false
                  product_id:
                    type: string | nil
                    required: false
                  batch:
                    type: string | nil
                    required: false
                  client_nit:
                    type: string | nil
                    required: false
                  position:
                    type: string | nil
                    required: false
                  product:
                    type: string | nil
                    required: false
                  serial:
                    type: string | nil
                    required: false
                  ubication:
                    type: string | nil
                    required: false
                  unit_value:
                    type: number
                    required: false