#%RAML 1.0 DataType
properties:
  status:
    type: number
    example: 200
  code:
    type: string
    example: "OK"
  response:
        type: object
        properties:
          get_pqrResponse:
            type: object
            properties:
              get_pqrResult:
                required: false
                type: object
                properties:
                  wsResponseHeader:
                    required: false
                    type: object
                    properties:
                      system:
                        required: false
                        type: object
                        properties:
                          name:
                            required: false
                            type: string
                            example: "MDM_Data_Services"         
                          correlationId:
                            required: false
                            type: string
                            example: "4347180004009329"
                          processingServer:
                            required: false
                            type: string
                            example: "Tibco MDM"
                      service:
                        required: false
                        type: object
                        properties:
                          status:
                            required: false
                            type: string
                            example: "OK"         
                          responseDate:
                            required: false
                            type: string
                            example: "2022-07-27 10:05:48"
                          statusDetail:
                            required: false
                            type: string
                            example: "?"
                      property:
                        required: false
                        type: array
                        items:
                          type: object
                          properties:
                            property:
                              type: object
                              properties:
                                name:
                                  required: false
                                  type: string
                                  example: "?"
                                value:
                                  required: false
                                  type: string
                                  example: "?"  
                  wsResponseBody:
                    required: false
                    type: array
                    items:
                      type: object
                      properties:
                        pqrPQR:
                          type: object
                          properties:
                            extract_update:
                              required: false
                              type: number
                              example: 1
                            id:
                              required: false
                              type: string
                              example: "62e07463f46b16213001a411"
                            rowIdPQR:
                              required: false
                              type: string
                              example: "MDM-PQR-4088670"
                            pqrNumber:
                              required: false
                              type: string
                              example: "MDM-PQR-4088670"
                            documentType:
                              required: false
                              type: string
                              example: "CC"
                            identificationNumber:
                              required: false
                              type: number
                              example: 8546541564
                            contactDocumentType:
                              required: false
                              type: string
                              example: "CC"
                            contactDocumentNumber:
                              required: false
                              type: number
                              example: 2244668899
                            serviceId:
                              required: false
                              type: string
                              example: "SR-6356484"
                            connectionNumber:
                              required: false
                              type: number
                              example: 6018000962
                            serviceAccount:
                              required: false
                              type: string
                              example: "CS-1015474"
                            billingAccount:
                              required: false
                              type: number
                              example: 15052863783
                            product:
                              required: false
                              type: string
                              example: "INTERNET"
                            orderNumber:
                              required: false
                              type: string
                              example: ""
                            pqrComplaintPQR:
                              required: false
                              type: string
                              example: ""
                            typePqrComplaint:
                              required: false
                              type: string
                              example: ""
                            cun:
                              required: false
                              type: number
                              example: 4347180004009329
                            service:
                              required: false
                              type: string
                              example: ""
                            technology:
                              required: false
                              type: string
                              example: "FTTC"
                            pqrType:
                              required: false
                              type: string
                              example: "PRODUCTO"
                            pqrClass:
                              required: false
                              type: string
                              example: "QUEJA"
                            pqrMotive:
                              required: false
                              type: string
                              example: "FACTURACION/GESTION DE SALDOS"
                            pqrCausal:
                              required: false
                              type: string
                              example: "ERROR FACTURA / COBRO O DESCUENTO INJUSTIFICADO"
                            pqrUrgency:
                              required: false
                              type: string
                              example: ""
                            impact:
                              required: false
                              type: string
                              example: ""                         
                            pqrSymptom:
                              required: false
                              type: string
                              example: "CAMBIO PLAN NO CUMPLIDO"
                            claimedValue:
                              type: number
                              example: 0
                            adjustedValue:
                              type: number
                              example: 0
                            creationDate:
                              type: datetime
                              example: 2022-07-26T23:10:27Z
                            radication_Date:
                              type: datetime
                              example: 2022-07-26T23:10:27Z
                            solutionDate:
                              type: datetime
                              example: 2022-07-26T23:10:27Z
                            solution:
                              required: false
                              type: string
                              example: " jghj"
                            accountability:
                              required: false
                              type: string
                              example: ""
                            pqrStatus:
                              required: false
                              type: string
                              example: "Resuelto"
                            remedySendingState:
                              required: false
                              type: string
                              example: ""
                            closingType:
                              required: false
                              type: string
                              example: "NO ACCEDE"
                            pqrNotificationVia:
                              required: false
                              type: string
                              example: ""
                            receptionVia:
                              required: false
                              type: string
                              example: "APLICACIÓN MÓVIL"
                            pqrDescription:
                              required: false
                              type: string
                              example: "fgfgfhf"
                            pqrResponse:
                              required: false
                              type: string
                              example: ""
                            numIncidenceRemedy:
                              required: false
                              type: string
                              example: ""
                            responseRemedy:
                              required: false
                              type: string
                              example: ""
                            systemOriginId:
                              required: false
                              type: string
                              example: "MDM_PQR"
                            systemOrigin:
                              required: false
                              type: string
                              example: ""
                            lspCallSource:
                              required: false
                              type: string
                              example: ""
                            lspThirdDestination:
                              required: false
                              type: string
                              example: ""
                            pqrFullFlag:
                              required: false
                              type: string
                              example: ""
                            email:
                              required: false
                              type: string
                              example: ""
                            cunMassiveFailure:
                              required: false
                              type: string
                              example: ""
                            writtenNotificationAddress:
                              required: false
                              type: string
                              example: ""
                            externalRooted:
                              required: false
                              type: string
                              example: ""
                            flagAppealResource:
                              type: string
                              example: "false"
                            flagTransferGovernment:
                              type: string
                              example: "false"
                            flagRecurringCustomer:
                              type: string
                              example: "false"
                            flagReopening:
                              type: string
                              example: "false"
                            priority:
                              required: false
                              type: string
                              example: ""
                            creatorUser:
                              required: false
                              type: string
                              example: "juanbaeg"
                            assignedUser:
                              required: false
                              type: string
                              example: "juanbaeg"
                            comments:
                              required: false
                              type: string
                              example: ""
                            customerName:
                              required: false
                              type: string
                              example: "PER SONA"
                            customerSegment:
                              required: false
                              type: string
                              example: "Hogares"
                            resolutionCode:
                              required: false
                              type: string
                              example: ""
                            resolurionDescription:
                              required: false
                              type: string
                              example: ""
                            subChannel:
                              required: false
                              type: string
                              example: "APP Mi ETB"
                            point:
                              required: false
                              type: string
                              example: "AUTOGESTIÓN"
                            supplier:
                              required: false
                              type: string
                              example: "ATENTO"
                            management:
                              required: false
                              type: string
                              example: "GERENCIA EXPERIENCIA AL CLIENTE"
                            stoplight:
                              required: false
                              type: string
                              example: "verde"
                            businessDays:
                              type: number
                              required: false
                              example: 0
                            waitStartDate:
                              type: string | nil
                              example: null
                            waitEndDate:
                              type: string | nil
                              example: null
                            cunRelated:
                              required: false
                              type: string
                              example: "4347180004009329"
                            contactName:
                              required: false
                              type: string
                              example: "TEST RUIZ RUIZ RUIZ"
                            receptionChannel:
                              required: false
                              type: string
                              example: "DIGITAL"
                            pqrExtensions:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  pqrExtension:
                                    type: object
                                    properties:
                                      extensionDays:
                                        type: string
                                        example: "?"
                                      extensionStartDate:
                                        type: string
                                        example: "?"
                                      extensionEndDate:
                                        type: string
                                        example: "?"
                            pqrActivitiesPQR:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  pqrActivityPQR:
                                    required: false
                                    type: object
                                    properties:
                                      extractorUpdate:
                                        required: false
                                        type: number
                                        example: 1
                                      activityRowId:
                                        required: false
                                        type: string
                                        example: "MDM-PQR-ACT-2175105"
                                      activityName:
                                        required: false
                                        type: string
                                        example: "INSTANCIA ADMINISTRATIVA"
                                      activityStatus:
                                        required: false
                                        type: string
                                        example: "En progreso"
                                      comments:
                                        required: false
                                        type: string
                                        example: ""
                                      description:
                                        required: false
                                        type: string
                                        example: ""
                                      management:
                                        required: false
                                        type: string
                                        example: "NO APLICA"
                                      managementDescription:
                                        required: false
                                        type: string
                                        example: "ES IMPORTANTE MENCIONAR QUE  CONTRA LA PRESENTA PETICION/QUEJA NO PROCEDE INSTANCIA ADMINISTRATIVA DEBIDO A QUE NO ESTÁ ENMARCADA DENTRO DE LAS CAUSALES SEÑALADAS EN EL ARTÍCULO 54 DE LA LEY 1341/11 Y ARTÍCULO 47 DE LA RESOLUCION 3066/11”."
                                      activityGroup:
                                        required: false
                                        type: string
                                        example: "MIXTA"
                                      assignedUser:
                                        required: false
                                        type: string
                                        example: "juanbaeg"
                                      userCreatorActivity:
                                        required: false
                                        type: string
                                        example: "juanbaeg"
                                      activityStartDate:
                                        type: datetime
                                        example: 2022-07-26T23:12:10Z
                                      currentStatusDate:
                                        type: datetime
                                        example: 2022-07-26T23:12:10Z
                                      activityDueDate:
                                        type: datetime
                                        example: 2022-07-31T23:12:10Z
                                      final:
                                        required: false
                                        type: string
                                        example: ""
                                      priority:
                                        required: false
                                        type: string
                                        example: ""
                                      disconnectionDate:
                                        required: false
                                        type: string
                                        example: ""
                                      reconnectionDate:
                                        required: false
                                        type: string
                                        example: ""
                                      duration:
                                        required: false
                                        type: string
                                        example: ""
                                      bill:
                                        required: false
                                        type: string
                                        example: ""
                                      notification:
                                        required: false
                                        type: string
                                        example: ""
                                      stoplight:
                                        required: false
                                        type: string
                                        example: ""
                                      businessDays:
                                        required: false
                                        type: string
                                        example: ""
                                      attachedActivities:
                                        required: false
                                        type: array
                                        items:
                                          type: object
                                          properties:
                                            pqrAttachmentsActivity:
                                              type: object
                                              properties:
                                                attached_activities:
                                                  required: false
                                                  type: string
                                                  example: ""
                            pqrAttachedFiles:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  pqrAttachedFile:
                                    type: object
                                    properties:
                                      attachedFile:
                                        required: false
                                        type: string
                                        example: "?"
                            characteristicsPQR:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  characteristicsPQR:
                                    type: object
                                    properties:
                                      flowId:
                                        required: false
                                        type: string
                                        example: "?"
                                      url: 
                                        required: false
                                        type: string
                                        example: "?"
                                      date:
                                        type: string
                                        example: "?"
                            pqrCharacteristics:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  pqrCharacteristics:
                                    type: object
                                    properties:
                                      characteristic:
                                        required: false
                                        type: string
                                        example: "?"
                                      value:
                                        required: false
                                        type: string
                                        example: "?"
                            pqrSuspensionDetail:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  pqrSuspensionDetail:
                                    type: object
                                    properties:
                                      newGroup:
                                        required: false
                                        type: string
                                        example: "?"
                                      suspensionStatus:
                                        type: string
                                        example: "?"
                                      causalReasonSupension:
                                        required: false
                                        type: string
                                        example: "?"
                                      groupChangeDate:
                                        required: false
                                        type: string
                                        example: "?"
                            pqrVersion:
                              required: false
                              type: string
                              example: "37"
                            flagNotificacion:
                              type: string
                              example: "false"
                            earlyFailureFlag:
                              type: string
                              example: "false"
                            secondLevelStatus:
                              required: false
                              type: array
                              items:
                                type: object
                                properties:
                                  secondLevelStatus:
                                    type: object
                                    properties:
                                      id:
                                        required: false
                                        type: string
                                        example: "?"
                                      code:
                                        required: false
                                        type: string
                                        example: "?"
                                      description:
                                        required: false
                                        type: string
                                        example: "?"
                                      date:
                                        type: string
                                        example: "?"
                                      retries:
                                        type: string
                                        example: "?" 
                                      exceptionCode:
                                        type: string
                                        example: "?"
                            modificationDate:
                              type: string
                              example: "2022-07-26T23:12:50.839Z"                        
                            subStatus:
                              required: false
                              type: string
                              example: "?"         
                            exception:
                              required: false
                              type: string
                              example: "?"         
                            excepcionType:
                              required: false
                              type: string
                              example: "?"         
                            originatedBy:
                              required: false
                              type: string
                              example: "?"         
                            family:
                              required: false
                              type: string
                              example: "FACTURACION"         
                            contactType:
                              required: false
                              type: string
                              example: "TRANSACCION"         
                            firm:
                              required: false
                              type: string
                              example: "?"         
                            isMultiDetail:
                              type: string
                              example: "true"         
                            contingentDate:
                              required: false
                              type: string
                              example: "?"         
                            shippingCommunications:                          
                              required: false
                              type: object
                              properties:
                                communicationVia:
                                  required: false
                                  type: string
                                  example: "?"                                  
                                communicationData1:
                                  required: false
                                  type: string
                                  example: "?"                
                                communicationData2:
                                  required: false
                                  type: string
                                  example: "?"
                            mdmRelates:
                              required: false
                              type: string
                              example: "?"                              
                            annulmentMotive:                
                              required: false
                              type: string
                              example: "?"  