#%RAML 1.0 DataType

properties:
  Envelope:
    type: object
    properties:
      Body:
        type: object
        properties:
          Fault:
            type: object
            properties:
              faultcode:
                type: string
                example: "soap:Server"
              faultstring: 
                type: string
                example: "Server was unable to process request. ---> Root element is missing."