#%RAML 1.0 DataType
properties:
  ServiceOutput:
    type: object
    properties:
      Header:
        type: object
        properties:
          transactionId: string
          sourceSystem: string
      OutputMessage:
        type: object
        properties: 
          id: string
          code: string
          description: string