#%RAML 1.0 DataType
properties:
  status:
    type: string
    example: "OK"
  operationResult:
    type: string
    example: "1"
  operationResultDesc:
    type: string
    example: "Información almacenada de manera exitosa"
  responseDate:
    type: string
    example: "2023-07-26 12:26:17"

example:
  {
    "status": "OK",
    "operationResult": "1",
    "operationResultDesc": "Información almacenada de manera exitosa",
    "responseDate": "2023-07-26 12:26:17"
  } 