#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Orden consultada exitosamente
    required: false
  order:
    type: object
    properties:
      id:
        type: string
        example: 68ded01c7d0397ef7b0664cc
        required: false
      createdAt:
        type: datetime
        example: '2025-10-02T14:18:52.473Z'
        required: false
      updatedAt:
        type: datetime
        example: '2025-10-02T14:30:25.385Z'
        required: false
      updatedBy:
        type: string
        example: PortalLTE
        required: false
      createdBy:
        type: string
        example: PortalLTE
        required: false
      extractorUpdate:
        type: string
        example: '1'
        required: false
      orderNumber:
        type: string
        example: MDM-FIBRA-000636091
        required: false
      channel:
        type: string
        example: Ecommerce
        required: false
      phase:
        type: string
        example: ORDERF
        required: false
      commercialOrderStatus:
        type: object
        properties:
          code:
            type: string
            example: O75
            required: false
          description:
            type: string
            example: Error Orquestación
            required: false
          date:
            type: datetime
            example: '2025-10-02T14:22:17.594Z'
            required: false
          retries:
            type: integer
            example: 0
            required: false
          exceptionCode:
            type: integer
            example: 1
            required: false
          exception:
            type: string
            example: >-
              La tarea VCONDES del sistema no se ha completado correctamente.
              Consulte al fiduciario del sistema.
            required: false
      through:
        type: object
        properties:
          throughType:
            type: string
            example: VTA
            required: false
          throughSubtype:
            type: string
            example: ''
            required: false
          throughDate:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          reconnectionDate:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          suspensionDate:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          executionDate:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          keepConnectionNumber:
            type: boolean
            example: false
            required: false
          permanenceClause:
            type: boolean
            example: true
            required: false
          permanenceClauseValue:
            type: integer
            example: 0
            required: false
          cancellationReason:
            type: string
            example: ''
            required: false
          cancellationSubreason:
            type: string
            example: ''
            required: false
          cancellationDescription:
            type: string
            example: ''
            required: false
          orderReasons:
            type: string
            example: ''
            required: false
      serviceType:
        type: string
        example: ''
        required: false
      cun:
        type: string
        example: '4347250001278699'
        required: false
      previousCustomer:
        type: string
        example: ''
        required: false
      customer:
        type: object
        properties:
          id:
            type: object
            properties:
              oid:
                type: string
                example: 68decf606d735051ede511c7
                required: false
          createdAt:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          updatedAt:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          updatedBy:
            type: string
            example: PortalLTE
            required: false
          createdBy:
            type: string
            example: PortalLTE
            required: false
          extractorUpdate:
            type: string
            example: ''
            required: false
          customerAccountId:
            type: integer
            example: 0
            required: false
          documentType:
            type: string
            example: CC
            required: false
          documentNumber:
            type: string
            example: '28564778'
            required: false
          firstNames:
            type: string
            example: PROSPECTO
            required: false
          companyShortName:
            type: string
            example: ''
            required: false
          firstLastName:
            type: string
            example: JIMENEZ
            required: false
          secondLastName:
            type: string
            example: ''
            required: false
          expeditionDate:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          identityValidationDate:
            type: string
            example: ''
            required: false
          authorizesPersonalDataHandling:
            type: string
            example: 'N'
            required: false
          authorizesCreditBureauConsultation:
            type: string
            example: 'N'
            required: false
          uen:
            type: string
            example: Hogares y Mipymes
            required: false
          uenSegment:
            type: string
            example: Hogares
            required: false
          segment:
            type: string
            example: Hogares
            required: false
          fixedScoring:
            type: object
            properties:
              scoringValue:
                type: integer
                example: 0
                required: false
              scoringDate:
                type: datetime
                example: '2025-10-02T14:18:52.473Z'
                required: false
              scoringClassification:
                type: string
                example: ''
                required: false
              scoringType:
                type: string
                example: ''
                required: false
              originSystem:
                type: string
                example: ''
                required: false
          landlinePhone:
            type: string
            example: ''
            required: false
          extension:
            type: string
            example: ''
            required: false
          mobilePhone:
            type: string
            example: '3156360101'
            required: false
          mobilePhone2:
            type: string
            example: ''
            required: false
          email:
            type: string
            example: notiene@etb.com.co
            required: false
          contacts:
            type: array
            items:
              type: object
              properties:
                id:
                  type: object
                  properties:
                    oid:
                      type: string
                      example: 68decf606d735051ede511c7
                      required: false
                documentType:
                  type: string
                  example: CC
                  required: false
                documentNumber:
                  type: string
                  example: '28564778'
                  required: false
                firstNames:
                  type: string
                  example: PROSPECTO
                  required: false
                firstLastName:
                  type: string
                  example: JIMENEZ
                  required: false
                secondLastName:
                  type: string
                  example: ''
                  required: false
                landlinePhone:
                  type: string
                  example: ''
                  required: false
                landlinePhone2:
                  type: string
                  example: ''
                  required: false
                mobilePhone:
                  type: string
                  example: '3156360101'
                  required: false
                mobilePhone2:
                  type: string
                  example: ''
                  required: false
                email:
                  type: string
                  example: ''
                  required: false
                department:
                  type: string
                  example: BOGOTA
                  required: false
                city:
                  type: string
                  example: BOGOTA D.C.
                  required: false
                daneCode:
                  type: string
                  example: ''
                  required: false
                address:
                  type: string
                  example: KR 7 20 00
                  required: false
                locality:
                  type: string
                  example: ''
                  required: false
                selected:
                  type: boolean
                  example: false
                  required: false
                authorized:
                  type: boolean
                  example: true
                  required: false
                status:
                  type: boolean
                  example: false
                  required: false
                delete:
                  type: boolean
                  example: false
                  required: false
                contactAttachments:
                  type: string
                  example: ''
                  required: false
                expeditionDate:
                  type: string
                  example: ''
                  required: false
                birthdayDate:
                  type: string
                  example: ''
                  required: false
                phoneValidationDate:
                  type: string
                  example: ''
                  required: false
                emailValidationDate:
                  type: string
                  example: ''
                  required: false
                extractorUpdate:
                  type: string
                  example: ''
                  required: false
          addresses:
            type: array
            items:
              type: object
              properties:
                addressId:
                  type: integer
                  example: 2
                  required: false
                normalizedAddress:
                  type: string
                  example: KR 1 70 21 AP 101
                  required: false
                addressType:
                  type: string
                  example: INSTALACION
                  required: false
                addressCode:
                  type: string
                  example: ''
                  required: false
                departmentCode:
                  type: string
                  example: '11'
                  required: false
                municipalityCode:
                  type: string
                  example: '11001'
                  required: false
                countryCode:
                  type: string
                  example: 593b0ac99a8e4177d410df4d
                  required: false
                addressName:
                  type: string
                  example: ''
                  required: false
                department:
                  type: string
                  example: BOGOTA
                  required: false
                municipality:
                  type: string
                  example: BOGOTA D.C.
                  required: false
                status:
                  type: string
                  example: ACTIVO
                  required: false
                selected:
                  type: boolean
                  example: false
                  required: false
                coverage:
                  type: object
                  properties:
                    coverageType:
                      type: string
                      example: MOLECULA
                      required: false
                    lotCode:
                      type: string
                      example: '12'
                      required: false
                    locality:
                      type: string
                      example: '02'
                      required: false
                    stratum:
                      type: integer
                      example: 2
                      required: false
                    latitude:
                      type: number
                      example: 4.650874623
                      required: false
                    longitude:
                      type: number
                      example: -74.05224817
                      required: false
                    gisAddress:
                      type: string
                      example: '612802304579196010'
                      required: false
                    coverageName:
                      type: string
                      example: FCO23
                      required: false
                    olt:
                      type: string
                      example: BOCOZTC30001
                      required: false
                    owner:
                      type: string
                      example: ETB
                      required: false
                    purpose:
                      type: string
                      example: '01'
                      required: false
                    technology:
                      type: string
                      example: FTTH
                      required: false
                    zone:
                      type: string
                      example: CHICO
                      required: false
                    distanceType:
                      type: string
                      example: AE
                      required: false
                    distanceType2:
                      type: string
                      example: ''
                      required: false
                    district:
                      type: string
                      example: ''
                      required: false
                    molecule:
                      type: string
                      example: FCO23
                      required: false
                    viable:
                      type: boolean
                      example: false
                      required: false
                    usageCode:
                      type: string
                      example: '001'
                      required: false
                availableCoverages:
                  type: array
                  items:
                    type: object
                    properties:
                      coverageType:
                        type: string
                        example: MOLECULA
                        required: false
                      lotCode:
                        type: string
                        example: '12'
                        required: false
                      locality:
                        type: string
                        example: '02'
                        required: false
                      stratum:
                        type: integer
                        example: 2
                        required: false
                      latitude:
                        type: number
                        example: 4.650874623
                        required: false
                      longitude:
                        type: number
                        example: -74.05224817
                        required: false
                      gisAddress:
                        type: string
                        example: '612802304579196010'
                        required: false
                      coverageName:
                        type: string
                        example: FCO23
                        required: false
                      olt:
                        type: string
                        example: BOCOZTC30001
                        required: false
                      owner:
                        type: string
                        example: ETB
                        required: false
                      purpose:
                        type: string
                        example: '01'
                        required: false
                      technology:
                        type: string
                        example: FTTH
                        required: false
                      zone:
                        type: string
                        example: CHICO
                        required: false
                      distanceType:
                        type: string
                        example: AE
                        required: false
                      distanceType2:
                        type: string
                        example: ''
                        required: false
                      district:
                        type: string
                        example: ''
                        required: false
                      molecule:
                        type: string
                        example: FCO23
                        required: false
                      viable:
                        type: boolean
                        example: false
                        required: false
                      usageCode:
                        type: string
                        example: '001'
                        required: false
                usageCode:
                  type: string
                  example: '001'
                  required: false
          billingAccounts:
            type: string
            example: ''
            required: false
          serviceAccounts:
            type: string
            example: ''
            required: false
          customerAttachments:
            type: array
            items: {}
          originSystem:
            type: object
            properties:
              originSystemId:
                type: string
                example: Tienda
                required: false
              originSystemName:
                type: string
                example: Web
                required: false
          status:
            type: string
            example: PENDIENTE
            required: false
          carouselReason:
            type: string
            example: ''
            required: false
          carouselSubReason:
            type: string
            example: ''
            required: false
          atdp:
            type: object
            properties:
              habeasData:
                type: string
                example: ''
                required: false
              date:
                type: datetime
                example: '2025-10-02T14:18:35.158Z'
                required: false
              user:
                type: string
                example: PortalLTE
                required: false
              channel:
                type: string
                example: Tienda
                required: false
              associatedPqr:
                type: string
                example: 68decf8d6d735051ede511c8
                required: false
          address:
            type: string
            example: ''
            required: false
          coverage:
            type: string
            example: ''
            required: false
          department:
            type: string
            example: BOGOTA
            required: false
          city:
            type: string
            example: BOGOTA D.C.
            required: false
          communicationsConsent:
            type: string
            example: ''
            required: false
          emailAddress:
            type: string
            example: notiene@etb.com.co
            required: false
      previousService:
        type: string
        example: ''
        required: false
      service:
        type: object
        properties:
          id:
            type: object
            properties:
              oid:
                type: string
                example: '000000000000000000000000'
                required: false
          createdAt:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          updatedAt:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          updatedBy:
            type: string
            example: ''
            required: false
          createdBy:
            type: string
            example: ''
            required: false
          extractorUpdate:
            type: string
            example: ''
            required: false
          serviceAccountId:
            type: string
            example: CS-1052382
            required: false
          bundle:
            type: object
            properties:
              id:
                type: object
                properties:
                  oid:
                    type: string
                    example: 68769f4c7b67fb1a1015a60a
                    required: false
              createdAt:
                type: datetime
                example: '2025-10-02T14:18:52.473Z'
                required: false
              updatedAt:
                type: datetime
                example: '2025-10-02T14:18:52.473Z'
                required: false
              updatedBy:
                type: string
                example: ''
                required: false
              createdBy:
                type: string
                example: ''
                required: false
              extractorUpdate:
                type: string
                example: ''
                required: false
              configCode:
                type: string
                example: ''
                required: false
              groupingNumber:
                type: integer
                example: 6847
                required: false
              productType:
                type: string
                example: BUNDLE
                required: false
              serviceType:
                type: string
                example: FTTH
                required: false
              serviceSubtype:
                type: string
                example: ''
                required: false
              productSubtype:
                type: string
                example: ''
                required: false
              sequence:
                type: integer
                example: 0
                required: false
              dependency:
                type: integer
                example: 0
                required: false
              classification:
                type: string
                example: SERVICIO
                required: false
              name:
                type: string
                example: DUO 500M HOG V3
                required: false
              icon:
                type: string
                example: ''
                required: false
              display:
                type: string
                example: ''
                required: false
              status:
                type: string
                example: Activo
                required: false
              minimumQuantity:
                type: integer
                example: 1
                required: false
              maximumQuantity:
                type: integer
                example: 1
                required: false
              offerPrice:
                type: array
                items:
                  type: object
                  properties:
                    salesChannel:
                      type: string
                      example: ''
                      required: false
                    priceExcludingTax:
                      type: integer
                      example: 99900
                      required: false
                    priceIncludingTax:
                      type: integer
                      example: 99900
                      required: false
                    tax:
                      type: integer
                      example: 0
                      required: false
              offerProductFeatures:
                type: array
                items: {}
              offerFilterGrouping:
                type: string
                example: ''
                required: false
              offerTechnicalSpecValue:
                type: string
                example: ''
                required: false
              serviceClassId:
                type: integer
                example: 0
                required: false
              availability:
                type: boolean
                example: false
                required: false
              scheduling:
                type: boolean
                example: false
                required: false
              provisioning:
                type: boolean
                example: false
                required: false
              billing:
                type: boolean
                example: false
                required: false
              action:
                type: string
                example: ''
                required: false
              itemId:
                type: string
                example: ''
                required: false
              parentItemId:
                type: string
                example: ''
                required: false
              productTypeId:
                type: integer
                example: 0
                required: false
              serviceTypeId:
                type: integer
                example: 2
                required: false
              serviceSubtypeId:
                type: integer
                example: 0
                required: false
              productSubtypeId:
                type: integer
                example: 0
                required: false
              serviceId:
                type: string
                example: CS-1052382
                required: false
              auxiliaryOptionalId:
                type: string
                example: ''
                required: false
              attributes:
                type: array
                items: {}
              additionalType:
                type: string
                example: ''
                required: false
              productParameters:
                type: array
                items: {}
              selected:
                type: boolean
                example: false
                required: false
              disabled:
                type: boolean
                example: false
                required: false
              discount:
                type: integer
                example: 0
                required: false
              finalPrice:
                type: integer
                example: 0
                required: false
              bundleParameters:
                type: array
                items:
                  type: object
                  properties:
                    parameter:
                      type: string
                      example: CANAL VENTA
                      required: false
                    parameterType:
                      type: string
                      example: Parámetro General
                      required: false
                    value:
                      type: string
                      example: PORTAL FIJA/ECOMMERCE/AUTOGESTION
                      required: false
              primaries:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: object
                      properties:
                        oid:
                          type: string
                          example: 68769ff87b67fb1a1015a627
                          required: false
                    createdAt:
                      type: string
                      example: ''
                      required: false
                    updatedAt:
                      type: string
                      example: ''
                      required: false
                    updatedBy:
                      type: string
                      example: ''
                      required: false
                    createdBy:
                      type: string
                      example: ''
                      required: false
                    extractorUpdate:
                      type: string
                      example: ''
                      required: false
                    configCode:
                      type: string
                      example: '122229'
                      required: false
                    groupingNumber:
                      type: integer
                      example: 6847
                      required: false
                    productType:
                      type: string
                      example: Primario
                      required: false
                    serviceType:
                      type: string
                      example: FTTH
                      required: false
                    serviceSubtype:
                      type: string
                      example: FTTH INTERNET
                      required: false
                    productSubtype:
                      type: string
                      example: ''
                      required: false
                    sequence:
                      type: integer
                      example: 10
                      required: false
                    dependency:
                      type: integer
                      example: 10
                      required: false
                    classification:
                      type: string
                      example: ''
                      required: false
                    name:
                      type: string
                      example: INTERNET
                      required: false
                    icon:
                      type: string
                      example: ''
                      required: false
                    display:
                      type: string
                      example: ''
                      required: false
                    status:
                      type: string
                      example: Activo
                      required: false
                    minimumQuantity:
                      type: integer
                      example: 0
                      required: false
                    maximumQuantity:
                      type: integer
                      example: 0
                      required: false
                    offerPrice:
                      type: string
                      example: ''
                      required: false
                    offerProductFeatures:
                      type: array
                      items: {}
                    offerFilterGrouping:
                      type: string
                      example: ''
                      required: false
                    offerTechnicalSpecValue:
                      type: string
                      example: ''
                      required: false
                    serviceClassId:
                      type: integer
                      example: 1100
                      required: false
                    availability:
                      type: boolean
                      example: true
                      required: false
                    scheduling:
                      type: boolean
                      example: true
                      required: false
                    provisioning:
                      type: boolean
                      example: true
                      required: false
                    billing:
                      type: boolean
                      example: false
                      required: false
                    action:
                      type: string
                      example: ''
                      required: false
                    itemId:
                      type: string
                      example: '1'
                      required: false
                    parentItemId:
                      type: string
                      example: ''
                      required: false
                    productTypeId:
                      type: integer
                      example: 1
                      required: false
                    serviceTypeId:
                      type: integer
                      example: 2
                      required: false
                    serviceSubtypeId:
                      type: integer
                      example: 22
                      required: false
                    productSubtypeId:
                      type: integer
                      example: 0
                      required: false
                    serviceId:
                      type: string
                      example: SR-7002656
                      required: false
                    auxiliaryOptionalId:
                      type: string
                      example: ''
                      required: false
                    attributes:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            example: FAMILIA
                            required: false
                          value:
                            type: string
                            example: HSI
                            required: false
                          type:
                            type: string
                            example: Agendamiento
                            required: false
                    additionalType:
                      type: string
                      example: ''
                      required: false
                    productParameters:
                      type: array
                      items: {}
                    selected:
                      type: boolean
                      example: false
                      required: false
                    disabled:
                      type: boolean
                      example: false
                      required: false
                    discount:
                      type: integer
                      example: 0
                      required: false
                    finalPrice:
                      type: integer
                      example: 0
                      required: false
                    secondaries:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: object
                            properties:
                              oid:
                                type: string
                                example: 68769ff87b67fb1a1015a628
                                required: false
                          createdAt:
                            type: string
                            example: ''
                            required: false
                          updatedAt:
                            type: string
                            example: ''
                            required: false
                          updatedBy:
                            type: string
                            example: ''
                            required: false
                          createdBy:
                            type: string
                            example: ''
                            required: false
                          extractorUpdate:
                            type: string
                            example: ''
                            required: false
                          configCode:
                            type: string
                            example: '22222220221'
                            required: false
                          groupingNumber:
                            type: integer
                            example: 6847
                            required: false
                          productType:
                            type: string
                            example: SECUNDARIO
                            required: false
                          serviceType:
                            type: string
                            example: FTTH
                            required: false
                          serviceSubtype:
                            type: string
                            example: FTTH INTERNET
                            required: false
                          productSubtype:
                            type: string
                            example: ''
                            required: false
                          sequence:
                            type: integer
                            example: 20
                            required: false
                          dependency:
                            type: integer
                            example: 10
                            required: false
                          classification:
                            type: string
                            example: ''
                            required: false
                          name:
                            type: string
                            example: IP DINÁMICA
                            required: false
                          icon:
                            type: string
                            example: ''
                            required: false
                          display:
                            type: string
                            example: ''
                            required: false
                          status:
                            type: string
                            example: Activo
                            required: false
                          minimumQuantity:
                            type: integer
                            example: 1
                            required: false
                          maximumQuantity:
                            type: integer
                            example: 1
                            required: false
                          offerPrice:
                            type: string
                            example: ''
                            required: false
                          offerProductFeatures:
                            type: array
                            items: {}
                          offerFilterGrouping:
                            type: string
                            example: ''
                            required: false
                          offerTechnicalSpecValue:
                            type: string
                            example: ''
                            required: false
                          serviceClassId:
                            type: integer
                            example: 2102
                            required: false
                          availability:
                            type: boolean
                            example: true
                            required: false
                          scheduling:
                            type: boolean
                            example: false
                            required: false
                          provisioning:
                            type: boolean
                            example: true
                            required: false
                          billing:
                            type: boolean
                            example: false
                            required: false
                          action:
                            type: string
                            example: ''
                            required: false
                          itemId:
                            type: string
                            example: '2'
                            required: false
                          parentItemId:
                            type: string
                            example: ''
                            required: false
                          productTypeId:
                            type: integer
                            example: 2
                            required: false
                          serviceTypeId:
                            type: integer
                            example: 2
                            required: false
                          serviceSubtypeId:
                            type: integer
                            example: 22
                            required: false
                          productSubtypeId:
                            type: integer
                            example: 2220
                            required: false
                          serviceId:
                            type: string
                            example: SR-7002657
                            required: false
                          auxiliaryOptionalId:
                            type: string
                            example: ''
                            required: false
                          attributes:
                            type: array
                            items:
                              type: object
                              properties:
                                name:
                                  type: string
                                  example: MASCARA
                                  required: false
                                value:
                                  type: string
                                  example: '30'
                                  required: false
                                type:
                                  type: string
                                  example: Aprovisionamiento
                                  required: false
                          additionalType:
                            type: string
                            example: ''
                            required: false
                          productParameters:
                            type: array
                            items: {}
                          selected:
                            type: boolean
                            example: false
                            required: false
                          disabled:
                            type: boolean
                            example: false
                            required: false
                          discount:
                            type: integer
                            example: 0
                            required: false
                          finalPrice:
                            type: integer
                            example: 0
                            required: false
                    additionals:
                      type: array
                      items: {}
                    gold:
                      type: string
                      example: ''
                      required: false
                    number:
                      type: string
                      example: ''
                      required: false
          bundlePermanenceClause:
            type: string
            example: ''
            required: false
          optionals:
            type: array
            items: {}
          promotions:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  example: 680a5f8ed7083908080132b1
                  required: false
                name:
                  type: string
                  example: PROMOCIÓN DESCUENTO 100% PRORRATEO + 50% MESES 1-2-3-4
                  required: false
                description:
                  type: string
                  example: PROMOCIÓN DESCUENTO 100% PRORRATEO + 50% MESES 1-2-3-4
                  required: false
                type:
                  type: string
                  example: Nueva
                  required: false
                startDate:
                  type: datetime
                  example: '2025-10-02T14:18:52.473Z'
                  required: false
                action:
                  type: string
                  example: Adicionar
                  required: false
                products:
                  type: array
                  items: {}
                optionals:
                  type: array
                  items: {}
                discount:
                  type: boolean
                  example: true
                  required: false
                origin:
                  type: string
                  example: Promociones
                  required: false
                level:
                  type: integer
                  example: 0
                  required: false
                groupingNumber:
                  type: integer
                  example: 6847
                  required: false
                features:
                  type: array
                  items:
                    type: object
                    properties:
                      feature:
                        type: string
                        example: TipoAuxiliarDependiente
                        required: false
                      values:
                        type: array
                        items:
                          type: string
          customer:
            type: string
            example: ''
            required: false
          status:
            type: string
            example: ''
            required: false
          throughOrderId:
            type: string
            example: ''
            required: false
          billingAccountId:
            type: string
            example: '0'
            required: false
          originSystem:
            type: string
            example: ''
            required: false
          installationAddressId:
            type: integer
            example: 2
            required: false
          activationDate:
            type: string
            example: ''
            required: false
          permanenceClause:
            type: string
            example: ''
            required: false
          previousConnectionNumber:
            type: integer
            example: 212121
            required: false
          salesforceId:
            type: integer
            example: 0
            required: false
          integrationId:
            type: string
            example: CS-1052382
            required: false
          serviceFeature:
            type: array
            items: {}
          attachments:
            type: array
            items: {}
          project:
            type: string
            example: ''
            required: false
          churnRisk:
            type: string
            example: ''
            required: false
          auxiliaryServices:
            type: array
            items: {}
          isRecurringPayment:
            type: boolean
            example: false
            required: false
          conditionedPromotions:
            type: array
            items: {}
          discount:
            type: integer
            example: 0
            required: false
          finalPrice:
            type: integer
            example: 0
            required: false
          migratedTechnologyChange:
            type: boolean
            example: false
            required: false
      serviceOrder:
        type: object
        properties:
          orderNumber:
            type: string
            example: OS-MDM-FIBRA-000636091
            required: false
          orderStatus:
            type: object
            properties:
              code:
                type: string
                example: '115'
                required: false
              description:
                type: string
                example: Consulta Reserva Inventario
                required: false
              date:
                type: datetime
                example: '2025-10-02T14:22:17.594Z'
                required: false
              retries:
                type: integer
                example: 0
                required: false
              exceptionCode:
                type: integer
                example: 1
                required: false
              exception:
                type: string
                example: >-
                  La tarea VCONDES del sistema no se ha completado
                  correctamente. Consulte al fiduciario del sistema.
                required: false
          services:
            type: array
            items:
              type: object
              properties:
                itemId:
                  type: string
                  example: '1'
                  required: false
                serviceId:
                  type: string
                  example: SR-7002656
                  required: false
                serviceClassId:
                  type: integer
                  example: 1100
                  required: false
                name:
                  type: string
                  example: INTERNET
                  required: false
                extended:
                  type: boolean
                  example: false
                  required: false
                serviceClass:
                  type: string
                  example: Broadband Service Class
                  required: false
                action:
                  type: string
                  example: ADD
                  required: false
                availability:
                  type: boolean
                  example: true
                  required: false
                scheduling:
                  type: boolean
                  example: true
                  required: false
                provisioning:
                  type: boolean
                  example: true
                  required: false
                childServices:
                  type: array
                  items:
                    type: object
                    properties:
                      itemId:
                        type: string
                        example: '2'
                        required: false
                      serviceId:
                        type: string
                        example: SR-7002657
                        required: false
                      serviceClassId:
                        type: integer
                        example: 2102
                        required: false
                      name:
                        type: string
                        example: IP DINÁMICA
                        required: false
                      extended:
                        type: boolean
                        example: false
                        required: false
                      serviceClass:
                        type: string
                        example: IP Dynamic Package Feature Class
                        required: false
                      action:
                        type: string
                        example: ADD
                        required: false
                      availability:
                        type: boolean
                        example: false
                        required: false
                      scheduling:
                        type: boolean
                        example: false
                        required: false
                      provisioning:
                        type: boolean
                        example: true
                        required: false
                      childServices:
                        type: array
                        items: {}
                      attributes:
                        type: array
                        items: {}
                      commit:
                        type: array
                        items: {}
                      rollback:
                        type: array
                        items: {}
                      configCode:
                        type: string
                        example: '22222220221'
                        required: false
                      isNew:
                        type: boolean
                        example: true
                        required: false
                      ports:
                        type: array
                        items: {}
                      serviceTypeId:
                        type: integer
                        example: 2
                        required: false
                      serviceSubtypeId:
                        type: integer
                        example: 22
                        required: false
                attributes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        example: FAMILIA
                        required: false
                      value:
                        type: string
                        example: HSI
                        required: false
                      type:
                        type: string
                        example: Agendamiento
                        required: false
                      class:
                        type: string
                        example: Catalogo
                        required: false
                      isNew:
                        type: boolean
                        example: true
                        required: false
                      display:
                        type: integer
                        example: 0
                        required: false
                commit:
                  type: array
                  items: {}
                rollback:
                  type: array
                  items: {}
                configCode:
                  type: string
                  example: '122229'
                  required: false
                isNew:
                  type: boolean
                  example: true
                  required: false
                ports:
                  type: array
                  items: {}
                serviceTypeId:
                  type: integer
                  example: 2
                  required: false
                serviceSubtypeId:
                  type: integer
                  example: 22
                  required: false
      scheduling:
        type: object
        properties:
          appointmentDate:
            type: datetime
            example: '2025-10-03T00:00:00.000Z'
            required: false
          appointmentSlot:
            type: string
            example: AM_2
            required: false
          actionType:
            type: string
            example: F.O. (HSI/VOIP)
            required: false
          workSkill:
            type: string
            example: MPPFTTH
            required: false
          duration:
            type: string
            example: '130'
            required: false
          installerCode:
            type: string
            example: ''
            required: false
          isEnriched:
            type: boolean
            example: false
            required: false
          hasSchedule:
            type: boolean
            example: true
            required: false
          activityId:
            type: string
            example: '8848731'
            required: false
          quotaList:
            type: array
            items: {}
      activationOrder:
        type: string
        example: ''
        required: false
      previousBillingAccount:
        type: string
        example: ''
        required: false
      billingAccount:
        type: object
        properties:
          id:
            type: object
            properties:
              oid:
                type: string
                example: '000000000000000000000000'
                required: false
          createdAt:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          updatedAt:
            type: datetime
            example: '2025-10-02T14:18:52.473Z'
            required: false
          updatedBy:
            type: string
            example: ''
            required: false
          createdBy:
            type: string
            example: ''
            required: false
          extractorUpdate:
            type: string
            example: ''
            required: false
          billingAccountId:
            type: string
            example: ''
            required: false
          basicCustomer:
            type: string
            example: ''
            required: false
          status:
            type: string
            example: ''
            required: false
          billingType:
            type: string
            example: Detallada
            required: false
          invoiceType:
            type: string
            example: Detallada
            required: false
          deliveryType:
            type: string
            example: Electronica
            required: false
          invoiceValue:
            type: integer
            example: 0
            required: false
          invoiceValueFormat:
            type: string
            example: ''
            required: false
          billingEmail:
            type: string
            example: notiene@etb.com.co
            required: false
          billingCycle:
            type: string
            example: ''
            required: false
          cutoffDay:
            type: integer
            example: 0
            required: false
          isDelinquent:
            type: boolean
            example: false
            required: false
          billingAddressId:
            type: integer
            example: 0
            required: false
          suspensionDate:
            type: string
            example: ''
            required: false
          chargingCycle:
            type: integer
            example: 0
            required: false
          chargingCycleCode:
            type: integer
            example: 0
            required: false
          serviceAccounts:
            type: string
            example: ''
            required: false
          billingCutoffDate:
            type: string
            example: ''
            required: false
      orderRequiresAvailability:
        type: boolean
        example: true
        required: false
      orderRequiresScheduling:
        type: boolean
        example: false
        required: false
      totalOrderPrice:
        type: string
        example: '99900'
        required: false
      customerAttachments:
        type: string
        example: ''
        required: false
      serviceAttachments:
        type: string
        example: ''
        required: false
      orderFeatures:
        type: array
        items:
          type: object
          properties:
            feature:
              type: string
              example: Envio_Notificacion
              required: false
            value:
              type: string
              example: '1'
              required: false
      others:
        type: object
        properties:
          contractDelivery:
            type: string
            example: Digital
            required: false
          salesUser:
            type: string
            example: ''
            required: false
          communicationMedium:
            type: string
            example: ''
            required: false
      isInPerson:
        type: boolean
        example: false
        required: false
      suggestedOffer:
        type: array
        items: {}
      reservation:
        type: string
        example: ''
        required: false
      attachments:
        type: object
        properties:
          service:
            type: array
            items:
              type: object
              properties:
                fileName:
                  type: string
                  example: ANEXO_DIGITAL_DEFINITIVO_SVA
                  required: false
                path:
                  type: string
                  example: 28564778/MDM-FIBRA-000636091/ANEXO_DIGITAL_DEFINITIVO_SVA
                  required: false
                description:
                  type: string
                  example: ANEXO_DIGITAL_DEFINITIVO_SVA
                  required: false
                size:
                  type: string
                  example: '236023'
                  required: false
                send:
                  type: boolean
                  example: true
                  required: false