#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: OK
    required: false
  subscriberProfile:
    type: object
    properties:
      serviceNumber:
        type: string
        example: '6015551234'
        required: false
      state:
        type: string
        example: A
        required: false
      activeDate:
        type: date-only
        example: '2026-01-15'
        required: false
      updateDate:
        type: date-only
        example: '2026-03-10'
        required: false
      accountCode:
        type: string
        example: '14000001234'
        required: false
      custCode:
        type: string
        example: '12345678'
        required: false
      customerName:
        type: string
        example: Juan Perez
        required: false
      preFlag:
        type: string
        example: 'N'
        required: false
      balList:
        type: array
        items:
          type: object
          properties:
            balId:
              type: string
              example: '1105'
              required: false
            acctResCode:
              type: string
              example: LOCAL_CURRENCY
              required: false
            acctResName:
              type: string
              example: Local Currency
              required: false
            unitType:
              type: string
              example: Currency
              required: false
            currencyType:
              type: string
              example: PSO
              required: false
            balance:
              type: string
              example: '-145000.000000'
              required: false
            effDate:
              type: string
              example: '2026-01-01 00:00:00'
              required: false
            expDate:
              type: string
              example: '2049-12-31 23:59:59'
              required: false
            updateDate:
              type: string
              example: '2026-03-10 13:56:44'
              required: false
            offerCode:
              type: string
              example: PLAN_POSTPAGO_50GB
              required: false
            offerName:
              type: string
              example: Plan Postpago 50GB
              required: false
      additionalOfferInstList:
        type: array
        items:
          type: object
          properties:
            offerCode:
              type: string
              example: VA_ROAMING_AMERICAS
              required: false
            offerName:
              type: string
              example: Roaming Americas
              required: false
            effDate:
              type: string
              example: '2026-02-01 00:00:00'
              required: false
            expDate:
              type: string
              example: '2026-08-01 23:59:59'
              required: false
            saleListPrice:
              type: string
              example: '0'
              required: false
            rentListPrice:
              type: string
              example: '15000'
              required: false
            offerInstAttrList:
              type: array
              items:
                type: object
                properties:
                  attrCode:
                    type: string
                    example: PLAN_CODE
                    required: false
                  attrName:
                    type: string
                    example: Subscription Plan
                    required: false
                  attrValue:
                    type: string
                    example: ROAMING_AMERICAS_MONTHLY
                    required: false
      prodInstAttrList:
        type: array
        items:
          type: object
          properties:
            attrCode:
              type: string
              example: PLAN_CODE
              required: false
            attrName:
              type: string
              example: Subscription Plan
              required: false
            attrValue:
              type: string
              example: PLAN_POSTPAGO_50GB
              required: false
