#%RAML 1.0 DataType
type: object
properties:
  code:
    type: string
    example: "200"
    required: false
  message:
    type: string
    example: "Cliente Validado Exitosamente"
    required: false
  result:
    type: object
    description: Validation object returned by LISIM
    required: false
