#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Orden registrada exitosamente
    required: false
  order:
    type: object
    properties:
      orderNumber:
        type: string
        example: MDM-FIBRA-551482
        required: false
      rulesApplied:
        type: array
        items:
          type: object
          properties:
            isValid:
              type: boolean
              example: false
              required: false
            mandatory:
              type: boolean
              example: true
              required: false
            detailedEvaluation:
              type: array
              items:
                type: object
                properties:
                  compared:
                    type: string
                    example: 1 > 0
                    required: false
                  description:
                    type: string
                    example: Validar que la consulta contiene resultados
                    required: false
                  mandatory:
                    type: boolean
                    example: true
                    required: false
                  result:
                    type: string
                    example: OK
                    required: false
            idRule:
              type: string
              example: REG-CLIENTE-001
              required: false
            responseRule:
              type: object
              properties:
                code:
                  type: string
                  example: '404'
                  required: false
                message:
                  type: string
                  example: No se encontraron coincidencias del cliente consultado
                  required: false
