http:
  private:
    port: "8093"

app.name: "resource-papi-services-v2"

autodiscovery: "20867936"

jsc-sapi:
  protocol: "HTTPS"
  port: "443"
  host: "32ba8410-20f7-46a5-9cd3-649cc099fec5.mock.pstmn.io"
  basePath: "/jsc/v1"
  availability:
    msisdn-path: "/msisdn/{msisdn}"
    sim-path: "/sim/{iccid}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

configurationTimeout:
  resource-papi-v2-listener: "62000"
  jsc-sapi:
    responseTimeout: "62000"
    connectionIdleTimeout: "60000"

anypoint.platform.client_id: ""
anypoint.platform.client_secret: ""
anypoint.platform.config.analytics.agent.enabled: "false"
