#%RAML 1.0 DataType
type: object
properties:
  documentType:
    description: Type of Document.
    type: string 
    example: "CC"
  documentNumber:
    description: Document number.
    type: string
    example: "1095846957"  
  planPackage:
    type: array
    items:
      properties:
        id:
          type: string
          description: Plan package id.
  suscriberId:
    description: Suscriber id.
    required: false
    type: string
    example: "147896325"  
  MSISDN:
    description: Mobile Station International Subscriber Directory Number.
    type: string
    example: "70222479"  
  ICCID:
    description: Globally unique serial number.
    type: string
    example: "12345678990123456987"  
  PAM:
    description: Billing Cycle.
    type: string
    example: "20"    
  integrationId:
    description: Unique identifier.
    type: string
    example: "35547892514"     
    