#%RAML 1.0 DataType
properties:
  destinations:
    type: array
    items:
      type: string
  message:
    type: string
    minLength: 1
    maxLength: 160
  category:
    type: string
    enum: ["OTP", "REGULATORY", "CAMPAIGN"]
  customSenderNumber:
    type: string
    required: false   