#%RAML 1.0 DataType
displayName: Subscription Replacement
type: object
properties:
  newMsisdn:
    type: string
    example: "3336025011"
  oldMsisdn:
    type: string
    example: "3457025012"  
  integrationId:
    type: string
    example: "MDM-MOV-0000000001-1"   
