#%RAML 1.0 DataType
properties:
  modalidad:
    type: string
    example: "pospago-prepago"
  integrationId:
    type: string
    example: "MDM-16235538"
    required: false
  packageId:
    type: string
    example: "TestETBMVNE2_changePlan"
  pam:
    type: string
    required: false
    example: "20"
  msisdn:
    type: string
    required: false
    example: "3057135005"