#%RAML 1.0 DataType
properties:
  externalID_Origen:
    description: Origin client identification type and number.
    type: string
    example: "CC202402211137"
  externalID_Destino:
    description: Target client identification type and number.
    type: string
    example: "CC45135489877"
  integration_id:
    description: .
    type: string
    example: "MDM-PRE-3058947808-92936"
    required: false
  msisdn:
    description: .
    type: string
    example: "MDM-PRE-3058947808-92936"
    required: false