#%RAML 1.0 DataType
displayName: Subscription Replacement
type: object
properties:
  msisdnOrig:
    type: string
    example: "3058966578"
  msisdnDest:
    type: string
    example: "3054126598"
  externalIDorig:
    type: string
    example: "MDM-PLTE-021957-1"  
  externalIDest:
    type: string
    example: "MDM-PLTE-056478-1"  
  monto:
    type: number
    example: 500
