#%RAML 1.0 DataType
properties:
  numeroConexion:
    type: string
    description: "Número de conexión del servicio o línea móvil"
  svas:
    type: array
    items:
      properties:
        id:
          type: string
          description: "Número de agrupación del servicio adicional adquirir"

example: !include ../../examples/request/post-api-svas.json