#%RAML 1.0 DataType

type: object
properties:
  methodCall: 
    type: object
    properties:
      methodName: 
        type: string
        enum: ["Refill", "Pkgaddon"]
        example: "Refill"
      member:
        type: object
        properties:
          refillProfileID:
            type: string
            example: "R000"
          action:
            type: string 
            example: "ADD"
          transactionAmount:
            type: string 
            example: "20000"
          refillType:
            type: string 
            example: "1"
          subscriberNumber:
            type: string 
            example: "3059464961"
          originTransactionID:
            type: string 
            example: "3278365642"
          originTimeStamp:
            type: string 
            example: "2024-07-24T17:28:49.589-05:00"
          transactionCurrency:
            type: string 
            example: "COP"
          originHostName:
            type: string 
            example: "xxsi848"