{
    "CantidadLineasActivasPre": 0,
    "CantidadLineasInactivasPre": 0,
    "CantidadLineasActivasPos": 1,
    "CantidadLineasInactivasPos": 0,
    "TotalLineasPre": 0,
    "TotalLineasPos": 1,
    "Respuesta": "true",
    "Mensaje": "Cliente valido. **Validar si el cliente tiene ordenes en curso para cancelar o retomar.",
    "Codigo": "000",
    "TotalLineasPreParametro": 3,
    "TotalLineasPosParametro": 5,
    "TotalLineasPreVuelo": 0,
    "TotalLineasPosVuelo": 0
}