#%RAML 1.0 DataType
displayName: CUN Cancellation Request
type: object

properties:
  typology:
    type: string
    example: "VTA"
    required: true
  incidentDate:
    type: string
    example: "16/05/2026 14:40:09"
    required: true
  reportDate:
    type: string
    example: "16/05/2026 14:45:00"
    required: true
  creatorUser:
    type: string
    example: "MDM"
    required: true
  date:
    type: string
    example: "16/05/2026 14:40:09"
    required: true
  user:
    type: string
    example: "MDM"
    required: true
  system:
    type: string
    example: "MDM"
    required: true
  customer:
    type: object
    required: true
    properties:
      identificationType:
        type: string
        description: Identification type associated with the main identification data of the request. Maps to TipoIdentificacion in CUN Center.
        example: "CC"
        required: true
      identification:
        type: string
        description: Identification number associated with identificationType. Maps to Identificacion in CUN Center.
        example: "12014261"
        required: true
      customerIdentificationType:
        type: string
        description: Customer identification type used for the additional customer identification required by CUN Center. Maps to TipoIdentificacionCl.
        example: "CC"
        required: true
      customerIdentification:
        type: string
        description: Customer identification number associated with customerIdentificationType. Maps to IdentificacionCl in CUN Center.
        example: "12014261"
        required: true
  service:
    type: object
    required: true
    properties:
      orderNumber:
        type: string
        example: "MDM-FIBRA-0006481213"
        required: true
      connectionNumber:
        type: string
        example: "1"
        required: true
examples:
  patchCun: !include ../../examples/request/patch-cun-cancellation.json
