#%RAML 1.0 DataType
displayName: CUN Assignment and Trace Request
type: object

properties:
  cunNumber:
    type: string
    example: "4347260001285770"
    required: false
  cunType:
    type: string
    example: "VTA"
    required: true
  date:
    type: string
    example: "16/05/2026 14:40:09"
    required: true
  cunAction:
    type: string
    enum: [ASIGNAR, RASTRO]
    example: "ASIGNAR"
    required: true
  user:
    type: string
    example: "MDM"
    required: true
  system:
    type: string
    example: "MDM"
    required: true
  customer:
    type: object
    required: true
    properties:
      identificationType:
        type: string
        example: "CC"
        required: true
      identification:
        type: string
        example: "12014261"
        required: true
  service:
    type: object
    required: true
    properties:
      orderNumber:
        type: string
        example: "MDM-FIBRA-0006481213"
        required: true
      connectionNumber:
        type: string
        example: "1"
        required: true

examples:
  postCunAssignment: !include ../../examples/request/post-cun-assignment.json
  postCunTrace: !include ../../examples/request/post-cun-trace.json