user: vpc-tools
pass: SomePass
beating: '1'
beating.host: '10.112.1.72'
beating.host.internal: 'mule-worker-internal-net-tools-etb-prod.us-e2.cloudhub.io'
beating.host.redundancy: '10.60.22.9'
beating.host.redundancy.2: '10.112.1.118'
waitTime: '20'
waitTime.internal: '20'