#%RAML 1.0 Trait
queryParameters:
  startRecord:
    type: string
    description: Indicates the first record to fetch
    required: true
    minLength: 1
    example:
      "0"
  maxLimit:
    type: string
    description: Indicates the limit amount of records to fetch
    required: true
    minLength: 1
    example:
      "100"