#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    required: false
  responseMessage:
    type: string
    required: false
  billingData:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          required: false
        billingCycle:
          type: string
          required: false
        city:
          type: string
          required: false
        email:
          type: string
          required: false
        billingAccount:
          type: string
          required: false
        department:
          type: string
          required: false
        address:
          type: string
          required: false
        status:
          type: string
          required: false
        billingCutoffDate:
          type: datetime
          example: '2022-05-12T19:21:55.190Z'
          required: false
        frequency:
          type: string
          required: false
        documentNumber:
          type: string
          required: false
        country:
          type: string
          required: false
        documentType:
          type: string
          required: false
        invoiceDeliveryType:
          type: string
          required: false
        invoiceType:
          type: string
          required: false
        creationUser:
          type: string
          required: false
        arrearsHeight:
          type: string
          required: false
        neighborhood:
          type: string
          required: false
        chargingCycle:
          type: string
          required: false
        chargingCycleCode:
          type: string
          required: false
        parentBillingAccount:
          type: string
          required: false
        stratum:
          type: string
          required: false
        updateDate:
          type: datetime
          example: '2022-05-12T19:21:55.190Z'
          required: false
        creationDate:
          type: datetime
          example: '2022-05-12T19:21:55.190Z'
          required: false
        modificationDate:
          type: datetime
          example: '2022-05-12T19:21:55.190Z'
          required: false
        billingAccountId:
          type: string
          required: false
        salesforceBillingAccountId:
          type: string
          required: false
        billingAddressId:
          type: integer
          required: false
        relatedOrderId:
          type: string
          required: false
        taxes:
          type: string
          required: false
        locality:
          type: string
          required: false
        market:
          type: string
          required: false
        modifiedMDM:
          type: string
          required: false
        recurrentPayment:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                required: false
              extractorUpdate:
                type: string
                required: false
              creationDate:
                type: datetime
                example: '2022-05-12T19:21:55.190Z'
                required: false
              modificationDate:
                type: datetime
                example: '2022-05-12T19:21:55.190Z'
                required: false
              paymentMethodId:
                type: string
                required: false
              isRecurrentPayment:
                type: boolean
                required: false
              creationUser:
                type: string
                required: false
              modificationUser:
                type: string
                required: false
        invoiceSupport:
          type: string
          required: false
        paymentType:
          type: string
          required: false
        modificationUser:
          type: string
          required: false
