#%RAML 1.0 DataType 
type: array
items:
  type: object
  properties:
    id:
      type: string
      example: ''
      required: false
    fullName:
      type: string
      example: ''
      required: false
    status:
      type: string
      example: active
      required: false
    contactMedium:
      type: array
      items:
        type: object
        properties:
          mediumType:
            type: string
            example: ''
            required: false
          value:
            type: string
            example: ''
            required: false
