#%RAML 1.0 DataType
properties:
  Bill:
    type: array
    items:
      type: object
      properties:
        number:
          type: string
          example: ""
        date:
          type: date-only
          example: 2022-08-01
        amount:
          type: string
          example: ""
        paymentDeadLine:
          type: date-only
          example: 2022-08-01
        customerName:
          type: string
          example: ""
        customerId:
          type: string
          example: ""