#%RAML 1.0 NamedExample
value:
  RETURN: 
    TYPE: S
    CODE: "000"
    MESSAGE: CA Creado000007434549
  CTRACPARTNERDETAIL: 
    item: 
      PARTNER: null
      EXVKO: a054y00000lClQhAAK
      ABWRE: null
      ABWMA: null
      EBVTY: null
      ABVTY: null
      EZAWE: null
      AZAWE: null
      IKEY: null
      MAHNV: null
      MANSP: null
      VKONV: null
      BEGRU: null
      COPRC: null
      KOFIZ__SD: null
      KTOKL: "0005"
      CCARD__ID: null
      DEF__REC: null
      DEF__REC__IND: null
      GPARV: null
      AUGRS__DEF: null
      SENDCONTROL__MA: null
      SENDCONTROL__GP: null
      MGRUP: null
      VERTYP: null
      VKPBZ: null
      TOGRU: null
      FDGRP: null
      TWAERS: null
      ZAHLKOND: null
      OPBUK: null
      LANGU: null
      POST__LOCK: null
      DUN__REASON: null
      QSSKZ__E: null
      QSSKZ__A: null
      EXTADDRESSNUMBER: a054y00000lClQhAAK