#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Su tipo de entrega de factura ha sido actualizado exitosamente
    required: false
  detail:
    type: object
    required: false
    properties:
      numberPqr:
        type: string
        example: ''
        required: false