#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  balance:
    type: object
    properties:
      availableCoin:
        type: string
        example: string
        required: false
      availableCoinValue:
        type: string
        example: number
        required: false
      promotionCoin:
        type: string
        example: string
        required: false
      promotionCoinValue:
        type: string
        example: number
        required: false
      detailed:
        type: object
        properties:
          detail:
            type: array
            items:
              type: object
              properties:
                sectionName:
                  type: string
                  example: string
                  required: false
                boxes:
                  type: array
                  items:
                    type: object
                    properties:
                      boxName:
                        type: string
                        example: string
                        required: false
                      groupName:
                        type: string
                        example: string
                        required: false
                      unitType:
                        type: string
                        example: string
                        required: false
                      available:
                        type: string
                        example: string
                        required: false
                      consumed:
                        type: string
                        example: string
                        required: false
                      provisioned:
                        type: string
                        example: string
                        required: false
                      offers:
                        type: array
                        items:
                          type: object
                          properties:
                            offerName:
                              type: string
                              example: string
                              required: false
                            available:
                              type: string
                              example: string
                              required: false
                            consumed:
                              type: string
                              example: string
                              required: false
                            provisioned:
                              type: string
                              example: string
                              required: false
                            expirationDate:
                              type: string
                              example: string
                              required: false
      summary:
        type: object
        properties:
          resource:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  example: string
                  required: false
                available:
                  type: string
                  example: string
                  required: false
                consumed:
                  type: string
                  example: string
                  required: false
                provisioned:
                  type: string
                  example: string
                  required: false
                expirationDate:
                  type: string
                  example: string
                  required: false
