#%RAML 1.0 NamedExample
value:
  status: 200
  code: "OK"
  response: 
    service_particulars:
      -
        connection_number: "6012482773"
        service_id: "25731023"
        feat_nm_ld: ""
        external_service_id: "CS-1378874-01"
        subscriber_id: "155968706"
        bill_run_State: "I"
        rate_plan_name: "Mundo Automaticos y Asistidos- Chain Hog"
        fd: ""
        lsp_name: ""
        billing_entity_id: "31"
        rate_plan_name_cupo: ""
        billable_parent_id: "155968706"
        error_description: "Cuenta no esta en facturacion"
        parent_id: "" 
    transaction_number: 14425