#%RAML 1.0 NamedExample
value:
  status: 404
  code: "NOT FOUND"
  response:
    service_particulars:
      -
        connection_number: "11223344"
        service_id: ""
        feat_nm_ld: ""
        external_service_id: ""
        error_code: "E0004"
        subscriber_id: ""
        bill_run_State: ""
        rate_plan_name: ""
        fd: ""
        lsp_name: ""
        billing_entity_id: ""
        rate_plan_name_cupo: ""
        billable_parent_id: ""
        error_description: "El número que está intentando consultar 11223344 no tiene asociada una cuenta en Revchain"
        parent_id: ""
    transaction_number: 14691