#%RAML 1.0 NamedExample
value:
  status: 500
  code: "INTERNAL_SERVER_ERROR"
  message:
    message: "HTTP POST on resource. Failed: internal server error (500)."
  messageServer: ""
  cause:
    -
      origin: "sisext-sapi-services"
      message: ""
