#%RAML 1.0 DataType
properties:
  GetBillsOutput:
    type: object
    properties:
      WSResponseHeader2:
        type: object
        properties:
          System: !include ../subDatatypes/Header.raml
          Service:
            type: object
            properties:
              status:
                type: string
                example: "FAIL"
              statusDetail:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: "BWENGINE-100029"
                  errorMessage:
                    type: string
                    example: "Activity timed out"
      Result:
        type: object
        properties:
          code: 
            type: string
            example: "BWENGINE-100029"
          description:
            type: string
            example: "Activity timed out"