#%RAML 1.0 DataType

properties: 
  wsConsultaSAAWResponse:
    type: object
    properties:
      wsResponseHeader:
        type: object
        properties:
          system:
            type: object
            properties:
              name:
                type: string
                example: "TIBCO"
              correlationId:
                type: string
                example: "MDM-MOV-2306254-OL-1-OL"
              processingServer:
                type: string
                example: "MDM"
          service:
            type: object
            properties:   
              status:
                type: string
                example: "PASS"
              responseDate: 
                type: string 
                example: "2022-04-24T08:34:57.22-05:00"  
      saawQueryResponse:
        type: object
        properties:
          result:
            type: object
            properties:
              contractAccount:
                type: string
                example: ""
              error:
                type: string
                example: ""
              claimStatus:
                type: string
                example: "Abierto"
              claimDate:
                type: string
                example: "2022-01-20"
              customerIdentification:
                type: string 
                example: "123456789"
              customerName: 
                type: string 
                example: "PRUEBA SANITY PS"
              claimantName:
                type: string 
                example: "PORTAFOLIO2 SUPERIOR2 CONTACTO"
              cunNumber:
                type: string 
                example: ""
              customerSegment:
                type: string 
                example: "MiPymes"
              claimValue: 
                type: string
                example: ""
          