#%RAML 1.0 DataType
properties:
  PortabilityCompensationOUT:
    type: object
    properties:
      WSResponseHeader2:
        type: object
        properties:
          System: !include ../subDatatypes/System.raml
          Service:
            type: object
            properties:
              status:
                type: string
                example: FAIL
              responseDate:
                type: datetime-only
                example: 2022-06-29T14:35:55
      PortabilityCompensationOutput:
        type: object
        properties:
          ResponseService:
            type: object
            properties:
              Id:
                type: string
                required: true
                example: "1"
              Result:
                type: string
                required: true 
                example: "0"
              DescriptionError:
                type: string
                example: "OK"
