#%RAML 1.0 DataType
properties:
  status:
    type: number
    example: 200
  code:
    type: string
    example: "OK"
  response:
        type: object
        properties:
          consultPQRResponse:
            type: object
            properties:
              wSResponseHeader:
                type: object
                properties:
                  system:
                    type: object
                    properties:
                      correlationID:
                        type: string
                        example: "4347180004009329"
                      source?:
                        type: string
                        example: "TIBCO"
                  service:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "PASS"
              ocs_spcConsultar_spcPQR_spcWS_Output:
                type: object
                properties:
                  error_spcCode:
                    type: string
                    example: "OK"
                  error_spcMessage:
                    type: string
                    example: "?"
                  object_spcId:
                    type: string
                    example: ""
                  process_spcInstance_spcId:
                    type: string
                    example: ""
                  listOfOcsServiceRequest:
                    type: array
                    items:
                      type: object
                      properties:
                        serviceRequest:
                          type: object
                          properties:
                            contactFirstName:
                              type: string
                              example: "PER SONA"
                            customerRefNumber:
                              type: string
                              example: "4347180004009329"
                            ocsAccountDocumentNumber:
                              type: string
                              example: "8546541564"
                            ocsAccountDocumentType:
                              type: string
                              example: "CC"
                            ocsContactDocumentNumber:
                              type: string
                              example: "2244668899"
                            ocsContactDocumentType:
                              type: string
                              example: "CC"
                            ocsAccountBillingNumber:
                              type: string
                              example: "15052863783"
                            openedDate:
                              type: string
                              example: "2022-07-26T23:10:27Z"
                            srId:
                              type: string
                              example: "MDM-PQR-4088670"
                            srNumber:
                              type: string
                              example: "MDM-PQR-4088670"
                            status:
                              type: nil
                              example: null
                            ocsAccountSegment:
                              type: string
                              example: "Hogares"
                            ocsCausal:
                              type: string
                              example: "ERROR FACTURA / COBRO O DESCUENTO INJUSTIFICADO"
                            ocsSymptom:
                              type: string
                              example: "CAMBIO PLAN NO CUMPLIDO"
                            ocsOrderNumber:
                              type: string
                              example: ""
                            ocsValClaimed:
                              type: string
                              example: "0"
                            activity:
                              type: nil
                              example: null
                            technology:
                              type: string
                              example: "FTTC"
                  siebel_spcOperation_spcObject_spcId:
                    type: string
                    example: ""