#%RAML 1.0 DataType
properties:
  outputSuspensionsReconnections:
    type: object
    properties:
      action:
        type: string
        example: "Locked"
      ACK:
        type: string
        example: "orderCompleteEvent"
      currentState:
        type: string
        example: "closed.completed"
      reason:
        type: string
        example: ""
      eventId:
        type: number
        example: 4035