#%RAML 1.0 DataType
properties:
  updateSLFServicesStatusOutput:
    type: object
    required: true
    properties:
      wsResponseHeader2:
        type: object
        required: true
        properties:
          system:
            type: object
            required: true
            properties:
              name:
                type: string
                required: true
                example: "Tibco"
              correlationID:
                type: string
                required: true
                example: "MDM-MOV-320831"
              processingServer:
                type: string
                required: true
                example: "Tibco MDM"
          service:
            type: object
            required: true
            properties:
              status:
                type: string
                required: true
                example: "PASS"
      outcomes:
        type: object
        required: true
        properties:
          outcome:
            type: object
            required: true
            properties:
              order:
                type: object
                required: true
                properties:
                  orderId:
                    type: string
                    required: true
                    example: ""
              response:
                type: object
                required: true
                properties:
                  code:
                    type: string
                    required: true
                    example: "3"
                  description:
                    type: string
                    required: true
                    example: "No se encontro un servicio asociado al numero de conexion y cliente. "
      result:
        type: object
        required: true
        properties:
          code:
            type: string
            required: true
            example: "SUCCESS"
          description:
            type: string
            required: true
            example: "SUCCESS"