https:
  host: "0.0.0.0"
  port: "443"
  
autodiscovery: "19948222"
  
support:
  protocol: "HTTP"
  host: "mule-worker-internal-support-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/support"
  cun:
    path: "/v1/cun"
  imei:
    path: "/v1/imei"
  contact:
    path: "/v1/contacts"
  customer:
    path: "/v1/customers"
  cases:
    path: "/v1/cases"
  digitalRecord:
    path: "/v1/digitalRecord"
  businessHours:
    path: "/v1/businessHours"
  asset:
    path: "/v1/asset"
  account:
    path: "/v1/account"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
remedy-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-remedy-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/remedy/v1"
  createIncident:
    path: "/incident"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1" 
  path: "/logs/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"
  
format-date: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
  
common-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/common/v1"
  path:
    logEntry: "/traceabilityLogs"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
configurationTimeout:
  common-sapi: "3000000"  
  security: "62000"
  support: "62000"
  remedy-sapi: "62000"
  audits-mongo-sapi: "62000"
  operations-papi: "62000"
  bot-sapi: "62000"
  azure-sapi: "62000"

operations-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/operations/v1"
  omnicanalidad:
    path: "/omnicanalidad/interaction"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
bot-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/api/saleOrder"
  basepathv2: "/api"
  encrypted:
    path: "/encripted/v1"
  endpoints:
    parameters:
      base-path: "/parameters"
      cities: "/cities/v1"
      departments: "/departments/v1"
      operators: "/operators/v1"
      businessdays: "/businessdays/v1"
      servicestypeportability: "/servicestypeportability/v1"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
azure-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-azure-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/azure/v1"
  path:
    keyVault: "/keyVault/{key}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"