#%RAML 1.0 DataType
properties:
  fileName:
    type: string
    required: true
    example: "000022024060632238-CC.pdf"
  filePath:
    type: string
    required: false
    example: ""
  fileContent:
    type: any
    required: true
    example: "Base64 file content"