#%RAML 1.0 DataType
displayName: Convertibility Logs Message Input
type: object
properties:
  convertibilityLogsMsgInput:
    required: true
    type: object
    properties:
      ConvertibilityLoggerIN:
        required: true
        type: object
        properties:
          OperationDate:
            required: false
            type: string | nil
          OrderNumber:
            required: false
            type: string | nil
          Operation:
            required: false
            type: string | nil
          PreviousValue:
            required: false
            type: string | nil
          UpdatedValue:
            required: false
            type: string | nil
          OperationResult:
            required: false
            type: string | nil
          User:
            required: false
            type: string | nil