#%RAML 1.0 DataType
displayName: CUN Assignment Request
type: object
properties:
  pqrType:
    type: string
    example: "PQR_TYPE"
    required: true
  pqrDate:
    type: string
    example: "2025-03-16"
    required: true
  system:
    type: string
    example: "SISTEMA"
    required: true
  orderNumber:
    type: string
    example: "ORD78965426"
    required: true
  identification:
    type: string
    example: "87654321"
    required: true
  identificationType:
    type: string
    example: "CC"
    required: true
  user:
    type: string
    example: "USUARIO_SISTEMA"
    required: true
  password?:
    type: string
    example: "USUARIO_PASS"
    required: false
example: !include ../../examples/request/post-cun-assignment-request.json