#%RAML 1.0 DataType
displayName: CUN History Request
type: object

properties:
  cunNumber:
    type: string
    example: "CUN986532"
    required: True
  identification:
    type: string
    example: "12014261"
    required: True
  connectionNumber:
    type: string
    example: "CONN54976"
    required: True
  identificationType:
    type: string
    example: "CC"
    required: True
  user:
    type: string
    example: "MDM"
    required: True
  password:
    type: string
    example: "USUARIO_PASS"
    required: false

examples:
  cunTrace: !include ../../examples/request/post-cun-history-request.json