#%RAML 1.0 DataType
displayName: Audit Logs Message Input
type: object
properties:
  auditLogsMsgInput:
    required: true
    type: object
    properties:
      auditLogIn:
        required: true
        type: object
        properties:
          logDate:
            required: false
            type: string
          sourceIP:
            required: false
            type: string
          user:
            required: false
            type: string
          sourcePortal:
            required: false
            type: string
          requestIdentifier:
            required: false
            type: string
          collectionName:
            required: false
            type: string
          serviceName:
            required: false
            type: string
          operation:
            required: false
            type: string
          requestDate:
            required: false
            type: string
          inputData:
            required: false
            type: any
          responseDate:
            required: false
            type: string
          outputData:
            required: false
            type: string
          observations:
            required: false
            type: string
example: !include ../../examples/request/post-auditLogs.raml