#%RAML 1.0 DataType 
type: object
properties:
  eventType:
    type: string
    example: ACTIVACION
    required: false
  ID_Sistema:
    type: string
    example: AIR
    required: false
  ID_Tpo_Xdr:
    type: string
    example: RECARGA
    required: false
  Fecha_Ini:
    type: string
    example: '20250524'
    required: false
  Hora_Ini:
    type: string
    example: '21:38:52'
    required: false
  Abonado_A:
    type: string
    example: '3058340776'
    required: false
  Abonado_B:
    type: string
    example: '3058705633'
    required: false
  Saldo_Ini:
    type: string
    example: '3'
    required: false
  Saldo_Fin:
    type: string
    example: '1003'
    required: false
  Valor_Nominal:
    type: string
    example: '1000'
    required: false
  Fch_Vigencia_Ini:
    type: string
    example: '20270519'
    required: false
  Hora_Vigencia_Ini:
    type: string
    example: '00:00:00'
    required: false
  Fch_Vigencia_Fin:
    type: string
    example: '20270524'
    required: false
  Hora_Vigencia_Fin:
    type: string
    example: '00:00:00'
    required: false
  Vigencia_Rec:
    type: string
    example: '165'
    required: false
  ID_Gestor_Rec:
    type: string
    example: '103'
    required: false
  Gestor_Rec:
    type: string
    example: '102'
    required: false
  Modalidad_pago:
    type: string
    example: PREPAGO
    required: false
  Modalidad_pago_abonado_a:
    type: string
    example: PREPAGO
    required: false
  Modalidad_pago_abonado_b:
    type: string
    example: CONTROL
    required: false
  ID_Medio_pago:
    type: string
    example: '192'
    required: false
  ID_Plan:
    type: string
    example: '102'
    required: false
  ID_Punto_Rec:
    type: string
    example: '5001'
    required: false
  ID_Canal_Rec:
    type: string
    example: '0'
    required: false
  Transaccion_Orig:
    type: string
    example: '474154'
    required: false
  Bolsa:
    type: string
    example: '66470'
    required: false
  Usuario:
    type: string
    example: ETBNEWUSER
    required: false
