#%RAML 1.0 DataType
type: object
properties: 
  status: 
    type: number
    example: 500
  code: 
    type: string
    example: "INTERNAL_ERROR"
  message: 
    type: object
    properties:
      message:
        type: string
        example: "NOK: El Identificador del caso no es valido"
  messageServer:
    type: string  
    example: ""
  cause: 
    type: array
    items:
      properties:
        origin:
          type: string
          example: "salesforce-sapi-services"
        message:
          type: string
          example: "org.mule.runtime.api.exception.DefaultMuleException"
