#%RAML 1.0 DataType
type:
  properties:
    sfilluminate:
      type: object
      properties:
        operacion:
          type: string
          required: true
        orden_om:
          type: string
          required: true
        orden_comercial:
          type: string
          required: true
        servicio:
          type: object
          properties:
            cuenta:
              type: string
              required: true
            external_service_id:
              type: string
              required: true
            fecha_inicio:
              type: string
              required: true
            nickname:
              type: string
              required: true
            servicio:
              type: string
              required: true
            plan:
              type: array
              items:
                type: object
                properties:
                  nombre: 
                    type: string
                    required: false
                  parametros:
                    type: array
                    items:
                      type: object
                      properties:
                        nombre:
                          type: string
                          required: true
                        valor:
                          type: string
                          required: false
            numeros_conexion:
              type: array
              required: false
              items:
                type: object
                properties:
                  connection_number_type_id:
                    type: string
                    required: true
                  connection_type_id:
                    type: string
                    required: true
                  numero_conexion:
                    type: string
                    required: true
example:
  !include ../../examples/requests/BillingProducts.json