#%RAML 1.0 DataType
type:
  properties:
    sfilluminate:
      type: object
      properties:
        operacion:
          type: string
          example: "servicio_av"
        orden_om:
          type: string
          example: "OM-12365478"
        orden_comercial:
          type: string
          example: "OC-12388552"
        cuenta:
          type: string
          example: "15052855047"
        external_service_id:
          type: string
          example: "AC-XXXX"
        fecha_inicio:
          type: string
          example: "dd/MM/yyyy"
        nickname:
          type: string
          example: "IGPON00001760"
        servicio:
          type: string
          example: "Datos Internet Dedicado GPON"
        plan:
          type: array
          items:
            type: object
            properties:
              nombre: 
                type: string
                example: "Plan Internet Dedicado GPON"
              parametros:
                type: array
                items:
                  type: object
                  properties:
                    nombre:
                      type: string
                      example: "Unidad de Capacidad"
                    valor:
                      type: string
                      example: ""
        numeros_conexion:
          type: object
          required: false
          properties:
            tipo_numero:
              type: string
              required: false
              example: "xxxx"
            numero_conexion:
              type: string
              required: false
              example: "IGPON00001760"


example:
  !include ../../examples/requests/CreateBillingOperationCompRvch.json