#%RAML 1.0 DataType
properties:
  Id?: string
  document_type?: string
  document_number?: string
  billing_account?: string
  parent_billing_account?: string
  state?: string
  market?: string
  frequency?: string
  creator_user?: string
  modifier_user?: string
  email?: string
  address?: string
  country?: string
  department?: string
  city?: string
  neighborhood?: string
  location?: string
  stratum?: string
  billing_cycle?: string
  long_time?: string
  invoice_type?: string
  invoice_support?: string
  type_delivery_invoice?: string
  charging_cycle?: string
  code_charging_cycle?: string
  date_cut_billing?: string
  taxes?: string
  modified_MDM?: string
  order_order_related?: string
  Salesforce_invoice_id?: string
  set_type?: string

example:
  !include ../../examples/requests/CreateBillingAccountExample.json