#%RAML 1.0 DataType
properties:
  "ext_market_typ":
    type: string
    example: "Company"
  "inv_day": 
    type: string
    example: "4"
  "conv_ind": 
    type: string
    example: "1"
  "sub_id": 
    type: string
    example: ""
  "geo_code1":
    type: string
    example: "11001000"
  "geo_code2":
    type: string
    example: "1"
  "geo_code3": 
    type: string | nil
    example: ""
  "order_type":
    type: string
    example: "VENTA"
  "ct_num": 
    type: string
    example: ""
  "fd": 
    type: string | nil
    example: ""
  "payment_prd":
    type: string
    example: "15"
  "billable":
    type: string
    example: "T"
  "bill_prnt_sub_id": 
    type: string
    example: ""

example:
  !include ../../examples/requests/CycleReq.json