#%RAML 1.0 DataType

uses:
  serviceProv-lib: ../../libraries/serviceProvisioning-library.raml
  
properties:
  wsInvokeServiceProvisioningIN:
    type: object
    required: true
    properties:
      services:
        type: serviceProv-lib.servicesType
        required: true
example: !include ../../examples/requests/invokeServiceProvisioning.json