#%RAML 1.0 DataType
type: object
properties:
    cuenta:
      type: string
      description: "cuenta de facturación del servicio"
      example: "15052889486"
      required: true
      minLength: 1
    id_servicio_externo:
      type: string
      description: "ID de servicio externo"
      example: "AC-1090291"
      required: true
      minLength: 1
    numero_conexion_origen:
      type: string | nil
      description: "Número de conexión a actualizar"
      example: "IPTX00012"
      required: false
    numero_conexion_destino:
      type: string | nil
      description: "Número de conexión a asignar"
      example: "IPTXD00012"
      required: false
    fecha_inicio:
      type: string
      description: "fecha en la que se deberá procesar la solicitud en revchain (formato DD-MM-YYYY)"
      example: "14-11-2023"
      required: true 
      minLength: 1
    features:
      type: array
      description: "Lista del objeto feature"
      required: false
      items:
        properties:
          feature_type_name:
            type: string
            description: "Nombre del feature del servicio en revchain"
            example: "Cargo Fijo IPTrunking"
            required: true
            minLength: 1
          parameters:
            type: array
            description: "Lista del objeto parameter"
            required: true
            items:
              properties:
                action:
                  type: string
                  description: "Acción a enviar a Revchain con respecto al procesamiento del parámetro"
                  example: "modify"
                  required: true
                  minLength: 1
                parameter_type_name:
                  type: string
                  description: "Nombre del parámetro a modificar en el servicio en revchain"
                  example: "CargoDS"
                  required: true
                  minLength: 1
                parameter_value:
                  type: string
                  description: "Valor del parámetro a asignar en el servicio en revchain"
                  example: "450000"
                  required: true
                  minLength: 1