#%RAML 1.0 DataType

properties:
  portalfija_data:
    type: object
    properties:
      compensacion_portabilidad:
        type: object
        properties:
          id:
            type: string
            example: "1"
            minLength: 1
          cuenta: 
            type: string  
            example: "15052853000"
            minLength: 1
          horas: 
            type: string
            example: "3.18" 
            minLength: 1

