#%RAML 1.0 DataType
properties:
  sfilluminate:
    type: object
    properties:
      cobro_retiro_anticipado:
        type: object
        properties:
          cuenta:
            type: number
            required: true
            example: 1234
          cod_fact:
            type: string
            required: true
            example: "cod_fact"
          valor:
            type: number
            required: true
            example: 123.2340
          descripcion:
            type: string
            required: true
            example: "trans_desc"
          fecha:
            type: string
            required: true
            description: format (dd-mm-yyyy)
            example: "20-01-2024"