#%RAML 1.0 DataType
properties:
  subscribers:
    type: object
    properties:
      subscriber_particulars:
        type: object
        properties:
          subscriber_data:
            type: object
            properties:
              action:
                type: string
                example: "modify"
              user:
                type: string
                example: "Tibco"
              subscriber_id:
                type: string
                example: "15052904684"
              first_name:
                type: string
                example: "CRISTIAM ALEJANDRO"
              last_name:
                type: string
                example: "FAJARDO"
              subscriber_name:
                type: string
                example: "CRISTIAM ALEJANDRO FAJARDO"
          billing_address_data:
            type: object
            properties:
              action:
                type: string
                example: "modify"
              bill_address1:
                type: string
                example: "CL 83 BIS 23 47 AP 102"
              bill_city:
                type: string
                example: "11001"
              bill_country_code:
                type: string
                example: "COL"
              bill_state_code:
                type: string
                example: "11"
          address_data:
            type: object
            properties:
              action:
                type: string
                example: "modify"
              address1:
                type: string
                example: "CL 83 BIS 23 47 AP 102"
              address_geo_code:
                type: string
                example: "11001"
              city:
                type: string
                example: "BOGOTA D.C."
              country_code:
                type: string
                example: "COL"
              state_code:
                type: string
                example: "11"
          email_data:
            type: object
            properties:
              action:
                type: string
                example: "add"
              email_address:
                type: string
                example: "nicolpineda1712@gmail.com"
              email_is_primary_flag:
                type: string
                example: "Y"
          invoice_method_data:
            type: object
            properties:
              action:
                type: string
                example: "modify"
              invoice_method_name:
                type: string
                example: "Cuentas LTE Detallada"
              invoice_delivery_name:
                type: string
                example: "Email"

example: !include ../../examples/requests/UpdateSubscriber.json