https:
  port: "8082"

configurationTimeout:
  suma: "30000"
  sisext: "62000"
  
process-suma:
  protocol: "HTTP"
  host: "procesossuma.app.etb.co"
  port: "80"
  path:
    validateLines: "/VentasMoviles/ValidacionCantidadLineas"
    notification: "/servicios/Notificacion/svcNotificacion.svc"
    
tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"
  
autodiscovery: "18736817"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
sisext-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/sisext/v1"
  documentHomologation: 
    path: "/document/validation"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"