#%RAML 1.0 DataType
type: object
displayName: Error
description: Standard error object defined by TM Forum Open APIs
properties:
  code:
    type: string
    required: true
    example: "400"
  reason:
    type: string
    required: true
    example: "Invalid field value"
  message:
    type: string
    required: true
    example: "The value provided for 'lifecycleStatus' is not valid."
  status:
    type: string
    required: true
    example: "Bad Request"
  referenceError:
    type: string
    required: false
    example: "ERR-PO-001"
  timestamp:
    type: datetime
    required: false
    example: "2024-05-30T13:25:48Z"
  "@type":
    type: string
    required: false
    example: "Error"
    description: The type of the error object
  "@baseType":
    type: string
    required: false
    example: "Entity"
    description: The base type of this entity
  "@schemaLocation":
    type: string
    required: false
    example: "https://mydomain.com/schema/Error"
    description: A link to the JSON schema describing this object
