#%RAML 1.0 DataType
displayName: Georeference Response
type: object
properties:
  GetGeoreferenceOut:
    type: object
    properties:
      Result:
        type: object
        properties:
          status:
            type: string
            example: "PASS"
          messageCode:
            type: string
            example: "OK"
          descripcion:
            type: string
            required: false
      Address:
        type: object
        properties:
          EstadoGeo:
            type: string
            example: "A"
          CodigoDireccion:
            type: number
            example: 612802304578775600
          Latitud:
            type: number
            example: 4.734444173
          Longitud:
            type: number
            example: -74.01456934
          Estrato:
            type: integer
            example: 1
          CodigoLote:
            type: integer
            example: 27
          Destino:
            type: integer
            example: 1
          Chip:
            type: string
            example: "AAA0225JWHY"
          Barrio:
            type: integer
            example: 8543
          Localidad:
            type: integer
            example: 1
          TipoDistancia:
            type: string
            example: "AE"

