http:
  private:
    port: "8091"
  
configurationTimeout:
  tipologyRVC: "60000"
  compRvch: "60000"
  revchain: "60000"
  self-call: "60000"
  portabilityCompensationIntf: "60000"

revchain-client:
  protocol: "HTTP"
  host: "10.112.71.62"
  port: "7003"
  basePath: "/SupplanterWS"
  path:
    subscriber: "/SupplanterService"
  factory: "weblogic.jndi.WLInitialContextFactory"
  contextUrl: "t3://10.112.71.14:9001"
  jndiName: "ejb/CreateSubscriber#com.etb.process.UtilDataCreateSubscriber.UtilDataCreateSubscriberXMLSvcRemote"
  username: "newtibco"
  password: "J4lF1br4"
  
revchain-PortabilityCompensationIntf:
  protocol: "HTTP"
  host: ""
  port: "10003"
  basePath: "PortalFijaWS"
  path: "PortalFijaService"  
  
comp-rvch-client:
  protocol: "HTTP"
  host: ""
  port: "10003"
  basePath: "/FactCorpWS"
  path:
    factCorp: "/FactCorpService" 

tipologyRVC:
  protocol: "HTTP"
  host: "10.112.71.62"
  port: "7003"
  basePath: "/WSPerfilFact"
  path:
    perfilFact: "/WSPerfilFact" 

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
serviceProvisioning:
  doctype: "<!DOCTYPE services SYSTEM './dtd2/ServiceProvisioning.dtd'>"
  factory: "weblogic.jndi.WLInitialContextFactory"
  contextUrl: "t3://appjalprd03.etb.com.co:8001"
  jndiName: "process.ProvisionSubscriberXMLHome"
  username: "newtibco"
  password: "asegura2013_1"
  
self-call-revchain:
  protocol: "HTTP"
  host: "mule-worker-internal-revchain-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/revchain/v1"
  path:
    invokeServiceProvisioning: "/billing/provisioning/services"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

autodiscovery: "18003999"

revchain-db:
  host: "10.113.1.93"
  port: "1523"
  user: "***"
  password: "***"
  serviceName: "REVPQA1"
  maximumPoolSize: "150"
  connectionTimeout: "10000"
  jdbcUrl: "jdbc:oracle:thin:@${revchain-db.host}:${revchain-db.port}:${revchain-db.serviceName}"
