#%RAML 1.0 NamedExample
logMsgOutput:
  wsResponseHeader2:
    system:
      name: "MULESOFT"
      correlationID: "?"
      processingServer: "MULESOFT"
    service:
      status: "PASS"
      responseDate: "2022-08-20T10:05:00"
  logOut:
    result: "OK"
    description: "Proceso Ejecutado Exitosamente"