#APP CONFIG#
app:
  credentials:
    clientId: "![+K8Uxj7URPZ9w5twdvJN6YmweH4a11lMeIhsUwCQC6wqwUfuvrJp7A==]"
    clientSecret: "![cYwDisCgH12RmJEKKsGto4W+Lrc+yfhaKam2QLMpuCHU/Obmn+mY8A==]"

##TLS CONFIG##
tls:
  keyPassword: "![7fPh5MFJDR+viNgRr8/1ow==]"
  password: "![7fPh5MFJDR+viNgRr8/1ow==]"