envName: "Local"

app:
  apiId: "20494982"
  listener:
    host: "localhost"
    port: "8092"
    basePath: ""
  
payu:
  accountId: "512321"
  merchantId: "508029"
  apiLogin: "pRRXKOl8ikMmt9u"
  apiKey: "4Vj8eK4rloUd272L48hsrarnUA"
  publicKey: ""
  endpoint: "sandbox.api.payulatam.com"
  language: "es"
  test: "true"
  paymentMethod: "PSE"
  paymentCountry: "CO"
  type: "AUTHORIZATION_AND_CAPTURE"