#%RAML 1.0 DataType
properties:
  authorizations_response:
    type: array
    items:
      type: object
      properties:
        urn:
          type: string
          example: "urn:tve:ucinema"
        access:
          type: string
          example: "true"
        max_rating:
          type: string
          example: "G"
        ttl:
          type: string
          example: "3600"

example: !include ../../examples/response/authorizationTV-response.json