# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
# --- Zsmart HTTP Requester ---
zsmart:
  protocol: "HTTP"
  host: ""
  port: ""
  basePath: "/api"
  billing:
    path: "/rest"
    post:
      method: "POST"