# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
# --- Example Backend HTTP Requester ---
zsmart:
  protocol: "HTTPS"
  host: "prod-backend.example.com"
  port: "443"
  basePath: "/api/v1"
  accountUpdate:
    path: "/accountUpdate"
    patch:
      method: "PATCH"
  addCharge:
    path: "/addCharge"
    patch:
      method: "PATCH"
  additionSva:
    path: "/additionSva"
    patch:
      method: "PATCH"
  addressChange:
    path: "/addressChange"
    patch:
      method: "PATCH"
  billingCycleChange:
    path: "/billingCycleChange"
    patch:
      method: "PATCH"
  customerUpdate:
    path: "/customerUpdate"
    patch:
      method: "PATCH"
  numberChange:
    path: "/numberChange"
    patch:
      method: "PATCH"
  ownershipTransfer:
    path: "/ownershipTransfer"
    patch:
      method: "PATCH"
  planChange:
    path: "/planChange"
    patch:
      method: "PATCH"
  removalSva:
    path: "/removalSva"
    patch:
      method: "PATCH"
  restoration:
    path: "/restoration"
    patch:
      method: "PATCH"
  stratumChange:
    path: "/stratumChange"
    patch:
      method: "PATCH"
  suspension:
    path: "/suspension"
    patch:
      method: "PATCH"
  voluntaryCancellation:
    path: "/voluntaryCancellation"
    patch:
      method: "PATCH"
  sale:
    path: "/sale"
    post:
      method: "POST"