#%RAML 1.0 SecurityScheme
type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      description: |
        Used to send a valid OAuth 2 access token. Do not use
        with the "access_token" query string parameter.
      type: string
  queryParameters:
    access_token:
      description: |
        Used to send a valid OAuth 2 access token. Do not use together with
        the "Authorization" header
    type: string
  responses:
    400:
          description: Invalid token.
    401:
      description: |
        Unauthorized or Connection error when connecting to the authorization server.
    403:
      description: |
        Forbidden, invalid client application credentials.
    500:
      description: |
        Bad response from authorization server, or WSDL SOAP Fault error.
settings:
  authorizationUri: https://oauth-etb-security-services.us-e2.cloudhub.io/security/v1/validate
  accessTokenUri: https://oauth-etb-security-services.us-e2.cloudhub.io/security/v1/access_token
  authorizationGrants: [ client_credentials, authorization_code, password ]
  scopes:
        - service.write
        - service.read
    