#%RAML 1.0 NamedExample
value:
  WSRequestHeader:
    System:
      correlationID: "1-QBH6EM7"
      processingServer: ""
    Property:
      value: ""
      name: ""
  RegistroPositivo:
    sUsuarioETB: "BRAYCASC"
    sIMEI: "354834097350775"
    sMSISDN: "3057447900"
    sNombrePropietario: "DAIRON ALONSO  SUAREZ  FERNANDEZ"
    sDireccionPropietario: "Bogota"
    iTipoUsuarioPropietario: "1"
    sTipoDocPropietario: "CC"
    sDocPropietario: "79910648"
    sTelContactoPropietario: "3057447900"
    sNombreContacto: ""
    sDireccionContacto: ""
    iTipoUsuarioAutorizado: "1"
    sTipoDoAutorizado: ""
    sDocAutorizado: ""
    sTelContactoAutorizado: ""
