#%RAML 1.0 Library
usage: Library that contains most common resource and traits, use them for consistency

types:
  CycleResponse: !include ../datatypes/responses/AccountCycleResponse.raml

resourceTypes:
  collection: !include ../resourceTypes/collection.raml
  member: !include ../resourceTypes/member.raml

traits:
  security-clientId-trait: !include ../exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  RequestHeaders: !include ../exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.5/tibcorequestheaders.raml