#%RAML 1.0
title: gestor-sapi-services
baseUri: http://gestor-sapi-services-{env}.us-e2.cloudhub.io/gestor
version: 1

mediaType: 
  - application/json

protocols:
  - HTTP

traits:
    security-client-id: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
    tibcoHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.5/tibcorequestheaders.raml

/v1:
  /inventory:
    /idTransaccion/{idTransaccion}:
      get:
        is:
          - security-client-id
          - tibcoHeaders
        displayName: Consult inventory
        description: Consult inventory
        queryParameters:
          idServicio:
            description: Id service
            type: string
            example: CAV30CI1100924
            required: true
        responses:
          201:
            body:
              application/json:
                type: !include datatypes/response/get-inventory200Response.raml
          404:
            body:
              application/json:
                type: !include datatypes/response/get-inventory404Response.raml
            