#%RAML 1.0 NamedExample
value:
  updateOrderCharacteristics:
    characteristics:
      -
        orderCharacteristic: 
          characteristic: "FECHA_SOLUCION_QUIEBRE_REMEDY"
          value: "5/20/2022 8:24:29 AM"
      -
        orderCharacteristic:
          characteristic: "SOLUCION_QUIEBRE_REMEDY"
          value: "CAMBIO DE TECNICO"
      -
        orderCharacteristic:
          characteristic: "EDO_ORDEN_QUIEBRE_REMEDY"
          value: "Terminado"
      -
        orderCharacteristic:
          characteristic: "MOTIVO QUIEBRE"
          value: "SOLUCIONADO"
      -
        orderCharacteristic: 
          characteristic: "DOCUMENTACION REQUERIMIENTO"
          value: "CAMBIO DE TECNICO"

    user: ""