#%RAML 1.0 DataType
properties:
  access_token:
    type: string
    example: 00D8C0000004dAf!ARQAQMyjmZcuEvTPduJJdOsCIo1JfS.bG1aBQY5lB7zoqSUVvlTRofoplwbMuCDZgkKr5hLzk3YQJCh5ZMQF_1PLiCi9Ec0A
  instance_url:
    type: string
    example: https://etb--uat.my.salesforce.com
  id:
    type: string
    example: https://test.salesforce.com/id/00D8C0000004dAfUAI/0058C000000XmHXQA0
  token_type:
    type: string
    example: Bearer
  issued_at:
    type: number
    example: 1657650081739
  signature:
    type: string
    example: no/cB0mtZsM7IR6xD6CvkqO6bdeN/7HcGyCwqExjMVA=