#%RAML 1.0 DataType
type: object
xml:
  name: Envelope
  wrapped: true
properties:
  Header:
    type: nil
    required: false
  Body:
    type: object
    properties:
      doConsultarNumerosDisponiblesResponse:
        type: object
        properties:
          RespuestaPeticionNumerosDisponibles:
            type: object
            properties:
              Numeros:
                type: array
                required: true
                items:
                  properties:
                    Numero:
                      type: string
                      required: true
              Resultado:
                type: object
                required: true
                properties:
                  Resultado:
                    type: string
                    required: true
                  CodigoErrorResultado:
                    type: string
                    required: false
                  DescripcionErrorResultado:
                    type: string
                    required: false