#%RAML 1.0 DataType
type: object
displayName: coverageGIS
properties:
  GetCoverageSMOut:
    type: object
    properties:
      Result: 
        type: object
        properties:
          status:
            description: Status
            type: string
            required: true
          code:
            description: code of output
            type: string
            required: true
          description:
            description: code of output
            type: string
            required: false
      body:
        type: object
        properties:
          Tecnologia:
            type: array
            items:
              type: object
              properties:
                Tipo:
                  description: Type of technology
                  type: string
                  required: true
                Propietario:
                  description: Owner
                  type: string
                  required: true
                EstratoPredominante:
                  description: Stratum Predominant 
                  type: string
                  required: true
                TipoCobertura:
                  description: Type of coverage
                  type: string
                  required: true
                Cobertura:
                  description: Coverage
                  type: string
                  required: true
                NombreCobertura:
                  description: Name of coverage
                  type: string
                  required: true
                TipoArea:
                  description: Type of Area
                  type: string
                  required: true
                Area:
                  description: Area of coverage
                  type: string
                  required: true 
                MigracionOLT:
                  type: string
                  required: true 
                NombreOLT:
                  type: string
                  required: true 
example:
  !include ../../examples/response/coverageGIS.raml