#%RAML 1.0 DataType
type: object
properties:
  System:
    properties:
      correlationID:
        type: string
      processingServer:
        type: string
      responseDate:
        type: datetime
  Response:
    properties:
      Codigo:
        type: string
      Mensaje:
        type: string
      Tipo:
        type: string