#%RAML 1.0 DataType
properties:
  id?: string
  estado?: 
    type: object
    properties:
      codigo?: string
      nombre: string
  fecha-creacion?:
    type: object
    properties:
      dia: string
      franja?: string
      anio: string
      mes:
        type: object
        properties:
          numero: string
          nombre: string
      hora?: string
  fecha-visita?:
    type: object
    properties:
      dia: string
      franja?: string
      anio: string
      mes:
        type: object
        properties:
          numero: string
          nombre: string
      hora?: string