#%RAML 1.0 DataType
type: object
displayName: normalizedAddress
properties:
  NormalizedAddressResponse:
    type: object
    properties:
      NormalizedAddress:
        type: string
        minLength: 1
        required: true
      CUNU:
        type: string
        required: false

example: !include ../../examples/response/normalizedAddress.json