#%RAML 1.0 DataType
properties:
  codigo:
    type: string
    example: "200"
  descripcionRespuesta:
    type: string
    example: "Respuesta AZSign"
  numeroAcuerdo:
    type: string
    example: "Id del acuerdo creado por AZSIGN"