#%RAML 1.0
title: portal-fija-sapi-services
version: 1
protocols:
  - HTTP
baseUri: http://portal-fija-sapi-services.us-e2.cloudhub.io/fija
uses:
  portal-fija-sapi-services: /libraries/portal-fija-services-library.raml
mediaType: 
  - application/json

/v1:
  /accounts:
    /{account_id}:
      uriParameters:
        account_id:
          type: string
          maxLength: 40
          minLength: 1
          required: true
          pattern: '[a-zA-Z0-9]*'
      /cycles:
        description: Obtains the billing cycle of the account from Revchain.
        get:
        type: 
          portal-fija-sapi-services.member
  /hierarchy_account:
    get:
      is: [portal-fija-sapi-services.security-clientId-trait, portal-fija-sapi-services.RequestHeaders]
      displayName: Obtener un número (jerarquía de cuentas)
      description: Obtener la jerarquía de cuentas -> obtener un número
      queryParameters:
        source_account:
          type: string
          required: true
          example: "15052863470"
        external_serviceId:
          type: string
          required: true
          example: "AC-1001795"
        destination_account:
          type: string
          required: true
          example: "15052855047"
      responses:
          200:
            body:
              application/json:
                type: !include /datatypes/responses/get-HierarchyAccount200Response.raml
          500:
            body:
              application/json:
                type: !include /datatypes/responses/get-HierarchyAccount500Response.raml
  /health_check:
    get:
      is: [portal-fija-sapi-services.security-clientId-trait, portal-fija-sapi-services.RequestHeaders]
      displayName: Health Check
      description: Check the connectivity of calls
      responses:
        200:
          description: Status of legacies and dependencies
          body:
            application/json:
              type: !include datatypes/responses/healthcheckobjectresponse.raml
              example: !include examples/responses/get_healthcheck_response.json
  /agreement:
    /getPermanenceClause:
        get:
          is: [portal-fija-sapi-services.security-clientId-trait, portal-fija-sapi-services.RequestHeaders]
          displayName: Retrieve Agreement Information
          description: Retrieves contract details including start date, end date, and minimum commitment clause. 
          queryParameters:
            cuentaPadre:
              type: string
              example: "15052963375"
              description: "Identificador de la cuenta padre asociada a la cláusula de permanencia."
              required: false
            integrationId:
              type: string
              example: "CS-1052455"
              description: "Identificador de integración asociado al proceso o transacción."
              required: false
            activeDate:
              type: string
              example: "09/10/2025"
              description: "Fecha activa o de vigencia para consultar la cláusula de permanencia (formato DD/MM/YYYY)."
              required: false
          responses:
                200:
                  body:
                    application/json:
                      type: !include /datatypes/responses/get-permanenceClause.raml
                      example: !include /examples/responses/get-permanenceClause.json

