#%RAML 1.0 DataType

properties:
  status:
    type: number
    example: 404
  code:
    type: string
    example: "NOT_FOUND"
  message:
    type: object
    properties:
      message:
        type: string
        example: "Data not found"
        required: false
  messageServer:
    type: string
    example: ""
    required: false
  cause:
    type: array
    items:
      properties:
        origin:
          type: string
          required: false
          example: "service-papi-services-qa"
        message:
          type: string
          required: false
          example: "org.mule.module.apikit.exception.NotFoundException"