#%RAML 1.0 DataType
properties:
  destination:
    type: string
    required: true
  status:
    type: string
    enum: [ success, error ]
    required: true
  messageId:
    type: string
    description: UUID del mensaje
    required: true
  details:
    type: string
    required: true   