#%RAML 1.0 Library
usage:
types:
  rejectedNumerationType:
    type: object
    properties:
      NumeracionRechazada:
        type: object
        properties:
          Numero:
            type: string
            minLength: 1
            required: true
          CodigosRechazo:
            type: array
            required: true
            items:
              properties:
                CodigoRechazo:
                  type: string
                  minLength: 1
                  required: true
          DocumentoDC:
            type: string
            minLength: 1
            required: false
          DocumentoFC:
            type: string
            minLength: 1
            required: false
          DocumentoFR:
            type: string
            minLength: 1
            required: false
          DocumentoUO:
            type: string
            minLength: 1
            required: false
