#%RAML 1.0 DataType
type: object
properties:
  Id:
    type: string | nil
    required: false
  lstObjetosHijosRelacionados:
    type: object
    required: false
    properties:      
      ObjetosHijosRelacionados:
        type: array
        items:
          properties:                        
            Id:
              type: string | nil
              required: false
            lstParametros:
              type: object
              required: false
              properties:
                Keys:
                  type: array
                  items:
                    properties:                                
                      Campo:
                        type: string | nil
                        required: false
                      Valor:
                        type: string | nil
                        required: false
            NombreRelacion:
              type: string | nil
              required: false
  lstParametros:
    type: object   
    required: false
    properties:
      Keys:
        type: array
        items: 
          properties:                              
            Campo:
              type: string | nil
              required: false
            Valor:
              type: string | nil
              required: false
  NombreObjeto:
    type: string | nil
    required: false

example: !include ../../examples/request/updateObjectSFExample.raml