#%RAML 1.0 DataType
properties:
  updateProperties:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          example: "grupo_remedy"
        value:
          type: string
          example: "APROVISIONAMIENTO GESTION NPLAY"