<soapenv:Envelope 
xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:tem="http://tempuri.org/" xmlns:por="http://schemas.datacontract.org/2004/07/PortalFibra.Negocio.Manejadores">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:EnvioNotificacionTipoEntidad>
         <tem:envio>
            <por:datoEnvio>573102452756</por:datoEnvio>
            <por:idEntidad>6016933656</por:idEntidad>
            <por:reintento>false</por:reintento>
            <por:tipoEntidad>Numero_Conexion</por:tipoEntidad>
            <por:tipoNotificacion>Exp_Tec_Cambio_Clave_Wifi</por:tipoNotificacion>
         </tem:envio>
      </tem:EnvioNotificacionTipoEntidad>
   </soapenv:Body>
</soapenv:Envelope>