<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:por="http://schemas.datacontract.org/2004/07/PortalFibra.Negocio.Manejadores">
	<soapenv:Header/>
	<soapenv:Body>
		<tem:EnvioNotificacionResponsys>
			<tem:envio>
				<por:atributos>
					<por:atributos>
						<por:nombre>MOBILE_NUMBER_</por:nombre>
						<por:valor>573105330192</por:valor>
					</por:atributos>
					<por:atributos>
						<por:nombre>NOMBRE</por:nombre>
						<por:valor>LEANDRO ALBERTO GARCIA SILVA</por:valor>
					</por:atributos>
					<por:atributos>
						<por:nombre>CEDULA</por:nombre>
						<por:valor>9774689</por:valor>
					</por:atributos>
					<por:atributos>
						<por:nombre>CUENTA</por:nombre>
						<por:valor>12054347703</por:valor>
					</por:atributos>
				</por:atributos>
				<por:nombreLista>Automaticas2</por:nombreLista>
				<por:nombreObjeto>Automaticas2</por:nombreObjeto>
				<por:tipoNotificacion>EnvioLinkPagos</por:tipoNotificacion>
			</tem:envio>
		</tem:EnvioNotificacionResponsys>
	</soapenv:Body>
</soapenv:Envelope>