#%RAML 1.0
title: product-papi-services
version: "2"
protocols:
  - HTTP
mediaType:
  - application/json
baseUri: https://product-papi-services-v2-{env}.us-e2.cloudhub.io/{version}
description: API de productos PAPI v2 (recarga de saldo y recarga de paquete).

/usageConsumptionReport:
  post:
    displayName: Recarga de saldo (Usage Consumption Report)
    description: Recarga de saldo en línea.
    body:
      application/json:
        type: !include datatypes/request/usageConsumptionReport.raml
    responses:
      200:
        body:
          application/json:
            type: !include datatypes/response/usageConsumptionReport.raml
      404:
        body:
          application/json:
            type: !include datatypes/response/notFoundError.raml
      500:
        body:
          application/json:
            type: !include datatypes/response/internalServerError.raml
/usageConsumption:
  post:
    displayName: Recarga de paquete (Usage Consumption)
    description: Recarga de paquete(s) en línea.
    body:
      application/json:
        type: !include datatypes/request/usageConsumption.raml
    responses:
      200:
        body:
          application/json:
            type: !include datatypes/response/usageConsumption.raml
      404:
        body:
          application/json:
            type: !include datatypes/response/notFoundError.raml
      500:
        body:
          application/json:
            type: !include datatypes/response/internalServerError.raml
/subscription:
  /{msisdn}:
    uriParameters:
      msisdn:
        type: string
        description: Número MSISDN a consultar.
        example: "573001234567"
    get:
      displayName: Consultar suscripción por MSISDN
      description: Consulta suscripción en JSC (`/jsc/v1/subscription?msisdn=`) y devuelve solo los campos acordados (claves en inglés).
      queryParameters:
        ORIGIN:
          type: string
          required: false
          description: Canal u origen de la petición.
          example: "CATALOGO"
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/get-subscription-by-msisdn.raml
              example: !include examples/response/get-subscription-by-msisdn-200.json
        404:
          body:
            application/json:
              type: !include datatypes/response/notFoundError.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/internalServerError.raml
