#%RAML 1.0 DataType
properties:
  SuscriberId: string
  DocumentNumber: string
  DocumentType: string
  FullName: string
  FirstName?: string
  LastName: string
  AccountIdentificationID: string
  AccountDocumentNumber: string
  AccountName: string
  AccountTypeCode: string
  IdentificationID: string
  OrderSubType: string
  SourceSystem: string
  ClaimMethod: string
  ExternalAddressNumber: string
  IndustrialSector?: string
  Segment: string
  SubSegment: string
  EconomicActivity: string
  Country: string
  City: string
  Street: string
  Telephone: string
  InvoicingCycle: string
  DaneCode: string
  IsBilling: string

example:
  !include ../../examples/requests/CreateRMCAAccountInputExample.raml