#%RAML 1.0 DataType
properties:
  Header:
    type: !include subdatatypes/Header.raml
  Body:
    type: object
    properties:
      Set_BillingAccount:
        type: object
        properties:
          WSRequestHeader:
            type: !include subdatatypes/WSRequestHeader.raml
          WSRequestBody:
            type: !include subdatatypes/WSRequestBody.raml

example:
  !include ../../examples/requests/CreateMdmAccountExample.raml