#%RAML 1.0 DataType
properties:
  OrderFulfilment?: 
    type: !include subdatatypes/ProcessSalesOrderFulfilmentType.raml
  BillingProcess?:
    type: !include subdatatypes/CreateBillingAccountType.raml
  ConservationNumber?:
    type: !include subdatatypes/ConservationNumberType.raml
example:
  !include ../../examples/requests/CreateRMCAAccountInputExample.raml