#%RAML 1.0 DataType
properties:
  UpdateAccountDataSystemsBody:
    type: object
    properties:
      "SubscriberId": 
        type: string
        example: "15052904684"
      "FirstName":  
        type: string
        example: "CRISTIAM ALEJANDRO"
      "LastName":  
        type: string
        example: "FAJARDO"
      "SubscriberName":  
        type: string
        example: "CRISTIAM ALEJANDRO FAJARDO"
      "EmailAddress":  
        type: string
        example: "nicolpineda1712@gmail.com"
      "EmailIsPrimaryFlag":  
        type: string
        example: "Y"
      "BillAddress":  
        type: string
        example: "CL 83 BIS 23 47 AP 102"
      "AddressGeoCode":  
        type: string
        example: "11001"
      "City":  
        type: string
        example: "BOGOTA D.C."
      "BillStateCode":  
        type: string
        example: "11"
      "InvoiceDeliveryType":  
        type: string
        example: "Email"
      "User":  
        type: string
        example: "Tibco" 
  "ProcessData":
    type: object
    properties:
      "ProcessingType":  
        type: string
        example: "Reenvio"
      "RVC":  
        type: string
        example: "1"
      "RMCA":  
        type: string
        example: "1"
      "MDM":  
        type: string
        example: "1"

example:
  !include ../../examples/requests/patch-updateAccountData.json
