#%RAML 1.0 DataType
properties:
  WsRequestBody:
    properties:
      orden_om:
        type: string
        example: OM-12365478
      orden_comercial:
        type: string
        example: OC-1331048
      Cuenta_Facturacion:
        type: number
        example: 12054361312
        required: false  
      CicloFacturacion:
        type: number
        example: 18
        required: false  
      Corte:
        type: number
        example: 0
        required: false  
      Codigo_Respuesta:
        type: number
        example: 0
      Descripcion_Respuesta:
        type: string
        example: OK