#%RAML 1.0 DataType
properties:
  WSRequestConceptosFactura:
    type: object
    properties:
      system:
        type: object
        properties:
          application:
            type: string
            required: true
            minLength: 1
          numero_conexion:
            type: string | nil
            required: false
          cuenta_facturacion:
            type: string | nil
            required: false
          numero_factura:
            type: string | nil
            required: false