#%RAML 1.0 Trait

headers:
  X-CORRELATION-ID:
    description: "Optional Correlation ID to be overwritten when sent the request as a transaction identifier"
    example: "b5a95a63.f190.4c91.880a.5b54512fa6b1"
    type: string
    required: true
  system:
    description: "System who is invoking the resourse."
    example: "Salesforce"
    type: string
    required: false
  target:
    description: "Target system to consume"
    example: "JSC"
    type: string
    required: false