envName: "Local"

app:
  apiId: "20494973"
  listener:
    host: "0.0.0.0"
    port: "8094"
    basePath: ""
  
wompi:
  host: "sandbox.wompi.co"
  port: "443"
  basePath: "v1"
  auth:
    public_key: "pub_test_6luCctD6wC8nOQKNoPHZyrh30vC1it2M"
    private_key: "prv_test_Nc725HldCVG4vNHiLggPUZ0CiTMZaUBa"
    signature: "test_integrity_XmM6NAY2GCRUKuruYwRPXErHs2AgLfiO"