#%RAML 1.0 DataType
type: object
displayName: nonStandardAddress
properties:
  outputSet:
    type: object
    properties:
      RETURN_VALUE:
        description: The non standard address
        type: string
        example: "CL 86 95C 15 IN 109"
        required: true