#%RAML 1.0 DataType
type: object
properties:
  CancelOrderOutput:
    type: object
    properties:
      appointmentId:
        type: string
      appt_number:
        type: string
      message:
        type: array
        items:
          properties:
            result:
              type: string
            type:
              type: string
            code:
              type: string
            description:
              type: string