#%RAML 1.0 DataType 
type: object
properties:
  totalResults:
    type: integer
    example: 3
    required: false
  limit:
    type: integer
    example: 10
    required: false
  offset:
    type: integer
    example: 0
    required: false
  items:
    type: array
    items:
      type: object
      properties:
        resourceId:
          type: string
          example: '1006094077'
          required: false
        lng:
          type: number
          example: -74.08767
          required: false
        lat:
          type: number
          example: 4.67953
          required: false
        time:
          type: string
          example: 2025-09-29T13:33:52+0000
          required: false
        dis:
          type: integer
          example: 706
          required: false
  links:
    type: array
    items:
      type: object
      properties:
        rel:
          type: string
          example: canonical
          required: false
        href:
          type: string
          example: >-
            https://etb.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/custom-actions/resourcesInA
          required: false
