#%RAML 1.0 DataType 
type: object
properties:
  cod_res:
    type: string
    example: '200'
    required: false
  res:
    type: string
    example: Consulta exitosa.
    required: false
  objConfiguracionInventario:
    type: object
    properties:
      serviceAccounts:
        type: array
        items:
          type: object
          properties:
            serviceAccountId:
              type: string
              example: CS-9012096
              required: false
            addresses:
              type: array
              items:
                type: object
                properties:
                  accesses:
                    type: array
                    items:
                      type: object
                      properties:
                        accessId:
                          type: string
                          example: '180097'
                          required: false
                        technologyName:
                          type: string
                          example: FIBRA
                          required: false
                        detailedRoute:
                          type: object
                          properties:
                            elements:
                              type: array
                              items:
                                type: object
                                properties:
                                  elementId:
                                    type: string
                                    example: '0'
                                    required: false
                                  elementType:
                                    type: string
                                    example: OLT SHELF
                                    required: false
                                  hostName:
                                    type: string
                                    example: BOCOZTC30001
                                    required: false
                                  port:
                                    type: string
                                    example: ''
                                    required: false
                                  vendor:
                                    type: string
                                    example: ZTE
                                    required: false
                                  networkLocation:
                                    type: string
                                    example: CHICO
                                    required: false
                        attributes:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: VelocidadSubida
                                required: false
                              value:
                                type: string
                                example: 2M
                                required: false
                  services:
                    type: array
                    items:
                      type: object
                      properties:
                        serviceId:
                          type: string
                          example: SR-9247201
                          required: false
                        rootServiceId:
                          type: string
                          example: SR-9247201
                          required: false
                        parentServiceId:
                          type: string
                          example: ''
                          required: false
                        serviceName:
                          type: string
                          example: Broadband Service Class
                          required: false
                        serviceStatus:
                          type: string
                          example: '1'
                          required: false
                        attributes:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                                example: SERVICENAME
                                required: false
                              value:
                                type: string
                                example: HSI_PPPOE
                                required: false
                              action:
                                type: string
                                example: ADD
                                required: false
                  policies:
                    type: array
                    items:
                      type: object
                      properties:
                        equipmentPolicies:
                          type: array
                          items:
                            type: object
                            properties:
                              equipmentType:
                                type: string
                                example: CPE-AP
                                required: false
                              brand:
                                type: string
                                example: ZTE
                                required: false
                              model:
                                type: string
                                example: ZTE H196A
                                required: false
                              minimumQuantity:
                                type: integer
                                example: 1
                                required: false
                              attributes:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: CLEI
                                      required: false
                                    value:
                                      type: string
                                      example: 101-33333
                                      required: false