#%RAML 1.0 DataType
type: object
properties:
  RestResponse:
    properties:
      items:
        type: array
        items:
          properties:
            XI_Denominacion:
              type: string
              example: "0000147868"
            XI_Logistic_Centre:
              type: string
              example: "ETB1"
            XI_Lote:
              type: string
              example: "0000147868"
            XI_Movement_Type:
              type: string
              example: "XI_Movement_Type"
            XI_PEP:
              type: string
              example: "XI_PEP"
            XI_Warehouse:
              type: string
              example: "2119"
            XI_macn:
              type: string
              example: "D4AC3806"
            inventoryId:
              type: number
              example: 10840955
            inventoryType:
              type: string
              example: "232-00874"
            quantity:
              type: number
              example: 1
            resourceId:
              type: string
              example: "9007456230"
            serialNumber:
              type: string
              example: "VBOX20PRUEBA104"
            status:
              type: string
              example: "resource"
      totalResults:
        type: number
        example: 223
      detail:
        type: string
        example: "detail"
      status:
        type: string
        example: "status"
      title:
        type: string
        example: "title"
      
            
            