#%RAML 1.0 DataType 
type: object
properties:
  resourceId:
    type: string
    example: '88185797'
    required: false
  organization:
    type: string
    example: default
    required: false
  email:
    type: string
    example: rafaelcante@consorciofibetel.com
    required: false
  phone:
    type: string
    example: '3138979747'
    required: false
  resourceInternalId:
    type: integer
    example: 5953
    required: false
  parentResourceInternalId:
    type: integer
    example: 4469
    required: false
  status:
    type: string
    example: active
    required: false
  resourceType:
    type: string
    example: PR
    required: false
  name:
    type: string
    example: RAFAEL CANTE MARTINEZ
    required: false
  language:
    type: string
    example: es
    required: false
  languageISO:
    type: string
    example: es-ES
    required: false
  timeZoneDiff:
    type: integer
    example: -300
    required: false
  timeZoneName:
    type: string
    example: Colombia (COT)
    required: false
  timeZoneIANA:
    type: string
    example: America/Bogota
    required: false
  dateFormat:
    type: string
    example: M/dd/yy
    required: false
  timeFormat:
    type: string
    example: 24-hour
    required: false
  durationStatisticsInitialRatio:
    type: integer
    example: 1
    required: false
  durationStatisticsInitialPeriod:
    type: integer
    example: 5
    required: false
  personnelType:
    type: string
    example: Field
    required: false
  XR_Warehouse:
    type: integer
    example: 2161
    required: false
  Contratista:
    type: string
    example: '8'
    required: false
  inventories:
    type: object
    properties:
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: canonical
              required: false
            href:
              type: string
              example: >-
                https://etb.test.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/88185797/inventories
              required: false
  users:
    type: object
    properties:
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: canonical
              required: false
            href:
              type: string
              example: >-
                https://etb.test.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/88185797/users
              required: false
  workZones:
    type: object
    properties:
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: canonical
              required: false
            href:
              type: string
              example: >-
                https://etb.test.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/88185797/workZones
              required: false
  workSkills:
    type: object
    properties:
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: canonical
              required: false
            href:
              type: string
              example: >-
                https://etb.test.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/88185797/workSkills
              required: false
  workSchedules:
    type: object
    properties:
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: canonical
              required: false
            href:
              type: string
              example: >-
                https://etb.test.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/88185797/workSchedules
              required: false
  links:
    type: array
    items:
      type: object
      properties:
        rel:
          type: string
          example: canonical
          required: false
        href:
          type: string
          example: >-
            https://etb.test.fs.ocs.oraclecloud.com/rest/ofscCore/v1/resources/88185797
          required: false
