#%RAML 1.0 DataType
type: object
properties:
  status:
    type: string
    required: true
    example: "PASS"
  description:
    type: string  
    required: true
    example: "SUCCESSS"
  capacities:
    type: array
    items:
      properties:
        date:
          type: string
          required: true
          example: "2022-10-13"
        time_slot:
          type: string
          required: true
          example: "1300-1500"
        work_skill:
          type: string
          required: true
          example: "ASEGBA_Plata"
        quota:
          type: string
          required: true
          example: "504"
        available:
          type: string
          required: true
          example: "504"