#%RAML 1.0 DataType 
type: object
properties:
  respuestaConsultaDisponibilidad:
    type: object
    properties:
      encabezadoMensaje:
        type: object
        properties:
          idDisponibilidad:
            type: string
            example: ''
            required: false
          numeroOrdenAprovisionador:
            type: string
            example: ''
            required: false
          numeroRevision:
            type: string
            example: ''
            required: false
          tecnologiaETB:
            type: string
            example: ''
            required: false
          fechaPeticionOrden:
            type: string
            example: ''
            required: false
      detalleMensaje:
        type: object
        properties:
          global:
            type: object
            properties:
              disponibilidad:
                type: string
                example: ''
                required: false
              motivo:
                type: object
                properties:
                  idServicioPadre:
                    type: string
                    example: ''
                    required: false
                  recurso:
                    type: string
                    example: ''
                    required: false
                  descripcion:
                    type: string
                    example: ''
                    required: false
          orderItems:
            type: array
            items:
              type: object
              properties:
                idServicio:
                  type: string
                  example: ''
                  required: false
                atributos:
                  type: array
                  items:
                    type: object
                    properties:
                      atributo:
                        type: string
                        example: ''
                        required: false
                      valor:
                        type: string
                        example: ''
                        required: false
                tecnologias:
                  type: array
                  items:
                    type: object
                    properties:
                      nombreTecnologia:
                        type: string
                        example: ''
                        required: false
                      resultadoTecnologia:
                        type: string
                        example: ''
                        required: false
                      motivo:
                        type: object
                        properties:
                          producto:
                            type: string
                            example: ''
                            required: false
                          recurso:
                            type: string
                            example: ''
                            required: false
                          descripcion:
                            type: string
                            example: ''
                            required: false
          resultado:
            type: object
            properties:
              resultado:
                type: string
                example: ''
                required: false
              codigoErrorResultado:
                type: string
                example: ''
                required: false
              descripcionErrorResultado:
                type: string
                example: ''
                required: false
