#%RAML 1.0 DataType
properties:
  defaultBillingAccount:
    type: object
    properties:
        id:
          type: string
          required: true
          example: "18"
        name:
          type: string
          required: true
          example: "Name"