#%RAML 1.0 DataType
properties:
  type:
    type: string
    required: true
    example: "RETAIL"
  salesChannel:
      type: string
      required: true
      example: "OWN_CALLCENTER"
  status:
      type: string
      required: true
      example: "STATUS"
  packages:
    type: array
    required: true
    items:
      properties:
          id:
            type: string
            required: true
            example: "plan_inicial_testetbmvne"
  subscriber:
    type: object
    properties:
        id:
          type: string
          required: true
          example: "223179"