#%RAML 1.0 DataType
properties:
  amount:
    type: object
    properties:
        amount:
          type: number
          required: true
          example: 500
        currency:
          type: string
          required: true
          example: "COP"
  subscription:
    type: string
    required: true
    example: "SID928554_TS1730029493042_0"
  msisdn:
    type: string
    required: true
    example: "3058386387"
  channel:
    type: string
    required: true
    example: "BALANCE_TRANSFER"
  comment:
    type: string
    required: true
    example: "Transferencia de saldo"

example: {  "amount": { "amount": 500, "currency": "COP" }, "subscription": "SID928554_TS1730029493042_0", "msisdn": "3058386387", "channel": "BALANCE_TRANSFER", "comment": "Transferencia de saldo"}