#%RAML 1.0 DataType
properties:
  id:
    type: string
    required: true
    example: "3050040017"
  name:
    type: string
    required: true
    example: "Name"
  status:
    type: string
    required: true
    example: "FREE"
  storeStatus:
    type: string
    required: true
    example: "UNDEFINED"
  pool:
    type: object
    properties:
      id:
          type: string
          required: true
          example: "654654"
      name:
        type: string
        required: true
        example: "PoolMsisdn_ETBMVNE_PruebasCliente"
  sourcePool:
    type: object
    properties:
      id:
          type: string
          required: true
          example: "65321" 
      name:
        type: string
        required: true
        example: "PoolMsisdn_ETBMVNE_PruebasCliente"       