#%RAML 1.0 DataType
properties:
  externalID:
    type: string
    required: true
    example: "externelaID_002"
  subscriberType:
      type: string
      required: true
      example: "EXTERNAL"
  document:
    type: object
    properties:
        documentType:
          type: string
          required: true
          example: "EXTERNAL"
        fiscalID:
          type: string
          required: true
          example: "externelaID_032"