#%RAML 1.0 DataType
type: object
displayName: SMPP de JSC
description: Documento que contiene número y mensaje entre otros datos.

properties:
  _id?:
    type: object
    description: Identificador único del documento (autogenerado por MongoDB).
    properties:
      $oid:
        type: string
        description: Valor del ObjectId generado por MongoDB.
        example: "68d2c2cde6d7096a65f183dd"

  message:
    type: string
    description: El contenido o payload del mensaje.
    example: "Inscríbete en nuestro servicio"

  destination:
    type: string
    description: Número de destino en formato internacional (MSISDN).
    example: "573009999999"

  createdAt:
    type: datetime
    description: Marca de tiempo para la creación del mensaje en formato fecha y hora (UTC).
    example: "2025-09-18T09:30:00.000Z"

  status:
    type: string
    description: Indica el estado del mensaje (pending, processing, processed).
    example: "pending"

  priority:
    type: string
    description: Prioridad del mensaje (1 = baja, 2 = media, 3 = alta).
    example: "1"
