#%RAML 1.0 DataType
properties:
  id:
    type: string
    required: true
    example: "subscription.id"
  name:
    type: string
    required: true
    example: "Add member to group"
  msisdn:
    type: string
    required: true
    example: "MSISDN"