#%RAML 1.0 DataType
properties:
  amount:
    type: object
    required: true
    properties:
        amount:
          type: number
          required: true
          example: 15.45
        currency:
          type: string
          required: true
          example: "USD"
  zipcode:
    type: string
    required: false
    example: "35001"
  aggregatorRef:
      type: string
      required: false
      example: "ref_agg"
  subscription:
      type: string
      required: false
      example: "SID125_TS12234_1"
  msisdn:
      type: string
      required: false
      example: "65896321"
  externalID:
      type: string
      required: false
      example: "ente_recargador_etb_0001"