#%RAML 1.0 NamedExample
value:
  wsNegQuoteQueryRequest:
    wsRequestHeader:
      property: 
        APELLIDO: "RODRIGUEZ"
        NOMBRE: "Cacharrito S.A"
        TRAMITE: "VTA"
        USUARIO: "DANIMERG"
        CANAL: "PORTAL FIJA"
        PROVEEDOR: ""
        CIUDAD: "BOGOTA D.C"
        DEPARTAMENTO": "BOGOTA"
        SISTEMA_ORIGEN: "PORTAL FIJA"
        MODELO: "2"
    quoteCalculation:
      calculationObject: 
        requestId: 1
        companyBasicInformation: 
          businessName: "Elcacharrito"
          identificationType: 9
          identification: "800013931"
          city: 146
          address: "DASDSADASD"
        companyAdditionalInformation:
          economicActivity: 16
          constitutionDate: "2000-09-08T00:00:00"
          stratum: 2
          zoneId: 2
        legalRepresentative:
          names: "SINLISIM"
          surnames: "RODRIGUEZ"
          identificationType: 1
          identification: "99103410"
          dateBirth: "1967-09-22T00:00:00"
        generalBalance:
          totalCurrentAssets: 789789
          inventories: 7897897
          totalAssets: 897897
          totalCurrentLiabilities: 8789789
          totalLiabilities: 789789789
          totalPatrimony: 7897897
        statusResults:
          currentYearOperatingRevenue: 8978978
          currentYearNoOperatingRevenue: 8978978
          previousYearOperatingRevenue: 978789
          previousYearNoOperatingRevenue: 789789
          costSale: 7897897
          operationalExpenses: 89789
          operationalProfit: 7897897
          otherExpenses: 897897
          netProfit: 8787
          beforeTaxProfit: 897897
          incomeTaxAndComplementary: 897897
          accountReceivable: 87897
          financialObligations: 897897
        policy:
          description: "?"