#%RAML 1.0 NamedExample
value:
  OrderFulfilment:
    Identification:
      ID: a094y00000Y4W2ZAAV
      BusinessComponentID: a094y00000Y4W2ZAAV
      ApplicationObjectKeyID: a094y00000Y4W2ZAAV
      RevisionNumber: '1'
    SalesOrder:
      OrderDateTime: '2022-02-01T10:39:47-05:00'
      DeliveryDateTime: '2022-02-01T11:00:30-05:00'
      TypeCode: SALES ORDER
      FulfilmentPriorityCode: '4'
      FulfilmentModeCode: DELIVER
      StatusCode: OPEN
    BusinessReference:
      Id: 00D40000000MzGuEAK
      ComponentId: 00D40000000MzGuEAK
      ApplicationObjectKeyId: 00D40000000MzGuEAK
    CustomerPartyAccount:
      Identification:
        ID: 0014000000y8AKcAAM
        BusinessComponentID: 0014000000y8AKcAAM
        ApplicationObjectKeyID: 0014000000y8AKcAAM
      Name: SECRETARIA DISTRITAL DE MOVILIDAD
      Address:
        Identification:
          ID: ''
          BusinessComponentID: ''
          ApplicationObjectKeyID: ''
        LineOne: ''
        CityName: ''
        StateName: ''
        CountryCode: '57'
        CountryName: Colombia
        GisID: ''
        Latitude: ''
        Longitude: ''
        CityCode: ''
        StateCode: '25'
        PurposeCode: ''
        Reference: N/A
        Technology:
          Type: ''
          CoverageType: ''
          CoverageIndicator: 'false'
          CoverageName: ''
          Zone: ''
      ContactPerson:
        FirstName: ''
        FamilyName: ''
        CompleteNumber: ''
      TypeCode: '2'
      Custom:
        DocumentType: NIT
        DocumentNumber: '899999061'
    Custom:
      OrderSubType: NORMAL
      SignedDocumentIndicator: 'true'
    PartyIdentification:
      ID: 005f30000060YMAAA2
      BusinessComponentID: 005f30000060YMAAA2
      ApplicationObjectKeyID: 005f30000060YMAAA2
    SalesOrderLine:
      - Identification:
          ID: a1Cf300000B4qbUEAR
          BusinessComponentID: a1Cf300000B4qbUEAR
          ApplicationObjectKeyID: a1Cf300000B4qbUEAR
        OrderQuantity: '1'
        ServiceActionCode: DELETE
        FulfilmentModeCode: DO
        ParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        RootParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        StatusCode: OPEN
        ServiceAddress:
          Identification:
            ID: ''
            BusinessComponentID: ''
            ApplicationObjectKeyID: ''
          LineOne: ''
          CityName: ''
          StateName: ''
          CountryCode: '57'
          CountryName: Colombia
          GisID: ''
          Latitude: ''
          Longitude: ''
          CityCode: ''
          StateCode: '25'
          PurposeCode: ''
          Reference: ''
          Technology:
            Type: ''
            CoverageType: Molecula
            CoverageIndicator: 'false'
            CoverageName: ''
            Zone: ''
        ItemReference:
          ItemIdentification:
            ID: a0pf3000006WSmRAAW
            BusinessComponentID: a0pf3000006WSmRAAW
            ApplicationObjectKeyID: a0pf3000006WSmRAAW
          Name: Plan_V+D EMPRESAS_3.0 GB_4x4G PROMO
          ServiceIndicator: 'false'
          TypeCode: PRODUCT
          NetworkIndicator: 'false'
          PrimaryClassificationCode: LTE Control Plan Class
        SalesOrderSchedule:
          RequestedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ExpectedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ShipTo:
            GisID: ''
            Latitude: ''
            Longitude: ''
            CityCode: ''
            StateCode: ''
            PurposeCode: ''
            Reference: ''
            Technology:
              Type: ''
              CoverageType: ''
              CoverageIndicator: 'false'
              CoverageName: ''
              Zone: ''
        OwnerPartyReference:
          ID: 005f30000060YMAAA2
          BusinessComponentID: 005f30000060YMAAA2
          ApplicationObjectKeyID: 005f30000060YMAAA2
        ScheduleOrderIndicator: 'false'
        Discounts: ''
        SpecificationGroupXA:
          - XAID: a1Df300000N5ML5EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML5EAN
            ActionCode: DELETE
            Name: RVC PARM Index DS
            Value: 6Mmin3G-6Mmin4G-3GB3G-12B4G-100-5
          - XAID: a1Df300000N5ML4EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML4EAN
            ActionCode: DELETE
            Name: RVC DURACION
            Value: '0'
          - XAID: a1Df300000N5ML3EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML3EAN
            ActionCode: DELETE
            Name: RVC PLN
            Value: Plan_V+D EMPRESAS_3.0 GB_4x4G PROMO
          - XAID: a1Df300000N5ML2EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML2EAN
            ActionCode: DELETE
            Name: SERVICE CLASSE OCS
            Value: CONTR0002171914
          - XAID: a1Df300000N5ML1EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML1EAN
            ActionCode: DELETE
            Name: RATE PLAN
            Value: PE30C
          - XAID: a1Df300000N5MLDEA3
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5MLDEA3
            ActionCode: DELETE
            Name: PAM_CLASS_ID
            Value: '0'
          - XAID: a1Df300000N5ML6EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML6EAN
            ActionCode: DELETE
            Name: RVC PARM Index desc
            Value: V-D-SMS-SVAs
          - XAID: a1Df300000N5MLBEA3
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5MLBEA3
            ActionCode: DELETE
            Name: RVC DESCUENTO INICIAL
            Value: '0'
          - XAID: a1Df300000N5MLAEA3
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5MLAEA3
            ActionCode: DELETE
            Name: RVC DESCUENTO TRES
            Value: '0'
          - XAID: a1Df300000N5ML9EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML9EAN
            ActionCode: DELETE
            Name: RVC DURACION DOS
            Value: '0'
          - XAID: a1Df300000N5ML8EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML8EAN
            ActionCode: DELETE
            Name: RVC FEAT
            Value: Cargo Fijo LTE
          - XAID: a1Df300000N5ML7EAN
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5ML7EAN
            ActionCode: DELETE
            Name: RVC PARM Descuento DS
            Value: $FDSCTOS_ROOT
          - XAID: a1Df300000N5MLCEA3
            ParentID: a1Cf300000B4qbUEAR
            ID: a1Df300000N5MLCEA3
            ActionCode: DELETE
            Name: RVC DESCUENTO DOS
            Value: '0'
        Custom:
          PartNumber: ''
          AssetIntegrationID: AC-713519
      - Identification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        OrderQuantity: '1'
        ServiceActionCode: DELETE
        FulfilmentModeCode: DO
        ParentSalesOrderLineIdentification:
          ID: ''
          BusinessComponentID: ''
          ApplicationObjectKeyID: ''
        RootParentSalesOrderLineIdentification:
          ID: ''
          BusinessComponentID: ''
          ApplicationObjectKeyID: ''
        StatusCode: OPEN
        ServiceAddress:
          Identification:
            ID: 0013300001bVL1nAAG
            BusinessComponentID: 0013300001bVL1nAAG
            ApplicationObjectKeyID: 0013300001bVL1nAAG
          LineOne: 'Calle 13 # 37-35 Piso 2'
          CityName: 'BOGOTÁ, D.C.'
          StateName: 'BOGOTÁ, D.C.'
          CountryCode: '57'
          CountryName: Colombia
          GisID: ''
          Latitude: ''
          Longitude: ''
          CityCode: '11001'
          StateCode: '25'
          PurposeCode: ''
          Reference: ''
          Technology:
            Type: ''
            CoverageType: Molecula
            CoverageIndicator: 'false'
            CoverageName: ''
            Zone: ''
        ItemReference:
          ItemIdentification:
            ID: a0m33000006eEEDAA2
            BusinessComponentID: a0m33000006eEEDAA2
            ApplicationObjectKeyID: a0m33000006eEEDAA2
          Name: TELEFONIA MOVIL (LTE)
          ServiceIndicator: 'false'
          TypeCode: PRODUCT
          NetworkIndicator: 'false'
          PrimaryClassificationCode: LTE Service Class
        SalesOrderSchedule:
          RequestedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ExpectedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ShipTo:
            GisID: ''
            Latitude: ''
            Longitude: ''
            CityCode: ''
            StateCode: ''
            PurposeCode: ''
            Reference: ''
            Technology:
              Type: ''
              CoverageType: ''
              CoverageIndicator: 'false'
              CoverageName: ''
              Zone: ''
        OwnerPartyReference:
          ID: 005f30000060YMAAA2
          BusinessComponentID: 005f30000060YMAAA2
          ApplicationObjectKeyID: 005f30000060YMAAA2
        ScheduleOrderIndicator: 'false'
        Discounts: ''
        SpecificationGroupXA:
          - XAID: a1Df300000LceoIEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoIEAR
            ActionCode: DELETE
            Name: RESGISTRO EN LISTA NEGRA ROBO O PERDIDA
            Value: 'NO'
          - XAID: a1Df300000LceoJEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoJEAR
            ActionCode: DELETE
            Name: RVC DURACION
            Value: NA
          - XAID: a1Df300000LceoKEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoKEAR
            ActionCode: DELETE
            Name: RVC DURACION DOS
            Value: NA
          - XAID: a1Df300000LceoLEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoLEAR
            ActionCode: DELETE
            Name: RVC NOMBRE
            Value: '''LTE'''
          - XAID: a1Df300000LceoMEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoMEAR
            ActionCode: DELETE
            Name: RVC PLN
            Value: Uso No Pre-tarificado LTE
          - XAID: a1Df300000LceoHEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoHEAR
            ActionCode: DELETE
            Name: REGISTRO DE EQUIPO A CLIENTE
            Value: 'YES'
          - XAID: a1Df300000LceoGEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoGEAR
            ActionCode: DELETE
            Name: PRODUCTOS LB BA
            Value: ''
          - XAID: a1Df300000LceoFEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoFEAR
            ActionCode: DELETE
            Name: TIPO DE SIM CARD
            Value: TRIO NACKED
          - XAID: a1Df300000LceoEEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoEEAR
            ActionCode: DELETE
            Name: PROCENTAJE DE FINANCIAMIENTO
            Value: '0'
          - XAID: a1Df300000LceoDEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoDEAR
            ActionCode: DELETE
            Name: PORTABILIDAD
            Value: 'Y'
          - XAID: a1Df300000LceoCEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoCEAR
            ActionCode: DELETE
            Name: PERMANENCIA
            Value: NA
          - XAID: a1Df300000LceoBEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoBEAR
            ActionCode: DELETE
            Name: NUMERO FIJO
            Value: ''
          - XAID: a1Df300000LceoAEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoAEAR
            ActionCode: DELETE
            Name: MODO ADQUISICION EQUIPO
            Value: PROPIO
          - XAID: a1Df300000Lceo9EAB
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000Lceo9EAB
            ActionCode: DELETE
            Name: GAMA DEL EQUIPO
            Value: Baja
          - XAID: a1Df300000Lceo8EAB
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000Lceo8EAB
            ActionCode: DELETE
            Name: FINANCIAMIENTO
            Value: NA
          - XAID: a1Df300000Lceo7EAB
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000Lceo7EAB
            ActionCode: DELETE
            Name: FECHA INICIO SUSPENSION (DD/MM/YYYY)
            Value: 05/01/2014
          - XAID: a1Df300000Lceo6EAB
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000Lceo6EAB
            ActionCode: DELETE
            Name: FECHA FINAL SUSPENSION (DD/MM/YYYY)
            Value: 01/01/2014
          - XAID: a1Df300000Lceo5EAB
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000Lceo5EAB
            ActionCode: DELETE
            Name: METODO DE PAGO
            Value: POSPAGO
          - XAID: a1Df300000LceoNEAR
            ParentID: a1Cf300000BQfDREA1
            ID: a1Df300000LceoNEAR
            ActionCode: DELETE
            Name: SUBTIPO ORDEN
            Value: Venta LTE
        Custom:
          PartNumber: ''
          AssetIntegrationID: AC-713519
      - Identification:
          ID: a1Cf300000BQfDWEA1
          BusinessComponentID: a1Cf300000BQfDWEA1
          ApplicationObjectKeyID: a1Cf300000BQfDWEA1
        OrderQuantity: '1'
        ServiceActionCode: DELETE
        FulfilmentModeCode: DO
        ParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        RootParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        StatusCode: OPEN
        ServiceAddress:
          Identification:
            ID: 0013300001bVL1nAAG
            BusinessComponentID: 0013300001bVL1nAAG
            ApplicationObjectKeyID: 0013300001bVL1nAAG
          LineOne: 'Calle 13 # 37-35 Piso 2'
          CityName: 'BOGOTÁ, D.C.'
          StateName: 'BOGOTÁ, D.C.'
          CountryCode: '57'
          CountryName: Colombia
          GisID: ''
          Latitude: ''
          Longitude: ''
          CityCode: '11001'
          StateCode: '25'
          PurposeCode: ''
          Reference: ''
          Technology:
            Type: ''
            CoverageType: Molecula
            CoverageIndicator: 'false'
            CoverageName: ''
            Zone: ''
        ItemReference:
          ItemIdentification:
            ID: a0r33000008FkcpAAC
            BusinessComponentID: a0r33000008FkcpAAC
            ApplicationObjectKeyID: a0r33000008FkcpAAC
          Name: EQUIPO PROPIEDAD CLIENTE
          ServiceIndicator: 'false'
          TypeCode: PRODUCT
          NetworkIndicator: 'false'
          PrimaryClassificationCode: LTE Customer Equipment Class
        SalesOrderSchedule:
          RequestedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ExpectedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ShipTo:
            GisID: ''
            Latitude: ''
            Longitude: ''
            CityCode: ''
            StateCode: ''
            PurposeCode: ''
            Reference: ''
            Technology:
              Type: ''
              CoverageType: ''
              CoverageIndicator: 'false'
              CoverageName: ''
              Zone: ''
        OwnerPartyReference:
          ID: 005f30000060YMAAA2
          BusinessComponentID: 005f30000060YMAAA2
          ApplicationObjectKeyID: 005f30000060YMAAA2
        ScheduleOrderIndicator: 'false'
        Discounts: ''
        SpecificationGroupXA:
          - XAID: a1Df300000LceoWEAR
            ParentID: a1Cf300000BQfDWEA1
            ID: a1Df300000LceoWEAR
            ActionCode: DELETE
            Name: IMEI
            Value: '353420089816881'
          - XAID: a1Df300000LceoXEAR
            ParentID: a1Cf300000BQfDWEA1
            ID: a1Df300000LceoXEAR
            ActionCode: DELETE
            Name: MODELO
            Value: SAMSUNG GALAXY J5 PRIME
          - XAID: a1Df300000LceoYEAR
            ParentID: a1Cf300000BQfDWEA1
            ID: a1Df300000LceoYEAR
            ActionCode: DELETE
            Name: MARCA
            Value: Samsung
          - XAID: a1Df300000LceoZEAR
            ParentID: a1Cf300000BQfDWEA1
            ID: a1Df300000LceoZEAR
            ActionCode: DELETE
            Name: NUMERO DE SIM (ICCID)
            Value: ''
          - XAID: a1Df300000LceoaEAB
            ParentID: a1Cf300000BQfDWEA1
            ID: a1Df300000LceoaEAB
            ActionCode: DELETE
            Name: PART NUMBER
            Value: 108-00760
        Custom:
          PartNumber: ''
          AssetIntegrationID: AC-713519
      - Identification:
          ID: a1Cf300000BQfDXEA1
          BusinessComponentID: a1Cf300000BQfDXEA1
          ApplicationObjectKeyID: a1Cf300000BQfDXEA1
        OrderQuantity: '1'
        ServiceActionCode: DELETE
        FulfilmentModeCode: DO
        ParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        RootParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        StatusCode: OPEN
        ServiceAddress:
          Identification:
            ID: 0013300001bVL1nAAG
            BusinessComponentID: 0013300001bVL1nAAG
            ApplicationObjectKeyID: 0013300001bVL1nAAG
          LineOne: 'Calle 13 # 37-35 Piso 2'
          CityName: 'BOGOTÁ, D.C.'
          StateName: 'BOGOTÁ, D.C.'
          CountryCode: '57'
          CountryName: Colombia
          GisID: ''
          Latitude: ''
          Longitude: ''
          CityCode: '11001'
          StateCode: '25'
          PurposeCode: ''
          Reference: ''
          Technology:
            Type: ''
            CoverageType: Molecula
            CoverageIndicator: 'false'
            CoverageName: ''
            Zone: ''
        ItemReference:
          ItemIdentification:
            ID: a0r33000008FkcuAAC
            BusinessComponentID: a0r33000008FkcuAAC
            ApplicationObjectKeyID: a0r33000008FkcuAAC
          Name: NUMERO SIM CARD
          ServiceIndicator: 'false'
          TypeCode: PRODUCT
          NetworkIndicator: 'false'
          PrimaryClassificationCode: LTE Simcard Class
        SalesOrderSchedule:
          RequestedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ExpectedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ShipTo:
            GisID: ''
            Latitude: ''
            Longitude: ''
            CityCode: ''
            StateCode: ''
            PurposeCode: ''
            Reference: ''
            Technology:
              Type: ''
              CoverageType: ''
              CoverageIndicator: 'false'
              CoverageName: ''
              Zone: ''
        OwnerPartyReference:
          ID: 005f30000060YMAAA2
          BusinessComponentID: 005f30000060YMAAA2
          ApplicationObjectKeyID: 005f30000060YMAAA2
        ScheduleOrderIndicator: 'false'
        Discounts: ''
        SpecificationGroupXA:
          - XAID: a1Df300000LceocEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceocEAB
            ActionCode: DELETE
            Name: PIN
            Value: '0000'
          - XAID: a1Df300000LceobEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceobEAB
            ActionCode: DELETE
            Name: CAMBIO SIMCARD
            Value: 'NO'
          - XAID: a1Df300000LceodEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceodEAB
            ActionCode: DELETE
            Name: CON CARGO?
            Value: 'NO'
          - XAID: a1Df300000LceojEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceojEAB
            ActionCode: DELETE
            Name: connection_number_type_name
            Value: '''Numero Movil'''
          - XAID: a1Df300000LceoiEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceoiEAB
            ActionCode: DELETE
            Name: connection_type_name
            Value: '''IMSI'''
          - XAID: a1Df300000LceohEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceohEAB
            ActionCode: DELETE
            Name: DESCUENTO
            Value: '100'
          - XAID: a1Df300000LceogEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceogEAB
            ActionCode: DELETE
            Name: ICCID
            Value: '89571871150018747736'
          - XAID: a1Df300000LceofEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceofEAB
            ActionCode: DELETE
            Name: IMSI
            Value: '732187102354773'
          - XAID: a1Df300000LceoeEAB
            ParentID: a1Cf300000BQfDXEA1
            ID: a1Df300000LceoeEAB
            ActionCode: DELETE
            Name: PUK
            Value: '66335109'
        Custom:
          PartNumber: ''
          AssetIntegrationID: AC-713519
      - Identification:
          ID: a1Cf300000BQfDZEA1
          BusinessComponentID: a1Cf300000BQfDZEA1
          ApplicationObjectKeyID: a1Cf300000BQfDZEA1
        OrderQuantity: '1'
        ServiceActionCode: DELETE
        FulfilmentModeCode: DO
        ParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        RootParentSalesOrderLineIdentification:
          ID: a1Cf300000BQfDREA1
          BusinessComponentID: a1Cf300000BQfDREA1
          ApplicationObjectKeyID: a1Cf300000BQfDREA1
        StatusCode: OPEN
        ServiceAddress:
          Identification:
            ID: 0013300001bVL1nAAG
            BusinessComponentID: 0013300001bVL1nAAG
            ApplicationObjectKeyID: 0013300001bVL1nAAG
          LineOne: 'Calle 13 # 37-35 Piso 2'
          CityName: 'BOGOTÁ, D.C.'
          StateName: 'BOGOTÁ, D.C.'
          CountryCode: '57'
          CountryName: Colombia
          GisID: ''
          Latitude: ''
          Longitude: ''
          CityCode: '11001'
          StateCode: '25'
          PurposeCode: ''
          Reference: ''
          Technology:
            Type: ''
            CoverageType: Molecula
            CoverageIndicator: 'false'
            CoverageName: ''
            Zone: ''
        ItemReference:
          ItemIdentification:
            ID: a0r33000008Fkd4AAC
            BusinessComponentID: a0r33000008Fkd4AAC
            ApplicationObjectKeyID: a0r33000008Fkd4AAC
          Name: NUMERO TELEFONICO LTE
          ServiceIndicator: 'false'
          TypeCode: PRODUCT
          NetworkIndicator: 'false'
          PrimaryClassificationCode: LTE Number Class
        SalesOrderSchedule:
          RequestedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ExpectedDeliveryDate: '2022-02-01T11:00:30-05:00'
          ShipTo:
            GisID: ''
            Latitude: ''
            Longitude: ''
            CityCode: ''
            StateCode: ''
            PurposeCode: ''
            Reference: ''
            Technology:
              Type: ''
              CoverageType: ''
              CoverageIndicator: 'false'
              CoverageName: ''
              Zone: ''
        OwnerPartyReference:
          ID: 005f30000060YMAAA2
          BusinessComponentID: 005f30000060YMAAA2
          ApplicationObjectKeyID: 005f30000060YMAAA2
        ScheduleOrderIndicator: 'false'
        Discounts: ''
        SpecificationGroupXA:
          - XAID: a1Df300000LceonEAB
            ParentID: a1Cf300000BQfDZEA1
            ID: a1Df300000LceonEAB
            ActionCode: DELETE
            Name: conection_number_type_name
            Value: '''MSISDN'''
          - XAID: a1Df300000LceooEAB
            ParentID: a1Cf300000BQfDZEA1
            ID: a1Df300000LceooEAB
            ActionCode: DELETE
            Name: connection_number
            Value: $MSISDN
          - XAID: a1Df300000LceoqEAB
            ParentID: a1Cf300000BQfDZEA1
            ID: a1Df300000LceoqEAB
            ActionCode: DELETE
            Name: NumeroAnterior
            Value: ''
          - XAID: a1Df300000LceorEAB
            ParentID: a1Cf300000BQfDZEA1
            ID: a1Df300000LceorEAB
            ActionCode: DELETE
            Name: connection_type_name
            Value: '''Numero Movil'''
          - XAID: a1Df300000LceopEAB
            ParentID: a1Cf300000BQfDZEA1
            ID: a1Df300000LceopEAB
            ActionCode: DELETE
            Name: Numero
            Value: '3208460688'
        Custom:
          PartNumber: ''
          AssetIntegrationID: AC-713519
    Scheduling:
      SubOrderType: Cancelacion Voluntaria
    AltKey:
      - AltKeyName: SDP
        AltKeyValue: ''
      - AltKeyName: ServiceId
        AltKeyValue: a02f300000gVCygAAG-a094y00000Y4W2ZAAV
      - AltKeyName: NOMBRES
        AltKeyValue: SECRETARIA DISTRITAL DE MOVILIDAD
      - AltKeyName: APELLIDO1
        AltKeyValue: ''
      - AltKeyName: APELLIDO2
        AltKeyValue: ''
      - AltKeyName: INVOICING_CYCLE_OCS
        AltKeyValue: '5'
      - AltKeyName: SistemaOrigen
        AltKeyValue: SALESFORCE
  BillingProcess:
    CustomerBill:
      InvoicingCycle: '5'