#%RAML 1.0
title: appointment-management-papi-services-v2
version: v2
baseUri: https://appointment-mgmt-papi-services-v2-{env}.us-e2.cloudhub.io/{version}
protocols:
  - HTTPS

description: |
  # Appointment papi API Services

traits:
  tibcoHeaders: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml

  security_client_id: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml

mediaType: 
  - application/json

/appointment:
  get:
    is: [security_client_id,tibcoHeaders]
    displayName: Get Schedules.
    description: Retrieves the list of available schedules.

    queryParameters:
      ORIGIN:
        type: string
        example: "WHATSAPP"
        description: Parameter that allows identifying the origin of the request.

      CUSTOMER_ID:
        type: string
        example: "12552454"
        description: Customer identification number (ID card or tax ID number).
        required: false

      CUSTOMER_ID_TYPE:
        type: string
        enum: ["CC", "CE", "PASAPORTE", "NIT", "RUT", "TI"]
        example: "CC"
        description: Type of customer identification document.
        required: false

      FILTERS:
        type: string
        example: ""
        description: "String used to apply filters such as start date, end date, penalty value, and clause duration. Follow the example: separate the filter name and its value with a colon, and multiple filters with a semicolon."
        required: false

      LIMIT:
        type: number
        description: "Limit on orders to display"
        required: false

      OFFSET:
        type: string
        description: "used to organize information and establish a logical order"
        required: false
        
    responses:
      200:
        body:
          application/json:
            type: !include /datatypes/response/get-appointment.raml
            example: !include /examples/response/get-appointment.json

      400:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-400.json

      401:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-401.json

      404:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-404.json

      500:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-500.json
/appointments:
  get:
    is: [security_client_id,tibcoHeaders]
    displayName: Get Appointments
    description: Retrieves appointment schedules for both assurance and provisioning processes.

    queryParameters:
      ORIGIN:
        type: string
        example: "WHATSAPP"
        description: Parameter that allows identifying the origin of the request.

      CUSTOMER_ID:
        type: string
        example: "12552454"
        description: Customer identification number (ID card or tax ID number).
        required: false

      CUSTOMER_ID_TYPE:
        type: string
        enum: ["CC", "CE", "PASAPORTE", "NIT", "RUT", "TI"]
        example: "CC"
        description: Type of customer identification document.
        required: false

      FILTERS:
        type: string
        example: ""
        description: "String used to apply multiple filters in a key–value format. Each filter must be defined as key:value and multiple filters must be separated by semicolons. Example: numOrder:234242;status:Completed;startDate:2020-11-19T00:00:00Z;endDate:2020-11-19T00:00:00Z."
        required: false

      LIMIT:
        type: number
        description: "Limit on orders to display"
        required: false

      OFFSET:
        type: string
        description: "used to organize information and establish a logical order"
        required: false
        
    responses:
      200:
        body:
          application/json:
            type: !include /datatypes/response/get-appointments.raml
            example: !include /examples/response/get-appointments.json

      400:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-400.json

      401:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-401.json

      404:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-404.json

      500:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-500.json

/schedules:
  post:
    is: [security_client_id,tibcoHeaders]
    displayName: Post Scheduling
    description: Create the scheduling of the orders.
    body:
      application/json:
        type: !include /datatypes/request/post-schedules.raml
        example: !include /examples/request/post-schedules.json
    responses:
      201:
        body:
          application/json:
            type: !include /datatypes/response/post-schedules.raml
            example: !include /examples/response/post-schedules.json
      400:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-400.json

      401:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-401.json

      404:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-404.json

      500:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-500.json
