#%RAML 1.0
title: oracle-sapi-services
version: "1"
mediaType: 
- application/json
baseUri: http://oracle-sapi-services-dev.us-e2.cloudhub.io/oracle/
description: 
uses:
  processId-lib: libraries/processId-library.raml
traits:
  securityClient: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  tibcoRequestHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.5/tibcorequestheaders.raml

/v1:
  /assurance:
    /order:
      post:
        is: [securityClient, tibcoRequestHeaders]
        displayName: Create Order in OFSC
        description: Service to create order in OFSC
        body:
          application/json:
            type: !include datatypes/request/post-order-assurance.raml
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/responses/post-order-assurance-200.raml
      /{activityId}:
        get:
          is: [securityClient, tibcoRequestHeaders]
          displayName: Sync Order in OFSC
          description: Service to sync order in OFSC
          responses:
            200:
              body:
                application/json:
                  example: !include /examples/response/get-order-assurance-200.json
            404:
              body:
                application/json:
                  example: !include /examples/response/get-order-assurance-404.json
        patch:
          is: [securityClient, tibcoRequestHeaders]
          displayName: Update order OFSC 
          description: Servicio de actualización de ordenes en OFSC
          body:
            application/json:
              type: !include datatypes/request/patchAssuranceOrder.raml
          responses:
            200:
              body:
                application/json:
                  example: !include /examples/response/patchAssuranceOrder.json
  /normalizeAddressBogota:
    is: [securityClient, tibcoRequestHeaders]
    post:
      displayName: Normalize address
      description: Normalizes addresses corresponding to Bogota
      body:
        type: !include datatypes/request/unNormalizedAddress.raml
      responses:
        201:
          body: 
            type: !include datatypes/responses/normalizedAddress.raml
       
  /normalizeAddressGeneral:
    is: [securityClient, tibcoRequestHeaders]
    post:
      displayName: Normalize address
      description: General normalization of addresses
      body:
        type: !include datatypes/request/unNormalizedAddress.raml
      responses:
        201:
          body:
              type: !include datatypes/responses/normalizedAddress.raml

  /processId:
    is: [securityClient]
    get:
      displayName: Get process id
      description: Get process id by salesforce id from oracle database
      queryParameters:
        salesforce-id:
          type: string
          required: true
      responses:
        200:
          body:
              type: processId-lib.getProcessIdResponse
              examples:
                successResponse: !include examples/response/getProcessIdResponse.json
                emptyResponse: !include examples/response/getProcessIdEmptyResponse.json

    post:
      displayName: Insert process id
      description: If the process id isn't found in a search, insert it in oracle database.
      body:
        type: processId-lib.processIdRequest
        example: !include examples/request/processIdRequest.json
      responses:
        201:
          body:
              type: processId-lib.processIdResponse
              example: !include examples/response/processIdInsertResponse.json
    patch:
      displayName: Update process id
      description: When a process id is found, update it in oracle database.
      body:
        type: processId-lib.processIdRequest
        example: !include examples/request/processIdRequest.json
      responses:
        200:
          body:
              type: processId-lib.processIdResponse
              example: !include examples/response/processIdUpdateResponse.json

  /health_check:
    get:
      displayName: Health Check
      description: Check the connectivity of calls
      responses:
        200:
          description: Status of legacies and dependencies
          body:
            application/json:
              type: !include datatypes/responses/healthcheckobjectresponse.raml
              example: !include examples/response/get_healthcheck_response.json
  /cancelOrder:
    is: [securityClient, tibcoRequestHeaders]
    post:
      displayName: This method Cancel an Order on OCS
      description: Method to Cancel an Order
      body:
        type: !include datatypes/request/cancelOrder.raml
        example: !include examples/request/cancelOrder.json
      responses:
        200:
          body:
              type: !include datatypes/responses/cancelOrderSuccess.raml
              example: !include examples/response/cancelOrderSuccess.json
  /order:
    is: [securityClient, tibcoRequestHeaders] 
    post:
      displayName: This method Create an Order on OCS.
      description: Method to Create an Order.
      body:
        type: !include datatypes/request/createOrder.raml
        example: !include examples/request/createOrder.json
      responses:
        200:
          body:
            example: !include examples/response/createOrder.json            
  /resInvList:
    /{externalId}:
      uriParameters:
        externalId:
          required: true
          type: string
          example: "900162721"
      get:
        is: [securityClient, tibcoRequestHeaders]
        displayName: Get an RevInvList
        description: Get an RevInvList
        queryParameters:
          limit:
            type: string
            required: true
            example: "100"
          offset:
            type: string
            required: true
            example: "0"
        responses:
          200:
            body:
                application/json:
                  type: !include datatypes/responses/get-resInvList.raml
  /invokeETADirectInbound:
    post:
      is: [securityClient, tibcoRequestHeaders]
      displayName: Invoke ETA Direct Inbound
      description: This method invokeETADirectInbound on OCS
      body:
        type: !include datatypes/request/invokeETADirectInbound.raml
        example: !include examples/request/invokeETADirectInbound.json
      responses:
        200:
          body:
            example: !include examples/response/invokeETADirectInbound-response.json
  /sendMessage:
    is: [securityClient, tibcoRequestHeaders]
    post:
      displayName: Send Email or SMS
      description: This method send an email or SMS
      body:
        application/json:
          type: !include datatypes/request/SendMessage.raml
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/responses/SentMessage.raml
              
  /document:
    /homologation:
      /{idDocument}:
        uriParameters:
          idDocument:
            type: string
            enum: [C.C, C.D, C.E, E.S.N, FID, NIT, PAS, R.C, SEG, T.I]
            example: "C.C"
        get:
          is: [securityClient, tibcoRequestHeaders]
          displayName: Homologate document 
          description: Homologate document by its type.
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/responses/documentHomologation.raml

  /nonStandardAddress:  
    post:
      is: [securityClient, tibcoRequestHeaders]
      displayName: Post an unnormalized address
      description: Adds a new un-normalized address to the list
      body:
        type: !include datatypes/request/addressRequest.raml
      responses:
        201:
          body:
            type: !include datatypes/responses/addressResponse.raml
    /{address}:
      uriParameters:
        address:
          type: string
          required: true
      get:
        is: [securityClient, tibcoRequestHeaders]
        displayName: Get an unnormalized address
        description: Gets from a list of un-normalized addresses the one that matches with the input
        responses:
          200:
            body:
              type: !include datatypes/responses/addressResponse.raml
    /specialMunicipalities:
      /{municipality}:
        uriParameters:
          municipality:
            type: string
            required: true
        get:
          is: [securityClient, tibcoRequestHeaders]
          displayName: Get special municipalities
          description: Checks for the existance of a municipality code from a list of special municipalities
          responses:
            200:
              body:
                type: !include datatypes/responses/specialMunicipalitiesResponse.raml

  /homologation:
    /{genericValue}:
      /{catalog}:
        uriParameters:
          genericValue:
            type: string
            example: "Venta LTE"
          catalog:
            type: string
            example: "CT21AQO"
        get:
          is: [securityClient, tibcoRequestHeaders]
          displayName: Homologate genericValue
          description: Homologate genericValue by its catalog.
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/responses/genericValueHomologation.raml
  /getCapacity:
    is: [securityClient, tibcoRequestHeaders]
    post:
      displayName: Gets capacity according skill attribute
      description: This method gets the capacity based on the skill attribute
      body:
        application/json:
          type: !include datatypes/request/getCapacity.raml
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/responses/getCapacity.raml
  /api:
    /responsys:
      /enviogeneral:
        post:
          description: Operación de ejemplo para enviar mensajes por Responsys
          body:
            application/json:
              type: !include datatypes/request/envioGeneral.raml
              example: !include examples/request/envioGeneralRequest.json                
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/responses/envioGeneralResponse.raml
                  example: !include examples/response/envioGeneralResponse.json
  /resources:
    /{id}:
      get:
        is: [securityClient]
        displayName: Get employee
        description: Get employee
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/responses/get-resources-id.raml
                example: !include examples/response/get-resources-id.json
    /inArea:
      get:
        is: [securityClient]
        displayName: Get Technician Crews by Area
        description: Get Technician Crews by Area
        queryParameters:
          lat:
            type: string
            required: true
            example: "4.75026014400004"
          lng:
            type: string
            required: true
            example: "74.0817942529999"
          radius:
            type: string
            required: true
            example: "10000"
          limit:
            type: string
            required: true
            example: "10"
          timeDiff:
            type: string
            required: true
            example: "30"
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/responses/get-resources-inArea.raml
                example: !include examples/response/get-resources-inArea.json