#%RAML 1.0 Library
usage:
types:
  ping: !include ../datatypes/responses/ping.raml
  banks: !include ../datatypes/responses/banks.raml
  post-payment-response: !include ../datatypes/responses/post-payment-response.raml
  get-payment-transaction-response: !include  ../datatypes/responses/get-payment-transaction-response.raml
  
    