# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
# --- Example Backend HTTP Requester ---
wbd:
  protocol: "HTTPS"
  host: ""
  port: ""
  basePath: ""
  subscriptions:
    path: "/subscriptions/{partnerId}"
    get:
      method: "GET"
  events:
    path: "/event/{partnerId}"
    post:
      method: "POST"