#%RAML 1.0 NamedExample
value:
  System:
    correlationID: "2021-02-19 04:04:58"
    processingServer: Mulesoft
    responseDate: 2021-02-18T23:04:59.443-05:00
  Response:
    ResponseTramits:
      -
        orderNumber: a09m0000005ay9JAAQ
        responseCode: "0"
        responseDescription: No fue posible realizar el registro  