#%RAML 1.0 NamedExample
value:
  IMEI: "354522058683249"
  Estado: No registrado
  Marca: Samsung   
  CodigoRespuestaListas: "4"  
  Modelo: GT-S7562L
  RespuestaGSMA: 4G_ETB 
  ProbadoRedETB: NO -
  RespuestaPruebaRedETB: ""
  HomologadoColombia: EXISTE
  TamanoSIM: ""
  PartNumberSIM: "" 
  CodigoError: "0"
  DescripcionError: "" 