#%RAML 1.0 NamedExample
value:
  cunNumber: "4347210003472216"
  cunDate: 18/11/2021 04:53:04 a.m.
  errorCode: "5015"
  errorDescription: ASIGNACION CUN PRIMERA VEZ
  pqrType: caso pqr
  pqrDate?: 11/17/2021 23:50:09
  system?: SALESFORCE
  ordenNumber: "2253126"
  identificationType: NIT
  identification: "800130244"
  conexionNum: "0"