#%RAML 1.0 DataType 
type: object
properties:
  IdentityValidationId:
    type: integer
    example: 14225
    required: false
  Model:
    type: integer
    example: 1
    required: false
  Stratum:
    type: integer
    example: 3
    required: false
  Department:
    type: integer
    example: 11
    required: false
  City:
    type: integer
    example: 11001
    required: false
