#%RAML 1.0 DataType
type: object
properties:
  Tipo_Documento:
    type: string
    example: "CC"
    required: true
  Numero_Documento:
    type: string
    example: "123456789"
    required: true
  Primer_Apellido:
    type: string
    example: "PEREZ"
    required: true
  Fecha_Expedicion:
    type: string
    description: Document expedition date (dd/mm/yyyy)
    example: "20/05/2010"
    required: false
  Razon_Social:
    type: string
    example: ""
    required: false
  Caracteristicas:
    type: array
    required: false
    items:
      type: object
      properties:
        Nombre:
          type: string
          example: "APELLIDO"
        Valor:
          type: string
          example: "PEREZ"
