#%RAML 1.0 DataType
type: object
properties:
  Properties:
    type: object
    required: false
    properties:
      APELLIDO:
        type: string
        required: false
      NOMBRE:
        type: string
        required: false
      TRAMITE:
        type: string
        required: false
      USUARIO:
        type: string
        required: false
      CANAL:
        type: string
        required: false
      PROVEEDOR:
        type: string | nil
        required: false
      CIUDAD:
        type: string
        required: false
      DEPARTAMENTO:
        type: string
        required: false
      SISTEMA_ORIGEN:
        type: string
        required: false
      MODELO:
        type: string
        required: false
      PORTAL:
        type: string
        required: false
      ESTRATO:
        type: string
        required: false
  Body:
    type: object
    properties:
      GestionClientes:
        type: object
        properties:
          head:
            type: object
            properties:
              Interfaz:
                type: string
                required: false
              Destino:
                type: string
                required: false
          body:
            type: object
            properties:
              Cliente:
                type: object
                properties:
                  TipoDocumento:
                    type: string
                    required: true
                    minLength: 1
                  NumeroDocumento:
                    type: string
                    required: true
                    minLength: 1
                  FechaExpedicionDocumento:
                    type: string
                    required: true
                    minLength: 1
                  PrimerApellido:
                    type: string
                    required: true
                    minLength: 1