#%RAML 1.0 NamedExample
value:
  lstObjetosHijosRelacionados:    
      ObjetosHijosRelacionados:
        - 
          lstParametros:
            Keys:
              - 
                Campo: "CommentBody"
                Valor: "Actualizacion Salesforce ASC"
          NombreRelacion: "CaseComments"
  lstParametros:    
    Keys:
      - 
        Campo: "Description"
        Valor: "NIT 900276962"
      - 
        Campo: "Subject"
        Valor: "ENLACE CAIDO ID00000324 KOBA COLOMBIA S.A.S TIENDA BOG GRANADA"
      -
        Campo: "FechaInicioAfectacion__c"
        Valor: "2022-4-23 19:30:00"      
      -
        Campo: "ID_Servicio"
        Valor: null      
      -
        Campo: "Status"
        Valor: "En Progreso"      
      -
        Campo: "Id_Sistema_Legado__c"
        Valor: "INC000006533023"      
      -
        Campo: "Priority"
        Valor: "Alta"      
      -
        Campo: "Causal_Estado__c"
        Valor: "Asignado"      
      -
        Campo: "NumeroDocumento"
        Valor: "900276962"      
      -
        Campo: "Proceso__c"
        Valor: "INTERRUPCION"      
      -
        Campo: "Agrupacion__c"
        Valor: "CAIDA TOTAL"      
      -
        Campo: "Tipologia__c"
        Valor: "CAIDA TOTAL"      
      -
        Campo: "EstadoSistemaLegado__c"
        Valor: "EN ESPERA CLIENTE"         
  NombreObjeto: "Case"


