# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
# --- Example Backend HTTP Requester ---
backend:
  protocol: "HTTPS"
  host: "prod-backend.example.com"
  port: "443"
  basePath: "/api/v1"
  resources:
    path: "/resources"
    get:
      method: "GET"
    post:
      method: "POST"