# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
# --- Example Backend HTTP Requester ---
order-mngt-papi:
  protocol: "HTTP"
  host: "order-management-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/v1"
  resources:
    path: "/cancelProductOrder"
    get:
      method: "GET"
    post:
      method: "POST"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"