#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Su tipo de entrega de factura ha sido actualizado exitosamente
    required: false
  detail:
    type: object
    properties:
      nipGenerated:
        type: string
        example: ''
        required: false
      orderStatus:
        type: string
        example: ''
        required: false
      portabilityStatus:
        type: string
        example: ''
        required: false
      status:
        type: string
        example: ''
        required: false
      message:
        type: string
        example: ''
        required: false
