#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  responseMessage:
    type: string
    example: succes
    required: false
  orders:
    type: array
    items:
      type: object
      properties:
        agenda:
          type: object
          properties:
            installerId:
              type: string
              example: ''
              required: false
            isSuspended:
              type: boolean
              example: false
              required: false
            suspensionInfo:
              type: string
              example: ''
              required: false
            trackingMap:
              type: string
              example: >-
                https://suma.etb.co:88/MapTech/MapaTecnico/?Encpyt=wMWSpo2r:bB9czh3W9Fp_Q=
              required: false
            date:
              type: object
              properties:
                date:
                  type: datetime
                  example: '2025-08-19T11:52:26.539Z'
                  required: false
                format1:
                  type: string
                  example: 19/08
                  required: false
                format2:
                  type: string
                  example: 19/08/2025
                  required: false
                format3:
                  type: string
                  example: 19/08/2025 11:52:26
                  required: false
                format4:
                  type: string
                  example: 19/08/2025 11:52:26 AM
                  required: false
                day:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '19'
                      required: false
                    format2:
                      type: string
                      example: Mar.
                      required: false
                    format3:
                      type: string
                      example: Martes
                      required: false
                month:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '08'
                      required: false
                    format2:
                      type: string
                      example: Ago.
                      required: false
                    format3:
                      type: string
                      example: Agosto
                      required: false
                year:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '25'
                      required: false
                    format2:
                      type: string
                      example: '2025'
                      required: false
                    format3:
                      type: string
                      example: '02025'
                      required: false
                hour:
                  type: object
                  properties:
                    format1:
                      type: time-only
                      example: '11:52:26'
                      required: false
                    format2:
                      type: string
                      example: 11:52:26 AM
                      required: false
                    format3:
                      type: string
                      example: '11'
                      required: false
                    format4:
                      type: string
                      example: 11 AM
                      required: false
                    format5:
                      type: string
                      example: '52'
                      required: false
                    format6:
                      type: string
                      example: '26'
                      required: false
            idEta:
              type: string
              example: ''
              required: false
            idOsm:
              type: string
              example: ''
              required: false
            isScheduled:
              type: boolean
              example: true
              required: false
            state:
              type: string
              example: ''
              required: false
            timeslot:
              type: object
              properties:
                endTime:
                  type: string
                  example: ''
                  required: false
                initTime:
                  type: string
                  example: ''
                  required: false
                timeslotBeauty:
                  type: string
                  example: ''
                  required: false
                timeslotTechnical:
                  type: string
                  example: ''
                  required: false
                timeslotUser:
                  type: string
                  example: ''
                  required: false
            zone:
              type: string
              example: ''
              required: false
        cancelationInfo:
          type: string
          example: ''
          required: false
        channel:
          type: string
          example: Canal_Fibra
          required: false
        characteristics:
          type: array
          items:
            type: object
            properties:
              action:
                type: string
                example: ''
                required: false
              name:
                type: string
                example: Incidencia_Remedy
                required: false
              value:
                type: string
                example: INC000014037696
                required: false
        creatorUser:
          type: string
          example: orquestador
          required: false
        customer:
          type: object
          properties:
            atdp:
              type: string
              example: ''
              required: false
            birthday:
              type: string
              example: ''
              required: false
            business:
              type: string
              example: ''
              required: false
            collectionCommunications:
              type: string
              example: ''
              required: false
            documentNumber:
              type: string
              example: '79715143'
              required: false
            documentType:
              type: string
              example: CC
              required: false
            email:
              type: string
              example: ''
              required: false
            mobilePhone:
              type: string
              example: '3118069700'
              required: false
            mobilePhone2:
              type: string
              example: ''
              required: false
            name:
              type: object
              properties:
                completeName:
                  type: string
                  example: ''
                  required: false
                firstName:
                  type: string
                  example: JAIRO
                  required: false
                firstSurname:
                  type: string
                  example: MONTOYA
                  required: false
                names:
                  type: string
                  example: JAIRO
                  required: false
                secondName:
                  type: string
                  example: ''
                  required: false
                secondSurname:
                  type: string
                  example: ' ORTIZ'
                  required: false
                surnames:
                  type: string
                  example: MONTOYA  ORTIZ
                  required: false
            segmentation:
              type: object
              properties:
                attentionScheme:
                  type: string
                  example: ''
                  required: false
                category:
                  type: string
                  example: Plata
                  required: false
                profile:
                  type: string
                  example: ''
                  required: false
                segment:
                  type: string
                  example: Hogares
                  required: false
                uen:
                  type: string
                  example: Hogares y mipymes
                  required: false
                segmentUen:
                  type: string
                  example: Hogares
                  required: false
            validationCode:
              type: string
              example: ''
              required: false
        modifyingUser:
          type: string
          example: orquestador
          required: false
        newOffer:
          type: object
          properties:
            address:
              type: object
              properties:
                city:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '11001'
                      required: false
                    name:
                      type: string
                      example: BOGOTA D.C.
                      required: false
                department:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '11'
                      required: false
                    name:
                      type: string
                      example: BOGOTA
                      required: false
                coverage:
                  type: object
                  properties:
                    distanceType:
                      type: string
                      example: ''
                      required: false
                    gisAddress:
                      type: string
                      example: '612802304579161439'
                      required: false
                    idPlot:
                      type: string
                      example: '22'
                      required: false
                    latitude:
                      type: number
                      example: 4.622048062
                      required: false
                    longitude:
                      type: number
                      example: -74.17719331
                      required: false
                    molecule:
                      type: string
                      example: ''
                      required: false
                    name:
                      type: string
                      example: FHO05
                      required: false
                    olt:
                      type: string
                      example: BOHOAL736005
                      required: false
                    owner:
                      type: string
                      example: ETB
                      required: false
                    district:
                      type: string
                      example: ''
                      required: false
                    locality:
                      type: string
                      example: ''
                      required: false
                    localityId:
                      type: string
                      example: '08'
                      required: false
                    stratum:
                      type: integer
                      example: 2
                      required: false
                    technology:
                      type: string
                      example: FTTH
                      required: false
                    type:
                      type: string
                      example: MOLECULA
                      required: false
                    zone:
                      type: string
                      example: HOLANDA
                      required: false
                country:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 593b0ac99a8e4177d410df4d
                      required: false
                    name:
                      type: string
                      example: ''
                      required: false
                id:
                  type: integer
                  example: 3
                  required: false
                state:
                  type: string
                  example: ACTIVO
                  required: false
                streetAddress:
                  type: string
                  example: CL 53 SUR 82A 24
                  required: false
                type:
                  type: string
                  example: INSTALACION
                  required: false
            billing:
              type: object
              properties:
                address:
                  type: string
                  example: ''
                  required: false
                billingAccount:
                  type: string
                  example: '12054085171'
                  required: false
                billingAccountFather:
                  type: string
                  example: '12054085171'
                  required: false
                billingDueDay:
                  type: string
                  example: '0'
                  required: false
                billingDueOcsDay:
                  type: string
                  example: '30'
                  required: false
                billingDueDayUser:
                  type: string
                  example: '31'
                  required: false
                canUpdateDeliveryType:
                  type: string
                  example: ''
                  required: false
                cycle:
                  type: string
                  example: '38'
                  required: false
                deliveryType:
                  type: string
                  example: Electronica
                  required: false
                email:
                  type: string
                  example: YAIRUS4@GMAIL.COM
                  required: false
                idSalesforce:
                  type: string
                  example: ''
                  required: false
                phone:
                  type: string
                  example: ''
                  required: false
                state:
                  type: string
                  example: ACTIVO
                  required: false
                stratum:
                  type: string
                  example: '2'
                  required: false
                type:
                  type: string
                  example: Detallada
                  required: false
            plan:
              type: object
              properties:
                home:
                  type: object
                  properties:
                    internet:
                      type: object
                      properties:
                        capacity:
                          type: string
                          example: ''
                          required: false
                        descentSpeed:
                          type: object
                          properties:
                            description:
                              type: string
                              example: 50M
                              required: false
                            unity:
                              type: string
                              example: M
                              required: false
                            value:
                              type: string
                              example: '50'
                              required: false
                        isTwin:
                          type: boolean
                          example: true
                          required: false
                        secundary:
                          type: array
                          items:
                            type: object
                            properties:
                              count:
                                type: string
                                example: ''
                                required: false
                              desc:
                                type: string
                                example: IP Dinámica
                                required: false
                              description:
                                type: string
                                example: IP Dinámica
                                required: false
                              icon:
                                type: string
                                example: ''
                                required: false
                              name:
                                type: string
                                example: IP DINÁMICA
                                required: false
                              type:
                                type: string
                                example: Secundario
                                required: false
                        sharedCapacity:
                          type: string
                          example: ''
                          required: false
                        uploadSpeed:
                          type: object
                          properties:
                            description:
                              type: string
                              example: 50M
                              required: false
                            unity:
                              type: string
                              example: M
                              required: false
                            value:
                              type: string
                              example: '50'
                              required: false
                    tv:
                      type: string
                      example: ''
                      required: false
                    voice:
                      type: object
                      properties:
                        capacity:
                          type: object
                          properties:
                            description:
                              type: string
                              example: Llamadas ilimitadas
                              required: false
                            unity:
                              type: string
                              example: MIN
                              required: false
                            value:
                              type: string
                              example: Ilimitados
                              required: false
                        secundary:
                          type: array
                          items:
                            type: object
                            properties:
                              count:
                                type: string
                                example: ''
                                required: false
                              desc:
                                type: string
                                example: Llamadas con 3 líneas al mismo tiempo
                                required: false
                              description:
                                type: string
                                example: Llamadas con 3 líneas al mismo tiempo
                                required: false
                              icon:
                                type: string
                                example: ''
                                required: false
                              name:
                                type: string
                                example: CONFERENCIA ENTRE TRES
                                required: false
                              type:
                                type: string
                                example: Secundario
                                required: false
                mobile:
                  type: string
                  example: ''
                  required: false
                promotions:
                  type: array
                  items: {}
                available:
                  type: boolean
                  example: false
                  required: false
                contracted:
                  type: boolean
                  example: false
                  required: false
                description:
                  type: array
                  items:
                    type: string
                executionPlan:
                  type: array
                  items:
                    type: object
                    properties:
                      features:
                        type: array
                        items:
                          type: object
                          properties:
                            description:
                              type: string
                              example: >-
                                Paga el valor original de tu plan DUO 50M  $
                                46,128
                              required: false
                            differential:
                              type: boolean
                              example: false
                              required: false
                            discount:
                              type: boolean
                              example: false
                              required: false
                            outstanding:
                              type: boolean
                              example: false
                              required: false
                            type:
                              type: string
                              example: Plan
                              required: false
                      month:
                        type: integer
                        example: 1
                        required: false
                      saving:
                        type: string
                        example: ''
                        required: false
                      savingStr:
                        type: string
                        example: ''
                        required: false
                      state:
                        type: string
                        example: ''
                        required: false
                      value:
                        type: integer
                        example: 46128
                        required: false
                      valueStr:
                        type: string
                        example: $ 46.128
                        required: false
                id:
                  type: string
                  example: '4774'
                  required: false
                idsPackaging:
                  type: string
                  example: ''
                  required: false
                installationCharges:
                  type: object
                  properties:
                    acceptPermanenceClause:
                      type: string
                      example: ''
                      required: false
                    installationChargesInternet:
                      type: integer
                      example: 750000
                      required: false
                    installationChargesTv:
                      type: integer
                      example: 0
                      required: false
                    installationChargesVoice:
                      type: integer
                      example: 750000
                      required: false
                    total:
                      type: integer
                      example: 1500000
                      required: false
                isPacking:
                  type: boolean
                  example: false
                  required: false
                isZoned:
                  type: boolean
                  example: false
                  required: false
                name:
                  type: string
                  example: 'DUO 50M '
                  required: false
                nameTechnical:
                  type: string
                  example: MIGRACION- DUO 50M HOG METRO
                  required: false
                outstanding:
                  type: boolean
                  example: false
                  required: false
                price:
                  type: object
                  properties:
                    anticipatedPayment:
                      type: boolean
                      example: false
                      required: false
                    iva:
                      type: integer
                      example: 0
                      required: false
                    value:
                      type: integer
                      example: 46128
                      required: false
                    valueStr:
                      type: string
                      example: $ 46.128
                      required: false
                    valueWithoutIva:
                      type: integer
                      example: 46128
                      required: false
                    valueWithoutIvaStr:
                      type: string
                      example: $ 46.128
                      required: false
                    validity:
                      type: string
                      example: Cargo fijo mensual
                      required: false
                retencion:
                  type: boolean
                  example: false
                  required: false
                saving:
                  type: integer
                  example: 0
                  required: false
                savingStr:
                  type: string
                  example: $ 0
                  required: false
                stratum:
                  type: string
                  example: ''
                  required: false
                subtype:
                  type: string
                  example: Internet + Telefonía
                  required: false
                svasFeatured:
                  type: string
                  example: ''
                  required: false
                svasIncluded:
                  type: string
                  example: ''
                  required: false
                technology:
                  type: string
                  example: FTTH
                  required: false
                type:
                  type: string
                  example: DUO
                  required: false
                value:
                  type: integer
                  example: 46128
                  required: false
                valueStr:
                  type: string
                  example: $ 46.128
                  required: false
                zoned:
                  type: string
                  example: ''
                  required: false
            promotions:
              type: string
              example: ''
              required: false
            svas:
              type: array
              items:
                type: object
                properties:
                  mobile:
                    type: string
                    example: ''
                    required: false
                  promotions:
                    type: array
                    items: {}
                  subSvas:
                    type: string
                    example: ''
                    required: false
                  available:
                    type: boolean
                    example: false
                    required: false
                  description:
                    type: string
                    example: >-
                      Es  un dispositivo que ayuda a mejorar  la experiencia
                      actual del servicio de internet , tanto en  cobertura cómo
                      en  velocidad a tráves de WIFI.
                    required: false
                  characteristics:
                    type: array
                    items:
                      type: object
                      properties:
                        characteristic:
                          type: string
                          example: >-
                            Extiende tu red Wi-Fi (1 equipo) y disfruta de la
                            velocidad de la fibra
                          required: false
                        icon:
                          type: string
                          example: ''
                          required: false
                  conflicting:
                    type: array
                    items:
                      type: string
                  contracted:
                    type: boolean
                    example: false
                    required: false
                  executionPlan:
                    type: array
                    items:
                      type: object
                      properties:
                        features:
                          type: array
                          items:
                            type: object
                            properties:
                              description:
                                type: string
                                example: >-
                                  Paga el valor original de tu servicio
                                  adicional WIFI PLUS TIPO 1 $ 6,000
                                required: false
                              differential:
                                type: boolean
                                example: false
                                required: false
                              discount:
                                type: boolean
                                example: false
                                required: false
                              outstanding:
                                type: boolean
                                example: false
                                required: false
                              type:
                                type: string
                                example: SVA
                                required: false
                        month:
                          type: integer
                          example: 1
                          required: false
                        saving:
                          type: string
                          example: ''
                          required: false
                        savingStr:
                          type: string
                          example: ''
                          required: false
                        state:
                          type: string
                          example: ''
                          required: false
                        value:
                          type: integer
                          example: 6000
                          required: false
                        valueStr:
                          type: string
                          example: $ 6.000
                          required: false
                  executionPlanDifferential:
                    type: string
                    example: ''
                    required: false
                  icon:
                    type: string
                    example: >-
                      https://strmietb.blob.core.windows.net/imagenes/flujocomercial/AP/img-logo-ap.svg
                    required: false
                  id:
                    type: string
                    example: '3067'
                    required: false
                  idsOld:
                    type: string
                    example: ''
                    required: false
                  mandatory:
                    type: string
                    example: ''
                    required: false
                  name:
                    type: string
                    example: WIFI PLUS TIPO 1
                    required: false
                  price:
                    type: object
                    properties:
                      anticipatedPayment:
                        type: boolean
                        example: false
                        required: false
                      iva:
                        type: integer
                        example: 19
                        required: false
                      value:
                        type: integer
                        example: 6000
                        required: false
                      valueStr:
                        type: string
                        example: $ 6.000
                        required: false
                      valueWithoutIva:
                        type: integer
                        example: 5042
                        required: false
                      valueWithoutIvaStr:
                        type: string
                        example: $ 5.042
                        required: false
                      validity:
                        type: string
                        example: Cargo fijo mensual
                        required: false
                  quantity:
                    type: object
                    properties:
                      available:
                        type: integer
                        example: 2
                        required: false
                      contracted:
                        type: integer
                        example: 0
                        required: false
                  saving:
                    type: string
                    example: ''
                    required: false
                  serviceType:
                    type: string
                    example: INTERNET
                    required: false
                  value:
                    type: integer
                    example: 6000
                    required: false
                  visibility:
                    type: object
                    properties:
                      action:
                        type: string
                        example: Nin
                        required: false
                      conditioned:
                        type: boolean
                        example: true
                        required: false
                      plans:
                        type: array
                        items:
                          type: string
        oldOffer:
          type: object
          properties:
            address:
              type: object
              properties:
                city:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '11001'
                      required: false
                    name:
                      type: string
                      example: BOGOTA D.C.
                      required: false
                department:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '11'
                      required: false
                    name:
                      type: string
                      example: BOGOTA
                      required: false
                coverage:
                  type: object
                  properties:
                    distanceType:
                      type: string
                      example: ''
                      required: false
                    gisAddress:
                      type: string
                      example: '612802304579161439'
                      required: false
                    idPlot:
                      type: string
                      example: '22'
                      required: false
                    latitude:
                      type: number
                      example: 4.622048062
                      required: false
                    longitude:
                      type: number
                      example: -74.17719331
                      required: false
                    molecule:
                      type: string
                      example: ''
                      required: false
                    name:
                      type: string
                      example: FHO05
                      required: false
                    olt:
                      type: string
                      example: BOHOAL736005
                      required: false
                    owner:
                      type: string
                      example: ETB
                      required: false
                    district:
                      type: string
                      example: ''
                      required: false
                    locality:
                      type: string
                      example: ''
                      required: false
                    localityId:
                      type: string
                      example: '08'
                      required: false
                    stratum:
                      type: integer
                      example: 2
                      required: false
                    technology:
                      type: string
                      example: FTTH
                      required: false
                    type:
                      type: string
                      example: MOLECULA
                      required: false
                    zone:
                      type: string
                      example: HOLANDA
                      required: false
                country:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 593b0ac99a8e4177d410df4d
                      required: false
                    name:
                      type: string
                      example: ''
                      required: false
                id:
                  type: integer
                  example: 3
                  required: false
                state:
                  type: string
                  example: ACTIVO
                  required: false
                streetAddress:
                  type: string
                  example: CL 53 SUR 82A 24
                  required: false
                type:
                  type: string
                  example: INSTALACION
                  required: false
            billing:
              type: object
              properties:
                address:
                  type: string
                  example: ''
                  required: false
                billingAccount:
                  type: string
                  example: '12054085171'
                  required: false
                billingAccountFather:
                  type: string
                  example: '12054085171'
                  required: false
                billingDueDay:
                  type: string
                  example: '0'
                  required: false
                billingDueOcsDay:
                  type: string
                  example: '30'
                  required: false
                billingDueDayUser:
                  type: string
                  example: '31'
                  required: false
                canUpdateDeliveryType:
                  type: string
                  example: ''
                  required: false
                cycle:
                  type: string
                  example: '38'
                  required: false
                deliveryType:
                  type: string
                  example: Electronica
                  required: false
                email:
                  type: string
                  example: YAIRUS4@GMAIL.COM
                  required: false
                idSalesforce:
                  type: string
                  example: ''
                  required: false
                phone:
                  type: string
                  example: ''
                  required: false
                state:
                  type: string
                  example: ACTIVO
                  required: false
                stratum:
                  type: string
                  example: '2'
                  required: false
                type:
                  type: string
                  example: Detallada
                  required: false
            plan:
              type: object
              properties:
                home:
                  type: object
                  properties:
                    internet:
                      type: object
                      properties:
                        capacity:
                          type: string
                          example: ''
                          required: false
                        descentSpeed:
                          type: object
                          properties:
                            description:
                              type: string
                              example: 50M
                              required: false
                            unity:
                              type: string
                              example: M
                              required: false
                            value:
                              type: string
                              example: '50'
                              required: false
                        isTwin:
                          type: boolean
                          example: true
                          required: false
                        secundary:
                          type: array
                          items:
                            type: object
                            properties:
                              count:
                                type: string
                                example: ''
                                required: false
                              desc:
                                type: string
                                example: IP Dinámica
                                required: false
                              description:
                                type: string
                                example: IP Dinámica
                                required: false
                              icon:
                                type: string
                                example: ''
                                required: false
                              name:
                                type: string
                                example: IP DINÁMICA
                                required: false
                              type:
                                type: string
                                example: Secundario
                                required: false
                        sharedCapacity:
                          type: string
                          example: ''
                          required: false
                        uploadSpeed:
                          type: object
                          properties:
                            description:
                              type: string
                              example: 50M
                              required: false
                            unity:
                              type: string
                              example: M
                              required: false
                            value:
                              type: string
                              example: '50'
                              required: false
                    tv:
                      type: string
                      example: ''
                      required: false
                    voice:
                      type: object
                      properties:
                        capacity:
                          type: object
                          properties:
                            description:
                              type: string
                              example: Llamadas ilimitadas
                              required: false
                            unity:
                              type: string
                              example: MIN
                              required: false
                            value:
                              type: string
                              example: Ilimitados
                              required: false
                        secundary:
                          type: array
                          items:
                            type: object
                            properties:
                              count:
                                type: string
                                example: ''
                                required: false
                              desc:
                                type: string
                                example: Llamadas con 3 líneas al mismo tiempo
                                required: false
                              description:
                                type: string
                                example: Llamadas con 3 líneas al mismo tiempo
                                required: false
                              icon:
                                type: string
                                example: ''
                                required: false
                              name:
                                type: string
                                example: CONFERENCIA ENTRE TRES
                                required: false
                              type:
                                type: string
                                example: Secundario
                                required: false
                mobile:
                  type: string
                  example: ''
                  required: false
                promotions:
                  type: array
                  items: {}
                available:
                  type: boolean
                  example: false
                  required: false
                contracted:
                  type: boolean
                  example: false
                  required: false
                description:
                  type: array
                  items:
                    type: string
                executionPlan:
                  type: array
                  items:
                    type: object
                    properties:
                      features:
                        type: array
                        items:
                          type: object
                          properties:
                            description:
                              type: string
                              example: >-
                                Paga el valor original de tu plan DUO 50M  $
                                46,128
                              required: false
                            differential:
                              type: boolean
                              example: false
                              required: false
                            discount:
                              type: boolean
                              example: false
                              required: false
                            outstanding:
                              type: boolean
                              example: false
                              required: false
                            type:
                              type: string
                              example: Plan
                              required: false
                      month:
                        type: integer
                        example: 1
                        required: false
                      saving:
                        type: string
                        example: ''
                        required: false
                      savingStr:
                        type: string
                        example: ''
                        required: false
                      state:
                        type: string
                        example: ''
                        required: false
                      value:
                        type: integer
                        example: 46128
                        required: false
                      valueStr:
                        type: string
                        example: $ 46.128
                        required: false
                id:
                  type: string
                  example: '4774'
                  required: false
                idsPackaging:
                  type: string
                  example: ''
                  required: false
                installationCharges:
                  type: object
                  properties:
                    acceptPermanenceClause:
                      type: string
                      example: ''
                      required: false
                    installationChargesInternet:
                      type: integer
                      example: 750000
                      required: false
                    installationChargesTv:
                      type: integer
                      example: 0
                      required: false
                    installationChargesVoice:
                      type: integer
                      example: 750000
                      required: false
                    total:
                      type: integer
                      example: 1500000
                      required: false
                isPacking:
                  type: boolean
                  example: false
                  required: false
                isZoned:
                  type: boolean
                  example: false
                  required: false
                name:
                  type: string
                  example: 'DUO 50M '
                  required: false
                nameTechnical:
                  type: string
                  example: MIGRACION- DUO 50M HOG METRO
                  required: false
                outstanding:
                  type: boolean
                  example: false
                  required: false
                price:
                  type: object
                  properties:
                    anticipatedPayment:
                      type: boolean
                      example: false
                      required: false
                    iva:
                      type: integer
                      example: 0
                      required: false
                    value:
                      type: integer
                      example: 46128
                      required: false
                    valueStr:
                      type: string
                      example: $ 46.128
                      required: false
                    valueWithoutIva:
                      type: integer
                      example: 46128
                      required: false
                    valueWithoutIvaStr:
                      type: string
                      example: $ 46.128
                      required: false
                    validity:
                      type: string
                      example: Cargo fijo mensual
                      required: false
                retencion:
                  type: boolean
                  example: false
                  required: false
                saving:
                  type: integer
                  example: 0
                  required: false
                savingStr:
                  type: string
                  example: $ 0
                  required: false
                stratum:
                  type: string
                  example: ''
                  required: false
                subtype:
                  type: string
                  example: Internet + Telefonía
                  required: false
                svasFeatured:
                  type: string
                  example: ''
                  required: false
                svasIncluded:
                  type: string
                  example: ''
                  required: false
                technology:
                  type: string
                  example: FTTH
                  required: false
                type:
                  type: string
                  example: DUO
                  required: false
                value:
                  type: integer
                  example: 46128
                  required: false
                valueStr:
                  type: string
                  example: $ 46.128
                  required: false
                zoned:
                  type: string
                  example: ''
                  required: false
            promotions:
              type: string
              example: ''
              required: false
            svas:
              type: array
              items:
                type: object
                properties:
                  mobile:
                    type: string
                    example: ''
                    required: false
                  promotions:
                    type: array
                    items: {}
                  subSvas:
                    type: string
                    example: ''
                    required: false
                  available:
                    type: boolean
                    example: false
                    required: false
                  description:
                    type: string
                    example: >-
                      Es  un dispositivo que ayuda a mejorar  la experiencia
                      actual del servicio de internet , tanto en  cobertura cómo
                      en  velocidad a tráves de WIFI.
                    required: false
                  characteristics:
                    type: array
                    items:
                      type: object
                      properties:
                        characteristic:
                          type: string
                          example: >-
                            Extiende tu red Wi-Fi (1 equipo) y disfruta de la
                            velocidad de la fibra
                          required: false
                        icon:
                          type: string
                          example: ''
                          required: false
                  conflicting:
                    type: array
                    items:
                      type: string
                  contracted:
                    type: boolean
                    example: false
                    required: false
                  executionPlan:
                    type: array
                    items:
                      type: object
                      properties:
                        features:
                          type: array
                          items:
                            type: object
                            properties:
                              description:
                                type: string
                                example: >-
                                  Paga el valor original de tu servicio
                                  adicional WIFI PLUS TIPO 1 $ 6,000
                                required: false
                              differential:
                                type: boolean
                                example: false
                                required: false
                              discount:
                                type: boolean
                                example: false
                                required: false
                              outstanding:
                                type: boolean
                                example: false
                                required: false
                              type:
                                type: string
                                example: SVA
                                required: false
                        month:
                          type: integer
                          example: 1
                          required: false
                        saving:
                          type: string
                          example: ''
                          required: false
                        savingStr:
                          type: string
                          example: ''
                          required: false
                        state:
                          type: string
                          example: ''
                          required: false
                        value:
                          type: integer
                          example: 6000
                          required: false
                        valueStr:
                          type: string
                          example: $ 6.000
                          required: false
                  executionPlanDifferential:
                    type: string
                    example: ''
                    required: false
                  icon:
                    type: string
                    example: >-
                      https://strmietb.blob.core.windows.net/imagenes/flujocomercial/AP/img-logo-ap.svg
                    required: false
                  id:
                    type: string
                    example: '3067'
                    required: false
                  idsOld:
                    type: string
                    example: ''
                    required: false
                  mandatory:
                    type: string
                    example: ''
                    required: false
                  name:
                    type: string
                    example: WIFI PLUS TIPO 1
                    required: false
                  price:
                    type: object
                    properties:
                      anticipatedPayment:
                        type: boolean
                        example: false
                        required: false
                      iva:
                        type: integer
                        example: 19
                        required: false
                      value:
                        type: integer
                        example: 6000
                        required: false
                      valueStr:
                        type: string
                        example: $ 6.000
                        required: false
                      valueWithoutIva:
                        type: integer
                        example: 5042
                        required: false
                      valueWithoutIvaStr:
                        type: string
                        example: $ 5.042
                        required: false
                      validity:
                        type: string
                        example: Cargo fijo mensual
                        required: false
                  quantity:
                    type: object
                    properties:
                      available:
                        type: integer
                        example: 2
                        required: false
                      contracted:
                        type: integer
                        example: 0
                        required: false
                  saving:
                    type: string
                    example: ''
                    required: false
                  serviceType:
                    type: string
                    example: INTERNET
                    required: false
                  value:
                    type: integer
                    example: 6000
                    required: false
                  visibility:
                    type: object
                    properties:
                      action:
                        type: string
                        example: Nin
                        required: false
                      conditioned:
                        type: boolean
                        example: true
                        required: false
                      plans:
                        type: array
                        items:
                          type: string
        promotions:
          type: string
          example: ''
          required: false
        subChannel:
          type: string
          example: ''
          required: false
        technician:
          type: object
          properties:
            avatar:
              type: string
              example: ''
              required: false
            id:
              type: string
              example: '25006323'
              required: false
            name:
              type: string
              example: ''
              required: false
        technology:
          type: string
          example: FTTH
          required: false
        creationTime:
          type: object
          properties:
            date:
              type: datetime
              example: '2025-08-19T11:52:26.544Z'
              required: false
            format1:
              type: string
              example: 19/08
              required: false
            format2:
              type: string
              example: 19/08/2025
              required: false
            format3:
              type: string
              example: 19/08/2025 11:52:26
              required: false
            format4:
              type: string
              example: 19/08/2025 11:52:26 AM
              required: false
            day:
              type: object
              properties:
                format1:
                  type: string
                  example: '19'
                  required: false
                format2:
                  type: string
                  example: Mar.
                  required: false
                format3:
                  type: string
                  example: Martes
                  required: false
            month:
              type: object
              properties:
                format1:
                  type: string
                  example: '08'
                  required: false
                format2:
                  type: string
                  example: Ago.
                  required: false
                format3:
                  type: string
                  example: Agosto
                  required: false
            year:
              type: object
              properties:
                format1:
                  type: string
                  example: '25'
                  required: false
                format2:
                  type: string
                  example: '2025'
                  required: false
                format3:
                  type: string
                  example: '02025'
                  required: false
            hour:
              type: object
              properties:
                format1:
                  type: time-only
                  example: '11:52:26'
                  required: false
                format2:
                  type: string
                  example: 11:52:26 AM
                  required: false
                format3:
                  type: string
                  example: '11'
                  required: false
                format4:
                  type: string
                  example: 11 AM
                  required: false
                format5:
                  type: string
                  example: '52'
                  required: false
                format6:
                  type: string
                  example: '26'
                  required: false
        cun:
          type: string
          example: '4347250001199199'
          required: false
        id:
          type: string
          example: MDM-PQR-52507473
          required: false
        modificationTime:
          type: object
          properties:
            date:
              type: datetime
              example: '2025-08-19T11:52:26.544Z'
              required: false
            format1:
              type: string
              example: 19/08
              required: false
            format2:
              type: string
              example: 19/08/2025
              required: false
            format3:
              type: string
              example: 19/08/2025 11:52:26
              required: false
            format4:
              type: string
              example: 19/08/2025 11:52:26 AM
              required: false
            day:
              type: object
              properties:
                format1:
                  type: string
                  example: '19'
                  required: false
                format2:
                  type: string
                  example: Mar.
                  required: false
                format3:
                  type: string
                  example: Martes
                  required: false
            month:
              type: object
              properties:
                format1:
                  type: string
                  example: '08'
                  required: false
                format2:
                  type: string
                  example: Ago.
                  required: false
                format3:
                  type: string
                  example: Agosto
                  required: false
            year:
              type: object
              properties:
                format1:
                  type: string
                  example: '25'
                  required: false
                format2:
                  type: string
                  example: '2025'
                  required: false
                format3:
                  type: string
                  example: '02025'
                  required: false
            hour:
              type: object
              properties:
                format1:
                  type: time-only
                  example: '11:52:26'
                  required: false
                format2:
                  type: string
                  example: 11:52:26 AM
                  required: false
                format3:
                  type: string
                  example: '11'
                  required: false
                format4:
                  type: string
                  example: 11 AM
                  required: false
                format5:
                  type: string
                  example: '52'
                  required: false
                format6:
                  type: string
                  example: '26'
                  required: false
        state:
          type: object
          properties:
            code:
              type: string
              example: O05
              required: false
            date:
              type: object
              properties:
                date:
                  type: datetime
                  example: '2025-08-19T11:52:26.549Z'
                  required: false
                format1:
                  type: string
                  example: 19/08
                  required: false
                format2:
                  type: string
                  example: 19/08/2025
                  required: false
                format3:
                  type: string
                  example: 19/08/2025 11:52:26
                  required: false
                format4:
                  type: string
                  example: 19/08/2025 11:52:26 AM
                  required: false
                day:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '19'
                      required: false
                    format2:
                      type: string
                      example: Mar.
                      required: false
                    format3:
                      type: string
                      example: Martes
                      required: false
                month:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '08'
                      required: false
                    format2:
                      type: string
                      example: Ago.
                      required: false
                    format3:
                      type: string
                      example: Agosto
                      required: false
                year:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '25'
                      required: false
                    format2:
                      type: string
                      example: '2025'
                      required: false
                    format3:
                      type: string
                      example: '02025'
                      required: false
                hour:
                  type: object
                  properties:
                    format1:
                      type: time-only
                      example: '11:52:26'
                      required: false
                    format2:
                      type: string
                      example: 11:52:26 AM
                      required: false
                    format3:
                      type: string
                      example: '11'
                      required: false
                    format4:
                      type: string
                      example: 11 AM
                      required: false
                    format5:
                      type: string
                      example: '52'
                      required: false
                    format6:
                      type: string
                      example: '26'
                      required: false
            description:
              type: string
              example: Datos Cliente
              required: false
            phase:
              type: string
              example: ORDERF
              required: false
            state:
              type: string
              example: ''
              required: false
        status:
          type: string
          example: PENDIENTE
          required: false
        tramite:
          type: object
          properties:
            execution:
              type: object
              properties:
                date:
                  type: datetime
                  example: '2025-08-19T11:52:26.544Z'
                  required: false
                format1:
                  type: string
                  example: 19/08
                  required: false
                format2:
                  type: string
                  example: 19/08/2025
                  required: false
                format3:
                  type: string
                  example: 19/08/2025 11:52:26
                  required: false
                format4:
                  type: string
                  example: 19/08/2025 11:52:26 AM
                  required: false
                day:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '19'
                      required: false
                    format2:
                      type: string
                      example: Mar.
                      required: false
                    format3:
                      type: string
                      example: Martes
                      required: false
                month:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '08'
                      required: false
                    format2:
                      type: string
                      example: Ago.
                      required: false
                    format3:
                      type: string
                      example: Agosto
                      required: false
                year:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '25'
                      required: false
                    format2:
                      type: string
                      example: '2025'
                      required: false
                    format3:
                      type: string
                      example: '02025'
                      required: false
                hour:
                  type: object
                  properties:
                    format1:
                      type: time-only
                      example: '11:52:26'
                      required: false
                    format2:
                      type: string
                      example: 11:52:26 AM
                      required: false
                    format3:
                      type: string
                      example: '11'
                      required: false
                    format4:
                      type: string
                      example: 11 AM
                      required: false
                    format5:
                      type: string
                      example: '52'
                      required: false
                    format6:
                      type: string
                      example: '26'
                      required: false
            reconection:
              type: string
              example: ''
              required: false
            subType:
              type: string
              example: ''
              required: false
            suspension:
              type: string
              example: ''
              required: false
            tramite:
              type: object
              properties:
                date:
                  type: datetime
                  example: '2025-08-19T11:52:26.544Z'
                  required: false
                format1:
                  type: string
                  example: 19/08
                  required: false
                format2:
                  type: string
                  example: 19/08/2025
                  required: false
                format3:
                  type: string
                  example: 19/08/2025 11:52:26
                  required: false
                format4:
                  type: string
                  example: 19/08/2025 11:52:26 AM
                  required: false
                day:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '19'
                      required: false
                    format2:
                      type: string
                      example: Mar.
                      required: false
                    format3:
                      type: string
                      example: Martes
                      required: false
                month:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '08'
                      required: false
                    format2:
                      type: string
                      example: Ago.
                      required: false
                    format3:
                      type: string
                      example: Agosto
                      required: false
                year:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '25'
                      required: false
                    format2:
                      type: string
                      example: '2025'
                      required: false
                    format3:
                      type: string
                      example: '02025'
                      required: false
                hour:
                  type: object
                  properties:
                    format1:
                      type: time-only
                      example: '11:52:26'
                      required: false
                    format2:
                      type: string
                      example: 11:52:26 AM
                      required: false
                    format3:
                      type: string
                      example: '11'
                      required: false
                    format4:
                      type: string
                      example: 11 AM
                      required: false
                    format5:
                      type: string
                      example: '52'
                      required: false
                    format6:
                      type: string
                      example: '26'
                      required: false
            type:
              type: string
              example: Aseguramiento
              required: false
            permanenceClause:
              type: boolean
              example: false
              required: false
