#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: succes
    required: false
  debt:
    type: object
    required: false
    properties:
      phone:
        type: string
        example: '6013103732'
        required: false
      billingAccount:
        type: string
        example: '15052876387'
        required: false
      totalAmount:
        type: integer
        example: 125000
        required: false
      currency:
        type: string
        example: COP
        required: false
      dueDate:
        type: date-only
        example: '2024-12-25'
        required: false
      status:
        type: string
        example: Vencida
        required: false
      reasons:
        type: array
        required: false
        items:
          type: object
          properties:
            code:
              type: string
              example: FACTURA_VENCIDA
              required: false
            description:
              type: string
              example: Factura vencida del mes anterior
              required: false
            amount:
              type: integer
              example: 89000
              required: false
