#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Métodos de pago consultados exitosamente.
    required: false
  paymentMethod:
    type: object
    required: false
    properties:
      id:
        type: string
        example: ''
        required: false
      services:
        type: array
        required: false
        items:
          type: object
          properties:
            billingAccount:
              type: string
              example: '1234567890'
              required: false
            icon:
              type: string
              example: mobile
              required: false
            nickname:
              type: string
              example: Mi Línea Principal
              required: false
            phone:
              type: string
              example: '6019980626'
              required: false
            plan:
              type: string
              example: Plan Postpago 30GB
              required: false
            scheduledPayment:
              type: object
              properties:
                creditCard:
                  type: string
                  example: '****1234'
                  required: false
                creditCardCompany:
                  type: string
                  example: VISA
                  required: false
