#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: LTE eSIM order created successfully
    required: false
  order:
    type: object
    properties:
      id:
        type: string
        example: 68ded01c7d0397ef7b0664cc
        required: false
      orderNumber:
        type: string
        example: MDM-LTE-000123456
        required: false
