#%RAML 1.0 DataType
properties:
  message_id:
    type: string
    example: "INC000004726616"
  status:
    type: string
    example: "delivered"
  Date:
    type: string
    example: "2022-09-05T14:07:30-05:00"