#%RAML 1.0 DataType
properties:
  CloseR_ResultadoTransaccion?:
    type: string
    example: "ERROR"
  CloseR_MensajeError?:
    type: string
    example: "No se han encontrado coincidencias con el Código de Resolución enviado, informe al administrador"
