#%RAML 1.0
title: product-xapi-services
version: v1
baseUri: https://product-xapi-services-{env}.us-e2.cloudhub.io/{version}
description: product information

protocols:
  - HTTPS

mediaType:
  - application/json

traits:
  tibcoHeaders: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml

securitySchemes:
  oauth_2_0: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

types:
  error-response: !include datatypes/response/error.raml

/productOffering:
  get:
    is:  
     - tibcoHeaders
    securedBy: [ oauth_2_0 ]
    description:  Permite consultar ofertas de productos
    queryParameters:
      ORIGIN:
        type: string
        example: "WHATSAPP"
        description: Parameter that allows the origin of the request to be identified
      CATEGORY:
        type: string
        required: false
        description: Categoria del producto
        example: ""
      FILTERS:
        type: string
        example: "Product_Type:value;Service_Type:value;Product_Subtype:value;"
        description: String used to apply filters to the query (follow example), separate the filter type and its value with a colon, and separate the number of filters with a semicolon.
        required: false
      LIMIT:
        type: number
        description: Limit on orders to display
        required: true
      OFFSET:
        type: string
        description: used to organize information and establish a logical order
        required: true
    responses:
      200:
        body:
          application/json:
            type: !include /datatypes/response/get-productOffering.raml
            example: !include /examples/response/get-productOffering.json
      400:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-400.json
      401:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-401.json
      404:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-404.json
      500:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-500.json
  /bags:
    get:
      is: 
      - tibcoHeaders 
      securedBy: [ oauth_2_0 ]
      description: Consulta Catalogo Bolsas
      queryParameters:
        ORIGIN:
          type: string
          example: "WHATSAPP"
          description: Parameter that allows the origin of the request to be identified
        AGRUPATION_NUMBER:
          type: string
          required: false
          description: Numero de agrupacion
          example: ""
        NAME:
          type: string
          required: false
          description: Nombre
          example: ""
      responses:
        200:
          body:
            application/json:
              type: !include /datatypes/response/get-bags.raml
              example: !include /examples/response/get-bags.json
        400:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-400.json
        401:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-401.json
        404:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-404.json
        500:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-500.json

/promotion:
  get:
    is: 
     - tibcoHeaders 
    securedBy: [ oauth_2_0 ]
    description: Consulta de promociones disponibles
    queryParameters:
      ORIGIN:
        type: string
        example: "WHATSAPP"
        description: Parameter that allows the origin of the request to be identified
      PLANS_TO_BE_APPLIED:
        type: array
        items: string
        required: false
        description: Categoria del producto
        example: ["274","215"]
      FILTERS:
        type: string
        example: "Key:value;"
        description: String used to apply filters to the query (follow example), separate the filter type and its value with a colon, and separate the number of filters with a semicolon.
        required: false
      LIMIT:
        type: number
        description: Limit on orders to display
        required: true
      OFFSET:
        type: string
        description: used to organize information and establish a logical order
        required: true
    responses:
      200:
        body:
          application/json:
            type: !include /datatypes/response/get-promotion.raml
            example: !include /examples/response/get-promotion.json
      400:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-400.json
      401:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-401.json
      404:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-404.json
      500:
        body:
          application/json:
            type: !include /datatypes/response/error.raml
            example: !include /examples/response/error-500.json

/productUsage:
  /notify:
    post:
      is: 
       - tibcoHeaders
      securedBy: [ oauth_2_0 ]
      displayName: Product Notification
      description: Product Notification
      queryParameters:
        ORIGIN:
          type: string
          example: "WHATSAPP"
          description: Parameter that allows the origin of the request to be identified
      body:
        application/json:
          type: !include /datatypes/request/notification-product.raml
          example: !include /examples/request/notification-product.json
      responses:
        200:
          body:
            application/json:
              type: !include /datatypes/response/notification-product.raml
              example: !include /examples/response/notification-product.json
        400:
          body:
            application/json:
              type: !include /datatypes/response/error_base.raml
              example: !include /examples/response/error-400.json
        401:
          body:
            application/json:
              type: !include /datatypes/response/error_base.raml
              example: !include /examples/response/error-401.json
        404:
          body:
            application/json:
              type: !include /datatypes/response/error_base.raml
              example: !include /examples/response/error-404.json
        500:
          body:
            application/json:
              type: !include /datatypes/response/error_base.raml
              example: !include /examples/response/error-500.json