#%RAML 1.0 NamedExample
value:
  consultTaskArrayOut: 
    status: "Exitoso"
    tasks: 
      -
        taskId: "TAS000000098333"
        nombreTask: "PRUEBA GRUPO SOPORTE TAREA"
        estadoSf: "CERRADO"
        estadoRmd: "Closed"
        "idTareaSf": "TOA8729257"
      -
        taskId: "TAS000000098467"
        nombreTask: "PRUENA"
        estadoSf: "CERRADO"
        estadoRmd: "Closed"
        idTareaSf: "TOA8733634"