#%RAML 1.0 NamedExample
value:
  status: 500
  code: "UNEXPECTED_ERROR"
  message:
    message: "EL ID de la Tarea enviado, ya existe generado en remedy"
  messageServer: ""
  cause:
    -
      origin: "remedy-sapi-services-dev"
      message: "org.mule.runtime.api.exception.DefaultMuleException"