#%RAML 1.0 Trait
headers:
#  correlationID?: 
#    description: Identificador de la peticion
#    type: string
#  processingServer?:
#    description: Nombre de servidor que procesa la peticion
#    type: string
#  status:
#    description: Codigo de estado de la ejecución del servicio. PASS o FAIL
#    type: string
#    enum: 
#      - PASS
#      - FAIL
#  responseDate?:
#    description: Fecha de respuesta
#    type: datetime
#  errorCode:
#    description: Codigo de error (si existe) relacionado con la ejecución del servicio a nivel de integración
#    type: string
#  errorDetailCode:
#    description: Código detallado del error (si existe) relacionado con la ejecución del servicio a nivel de integración
#    type: string
#  errorMessage:
#    description: Descripción del error (si existe) relacionado con la ejecución del servicio a nivel de integración
#    type: string
#  name?:
#    description: Nombre de la propiedad
#    type: string
#  value?:
#    description: Valor de la propiedad
#    type: string