#%RAML 1.0 DataType
type: object
properties:
  ProgramacionPortacion:
    type: object
    required: true
    properties:
      Header:
        type: object
        required: true
        properties:
          IdIntegracion:
            type: string
            required: true
            example: "MDM-MOV-3114267"
          System:
            type: string
            required: true
            example: "MDM-MOV"
      MensajeABD:
        type: object
        required: true
        properties:
          CabeceraMensaje:
            type: object
            required: true
            properties:
              IdentificadorProceso:
                type: string
                required: true
                example: "00007202406120100449"
              IdentificadorMensaje:
                type: string
                required: true
                example: "00007202405060000963"
              FechaCreacion:
                type: string
                required: true
                example: "20240612160524"
              TipoMensaje:
                type: string
                required: true
                example: "1006"
              Emisor:
                type: string
                required: true
                example: "00007"
              Observaciones:
                type: string
                required: true
                example: ""
          CuerpoMensaje:
            type: object
            required: true
            properties:
              ProgramacionPortacion:
                type: object
                required: true
                properties:
                  FechaVentanaCambio:
                    type: string
                    required: true
                    example: "20240613000000"