# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================

# --- Example Backend HTTP Requester ---
order-mngt-papi:
  token: "![encrypted_token_here]"
  client-id: "![efwusRki5dYotfJAqSSokwnGy6UbyyF2P6kB1ZuLAYbYwMnJuwg4rQ==]"
  client-secret: "![Nh49u89TTWqZrx8OvMtB0uO5ZmVedaUYoahXpKb0895g/WfHETz/ww==]"