#%RAML 1.0 ResourceType
get?:
  displayName: List <<resourcePathName | !uppercamelcase>>
  description: List <<resourcePathName | !uppercamelcase>>
  is:
    - support-api-services.security-clientid-trait:
    - support-api-services.RequestHeaders:
    - support-api-services.<<resourcePathName | !singularize | !uppercamelcase>>QueryParameters:
  responses:
    200:
      #is:
        #- support-api-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>GetResponse[]
post?:
  displayName: Create <<resourcePathName | !singularize | !uppercamelcase>>
  description: Create <<resourcePathName | !singularize | !uppercamelcase>>
  is:
    - support-api-services.security-clientid-trait:
    - support-api-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>PostRequest
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>PostResponse
put?:
  displayName: Update <<resourcePathName | !singularize | !uppercamelcase>>
  description: Update <<resourcePathName | !singularize | !uppercamelcase>>
  is:
    - support-api-services.security-clientid-trait:
    - support-api-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>PutRequest
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>PutResponse