#%RAML 1.0 NamedExample
value:
  pqrType: caso pqr
  pqrDate: 26/02/2021 23:50:09
  ordenNumber: "2253126"
  identificationType: NIT
  identification: "800130244"
  conexionNum: "0"
  system: SALESFORCE