#%RAML 1.0 NamedExample
value:
  Estado: "IN PROGRESS"
  Fecha_Estado: "2021-12-01T00:00:13.515-05:00"
  Servicios_Orden:
    -
      MDM_Servicio_Orden: 
        Codigo_Producto: "1-QB1VT4D"
        Accion: null
        Estado: "IN PROGRESS"
        Fecha_Estado: "2021-12-01T00:00:13.515-05:00"
        Caracteristica_Servicio: null
    -
      MDM_Servicio_Orden:
        Codigo_Producto: "1-QB4LRG9"
        Accion: null
        Estado: "COMPLETE"
        Fecha_Estado: "2021-12-01T00:00:13.515-05:00"
        Caracteristica_Servicio: null