#%RAML 1.0 NamedExample
value:
  sUsuarioETB?: ""
  sIMEI?: ""
  sMSISDN?: ""
  sNombrePropietario?: ""
  sTipoDocPropietario?: ""
  sDocPropietario?: ""
  sTelContactoPropietario?: ""
  sNombreContacto?: ""
  sDireccionContacto?: ""
  iTipoUsuarioAutorizado?: ""
  sTipoDoAutorizado?: ""
  sDocAutorizado?: ""
  sTelContactoAutorizado?: ""