#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Success
    required: false
  networks:
    type: array
    items:
      type: object
      properties:
        connectedDevices:
          type: array
          items:
            type: object
            properties:
              authenticated:
                type: boolean
                example: true
                required: false
              attributes:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: tipo
                      required: false
                    value:
                      type: string
                      example: wlan
                      required: false
              index:
                type: string
                example: '1'
                required: false
              isLan:
                type: boolean
                example: false
                required: false
              isWlan:
                type: boolean
                example: true
                required: false
              ip:
                type: string
                example: 192.168.1.50
                required: false
              linkRate:
                type: string
                example: '72'
                required: false
              locked:
                type: boolean
                example: false
                required: false
              mac:
                type: string
                example: AA:BB:CC:DD:EE:FF
                required: false
              name:
                type: string
                example: Cliente-Tablet
                required: false
              noise:
                type: string
                example: ''
                required: false
              serial:
                type: string
                example: ''
                required: false
              state:
                type: boolean
                example: true
                required: false
              snr:
                type: string
                example: ''
                required: false
              rrsi:
                type: string
                example: '-45'
                required: false
  totalDevices:
    type: integer
    example: 0
    required: false
  phone:
    type: string
    example: ''
    required: false