#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Success
    required: false
  equipments:
    type: array
    items:
      type: object
      properties:
        brand:
          type: string
          example: Nokia
          required: false
        firmware:
          type: string
          example: 3FE48xxx
          required: false
        isDual:
          type: boolean
          example: true
          required: false
        mac:
          type: string
          example: AA:BB:CC:DD:EE:FF
          required: false
        manageable:
          type: boolean
          example: true
          required: false
        model:
          type: string
          example: G-140W-C
          required: false
        serial:
          type: string
          example: ALCLB1234567
          required: false
        serialSlaves:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
                example: string
                required: false
        typeModem:
          type: string
          example: Modem
          required: false
        networks:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: Mi Red WiFi
                required: false
              type:
                type: string
                example: 2.4G
                required: false