#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  normalized:
    type: object
    required: false
    properties:
      diagnostic:
        type: object
        required: false
        properties:
          ontOn:
            type: boolean
            example: true
            required: false
          poorConnection:
            type: boolean
            example: false
            required: false
          speedFault:
            type: boolean
            example: false
            required: false
          status:
            type: string
            example: string
            required: false
          message:
            type: string
            example: string
            required: false
      massiveFailure:
        type: object
        required: false
        properties:
          endDate:
            type: object
            properties:
              date:
                type: string
                example: '2025-08-19T23:52:57.427+00:00'
                required: false
              format1:
                type: string
                example: 19/08
                required: false
              format2:
                type: string
                example: 19/08/2025
                required: false
              format3:
                type: string
                example: 19/08/2025 23:52:57
                required: false
              format4:
                type: string
                example: 19/08/2025 11:52:57 PM
                required: false
              day:
                type: object
                properties:
                  format1:
                    type: string
                    example: '19'
                    required: false
                  format2:
                    type: string
                    example: Mar.
                    required: false
                  format3:
                    type: string
                    example: Martes
                    required: false
              month:
                type: object
                properties:
                  format1:
                    type: string
                    example: '08'
                    required: false
                  format2:
                    type: string
                    example: Ago.
                    required: false
                  format3:
                    type: string
                    example: Agosto
                    required: false
              year:
                type: object
                properties:
                  format1:
                    type: string
                    example: '25'
                    required: false
                  format2:
                    type: string
                    example: '2025'
                    required: false
                  format3:
                    type: string
                    example: '02025'
                    required: false
              hour:
                type: object
                properties:
                  format1:
                    type: time-only
                    example: '23:52:57'
                    required: false
                  format2:
                    type: string
                    example: 11:52:57 PM
                    required: false
                  format3:
                    type: string
                    example: '23'
                    required: false
                  format4:
                    type: string
                    example: 11 PM
                    required: false
                  format5:
                    type: string
                    example: '52'
                    required: false
                  format6:
                    type: string
                    example: '57'
                    required: false
          expectedSolutionTime:
            type: integer
            example: 6
            required: false
          priority:
            type: integer
            example: 4
            required: false
          product:
            type: string
            example: INTERNET
            required: false
          numPqr:
            type: string
            example: MDM-PQR-4163009
            required: false
          startDate:
            type: object
            properties:
              date:
                type: string
                example: '2025-08-19T17:52:57.427+00:00'
                required: false
              format1:
                type: string
                example: 19/08
                required: false
              format2:
                type: string
                example: 19/08/2025
                required: false
              format3:
                type: string
                example: 19/08/2025 17:52:57
                required: false
              format4:
                type: string
                example: 19/08/2025 05:52:57 PM
                required: false
              day:
                type: object
                properties:
                  format1:
                    type: string
                    example: '19'
                    required: false
                  format2:
                    type: string
                    example: Mar.
                    required: false
                  format3:
                    type: string
                    example: Martes
                    required: false
              month:
                type: object
                properties:
                  format1:
                    type: string
                    example: '08'
                    required: false
                  format2:
                    type: string
                    example: Ago.
                    required: false
                  format3:
                    type: string
                    example: Agosto
                    required: false
              year:
                type: object
                properties:
                  format1:
                    type: string
                    example: '25'
                    required: false
                  format2:
                    type: string
                    example: '2025'
                    required: false
                  format3:
                    type: string
                    example: '02025'
                    required: false
              hour:
                type: object
                properties:
                  format1:
                    type: time-only
                    example: '17:52:57'
                    required: false
                  format2:
                    type: string
                    example: 05:52:57 PM
                    required: false
                  format3:
                    type: string
                    example: '17'
                    required: false
                  format4:
                    type: string
                    example: 05 PM
                    required: false
                  format5:
                    type: string
                    example: '52'
                    required: false
                  format6:
                    type: string
                    example: '57'
                    required: false
      semaphore:
        type: object
        required: false
        properties:
          attenuation:
            type: string
            example: ''
            required: false
          modem:
            type: string
            example: Verde
            required: false
          noise:
            type: string
            example: ''
            required: false
          potency:
            type: string
            example: Verde
            required: false
      modemPhoneProgrammed:
        type: string
        example: string
        required: false
      stateVoipAcs:
        type: string
        example: string
        required: false
      stateVoipIms:
        type: string
        example: string
        required: false
      stateMssInventory:
        type: string
        example: string
        required: false
      trafficLightColor:
        type: string
        example: ''
        required: false
      numPqr:
        type: string
        example: MDM-PQR-4163009
        required: false
      status:
        type: string
        example: string
        required: false
      message:
        type: string
        example: string
        required: false
      additionalChannels:
        type: string
        example: string
        required: false
      additionalServices:
        type: string
        example: string
        required: false
      decos:
        type: string
        example: string
        required: false
      stateSubscriberId:
        type: string
        example: string
        required: false
      brand:
        type: string
        example: ETB
        required: false
      phone:
        type: string
        example: '3057000421'
        required: false
      restarOnt:
        type: object
        required: false
        properties:
          executionDate:
            type: datetime-only
            example: '2024-12-19T10:30:00'
            required: false
          state:
            type: string
            example: SUCCESS
            required: false
          stateDescription:
            type: string
            example: ONT reiniciado exitosamente
            required: false
      serviceAccount:
        type: string
        example: ACC123456789
        required: false
      technology:
        type: string
        example: FTTH
        required: false
