#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: succes
    required: false
  detail:
    type: object
    required: false
    properties:
      numberPqr:
        type: string
        example: string
        required: false
      status:
        type: string
        example: string
        required: false
      message:
        type: string
        example: string
        required: false
