#%RAML 1.0 DataType 
type: array
items:
  type: object
  properties:
    _id:
      type: object
      properties:
        $oid:
          type: string
          example: 6363e646f46b161b641ab285
          required: false
    actualizacion_extractor:
      type: string
      example: '1'
      required: false
    row_id_pqr:
      type: string
      example: MDM-PQR-4096071
      required: false
    numero_pqr:
      type: string
      example: MDM-PQR-4096071
      required: false
    tipo_documento:
      type: string
      example: CC
      required: false
    numero_identificacion:
      type: string
      example: '645219196'
      required: false
    contacto_tipo_documento:
      type: string
      example: CC
      required: false
    contacto_numero_documento:
      type: string
      example: '1022403623'
      required: false
    id_servicio:
      type: string
      example: SR-6605579
      required: false
    numero_conexion:
      type: string
      example: '6018009582'
      required: false
    cuenta_servicio:
      type: string
      example: CS-1029503
      required: false
    cuenta_facturacion:
      type: string
      example: '15052880307'
      required: false
    producto:
      type: string
      example: INTERNET
      required: false
    numnumero_pedido:
      type: 'null'
      example: null
      required: false
    pqr_reclamo_pqr:
      type: 'null'
      example: null
      required: false
    tipo_pqr_reclamo:
      type: 'null'
      example: null
      required: false
    cun:
      type: string
      example: '4347220001249217'
      required: false
    servicio:
      type: 'null'
      example: null
      required: false
    tecnologia:
      type: string
      example: FO
      required: false
    tipo_pqr:
      type: string
      example: PRODUCTO
      required: false
    clase_pqr:
      type: string
      example: PETICION
      required: false
    motivo_pqr:
      type: string
      example: FALLA TECNICA
      required: false
    causal_pqr:
      type: string
      example: FALLA INTERNET
      required: false
    urgencia_pqr:
      type: 'null'
      example: null
      required: false
    impacto:
      type: 'null'
      example: null
      required: false
    sintoma_pqr:
      type: string
      example: SIN SERVICIO -F
      required: false
    valor_reclamado:
      type: string
      example: '0'
      required: false
    valor_ajustado:
      type: string
      example: '0'
      required: false
    fecha_creacion:
      type: object
      properties:
        $date:
          type: datetime
          example: '2022-11-03T11:03:24.361Z'
          required: false
    fecha_radicacion:
      type: object
      properties:
        $date:
          type: string
          example: '2022-11-03T21:03:19Z'
          required: false
    fecha_solucion:
      type: 'null'
      example: null
      required: false
    solucion:
      type: 'null'
      example: null
      required: false
    imputabilidad:
      type: 'null'
      example: null
      required: false
    estado_pqr:
      type: string
      example: Enviado a Segundo Nivel
      required: false
    estado_envio_remedy:
      type: 'null'
      example: null
      required: false
    Tipo_cierre:
      type: string
      example: ACCEDE
      required: false
    medio_notificacion_pqr:
      type: string
      example: VIRTUAL
      required: false
    medio_recepcion:
      type: string
      example: VIRTUAL
      required: false
    descripcion_pqr:
      type: 'null'
      example: null
      required: false
    respuesta_pqr:
      type: 'null'
      example: null
      required: false
    num_incidendia_remedy:
      type: 'null'
      example: null
      required: false
    respuesta_remedy:
      type: 'null'
      example: null
      required: false
    id_sistema_origen:
      type: string
      example: Max
      required: false
    sistema_origen:
      type: 'null'
      example: null
      required: false
    lsp_origen_llamada:
      type: string
      example: ETB S.A ESP
      required: false
    lsp_tercer_destino:
      type: string
      example: ETB S.A ESP
      required: false
    indicador_pqr_completa:
      type: 'null'
      example: null
      required: false
    correo_electronico:
      type: string
      example: zestatupsa@vusra.com
      required: false
    cun_falla_masiva:
      type: string
      example: '4347220001249169'
      required: false
    direccion_notificacion_escrita:
      type: 'null'
      example: null
      required: false
    radicado_externo:
      type: 'null'
      example: null
      required: false
    flag_recurso_apelacion:
      type: boolean
      example: false
      required: false
    flag_traslado_gobierno:
      type: boolean
      example: false
      required: false
    flag_cliente_recurrente:
      type: boolean
      example: false
      required: false
    flag_reapertura:
      type: boolean
      example: false
      required: false
    prioridad:
      type: 'null'
      example: null
      required: false
    usuario_creador:
      type: string
      example: maxbot
      required: false
    usuario_asignado:
      type: string
      example: maxbot
      required: false
    comentarios:
      type: 'null'
      example: null
      required: false
    nombre_cliente:
      type: string
      example: SINLISIM PRUEBA
      required: false
    segmento_cliente:
      type: 'null'
      example: null
      required: false
    codigo_resolucion:
      type: 'null'
      example: null
      required: false
    descripcion_resolucion:
      type: 'null'
      example: null
      required: false
    subcanal:
      type: string
      example: Chat Bot
      required: false
    punto:
      type: string
      example: Autogestión
      required: false
    proveedor:
      type: string
      example: Max
      required: false
    gerencia:
      type: string
      example: GERENCIA EXPERIENCIA AL CLIENTE
      required: false
    semaforo:
      type: string
      example: rojo
      required: false
    dias_habiles:
      type: string
      example: '510'
      required: false
    Fecha_Inicio_Espera:
      type: 'null'
      example: null
      required: false
    Fecha_Fin_Espera:
      type: 'null'
      example: null
      required: false
    cun_relacionado:
      type: string
      example: ""
      required: false
    nombre_contacto:
      type: string
      example: ""
      required: false
    canal_recepcion:
      type: string
      example: Web
      required: false
    pqr_extensiones:
      type: array
      items: {}
    pqr_actividades_pqr:
      type: array
      items:
        type: object
        properties:
          descripcion_gestion:
            type: string
            example: >-
              La PQR se encuentra registrado en una falla masiva asociada al
              cun:4347220001249169
            required: false
          estado_actividad:
            type: string
            example: En progreso
            required: false
          fecha_estado_actual:
            type: object
            properties:
              $date:
                type: string
                example: '2022-11-03T16:03:18Z'
                required: false
          fecha_inicio_actividad:
            type: object
            properties:
              $date:
                type: string
                example: '2022-11-03T16:03:18Z'
                required: false
          fecha_vencimiento_actividad:
            type: object
            properties:
              $date:
                type: string
                example: '2022-11-08T16:03:18Z'
                required: false
          gestion:
            type: string
            example: GESTION TECNICA EXTERNA
            required: false
          grupo_actividad:
            type: string
            example: GESTION TECNICA EXTERNA
            required: false
          nombre_actividad:
            type: string
            example: GESTION TECNICA
            required: false
          row_id_actividad:
            type: string
            example: MDM-PQR-ACT-2180732
            required: false
          comentarios:
            type: string
            example: ''
            required: false
    pqr_archivos_adjuntos:
      type: array
      items: {}
    carateristicas_pqr:
      type: 'null'
      example: null
      required: false
    pqr_caracteristicas:
      type: 'null'
      example: null
      required: false
    version_pqr:
      type: string
      example: '41'
      required: false
    flag_notificacion:
      type: boolean
      example: false
      required: false
    flag_fallaJoven:
      type: boolean
      example: false
      required: false
    fecha_modificacion:
      type: object
      properties:
        $date:
          type: datetime
          example: '2024-10-18T16:12:55.869Z'
          required: false
    sub_estado:
      type: string
      example: ' '
      required: false
    excepcion:
      type: string
      example: ' '
      required: false
    tipo_excepcion:
      type: string
      example: ' '
      required: false
