#%RAML 1.0 DataType 
type: array
items:
  type: object
  properties:
    _id:
      type: object
      properties:
        $oid:
          type: string
          example: 6356f078e8f33e9fd974da76
          required: false
    Fecha_Creacion:
      type: datetime
      example: '2020-11-15T13:43:25.581Z'
      required: false
    Usuario_Creacion:
      type: string
      example: orquestador
      required: false
    Fecha_Modificacion:
      type: datetime
      example: '2021-08-30T01:13:30.659Z'
      required: false
    Usuario_Modificacion:
      type: string
      example: orquestador
      required: false
    Actualizacion_Extractor:
      type: string
      example: '1'
      required: false
    Numero_Orden:
      type: string
      example: MDM-PQR-009999999
      required: false
    Canal:
      type: string
      example: Canal_Fibra
      required: false
    Fase:
      type: string
      example: ORDERF
      required: false
    Estado_Orden_Comercial:
      type: object
      properties:
        Codigo:
          type: string
          example: O10
          required: false
        Descripcion:
          type: string
          example: Aprovisionamiento Pendiente
          required: false
        Fecha:
          type: datetime
          example: '2020-11-17T16:21:10.677Z'
          required: false
        Reintentos:
          type: integer
          example: 0
          required: false
        CodigoExcepcion:
          type: integer
          example: 0
          required: false
    Tramite:
      type: object
      properties:
        Tipo_Tramite:
          type: string
          example: ASEG
          required: false
        Subtipo_Tramite:
          type: 'null'
          example: null
          required: false
        Fecha_Tramite:
          type: datetime
          example: '2020-11-15T13:43:25.581Z'
          required: false
        Fecha_Ejecucion:
          type: datetime
          example: '2020-11-15T13:43:25.581Z'
          required: false
        Conservar_Numero_Conexion:
          type: boolean
          example: false
          required: false
        Clausula_Permanencia:
          type: boolean
          example: false
          required: false
        Valor_Clausula_Permanencia:
          type: integer
          example: 0
          required: false
        Orden_Origen:
          type: string
          example: MDM-PQR-17502914
          required: false
    Tipo_Servicio:
      type: string
      example: FTTC
      required: false
    CUN:
      type: string
      example: '4347200003582232'
      required: false
    Cliente_Tramite:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: 5a4c2f5a080e9b49a8d59620
              required: false
        Fecha_Creacion:
          type: datetime
          example: '2020-11-15T13:43:25.587Z'
          required: false
        Usuario_Creacion:
          type: string
          example: GUILPINM_EX
          required: false
        Fecha_Modificacion:
          type: datetime
          example: '2020-11-15T13:43:25.587Z'
          required: false
        Usuario_Modificacion:
          type: string
          example: JAVIBARH_EX
          required: false
        Actualizacion_Extractor:
          type: string
          example: '1'
          required: false
        Id_Cuenta_Cliente:
          type: integer
          example: 0
          required: false
        Tipo_Documento:
          type: string
          example: CC
          required: false
        Numero_Documento:
          type: string
          example: '79632809'
          required: false
        Nombres:
          type: string
          example: DUVAN
          required: false
        Primer_Apellido:
          type: string
          example: VARGAS
          required: false
        Segundo_Apellido:
          type: string
          example: ' MORA'
          required: false
        Fecha_Expedicion:
          type: string
          example: '0001-01-01T00:00:00.000Z'
          required: false
        UEN:
          type: string
          example: Uen hogares y negocios
          required: false
        Segmento_UEN:
          type: string
          example: Hogares
          required: false
        Scoring_Fija:
          type: object
          properties:
            Valor_Scoring:
              type: integer
              example: 0
              required: false
            Fecha_Scoring:
              type: string
              example: '0001-01-01T00:00:00.000Z'
              required: false
            Clasificacion_Scoring:
              type: string
              example: ''
              required: false
            Tipo_Scoring:
              type: string
              example: ''
              required: false
            Sistema_Origen:
              type: 'null'
              example: null
              required: false
        Telefono_Fijo:
          type: string
          example: ''
          required: false
        Telefono_Movil:
          type: string
          example: '3186529744'
          required: false
        Email:
          type: string
          example: edivargas18@gmail.com
          required: false
        Contactos:
          type: array
          items:
            type: object
            properties:
              Tipo_Documento:
                type: string
                example: CC
                required: false
              Numero_Documento:
                type: string
                example: '51988121'
                required: false
              Nombres:
                type: string
                example: Edilma
                required: false
              Primer_Apellido:
                type: string
                example: Vargas
                required: false
              Segundo_Apellido:
                type: string
                example: ''
                required: false
              Telefono_Fijo:
                type: string
                example: '79632809'
                required: false
              Telefono_Movil:
                type: string
                example: '3186529744'
                required: false
              Email:
                type: string
                example: notiene@etb.com
                required: false
              Departamento:
                type: string
                example: ''
                required: false
              Ciudad:
                type: string
                example: ''
                required: false
              Direccion:
                type: string
                example: ''
                required: false
              Localidad:
                type: string
                example: ''
                required: false
              Seleccionado:
                type: boolean
                example: false
                required: false
              Autorizado:
                type: boolean
                example: true
                required: false
              Estado:
                type: boolean
                example: true
                required: false
        Direcciones:
          type: array
          items:
            type: object
            properties:
              Id_Direccion:
                type: integer
                example: 51
                required: false
              Direccion_Normalizada:
                type: string
                example: DG 91C SUR 18M 17
                required: false
              Tipo_Direccion:
                type: string
                example: INSTALACION
                required: false
              Codigo_Direccion:
                type: string
                example: '612802304577588342'
                required: false
              Codigo_Departamento:
                type: string
                example: '11'
                required: false
              Codigo_Municipio:
                type: string
                example: '11001'
                required: false
              Codigo_Pais:
                type: string
                example: 593b0ac99a8e4177d410df4d
                required: false
              Nombre_Direccion:
                type: 'null'
                example: null
                required: false
              Estado:
                type: string
                example: ACTIVO
                required: false
              Cobertura:
                type: object
                properties:
                  Direccion_GIS:
                    type: string
                    example: '612802304577588342'
                    required: false
                  Tecnologia:
                    type: string
                    example: FTTC
                    required: false
                  Tipo_Cobertura:
                    type: string
                    example: DISTRITO
                    required: false
                  NombreCobertura:
                    type: string
                    example: '31125'
                    required: false
                  Zona:
                    type: string
                    example: BOGO20
                    required: false
                  Latitud:
                    type: number
                    example: 4.508267
                    required: false
                  Longitud:
                    type: number
                    example: -74.149106
                    required: false
                  Proposito:
                    type: string
                    example: '01'
                    required: false
                  Localidad:
                    type: string
                    example: ''
                    required: false
                  Estrato:
                    type: integer
                    example: 1
                    required: false
                  Viable:
                    type: boolean
                    example: false
                    required: false
              Seleccionada:
                type: boolean
                example: true
                required: false
              Departamento:
                type: string
                example: BOGOTA
                required: false
              Municipio:
                type: string
                example: BOGOTA D.C.
                required: false
        Cuentas_Facturacion:
          type: array
          items: {}
        Cuentas_Servicio:
          type: array
          items: {}
        Adjuntos_Cliente:
          type: array
          items: {}
        Sistema_Origen:
          type: object
          properties:
            Id_Sistema_Origen:
              type: string
              example: 1-5C7LHC
              required: false
            Sistema_Origen_Nombre:
              type: string
              example: COBRE
              required: false
        Estado:
          type: string
          example: ACTIVO
          required: false
        Fecha_Validacion_Identidad:
          type: datetime
          example: '2020-11-15T13:43:25.587Z'
          required: false
        Autoriza_Manejo_Datos_Personales:
          type: string
          example: 'N'
          required: false
        Autoriza_Consulta_Centrales:
          type: string
          example: 'N'
          required: false
    Servicio_Anterior:
      type: object
      properties:
        _t:
          type: string
          example: CuentaServicio
          required: false
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: 5c7a93ee2ab1b54c6c73a1da
              required: false
        Fecha_Creacion:
          type: datetime
          example: '2017-05-30T01:07:20.000Z'
          required: false
        Usuario_Creacion:
          type: string
          example: SADMIN
          required: false
        Fecha_Modificacion:
          type: datetime
          example: '2020-09-11T14:48:55.392Z'
          required: false
        Usuario_Modificacion:
          type: string
          example: orquestador
          required: false
        Actualizacion_Extractor:
          type: string
          example: 03/03/2019
          required: false
        Id_Cuenta_Servicio:
          type: string
          example: 1-J2JTTZP
          required: false
        Bundle:
          type: object
          properties:
            _id:
              type: object
              properties:
                $oid:
                  type: string
                  example: 5bf813b44379b104087c659f
                  required: false
            Codigo_Configuracion:
              type: 'null'
              example: null
              required: false
            Numero_Agrupacion:
              type: integer
              example: 1425
              required: false
            Tipo_Producto:
              type: string
              example: BUNDLE
              required: false
            Tipo_Servicio:
              type: string
              example: FTTC
              required: false
            Subtipo_Servicio:
              type: 'null'
              example: null
              required: false
            Subtipo_Producto:
              type: 'null'
              example: null
              required: false
            Secuencia:
              type: integer
              example: 0
              required: false
            Dependencia:
              type: integer
              example: 0
              required: false
            Clasificacion:
              type: string
              example: SERVICIO
              required: false
            Nombre:
              type: string
              example: 2PLAY 3M PLAN LIGERO
              required: false
            Icono:
              type: 'null'
              example: null
              required: false
            Display:
              type: 'null'
              example: null
              required: false
            Estado:
              type: string
              example: Activo
              required: false
            Cantidad_Minima:
              type: integer
              example: 1
              required: false
            Cantidad_Maxima:
              type: integer
              example: 1
              required: false
            Precio_Oferta:
              type: array
              items:
                type: object
                properties:
                  Canal_Venta:
                    type: 'null'
                    example: null
                    required: false
                  Precio_Sin_Iva:
                    type: integer
                    example: 59500
                    required: false
                  Precio_Con_Iva:
                    type: integer
                    example: 53903
                    required: false
                  Iva:
                    type: integer
                    example: 0
                    required: false
            Caracteristicas_Producto_Oferta:
              type: array
              items:
                type: object
                properties:
                  Caracteristica:
                    type: string
                    example: CUENTA CONTROL
                    required: false
                  Valor:
                    type: string
                    example: SI
                    required: false
                  Accion_caracteristica_oferta:
                    type: array
                    items:
                      type: object
                      properties:
                        Accion:
                          type: string
                          example: ADD
                          required: false
            Id_Clase_Servicio:
              type: integer
              example: 0
              required: false
            Disponibilidad:
              type: boolean
              example: false
              required: false
            Agendamiento:
              type: boolean
              example: false
              required: false
            Aprovisionamiento:
              type: boolean
              example: false
              required: false
            Facturacion:
              type: boolean
              example: false
              required: false
            Accion:
              type: 'null'
              example: null
              required: false
            Id_Item:
              type: 'null'
              example: null
              required: false
            Id_Item_Padre:
              type: 'null'
              example: null
              required: false
            Id_Tipo_Producto:
              type: integer
              example: 0
              required: false
            Id_Tipo_Servicio:
              type: integer
              example: 3
              required: false
            Id_Subtipo_Servicio:
              type: integer
              example: 0
              required: false
            Id_Subtipo_Producto:
              type: integer
              example: 0
              required: false
            Id_Servicio:
              type: string
              example: 1-J2JTTZP
              required: false
            id_opcional_auxiliar:
              type: 'null'
              example: null
              required: false
            Atributos:
              type: array
              items: {}
            tipo_adicional:
              type: 'null'
              example: null
              required: false
            Parametros_Producto:
              type: 'null'
              example: null
              required: false
            seleccionado:
              type: boolean
              example: false
              required: false
            deshabilitado:
              type: boolean
              example: false
              required: false
            Fecha_Asignacion:
              type: datetime
              example: '2017-05-27T05:00:00.000Z'
              required: false
            Parametros_bundle:
              type: array
              items:
                type: object
                properties:
                  Parametro:
                    type: string
                    example: ESTRATO
                    required: false
                  Tipo_Parametro:
                    type: string
                    example: Parámetro General
                    required: false
                  Valor:
                    type: string
                    example: 1/2
                    required: false
            Primarios:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: object
                    properties:
                      $oid:
                        type: string
                        example: 5c055a5b4379b11a48a3c9e1
                        required: false
                  Codigo_Configuracion:
                    type: string
                    example: '133139'
                    required: false
                  Numero_Agrupacion:
                    type: integer
                    example: 1425
                    required: false
                  Tipo_Producto:
                    type: string
                    example: Primario
                    required: false
                  Tipo_Servicio:
                    type: string
                    example: FTTC
                    required: false
                  Subtipo_Servicio:
                    type: string
                    example: FTTC VOZ
                    required: false
                  Subtipo_Producto:
                    type: 'null'
                    example: null
                    required: false
                  Secuencia:
                    type: integer
                    example: 10
                    required: false
                  Dependencia:
                    type: integer
                    example: 10
                    required: false
                  Clasificacion:
                    type: 'null'
                    example: null
                    required: false
                  Nombre:
                    type: string
                    example: LINEA TELEFONICA FTTC
                    required: false
                  Icono:
                    type: 'null'
                    example: null
                    required: false
                  Display:
                    type: 'null'
                    example: null
                    required: false
                  Estado:
                    type: string
                    example: Inactivo
                    required: false
                  Cantidad_Minima:
                    type: integer
                    example: 0
                    required: false
                  Cantidad_Maxima:
                    type: integer
                    example: 0
                    required: false
                  Id_Clase_Servicio:
                    type: integer
                    example: 1200
                    required: false
                  Disponibilidad:
                    type: boolean
                    example: true
                    required: false
                  Agendamiento:
                    type: boolean
                    example: true
                    required: false
                  Aprovisionamiento:
                    type: boolean
                    example: true
                    required: false
                  Facturacion:
                    type: boolean
                    example: false
                    required: false
                  Accion:
                    type: 'null'
                    example: null
                    required: false
                  Id_Item:
                    type: string
                    example: '1'
                    required: false
                  Id_Item_Padre:
                    type: 'null'
                    example: null
                    required: false
                  Id_Tipo_Producto:
                    type: integer
                    example: 1
                    required: false
                  Id_Tipo_Servicio:
                    type: integer
                    example: 3
                    required: false
                  Id_Subtipo_Servicio:
                    type: integer
                    example: 31
                    required: false
                  Id_Subtipo_Producto:
                    type: integer
                    example: 0
                    required: false
                  Id_Servicio:
                    type: string
                    example: 1-J2JZ960
                    required: false
                  id_opcional_auxiliar:
                    type: 'null'
                    example: null
                    required: false
                  Atributos:
                    type: array
                    items:
                      type: object
                      properties:
                        Nombre:
                          type: string
                          example: FAMILIA
                          required: false
                        Valor:
                          type: string
                          example: LB
                          required: false
                        Tipo:
                          type: string
                          example: Agendamiento
                          required: false
                  tipo_adicional:
                    type: 'null'
                    example: null
                    required: false
                  Parametros_Producto:
                    type: 'null'
                    example: null
                    required: false
                  seleccionado:
                    type: boolean
                    example: false
                    required: false
                  deshabilitado:
                    type: boolean
                    example: false
                    required: false
                  Secundarios:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: object
                          properties:
                            $oid:
                              type: string
                              example: 5c055a5b4379b11a48a3c9e4
                              required: false
                        Codigo_Configuracion:
                          type: string
                          example: '23313120348'
                          required: false
                        Numero_Agrupacion:
                          type: integer
                          example: 1425
                          required: false
                        Tipo_Producto:
                          type: string
                          example: SECUNDARIO
                          required: false
                        Tipo_Servicio:
                          type: string
                          example: FTTC
                          required: false
                        Subtipo_Servicio:
                          type: string
                          example: FTTC VOZ
                          required: false
                        Subtipo_Producto:
                          type: 'null'
                          example: null
                          required: false
                        Secuencia:
                          type: integer
                          example: 40
                          required: false
                        Dependencia:
                          type: integer
                          example: 10
                          required: false
                        Clasificacion:
                          type: 'null'
                          example: null
                          required: false
                        Nombre:
                          type: string
                          example: LOCAL EXCLUSIVO CC
                          required: false
                        Icono:
                          type: 'null'
                          example: null
                          required: false
                        Display:
                          type: 'null'
                          example: null
                          required: false
                        Estado:
                          type: string
                          example: Inactivo
                          required: false
                        Cantidad_Minima:
                          type: integer
                          example: 1
                          required: false
                        Cantidad_Maxima:
                          type: integer
                          example: 1
                          required: false
                        Id_Clase_Servicio:
                          type: integer
                          example: 3202
                          required: false
                        Disponibilidad:
                          type: boolean
                          example: false
                          required: false
                        Agendamiento:
                          type: boolean
                          example: false
                          required: false
                        Aprovisionamiento:
                          type: boolean
                          example: true
                          required: false
                        Facturacion:
                          type: boolean
                          example: false
                          required: false
                        Accion:
                          type: string
                          example: '-'
                          required: false
                        Id_Item:
                          type: string
                          example: '2'
                          required: false
                        Id_Item_Padre:
                          type: 'null'
                          example: null
                          required: false
                        Id_Tipo_Producto:
                          type: integer
                          example: 2
                          required: false
                        Id_Tipo_Servicio:
                          type: integer
                          example: 3
                          required: false
                        Id_Subtipo_Servicio:
                          type: integer
                          example: 31
                          required: false
                        Id_Subtipo_Producto:
                          type: integer
                          example: 3120
                          required: false
                        Id_Servicio:
                          type: string
                          example: 1-J2JZ960-1
                          required: false
                        id_opcional_auxiliar:
                          type: 'null'
                          example: null
                          required: false
                        Atributos:
                          type: array
                          items:
                            type: object
                            properties:
                              Nombre:
                                type: string
                                example: CUPO
                                required: false
                              Valor:
                                type: string
                                example: '25585'
                                required: false
                              Tipo:
                                type: string
                                example: Aprovisionamiento
                                required: false
                        tipo_adicional:
                          type: 'null'
                          example: null
                          required: false
                        Parametros_Producto:
                          type: 'null'
                          example: null
                          required: false
                        seleccionado:
                          type: boolean
                          example: false
                          required: false
                        deshabilitado:
                          type: boolean
                          example: false
                          required: false
                  Adicionales:
                    type: array
                    items: {}
                  Numero:
                    type: string
                    example: '5717390613'
                    required: false
        Opcionales:
          type: array
          items: {}
        Promociones:
          type: array
          items: {}
        Cliente:
          type: object
          properties:
            _id:
              type: object
              properties:
                $oid:
                  type: string
                  example: '000000000000000000000000'
                  required: false
            Fecha_Creacion:
              type: datetime
              example: '2019-03-02T14:32:14.317Z'
              required: false
            Usuario_Creacion:
              type: 'null'
              example: null
              required: false
            Fecha_Modificacion:
              type: datetime
              example: '2019-03-02T14:32:14.317Z'
              required: false
            Id_Cuenta_Cliente:
              type: integer
              example: 0
              required: false
            Tipo_Documento:
              type: string
              example: CC
              required: false
            Numero_Documento:
              type: string
              example: '79632809'
              required: false
        Estado:
          type: object
          properties:
            Principal:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2020-09-11T14:48:55.397Z'
                  required: false
            Pago:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2019-11-29T21:57:29.926Z'
                  required: false
            Fraude:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2017-05-30T01:07:20.000Z'
                  required: false
            Tramite:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2020-09-11T14:48:55.397Z'
                  required: false
            Voluntaria:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2017-05-30T01:07:20.000Z'
                  required: false
            RoboPerdida:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2017-05-30T01:07:20.000Z'
                  required: false
        Id_Cuenta_Facturacion:
          type: string
          example: '322840716'
          required: false
        Sistema_Origen:
          type: object
          properties:
            Id_Sistema_Origen:
              type: string
              example: 1-J2JTTZP
              required: false
            Sistema_Origen_Nombre:
              type: string
              example: PORTALFIJA
              required: false
        Id_Direccion_Instalacion:
          type: integer
          example: 51
          required: false
        Servicios_Auxiliares:
          type: array
          items: {}
        Fecha_Activacion:
          type: datetime
          example: '2017-05-27T05:00:00.000Z'
          required: false
        Clausula_Permanencia:
          type: string
          example: F
          required: false
        Numero_Conexion_Anterior:
          type: integer
          example: 0
          required: false
        Id_SalesForce:
          type: integer
          example: 0
          required: false
        Integration_Id:
          type: string
          example: 1-J2JTTZP
          required: false
        Caracteristica_Servicio:
          type: array
          items:
            type: object
            properties:
              Caracteristica:
                type: string
                example: Fecha_Suspension
                required: false
              Valor:
                type: string
                example: 27/11/2019 23:15:00
                required: false
        Is_Pago_Recurrente:
          type: boolean
          example: false
          required: false
    Servicio_Tramite:
      type: object
      properties:
        _t:
          type: string
          example: CuentaServicio
          required: false
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: 5c7a93ee2ab1b54c6c73a1da
              required: false
        Fecha_Creacion:
          type: datetime
          example: '2017-05-30T01:07:20.000Z'
          required: false
        Usuario_Creacion:
          type: string
          example: SADMIN
          required: false
        Fecha_Modificacion:
          type: datetime
          example: '2020-09-11T14:48:55.392Z'
          required: false
        Usuario_Modificacion:
          type: string
          example: orquestador
          required: false
        Actualizacion_Extractor:
          type: string
          example: 03/03/2019
          required: false
        Id_Cuenta_Servicio:
          type: string
          example: 1-J2JTTZP
          required: false
        Bundle:
          type: object
          properties:
            _id:
              type: object
              properties:
                $oid:
                  type: string
                  example: 5bf813b44379b104087c659f
                  required: false
            Codigo_Configuracion:
              type: 'null'
              example: null
              required: false
            Numero_Agrupacion:
              type: integer
              example: 1425
              required: false
            Tipo_Producto:
              type: string
              example: BUNDLE
              required: false
            Tipo_Servicio:
              type: string
              example: FTTC
              required: false
            Subtipo_Servicio:
              type: 'null'
              example: null
              required: false
            Subtipo_Producto:
              type: 'null'
              example: null
              required: false
            Secuencia:
              type: integer
              example: 0
              required: false
            Dependencia:
              type: integer
              example: 0
              required: false
            Clasificacion:
              type: string
              example: SERVICIO
              required: false
            Nombre:
              type: string
              example: 2PLAY 3M PLAN LIGERO
              required: false
            Icono:
              type: 'null'
              example: null
              required: false
            Display:
              type: 'null'
              example: null
              required: false
            Estado:
              type: string
              example: Activo
              required: false
            Cantidad_Minima:
              type: integer
              example: 1
              required: false
            Cantidad_Maxima:
              type: integer
              example: 1
              required: false
            Precio_Oferta:
              type: array
              items:
                type: object
                properties:
                  Canal_Venta:
                    type: 'null'
                    example: null
                    required: false
                  Precio_Sin_Iva:
                    type: integer
                    example: 59500
                    required: false
                  Precio_Con_Iva:
                    type: integer
                    example: 53903
                    required: false
                  Iva:
                    type: integer
                    example: 0
                    required: false
            Caracteristicas_Producto_Oferta:
              type: array
              items:
                type: object
                properties:
                  Caracteristica:
                    type: string
                    example: CUENTA CONTROL
                    required: false
                  Valor:
                    type: string
                    example: SI
                    required: false
                  Accion_caracteristica_oferta:
                    type: array
                    items:
                      type: object
                      properties:
                        Accion:
                          type: string
                          example: ADD
                          required: false
            Id_Clase_Servicio:
              type: integer
              example: 0
              required: false
            Disponibilidad:
              type: boolean
              example: false
              required: false
            Agendamiento:
              type: boolean
              example: false
              required: false
            Aprovisionamiento:
              type: boolean
              example: false
              required: false
            Facturacion:
              type: boolean
              example: false
              required: false
            Accion:
              type: 'null'
              example: null
              required: false
            Id_Item:
              type: 'null'
              example: null
              required: false
            Id_Item_Padre:
              type: 'null'
              example: null
              required: false
            Id_Tipo_Producto:
              type: integer
              example: 0
              required: false
            Id_Tipo_Servicio:
              type: integer
              example: 3
              required: false
            Id_Subtipo_Servicio:
              type: integer
              example: 0
              required: false
            Id_Subtipo_Producto:
              type: integer
              example: 0
              required: false
            Id_Servicio:
              type: string
              example: 1-J2JTTZP
              required: false
            id_opcional_auxiliar:
              type: 'null'
              example: null
              required: false
            Atributos:
              type: array
              items: {}
            tipo_adicional:
              type: 'null'
              example: null
              required: false
            Parametros_Producto:
              type: 'null'
              example: null
              required: false
            seleccionado:
              type: boolean
              example: false
              required: false
            deshabilitado:
              type: boolean
              example: false
              required: false
            Fecha_Asignacion:
              type: datetime
              example: '2017-05-27T05:00:00.000Z'
              required: false
            Parametros_bundle:
              type: array
              items:
                type: object
                properties:
                  Parametro:
                    type: string
                    example: ESTRATO
                    required: false
                  Tipo_Parametro:
                    type: string
                    example: Parámetro General
                    required: false
                  Valor:
                    type: string
                    example: 1/2
                    required: false
            Primarios:
              type: array
              items:
                type: object
                properties:
                  _id:
                    type: object
                    properties:
                      $oid:
                        type: string
                        example: 5c055a5b4379b11a48a3c9e1
                        required: false
                  Codigo_Configuracion:
                    type: string
                    example: '133139'
                    required: false
                  Numero_Agrupacion:
                    type: integer
                    example: 1425
                    required: false
                  Tipo_Producto:
                    type: string
                    example: Primario
                    required: false
                  Tipo_Servicio:
                    type: string
                    example: FTTC
                    required: false
                  Subtipo_Servicio:
                    type: string
                    example: FTTC VOZ
                    required: false
                  Subtipo_Producto:
                    type: 'null'
                    example: null
                    required: false
                  Secuencia:
                    type: integer
                    example: 10
                    required: false
                  Dependencia:
                    type: integer
                    example: 10
                    required: false
                  Clasificacion:
                    type: 'null'
                    example: null
                    required: false
                  Nombre:
                    type: string
                    example: LINEA TELEFONICA FTTC
                    required: false
                  Icono:
                    type: 'null'
                    example: null
                    required: false
                  Display:
                    type: 'null'
                    example: null
                    required: false
                  Estado:
                    type: string
                    example: Inactivo
                    required: false
                  Cantidad_Minima:
                    type: integer
                    example: 0
                    required: false
                  Cantidad_Maxima:
                    type: integer
                    example: 0
                    required: false
                  Id_Clase_Servicio:
                    type: integer
                    example: 1200
                    required: false
                  Disponibilidad:
                    type: boolean
                    example: true
                    required: false
                  Agendamiento:
                    type: boolean
                    example: true
                    required: false
                  Aprovisionamiento:
                    type: boolean
                    example: true
                    required: false
                  Facturacion:
                    type: boolean
                    example: false
                    required: false
                  Accion:
                    type: 'null'
                    example: null
                    required: false
                  Id_Item:
                    type: string
                    example: '1'
                    required: false
                  Id_Item_Padre:
                    type: 'null'
                    example: null
                    required: false
                  Id_Tipo_Producto:
                    type: integer
                    example: 1
                    required: false
                  Id_Tipo_Servicio:
                    type: integer
                    example: 3
                    required: false
                  Id_Subtipo_Servicio:
                    type: integer
                    example: 31
                    required: false
                  Id_Subtipo_Producto:
                    type: integer
                    example: 0
                    required: false
                  Id_Servicio:
                    type: string
                    example: 1-J2JZ960
                    required: false
                  id_opcional_auxiliar:
                    type: 'null'
                    example: null
                    required: false
                  Atributos:
                    type: array
                    items:
                      type: object
                      properties:
                        Nombre:
                          type: string
                          example: FAMILIA
                          required: false
                        Valor:
                          type: string
                          example: LB
                          required: false
                        Tipo:
                          type: string
                          example: Agendamiento
                          required: false
                  tipo_adicional:
                    type: 'null'
                    example: null
                    required: false
                  Parametros_Producto:
                    type: 'null'
                    example: null
                    required: false
                  seleccionado:
                    type: boolean
                    example: false
                    required: false
                  deshabilitado:
                    type: boolean
                    example: false
                    required: false
                  Secundarios:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: object
                          properties:
                            $oid:
                              type: string
                              example: 5c055a5b4379b11a48a3c9e4
                              required: false
                        Codigo_Configuracion:
                          type: string
                          example: '23313120348'
                          required: false
                        Numero_Agrupacion:
                          type: integer
                          example: 1425
                          required: false
                        Tipo_Producto:
                          type: string
                          example: SECUNDARIO
                          required: false
                        Tipo_Servicio:
                          type: string
                          example: FTTC
                          required: false
                        Subtipo_Servicio:
                          type: string
                          example: FTTC VOZ
                          required: false
                        Subtipo_Producto:
                          type: 'null'
                          example: null
                          required: false
                        Secuencia:
                          type: integer
                          example: 40
                          required: false
                        Dependencia:
                          type: integer
                          example: 10
                          required: false
                        Clasificacion:
                          type: 'null'
                          example: null
                          required: false
                        Nombre:
                          type: string
                          example: LOCAL EXCLUSIVO CC
                          required: false
                        Icono:
                          type: 'null'
                          example: null
                          required: false
                        Display:
                          type: 'null'
                          example: null
                          required: false
                        Estado:
                          type: string
                          example: Inactivo
                          required: false
                        Cantidad_Minima:
                          type: integer
                          example: 1
                          required: false
                        Cantidad_Maxima:
                          type: integer
                          example: 1
                          required: false
                        Id_Clase_Servicio:
                          type: integer
                          example: 3202
                          required: false
                        Disponibilidad:
                          type: boolean
                          example: false
                          required: false
                        Agendamiento:
                          type: boolean
                          example: false
                          required: false
                        Aprovisionamiento:
                          type: boolean
                          example: true
                          required: false
                        Facturacion:
                          type: boolean
                          example: false
                          required: false
                        Accion:
                          type: string
                          example: '-'
                          required: false
                        Id_Item:
                          type: string
                          example: '2'
                          required: false
                        Id_Item_Padre:
                          type: 'null'
                          example: null
                          required: false
                        Id_Tipo_Producto:
                          type: integer
                          example: 2
                          required: false
                        Id_Tipo_Servicio:
                          type: integer
                          example: 3
                          required: false
                        Id_Subtipo_Servicio:
                          type: integer
                          example: 31
                          required: false
                        Id_Subtipo_Producto:
                          type: integer
                          example: 3120
                          required: false
                        Id_Servicio:
                          type: string
                          example: 1-J2JZ960-1
                          required: false
                        id_opcional_auxiliar:
                          type: 'null'
                          example: null
                          required: false
                        Atributos:
                          type: array
                          items:
                            type: object
                            properties:
                              Nombre:
                                type: string
                                example: CUPO
                                required: false
                              Valor:
                                type: string
                                example: '25585'
                                required: false
                              Tipo:
                                type: string
                                example: Aprovisionamiento
                                required: false
                        tipo_adicional:
                          type: 'null'
                          example: null
                          required: false
                        Parametros_Producto:
                          type: 'null'
                          example: null
                          required: false
                        seleccionado:
                          type: boolean
                          example: false
                          required: false
                        deshabilitado:
                          type: boolean
                          example: false
                          required: false
                  Adicionales:
                    type: array
                    items: {}
                  Numero:
                    type: string
                    example: '5717390613'
                    required: false
        Opcionales:
          type: array
          items: {}
        Promociones:
          type: array
          items: {}
        Cliente:
          type: object
          properties:
            _id:
              type: object
              properties:
                $oid:
                  type: string
                  example: '000000000000000000000000'
                  required: false
            Fecha_Creacion:
              type: datetime
              example: '2019-03-02T14:32:14.317Z'
              required: false
            Usuario_Creacion:
              type: 'null'
              example: null
              required: false
            Fecha_Modificacion:
              type: datetime
              example: '2019-03-02T14:32:14.317Z'
              required: false
            Id_Cuenta_Cliente:
              type: integer
              example: 0
              required: false
            Tipo_Documento:
              type: string
              example: CC
              required: false
            Numero_Documento:
              type: string
              example: '79632809'
              required: false
        Estado:
          type: object
          properties:
            Principal:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2020-09-11T14:48:55.397Z'
                  required: false
            Pago:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2019-11-29T21:57:29.926Z'
                  required: false
            Fraude:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2017-05-30T01:07:20.000Z'
                  required: false
            Tramite:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2020-09-11T14:48:55.397Z'
                  required: false
            Voluntaria:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2017-05-30T01:07:20.000Z'
                  required: false
            RoboPerdida:
              type: object
              properties:
                Codigo:
                  type: string
                  example: '1'
                  required: false
                Descripcion:
                  type: string
                  example: Activo
                  required: false
                Fecha:
                  type: datetime
                  example: '2017-05-30T01:07:20.000Z'
                  required: false
        Id_Cuenta_Facturacion:
          type: string
          example: '322840716'
          required: false
        Sistema_Origen:
          type: object
          properties:
            Id_Sistema_Origen:
              type: string
              example: 1-J2JTTZP
              required: false
            Sistema_Origen_Nombre:
              type: string
              example: PORTALFIJA
              required: false
        Id_Direccion_Instalacion:
          type: integer
          example: 51
          required: false
        Servicios_Auxiliares:
          type: array
          items: {}
        Fecha_Activacion:
          type: datetime
          example: '2017-05-27T05:00:00.000Z'
          required: false
        Clausula_Permanencia:
          type: string
          example: F
          required: false
        Numero_Conexion_Anterior:
          type: integer
          example: 0
          required: false
        Id_SalesForce:
          type: integer
          example: 0
          required: false
        Integration_Id:
          type: string
          example: 1-J2JTTZP
          required: false
        Caracteristica_Servicio:
          type: array
          items:
            type: object
            properties:
              Caracteristica:
                type: string
                example: Fecha_Suspension
                required: false
              Valor:
                type: string
                example: 27/11/2019 23:15:00
                required: false
        Is_Pago_Recurrente:
          type: boolean
          example: false
          required: false
    Agendamiento:
      type: object
      properties:
        Fecha_Agenda:
          type: datetime
          example: '2020-11-15T13:43:25.578Z'
          required: false
        Franja_Agenda:
          type: string
          example: ''
          required: false
        Enriquecida:
          type: boolean
          example: true
          required: false
        Agenda:
          type: boolean
          example: true
          required: false
        IdActividad:
          type: string
          example: '8013050'
          required: false
        Tipo_ActuacionII:
          type: string
          example: ' => '
          required: false
        ListaCuotas:
          type: array
          items: {}
        Codigo_Instalador:
          type: string
          example: '79979283'
          required: false
    Cuenta_Facturacion_Tramite:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: '000000000000000000000000'
              required: false
        Fecha_Creacion:
          type: datetime
          example: '2020-11-15T13:43:25.591Z'
          required: false
        Usuario_Creacion:
          type: 'null'
          example: null
          required: false
        Fecha_Modificacion:
          type: datetime
          example: '2020-11-15T13:43:25.591Z'
          required: false
        Id_Cuenta_Facturacion:
          type: string
          example: '322840716'
          required: false
        Cliente_Basico:
          type: object
          properties:
            _id:
              type: object
              properties:
                $oid:
                  type: string
                  example: '000000000000000000000000'
                  required: false
            Fecha_Creacion:
              type: datetime
              example: '2020-11-15T13:43:25.591Z'
              required: false
            Usuario_Creacion:
              type: 'null'
              example: null
              required: false
            Fecha_Modificacion:
              type: datetime
              example: '2020-11-15T13:43:25.591Z'
              required: false
            Id_Cuenta_Cliente:
              type: integer
              example: 0
              required: false
            Tipo_Documento:
              type: string
              example: CC
              required: false
            Numero_Documento:
              type: string
              example: '79632809'
              required: false
        Estado:
          type: object
          properties:
            Codigo:
              type: string
              example: ACTIVO
              required: false
            Descripcion:
              type: 'null'
              example: null
              required: false
            Fecha:
              type: 'null'
              example: null
              required: false
        Tipo_Facturacion:
          type: string
          example: Detallada
          required: false
        Tipo_Factura:
          type: string
          example: Detallada
          required: false
        Tipo_Envio:
          type: string
          example: SMS
          required: false
        Valor_Factura:
          type: integer
          example: 0
          required: false
        Email_Facturacion:
          type: string
          example: edivargas18@gmail.com
          required: false
        Ciclo_Facturacion:
          type: string
          example: '52'
          required: false
        Dia_Corte:
          type: integer
          example: 0
          required: false
        Mora:
          type: boolean
          example: false
          required: false
        Id_Direccion_Facturacion:
          type: integer
          example: 52
          required: false
        Ciclo_Charging:
          type: integer
          example: 0
          required: false
        Codigo_Ciclo_Charging:
          type: integer
          example: 0
          required: false
        Cuentas_Servicio:
          type: 'null'
          example: null
          required: false
        Fecha_Corte_Facturacion:
          type: string
          example: '0'
          required: false
    Orden_Requiere_Disponibilidad:
      type: boolean
      example: false
      required: false
    Orden_Requiere_Agendamiento:
      type: boolean
      example: true
      required: false
    Precio_Total_Orden:
      type: string
      example: ''
      required: false
    Adjuntos_Cliente:
      type: array
      items: {}
    Adjuntos_Servicio:
      type: array
      items: {}
    Otros:
      type: object
      properties: {}
    Caracteristica_Orden:
      type: array
      items:
        type: object
        properties:
          Caracteristica:
            type: string
            example: Incidencia_Remedy
            required: false
          Valor:
            type: string
            example: INC000005030385
            required: false
    Orden_Servicio:
      type: object
      properties:
        Numero_Orden:
          type: string
          example: OS-MDM-PQR-17502914
          required: false
        Estado_Orden:
          type: object
          properties:
            Codigo:
              type: string
              example: '5000'
              required: false
            Descripcion:
              type: string
              example: Orquestación exitosa
              required: false
            Fecha:
              type: datetime
              example: '2020-11-15T14:01:50.824Z'
              required: false
            Reintentos:
              type: integer
              example: 0
              required: false
            CodigoExcepcion:
              type: integer
              example: 0
              required: false
        Servicios:
          type: array
          items:
            type: object
            properties:
              Id_Item:
                type: string
                example: '1'
                required: false
              Id_Servicio:
                type: string
                example: 1-J2JZ960
                required: false
              Id_Clase_Servicio:
                type: integer
                example: 1200
                required: false
              Nombre:
                type: string
                example: LINEA TELEFONICA FTTC
                required: false
              Extendido:
                type: boolean
                example: false
                required: false
              Clase_Servicio:
                type: string
                example: VoIP Service Class
                required: false
              Accion:
                type: string
                example: '-'
                required: false
              Disponibilidad:
                type: boolean
                example: false
                required: false
              Agendamiento:
                type: boolean
                example: false
                required: false
              Aprovisionamiento:
                type: boolean
                example: false
                required: false
              Servicios_Hijos:
                type: array
                items:
                  type: object
                  properties:
                    Id_Item:
                      type: string
                      example: '2'
                      required: false
                    Id_Servicio:
                      type: string
                      example: 1-J2JZ960-1
                      required: false
                    Id_Clase_Servicio:
                      type: integer
                      example: 3202
                      required: false
                    Nombre:
                      type: string
                      example: LOCAL EXCLUSIVO CC
                      required: false
                    Extendido:
                      type: boolean
                      example: false
                      required: false
                    Clase_Servicio:
                      type: string
                      example: ETBLE01
                      required: false
                    Accion:
                      type: string
                      example: '-'
                      required: false
                    Disponibilidad:
                      type: boolean
                      example: false
                      required: false
                    Agendamiento:
                      type: boolean
                      example: false
                      required: false
                    Aprovisionamiento:
                      type: boolean
                      example: false
                      required: false
                    Servicios_Hijos:
                      type: array
                      items: {}
                    Atributos:
                      type: array
                      items:
                        type: object
                        properties:
                          Nombre:
                            type: string
                            example: ZONENAME
                            required: false
                          Valor:
                            type: string | date-only
                            example: e164.arpa
                            required: false
                          Tipo:
                            type: string
                            example: Aprovisionamiento
                            required: false
                          Clase:
                            type: string
                            example: Inventario
                            required: false
                          Nuevo:
                            type: boolean
                            example: false
                            required: false
                          Display:
                            type: integer
                            example: 0
                            required: false
                    Commit:
                      type: array
                      items: {}
                    Rollback:
                      type: array
                      items: {}
                    Codigo_Configuracion:
                      type: string
                      example: '23313120348'
                      required: false
                    Nuevo:
                      type: boolean
                      example: true
                      required: false
                    Puertos:
                      type: array
                      items:
                        type: object
                        properties:
                          Validado:
                            type: boolean
                            example: true
                            required: false
                          Validar:
                            type: boolean
                            example: false
                            required: false
                          Nombre:
                            type: string
                            example: '1'
                            required: false
                          Id_Servicio:
                            type: string
                            example: 1-J2JZ98H
                            required: false
              Atributos:
                type: array
                items:
                  type: object
                  properties:
                    Nombre:
                      type: string
                      example: VOIPGOLD
                      required: false
                    Valor:
                      type: string
                      example: ''
                      required: false
                    Tipo:
                      type: string
                      example: Disponibilidad
                      required: false
                    Clase:
                      type: string
                      example: Tramite
                      required: false
                    Nuevo:
                      type: boolean
                      example: false
                      required: false
                    Display:
                      type: integer
                      example: 0
                      required: false
              Commit:
                type: array
                items: {}
              Rollback:
                type: array
                items: {}
              Codigo_Configuracion:
                type: string
                example: '133139'
                required: false
              Nuevo:
                type: boolean
                example: true
                required: false
              Puertos:
                type: array
                items: {}
    Orden_Activacion:
      type: 'null'
      example: null
      required: false