#%RAML 1.0 DataType 
type: object
properties:
  codigo:
    type: string
    example: '200'
    required: false
  datos_facturacion:
    type: array
    items:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: 2ba33b6DEdcFACE87d47D9D8
              required: false
        Ciclo_Facturacion:
          type: string
          example: ABCDEFGHI
          required: false
        Ciudad:
          type: string
          example: ''
          required: false
        Correo_Electronico:
          type: string
          example: ABCDEFGHI
          required: false
        Cuenta_Facturacion:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUVWXYZAB
          required: false
        Departamento:
          type: string
          example: ABCDEFGHIJKLMNOP
          required: false
        Direccion:
          type: string
          example: ABCDEFGHIJKLMNOPQ
          required: false
        Estado:
          type: string
          example: ''
          required: false
        Fecha_Corte_Facturacion:
          type: string
          example: ''
          required: false
        Frecuencia:
          type: string
          example: ''
          required: false
        Numero_Identificacion:
          type: string
          example: ''
          required: false
        Pais:
          type: string
          example: ABCDEFGHIJKLMNOP
          required: false
        Tipo_Documento:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUVWXYZAB
          required: false
        Tipo_Entrega_Factura:
          type: string
          example: ABCDEFG
          required: false
        Tipo_Factura:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
          required: false
        Usuario_Creador:
          type: string
          example: ABCDEFGHIJKLMNOPQRST
          required: false
        Altura_Mora:
          type: string
          example: ABCD
          required: false
        Barrio:
          type: string
          example: ABCDEFGHIJKLMNOPQ
          required: false
        Ciclo_Charging:
          type: string
          example: ''
          required: false
        Codigo_Ciclo_Charging:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUVWX
          required: false
        Cuenta_Padre_Facturacion:
          type: string
          example: ABCDEFGHIJKLMNOPQR
          required: false
        Estrato:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUV
          required: false
        Fecha_Actualizacion:
          type: object
          properties:
            $date:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
              required: false
        Fecha_Creacion:
          type: object
          properties:
            $date:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUV
              required: false
        Fecha_Modificacion:
          type: object
          properties:
            $date:
              type: string
              example: ABCDEFGHIJKLMNOPQ
              required: false
        Id_Cuenta_Facturacion:
          type: string
          example: ''
          required: false
        Id_Cuenta_Facturacion_Salesforce:
          type: string
          example: ''
          required: false
        Id_Direccion_Facturacion:
          type: integer
          example: 0
          required: false
        Id_Orden_Relacionada:
          type: string
          example: ''
          required: false
        Impuestos:
          type: string
          example: ''
          required: false
        Localidad:
          type: string
          example: ABCDEFG
          required: false
        Mercado:
          type: string
          example: ''
          required: false
        Modificado_MDM:
          type: string
          example: ABCDEFGH
          required: false
        Pago_Rec:
          type: array
          items:
            type: object
            properties:
              _id:
                type: object
                properties:
                  $oid:
                    type: string
                    example: cbFf206EadBd42F71118beab
                    required: false
              Actualizacion_Extractor:
                type: string
                example: ABCDEFGHIJKLMNOPQRST
                required: false
              Fecha_Creacion:
                type: object
                properties:
                  $date:
                    type: string
                    example: ABCDEFGHIJK
                    required: false
              Fecha_Modificacion:
                type: object
                properties:
                  $date:
                    type: string
                    example: ABCDEF
                    required: false
              Id_Medio_Pago:
                type: string
                example: ABCDEFGHIJKLMNOPQR
                required: false
              Is_Pago_Recurrente:
                type: boolean
                example: false
                required: false
              Usuario_Creacion:
                type: string
                example: ABCDEFGHIJKLMNOPQRSTUVW
                required: false
              Usuario_Modificacion:
                type: string
                example: ABCDEFGHIJKLMN
                required: false
        Soporte_Factura:
          type: string
          example: ABCDEFG
          required: false
        Tipo_Pago:
          type: string
          example: ''
          required: false
        Usuario_Modificador:
          type: string
          example: ABCDEFGHI
          required: false
