#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: "200"
    required: false
  message:
    type: string
    example: "Consulta realizada con exito"
    required: false
  pqrParent?:
    type: array
    items:
      type: object
example: !include ../../examples/responses/get-pqrs-parents.json