#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: Consulta realizada con exito
    required: false
  variables?:
    type: array
    items:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: "5a055cabc128ff8eddb35d60"
              required: false
        Estado?:
          type: string
          example: "Activo"
          required: false
        Fecha_Creacion?:
          type: object
          properties:
            $date:
              type: datetime 
              example: "2023-06-23T13:45:41.671Z"
              required: false
        Localidades?:
          type: array
          items:
            type: string
        Nombre_Variable:
          type: string
          example: "Rango Score MiPymes FIJA"
          required: false
        Nombre_Tabla:
          type: string
          example: "RANGO SCORE MIPYMES 02 05 JULIO 2023"
          required: false
        Planes?:
          type: object
          properties:
            Planes_Fija?:
              type: array
              items:
                type: string
            Planes_LTE?:
              type: array
              items:
                type: string
        Prioridad:
          type: integer
          example: 3
          required: false
        Segmento?:
          type: array
          items:
            type: string
        Tabla_Asignada:
          type: string
          example: "4"
          required: false
        Tecnologia:
          type: string
          example: "FIJA"
          required: false
        Variables?:
          type: array
          items:
            type: string
        Fecha_Modificacion?:
          type: object
          properties:
            $date:
              type: datetime 
              example: "2023-06-23T13:45:41.671Z"
              required: false
example: !include ../../examples/responses/get-score-variables.json