#%RAML 1.0 DataType 
type: object
properties:
  codigo:
    type: string
    example: '200'
    required: false
  mensaje:
    type: string
    example: Consulta realizada con exito
    required: false
  promocion:
    type: array
    items:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: BdB5e423edbB9ecf3a720Aa6
              required: false
        Activo:
          type: boolean
          example: true
          required: false
        Aplicar_Mora:
          type: boolean
          example: true
          required: false
        Canales:
          type: array
          items:
            type: string
        Caracteristicas:
          type: array
          items:
            type: object
            properties:
              caracteristica:
                type: string
                example: ABCDEFGHIJKLMNOPQRSTUVW
                required: false
              valores:
                type: array
                items:
                  type: string
        Descripcion:
          type: string
          example: ABCDE
          required: false
        Descuento_Prorrateo:
          type: integer
          example: 0
          required: false
        Fecha_Creacion:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        Fecha_Final:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        Fecha_Inicial:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        Fecha_Modificacion:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        ID_Accion_Cambio_Plan:
          type: integer
          example: 0
          required: false
        ID_Accion_Condicionada:
          type: integer
          example: 0
          required: false
        ID_Convenio:
          type: string
          example: ABCDEFGHI
          required: false
        ID_Operador_Condicionada:
          type: integer
          example: 0
          required: false
        ID_Servicio:
          type: integer
          example: 0
          required: false
        ID_Tipo_Activacion:
          type: integer
          example: 0
          required: false
        ID_Tipo_Condicionada:
          type: integer
          example: 0
          required: false
        ID_Tipo_Promocion:
          type: integer
          example: 0
          required: false
        ID_Tipo_Servicio:
          type: integer
          example: 0
          required: false
        ID_Variable_Condicionada:
          type: integer
          example: 0
          required: false
        Nombre:
          type: string
          example: ABCD
          required: false
        Permanente:
          type: boolean
          example: true
          required: false
        Planes_Aplicar:
          type: array
          items:
            type: string
        Reglas:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUVWXY
          required: false
        Suspender_Mora:
          type: boolean
          example: true
          required: false
        Tramites_Aplicar:
          type: array
          items:
            type: string
        Usuario_Creacion:
          type: string
          example: ABCDEFGHIJKLMNOPQRSTUVWXYZAB
          required: false
        Usuario_Modificacion:
          type: string
          example: ABCDEFGHIJKLMN
          required: false
  totalDatos:
    type: integer
    example: 1542
    required: false