#%RAML 1.0 DataType 
type: object
properties:
  codigo:
    type: string
    example: '200'
    required: false
  mensaje:
    type: string
    example: Su tipo de entrega de factura ha sido actualizado exitosamente
    required: false
  ofertasProducto:
    type: array
    items:
      type: object
      properties:
        _id:
          type: string
          example: 5bad589d929c4e3b7c9967f6
          required: false
        usuario_creo:
          type: string
          example: gonzpula
          required: false
        fecha_creacion:
          type: datetime
          example: '2018-09-27T22:24:29.670Z'
          required: false
        cod_configuracion:
          type: string
          example: '2111130026'
          required: false
        secuencia:
          type: integer
          example: 50
          required: false
        dependencia:
          type: integer
          example: 10
          required: false
        num_agrupacion:
          type: integer
          example: 208
          required: false
        id_producto:
          type: string
          example: 59c26bf2929c4e1b0cf97c60
          required: false
        producto:
          type: string
          example: SVA Whatsapp Datos 250
          required: false
        tipo_producto:
          type: string
          example: SECUNDARIO
          required: false
        id_producto_principal:
          type: string
          example: 59c17cb1929c4e12bc5f2484
          required: false
        producto_principal:
          type: string
          example: LTE POSPAGO
          required: false
        id_bundle_principal:
          type: string
          example: ''
          required: false
        bundle_principal:
          type: string
          example: ''
          required: false
        fecha_ini_vigencia:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        fecha_fin_vigencia:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        estado:
          type: string
          example: Activo
          required: false
        tipo_servicio:
          type: string
          example: LTE
          required: false
        subtipo_servicio:
          type: string
          example: CONTROL
          required: false
        es_tipo_bundle:
          type: boolean
          example: false
          required: false
        tipo_bundle:
          type: string
          example: LTE
          required: false
        clasificacion:
          type: string
          example: ''
          required: false
        cantidad_minima:
          type: integer
          example: 0
          required: false
        cantidad_maxima:
          type: integer
          example: 0
          required: false
        precio_minimo:
          type: integer
          example: 0
          required: false
        precio_maximo:
          type: integer
          example: 0
          required: false
        rangoInicioSeguro:
          type: string
          example: ''
          required: false
        rangoFinSeguro:
          type: string
          example: ''
          required: false
        fase:
          type: string
          example: T
          required: false
        fase_update:
          type: string
          example: I
          required: false
        estado_update:
          type: string
          example: Activo
          required: false
        icono:
          type: string
          example: whatsapp
          required: false
        archivo:
          type: string
          example: >-
            data:image/png;base64,iVBORw0KGgoAAAANSUhEU
          required: false
        display:
          type: string
          example: 250MB Chat WhatsApp
          required: false
        es_modificacion:
          type: boolean
          example: false
          required: false
        usuario_bloqueo:
          type: string
          example: ''
          required: false
        descripcion_plan:
          type: string
          example: ''
          required: false
        especificacion_tecnica:
          type: string
          example: ''
          required: false
        observaciones:
          type: string
          example: ''
          required: false
        especificaciones_facturacion_upd:
          type: array
          required: false
          items:
            type: object
            properties:
              _id:
                type: string
                example: 5b58e28b164b7e06b4e0c1f4
                required: false
              usuario_creo:
                type: string
                example: asmeparg
                required: false
              fecha_creacion:
                    type: datetime
                    example: '2018-07-25T20:50:19.674Z'
                    required: false
              id_producto_espeficificacion:
                type: string
                example: ''
                required: false
              producto_espeficificacion:
                type: string
                example: ''
                required: false
              sistema:
                type: string
                example: REVCHAIN
                required: false
              tipo_especificacion:
                type: string
                example: ''
                required: false
              parametro:
                type: string
                example: RVC PARM Cargo Voz DS
                required: false
              valor:
                type: string
                example: '4522.56'
                required: false
              fecha_aplicacion:
                    type: datetime
                    example: '2018-07-26T05:00:00.000Z'
                    required: false
              estado:
                type: string
                example: Pendiente
                required: false
              accion_esp_tecnica_oferta:
                type: array
                items:
                  type: object
                  properties:
                    accion:
                      type: string
                      example: ADD
                      required: false
        valor_espec_tecnica_oferta:
          type: array
          required: false
          items:
            type: object
            properties:
              id_producto_espeficificacion:
                type: string
                example: ''
                required: false
              producto_espeficificacion:
                type: string
                example: ''
                required: false
              sistema:
                type: string
                example: REVCHAIN
                required: false
              tipo_especificacion:
                type: string
                example: PARAMETRO
                required: false
              parametro:
                type: string
                example: RVC FEAT
                required: false
              valor:
                type: string
                example: SVA Chat Whatsapp LTE
                required: false
              accion_esp_tecnica_oferta:
                type: array
                items:
                  type: object
                  properties:
                    accion:
                      type: string
                      example: ADD
                      required: false
        caracteristicas_producto_oferta:
          type: array
          required: false
          items:
            type: object
            properties:
              caracteristica:
                type: string
                example: DESCRIPCION
                required: false
              valor:
                type: string
                example: >-
                  Chat de WhatsApp que no consume de tus datos (WhatsApp limitado a
                  250MB por mes). Una vez superes este consumo descontará de los datos
                  de tu plan.
                required: false
              accion_caracteristica_oferta:
                type: array
                items:
                  type: object
                  properties:
                    accion:
                      type: string
                      example: ADD
                      required: false
        agrupa_filtros_oferta:
          type: array
          required: false
          items:
            type: object
            properties:
              grupo:
                type: string
                example: SCORING CLIENTE
                required: false
              grupo_filtros_oferta:
                type: array
                items:
                  type: object
                  properties:
                    filtro:
                      type: string
                      example: BAJO
                      required: false
                    valor_grupo_oferta:
                      type: array
                      items:
                        type: object
                        properties:
                          valor:
                            type: 'null'
                            example: null
                            required: false
                          valor_minimo:
                            type: integer
                            example: 761
                            required: false
                          valor_maximo:
                            type: integer
                            example: 10000
                            required: false
        parametros_bundle:
          type: array
          required: false
          items:
            type: object
            properties:
              parametro:
                type: string
                example: CANAL VENTA
                required: false
              tipo_parametro:
                type: string
                example: Parámetro General
                required: false
              valor:
                type: string
                example: DISTRIBUIDOR/RETAIL/MOVILIDAD/TIENDA LTE
                required: false
        precio_oferta:
          type: array
          required: false
          items:
            type: object
            properties:
              _id:
                type: string
                example: 5b5b3bf4929c4e1180bcc6fb
                required: false
              usuario_creo:
                type: string
                example: andrruec
                required: false
              fecha_creacion:
                    type: datetime
                    example: '2018-07-27T15:36:20.553Z'
                    required: false
              canal_venta:
                type: string
                example: ''
                required: false
              servicio:
                type: string
                example: ''
                required: false
              precio_sin_iva:
                type: integer
                example: 134379
                required: false
              precio_con_iva:
                type: integer
                example: 165900
                required: false
              iva:
                type: integer
                example: 19
                required: false
              fecha_aplicacion:
                    type: datetime
                    example: '2018-07-27T05:00:00.000Z'
                    required: false
              estado:
                type: string
                example: Inactivo
                required: false
              precio_filtros:
                type: string
                example: ''
                required: false
        agrupacion_filtros:
          type: array
          required: false
          items: {}
        imagenes_plan:
          type: array
          required: false
          items: {}
  totalDatos:
    type: integer
    example: 1542
    required: false