#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: "200"
    required: false
  message:
    type: string
    example: "Consulta realizada con exito"
    required: false
  botChannel?:
    type: array
    items:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: "5a055cabc128ff8eddb35d60"
              required: false
        Canal_Origen?:
          type: string
          example: "SUMA"
          required: false
        Canal_Destino?:
          type: string
          example: "Web"
          required: false
          
example: !include ../../examples/responses/get-bots-channels.json