#%RAML 1.0 DataType 
type: object
properties:
  _id:
    type: string
    example: 67fe6b381468356ab097ad65
    required: false
  Tipo_Parametro:
    type: string
    example: PARAMETROS_ESIM
    required: false
  Fecha_Creacion:
    type: string
    example: 2025-04-04T00:10:54.276+0000
    required: false
  Fecha_Modificacion:
    type: string
    example: 2025-04-04T00:10:54.276+0000
    required: false
  Usuario_Creacion:
    type: string
    example: Admin
    required: false
  Usuario_Modificacion:
    type: string
    example: Admin
    required: false
  Valores:
    type: array
    items:
      type: object
      properties:
        Codigo:
          type: string
          example: 'True'
          required: false
        Nombre:
          type: string
          example: ESIM_ACTIVACION_AUTOMATICA
          required: false
        Descripcion:
          type: string
          example: >-
            Indica si la activación de la eSIM debe realizarse automáticamente
            por el sistema (True) o de manera manual por el cliente (False).
          required: false
  Actualizacion_Extractor:
    type: string
    example: '1'
    required: false
