#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: Operacion exitosa
    required: false
  orden:
    type: array
    items:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
              example: 5fb6d87cde083f2c388536fb
              required: false
        usuario_creo:
          type: string
          example: juangom3
          required: false
        fecha_actualizacion:
          type: datetime
          example: '2022-09-29T20:55:57.014Z'
          required: false
        cun:
          type: string
          example: '4347200001200008'
          required: false
        service_type:
          type: string
          example: INTERNET
          required: false
        order_type:
          type: string
          example: MDM-PQR-4078972
          required: false
        technology:
          type: string
          example: FTTC
          required: false
        duration:
          type: string
          example: '50'
          required: false
        address:
          type: string
          example: KR 8 20 28 PI 2
          required: false
        connection_number:
          type: string
          example: '5718005816'
          required: false
        technician_document_type:
          type: string
          example: ''
          required: false
        technician_document_number:
          type: string
          example: ''
          required: false
        zone:
          type: string
          example: CU_BOGO03
          required: false
        skill:
          type: string
          example: FALLA_JOVEN_FTTC
          required: false
        order_number:
          type: string
          example: MDM-PQR-4078972
          required: false
        origin_system:
          type: string
          example: MDM_PQR
          required: false
        customer_document_type:
          type: string
          example: CC
          required: false
        customer_document_number:
          type: string
          example: '19112020'
          required: false
        action_type:
          type: string
          example: FALLA_JOVEN_FTTC
          required: false
        agendas_tmr:
          type: array
          items:
            type: object
            properties:
              _id:
                type: object
                properties:
                  $oid:
                    type: string
                    example: 6336065df46b1613148b467e
                    required: false
              fecha_creacion:
                type: datetime
                example: '2022-09-29T20:55:57.016Z'
                required: false
              usuario_creador:
                type: string
                example: ""
                required: false
              usuario_modificador:
                type: string
                example: ""
                required: false
              oportunidad_agenda:
                type: string
                example: ""
                required: false
              fecha_inicio_agenda:
                type: datetime
                example: '2022-09-29T20:55:57.016Z'
                required: false
              fecha_fin_agenda:
                type: datetime
                example: '2022-09-29T20:55:57.016Z'
                required: false
              id_eta:
                type: string
                example: ''
                required: false
              id_osm:
                type: string
                example: ''
                required: false
              timeslot:
                type: string
                example: ''
                required: false
              estado_agenda:
                type: string
                example: Cancelada
                required: false
              canal:
                type: string
                example: ""
                required: false
              motivo_reagendamiento:
                type: string
                example: ""
                required: false
              solicitado_cliente:
                type: boolean
                example: false
                required: false