#%RAML 1.0 DataType
displayName: Notifications Audit Response
description: Represents a notification audit record reponse detail .
example: !include ../../examples/responses/patch-notification-audit-response.json
type: object
properties:
  status:
    type: string
    example: '201'
    required: false
  message:
    type: string
    example: Consulta realizada con exito
    required: false
  result:
    type: string
    description: Notification ID from the provider
    example: "9865"