#%RAML 1.0 DataType
description: Respuesta de creación de una PQR
type: object
properties:
  status:
    type: string
    description: Código HTTP de respuesta
    example: "201"
  message:
    type: string
    description: Mensaje descriptivo del resultado de la operación
    example: "PQR Created"
  result:
    type: object
    description: Datos del recurso creado
    properties:
      mongoId:
        type: string
        description: Identificador único generado por MongoDB (ObjectId)
        example: "098iejokjeoeu"
      numero_pqr:
        type: string
        description: Número único asignado a la PQR creada
        example: "MDM-PQR-19828"
example: !include ../../examples/responses/post-pqr.json