#%RAML 1.0 DataType 
type: object
properties:
  codigo:
    type: string
    example: '200'
    required: false
  mensaje:
    type: string
    example: ''
    required: false
  numeroRetencion:
    type: string
    example: ''
    required: false
