#%RAML 1.0 DataType 
type: object
properties:
  response:
    type: object
    properties:
      result:
        type: object
        properties:
          code:
            type: string
            example: SUCCESS
            required: false
          description:
            type: string
            example: Update succesfully
            required: false
      responseDate:
        type: datetime
        description: "fecha de actualizacion"
        required: false
      orderNumber:
        type: string
        example: MDM-PAR-54545454
        required: false
