#%RAML 1.0 ResourceType
get?:
  displayName: List <<resourcePathName | !uppercamelcase>>
  description: List <<resourcePathName | !uppercamelcase>>
  is:
    - portal-fija-sapi-services.security-clientId-trait:
    - portal-fija-sapi-services.RequestHeaders:
    #- portal-fija-sapi-services.<<resourcePathName | !singularize | !uppercamelcase>>QueryParameters:
  responses:
    200:
      #is:
        #- portal-fija-sapi-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response[]
post?:
  displayName: Create <<resourcePathName | !singularize | !uppercamelcase>>
  description: Create <<resourcePathName | !singularize | !uppercamelcase>>
  is:
    - portal-fija-sapi-services.security-clientId-trait:
    - portal-fija-sapi-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response
put?:
  displayName: Update <<resourcePathName | !singularize | !uppercamelcase>>
  description: Update <<resourcePathName | !singularize | !uppercamelcase>>
  is:
    - portal-fija-sapi-services.security-clientId-trait:
    - portal-fija-sapi-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response