#%RAML 1.0 ResourceType
get?:
  displayName: Get <<resourcePathName | !singularize | !uppercamelcase>> By Id
  description: Get <<resourcePathName | !singularize | !uppercamelcase>> By Id
  is:
    - portal-fija-sapi-services.security-clientId-trait:
    - portal-fija-sapi-services.RequestHeaders:
    #- portal-fija-sapi-services.<<resourcePathName | !singularize | !uppercamelcase>>UriParameters:
  responses:
    200:
      #is:
        #- portal-fija-sapi-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response
patch?:
  displayName: Update <<resourcePathName | !singularize | !uppercamelcase>> Partially By Id
  description: Update <<resourcePathName | !singularize | !uppercamelcase>> Partially By Id
  is:
    - portal-fija-sapi-services.security-clientId-trait:
    - portal-fija-sapi-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    200:
      #is:
        #- portal-fija-sapi-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response