#%RAML 1.0 DataType
properties:
  subscriber_id:
    type: string
    example: "10164587925"
    required: false
  country_code:
    type: string
    example: "CO"
    required: false
  resource_id:
    type: string
    example: "urn:tve:ucinema"
  action_id:
    type: string
    example: "hasAccessTo"
    required: true
  ip_address:
    type: string
    example: "190.248.53.11"
    required: false

example: !include ../../examples/request/authorizationTV-request.json