#%RAML 1.0
title: normalize-api-services
version: "1"
protocols:
  - HTTP

baseUri: normalize-papi-services-dev.us-e2.cloudhub.io/normalize
description: This API contains the orquestation and logic for different System APIs that proceed from infraestructure-resource-api-service

traits:
  security_client_id: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  request_headers: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.5/tibcorequestheaders.raml

/v1:
  /normalizeAddress:
    is: [security_client_id, request_headers]
    post:
      displayName: Normalize address
      description: Normalizes input address and categorizes the address according to its availability
      body:
        application/json:
          type: !include datatypes/request/unNormalizedAddress.raml
      responses:
        201:
          body:
            application/json:
              type: !include datatypes/response/normalizedAddress.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/normalizeErrorMessageResponse.raml
              example: !include examples/response/normalizeErrorMessageResponse.json