# --- HTTP Listener ---
http:
  private:
    host: "0.0.0.0"
    port: "8091"
    readTimeout: "10000"

# --- API Metadata ---
api: 
  id: "0"
  name: "data-logic-sapi-services"
  version: "1.0.0"
  basePath: "/v1/*"

# --- PQR SOAP Requester ---
pqr:
  soap:
    protocol: "http://"
    wsdlHost: "40.118.188.146"
    wsdlPort: "81"
    wsdlPath: "/MDM_Data_Services/MDM_Data_Services.asmx?wsdl"
    service: "MDM_Data_Services"
    servicePort: "MDM_Data_ServicesSoap12"
    operations: 
      setPqr: "Set_PQR"