http:
  private:
    port: "8091"
  listener:
    basepath: "/v1/*"
    timeout: "30000"
          
autodiscovery: ""

pqr:
  soap:
    protocol: "http://"
    wsdlHost: ""
    wsdlPort: ""
    wsdlPath: "/MDM_Data_Services/MDM_Data_Services.asmx?wsdl"
    service: "MDM_Data_Services"
    servicePort: "MDM_Data_ServicesSoap12"
    operations: 
      setPqr: "Set_PQR"