#%RAML 1.0 DataType

properties:
  username:
    type: string
    required: true
    minLength: 1
    example: "test"
  password:
    type: string
    required: true
    minLength: 1
    example: "test"
  action:
    type: string
    required: true
    enum: [authenticate]
    example: "authenticate"