#%RAML 1.0 DataType

properties:
  quoteCalculation:
    type: object 
    properties:
      calculationObject:
        type: object
        properties:
          requestId: 
            type: number 
            required: true
            example: 45246 
          companyBasicInformation:
            type: object
            required: false
            properties:
              businessName:     
                type: string 
                required: false
                example: "JF LASER DE COLOMBIA SAS"
              identificationType:
                type: number
                required: true
                example: 9
              identification:
                type: string 
                required: false
                example: "901237030"
              city:
                type: number
                required: true
                example: 146
              address:
                type: string 
                required: false
                example: "CALLE 12 30 64"
          companyAdditionalInformation:
            type: object
            required: false
            properties:
              economicActivity:
                type: number
                required: true
                example: 61
              constitutionDate:
                type: string
                required: true
                example: "2018-12-05T00:00:00"
              stratum:
                type: number
                required: true
                example: 1
              zoneId:
                type: number
                required: true
                example: 2
          legalRepresentative:
            type: object
            required: false
            properties:
              names: 
                type: string
                required: false
                example: "JHON  FREDY"
              surnames:
                type: string
                required: false
                example: "TOBARIA  RAMIREZ"
              identificationType: 
                type: number
                required: true 
                example: 1
              identification:
                type: string 
                required: false
                example: "900585650"
              dateBirth:
                type: string 
                required: true
                example: "1986-03-03T00:00:00"
          generalBalance:
            type: object
            required: false
            properties:
              totalCurrentAssets:
                type: number
                required: true
                example: 5000.0
              inventories:
                type: number
                required: true
                example: 5000.0
              totalAssets:
                type: number
                required: true
                example: 5000.0
              totalCurrentLiabilities:
                type: number
                required: true
                example: 5000.0
              totalLiabilities:
                type: number
                required: true
                example: 5000.0
              totalPatrimony:
                type: number
                required: true
                example: 5000.0
          statusResults:
            type: object
            required: false
            properties:
              currentYearOperatingRevenue:
                type: number
                required: true
                example: 5000.0
              currentYearNoOperatingRevenue:
                type: number
                required: true
                example: 5000.0
              previousYearOperatingRevenue:
                type: number
                required: true
                example: 5000.0
              previousYearNoOperatingRevenue:
                type: number
                required: true
                example: 5000.0
              costSale:
                type: number
                required: true
                example: 5000.0
              operationalExpenses:
                type: number
                required: true
                example: 5000.0
              operationalProfit:
                type: number
                required: true
                example: 5000.0
              otherExpenses:
                type: number
                required: true
                example: 5000.0
              netProfit:
                type: number
                required: true
                example: 5000.0
              beforeTaxProfit:
                type: number
                required: true
                example: 5000.0
              incomeTaxAndComplementary:
                type: number
                required: true 
                example: 5000.0
              accountReceivable:
                type: number
                required: true
                example: 5000.0
              financialObligations: 
                type: number
                required: true
                example: 5000.0

