#%RAML 1.0 DataType
properties:
  createOrderRequest:
    type: object
    required: false
    properties:
      createOrderIn:
        type: object
        properties:
          order:
            type: object
            properties:
              cunNumber:
                type: string
                required: true
                example: "4347220000487728"
              reference:
                type: string
                required: true
                example: "MDM-MOV-2196193-OL-1-OL-1"
              date:
                type: string
                required: true
                example: "02/01/2022 10:02:18"
              resend:
                type: object
                properties:
                  dispatchOrder:
                    type: string
                    required: true
                    example: "false"
                  quantity:
                    type: number
                    required: true
                    example: 0
              orderType:
                type: string
                required: true
                example: "Express"
              entryType:
                type: string
                required: true
                example: "Cliente"
              observations:
                type: string
                required: true
                example: ""
              collection:
                type: object
                properties:
                  required:
                    type: boolean
                    required: true
                    example: true
                  value:
                    type: number
                    required: true
                    example: 0
              address:
                type: object
                properties:
                  address:
                    type: string
                    required: true
                    example: "CL 112 14B 50 AP 303"
                  district:
                    type: string
                    required: true
                    example: "SANTA BARBARA CENTRAL"
                  city:
                    type: string
                    required: true
                    example: "11001"
                  department:
                    type: string
                    required: true
                    example: "11"
              contact:
                type: object
                properties:
                  names:
                    type: string
                    required: true
                    example: "JULIO ALBERTO"
                  surnames:
                    type: string
                    required: true
                    example: "CABRA"
                  documentType:
                    type: string
                    required: true
                    example: "CC"
                  documentNumber:
                    type: string
                    required: true
                    example: "17194667"
                  mobilePhone:
                    type: string
                    required: true
                    example: "3103022312"
                  mobilePhone2:
                    type: string
                    required: true
                    example: "3103022312"
                  phoneNumber:
                    type: string
                    required: true
                    example: "6012140066"
                  email:
                    type: string
                    required: true
                    example: "jucafe18@gmail.com"
              item:
                type: object
                properties:
                  store:
                    type: string
                    required: true
                    example: "EMERGIA"
                  material:
                    type: string
                    required: true
                    example: "110-00007"
                  type:
                    type: string
                    required: true
                    example: "SIMCard"
                  subType:
                    type: string
                    required: true
                    example: "Postpago"
                  name:
                    type: string
                    required: true
                    example: "PLAN CONTROL MIXTO 40GB 6.0"
                  campaign:
                    type: string
                    required: true
                    example: "Venta LTE NCP"
                  value:
                    type: number
                    required: true
                    example: 44900
                  quantity:
                    type: number
                    required: true
                    example: 1

