#%RAML 1.0 DataType

properties:
  wsRequestConsultEvidentVerification:
    type: object
    properties:
      header:
        type: object
        properties:
          properties:
            type: array
            required: false
            items:
              type: object
              properties:
                name:
                  type: string
                  description: "Required names: MODELO, CIUDAD, SISTEMA_ORIGEN, CODIGO_DEPARTAMENTO, CODIGO_CIUDAD, CALCULAR_SCORE"
                  required: true
                value:
                  type: string
                  required: true
      answers:
        type: object
        properties:
          regQuestionnaire:
            type: string
            required: false
          identification:
            type: object
            required: false
            properties:
              number:
                type: string
                required: false
              type:
                type: string
                required: false
          answer:
            type: array
            required: false
            items:
              type: object
              properties:
                questionId:
                  type: string
                  required: false
                answerId:
                  type: string
                  required: false           
example: !include ../../examples/request/evidentVerification.json