#%RAML 1.0 DataType
type: object
properties:
  entityCode:
    type: string | nil
    required: false
    example: "12344321"
  entityAuthorizationId:
    type: string | nil
    required: false
    example: "11223344"