#%RAML 1.0 DataType
type: object
properties:
  body:
    type: object
    required: true
    properties:
      MensajeABD:
        type: object
        required: true
        properties:
          CabeceraMensaje: 
            type: object
            required: true
            properties:
              IdentificadorProceso: 
                type: string
                required: true
                example: "00007202405060000644"
              IdentificadorMensaje: 
                type: string
                required: true
                example: "00007202405060000963"
              FechaCreacionMsg: 
                type: string
                required: true
                example: "20240620145729"
              TipoMsg: 
                type: string
                required: true
                example: "0003"
              Emisor: 
                type: string
                required: true
                example: "00007"
              Observaciones: 
                type: string | nil
                required: false
                example: ""
          CuerpoMensaje:
            type: any
  attachments:
    type: any
    required: false
