#%RAML 1.0 DataType 
type: object
properties:
  entityCode:
    type: string
    example: '8999991158'
    required: false
  financialInstitutionCode:
    type: string
    example: '1007'
    required: false
  serviceCode:
    type: string
    example: '1002'
    required: false
  transactionValue:
    type: integer
    example: 1000000
    required: false
  vatValue:
    type: integer
    example: 190000
    required: false
  ticketId:
    type: integer
    example: 30001
    required: false
  entityurl:
    type: string
    example: https://www.tucomercio.com/return?id=30001
    required: false
  userType:
    type: string
    example: person
    required: false
  referenceNumber1:
    type: string
    example: REF001
    required: false
  referenceNumber2:
    type: string
    example: REF002
    required: false
  referenceNumber3:
    type: string
    example: REF003
    required: false
  soliciteDate:
    type: string
    example: '2026-02-02T10:25:00.000'
    required: false
  paymentDescription:
    type: string
    example: Pago factura servicios
    required: false
  identificationType:
    type: string
    example: CedulaDeCiudadania
    required: false
  identificationNumber:
    type: string
    example: '11111111'
    required: false
  fullName:
    type: string
    example: Juan Perez
    required: false
  cellphoneNumber:
    type: string
    example: '3014567890'
    required: false
  address:
    type: string
    example: 'Calle 10 #20-30'
    required: false
  email:
    type: string
    example: pruebas@correo.com
    required: false
  beneficiaryEntityIdentificationType:
    type: string
    example: NIT
    required: false
  beneficiaryEntityIdentification:
    type: string
    example: '900123456'
    required: false
  beneficiaryEntityName:
    type: string
    example: Comercio Pruebas SAS
    required: false
  beneficiaryEntityCIIUCategory:
    type: string
    example: '4652'
    required: false
  beneficiaryIdentificationType:
    type: string
    example: CedulaDeCiudadania
    required: false
  beneficiaryIdentification:
    type: string
    example: '11111111'
    required: false
  indicator4per1000:
    type: integer
    example: 0
    required: false
