#%RAML 1.0 DataType
properties:
  Msisdn:
    type: any
  NombrePersona: 
    type: string
  TipoDocumento: 
    type: string
  NumeroDocumento: 
    type: string
  TipoSolicitud:
    type: integer
  Email:
    type: string
  SistemaOrigen:
    type: string
  ConfirmacionCrc:
    type: string
  