#%RAML 1.0 DataType

properties:
  textMessage:
    type: object
    properties:
      phoneNumber:
        type: number
        example: 3057000415
      message:
        type: string
        example: "BIENVENIDO A MOVILES ETB! Tu Plan ya está activo, y tu número es 3057000415 Disfrútalo y ten el control de tu línea a través de la App 4GETB"