#%RAML 1.0 DataType

properties:
  description:
    type: string
    enum: [addONT, addService]
    required: true
    description: Descripción de la acción a realizar en el inventario
    example: "addONT"
  relatedParty:
    type: array
    minItems: 1
    required: true
    description: Arreglo con la información de la VNO
    items:
      type: object
      properties:
        id:
          type: string
          required: true
          minLength: 1
          maxLength: 200
          description: ID de la VNO
          example: "123"
        name:
          type: string
          required: false
          maxLength: 200
          description: Nombre de la VNO
          example: "VNO Name"
  parameters:
    type: array
    minItems: 1
    required: true
    description: Arreglo con la información técnica y de reserva
    items:
      type: any