#%RAML 1.0 DataType
type: object
properties:
  wsIdentificationValidationNegRequest:
    type: object
    required: true
    properties:
      identificationValidation:
        type: object
        required: true
        properties:
          validationObject:
            type: object
            required: true
            properties:
              identificationType:
                type: string
                required: true
                minLength: 1
                example: "9"
              identification:
                type: string
                required: true
                minLength: 1
                example: "901560597"
              correlationID:
                type: string | nil 
                required: false
                example: "MDM-LISIM-VIGENCIA-NIT-901560597"
              apellido:
                type: string | nil 
                required: false
                example: "Doe"
              nombre:
                type: string | nil
                required: false
                example: "COLBENZ SAS"
              tramite:
                type: string | nil
                required: false
                example: "VTA"
              usuario:
                type: string | nil
                required: false
                example: "LUISBARO"
              canal:
                type: string | nil
                required: false
                example: "PORTAL FIJA"
              proveedor:
                type: string | nil
                required: false
                example: "Supplier"
              ciudad:
                type: string | nil
                required: false
                example: "BOGOTA D.C."
              departamento:
                type: string | nil
                required: false
                example: "BOGOTA"
              sistemaOrigen:
                type: string | nil
                required: false
                example: "PORTAL FIJA"
              modelo:
                type: string | nil
                required: false
                example: "2"
              portal:
                type: string | nil
                required: false
                example: ""
              numeroContacto:
                type: string | nil
                required: false
                example: "112233445"
              tipo:
                type: string | nil
                required: false
                example: ""
              estrato:
                type: string | nil
                required: false
                example: ""
              calcularScore:
                type: string | nil
                required: false
                example: ""
    
              