#%RAML 1.0 DataType
properties:
  sCodInformacion?:
    type: string | nil
    example: "31415161"
  sMotConsulta?:
    type: string | nil
    example: "Motivo de la Consulta"
  sTipoDocumento:
    type: string
    enum: [C.C, C.D, C.E, E.S.N, FID, NIT, PAS, R.C, SEG, T.I]
    example: "C.C"
    required: true
  sNumDocumento:
    type: string
    example: "1030708585"
    required: true
  sFecDocumento:
    type: string
    example: "2019-12-18"
    required: true
  sPrimerApellido?:
    type: string | nil
    example: "Doe"
  tramite?:
    type: string | nil
    example: "Tramite"
  usuario?:
    type: string | nil
    example: "Usuario"
  canal?:
    type: string | nil
    example: "Canal"
  proveedor?:
    type: string | nil
    example: "Proveedor"
  departamento?:
    type: string | nil
    example: "Departamento"