# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "20593061"

# --- Common PAPI HTTP Requester ---
commonPapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-papi-services-v2-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/v2"
  parameters:
    path: "/parameters"
    get:
      method: "GET"
  documents:
    path: "/documents"
    post:
      method: "POST"
  troubleTicket:
    path: "/troubleTicket"
    post:
      method: "POST"
  communicationThirdPartyMessage:
    path: "/communications/third-party/message"
    post:
      method: "POST"
  userIdp:
    path: "/userIdp"
    post:
      method: "POST"
    get:
      method: "GET"
    delete:
      method: "DELETE"
    login:
     path: "/login"
  userIdpById:
    path: "/userIdp/{id}"
    patch:
      method: "PATCH"
  jwks:
    path: "/security/ott/jwks"
    get:
      method: "GET"