#%RAML 1.0 DataType
type: object
description: Represents configuration values for delivery times per message category (in seconds).
properties:
  otpTime:
    type: number
    description: Delivery time limit for OTP messages (in seconds).
    example: 60
  regulatoryTime:
    type: number
    description: Delivery time limit for Regulatory messages (in seconds).
    example: 120
  campaignTime:
    type: number
    description: Delivery time limit for Campaign messages (in seconds).
    example: 300
