#%RAML 1.0 DataType
displayName: Patch Order(MDM_CD_ORDER) Message Input
type: object
properties:
  serial: 
    type: string
  ontType:
    type: string
  transactionType:
    type: string
  serviceIndex:
    type: integer
  childServiceIndex:
    type: integer
  codeService:
    type: string
  descriptionService:
    type: string
  codeOrder:
    type: string
  descriptionOrder:
    type: string
  errorProvisioning:
    type: boolean
  serialOld?: 
    type: string | nil
  ontTypeOld?:
    type: string | nil
example:
  serial: "1"
  transactionType: "commit"
  ontType: "XYZ"
  serviceIndex: 0
  childServiceIndex: 0
  codeService: "44"
  descriptionService: "Rollback en Proceso"
  codeOrder: "30"
  descriptionOrder: "Activacion en proceso"
  errorProvisioning: false