#%RAML 1.0 DataType
type: object
displayName: Mensaje enviado - información SMPP
properties:
  uuids:
    type: array
    items: string
    description: Lista de identificadores (UUID) asociados al/los mensaje(s).
    example: ["13839cfc-ab77-4754-a1cc-75e92758352e"]
  codigoEstado:
    type: string
    description: Código del estado reportado.
    example: "MSG_SENT_INFO"
  smscId:
    type: string
    description: Identificador asignado por el SMSC/operador.
    example: "SMSC-ACME-01"
  fechaRespuesta:
    type: datetime
    description: Fecha y hora en que ocurrió la respuesta.
    example: "2025-09-10T14:16:00.000+00:00"
  respuestaSMSC:
    type: string
    description: Respuesta textual/de estado devuelta por el SMSC.
    example: "Message accepted for delivery"
  metadata:
    type: object
    description: Metadatos complementarios del envío.
    properties:
      prioridad?:
        type: string
        example: "Baja"
      canalEnvio?:
        type: string
        example: "SMPP"
      tipoMensaje?:
        type: string
        example: "CAMPAIGN"
      origenIP?:
        type: string
        example: "10.0.0.5"
