#%RAML 1.0 DataType
properties:
  "message":
    type: object
    description: "El contenido o payload del mensaje"
    properties:
      destinations:
        description: "Lista de números de teléfono."
        type: array
        items:
          type: string
        example: ["573009999999"]
      message:
        description: "Contenido del mensaje a guardar"
        type: string
        example: "Su código de verificación es 123456."
      category:
        description: "Categoría del mensaje (OTP, regulatorios, campañas)."
        type: string
        enum:
          - OTP
          - REGULATORY
          - CAMPAIGN
        example: "OTP"
      customSenderNumber?:
        description: "Opcional para especificar un número de envío particular, útil para campañas"
        type: string
        example: "3005550000"
  createdAt: 
    type: string
    description: "Marca de tiempo para la creación del mensaje en formato Fecha y hora"
  status:
    type: string
    description: "Indica el estado del mensaje"
  priority: 
    type: number
    description: "Prioridad del mensaje"
