#%RAML 1.0 DataType
properties:
  RequestAcuerdo:
    type: string
    required: false
  ResponseAcuerdo:
    type: string
    required: false
  FechaEnvio:
    type: string
    required: false
  FechaRespuesta:
    type: string
    required: false
  Aasesor: 
    type: string
    required: false
  Aplicacion: 
    type: string
    required: false
  NumeroDocumento:
    type: string
    required: false