#%RAML 1.0 DataType
type: object
properties:
  ordenOM: 
    type: string[]
    required: false
  fechaCreacion: 
    type: string | nil
    required: false
  idCuentaFacturacion: 
    type: string | nil
    required: false
  cuentaFacturacion: 
    type: string | nil
    required: false
  cicloFacturacion: 
    type: string | nil
    required: false
  corte: 
    type: string | nil
    required: false
  estado: 
    type: string | nil
    required: false
  fechaEstado: 
    type: string | nil
    required: false
    
example: !include ../../examples/request/postBillingAccountsExample.json