#%RAML 1.0 DataType
properties:
  Actualizacion_Contraseña:
    type: boolean
    example: true
    required: false
  FechaActivacion:
    type: datetime
    example: "2023-01-01T00:00:00Z"
  FechaExpedicion:
    type: string
    example: "01/01/1999"
  Estado:
    type: boolean
    example: false
  Estado_Registro:
    type: string
    example: "Pre-Registro"
  Identificador_Peticion_Creacion:
    type: string
    example: "MDM-FIBRA-000177747"
  Mail:
    type: string
    example: "aaa@gmail.com"
  NumIdentificacion:
    type: string
    example: "12345678"
  Password:
    type: string
    example: "password"
  Requiere_Actualizar_Pwd:
    type: boolean
    example: false
  TipoIdentificacion:
    type: string
    example: "CC"
  TipoRegistro:
    type: string
    example: "Registro Light"
  Widgets:
    type: array
    items:
      type: object
      properties:
        Application_Date:
          type: string
          example: "2023-01-03T16:07:29.4524664Z"
        Widget:
          type: object
          properties:
            "_id":
              type: string
              example: "6217d775f3893c92053f231e"
            Widget:
              type: string
              example: "Servicios"