#%RAML 1.0 DataType
type: object
properties:
  FechaHoraRegistro:
    type: string
    required: true
  Id_Iteracion:
    type: string
    required: true
  Numero_Whatsapp:
    type: string
    required: true
  Sistema_Origen:
    type: string
    required: false
  Fecha_Hora:
    type: string
    required: false
  Procesado:
    type: boolean
    required: true
  Tramite:
    type: string
    required: false
  Opciones_Plantilla:
    type: array
    required: false
    items:
      type: object
  Numero_Orden:
    type: string
    required: false
  Cuenta:
    type: string
    required: false
  Numero_Factura:
    type: string
    required: false
  Numero_Cuenta_Pago:
    type: string
    required: false
  Nombre_Cliente:
    type: string
    required: false
  Apellido_Cliente:
    type: string
    required: false
  Tipo_Documento:
    type: string
    required: false
  Numero_Documento:
    type: string
    required: false
  Identificador_Tramite:
    type: string
    required: false
  CUN:
    type: string
    required: false
  Numero_Servicio:
    type: string
    required: false
  Plantilla:
    type: string
    required: false
  Valores_Plantilla:
    required: false
    type: array
    items:
      type: string
      example: "Traslado Parameter 3"