#%RAML 1.0 DataType
type: object
properties:
  num_agrupacion:
    type: number
    required: false
    example: 6166
  parametros_bundle.parametro:
    type: string
    required: false
    example: "FAMILIA"  
  parametros_bundle.valor:
    type: string
    required: false
    example: "DIRECTV"   
  tipo_producto:
    type: string
    required: false
    example: "BUNDLE"      