#%RAML 1.0 DataType
type: array
items: 
  type: object
  properties:
    mensajeId:
      type: string
      example: "6302526f-c7ef-472d-8b11-7fa4a21b13c4"
    sistemaOrigen:
        type: string
        example: "CRM"
    numeroDestino:
      type: string
      example: "573009999999"
    contenidoSMS:
      type: string
      example: "Inscríbete en nuestro servicio"
    fechaRecepcion:
      type: datetime
      example: "2025-10-09T19:45:06Z"
    historialEstados:
      description: Bitácora de estados del procesamiento.
      type: array
      items:
        type: object
        properties:
          codigoEstado:
            type: string
            example: "MSG_RECEIVED"
          estado:
            type: string
            example: "Mensaje Recibido"
          detalle:
            type: string
            example: "El sistema ha recibido correctamente la solicitud de envío."
          fecha:
            type: datetime
            example: "2025-10-09T19:45:06Z"
          usuario:
            type: string
            example: "MuleSoft"
          codigoError?:
            type: string
            example: "SMPP_CONNECTION_FAILED"
          reintentos?:
            type: integer
            example: 2

    smscId?:
      type: string
      example: "2"
    respuestaSMSC?:
      type: string
      example: "DELIVERED"
    fechaRespuesta?:
      type: datetime
      example: "2025-10-09T19:58:00Z"

    usuarioRegistro:
      type: string
      example: "MuleSoft"

    metadata:
      type: object
      properties:
        prioridad:
          type: string
          example: "3"
        canalEnvio:
          type: string
          example: "Directo"
        tipoMensaje:
          type: string
          example: "Transaccional"
        origenIP:
          type: string
          example: ""
