#%RAML 1.0 DataType
properties:
  IdProceso:
    type: any
    example: "00007202406120100449"
    required: false
  IdMensaje:
    type: any
    example: "00007202406120001788"
    required: false
  IdIntegracion:
    type: any
    example: "MDM-MOV-328963"
    required: false
  NumeroRepresentante:
    type: any
    example: null
    required: false
  Numeracion:
    type: any
    example: null
    required: false
  TipoMsg:
    type: any
    example: "1006"
    required: false
  FechaCreacionMsg:
    type: any
    example: "20240612160524"
    required: false
  Emisor:
    type: any
    example: "00007"
    required: false
  Donante:
    type: any
    example: null
    required: false
  SistemaOrigen:
    type: any
    example: "MDM-MOV"
    required: false
  RespuestaABD:
    type: any
    example: "ack"
    required: false
  CodigosRechazo:
    type: any
    example: null
    required: false