#%RAML 1.0 DataType
properties:
  TipoDocumento:
    type: string
    required: false
  NumeroDocumento:
    type: string
    required: false
  UsuarioEnvioAcuerdo:
    type: string
    required: false
  FechaEnvio:
    type: string
    required: false
  NumeroOrden: 
    type: string
    required: false
  FirmantesAcuerdo: 
    type: string
    required: false
  EmailDestinatario:
    type: string
    required: false
  EmailCopia: 
    type: string
    required: false
  NumeroAcuerdo: 
    type: string
    required: false
  TipoTramite: 
    type: string
    required: false
  EstadoTramite: 
    type: string
    required: false
  FechaVencimientoTramite: 
    type: string
    required: false
  FechaRegistroTramite: 
    type: string
    required: false
  FechaActualizacionTramite: 
    type: string
    required: false