#%RAML 1.0 DataType
displayName: Put Order(MDM_CD_ORDER) Message Input
type: object
properties:
  _id: 
    type: object
    required: false
  Fecha_Creacion: 
      type: string
      required: false
  Fecha_Modificacion:
      type: string
      required: false
  Usuario_Modificacion:
      type: string
      required: false
  Usuario_Creacion:
      type: string
      required: false
  Actualizacion_Extractor:
      type: string
      required: false
  Numero_Orden:
      type: string
      required: false
  Canal:
      type: string
      required: false
  Fase:
      type: string
      required: false 
  Estado_Orden_Comercial:
    type: object
    properties:
      Codigo:
          type: string
          required: false
      Descripcion:
          type: string
          required: false
      Fecha:
          type: string
          required: false
      Reintentos:
          type: number
          required: false
      CodigoExcepcion:
          type: number
          required: false
  Tramite:
    type: object
    required: false
    properties:
      Tipo_Tramite:
          type: string
          required: false
      Subtipo_Tramite:
          type: string | nil
          required: false
      Fecha_Tramite:
          type: string
          required: false
      Fecha_Reconexion:
          type: string | nil
          required: false
      Fecha_Suspension:
          type: string | nil
          required: false
      Fecha_Ejecucion:
          type: string
          required: false
      Conservar_Numero_Conexion:
          type: boolean
          required: false
      Clausula_Permanencia:
          type: boolean
          required: false
      Valor_Clausula_Permanencia:
          type: number
          required: false
      Causal_Cancelacion:
          type: string | nil
          required: false
      Subcausal_Cancelacion:
          type: string | nil
          required: false
      Descripcion_Cancelacion:
          type: string | nil
          required: false
      MotivosOrden:
          type: string | nil
          required: false
  Tipo_Servicio:
    type: string | nil
    required: false
  CUN:
    type: string | nil
    required: false
  Cliente_Anterior:
    type: string | nil
    required: false
  Cliente_Tramite:
    type: object
    properties: 
      _id:
        type: object
        required: false
      Fecha_Creacion:
        type: string | nil
        required: false
      Fecha_Modificacion:
        type: string | nil
        required: false
      Usuario_Modificacion:
        type: string | nil
        required: false
      Usuario_Creacion:
        type: string | nil
        required: false
      Actualizacion_Extractor:
        type: string | nil
        required: false
      Id_Cuenta_Cliente:
        type: integer
        required: false
      Tipo_Documento:
        type: string
        required: false
      Numero_Documento:
        type: string
        required: false
      Nombres:
        type: string
        required: false
      Nombre_Corto_Empresa:
        type: string
        required: false
      Primer_Apellido:
        type: string
        required: false
      Segundo_Apellido:
        type: string
        required: false
      Fecha_Expedicion:
        type: string | nil
        required: false
      Fecha_Validacion_Identidad:
        type: string | nil
        required: false
      Autoriza_Manejo_Datos_Personales:
        type: string | nil
        required: false
      Autoriza_Consulta_Centrales:
        type: string | nil
        required: false
      UEN:
        type: string
        required: false
      Segmento_UEN:
        type: string | nil
        required: false
      Segmento:
        type: string | nil
        required: false
      Scoring_Fija: 
        type: string | nil
        required: false
      Telefono_Fijo:
        type: string
        required: false
      Extension:
        type: nil | string
        required: false
      Telefono_Movil:
        type: string
        required: false
      Telefono_Movil2:
        type: string
        required: false
      Email:
        type: string
        required: false
      Contactos:
        type: array
        required: false
      Direcciones:
        type: array
        required: false
        items:
          type: object
          properties:
            Id_Direccion:
              type: integer
              required: false
            Direccion_Normalizada:
              type: string
              required: false
            Tipo_Direccion:
              type: string
              required: false
            Codigo_Direccion:
              type: string
              required: false
            Codigo_Departamento:
              type: string
              required: false
            Codigo_Municipio:
              type: string
              required: false
            Codigo_Pais:
              type: string
              required: false
            Nombre_Direccion:
              type: string | nil
              required: false
            Estado:
              type: string
              required: false
            Cobertura:
              type: object
              properties:
                Direccion_GIS:
                  type: string | nil
                  required: false
                Tecnologia:
                  type: string | nil
                  required: false
                Tipo_Cobertura:
                  type: string | nil
                  required: false
                NombreCobertura:
                  type: string | nil
                  required: false
                Zona:
                  type: string | nil
                  required: false
                Latitud:
                  type: string | integer | number
                  required: false
                Longitud:
                  type: string | integer | number
                  required: false
                Proposito:
                  type: string | nil
                  required: false
                Codigo_Lote:
                  type: string | nil
                  required: false
                Localidad:
                  type: string | nil
                  required: false
                Estrato:
                  type: string | nil | integer
                  required: false
                TipoDistancia:
                  type: string | nil
                  required: false
                Molecula:
                  type: string | nil
                  required: false
                Viable:
                  type: boolean | nil
                  required: false
                Olt:
                  type: string | nil
                  required: false
                Propietario:
                  type: string | nil
                  required: false
            Seleccionada:
              type: boolean
              required: false
            Departamento:
              type: string
              required: false
            Municipio:
              type: string
              required: false
      Cuentas_Facturacion:
        type: string | nil
        required: false
      Cuentas_Servicio:
        type: string | nil
        required: false
      Adjuntos_Cliente:
        type: array
        required: false
      Sistema_Origen:
        type: string | nil
        required: false
      Estado:
        type: string | nil
        required: false
      CarruselMotivo:
        type: string | nil
        required: false
      CarruselSubMotivo:
        type: string | nil
        required: false
      Direccion:
        type: string | nil
        required: false
      Cobertura:
        type: string | nil
        required: false
      Departamento:
        type: string | nil
        required: false
      Ciudad:
        type: string | nil
        required: false
  Servicio_Anterior:
    type: object
    required: false
    properties:
      _id:
        type: string | object
        required: false
      Fecha_Creacion:
        type: string | nil
        required: false
      Fecha_Modificacion:
        type: string | nil
        required: false
      Usuario_Modificacion:
        type: string | nil
        required: false
      Usuario_Creacion:
        type: string | nil
        required: false
      Actualizacion_Extractor:
        type: object | nil
        required: false
      Id_Cuenta_Servicio:
        type: string | nil
        required: false
      Bundle:
        type: object
        required: false
        properties:
          _id:
            type: string | object
            required: false
          Fecha_Creacion:
            type: string | nil
            required: false
          Fecha_Modificacion:
            type: string | nil
            required: false
          Usuario_Modificacion:
            type: string | nil
            required: false
          Usuario_Creacion:
            type: string | nil
            required: false
          Actualizacion_Extractor:
            type: string | nil
            required: false
          Codigo_Configuracion:
            type: string | nil
            required: false
          Numero_Agrupacion:
            type: integer | nil
            required: false
          Tipo_Producto:
            type: string
            required: false
          Tipo_Servicio:
            type: string | nil
            required: false
          Subtipo_Servicio:
            type: string | nil
            required: false
          Subtipo_Producto:
            type: string | nil
            required: false
          Secuencia:
            type: integer | nil
            required: false
          Dependencia:
            type: integer | nil
            required: false
          Id_Clase_Servicio:
            type: integer | nil
            required: false
          Clasificacion:
            type: string | nil
            required: false
          Disponibilidad:
            type: boolean
            required: false
          Agendamiento:
            type: boolean
            required: false
          Aprovisionamiento:
            type: boolean
            required: false
          Facturacion:
            type: boolean
            required: false
          Accion:
            type: string | nil
            required: false
          Id_Item:
            type: string | nil
            required: false
          Id_Item_Padre:
            type: string | nil
            required: false
          Id_Tipo_Producto:
            type: integer | nil
            required: false
          Id_Tipo_Servicio:
            type: integer | nil
            required: false
          Id_Subtipo_Servicio:
            type: integer | nil
            required: false
          Id_Subtipo_Producto:
            type: integer | nil
            required: false
          id_opcional_auxiliar:
            type: string | nil
            required: false
          Id_Servicio:
            type: string | nil
            required: false
          tipo_adicional:
            type: string | nil
            required: false
          Parametros_Producto:
            type: any
            required: false
          seleccionado:
            type: boolean
            required: false
          deshabilitado:
            type: boolean
            required: false
          Nombre:
            type: string | nil
            required: false
          Icono:
            type: string | nil
            required: false
          Display:
            type: string | nil
            required: false
          Estado:
            type: string | nil
            required: false
          Cantidad_Minima:
            type: number | nil
            required: false
          Cantidad_Maxima:
            type: number | nil
            required: false
          Precio_Oferta:
            type: array
            required: false
            items:
              type: object
              properties: 
                Canal_Venta:
                  type: string | nil
                  required: false
                Precio_Sin_Iva:
                  type: number | nil
                  required: false
                Precio_Con_Iva:
                  type: number | nil
                  required: false
                Iva:
                  type: number | nil
                  required: false
          Tipo_Bundle:
            type: string | nil
            required: false
          Parametros_bundle:
            type: array
            required: false
          Primarios:
            type: array
            required: false
            items:
              type: object
              properties: 
                _id:
                  type: string | object
                  required: false
                Fecha_Creacion:
                  type: string | nil
                  required: false
                Fecha_Modificacion:
                  type: string | nil
                  required: false
                Usuario_Modificacion:
                  type: string | nil
                  required: false
                Usuario_Creacion:
                  type: string | nil
                  required: false
                Actualizacion_Extractor:
                  type: string | nil
                  required: false
                Codigo_Configuracion:
                  type: string | nil
                  required: false
                Numero_Agrupacion:
                  type: integer | nil
                  required: false
                Tipo_Producto:
                  type: string | nil
                  required: false
                Tipo_Servicio:
                  type: string | nil
                  required: false
                Subtipo_Servicio:
                  type: string | nil
                  required: false
                Subtipo_Producto:
                  type: string | nil
                  required: false
                Secuencia:
                  type: number | nil
                  required: false
                Dependencia:
                  type: number | nil
                  required: false
                Clasificacion:
                  type: string | nil
                  required: false
                Nombre:
                  type: string | nil
                  required: false
                Icono:
                  type: string | nil
                  required: false
                Display:
                  type: string | nil
                  required: false
                Estado:
                  type: string | nil
                  required: false
                Cantidad_Minima:
                  type: number | nil
                  required: false
                Cantidad_Maxima:
                  type: number | nil
                  required: false
                Precio_Oferta:
                  type: number | nil
                  required: false
                Caracteristicas_Producto_Oferta:
                  type: any
                  required: false
                Agrupa_filtros_oferta:
                  type: string | nil
                  required: false
                Valor_Especificacion_Tecnica_Oferta:
                  type: string | nil
                  required: false
                Id_Clase_Servicio:
                  type: integer | nil
                  required: false
                Disponibilidad:
                  type: boolean
                  required: false
                Agendamiento:
                  type: boolean
                  required: false
                Aprovisionamiento:
                  type: boolean
                  required: false
                Facturacion:
                  type: boolean
                  required: false
                Accion:
                  type: string | nil
                  required: false
                Id_Item:
                  type: string | nil
                  required: false
                Id_Item_Padre:
                  type: string | nil
                  required: false
                Id_Tipo_Producto:
                  type: integer | nil
                  required: false
                Id_Tipo_Servicio:
                  type: integer | nil
                  required: false
                Id_Subtipo_Servicio:
                  type: integer | nil
                  required: false
                Id_Subtipo_Producto:
                  type: integer | nil
                  required: false
                Id_Servicio:
                  type: integer | nil | string
                  required: false
                id_opcional_auxiliar:
                  type: integer | nil
                  required: false
                Atributos:
                  type: array
                  required: false
                  items:
                    type: object
                    properties:
                      Nombre:
                        type: string | nil
                        required: false
                      Valor:
                        type: string | nil
                        required: false
                      Tipo:
                        type: string | nil
                        required: false
                tipo_adicional:
                  type: string | nil
                  required: false
                Parametros_Producto:
                  type: any
                  required: false
                seleccionado:
                  type: boolean
                  required: false
                deshabilitado:
                  type: boolean
                  required: false
                Secundarios:
                  type: array
                  required: false
                  items:
                    type: object
                    properties:
                      _id:
                        type: string | object
                        required: false
                      Fecha_Creacion:
                        type: string | nil
                        required: false
                      Fecha_Modificacion:
                        type: string | nil
                        required: false
                      Usuario_Modificacion:
                        type: string | nil
                        required: false
                      Usuario_Creacion:
                        type: string | nil
                        required: false
                      Actualizacion_Extractor:
                        type: string | nil
                        required: false
                      Codigo_Configuracion:
                        type: string | nil
                        required: false
                      Numero_Agrupacion:
                        type: integer | nil
                        required: false
                      Tipo_Producto:
                        type: string | nil
                        required: false
                      Tipo_Servicio:
                        type: string | nil
                        required: false
                      Subtipo_Servicio:
                        type: string | nil
                        required: false
                      Subtipo_Producto:
                        type: string | nil
                        required: false
                      Secuencia:
                        type: number | nil
                        required: false
                      Dependencia:
                        type: number | nil
                        required: false
                      Clasificacion:
                        type: string | nil
                        required: false
                      Nombre:
                        type: string | nil
                        required: false
                      Icono:
                        type: string | nil
                        required: false
                      Display:
                        type: string | nil
                        required: false
                      Estado:
                        type: string | nil
                        required: false
                      Cantidad_Minima:
                        type: number | nil
                        required: false
                      Cantidad_Maxima:
                        type: number | nil
                        required: false
                      Precio_Oferta:
                        type: number | nil
                        required: false
                      Caracteristicas_Producto_Oferta:
                        type: any
                        required: false
                      Agrupa_filtros_oferta:
                        type: string | nil
                        required: false
                      Valor_Especificacion_Tecnica_Oferta:
                        type: string | nil
                        required: false
                      Id_Clase_Servicio:
                        type: integer | nil
                        required: false
                      Disponibilidad:
                        type: boolean
                        required: false
                      Agendamiento:
                        type: boolean
                        required: false
                      Aprovisionamiento:
                        type: boolean
                        required: false
                      Facturacion:
                        type: boolean
                        required: false
                      Accion:
                        type: string | nil
                        required: false
                      Id_Item:
                        type: integer | nil | string
                        required: false
                      Id_Item_Padre:
                        type: integer | nil
                        required: false
                      Id_Tipo_Producto:
                        type: integer | nil
                        required: false
                      Id_Tipo_Servicio:
                        type: integer | nil
                        required: false
                      Id_Subtipo_Servicio:
                        type: integer | nil
                        required: false
                      Id_Subtipo_Producto:
                        type: integer | nil
                        required: false
                      Id_Servicio:
                        type: integer | nil | string
                        required: false
                      id_opcional_auxiliar:
                        type: integer | nil
                        required: false
                      Atributos:
                        type: array
                        required: false
                        items:
                          type: object
                          properties:
                            Nombre:
                              type: string | nil
                              required: false
                            Valor:
                              type: string | nil
                              required: false
                            Tipo:
                              type: string | nil
                              required: false
                      tipo_adicional:
                        type: string | nil
                        required: false
                      Parametros_Producto:
                        type: any
                        required: false
                      seleccionado:
                        type: boolean
                        required: false
                      deshabilitado:
                        type: boolean
                        required: false
                Adicionales:
                  type: array
                  required: false
                Gold:
                  type: string | nil
                  required: false
                Numero:
                  type: string
                  required: false
      Bundle_Clausula_Permanencia:
        type: string | nil
        required: false
      Opcionales:
        type: string | nil | array
        required: false
      Promociones:
        type: string | nil | array
        required: false
      Cliente:
        type: any
        required: false
      Estado:
        type: any
        required: false
      Id_Orden_Tramite:
        type: string | nil
        required: false
      Id_Cuenta_Facturacion:
        type: string | nil
        required: false
      Sistema_Origen:
        type: any
        required: false
      Id_Direccion_Instalacion:
        type: integer | nil
        required: false
      Fecha_Activacion:
        type: string | nil
        required: false
      Clausula_Permanencia:
        type: string | nil
        required: false
      Numero_Conexion_Anterior:
        type: number | nil
        required: false
      Id_SalesForce:
        type: integer | nil
        required: false
      Integration_Id:
        type: string | nil
        required: false
      Adjuntos:
        type: array
        required: false
      Proyecto:
        type: string | nil
        required: false
      Riesgo_Churn:
        type: string | nil
        required: false
      Is_Pago_Recurrente:
        type: boolean
        required: false
      Promociones_Condicionadas:
        type: array
        required: false
  Servicio_Tramite:
    type: object
    required: false
    properties:
      _id:
        type: string | object
        required: false
      Fecha_Creacion:
        type: string | nil
        required: false
      Fecha_Modificacion:
        type: string | nil
        required: false
      Usuario_Modificacion:
        type: string | nil
        required: false
      Usuario_Creacion:
        type: string | nil
        required: false
      Actualizacion_Extractor:
        type: object | nil
        required: false
      Id_Cuenta_Servicio:
        type: string | nil
        required: false
      Bundle:
        type: object
        required: false
        properties:
          _id:
            type: string | object
            required: false
          Fecha_Creacion:
            type: string | nil
            required: false
          Fecha_Modificacion:
            type: string | nil
            required: false
          Usuario_Modificacion:
            type: string | nil
            required: false
          Usuario_Creacion:
            type: string | nil
            required: false
          Actualizacion_Extractor:
            type: string | nil
            required: false
          Codigo_Configuracion:
            type: string | nil
            required: false
          Numero_Agrupacion:
            type: integer | nil
            required: false
          Tipo_Producto:
            type: string
            required: false
          Tipo_Servicio:
            type: string | nil
            required: false
          Subtipo_Servicio:
            type: string | nil
            required: false
          Subtipo_Producto:
            type: string | nil
            required: false
          Secuencia:
            type: integer | nil
            required: false
          Dependencia:
            type: integer | nil
            required: false
          Id_Clase_Servicio:
            type: integer | nil
            required: false
          Clasificacion:
            type: string | nil
            required: false
          Disponibilidad:
            type: boolean
            required: false
          Agendamiento:
            type: boolean
            required: false
          Aprovisionamiento:
            type: boolean
            required: false
          Facturacion:
            type: boolean
            required: false
          Accion:
            type: string | nil
            required: false
          Id_Item:
            type: string | nil
            required: false
          Id_Item_Padre:
            type: string | nil
            required: false
          Id_Tipo_Producto:
            type: integer | nil
            required: false
          Id_Tipo_Servicio:
            type: integer | nil
            required: false
          Id_Subtipo_Servicio:
            type: integer | nil
            required: false
          Id_Subtipo_Producto:
            type: integer | nil
            required: false
          id_opcional_auxiliar:
            type: string | nil
            required: false
          Id_Servicio:
            type: string | nil
            required: false
          tipo_adicional:
            type: string | nil
            required: false
          Parametros_Producto:
            type: any
            required: false
          seleccionado:
            type: boolean
            required: false
          deshabilitado:
            type: boolean
            required: false
          Nombre:
            type: string | nil
            required: false
          Icono:
            type: string | nil
            required: false
          Display:
            type: string | nil
            required: false
          Estado:
            type: string | nil
            required: false
          Cantidad_Minima:
            type: number | nil
            required: false
          Cantidad_Maxima:
            type: number | nil
            required: false
          Precio_Oferta:
            type: array
            required: false
            items:
              type: object
              properties: 
                Canal_Venta:
                  type: string | nil
                  required: false
                Precio_Sin_Iva:
                  type: number | nil
                  required: false
                Precio_Con_Iva:
                  type: number | nil
                  required: false
                Iva:
                  type: number | nil
                  required: false
          Tipo_Bundle:
            type: string | nil
            required: false
          Parametros_bundle:
            type: array
            required: false
          Primarios:
            type: array
            required: false
            items:
              type: object
              properties: 
                _id:
                  type: string | object
                  required: false
                Fecha_Creacion:
                  type: string | nil
                  required: false
                Fecha_Modificacion:
                  type: string | nil
                  required: false
                Usuario_Modificacion:
                  type: string | nil
                  required: false
                Usuario_Creacion:
                  type: string | nil
                  required: false
                Actualizacion_Extractor:
                  type: string | nil
                  required: false
                Codigo_Configuracion:
                  type: string | nil
                  required: false
                Numero_Agrupacion:
                  type: integer | nil
                  required: false
                Tipo_Producto:
                  type: string | nil
                  required: false
                Tipo_Servicio:
                  type: string | nil
                  required: false
                Subtipo_Servicio:
                  type: string | nil
                  required: false
                Subtipo_Producto:
                  type: string | nil
                  required: false
                Secuencia:
                  type: number | nil
                  required: false
                Dependencia:
                  type: number | nil
                  required: false
                Clasificacion:
                  type: string | nil
                  required: false
                Nombre:
                  type: string | nil
                  required: false
                Icono:
                  type: string | nil
                  required: false
                Display:
                  type: string | nil
                  required: false
                Estado:
                  type: string | nil
                  required: false
                Cantidad_Minima:
                  type: number | nil
                  required: false
                Cantidad_Maxima:
                  type: number | nil
                  required: false
                Precio_Oferta:
                  type: number | nil
                  required: false
                Caracteristicas_Producto_Oferta:
                  type: any
                  required: false
                Agrupa_filtros_oferta:
                  type: string | nil
                  required: false
                Valor_Especificacion_Tecnica_Oferta:
                  type: string | nil
                  required: false
                Id_Clase_Servicio:
                  type: integer | nil
                  required: false
                Disponibilidad:
                  type: boolean
                  required: false
                Agendamiento:
                  type: boolean
                  required: false
                Aprovisionamiento:
                  type: boolean
                  required: false
                Facturacion:
                  type: boolean
                  required: false
                Accion:
                  type: string | nil
                  required: false
                Id_Item:
                  type: string | nil
                  required: false
                Id_Item_Padre:
                  type: string | nil
                  required: false
                Id_Tipo_Producto:
                  type: integer | nil
                  required: false
                Id_Tipo_Servicio:
                  type: integer | nil
                  required: false
                Id_Subtipo_Servicio:
                  type: integer | nil
                  required: false
                Id_Subtipo_Producto:
                  type: integer | nil
                  required: false
                Id_Servicio:
                  type: integer | nil | string
                  required: false
                id_opcional_auxiliar:
                  type: integer | nil
                  required: false
                Atributos:
                  type: array
                  required: false
                  items:
                    type: object
                    properties:
                      Nombre:
                        type: string | nil
                        required: false
                      Valor:
                        type: string | nil
                        required: false
                      Tipo:
                        type: string | nil
                        required: false
                tipo_adicional:
                  type: string | nil
                  required: false
                Parametros_Producto:
                  type: any
                  required: false
                seleccionado:
                  type: boolean
                  required: false
                deshabilitado:
                  type: boolean
                  required: false
                Secundarios:
                  type: array
                  required: false
                  items:
                    type: object
                    properties:
                      _id:
                        type: string | object
                        required: false
                      Fecha_Creacion:
                        type: string | nil
                        required: false
                      Fecha_Modificacion:
                        type: string | nil
                        required: false
                      Usuario_Modificacion:
                        type: string | nil
                        required: false
                      Usuario_Creacion:
                        type: string | nil
                        required: false
                      Actualizacion_Extractor:
                        type: string | nil
                        required: false
                      Codigo_Configuracion:
                        type: string | nil
                        required: false
                      Numero_Agrupacion:
                        type: integer | nil
                        required: false
                      Tipo_Producto:
                        type: string | nil
                        required: false
                      Tipo_Servicio:
                        type: string | nil
                        required: false
                      Subtipo_Servicio:
                        type: string | nil
                        required: false
                      Subtipo_Producto:
                        type: string | nil
                        required: false
                      Secuencia:
                        type: number | nil
                        required: false
                      Dependencia:
                        type: number | nil
                        required: false
                      Clasificacion:
                        type: string | nil
                        required: false
                      Nombre:
                        type: string | nil
                        required: false
                      Icono:
                        type: string | nil
                        required: false
                      Display:
                        type: string | nil
                        required: false
                      Estado:
                        type: string | nil
                        required: false
                      Cantidad_Minima:
                        type: number | nil
                        required: false
                      Cantidad_Maxima:
                        type: number | nil
                        required: false
                      Precio_Oferta:
                        type: number | nil
                        required: false
                      Caracteristicas_Producto_Oferta:
                        type: any
                        required: false
                      Agrupa_filtros_oferta:
                        type: string | nil
                        required: false
                      Valor_Especificacion_Tecnica_Oferta:
                        type: string | nil
                        required: false
                      Id_Clase_Servicio:
                        type: integer | nil
                        required: false
                      Disponibilidad:
                        type: boolean
                        required: false
                      Agendamiento:
                        type: boolean
                        required: false
                      Aprovisionamiento:
                        type: boolean
                        required: false
                      Facturacion:
                        type: boolean
                        required: false
                      Accion:
                        type: string | nil
                        required: false
                      Id_Item:
                        type: integer | nil | string
                        required: false
                      Id_Item_Padre:
                        type: integer | nil
                        required: false
                      Id_Tipo_Producto:
                        type: integer | nil
                        required: false
                      Id_Tipo_Servicio:
                        type: integer | nil
                        required: false
                      Id_Subtipo_Servicio:
                        type: integer | nil
                        required: false
                      Id_Subtipo_Producto:
                        type: integer | nil
                        required: false
                      Id_Servicio:
                        type: integer | nil | string
                        required: false
                      id_opcional_auxiliar:
                        type: integer | nil
                        required: false
                      Atributos:
                        type: array
                        required: false
                        items:
                          type: object
                          properties:
                            Nombre:
                              type: string | nil
                              required: false
                            Valor:
                              type: string | nil
                              required: false
                            Tipo:
                              type: string | nil
                              required: false
                      tipo_adicional:
                        type: string | nil
                        required: false
                      Parametros_Producto:
                        type: any
                        required: false
                      seleccionado:
                        type: boolean
                        required: false
                      deshabilitado:
                        type: boolean
                        required: false
                Adicionales:
                  type: array
                  required: false
                Gold:
                  type: string | nil
                  required: false
                Numero:
                  type: string
                  required: false
      Bundle_Clausula_Permanencia:
        type: string | nil
        required: false
      Opcionales:
        type: string | nil | array
        required: false
      Promociones:
        type: string | nil | array
        required: false
      Cliente:
        type: any
        required: false
      Estado:
        type: any
        required: false
      Id_Orden_Tramite:
        type: string | nil
        required: false
      Id_Cuenta_Facturacion:
        type: string | nil
        required: false
      Sistema_Origen:
        type: any
        required: false
      Id_Direccion_Instalacion:
        type: integer | nil
        required: false
      Fecha_Activacion:
        type: string | nil
        required: false
      Clausula_Permanencia:
        type: string | nil
        required: false
      Numero_Conexion_Anterior:
        type: number | nil
        required: false
      Id_SalesForce:
        type: integer | nil
        required: false
      Integration_Id:
        type: string | nil
        required: false
      Adjuntos:
        type: array
        required: false
      Proyecto:
        type: string | nil
        required: false
      Riesgo_Churn:
        type: string | nil
        required: false
      Is_Pago_Recurrente:
        type: boolean
        required: false
      Promociones_Condicionadas:
        type: array
        required: false
  Orden_Servicio:
    type: object | nil
    required: false
  Agendamiento:
    type: object
    required: false
    properties:
      Franja_Agenda:
        type: string | nil
        required: false
      Codigo_Instalador:
        type: string | nil
        required: false
      Enriquecida:
        type: boolean
        required: false
      Agenda:
        type: boolean
        required: false
      ListaCuotas:
        type: array
        required: false
  Cuenta_Facturacion_Anterior:
    type: string | nil
    required: false
  Cuenta_Facturacion_Tramite:
    type: string | nil | object
    required: false
  Orden_Requiere_Disponibilidad:
    type: boolean
    required: false
  Orden_Requiere_Agendamiento:
    type: boolean
    required: false
  Precio_Total_Orden:
    type: string | nil
    required: false
  Adjuntos_Cliente:
    type: string | nil
    required: false
  Adjuntos_Servicio:
    type: string | nil
    required: false
  Caracteristica_Orden:
    type: array
    required: false
  Otros:
    type: string | nil | object
    required: false
  Presencial:
    type: boolean
    required: false
  OfertaSugerida:
    type: array
    required: false
  Reserva:
    type: string | nil
    required: false
example: !include ../../examples/request/putOrderRequest_Availablity.json