#%RAML 1.0 DataType
properties:
  integrationId:
    type: string
    example: "MDM-MOV-313948-1"
  caracteristicaServicio:
    type: array
    items:
      properties: 
        name:
          type: string
          example: "RNE"
        value:
          type: string
          example: "RECIBIR MENSAJES"