#%RAML 1.0 ResourceType
get?:
  displayName: Get <<resourcePathName | !singularize | !uppercamelcase>> By Id
  description: Get <<resourcePathName | !singularize | !uppercamelcase>> By Id
  securedBy:
    - gestor-xapi-services.etb_oauth_2_0
  is:
    - gestor-xapi-services.RequestHeaders:
   # - gestor-xapi-services.<<resourcePathName | !singularize | !uppercamelcase>>QueryParameters:
  responses:
    200:
      #is:
        #- gestor-xapi-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response
patch?:
  displayName: Update <<resourcePathName | !singularize | !uppercamelcase>> Partially By Id
  description: Update <<resourcePathName | !singularize | !uppercamelcase>> Partially By Id
  securedBy:
    - gestor-xapi-services.etb_oauth_2_0
  is:
    - gestor-xapi-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    200:
      #is:
        #- billing-experience-xapi-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response