#%RAML 1.0 DataType
type: object
properties:
  code:
    type: string
    required: true
    example: "200"

  message:
    type: string
    required: true
    example: "Subscriber retrieved successfully"

  data:
    type: object
    required: true
    properties:

      id:
        type: string
        required: false
        example: "18370911"

      serviceSpecification:
        type: object
        required: false
        properties:
          name:
            type: string
            required: true
            example: "OTT"

      state:
        type: object
        required: false
        properties:
          id:
            type: string
            required: true
            example: "6"
          name:
            type: string
            required: true
            example: "Normal"

      customer:
        type: array
        required: false
        items:
          type: object
          properties:
            id:
              type: string
              required: true
              example: "18370911"
            name:
              type: string
              required: true
              example: "ADRIAN MARIANO ANGEL"
            givenNames:
              type: string
              required: true
              example: "ADRIAN MARIANO"
            familyNames:
              type: string
              required: true
              example: "ANGEL"
            middleNames:
              type: string
              required: false
              example: ""
            aristocraticTitle:
              type: string
              required: true
              example: "Senor"

      serviceCharacteristic:
        type: array
        required: false
        items:
          type: object
          properties:

            name:
              type: string
              required: true
              example: "customerProductList"

            value:
              type: array
              required: true
              items:
                type: object
                properties:

                  # --- PRODUCT LIST ---
                  productStatus:
                    type: object
                    required: false
                    properties:
                      name:
                        type: string
                        required: true
                        example: "A - Activo"
                      id:
                        type: string
                        required: true
                        example: "4"

                  productCategory:
                    type: object
                    required: false
                    properties:
                      description:
                        type: string
                        required: true
                        example: "ACCESS HD"
                      id:
                        type: string
                        required: true
                        example: "325"

                  # --- INQUIRY LIST ---
                  interactionDateComplete:
                    type: string
                    required: false
                    example: "2026-04-17T10:44:42"

                  description:
                    type: string
                    required: false
                    example: "Cuenta activada."

                  type:
                    type: object
                    required: false
                    properties:
                      code:
                        type: string
                        required: true
                        example: "001"
                      name:
                        type: string
                        required: true
                        example: "001-Logueo IN"

                  involves:
                    type: object
                    required: false
                    properties:
                      code:
                        type: string
                        required: true
                        example: "22673"

                  involvesCreation:
                    type: object
                    required: false
                    properties:
                      code:
                        type: string
                        required: true
                        example: "22673"
                      name:
                        type: string
                        required: true
                        example: "S_CO_QAM_ESB_IBS"

                  interactionStatus:
                    type: object
                    required: false
                    properties:
                      name:
                        type: string
                        required: true
                        example: "Completo"
                      id:
                        type: string
                        required: true
                        example: "C"

# --- HBO DATA ---
      customerId:
        type: string
        example: ETB-USER-123456
        required: false
      products:
        type: array
        required: false
        items:
          type: object
          properties:
            code:
              type: string
              example: MAX_AVOD
              required: false
            name:
              type: string
              example: Max Ad VOD
              required: false
            starts:
              type: integer
              example: 1551363200
              required: false
            expires:
              type: integer
              example: 1651363200
              required: false
            status:
              type: string
              example: ACTIVE
              required: false
            subscriptionId:
              type: string
              example: a8b945f7-b93b-41b3-b0a9-3fadf89bd7c4
              required: false
            transactionId:
              type: string
              example: ae22c0f4-5ff5-4b2c-842d-da538cd247bb
              required: false