#%RAML 1.0 DataType
type: object
properties:
  code:
    type: number
    required: false
  description:
    type: string
    required: false
  orderId:
    type: string
    required: false
  subscriptionId:
    type: string
    required: false
  modality:
    type: string
    required: false
    description: Echo of plan.modality when resource type is Plan (success responses).
