#%RAML 1.0 DataType
type: object
displayName: Tipos de datos correspondientes a un error sobre una API
description: Formato estándar para la definición de un error en una API
properties:
  codigo:
    type: string
    displayName: Código del error
    description: Código del error generado en la API asignado por ETB 
    required: true
  mensaje:
    type: string
    displayName: Mensaje del error
    description: Resumen o mensaje orientado al entendimiento netamente funcional
    required: true
  detalle:
    type: string
    displayName: Detalle técnico del error
    description: Detalle técnico del error que fue generado
    required: false