#%RAML 1.0 DataType 
type: object
properties:
  operation:
    type: string
    example: CREATE_APPOINTMENT
    required: false
  scheduleData:
    type: object
    properties:
      appointmentId:
        type: string
        example: APP123456
        required: false
      timeZone:
        type: string
        example: Colombia (COT)
        required: false
      timeZoneIANA:
        type: string
        example: America/Bogota
        required: false
      timeSlot:
        type: string
        example: AM_2
        required: false
      resourceName:
        type: string
        example: TECNICO SOLICITANTE
        required: false
      originAddress:
        type: string
        example: 'CALLE 161 #54-87'
        required: false
      destinationAddress:
        type: string
        example: 'CALLE 161 #54-87'
        required: false
      trasRequestdate:
        type: string
        example: 2025-12-08 12:08:00 PM
        required: false
      latitude:
        type: number
        example: 4.7382528
        required: false
      longitude:
        type: number
        example: -74.0622336
        required: false
      date:
        type: date-only
        example: '2026-03-30'
        required: false
      placaVehiculo:
        type: string
        example: DQP-091
        required: false
      tipoVehiculo:
        type: string
        example: CARRO
        required: false
      resourceId:
        type: string
        example: etb.conductor
        required: false
      resourceTimeZone:
        type: string
        example: Colombia (COT)
        required: false
      resourceTimeZoneIANA:
        type: string
        example: America/Bogota
        required: false
      zone:
        type: string
        example: NORTE
        required: false
      visitType:
        type: string
        example: Aprovisionamiento
        required: false
      technology:
        type: string
        example: FTTH
        required: false
  customerData:
    type: object
    properties:
      customerId:
        type: string
        example: '12345'
        required: false
      name:
        type: string
        example: ALEJANDRO PEREZ TORRES
        required: false
      phone:
        type: string
        example: '3001234567'
        required: false
      email:
        type: string
        example: correo@email.com
        required: false
      address:
        type: string
        example: 'CALLE 161 #54-87'
        required: false
      city:
        type: string
        example: BOGOTA
        required: false
      state:
        type: string
        example: BOGOTA
        required: false
  orderData:
    type: object
    properties:
      orderId:
        type: string
        example: ORD123456
        required: false
      orderType:
        type: string
        example: INSTALL
        required: false
      serviceType:
        type: string
        example: INSTALACION
        required: false
      comments:
        type: string
        example: Actividad creada desde XAPI MuleSoft
        required: false
      services:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              example: INTERNET
              required: false
            family:
              type: string
              example: HSI
              required: false
  pqrData:
    type: object
    properties:
      ticketId:
        type: string
        example: PQR123456
        required: false
      type:
        type: string
        example: ASEGURAMIENTO
        required: false