http:
  private:
    port: "8091"
  
autodiscovery: ""
 
mongo-db-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/mongo/v1"
  resources:
    dynamic-path: "/collection/{collectionName}/search"
    customer:
      base-path: "/customer"
      get:
        path: ""
      post:
        path: ""
      patch:
        path: ""

  security:
    client-id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client-secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

configurationTimeout:
  customer-papi-v2-listener: "62000"
  mongo-db-sapi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
  oracle-sapi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
  orquestador-sapi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
    
oracle-sapi:
    protocol: "HTTP"
    host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io"
    port: "8091"
    basePath: "/oracle/v1"
    resources:
      searchFields:
        path: "fieldService"
        searchField: "apptNumber"
        fields: "activityId,apptNumber,resourceId,date,status,recordType,positionInRoute,activityType,XA_Service_Type,cancel_reason,XA_NotDone_Reason,NOT_DONE_CODE,XA_Suspended_Reason,grupo_remedy,startTime,endTime,A_STATUS_CHANGE_TIME,A_Resolution_Level1,A_Resolution_Level2,A_Resolution_Level3,timeSlot"

orquestador-sapi:
    protocol: "HTTP"
    port: "8092"
    host: "mule-worker-internal-orquestador-sapi-services-prod.us-e2.cloudhub.io"
    basePath: "/orquestador/v1"
    resources:
      fallasMasivas: "massiveFailures"

customer360:
  collections:
    mdmCliente:
      name: MDM_CLIENTE
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    mdmCdServicio:
      name: MDM_CD_SERVICIO
      fields: ""
      filters:
        documentType: "Cliente.Tipo_Documento"
        documentNumber: "Cliente.Numero_Documento"
    mdmServicioActivo:
      name: MDM_SERVICIO_ACTIVO
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    logNotificacion:
      name: LOG_NOTIFICACIONES
      fields: ""
      filters:
        documentType: "Tipo_Documento_Cliente"
        documentNumber: "Numero_Documento"
    mdmInteraccion:
      name: MDM_INTERACCIONES
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    mdmPQR:
      name: PQR_PQR
      fields: ""
      filters:
        documentType: "tipo_documento"
        documentNumber: "numero_identificacion"
    mdmCuentaFacturacion:
      name: MDM_CUENTA_FACTURACION
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    cdRetencion:
      name: CD_RETENCION
      fields: ""
      filters:
        documentType: "Cliente_Retencion.Tipo_Documento"
        documentNumber: "Cliente_Retencion.Numero_Documento"
    promAltaPromocion:
      name: PROM_ALTA_PROMOCION
      fields: ""
      filters:
        documentType: "Tipo_Identificacion"
        documentNumber: "Numero_Identificacion"
    mdmOrden:
      name: MDM_ORDEN
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    mdmOrdenCompletadas:
      name: MDM_ORDEN_COMPLETADAS
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    mdmCdOrden:
      name: MDM_CD_ORDEN
      fields: ""
      filters:
        documentType: "Tipo_Documento"
        documentNumber: "Numero_Identificacion"
    mdmCdOrdenCompletadas:
      name: MDM_CD_ORDEN_COMPLETADA
      fields: ""
      filters:
        documentType: "Cliente_Tramite.Tipo_Documento"
        documentNumber: "Cliente_Tramite.Numero_Documento"
