#%RAML 1.0
title: smallworld-sapi-services
baseUri: smallworld-sapi-services-dev.us-e2.cloudhub.io/smallworld
description: The following API will handle the CRUD of smallworld.
mediaType:
  - application/json
version: "1"
protocols:
  - HTTP

traits:
  security_client_id: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  request_headers: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.2/tibcorequestheaders.raml

/v1:
  /georeference:
    is:
      - request_headers
      - security_client_id
    get:
      displayName: Obtain information about certain localization
      description: Returns information about a specific geolocalization using the information provided
      queryParameters:
        address:
          description: The address is already normalized
          example: "CL 163 BIS 2 60 ESTE"
          type: string
          required: true
        municipioCode:
          description: Should be a string that identifies itself
          example: "11001"
          type: string
          required: true
        departamentoCode:
          description: Should be a string that identifies itself
          example: "11"
          type: string
          required: true
      responses:
        200:
          body:
            application/json:
              example: !include examples/response/georeferenceResponse.raml
  /geoDireccion:
      patch:
        is:
          - request_headers
          - security_client_id
        displayName: Update GeoDirection
        description: Update GeoDirection
        body:
          application/json:
            type: !include datatypes/request/geoDireccionRequest.raml
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
                example: !include examples/response/geoDireccion200Response.raml
          500:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
                example: !include examples/response/geoDireccion500Response.raml
  /zonaAltoRiesgo:
    is:
      - request_headers
      - security_client_id
    get:
      displayName: get zonaAltoRiesgo
      description: get zonaAltoRiesgo
      queryParameters:
        direccion:
          description: direccion
          example: "612802304578782437"
          type: string
          required: false
        latitud:
          description: latitud
          example: "4.671102955"
          type: string
          required: false
        longitud:
          description: longitud
          example: "-74.06212576"
          type: string
          required: false
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/get-zonaAltoRiesgo.raml
              example: !include examples/response/get-zonaAltoRiesgo.json
  /coverage:
    is:
      - request_headers
      - security_client_id
    get:
      displayName: Obtain coverage with latitude and longitude
      description: Returns information about about coverage using the information provided
      queryParameters:
        latitude:
          description: Geo latitude
          example: 4.671486484
          type: number
          required: true
        longitude:
          description: Geo longitude
          example: -74.06268689
          type: number
          required: true
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/coverageResponse.raml
              example: !include examples/response/coverageResponse.json
  /geocodificar:
    is:
      - request_headers
      - security_client_id
    get:
      displayName: Geocodify address using Catastro Bogotá API
      description: Geocodifies an address using the Catastro Bogotá API to get coordinates and additional location information
      queryParameters:
        address:
          type: string
          required: true
          description: Dirección a geocodificar
          example: "Carrera 11 67A 40 SUR"
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/geocodificarResponse.raml
              example: !include examples/response/geocodificarResponse.json