#%RAML 1.0
title: portal-xapi-services
version: "1"
protocols:
  - HTTPS

baseUri: portal-xapi-services-dev.us-e2.cloudhub.io
description: 

securitySchemes:
  etb_oauth_2_0: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

traits:
  tibcoRequestHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.4/tibcorequestheaders.raml
  commonHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/api-spec-trait-common-headers/1.0.1/api-fragment-trait-common-headers.raml
  commonFaults: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/api-trait-common-faults/1.0.0/api-trait-common-faults.raml
  caching: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/api-trait-caching/1.0.1/api-trait-caching.raml
  clientCredentials: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  
types:
  patch-order-numOrden-adicion: !include datatypes/request/patch-order-numOrden-adicion.raml
  patch-order-numOrden-eliminacion: !include datatypes/request/patch-order-numOrden-eliminacion.raml
  patch-order-numOrden-sustitucion: !include datatypes/request/patch-order-numOrden-sustitucion.raml
  patchOrderStatus: !include datatypes/request/patchOrderRequest.raml

/operations:
  /v1:
    /orders:
      /{id}: 
        uriParameters:
          id:
            type: string
            example: MDM-MAY-00001  
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          displayName: Post orders  
          description: Operation to create an order
          body:    
            application/json:      
              type: !include /datatypes/request/post-order.raml
          responses:
            201:
              body:
                application/json:
                  type: !include datatypes/response/post-order.raml

        patch:
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          displayName: Update orders
          description: Operation to update an order
          body:
            application/json:
              type: patchOrderStatus
          responses:
            201:
              body:
                application/json:
                  type: !include datatypes/response/updateOrderResponse.raml  
    /cuestionario:
      post:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        displayName: Solicitud de cuestionario
        description: Solicitud de cuestionario
        body:
          application/json:
            type: !include datatypes/request/cuestionarioRequest.raml
        responses:
          201:
            body:
              application/json:
                type: !include datatypes/response/cuestionarioResponse.raml
                example: !include examples/response/cuestionarioResponse.json
    /coverages:
      /details:
        post:
          displayName: Get Coverage
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          body:
            application/json:
              type: !include datatypes/request/getCoverageInput.raml
          responses:
            200: 
              body: 
                application/json:
                  type: !include datatypes/response/getCoverageResponse200.raml
            400:
              body:
                application/json:
                  type: !include datatypes/response/getCoverageResponse400.raml
                  examples:
                    altResponse1: !include examples/response/getCoverageResponse400-1.json
                    altResponse2: !include examples/response/getCoverageResponse400-2.json
                    altResponse3: !include examples/response/getCoverageResponse400-3.json
                    altResponse4: !include examples/response/getCoverageResponse400-4.json
            500:        
              body:
                application/json:
                  type: !include datatypes/response/getCoverageResponse500.raml 
    /M6services:
      /vias:
        post:
          displayName: Consultar vías
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          body:
            application/xml:
              example: !include examples/request/consultarVias.xml
          responses:
            200:
              body:
                application/xml:
                  example: !include examples/response/consultarVias.xml
      /consultarNumerosDisponibles:
        /FTTH:
          post:
            displayName: Consultar Numeros Disponibles FTTH
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            body:
              application/xml:
                type: !include datatypes/request/consultarNumerosDisponiblesFTTH.raml
                #example: !include examples/request/consultaNumerosDisponiblesFTTH.xml
            responses:
              200: 
                body: 
                  application/xml:
                    type: !include datatypes/response/consultarNumerosDisponiblesFTTH.raml
                    example: !include examples/response/consultaNumerosDisponiblesFTTH.xml
        /FTTC:
          post:
            displayName: Consultar Numeros Disponibles FTTC
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            body:
              application/xml:
                example: !include examples/request/consultarNumerosDisponiblesFTTC.raml
            responses:
              200: 
                body: 
                  application/xml:
                    example: !include examples/response/consultaNumerosDisponiblesFTTC.raml 
        /disponibilidad:
          post:
            displayName: Consultar Disponibilidad Inventario Web
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            body:
              application/xml:
                type: !include datatypes/request/consultarNumerosDisponiblesFTTH.raml
                #example: !include examples/request/consultaNumerosDisponiblesFTTH.xml
            responses:
              200: 
                body: 
                  application/xml:
                    type: !include datatypes/response/consultarNumerosDisponiblesFTTH.raml
                    example: !include examples/response/consultaNumerosDisponiblesFTTH.xml
        /cobreWeb:
          post:
            displayName: Consultar Numeros Disponibles Cobre Web
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            body:
              application/xml:
                type: !include datatypes/request/consultarNumerosDisponiblesFTTH.raml
                #example: !include examples/request/consultaNumerosDisponiblesFTTH.xml
            responses:
              200: 
                body: 
                  application/xml:
                    type: !include datatypes/response/consultarNumerosDisponiblesFTTH.raml
                    example: !include examples/response/consultaNumerosDisponiblesFTTH.xml
    
    /masivas:
      /consultaPqrs:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          displayName: Consulta fallas masivas
          description: Consulta fallas masivas y cantidad afectados
          body:
            application/json:
              type: !include datatypes/request/consultaFallasMasivas.raml
          responses:
            200:
              body:
                  application/json:            
                    type: !include datatypes/response/consultaFallaMasiva.raml
                    example: !include examples/response/consultaFallasMasivas.json
        /elementos:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Consulta fallas masivas
            description: Consulta fallas masivas y cantidad afectados
            body:
              application/json:
                type: !include datatypes/request/consultaFallasMasivas.raml
            responses:
              200:
                body:
                    application/json:            
                      type: !include datatypes/response/consultaElementoFallaMasiva.raml
                      example: !include examples/response/consultaElementoFallasMasivas.json
    /agreements:
      /create:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          displayName: Generacion de Acuerdo
          description: Generacion de Acuerdo
          body:
            application/json:
              type: !include /datatypes/request/post-createAgreements.raml
          responses:
            200:
              body:
                  application/json:            
                    type: !include /datatypes/response/post-createAgreements.raml
      /retrieve:
        post:
          displayName: Obtencion de Respuesta de Acuerdo (WebHook)
          description: Obtencion de Respuesta de Acuerdo (WebHook)
          body:
            text/xml:
              type: !include /datatypes/request/post-retrieveAgreements.raml
          responses:
            200:
              body:
                application/json:  
                  type: !include /datatypes/response/post-retrieveAgreements.raml
                      
/infrastructure:
  /v1:
    /georeference:
      get:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        displayName: Obtain information of the user about the current location
        description: This method returns the information about certain user and his geolocalization and later be used by other services.
        queryParameters:
          address:
            description: It is needed a string contemplating the address to check the service
            example: "CL 163 BIS 2 60 ESTE"
            minLength: 1
            type: string
            required: true
          municipioCode:
            description: It is needed a string contemplating the municipality code to check the service
            example: "11001"
            minLength: 1
            type: string
            required: true
          departamentoCode:
            description: It is needed a string contemplating the department code to check the service
            example: "11"
            minLength: 1
            type: string
            required: true
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/georeferenceResponse.raml
    /feasibility:
      get:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        displayName: Interface for operations of pre-feasibility
        description: Interface for operation of pre-feasibility consultation of fiber services (FTTH) in GIS.
        queryParameters:
          addressCode:
            description: Required code to identify the address
            example: "612802304578431600"
            minLength: 1
            type: string
            required: true
          mayorista:
            description: Required name to identify the mayorista
            example: "ETB"
            type: string
            required: false
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/feasibilityResponse.raml
    /normalizeAddressOp:
      is: [tibcoRequestHeaders]
      post:
        securedBy: [etb_oauth_2_0]
        displayName: Interface to normalize address
        description: Interface to normalize and categorize address according to its availability
        body:
          application/json:
            type: !include datatypes/request/unNormalizedAddress.raml
        responses:
          201:
            body:
              application/json:
                type: !include datatypes/response/normalizedAddress.raml
          500:
            body:
              application/json:
                type: !include datatypes/response/normalizeErrorMessageResponse.raml
                example: !include examples/response/normalizeErrorMessageResponse.json
    /coverageGIS:
      post:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        displayName: Interface to get coverageGIS Address
        description: Interface to get coverageGIS Address and validate received requests with OAuth
        body:
          application/json:
            type: !include datatypes/request/coverageGIS.raml
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/coverageGIS.raml
    /geoDireccion:
      patch:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        displayName: Update GeoDirection
        description: Update GeoDirection
        body:
          application/json:
            type: !include datatypes/request/geoDireccionRequest.raml           
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
                example: !include examples/response/geoDireccion200Response.raml
          400:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
          401:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
          404:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
          500:
            body:
              application/json:
                type: !include datatypes/response/geoDireccionResponse.raml
                example: !include examples/response/geoDireccion500Response.raml    
    /geoAddress:
      post:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        displayName: manageGeoaddress
        description: Manage a geographic address in the system
        body:
          application/json:
            type: !include datatypes/request/geoAddressRequest.raml
            example: !include examples/request/geoDireccionRequest.json
        responses:
          201:
            body:
              application/json:
                type: !include datatypes/response/geoAddressResponse.raml
                example: !include examples/response/geoDireccionResponse.json
          400:
            body:
              application/json:
                type: !include datatypes/response/geoAddressResponse.raml
          401:
            body:
              application/json:
                type: !include datatypes/response/geoAddressResponse.raml
          404:
            body:
              application/json:
                type: !include datatypes/response/geoAddressResponse.raml
          500:
            body:
              application/json:
                type: !include datatypes/response/geoAddressResponse.raml
    /services:
      /feasibility:
        /bookingFeasibility:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Booking feasibility
            description: Interface to consult booking feasibility
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/bookingFeasibility.json
            responses:
              200:
                body:
                  application/json:
                    example: any
        /createBooking:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Create booking
            description: Interface to create services booking
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/createBooking.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpCreateBooking.json
        /consultBooking:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Consult booking
            description: Interface to consult services booking
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/consultBooking.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpConsultBooking.json
        /cancelBooking:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Cancel booking
            description: Interface to cancel services booking
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/cancelBooking.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpCancelBooking.json
      /activation:
        /ont:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: ONT service activation
            description: Interface to activate ont services
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/activateOnt.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpActivateOnt.json
        /service:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Service activation
            description: Interface to activate services
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/activateService.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpActivateService.json
      /deactivation:
        /ont:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: ONT service deactivation
            description: Interface to deactivate ont services
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/deactivateOnt.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpDeactivateOnt.json
        /service:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Service deactivation
            description: Interface to deactivate services
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/deactivateService.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpDeactivateService.json
      /support:
        /resetONT:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: ONT reset
            description: Interface to reset ont
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/resetONT.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpResetONT.json
        /consultLevels:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Consult levels
            description: Interface to measure the signal levels of the ONTs
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/consultLevels.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpConsultLevels.json
        /consultSpeed:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Consult speed
            description: Interface to check the information of the speed configured for the client
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/consultSpeed.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpConsultSpeed.json
        /consultState:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Consult state
            description: Interface to check the status of the ONT
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/consultState.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpConsultState.json
        /consultNeighbors:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Consult neighbors
            description: Interface to view neighboring clients
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/consultNeighbors.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpConsultNeighbors.json
      /modification:
        /serviceSuspension:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Service suspension
            description: Interface to suspend a service
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/serviceSuspension.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpServiceSuspension.json
        /serviceReactivation:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Service reactivation
            description: Interface to reactivate a service
            queryParameters:
              provider:
                required: true
                enum: [ATP, ATP_CHANGEONT]
            body:
              application/json:
                type: any
                example: !include examples/request/serviceReactivation.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpServiceReactivation.json
      /speedChange:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          displayName:  Speed change
          description: Interface to do speed change
          queryParameters:
            provider:
              required: true
              enum: [ATP]
          body:
            application/json:
              type: any
              example: !include examples/request/speedChange.json
          responses:
            200:
              body:
                application/json:
                  example: !include examples/response/atpSpeedChange.json
        /feasibility:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Speed change booking feasibility
            description: Interface to get change speed feasibility
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/speedChangeFeasibility.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpSpeedChangeFeasibility.json
        /createBooking:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Speed change create booking
            description: Interface to create change speed booking
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/speedChangeCreateBooking.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpSpeedChangeCreateBooking.json
        /cancelBooking:
          post:
            securedBy: [etb_oauth_2_0]
            is: [tibcoRequestHeaders]
            displayName: Speed change cancel booking
            description: Interface to cancel change speed booking
            queryParameters:
              provider:
                required: true
                enum: [ATP]
            body:
              application/json:
                type: any
                example: !include examples/request/speedChangeCancelBooking.json
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/atpSpeedChangeCancelBooking.json
/sendNotification:
  /{campania}:
    uriParameters:
      campania:
        type: string
        example: "deg_notificacion1"
    post:
      securedBy: [etb_oauth_2_0]
      is: [tibcoRequestHeaders]
      displayName: Gestionar los envíos de las notificaciones 
      description: Gestionar los envíos de las notificaciones
      body:
        application/json:
          type: !include /datatypes/request/sendNotification.raml
          example: !include /examples/request/sendNotification.json
      responses:
        200:
          description: Notificación enviada exitosamente
          body:
            application/json:
              properties:
                codigo: 
                  type: string
                  example: "200"
                descripcion: 
                  type: string
                  example: "Notificación enviada exitosamente"
        404:
          description: No se encontró la campaña
          body:
            application/json:
              properties:
                codigo: 
                  type: string
                  example: "404"
                descripcion: 
                  type: string
                  example: "La campaña solicitada no existe"
        500:
          description: Se ha generado una exceptión técnica y no fue posible continuar
          body:
            application/json:
              properties:
                codigo: 
                  type: string
                  example: "500"
                descripcion: 
                  type: string
                  example: "Se ha generado una exceptión técnica y no fue posible continuar"
/v1:
  /fractalia:
    /ordenes:
      /{numOrden}:
        uriParameters:
          numOrden:
            type: string
        patch:
          securedBy: [etb_oauth_2_0]
          is: [tibcoRequestHeaders]
          displayName: Update order en Fractalia
          description: Update order en Fractalia
          queryParameters:
            accion:
              enum: ["ADICION","SUSTITUCION", "ELIMINACION", "CREARUSUARIO"]
          body:
            application/json:
              type: patch-order-numOrden-adicion | patch-order-numOrden-sustitucion | patch-order-numOrden-eliminacion
          responses:
            201:
              body:
                application/json:
                  example: !include examples/response/patch-order-numOrden.json
  /ordenes:
    /{id}:
      uriParameters:
        id:
          type: string
          example: "MDM-FIBRA-0001"
      get:
        securedBy: [etb_oauth_2_0]
        is: [commonHeaders, commonFaults, caching]
        displayName: Get orders
        description: Operation to consult an order
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/get-ordenesResponse.raml
              
                                
  /visitas-tecnicas:
    /{id}:
      uriParameters:
        id:
          type: string
          example: "MDM-FIBRA-0001"
      get:
        securedBy: [etb_oauth_2_0]
        is: [commonHeaders, commonFaults, caching]
        displayName: Get technical visits
        description: Operation to consult a technical visit
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/get-visitasTecnicasResponse.raml
                
  /manualEquipos:
    get:
      securedBy: [etb_oauth_2_0]
      is: [tibcoRequestHeaders, commonFaults]
      displayName: Obtener los registros activos.
      description: Obtener los registros activos.
      responses:
        200:
          body:
            application/json:
              type: !include /datatypes/response/get-manualEquipos.raml

  /omnicanalidad:
    /interaction:
      post:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders, commonFaults]
        displayName: Post interacción/transacción.
        description: Almacenar interacción/transacción.  
        body:    
          application/json:      
            type: !include /datatypes/request/post-omnicanalidadInteraction.raml
        responses:
          200:
            body:
              application/json:
                properties:
                  codigo:
                    type: string
                    example: "OK"
                  descripcion:
                    type: string
                    example: "Registro insertado"

/orders:
  /v1:
    /OrderStatus:
      patch:
        securedBy: [etb_oauth_2_0]
        is: [tibcoRequestHeaders]
        body:
          application/json:
            example: !include examples/request/updateOrderStatus.json
        responses:
          201:
            description: update order status returned by the method
            body:
              application/json:
                example:
                  !include /examples/response/updateOrderStatusResponse.json
          500:
              description: Response for the status 500 of the update
              body:
                application/json:
                  type: !include examples/response/updateOrderStatusError.json
                  
/v1/esim/solicitarQResim:
  post:
    securedBy: [ etb_oauth_2_0 ]
    description: Procesar la solicitud de obtener y enviar una imagen png asociado a una eSIM.
    body:
      application/json:
        type: !include /datatypes/request/solicitarQResimRequest.raml
        example: !include /examples/request/solicitarQResimRequest.json
    responses:
      200:
        description: Documento PDF entregado exitosamente
        body:
          application/pdf:
            example: !binary |
              JVBERi0xLjQKJcTl8uXrp/Og0MTGCjQgMCBvYmogICUgZW50cmllcwo8PC9UeXBlIC9DYXRh
              bG9nL1BhZ2VzIDIgMCBSCj4+CmVuZG9iago1IDAgb2JqCjw8L1R5cGUgL1BhZ2UvUGFyZW50
              IDIgMCBSCi9NZWRpYUJveCBbMCAwIDU5NSA4NDJdCi9Db250ZW50cyA2IDAgUgo+PgplbmRv
              YmoK...
      400:
        description: Error en la solicitud
        body:
          application/json:
            type: object
            properties:
              status: integer
              code: string
              message:
                type: object
                properties:
                  message: string
              messageServer: string
              cause:
                type: array
                items:
                  type: object
                  properties:
                    origin: string
                    message: string
            example: !include /examples/response/solicitarQResimResponse400.json

