# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================

# --- API Client Credentials ---
api:
  clientId: "![FR9GC9Xtr6Buru76YxCDeLt4CEBWK35BWO6EzLzNYAeS+oUPImYw7A==]"
  clientSecret: "![mtn6+8cgeku1SUqSEntT25d7XpqabZLuwgcyEyzaQDIyCLyh0vNdWA==]"