# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================

# --- API Client Credentials ---
api:
  clientId: "![7b167b9c389a4c0099bbf7ea34df88fc]"
  clientSecret: "![8917F36fBC2c4105b72c7bC3a165740F]"