#%RAML 1.0 DataType
properties:
  Fecha_Creacion:
    type: string
    example: "2021-12-14T16:06:50"
  Fecha_Modificacion:
    type: string
    example: "2021-12-14T16:06:50"
  Usuario_Modificacion:
    type: string
    example: "wilmpulj"
  Usuario_Creacion:
    type: string
    example: "wilmpulj"
  Actualizacion_Extractor:
    type: string
    example: "1"
  Numero_Orden:
    type: string
    example: "MDM_MAY_00001"
  Canal:
    type: string
    example: "Canal_Fibra"
  Fase:
    type: string
    example: "INTERAF"
  Estado_Orden_Comercial:
    type: object
    properties:
      Codigo:
        type: string
        example: "I20"
      Descripcion:
        type: string
        example: "Validación Cobertura"
      Fecha:
        type: string
        example: "2021-12-14T16:15:28"
      Reintentos:
        type: number
        example: 0
      CodigoExcepcion:
        type: number
        example: 0
  Tramite:
    type: object
    properties:
      Tipo_Tramite:
        type: string
        example: "VTA"
      Subtipo_Tramite:
        type: nil
        example: null
      Fecha_Tramite:
        type: string
        example: "2021-12-14T16:06:50"
      Fecha_Reconexion:
        type: nil
        example: null
      Fecha_Suspension:
        type: nil
        example: null
      Fecha_Ejecucion:
        type: string
        example: "2021-12-14T16:06:50"
      Conservar_Numero_Conexion:
        type: boolean
        example: false
      Clausula_Permanencia:
        type: boolean
        example: false
      Valor_Clausula_Permanencia:
        type: number
        example: 0
      Causal_Cancelacion:
        type: nil
        example: null
      Subcausal_Cancelacion:
        type: nil
        example: null
      Descripcion_Cancelacion:
        type: nil
        example: null
      MotivosOrden:
        type: nil
        example: null
  Tipo_Servicio:
    type: nil
    example: null
  CUN:
    type: nil
    example: null
  Cliente_Anterior:
    type: nil
    example: null
  Cliente_Tramite:
    type: object
    properties:
      Fecha_Creacion:
        type: string
        example: "2021-12-14T16:06:50"
      Fecha_Modificacion:
        type: string
        example: "2021-12-14T16:06:50"
      Usuario_Modificacion:
        type: string
        example: "wilmpulj"
      Usuario_Creacion:
        type: nil
        example: null
      Actualizacion_Extractor:
        type: nil
        example: null
      Id_Cuenta_Cliente:
        type: number
        example: 0
      Tipo_Documento:
        type: string
        example: "NIT"
      Numero_Documento:
        type: string
        example: "830122566"
      Nombres:
        type: string
        example: "COLOMBIA TELECOMUNICACIONES"
      Nombre_Corto_Empresa:
        type: string
        example: "COLOMBIA TELECOMUNICACIONES S A E S P"
      Primer_Apellido:
        type: string
        example: "S"
      Segundo_Apellido:
        type: string
        example: "A E P"
      Fecha_Expedicion:
        type: nil
        example: null
      Fecha_Validacion_Identidad:
        type: nil
        example: null
      Autoriza_Manejo_Datos_Personales:
        type: nil
        example: null
      Autoriza_Consulta_Centrales:
        type: nil
        example: null
      UEN:
        type: string
        example: "Empresas y Ciudades Inteligentes"
      Segmento_UEN:
        type: string
        example: "Mayoristas"
      Segmento:
        type: string
        example: "Grande"
      Scoring_Fija:
        type: nil
        example: null
      Telefono_Fijo:
        type: string
        example: "6015935256"
      Extension:
        type: nil
        example: null
      Telefono_Movil:
        type: string
        example: "17050000"
      Telefono_Movil2:
        type: string
        example: ""
      Email:
        type: string
        example: "camilo.garcia@telefonica.com"
      Contactos:
        type: array
        required: false
        items:
          type: object
          properties:
            Tipo_Documento:
              type: string
              example: "CC"
            Numero_Documento:
              type: string
              example: "53140545"
            Nombres:
              type: string
              example: "XYZ"
            Primer_Apellido:
              type: string
              example: "XYZ"
            Segundo_Apellido:
              type: string
              example: "xyz"
            Telefono_Fijo:
              type: string
              example: "6012885406"
            Telefono_Fijo2:
              type: nil
              example: null
            Telefono_Movil:
              type: string
              example: "6012885406"
            Telefono_Movil2:
              type: nil
              example: null
            Email:
              type: string
              example: "no@hotmail.com"
            Departamento:
              type: nil
              example: null
            Ciudad:
              type: nil
              example: null
            Codigo_DANE:
              type: nil
              example: null
            Direccion:
              type: nil
              example: null
            Localidad:
              type: nil
              example: null
            Seleccionado:
              type: boolean
              example: false
            Autorizado:
              type: boolean
              example: false
            Estado:
              type: boolean
              example: false
            Adjuntos_Contacto:
              type: nil
              example: null
            FechaExpedicion:
              type: nil
              example: null
            FechaCumpleanos:
              type: nil
              example: null
            FechaValidaTelefono:
              type: nil
              example: null
            FechaValidaEmail:
              type: nil
              example: null
            actualizacion_extractor:
              type: nil
              example: null
            ATDP:
              type: object
              required: false
              properties:
                HABEAS_DATA:
                  type: string
                  example: "False"
                FECHA:
                  type: string
                  example: "2021-06-18T14:10:29"
                USUARIO:
                  type: string
                  example: "florespc"
                CANAL:
                  type: string
                  example: "PQR"
                PQR_ASOCIADA:
                  type: string
                  example: "607b5bee8c9947394c4b337c"
      Direcciones:
        type: array
        items:
          type: object
          properties:
            Id_Direccion:
              type: number
              example: 1
            Direccion_Normalizada:
              type: string
              example: "CL 45 39 40"
            Tipo_Direccion:
              type: string
              example: "INSTALACION"
            Codigo_Direccion:
              type: string
              example: ""
            Codigo_Departamento:
              type: string
              example: "50"
            Codigo_Municipio:
              type: string
              example: "50001"
            Codigo_Pais:
              type: string
              example: "593b0ac99a8e4177d410df4d"
            Nombre_Direccion:
              type: string
              example: ""
            Estado:
              type: string
              example: "ACTIVO"
            Cobertura:
              type: object
              required: false
              properties:
                Tipo_Cobertura:
                  type: string | nil
                  example: "MOLECULA"
                  required: false
                Codigo_Lote:
                  type: string | nil
                  example: "27"
                  required: false
                Localidad:
                  type: string | nil
                  example: "01"
                  required: false
                Estrato:
                  type: string | nil | integer
                  example: "1"
                  required: false
                Latitud:
                  type: number | string
                  example: "4.15985065460205"
                  required: false
                Longitud:
                  type: number | string
                  example: "4.159985065460205"
                  required: false
                Direccion_GIS:
                  type: string | nil
                  example: "612802304578775507"
                  required: false
                NombreCobertura:
                  type: string | nil
                  example: "MOLECULA"
                  required: false
                Olt:
                  type: string | nil
                  example: "TO01"
                  required: false
                Propietario:
                  type: string | nil
                  example: "ETB"
                  required: false
                Proposito:
                  type: string | nil
                  example: "01"
                  required: false
                Tecnologia:
                  type: string
                  example: "FIBRA"
                  required: false
                Zona:
                  type: string | nil
                  example: "VILLAVO03"
                  required: false
                TipoDistancia:
                  type: string | nil
                  example: "AE"
                  required: false
                TipoDistancia2:
                  type: string | nil
                  example: ""
                  required: false
                Distrito:
                  type: string | nil
                  example: ""
                  required: false
                Molecula:
                  type: string | nil
                  example: "MOLECULA"
                  required: false
                Viable:
                  type: boolean | nil
                  example: false
                  required: false
            Seleccionada:
              type: boolean
              example: true
            Departamento:
              type: string
              example: "META"
            Municipio:
              type: string
              example: "VILLAVICENCIO"
      Cuentas_Facturacion:
        type: nil
        example: null
      Cuentas_Servicio:
        type: nil
        example: null
      Adjuntos_Cliente:
        type: array
      Sistema_Origen:
        type: nil
        example: null
      Estado:
        type: string
        example: "ACTIVO"
      Datos_Empresa:
        type: object
        required: false
        properties:
          Informacion_Basica:
            type: object
            properties:
              Razon_Social:
                type: string 
                example: "COLOMBIA TELECOMUNICACIONES S A E S P"
              Sector:
                type: number
                example: 0
              Actividad_Economica:
                type: string 
                example: "61"
              Id_Solicitud:
                type: nil 
                example: null
          Representante_Legal:
            type: object
            properties:
              Tipo_Documento:
                type: string
                example: "CC"
              Numero_Documento:
                type: string
                example: "79383447"
              Primer_Nombre:
                type: string
                example: "XYZ"
              Segundo_Nombre:
                type: string
                example: "XYZ"
              Primer_Apellido:
                type: string
                example: "XYZ"
              Segundo_Apellido:
                type: string
                example: "XYZ"
              Fecha_Expedicion:
                type: string
                example: "1984-07-05T05:00:00Z"
              Fecha_Nacimiento:
                type: string
                example: "1984-07-05T05:00:00Z"
          Ubicacion:
            type: object
            properties:
              Fecha_Constitucion:
                type: string
                example: "1984-07-05T05:00:00Z"
              Tipo_Negocio:
                type: number
                example: 0
              Zona:
                type: number
                example: 0
              Estrato:
                type: number
                example: 0
              Codigo_Departamento:
                type: string
                example: "11"
              Departamento:
                type: string
                example: "2003-06-19"
              Codigo_Municipio:
                type: string
                example: "11001"
              Municipio:
                type: string
                example: "BOGOTA"
              Direccion:
                type: string
                example: "TRANSVERSAL 60 114 A 55"
              Telefono:
                type: string
                example: "6015935256"
              Extension:
                type: nil
                example: null
              Celular:
                type: string
                example: "3117050000"
              Email:
                type: string
                example: "camilo.garcia@telefonica.com"
          Balance_General:
            type: object
            properties:
              Total_Activo_Corriente:
                type: string
                example: "1"
              Inventarios:
                type: string
                example: "1"
              Total_Activos:
                type: string
                example: "1"
              Total_Pasivo_Corriente:
                type: string
                example: "1"
              Total_Pasivo:
                type: string
                example: "1"
              Total_Patrimonio:
                type: string
                example: "1"
          Estado_Resultados:
            type: object
            properties:
              Ingresos_Operacionales_Ano_Corriente:
                type: string
                example: "1"
              Ingresos_No_Operacionales_Ano_Corriente:
                type: string
                example: "1"
              Ingresos_Operacionales_Ano_Anterior:
                type: string
                example: "1"
              Ingresos_No_Operacionales_Ano_Anterior:
                type: string
                example: "1"
              Costo_Venta:
                type: string
                example: "1"
              Gastos_Operacionales:
                type: string
                example: "1"
              Utilidades_Operacionales:
                type: string
                example: "1"
              Otros_Egresos:
                type: string
                example: "1"
              Utilidad_Neta:
                type: string
                example: "1"
              Utilidad_Antes_De_Impuestos:
                type: string
                example: "1"
              Impuestos_Renta_Y_Complementarios:
                type: string
                example: "1"
              Cuentas_Por_Cobrar:
                type: string
                example: "1"
              Obligaciones_Financieras:
                type: string
                example: "1"
      CarruselMotivo:
        type: nil
        example: null
      CarruselSubMotivo:
        type: nil
        example: null
      ATDP:
        type: object
        required: false
        properties:
          HABEAS_DATA:
            type: string
            example: "True"
          FECHA:
            type: string
            example: "2021-06-18T14:10:29.698Z"
          USUARIO:
            type: string
            example: "NPLAY"
          CANAL:
            type: string
            example: "NPLAY"
          PQR_ASOCIADA:
            type: string | nil
            example: null
      Direccion:
        type: string
        example: "TRANSVERSAL 60 114 A 55"
      Cobertura:
        type: nil
        example: null
      Departamento:
        type: nil
        example: null
      Ciudad:
        type: nil
        example: null
  Servicio_Anterior:
    type: nil | object
    example: null
  Servicio_Tramite:
    type: object | nil
    example: {}
    required: false
  Orden_Servicio:
    type: nil
    example: null
  Agendamiento:
    type: object
    required: false
    properties:
      Franja_Agenda:
        type: string
        example: ""
      Codigo_Instalador:
        type: string
        example: ""
      Enriquecida:
        type: boolean
        example: false
      Agenda:
        type: boolean
        example: false
      ListaCuotas:
        type: array
  Orden_Activacion:
    type: nil
    example: null
    required: false
  Cuenta_Facturacion_Anterior:
    type: nil
    example: null
  Cuenta_Facturacion_Tramite:
    type: nil
    example: null
  Orden_Requiere_Disponibilidad:
    type: boolean
    example: false
  Orden_Requiere_Agendamiento:
    type: boolean
    example: false
  Precio_Total_Orden:
    type: nil
    example: null
  Adjuntos_Cliente:
    type: nil
    example: null
  Adjuntos_Servicio:
    type: nil
    example: null
  Caracteristica_Orden:
    type: array
    items:
      type: object
      properties:
        Caracteristica:
          type: string
          example: "MantenerOferta"
        Valor:
          type: string
          example: "false"
  Otros:
    type: nil
    example: null
  Presencial:
    type: boolean
    example: false
  OfertaSugerida:
    type: array
  Reserva:
    type: nil
    example: null
example:
  !include ../examples/order.json