http:
  host: "0.0.0.0"
  private:
    port: "8091"
  path: "/asap/*"
  
autodiscovery: "18363363"

jms:
  username: "tibco"
  password: "tibco123"
  connectionFactory: "weblogic.jms.ConnectionFactory"
  publisher:
    server: "PROD.JMSServer"
    module: "PROD.asap_jms_module"
    queue: "PROD.MessageQueue"
  consumer:
    server: "PROD.JMSServer"
    module: "asap_osm_jms_module"
    queue: "activationResponseQueueMulesoft"
  url: "t3://asap.etb.com.co:7003"
  reconnection: "30000"
 
os-asap:
  maxEntries: ""
  entryTTLdays: ""
  expirationIntervalMinutes: ""
  until-successful-strategy:
    time-between: "10000"
    retries: "10"
  
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
fractalia:
  protocol: "HTTPS"
  host: "apiprovision-app.onlineassist.me"
  basePath: "/api"
  path:
    user: "/user"
    sku: "/User/skus"
  key: "04d87ee0-b56e-4a1a-83d9-ed3348266805"
  
audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs/"
  path: "/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
configurationTimeout:
  audits-mongo: "2400"
  fractalia: "2400"