#%RAML 1.0 Library
usage: Library that contains most common resource and traits, use them for consistency

types:
  portabilityRequest:
    type: object
    properties:
      MensajeABD:
        type: object
        properties:
          CabeceraMensaje:
            type: object
            required: true
            properties:
              IdentificadorProceso:
                type: string
                required: true
                maxLength: 20
                example: "00007202406120100449"
              IdentificadorMensaje:
                type: string
                required: true
                maxLength: 20
                example: "00007202406120001788"
              FechaCreacionMsg:
                type: string
                required: true
                description: "yyyyMMddHHmmss"
                maxLength: 14
                example: "20240612160524"
              TipoMsg:
                type: string
                required: true
                maxLength: 4
                enum: ["0001", "0002", "0003", "0004", "1001", "1002", "1003", "1004", "1005", "1006", "1007", "9999", "2001", "2002", "3001", "3002", "9998", "4001", "4002", "4003", "4004", "4999", "5001", "5002", "5003", "5999"]
                example: "1006"
              Emisor:
                type: string
                required: true
                maxLength: 5
                example: "00007"
              Observaciones:
                type: string | nil
                required: false
                example: ""
          CuerpoMensaje:
            type: TipoRespuestaSolicitudNIP | TipoRespuestaSolicitudReenvioNIP | TipoReenvioNIP | TipoProgramacionPortacion | TipoSolicitudNIP | TipoSolicitudPortacion | TipoReplicaSolicitudPortacion | TipoRespuestaSolicitudPortacionDonante | TipoReplicaRespuestaSolicitudPortacionDonante | TipoSolicitudDeProgramacionPortacion | TipoConfirmacionProgramacionPortacion | TipoRechazoPortacion | TipoErrorDetectadoABD | TipoSolicitudCancelacion | TipoRespuestaSolicitudCancelacion

  #0002
  TipoRespuestaSolicitudNIP:
    type: object
    properties:
      RespuestaSolicitudNIP:
        type: object
        properties:
          RespuestaABD:
            type: TipoRespuestaABD
            required: true
          NumeracionRechazada:
            type: TipoNumeracionRechazada
            required: false
  
  #0004
  TipoRespuestaSolicitudReenvioNIP:
    type: object
    properties:
      RespuestaSolicitudReenvioNIP:
        type: object
        properties:
          RespuestaABD:
            type: TipoRespuestaABD
            required: true
          CodigosRechazo:
            type: object
            required: false
            properties:
              CodigoRechazo:
                type: string[]
                required: false

  TipoRespuestaABD:
    type: string
    description: "1: Aceptada solicitud; 0: Rechazada solicitud"
    enum: ["0", "1"]

  TipoNumeracionRechazada:
    type: array
    items:
      type: object
      properties:
        Numero: 
          type: string
          required: true
          maxLength: 15
        CodigosRechazo:
          type: object
          properties:
            CodigoRechazo:
              type: string[]
              required: true
          
  TipoListaNumeracionRechazadaDonante:
    type: object
    properties:
      NumeracionRechazada:
        type: array
        items:
          type: object
          properties:
            Numero:
              type: string
              required: true
            CodigosRechazo:
              type: object
              properties:
                CodigoRechazo:
                  type: string[]
                  required: true
            DocumentoFC:
              type: string | nil
              required: false
            DocumentoDC:
              type: string | nil
              required: false
            DocumentoFR:
              type: string | nil
              required: false
            DocumentoUO:
              type: string | nil
              required: false
            DocumentoLD:
              type: string | nil
              required: false
            DocumentoLS:
              type: string | nil
              required: false
            DocumentoNA:
              type: string | nil
              required: false
            DocumentoNI:
              type: string | nil
              required: false
            DocumentoLA:
              type: string | nil
              required: false

  #0003
  TipoReenvioNIP:
    type: object
    properties:
      SolicitudReenvioNIP: 
        type: object
        required: true
        properties:
          Numero:
            type: string
            required: true
            example: "3104XXX244"                  

  #1006
  TipoProgramacionPortacion:
    type: object
    properties:
      ProgramacionPortacion: 
        type: object
        required: true
        properties:
          FechaVentanaCambio:
            type: string
            required: true
            example: "20240613000000"
            
  #0001
  TipoSolicitudNIP:
    type: object
    properties:
      SolicitudNIP: 
        type: object
        required: true
        properties:
          Donante:
            type: string
            required: true
            maxLength: 5
          NumeroRepresentante:
            type: string | nil
            required: false
          ListaNumeracion:
            type: object
            required: true
            properties:
              Numero:
                type: string[]
                required: true
                
  #1001
  TipoSolicitudPortacion:
    type: object
    properties:
      SolicitudPortacion:
        type: object
        properties:
          NombreRazonSocialAbonado:
            type: string
            required: true
          TipoDocumentoIdentificacion:
            type: string
            required: true
            enum: ["1", "2", "3", "4", "5", "6"]
          DireccionAbonado:
            type: string
            required: true
          IdentificacionAbonado:
            type: string
            required: true
          FechaExpedicionIdentificacion:
            type: string | nil
            required: false
          TipoDocumentoIdentificacionRepresentanteLegal:
            type: string | nil
            required: false
          IdentificacionRepresentanteLegal:
            type: string | nil
            required: false
          FechaExpedicionIdentificacionRepresentanteLegal:
            type: string | nil
            required: false
          Donante:
            type: string
            required: true
          TipoUsuario:
            type: string
            required: true
            enum: ["1", "2"]
          TipoServicio:
            type: string
            required: true
            enum: ["1", "2"]
          NIP:
            type: string
            required: false
          FlagVentanaAmpliada:
            type: string
            required: true
            enum: ["0", "1"]
          SolicitudTerceros:
            type: string
            required: true
            enum: ["0", "1"]
          ListaNumeracion:
            type: object
            required: true
            properties:
              Numero:
                type: string[]
                required: true
          NRN:
            type: string
            required: true
          DocumentoID:
            type: string | nil
            required: false
          DocumentoAT:
            type: string | nil
            required: false
          DocumentoCC:
            type: string | nil
            required: false

  #1002
  TipoReplicaSolicitudPortacion:
    type: object
    properties:
      ReplicaSolicitudPortacion:
        type: object
        properties:
          NombreRazonSocialAbonado:
            type: string
            required: true
          TipoDocumentoIdentificacion:
            type: string
            required: true
            enum: ["1", "2", "3", "4", "5", "6"]
          DireccionAbonado:
            type: string
            required: true
          IdentificacionAbonado:
            type: string
            required: true
          FechaExpedicionIdentificacion:
            type: string | nil
            required: false
          TipoDocumentoIdentificacionRepresentanteLegal:
            type: string | nil
            required: false
          IdentificacionRepresentanteLegal:
            type: string | nil
            required: false
          FechaExpedicionIdentificacionRepresentanteLegal:
            type: string | nil
            required: false
          Donante:
            type: string
            required: true
          TipoUsuario:
            type: string
            required: true
            enum: ["1", "2"]
          TipoServicio:
            type: string
            required: true
            enum: ["1", "2"]
          SolicitudTerceros:
            type: string
            required: true
            enum: ["0", "1"]
          ListaNumeracionNip:
            type: object
            required: true
            properties:
              NumeracionNip:
                type: array
                items:
                  type: object
                  properties:
                    Numero:
                      type: string
                      required: true
                    FechaCreacionNIP:
                      type: string
                      required: true
          NRN:
            type: string
            required: true
          DocumentoID:
            type: string | nil
            required: false
          DocumentoAT:
            type: string | nil
            required: false
          DocumentoCC:
            type: string | nil
            required: false
  
  #1003
  TipoRespuestaSolicitudPortacionDonante:
    type: object
    properties:
      RespuestaSolicitudPortacionDonante:
        type: object
        required: true
        properties:
          RespuestaABD:
            type: TipoRespuestaABD
            required: true
          ListaNumeracionRechazada:
            type: TipoListaNumeracionRechazadaDonante
            required: false
  
  #1004
  TipoReplicaRespuestaSolicitudPortacionDonante:
    type: object
    properties:
      ReplicaRespuestaSolicitudPortacionDonante:
        type: object
        required: true
        properties:
          RespuestaABD:
            type: TipoRespuestaABD
            required: true
          ListaNumeracionRechazada:
            type: TipoListaNumeracionRechazadaDonante
            required: false
  
  #1005
  TipoSolicitudDeProgramacionPortacion:
    type: object
    properties:
      SolicitudDeProgramacionPortacion:
        type: object
        required: true
        properties:
          FechaVentanaMaxima:
            type: string
            required: true
  
  #1007
  TipoConfirmacionProgramacionPortacion:
    type: object
    properties:
      ConfirmacionProgramacionPortacion:
        type: object
        required: true
        properties:
          FechaVentanaCambio:
            type: string
            required: true
  
  #9999
  TipoRechazoPortacion:
    type: object
    properties:
      RechazoPortacion:
        type: object
        required: true
        properties:
          NumeracionesRechazadas:
            type: object
            required: false
            properties:
              NumeracionRechazada:
                type: array
                items:
                  type: object
                  properties:
                    Numero:
                      type: string
                      required: true
                    CodigosRechazo:
                      type: object
                      properties:
                        CodigoRechazo:
                          type: string[]
                          required: true
  
  #9998
  TipoErrorDetectadoABD:
    type: object
    properties:
      ErrorDetectadoABD:
        type: object
        properties:
          CodigosRechazo:
            type: object
            properties:
              CodigoRechazo:
                type: string[]
                required: true
          IdentificadorMensajeErroneo:
            type: string
            required: true
                
  #2001
  TipoSolicitudCancelacion:
    type: object
    properties:
      SolicitudCancelacion:
        type: object
        properties:
          ListaNumeracionCancelar:
            type: object
            required: true
            properties:
              Numero:
                type: string[]
                required: true
          FechaVentanaCancelacion:
            type: string | nil
            required: false
            
  #2002
  TipoRespuestaSolicitudCancelacion:
    type: object
    properties:
      RespuestaSolicitudCancelacion:
        type: object
        properties:
          RespuestaABD:
            type: TipoRespuestaABD
            required: true
          NumeracionesRechazadas:
            type: object
            required: false
            properties:
              NumeracionRechazada:
                type: array
                items:
                  type: object
                  properties:
                    Numero:
                      type: string
                    CodigosRechazo:
                      type: object
                      properties:
                        CodigoRechazo:
                          type: string[]