#%RAML 1.0 Library
types:
  WSCreateEnterpriseIncidentIN:
    type: object
    properties:
      part1:
        properties:
          CreateEnterpriseIncidentInput:
            properties:
              WSRequestHeader2:
                properties:
                  System:
                    properties:
                      name: 
                        description: Name of the system calling the service
                        type: string
                        example: "Salesforce"
                        required: true
                        minLength: 1
                      correlationID: 
                        description: Id related with the current service 
                        type: string
                        example: "5004y00001itm6JAAQ"
                        required: true
                        minLength: 1
                      processingServer:
                        description: Server or system controlling the service
                        type: string    
                        example: "Mulesoft"
                        required: true
                        minLength: 1
              Create:
                properties:
                  ACCION:
                    description: Action related to the incident
                    type: string
                    example: "CREAR INCIDENTE PORTAFOLIO"
                    required: false
                  IN_Notas:
                    description: Notes attached to the creation of this incident
                    type: string
                    example: "Letter or document written on the canvas"
                    required: false
                  IN_Resumen:
                    description: Summary of the event
                    type: string
                    example: "CAÍDA TOTAL DEL SERVICIO"
                    required: false
                  IN_FechaIniAfectacion: 
                    description: Date when the event occurs
                    type: string
                    example: "2021-11-01T01:31:00-05:00"
                    required: false
                  IN_TipoIdentificacion:
                    description: Kind of identification 
                    type: string
                    example: "0"
                    required: false
                  IN_IdenCliente:
                    description: Identification of the client
                    type: string
                    example: "901354361"
                    required: false
                  IN_ID_Salesforce:
                    description: Id registered in Salesforce
                    type: string
                    example: "5004y00001itm6JAAQ"
                    required: false
                  IN_IDCTAServicio:
                    description: Id of the service account
                    type: string
                    example: "0014y000022O8MuAAK"
                    required: false
                  IN_ServicioNegocio: 
                    description: Kind of service
                    type: string
                    example: "Conectividad Avanzada IP"
                    required: false
                  IN_ServicioAfectado:
                    description: Id of the process affected
                    type: string
                    example: "CAV2000010597"
                    required: false
                  IN_Nivel_1_Categoria_Operacional:
                    description: Operational category level 1
                    type: string
                    example: "INTERRUPCION"
                    required: false
                  IN_Nivel_2_Categoria_Operacional:
                    description: Operational category level 2
                    type: string
                    example: "CAIDA TOTAL"
                    required: false
                  IN_Nivel_3_Categoria_Operacional:
                    description: Operational category level 3
                    type: string
                    example: "CAIDA TOTAL"
                    required: false
                  IN_ID_Cuenta_Cliente:
                    description: Id Client Account
                    type: string
                    example: "001f300001yfNpCAAU"
                    required: false
                  IN_Nombres_Cliente:
                    description: Name of the client/enterprise
                    type: string
                    example: "PARTNERS TELECOM COLOMBIA S.A."
                    required: false
                  IN_Apellidos_Cliente:
                    description: Last Name of the client
                    type: string
                    example: "TELECOM COLOMBIA S.A."
                    required: false
                  IN_Telefono_Cliente: 
                    description: Phone number of the client
                    type: string
                    example: "3192900"
                    required: false
                  IN_E-Mail_Cliente:
                    description: Email of the client
                    type: string
                    example: "noc@avantel.com.co"
                    required: false
                  IN_Ubicacion_Cliente:
                    description: Location of the client
                    type: string
                    example: "CL 67 7 35 OF 1204"
                    required: false
                  IN_Direccion_Norm_Cliente:
                    description: Client address
                    type: string
                    example: "CL 67 7 35 OF 1204"
                    required: false
                  IN_Direccion_No_Norm_Cliente:
                    description: Client number address
                    type: string
                    example: "CL 67 7 35 OF 1204"
                    required: false
                  IN_Numero_CUN: 
                    description: CUN Number
                    type: string
                    example: "123456789"
                    required: false
                  IN_Ubicacion_Servicio:
                    description: Location of the service 
                    type: string
                    example: "Cr 26 12 55, Los Sauces"
                    required: false
                  IN_Direccion_Servicio:
                    description: Address of the service
                    type: string
                    example: "Cr 26 12 55, Los Sauces"
                    required: false
                  IN_Direccion_No_Norm_Servicio:
                    description: Address number of the service
                    type: string
                    example: "Cr 26 12 55, Los Sauces"
                    required: false
                  IN_ID_de_Servicio:
                    description: Id of the service
                    type: string
                    example: "1-969261"
                    required: false
                  IN_Codigo_Pais_Cliente: 
                    description: Code number of the client
                    type: string
                    example: "57"
                    required: false
                  IN_Codigo_Edo_Prov_Cliente:
                    description: Province code of the client
                    type: string
                    example: "11"
                    required: false
                  Create.IN_Codigo_Cd_Mun_Cliente:
                    description: Town code of the client
                    type: string
                    example: "11001"
                    required: false
                  IN_Codigo_Pais_Servicio:
                    description: Country code
                    type: string
                    example: "57"
                    required: false
                  IN_Codigo_Edo_Prov_Servicio:
                    description: Province code service
                    type: string
                    example: "25"
                    required: false
                  IN_Codigo_Cd_Mun_Servicio:
                    description: Town code service
                    type: string
                    example: "25899"
                    required: false
                  IN_Nombres_Contacto:
                    description: Contact Names
                    type: string
                    example: "NOC"
                    required: false
                  IN_Apellidos_Contacto:
                    description: Contact Last Name
                    type: string
                    example: "WOM COLOMBIA SAS"
                    required: false
                  IN_Telefono_Contacto: 
                    description: Contact phone number
                    type: string
                    example: "3507873055"
                    required: false
                  IN_EMail_Contacto:
                    description: Contact email
                    type: string
                    example: "noc@avantel.com.co"
                    required: false
                  IN_TipoCiudad:
                    description: City Type
                    type: string
                    example: "2000"
                    required: false
                  IN_Tipo_Incidencia:
                    description: Incident Type
                    type: string
                    example: "0"
                    required: false
                  IN_Impacto:
                    description: Impact
                    type: string
                    example: "2000"
                    required: false
                  IN_Urgencia: 
                    description: Insistence
                    type: string
                    example: "3000"
                    required: false
                  IN_Fuente_Reportada:
                    description: Reported source
                    type: string
                    example: "8000"
                    required: false
                  IN_Prioridad:
                    description: Priority
                    type: string
                    example: "2"
                    required: false
                  IN_ComentariosCaso:
                    description: Comments about the case
                    type: string
                    example: "Failed connection"
                    required: false
                  IN_Flag_Falla_Masiva:
                    description: Masive Failure
                    type: string
                    example: "Si"
                    required: false
                  IN_NroIncidencia_Padre_FM: 
                    description: Parent Incident Number
                    type: string
                    example: "1234567"
                    required: false
                  IN_ClientesAfectados:
                    description: Number of affected clients
                    type: string
                    example: "1"
                    required: false
                  IN_Nro_Caso:
                    description: Case Number
                    type: string
                    example: "02190443"
                    required: false
                  IN_GrupoAsignado:
                    description: Group Assigned
                    type: string
                    example: "SGP000000009522"
                    required: false
                  IN_Proveedor_Aliado:
                    description: Ally provider 
                    type: string
                    required: false
                  IN_NroProveedorAliado:
                    description: Number of the ally provider
                    type: string
                    required: false
                  IN_Esquema_Atencion:
                    description: Kind of attention
                    type: string
                    example: "Gold"
                    required: false