#%RAML 1.0 NamedExample
value:
  quotaCalculationResponse:
    quotaCalculationResult:
      requestId: 1 
      controlDate: 2022-09-27T13:03:52.64
      businessName: "Elcacharrito"
      nit: "800013931"
      approvedQuota: 1635000
      score: 905
      riskLevel: "Medio"
      errorId: 0
      errorMessage: ""