https:
  host: "0.0.0.0"
  port: "443" 
  
autodiscovery: "20593068"

customer-papi-v2:
  protocol: "HTTP"
  host: "mule-worker-internal-customer-papi-services-v2-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/v2"
  resources:  
    customer:
      base-path: "/customer"
      get:
        path: ""
    customer360:
      base-path: "/customer360"
    score:
      path: "/riskValidation/score"
    identity-validation:
      path: "/riskValidation/identityValidation"
    otp:
      resend:
        path: "/riskValidation/otp/resend"
      validation:
        path: "/riskValidation/otp/validation"
    questionnaire:
      path: "/riskValidation/questionnaire"
      validation:
        path: "/riskValidation/questionaries/{questionarie-id}/validation"
    questionaries:
      path: "/riskValidation/questionaries"
      get:
        path: "/{identityValidation}"
      validation:
        path: "/validation"
    mecna:
      path: "/riskValidation/mecna"
    product-order:
      base-path: "/productOrder"
      post:
        path: ""
      patch:
        path: ""
    transferBalance:
      path: "/transferBalance"
    balance:
      base-path: "/balance"
      get:
        path: ""
    billingBalance:
      path: "/billingBalance"
    billingHistory:
      path: "/billingHistory"
    billingAccountItem:
      path: "/billingAccountItem"
    billingDispute:
      path: "/billingDispute"
  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

service-papi-v2:
  protocol: "HTTP"
  host: "mule-worker-internal-service-papi-services-v2-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/v2"
  serviceOrder:
    base-path-mobile: "/serviceOrder/orquestator/mobile/processOrder"
    base-path-fix: "/serviceOrder/orquestator/fix/processOrder"

  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

payment-papi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-payment-management-papi-services-prod.us-e2.cloudhub.io"
  basepath: "/api/v1"
  paths:
    getBanks: "/payment/banks"
    postPayment: "/payment"
    getPayment: "/payment/{paymentId}"
    patchPayment: "/payment/{paymentId}"
    postWebhook: "/payment/webhook"
    postWebhookConfirmationPayu: "/payment/webhook/confirmation/payu"
  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"
  
configurationTimeout:
  customer-xapi-v2-listener: "62000"
  service-papi-v2:
    responseTimeout: "62000"
  customer-papi-v2:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
  product-papi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
  customers-papi: "62000"
