#%RAML 1.0 DataType
type: object
properties:
  validatePremiseEquipmentInstall:
    type: object
    properties:
      messageHeader:
        type: object
        properties:
          availabilityId: string
          provisioningOrderNumber: string
          revisionNumber: number
          orderRequestDate: string
          etbTechnology: string
      detail:
        type: object
        properties:
          address:
            type: object
            properties:
              uniqueAddressCode: string
              serviceAccountId: string
              equipments:
                type: array
                items:
                  type: object
                  properties:
                    serviceId:
                      type: string
                      required: false
                    equipmentSerial: string
                    equipmentMac: string
                    ports:
                      type: array
                      items:
                        type: object
                        properties:
                          portName: string
                          portServices:
                            type: object
                            properties:
                              portServiceId: string
                    installedEquipment: string