#%RAML 1.0 DataType
type: object
properties:
  completeInventoryOrder:
    type: object
    properties:
      messageHeader:
        type: object
        properties:
          availabilityId: string
          provisioningOrderNumber: string
          revisionNumber: number
          orderRequestDate: string
          etbTechnology: string
      detail:
        type: object
        properties:
          serviceAccounts:
            type: object
            properties:
              serviceAccount:
                type: array
                items:
                  type: object
                  properties:
                    serviceAccountId: string
                    servicesToComplete:
                      type: array
                      items:
                        type: object
                        properties:
                          serviceId: string
                          action: string
                          equipments:
                            type: array
                            items:
                              type: object
                              properties:
                                serviceId:
                                  type: string
                                  required: false
                                equipmentSerial: string
                                equipmentMac: string
                                equipmentStatus: string
                                action: string
                                ports:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      portName: string
                                      portServices:
                                        type: object
                                        properties:
                                          portServiceId: string
              source: string
