#%RAML 1.0 DataType

properties:
  ReconnectionRMCAOutput:
    type: object
    properties:
      WSResponseHeader2:
        type: object
        properties:
          System:
            type: object
            properties:
              name:
                type: string
                example: "MuleSoft"
              correlationID:
                type: string
                example: "$Start/root/pfx7:ReconnectionRMCAInput/pfx6:WSRequestHeader2/System/correlationID"
              processingServer:
                type: string
                example: "MuleSoft"
          Service:
            type: object
            properties:
              status:
                type: string
                example: "PASS"
              responseDate:
                type: string
                example:  "2022-07-29"
      ZRFC_TRAMITE_RECONEXIONResponse:
        type: object
        properties:
          T_RETURN:
            type: array
            items:
              properties:
                TYPE:
                  type: string | nil
                  required: false
                ID:
                  type: string | nil
                  required: false 
                NUMBER:
                  type: string | nil
                  required: false
                MESSAGE: 
                  type: string | nil
                  required: false
                LOG_NO:
                  type: string | nil
                  required: false
                LOG_MSG_NO:
                  type: string | nil
                  required: false
                MESSAGE_V1:
                  type: string | nil
                  required: false
                MESSAGE_V2:
                  type: string | nil
                  required: false
                MESSAGE_V3:
                  type: string | nil
                  required: false
                MESSAGE_V4:
                  type: string | nil
                  required: false