http:
  private:
    port: "8091"
  
autodiscovery: "20593005"

mongo-db-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/mongo/v1"
  resources:  
    retention:
      base-path: "/retention"
      post:
        path: ""
      patch:
        path: ""
    billingAccount:
      base-path: "/billingAccount"
      get:
        path: ""
    agreements:
      base-path: "/agreements"
      post:
        path: ""

  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
portal-fija-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-portal-fija-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/fija/v1"
  resources:  
    agreements:
      base-path: "/agreement"
      getPermanenceClause:
        path: "/getPermanenceClause"

  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
oracle-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/oracle/v1"
  resources:
    basepath: "/resources"
    get:
     path: "/{id}"
    inArea:
     path: "/inArea"
     
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  configurationTimeout: "62000"
  
sisext-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/sisext/v1"
  path:
    createAgreement: "createAgreement"
  employees:
    basepath: "/employees"
    get:
     path: "/{id}"

  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  configurationTimeout: "62000"

azure-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-azure-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/azure/v1"
  path:
    agreements: "agreements"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

common-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/common/v1"
  path:
    traceability: "/traceabilityLogs"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

jsc-sapi:
  protocol: "HTTPS"
  port: "443"
  host: "mule-worker-internal-jsc-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/jsc/v1"
  subscriber:
    patch-resource: "/subscriber/{id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

directv-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-directv-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/v1"

  resources:
    customer:
      base-path: "/customers"
      get:
       path: "/{customerId}"
      post:
       path: ""
      products:
        path: "/{customerId}/products"
        
  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

configurationTimeout:
  business-papi-v2-listener: "62000"
  mongo-db-sapi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
  portal-fija-sapi:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"
  azure-sapi:
    responseTimeout: "61000"
    connectionIdleTimeout: "60000"
  common-sapi:
    responseTimeout: "61000"
    connectionIdleTimeout: "60000"
  directv-sapi:
    responseTimeout: "62000"
    connectionIdleTimeout: "60000"
  jsc-sapi:
    responseTimeout: "62000"
    connectionIdleTimeout: "60000"

pagination:
  profile: "${PAGINATION_PROFILE:Bajo}"
  profiles:
    bajo:
      max: "${PAGINATION_BAJO_MAX:25}"
    medio:
      max: "${PAGINATION_MEDIO_MAX:50}"
    alto:
      max: "${PAGINATION_ALTO_MAX:100}"
  default:
    offset: "0"
