http:
  host: "0.0.0.0"
  private:
    port: "8091"
  path: "/orquestador/*"
 
autodiscovery: "18923828"

configurationTimeout:
  ofsc: "60000"
  orquestador: "60000"
  mongo-db-sapi: "60000"
  
ofsc:
  protocol: "HTTP"
  host: "10.60.22.17"
  port: "86"
  basepath: "/OFSC/OFSC.svc"
  getOrder:
    path: "/ofsc"
    soapAction: "http://tempuri.org/IOFSC/ObtenerOrdenOFSC"
  updateProperties:
    path: "/ofsc"
    soapAction: "http://tempuri.org/IOFSC/ActualizarPropiedades"
    
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
orquestador:
  protocol: "HTTP"
  host: "10.60.22.4"
  port: "81"
  basepath: "/MDM_Orquestador"
  path: "/MDMOrchestrationService.svc"
  soapAction: "http://orchestration.cloud.etb.com.co/IMDMOrchestrationService/RunOrchService"
  
mongo-db-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/mongo/v1"
  path:
    post-esim-log: "/esim/log"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
obtenerAgendaDisponible:
  soap:
    wsdlProtocol: "http://"
    addressProtocol: "http://"
    host: "10.60.22.4:86"
    wsdlPath: "/OrquestadorService.svc?wsdl"
    service: "OrquestadorService"
    servicePort: "BasicHttpBinding_IOrquestadorService"
    address: "/OrquestadorService.svc/basic"
    operations:
      obtenerAgendaDisponible: "ObtenerDisponibilidadAgendas"