https:
  port: "443"

autodiscovery: "17959357"

configurationTimeout:
  listener: "62000"
  normalize-sapi: "62000"
  sisext-sapi: "184000"
  smallworld-sapi: "72000"
  operations-papi: "184000"
  m6services: "60000"
  mongo-sapi: "62000"
  etb-mdm-sapi: "92000"
  portabilidad-papi: "62000"
  audits-mongo: "62000"
  support-papi: "62000"
  mongoDb-sapi: "62000"
  common-papi: "62000"
  

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

operations-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/operations"
  path: 
    getCoverage: "/v1/coverages/details"
    getCuestionario: "v1/cuestionario"
    sendNotification: "v1/sendNotification/{campania}"
    patchOrdenes: "/v1/order/{numOrden}"
    omnicanalidad: "/v1/omnicanalidad/interaction"
    solicitarQResim: "/v1/esim/solicitarQResim"

smallworld-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-smallworld-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/smallworld/v1"
  path: "/georeference"
  geoDireccion:
    path: "/geoDireccion"
    
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

sisext:
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/sisext/v1"
  feasibility:
    path: "/feasibility"
  coverage:
    path: "/coverageGIS"
  protocol: "HTTP"
  
normalize-papi:
  protocol: "HTTP"
  basepath: "/normalize/v1"
  path: "/normalizeAddress"
  host: "mule-worker-internal-normalize-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  
m6services:
  protocol: "HTTP"
  basepath: "/"
  host: "10.112.2.163"
  port: "80"
  ftth:
    path: "M6ETBInventarioWeb/jpd/consultas/ConsultarNumerosDisponibles.jpd"
    soapAction: "http://www.openuri.org/doConsultarNumerosDisponibles"
  fttc:
    path: "M6FTTC_Web/jpd/consultas/ConsultarNumerosDisponibles.jpd"
    soapAction: "http://www.openuri.org/doConsultarNumerosDisponibles"
  disponibilidad:
    path: "M6ETBInventarioWeb/jpd/gestionRecursos/disponibilidad/ConsultarNumerosDisponibles.jpd"
    soapAction: "http://www.openuri.org/doConsultarNumerosDisponibles"
  resources:
    vias:
      path: "CFG_Consulta_Numeracion/CFG_ConsultaNumeracionService"
  cobreWeb:
    host: "10.112.2.163"
    port: "80"
    path: "M6ETBCobreWeb/jpd/consultas/ConsultarNumerosDisponibles.jpd"
    soapAction: "http://www.openuri.org/doConsultarNumerosDisponibles"

mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/mongo/v1"
  path:
    ordenes: "/orders/{orderNumber}"
    agendaTmr: "/pqrs/agenda_tmr/{orderNumber}"
    fallasMasivas: "/pqrs/fallaMasiva"
    manualEquipos: "/manualEquipos"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
mongoDb-sapi:  
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/mongo/v1"
  path:
    ordenes: "/orders/{orderNumber}"    
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"  
  
etb-mdm:
  protocol: "HTTP"
  host: "mule-worker-internal-etb-mdm-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/mdm"
  path: 
    updateOrderStatus: "/v1/orders/orderStatus"
    
audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs/"
  path: "/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

portabilidad-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-portabilidad-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/v1"
  path:
    bookingFeasibility: "/infrastructure/services/feasibility/bookingFeasibility"
    createBooking: "/infrastructure/services/feasibility/createBooking"
    consultBooking: "/infrastructure/services/feasibility/consultBooking"
    cancelBooking: "/infrastructure/services/feasibility/cancelBooking"
    speedChangeFeasibility: "/infrastructure/services/speedChange/feasibility"
    speedChangeCreateBooking: "/infrastructure/services/speedChange/createBooking"
    speedChangeCancelBooking: "/infrastructure/services/speedChange/cancelBooking"
    speedChange: "/infrastructure/services/speedChange"
    activateOnt: "/infrastructure/services/activation/ont"
    activateService: "/infrastructure/services/activation/service"
    deactivateOnt: "/infrastructure/services/deactivation/ont"
    deactivateService: "/infrastructure/services/deactivation/service"
    resetONT: "/infrastructure/services/support/resetONT"
    consultLevels: "/infrastructure/services/support/consultLevels"
    consultSpeed: "/infrastructure/services/support/consultSpeed"
    consultState: "/infrastructure/services/support/consultState"
    consultNeighbors: "/infrastructure/services/support/consultNeighbors"
    serviceSuspension: "/infrastructure/services/modification/serviceSuspension"
    serviceReactivation: "/infrastructure/services/modification/serviceReactivation"

support-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-support-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/support/v1"
  path: 
    create: "/agreements/create"
    retrieve: "/agreements/retrieve" 
       
common-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/common"
  path:
    geoAddress: "/geographicAddressManagement/v1/geographicAddress/geoAddress"