#%RAML 1.0 DataType
properties:
  channel:
    type: string
    required: false
  date:
    type: datetime
    required: false
  decision:
    type: string
    required: false
  pqr:
    type: string
    required: false
  user:
    type: string
    required: false