#%RAML 1.0 DataType
properties:
  channels:
    type: array
    items:
      properties:
        channel:
          type: string
          required: false
        value:
          type: string
          required: false
  creationDate:
    type: datetime
    required: false
  schedule:
    type: string
    required: false
  updateDate:
    type: datetime
    required: false
    