#%RAML 1.0 DataType
properties:
  address:
    type: !include address.raml
    required: false
  economicActivity:
    type: string
    required: false
  email:
    type: string
    required: false
  legalName:
    type: string
    required: false
  legalRepresentative:
    type: any
    required: false
  mobilePhone:
    type: string
    required: false
  phone:
    type: string
    required: false
  sector:
    type: string
    required: false