#%RAML 1.0 DataType
properties:
  channel:
    type: string
    required: false
  decision:
    type: string
    required: false
  decisionDate:
    type: datetime
    required: false
  idPqr:
    type: string
    required: false