#%RAML 1.0 DataType
properties:
  acceptPermanenceClause:
    type: boolean
    required: false
  installationChargesInternet:
    type: number
    required: false
  installationChargesTv:
    type: number
    required: false
  installationChargesVoice:
    type: number
    required: false
  total:
    type: number
    required: false