#%RAML 1.0 DataType
properties:
  capacity:
    type: !include capacityService.raml
    required: false
  descentSpeed:
    type: !include capacityService.raml
    required: false
  isTwin:
    type: boolean
    required: false
  secundary:
    type: array
    items: !include secundary.raml
    required: false
  sharedCapacity:
    type: string
    required: false
  uploadSpeed:
    type: !include capacityService.raml
    required: false
  numberDevices:
    type: integer
    required: false
  svas:
    type: array
    items: any
    required: false
  usageTime:
    type: object
    required: false
    properties:
      entertainment:
        type: integer
        required: false
      study:
        type: integer
        required: false
      work:
        type: integer
        required: false