#%RAML 1.0 DataType
properties:
  anticipatedPayment:
    type: boolean
    required: false
  iva:
    type: number
    required: false
  value:
    type: number
    required: false
  valueStr:
    type: string
    required: false
  valueWithoutIva:
    type: number
    required: false
  valueWithoutIvaStr:
    type: string
    required: false
  validity:
    type: string
    required: false