#%RAML 1.0 DataType
properties:
  benefit:
    type: string
    required: false
  conditioned:
    type: boolean
    required: false
  description:
    type: string
    required: false
  descriptionShort:
    type: string
    required: false
  differential:
    type: boolean
    required: false
  discounts:
    type: array
    required: false
    items:
      type: object
      properties:
        benefit:
          type: string
          required: false
        description:
          type: string
          required: false
        validity:
          type: string
          required: false
  id:
    type: string
    required: false
  isZoned:
    type: boolean
    required: false
  mandatoryPlans:
    type: array
    items: string
    required: false
  name:
    type: string
    required: false
  outStanding:
    type: boolean
    required: false
  quantity:
    type: integer
    required: false
  stratums:
    type: array
    items: string
    required: false
  type:
    type: string
    required: false
  validity:
    type: string
    required: false
  zoned:
    type: !include zoned.raml
    required: false
  activationDate:
    type: datetime
    required: false
  currentMonth:
    type: integer
    required: false
  inactivationDate:
    type: datetime
    required: false
  timeLeft:
    type: string
    required: false