#%RAML 1.0 DataType
type: object
properties:
  available:
    type: boolean
    required: false
  description:
    type: string
    required: false
  characteristics:
    type: array
    required: false
    items:
      type: object
      properties:
        characteristic:
          type: string
          required: false
        icon:
          type: string
          required: false
  conflicting:
    type: array
    items: string
    required: false
  contracted:
    type: boolean
    required: false
  executionPlan:
    type: array
    items: !include executionPlan.raml
    required: false
  executionPlanDifferential:
    type: array
    items: !include executionPlan.raml
    required: false
  icon:
    type: string
    required: false
  id:
    type: string
    required: false
  idsOld:
    type: array
    items: string
    required: false
  mandatory:
    type: boolean
    required: false
  name:
    type: string
    required: false
  price:
    type: !include price.raml
    required: false
  quantity:
    type: object
    required: false
    properties:
      available:
        type: boolean
        required: true
      contracted:
        type: boolean
        required: true
  saving:
    type: number
    required: false
  serviceType:
    type: string
    required: false
  value:
    type: number
    required: false
  visibility:
    type: object
    required: false
    properties:
      action:
        type: string
        required: false
      conditioned:
        type: boolean
        required: false
      plans:
        type: array
        items: string
        required: false
  promotions:
    type: array
    items: !include promotion.raml
    required: false
  saleOrder:
    type: !include order.raml
    required: false