#%RAML 1.0 DataType
properties:
  name:
    type: string
    example: ""
    required: false
  correlationID:
    type: string
    example: ""
    required: false
  processingServer:
    type: string
    example: ""
    required: false