#%RAML 1.0 NamedExample
value:
  SuscriberId: "12054124652"
  DocumentNumber: "860002503"
  DocumentType: NIT
  FullName: COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP MOVIL
  #FirstName: null
  LastName: COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP MOVIL
  AccountIdentificationID: a054y00000lClQhAAK
  AccountDocumentNumber: "860002503"
  AccountName: COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP MOVIL
  AccountTypeCode: JURIDICO
  IdentificationID: a054y00000lClQhAAK
  OrderSubType: VENTA LTE
  SourceSystem: SF
  ClaimMethod: MetodoReclamacion
  ExternalAddressNumber: a054y00000lClQhAAK
  #IndustrialSector: null
  Segment: Empresas
  SubSegment: Grande
  EconomicActivity: 'Corp'
  Country: Colombia
  City: BOGOTÁ, D.C.
  Street: KR 10 28 49 TO A PI 4
  Telephone: "13410077"
  InvoicingCycle: "96"
  DaneCode: "11001"
  IsBilling: Y