#%RAML 1.0 NamedExample
value:
  OrderFulfilment:
    Identification:
      ID: a054y00000lClQhAAK
      BusinessComponentID: ""
      ApplicationObjectKeyID: ""
    SalesOrder:
      OrderDateTime: 2021-10-01T09:33:46.602-05:00
      DeliveryDateTime: 2021-10-01T09:33:46.602-05:00
      TypeCode: ""
      FulfilmentPriorityCode: ""
      FulfilmentModeCode: ""
      StatusCode: ""
    BusinessReference:
      Id: ""
      ComponentId: ""
      ApplicationObjectKeyId: ""
    CustomerPartyAccount:
      Identification:
        ID: ""
        BusinessComponentID: ""
        ApplicationObjectKeyID: ""
      Name: COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP MOVIL
      Address: 
        LineOne: ""
      ContactPerson:
        FirstName: ""
        FamilyName: ""
        CompleteNumber: ""
      TypeCode: JURIDICO
      Custom:
        DocumentType: ""
        DocumentNumber: "860002503"
    Custom:
      OrderSubType: VENTA LTE
      SignedDocumentIndicator: true
    PartyIdentification:
      ID: ""
      BusinessComponentID: ""
      ApplicationObjectKeyID: ""
    SalesOrderLine:
      Identification:
        ID: ""
        BusinessComponentID: ""
        ApplicationObjectKeyID: ""
      OrderQuantity: ""
      ServiceActionCode: ""
      FulfilmentModeCode: ""
      ParentSalesOrderLineIdentification:
        ID: ""
        BusinessComponentID: ""
        ApplicationObjectKeyID: ""
      RootParentSalesOrderLineIdentification:
        ID: ""
        BusinessComponentID: ""
        ApplicationObjectKeyID: ""
      StatusCode: ""
      ServiceAddress:
        LineOne: ""
      ItemReference:
        ItemIdentification:
          ID: ""
          BusinessComponentID: ""
          ApplicationObjectKeyID: ""
        Name: ""
        ServiceIndicator: true
        TypeCode: ""
        NetworkIndicator: true
        PrimaryClassificationCode: ""
      SalesOrderSchedule:
        RequestedDeliveryDate: 2021-10-01T09:33:46.602-05:00
        ExpectedDeliveryDate: 2021-10-01T09:33:46.602-05:00
      OwnerPartyReference:
        ID: ""
        BusinessComponentID: ""
        ApplicationObjectKeyID: ""
      ScheduleOrderIndicator: ""
      Custom:
        PartNumber: ""
        AssetIntegrationID: ""
      AltKey:
        -
          AltKeyName: SysOrg
          AltKeyValue: SF
        -
          AltKeyName: USO
          AltKeyValue: SF
        -
          AltKeyName: BACYT
          AltKeyValue: BOGOTÁ, D.C.
        - 
          AltKeyName: MetodoReclamacion
          AltKeyValue: MetodoReclamacion
        - 
          AltKeyName: BACON
          AltKeyValue: Colombia
        - 
          AltKeyName: BAAID
          AltKeyValue: a054y00000lClQhAAK
        - 
          AltKeyName: ETBFN
          AltKeyValue: ""
        - 
          AltKeyName: BAUSO
          AltKeyValue: ""
        - 
          AltKeyName: ETBLN
          AltKeyValue: COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP MOVIL
        - 
          AltKeyName: Segmento
          AltKeyValue: Empresas
        - 
          AltKeyName: BAADD
          AltKeyValue: KR 10 28 49 TO A PI 4
        - 
          AltKeyName: Subsegmento
          AltKeyValue: Grande
        - 
          AltKeyName: PHONE
          AltKeyValue: "13410077"
        - 
          AltKeyName: ETB Facturable
          AltKeyValue: Y
  BillingProcess:
    Customer:
      FullName: COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP MOVIL
      ContactInfo:
        ContactAddress:
          DaneCode: 11001
      DocumentType: NIT
      DocumentNo: 860002503
    CustomerBill:
      SuscriberId: "12054124652"
      InvoicingCycle: "96"  
