#%RAML 1.0 DataType
type: object
description: |
  Request body for billingDispute. Suspend the dispute charge and wait for the subsequent dispute to be settled in ZSmart (CreateDispute).
properties:
  transactionId:
    type: string
    minLength: 1
    maxLength: 60
    description: "transaction ID that generate by external system (e.g. 20260918220345) -> content.transactionID"
    example: "20260918220345"
    required: true
  msisdn:
    type: string
    minLength: 1
    maxLength: 20
    description: "MSISDN with area code (e.g. 6015551234). -> content.msisdn"
    example: '6015551234'
    required: false
  accountNumber:
    type: string
    minLength: 1
    maxLength: 30
    description: "Account number
MSISDN and AccountNumber can not be null at same time. If Both exist at same time, refer to MSISDN (e.g. 9865322154). -> content.accountNumber"
    example: '9865322154'
    required: false
  partyType:
    type: string
    minLength: 1
    maxLength: 1
    description: "partyType
When partyCode is not empty and partyType is empty,the partyType default value is F (e.g. F). -> content.partyType"
    example: 'F'
    required: false
  partyCode:
    type: string
    minLength: 1
    maxLength: 30
    description: "partyCode (e.g. code). -> content.partyCode"
    example: 'code'
    required: false
  comment:
    type: string
    minLength: 1
    maxLength: 255
    description: "comments, dispute reason (e.g. disputes reason). -> content.comment"
    example: 'dispute reason'
    required: false
  charge:
    type: string
    minLength: 1
    maxLength: 18
    description: "dispute ammount (e.g. 180000). -> content.charge"
    example: '180000'
    required: true
  billId:
    type: string
    minLength: 1
    maxLength: 15
    description: "Bill ID (e.g. 78545356). -> content.billId"
    example: '78545356'
    required: false
  channelCode:
    type: string
    minLength: 1
    maxLength: 20
    description: "Channel Code (e.g. USSD). -> content.channelCode"
    example: '78545356'
    required: false
  disputes:
    type: array
    required: true
    items:
      type: object
      properties:
        acctItemId:
          type: string
          minLength: 1
          maxLength: 15
          description: "Dispute account Item ID (e.g. 875421326598754). -> content.disputeItemExParamList[n].acct"
          example: '875421326598754'
          required: true
        charge:
          type: string
          minLength: 1
          maxLength: 18
          description: "Dispute charge (e.g. 800000). -> content.disputeItemExParamList[n].charge"
          example: '800000'
          required: true
example: !include ../../examples/request/post-billingDispute.json