#%RAML 1.0 DataType 
type: object
properties:
  id:
    type: string
    example: 68ded01c7d0397ef7b0664cc
    required: false
  createdAt:
    type: datetime
    example: '2025-10-02T14:18:52.473Z'
    required: false
  updatedAt:
    type: datetime
    example: '2025-10-02T14:30:25.385Z'
    required: false
  updatedBy:
    type: string
    example: PortalLTE
    required: false
  createdBy:
    type: string
    example: PortalLTE
    required: false
  extractorUpdate:
    type: string
    example: '1'
    required: false
  orderNumber:
    type: string
    example: MDM-FIBRA-000636091
    required: false
  channel:
    type: string
    example: Ecommerce
    required: true
  description:
    type: string
    example: Error Orquestación
    required: false
  priority:
    type: string
    example: Error Orquestación
    required: false
  phase:
    type: string
    example: ORDERF
    required: false
  commercialOrderStatus:
    type: object
    required: false
    properties:
      code:
        type: string
        example: O75
        required: false
      description:
        type: string
        example: Error Orquestación
        required: false
      date:
        type: datetime
        example: '2025-10-02T14:22:17.594Z'
        required: false
      retries:
        type: integer
        example: 0
        required: false
      exceptionCode:
        type: integer
        example: 1
        required: false
      exception:
        type: string
        example: >-
          La tarea VCONDES del sistema no se ha completado correctamente.
          Consulte al fiduciario del sistema.
        required: false
  through:
    type: object
    properties:
      throughType:
        type: string
        example: VTA
        required: true
      throughSubtype:
        type: string
        example: ''
        required: false
      throughDate:
        type: datetime
        example: '2025-10-02T14:18:52.473Z'
        required: false
      reconnectionDate:
        type: string
        example: ''
        required: false
      suspensionDate:
        type: string
        example: ''
        required: false
      executionDate:
        type: datetime
        example: '2025-10-02T14:18:52.473Z'
        required: false
      keepConnectionNumber:
        type: boolean
        example: false
        required: false
      permanenceClause:
        type: boolean
        example: true
        required: false
      permanenceClauseValue:
        type: integer
        example: 0
        required: false
      cancellationReason:
        type: string
        example: ''
        required: false
      cancellationSubreason:
        type: string
        example: ''
        required: false
      cancellationDescription:
        type: string
        example: ''
        required: false
      orderMotives:
        type: string
        example: ''
        required: false
  category:
    type: string
    example: LTE
    required: true
  cun:
    type: string
    example: '4347250001278699'
    required: false
  requestCustomer:
    type: object
    properties:
      documentType:
        type: string
        example: CC
        required: true
      documentNumber:
        type: string
        example: '28564778'
        required: true
      firstName:
        type: string
        example: PROSPECTO
        required: false
      companyShortName:
        type: string
        example: ''
        required: false
      firstLastName:
        type: string
        example: JIMENEZ
        required: false
      secondLastName:
        type: string
        example: ''
        required: false
      expeditionDate:
        type: string
        example: '1968-01-20T00:00:00Z'
        required: false
      identityValidationDate:
        type: string
        example: ''
        required: false
      personalDataHandlingAuthorization:
        type: string
        example: 'N'
        required: false
      creditBureauCheckAuthorization:
        type: string
        example: 'N'
        required: false
      businessUnit:
        type: string
        example: Hogares y Mipymes
        required: false
      businessUnitSegment:
        type: string
        example: Hogares
        required: false
      segment:
        type: string
        example: Hogares
        required: false
      fixedScoring:
        type: object
        properties:
          scoringValue:
            type: integer
            example: 0
            required: false
          scoringDate:
            type: string
            example: '1968-01-20T00:00:00Z'
            required: false
          scoringClassification:
            type: string
            example: ''
            required: false
          scoringType:
            type: string
            example: ''
            required: false
          sourceSystem:
            type: string
            example: ''
            required: false
      landlinePhone:
        type: string
        example: ''
        required: false
      extension:
        type: string
        example: ''
        required: false
      mobilePhone:
        type: string
        example: '3156360101'
        required: false
      secondaryMobilePhone:
        type: string
        example: ''
        required: false
      email:
        type: string
        example: notiene@etb.com.co
        required: false
      contacts:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              example: 68decf606d735051ede511c7
              required: false
            documentType:
              type: string
              example: CC
              required: false
            documentNumber:
              type: string
              example: '28564778'
              required: false
            firstName:
              type: string
              example: PROSPECTO
              required: false
            firstLastName:
              type: string
              example: JIMENEZ
              required: false
            secondLastName:
              type: string
              example: ''
              required: false
            landlinePhone:
              type: string
              example: ''
              required: false
            secondaryLandlinePhone:
              type: string
              example: ''
              required: false
            mobilePhone:
              type: string
              example: '3156360101'
              required: false
            secondaryMobilePhone:
              type: string
              example: ''
              required: false
            email:
              type: string
              example: ''
              required: false
            state:
              type: string
              example: BOGOTA
              required: false
            city:
              type: string
              example: BOGOTA D.C.
              required: false
            daneCode:
              type: string
              example: ''
              required: false
            address:
              type: string
              example: KR 7 20 00
              required: false
            locality:
              type: string
              example: ''
              required: false
            isSelected:
              type: boolean
              example: false
              required: false
            isAuthorized:
              type: boolean
              example: true
              required: false
            status:
              type: boolean
              example: false
              required: false
            isDeleted:
              type: boolean
              example: false
              required: false
            contactAttachments:
              type: string
              example: ''
              required: false
      addresses:
        type: array
        items:
          type: object
          properties:
            addressId:
              type: integer
              example: 2
              required: false
            normalizedAddress:
              type: string
              example: KR 1 70 21 AP 101
              required: false
            addressType:
              type: string
              example: INSTALACION
              required: false
            addressCode:
              type: string
              example: ''
              required: false
            stateCode:
              type: string
              example: '11'
              required: false
            municipalityCode:
              type: string
              example: '11001'
              required: false
            countryCode:
              type: string
              example: 593b0ac99a8e4177d410df4d
              required: false
            state:
              type: string
              example: BOGOTA
              required: false
            municipality:
              type: string
              example: BOGOTA D.C.
              required: false
            status:
              type: string
              example: ACTIVO
              required: false
            isSelected:
              type: boolean
              example: true
              required: false
            coverage:
              type: object
              properties:
                coverageType:
                  type: string
                  example: MOLECULA
                  required: false
                lotCode:
                  type: string
                  example: '12'
                  required: false
                locality:
                  type: string
                  example: '02'
                  required: false
                stratum:
                  type: integer
                  example: 2
                  required: false
                latitude:
                  type: number
                  example: 4.650874623
                  required: false
                longitude:
                  type: number
                  example: -74.05224817
                  required: false
                gisAddress:
                  type: string
                  example: '612802304579196010'
                  required: false
                coverageName:
                  type: string
                  example: FCO23
                  required: false
                olt:
                  type: string
                  example: BOCOZTC30001
                  required: false
                owner:
                  type: string
                  example: ETB
                  required: false
                purpose:
                  type: string
                  example: '01'
                  required: false
                technology:
                  type: string
                  example: FTTH
                  required: false
                zone:
                  type: string
                  example: CHICO
                  required: false
                molecule:
                  type: string
                  example: FCO23
                  required: false
                isViable:
                  type: boolean
                  example: false
                  required: false
                usageCode:
                  type: string
                  example: '001'
                  required: false
  requestService:
    type: object
    properties:
      updatedAt:
        type: datetime
        example: '2025-10-02T14:20:22.089Z'
        required: false
      serviceAccountId:
        type: string
        example: CS-1052382
        required: false
      bundle:
        type: object
        properties:
          id:
            type: string
            example: 68769f4c7b67fb1a1015a60a
            required: false
          productGroupingNumber:
            type: integer
            example: 6847
            required: false
          productType:
            type: string
            example: BUNDLE
            required: false
          serviceType:
            type: string
            example: FTTH
            required: true
          name:
            type: string
            example: DUO 500M HOG V3
            required: false
          status:
            type: string
            example: Activo
            required: false
          minQuantity:
            type: integer
            example: 1
            required: false
          maxQuantity:
            type: integer
            example: 1
            required: false
          offerPrice:
            type: array
            items:
              type: object
              properties:
                priceWithoutTax:
                  type: integer
                  example: 99900
                  required: false
                priceWithTax:
                  type: integer
                  example: 99900
                  required: false
                tax:
                  type: integer
                  example: 0
                  required: false
          bundleParameters:
            type: array
            items:
              type: object
              properties:
                parameter:
                  type: string
                  example: CANAL VENTA
                  required: false
                value:
                  type: string
                  example: PORTAL FIJA/ECOMMERCE/AUTOGESTION
                  required: false
      totalPrice:
        type: string
        example: '99900'
        required: false
  requestProduct:
    type: object
    properties:
      code:
        type: string
        example: bundle
        required: true
  featureOrder:
    type: array
    required: false
    items:
      type: object
      properties:
        feature:
          type: string
          example: PQR_CAUSAL
          required: false
        value:
          type: string
          example: FALLA INTERNET
          required: false
  featureService:
    type: array
    required: false
    items:
      type: object
      properties:
        feature:
          type: string
          example: PQR_CAUSAL
          required: false
        value:
          type: string
          example: FALLA INTERNET
          required: false
  requestBillingAccount:
    type: object
    required: false
    properties:
      createdAt:
        type: datetime
        example: '2025-10-03T15:59:17.578Z'
        required: false
      updatedAt:
        type: datetime
        example: '2025-10-03T15:59:17.578Z'
        required: false
      updatedBy:
        type: string
        example: ''
        required: false
      createdBy:
        type: string
        example: ''
        required: false
      extractorUpdate:
        type: string
        example: ''
        required: false
      billingAccountId:
        type: string
        example: '15052963336'
        required: false
      basicCustomer:
        type: object
        properties:
          id:
            type: string
            example: '000000000000000000000000'
            required: false
          createdAt:
            type: datetime
            example: '2025-10-03T15:59:17.578Z'
            required: false
          updatedAt:
            type: datetime
            example: '2025-10-03T15:59:17.578Z'
            required: false
          updatedBy:
            type: string
            example: ''
            required: false
          createdBy:
            type: string
            example: ''
            required: false
          extractorUpdate:
            type: string
            example: ''
            required: false
          customerAccountId:
            type: integer
            example: 0
            required: false
          documentType:
            type: string
            example: CC
            required: false
          documentNumber:
            type: string
            example: '210202502'
            required: false
      status:
        type: object
        properties:
          code:
            type: string
            example: A
            required: false
          description:
            type: string
            example: ''
            required: false
          date:
            type: string
            example: ''
            required: false
          exceptionCode:
            type: integer
            example: 0
            required: false
          exception:
            type: string
            example: ''
            required: false
      billingType:
        type: string
        example: Detailed
        required: false
      invoiceType:
        type: string
        example: Detailed
        required: false
      deliveryType:
        type: string
        example: Physical
        required: false
      invoiceValue:
        type: integer
        example: 0
        required: false
      formattedInvoiceValue:
        type: string
        example: ''
        required: false
      billingEmail:
        type: string
        example: dkdi317b6z@mkzaso.com
        required: false
      billingCycle:
        type: string
        example: '34'
        required: false
      cutoffDay:
        type: integer
        example: 0
        required: false
      isOverdue:
        type: boolean
        example: false
        required: false
      billingAddressId:
        type: integer
        example: 2
        required: false
      suspensionDate:
        type: string
        example: ''
        required: false
      chargingCycle:
        type: integer
        example: 0
        required: false
      chargingCycleCode:
        type: integer
        example: 0
        required: false
      serviceAccounts:
        type: string
        example: ''
        required: false
      billingCutoffDate:
        type: string
        example: '8'
        required: false
  scheduling:
    type: object
    required: false
    properties:
      appointmentDate:
        type: datetime
        example: '2025-10-03T00:00:00.000Z'
        required: false
      appointmentSlot:
        type: string
        example: AM_2
        required: false
      workType:
        type: string
        example: F.O. (HSI/VOIP)
        required: false
      duration:
        type: string
        example: '130'
        required: false
      hasAppointment:
        type: boolean
        example: true
        required: false
      activityId:
        type: string
        example: '8848731'
        required: false
  attachments:
    type: object
    required: false
    properties:
      service:
        type: array
        items:
          type: object
          properties:
            fileName:
              type: string
              example: ANEXO_DIGITAL_DEFINITIVO_SVA
              required: false
            path:
              type: string
              example: 28564778/MDM-FIBRA-000636091/ANEXO_DIGITAL_DEFINITIVO_SVA
              required: false
            size:
              type: string
              example: '236023'
              required: false
