#%RAML 1.0 DataType 
type: object
properties:
  serviceOrder:
    type: object
    properties:
      customer:
        type: object
        properties:
          documentNumber:
            type: string
            example: '1023456789'
            required: false
          documentType:
            type: string
            example: CC
            required: false
          phone:
            type: string
            example: +57 3001234567
            required: false
      service:
        type: object
        properties:
          serviceAccountNumber:
            type: string
            example: ACC-987654
            required: false
      orderType:
        type: string
        example: installation
        required: false
      causal:
        type: string
        example: customer request
        required: false
      operation:
        type: string
        example: create
        required: false
