#%RAML 1.0 DataType
type: object
properties:
  originatorParty:
    type: object
    properties:
      partyOrPartyRole:
        type: object
        properties:
          name:
            type: string
            example: ABCompany
            required: false
      role:
        type: string
        example: ServiceProvider
        required: false
  relatedEntity:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          example: task-1001
          required: false
        name:
          type: string
          example: Gestión de agenda
          required: false
        status:
          type: string
          example: completed
          required: false
        completionDate:
          type: string
          example: '2025-05-29T19:10:47.078'
          required: false
        description:
          type: string
          example: >-
            Se realiza operación de [Confirmación,Reagendamiento ó Cancelación]
            de agenda
          required: false
        role:
          type: string
          example: appoimentTask
          required: false
        type:
          type: string
          example: Task
          required: false
  '@type':
    type: string
    example: ServiceProblem
    required: false
