<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="https://www.portabilidad.co/" 
    xmlns:impl="https://www.portabilidad.co/" 
    xmlns:tns="https://www.portabilidad.co/" 
    xmlns="http://schemas.xmlsoap.org/wsdl/" 
    xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<types>
  <xsd:schema elementFormDefault="qualified" targetNamespace="https://www.portabilidad.co/">
	<xsd:element name="receiveMessage">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="userId" type="xsd:string"/>
      <xsd:element name="password" type="xsd:string"/>
      <xsd:element name="xmlMsg" type="xsd:string"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="receiveMessageResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="receiveMessageReturn" type="xsd:string"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
     </xsd:schema>
 </types>
 <!-- Operation Messages -->
 <message name="receiveMessageRequest">
  <part element="tns:receiveMessage" name="parameters"/>
 </message>
 <message name="receiveMessageResponse">
  <part element="tns:receiveMessageResponse" name="parameters"/>
 </message>
 
 <portType name="ABDWebService">
  <operation name="receiveMessage">
   <input message="tns:receiveMessageRequest" />
   <output message="tns:receiveMessageResponse" />
  </operation>
 </portType>
   
 <binding name="ABDWebServiceSoapBinding" type="tns:ABDWebService">
  <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="receiveMessage">
   <wsdlsoap:operation soapAction=""/>
   <input name="receiveMessageRequest">
    <wsdlsoap:body use="literal" parts="parameters"/>
   </input>
   <output name="receiveMessageResponse">
	<wsdlsoap:body use="literal"/>
   </output>
  </operation>
 </binding>
	<service name="ABDWebServiceService">
		<port binding="impl:ABDWebServiceSoapBinding" name="ABDWebService">
			<wsdlsoap:address location="https://abd-xapi-services.us-e2.cloudhub.io/axis/services/ABDWebService"/>
		</port>
	</service>
</definitions> 