#%RAML 1.0 DataType
properties:
  eid:
    type: string
    example: "DemoETB"
  email:
    type: string
    example: "test1@test.com"
  skus:
    type: array
    items:
      properties: 
        code:
          type: string
          example: "PREDIR"
        amount:
          type: integer
          example: 1
example:
  !include ../../examples/request/delete-sku.json