#%RAML 1.0 DataType
properties:
  email:
    type: string
    example: "testing@etb.com"
  nombres:
    type: string
    example: "DemoETB Test"
  apellidos:
    type: string
    example: "Prueba Prueba"
  direccion:
    type: string
    example: "KR 7 20 00"
  municipio:
    type: string
    example: "BOGOTA D.C."
  suites:
    type: string
    example: "HOG"
  eid:
    type: string
    example: "CS-2203942"
  cuentaServicio: 
    type: string
    example: "CS-2203942"
    required: false

example:
  !include ../../examples/request/post-user.json