#%RAML 1.0 DataType
type: object
properties:
  createOrderByValueRequest:
    type: object
    properties:
      orderValue:
        type: object
        properties:
          apiClientId:
            type: string
            minLength: 1
          orderKey:
            type: object
            properties:
              applicationDN:
                type: string
                minLength: 1
              type:
                type: string
                minLength: 1
              primaryKey:
                type: string
                minLength: 1
          requestedCompletionDate:
            type: string
          services:
            type: object
            properties:
              item:
                type: object
                properties:
                  serviceKey:
                    type: object
                    properties:
                      applicationContext:
                        type: object
                        properties:
                          factoryClass:
                            type: string
                            required: false
                          url:
                            type: string
                            required: false
                          systemProperties:
                            type: string
                            required: false
                      applicationDN:
                        type: string
                        minLength: 1
                      type:
                        type: string
                        minLength: 1
                      primaryKey:
                        type: string
                        minLength: 1
                  asdlRoute:
                    type: string
                    required: false
                  serviceValues:
                    type: object
                    properties:
                      serviceValue:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                            value:
                              type: string
                              minLength: 1
                            type:
                              type: string
                              minLength: 1
          origin:
            type: string
            minLength: 1
          rollbackState:
            type: string
            minLength: 1
          processType:
            type: string
            minLength: 1
          srqAction:
            type: string
            minLength: 1
          command:
            type: string
            minLength: 1