#%RAML 1.0 DataType
properties:
  res-casos:
    type: array
    required: true
    items:
      type: object
      properties:
        id:
          type: string
          example: "500RT00000FaZz2YAF"
        cun:
          type: string
          example: ""
        consecutivo: 
          type: string
          example: "02290993"
        estado: 
          type: string
          example: "Abierto"
        asunto: 
          type: string
          example: "Registro de solicitud autoatención LEY 2300 DE 2023"
        fechaRadicacion: 
          type: string
          example: "2024-09-30"
        tipoCaso: 
          type: string
          example: "CASO PQR"
        descripcionAvance: 
          type: string
          example: ""