#%RAML 1.0 DataType
type: object
properties:
  DeliveryLTEResponse:
    type: object
    properties:
      OrderId:
        type: string
        example: "535251"
      ResponseCode:
        type: number
        example: 0
      ResponseDescription:
        type: string
        example: "ENVIADO"