#%RAML 1.0 DataType
properties:
  codigo:
    type: string
    example: "200"
  descripcionRespuesta:
    type: string
    example: "Exito"
  estadoAcuerdo:
    type: string
    example: "FINALIZADO"
  fechaHoraRespuesta:
    type: string
    example: "2024-07-12T15:30:52-05:00"
  documentosAcuerdo:
    type: array
    items:
      properties:
        idDocumento:
          type: string
        nombreDocumento:
          type: string