#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  serviceResource:
    type: array
    required: false
    items:
      type: object
      properties:
        registerLine:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-17T14:39:29.2126701Z'
              required: false
            semaphore:
              type: string
              example: Yellow
              required: false
            semaphoreDescription:
              type: string
              example: La plataforma no obtuvo resultado, no se puede validar
              required: false
        state:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-17T14:39:29.040789Z'
              required: false
            semaphore:
              type: string
              example: Green
              required: false
            semaphoreDescription:
              type: string
              example: >-
                El estado de la plataforma es 0 y de MSS es 0. No se debe
                normalizar.
              required: false
        stateProgrammed:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-17T14:39:29.0876682Z'
              required: false
            semaphore:
              type: string
              example: Red
              required: false
            semaphoreDescription:
              type: string
              example: La plataforma no obtuvo resultado
              required: false
        additionalChannels:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-15T14:00:37.9807587Z'
              required: false
            semaphore:
              type: string
              example: Green
              required: false
            semaphoreDescription:
              type: string
              example: >-
                Los canales adicionales encontrados en plataforma son los mismos
                configurados en MSS
              required: false
        additionalServices:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-15T14:00:38.0432584Z'
              required: false
            semaphore:
              type: string
              example: Green
              required: false
            semaphoreDescription:
              type: string
              example: >-
                Los servicios adicionales encontrados en plataforma son los
                mismos configurados en MSS
              required: false
        decos:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-15T14:00:37.8557634Z'
              required: false
            semaphore:
              type: string
              example: Green
              required: false
            semaphoreDescription:
              type: string
              example: >-
                Los MACs encontrados en plataforma son los mismos configurados
                en MSS
              required: false
        subscriberIdState:
          type: object
          required: false
          properties:
            executionDate:
              type: string
              example: '2025-09-15T14:00:38.4807578Z'
              required: false
            semaphore:
              type: string
              example: Green
              required: false
            semaphoreDescription:
              type: string
              example: >-
                El estado en la plataforma es 1 y en MSS es 1. No requiere
                normalización
              required: false
        service:
          type: object
          required: false
          properties:
            billingAccount:
              type: string
              example: '100123456789'
              required: false
            phone:
              type: string
              example: '6018009578'
              required: false
            plan:
              type: string
              example: FIBRA_300_SIMETRICO
              required: false
            serviceAccount:
              type: string
              example: SA-100123456789
              required: false
            technology:
              type: string
              example: FTTH
              required: false
        equipments:
          type: array
          required: false
          items:
            type: object
            properties:
              acsModel:
                type: string
                example: ALCL_BGW320
                required: false
              brand:
                type: string
                example: ALCATEL
                required: false
              firmware:
                type: string
                example: 3.2.1.45
                required: false
              isDual:
                type: boolean
                example: true
                required: false
              mac:
                type: string
                example: 00:1A:2B:3C:4D:5E
                required: false
              model:
                type: string
                example: BGW320-500
                required: false
              networks:
                type: array
                items:
                  type: object
                  properties:
                    acsModel:
                      type: string
                      example: WIFI_BGW320_2G
                      required: false
                    dual:
                      type: boolean
                      example: false
                      required: false
                    firmware:
                      type: string
                      example: 3.2.1.45
                      required: false
                    isAvailableSetNetworkName:
                      type: boolean
                      example: true
                      required: false
                    isAvailableSetNetworkPassword:
                      type: boolean
                      example: true
                      required: false
                    isAvailableSetNetworkWifi:
                      type: boolean
                      example: true
                      required: false
                    networkName:
                      type: string
                      example: ETB_WiFi_2.4GHz
                      required: false
                    networkPassword:
                      type: string
                      example: MiClaveSegura2024
                      required: false
                    networkType:
                      type: string
                      example: '2.4'
                      required: false
                    networkStatus:
                      type: string
                      example: Encendido
                      required: false
              serial:
                type: string
                example: ALCLB545275C
                required: false
              status:
                type: string
                example: Encendido
                required: false
              type:
                type: string
                example: ONT
                required: false
              typeModem:
                type: string
                example: Modem
                required: false
