<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:open="http://www.openuri.org/" xmlns:tec="http://com/tecnocom">
   <soapenv:Header/>
   <soapenv:Body>
      <open:doConsultarNumerosDisponibles>
         <tec:PeticionNumerosDisponibles>
            <tec:Categoria>?</tec:Categoria>
            <tec:CodigoPais>?</tec:CodigoPais>
            <tec:CodigoDepartamento>?</tec:CodigoDepartamento>
            <tec:CodigoMunicipio>?</tec:CodigoMunicipio>
            <tec:Distrito>?</tec:Distrito>
            <tec:NumeroActual>?</tec:NumeroActual>
            <tec:TecnologiaDestino>?</tec:TecnologiaDestino>
            <tec:IdCuentaServicio>?</tec:IdCuentaServicio>
            <tec:NumeroEspecifico>?</tec:NumeroEspecifico>
         </tec:PeticionNumerosDisponibles>
      </open:doConsultarNumerosDisponibles>
   </soapenv:Body>
</soapenv:Envelope>