#%RAML 1.0 NamedExample
value:
  GetCoverageGISOPInput:
    WSRequestHeader2:
      System:
        correlationID: "MDM-FIBRA-006183400"
    GetCoverageGISRequest:
      Latitud: "4.653928605"
      Longitud: "-74.06588058"