# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================

# --- Example Backend HTTP Requester ---
directv:
  token:
    basic: "![X+f0uUmTKwgMgJZatS/BCYAgKf+LXLfboMVJ/KnapIpu7Sr4JnaIFZGNhLGzC3AW3Jhcgbdtkqs0lHG9tnnhQ0Syd5AmCI9l/mgCLaQmRW/BDWFV0cnFdOUFASfWXnBu]"