#%RAML 1.0 DataType 
type: object
properties:
  id:
    type: string
    example: '1234'
    required: false
  name:
    type: string
    example: Name
    required: false
  packageInstance:
    type: object
    properties:
      id:
        type: string
        example: '1234'
        required: false
      name:
        type: string
        example: Name
        required: false
      links:
        type: array
        items:
          type: object
          properties:
            rel:
              type: string
              example: string
              required: false
            href:
              type: string
              example: string
              required: false
            hreflang:
              type: string
              example: string
              required: false
            media:
              type: string
              example: string
              required: false
            title:
              type: string
              example: string
              required: false
            type:
              type: string
              example: string
              required: false
            deprecation:
              type: string
              example: string
              required: false
            profile:
              type: string
              example: string
              required: false
            name:
              type: string
              example: string
              required: false
  status:
    type: string
    example: ACTIVE
    required: false
  scope:
    type: string
    example: NETWORK
    required: false
  renewable:
    type: boolean
    example: true
    required: false
  renewalCount:
    type: integer
    example: 5
    required: false
  promotion:
    type: boolean
    example: true
    required: false
  startDate:
    type: datetime
    example: '2022-04-20T10:13:15.686Z'
    required: false
  origStartDate:
    type: datetime
    example: '2022-04-20T10:13:15.686Z'
    required: false
  terminationDate:
    type: datetime
    example: '2022-04-20T10:13:15.686Z'
    required: false
  chargingLimitValueOrig:
    type: number
    example: 35.2
    required: false
  chargingLimitValue:
    type: number
    example: 35.2
    required: false
  chargingLimitValueRenewal:
    type: number
    example: 35.2
    required: false
  trafficLimitValueOrig:
    type: number
    example: 35.2
    required: false
  trafficLimitValue:
    type: number
    example: 35.2
    required: false
  trafficLimitValueRenewal:
    type: number
    example: 35.2
    required: false
  additionalLimits:
    type: number | number[]
    example: 35.2
    required: false
  type:
    type: string
    example: BONUS
    required: false
  category:
    type: string
    example: VOICE
    required: false
  childs:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          example: '1234'
          required: false
        name:
          type: string
          example: Name
          required: false
        links:
          type: array
          items:
            type: object
            properties:
              rel:
                type: string
                example: string
                required: false
              href:
                type: string
                example: string
                required: false
              hreflang:
                type: string
                example: string
                required: false
              media:
                type: string
                example: string
                required: false
              title:
                type: string
                example: string
                required: false
              type:
                type: string
                example: string
                required: false
              deprecation:
                type: string
                example: string
                required: false
              profile:
                type: string
                example: string
                required: false
              name:
                type: string
                example: string
                required: false
  global:
    type: string
    example: CREDIT_LIMIT
    required: false
  chargingLimitValueOnRenewal:
    type: number
    example: 35.2
    required: false
  trafficLimitValueOnRenewal:
    type: number
    example: 35.2
    required: false
  links:
    type: array
    items:
      type: object
      properties:
        rel:
          type: string
          example: string
          required: false
        href:
          type: string
          example: string
          required: false
        hreflang:
          type: string
          example: string
          required: false
        media:
          type: string
          example: string
          required: false
        title:
          type: string
          example: string
          required: false
        type:
          type: string
          example: string
          required: false
        deprecation:
          type: string
          example: string
          required: false
        profile:
          type: string
          example: string
          required: false
        name:
          type: string
          example: string
          required: false
