#%RAML 1.0 DataType
properties:
  CantidadLineasActivasPre:
    type: number
    example: 0
  CantidadLineasInactivasPre:
    type: number
    example: 0
  CantidadLineasActivasPos:
    type: number
    example: 1
  CantidadLineasInactivasPos:
    type: number
    example: 0
  TotalLineasPre:
    type: number
    example: 0
  TotalLineasPos:
    type: number
    example: 1
  Respuesta:
    type: string
    example: "true"
  Mensaje:
    type: string
    example: "Cliente valido. **Validar si el cliente tiene ordenes en curso para cancelar o retomar."
  Codigo:
    type: string
    example: "000"
  TotalLineasPreParametro:
    type: number
    example: 3
  TotalLineasPosParametro:
    type: number
    example: 5
  TotalLineasPreVuelo:
    type: number
    example: 0
  TotalLineasPosVuelo:
    type: number
    example: 0