http:
  listener:
    protocol: "HTTPS"
    host: "0.0.0.0"
    port: "8082"
    readTimeout: "30000"

autodiscovery: ""

oauth:
  provider:
    rateLimiter:
      duration: "600"
      maxFailures: "5"

    grantTypes: "CLIENT_CREDENTIALS"

    token:
      path: "/v2/oauth/token"
      ttl: "86400"

objectstore:
  token:
    maxEntries: "10000"
    entryTtl: "0"
    expirationInterval: "1"

  client:
    maxEntries: "10000"
    entryTtl: "0"
    expirationInterval: "1"
    
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"