envName: "Production"

app:
  apiId: ""
  listener:
    host: "0.0.0.0"
    port: "8091"
    basePath: ""
  
payu:
  accountId: ""
  merchantId: ""
  apiLogin: ""
  apiKey: ""
  publicKey: ""
  endpoint: "api.payulatam.com"
  language: "es"
  test: "true"
  paymentMethod: "PSE"
  paymentCountry: "CO"
  type: "AUTHORIZATION_AND_CAPTURE"