#%RAML 1.0
title: ETB Customer Experience API
version: v2
baseUri: https://customer-xapi-services-{env}.us-e2.cloudhub.io/{version}
description: |
  **ETB Customer Experience API - Comprehensive Customer Management**

traits:
  tibcoHeaders: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml

mediaType: 
  - application/json

securitySchemes:
  etb_oauth_2_0: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

/customer360:
  get:
    is:
     - tibcoHeaders
    securedBy: [etb_oauth_2_0]
    displayName: getCustomer360
    description: view customer
    queryParameters:
      fields:
        type: array
        required: false
      documentNumber:
        type: string
        example: "12552454"
        description: Official identification number of the customer, such as ID card, passport, or tax ID.
        required: true
      documentType:
        type: string
        enum: ["CC","CE","PASAPORTE","NIT","RUT","TI"]
        example: "CC"
        description: Type of official document used for customer identification, such as ID card, passport, or tax certificate.
        required: true
      limit:
        type: number
        description: Specifies the maximum number of items to return in the response
        default: 10
        required: false
        example: 10
    responses:
        200:
          body:
            application/json:
              type: !include /datatypes/response/get-customer-360.raml
              example: !include /examples/response/get-customer.json
        400:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-400.json
        401:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-401.json
        404:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-404.json
        500:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-500.json

/customer:
  get:
    is: 
     - tibcoHeaders
    securedBy: [etb_oauth_2_0]
    displayName: getCustomer
    description: view customer 
    queryParameters:
        ORIGIN:
          type: string
          example: "WHATSAPP"
          description: Parameter that allows the origin of the request to be identified
        CUSTOMER_ID:
          type: string
          example: "12552454"
          description: Customer identification number can be ID card or tax ID number
          required: false
        CUSTOMER_ID_TYPE:
          type: string
          enum: ["CC","CE","PASAPORTE","NIT","RUT","TI"]
          example: "CC"
          description: Type of customer identification document
          required: false
        FILTERS:
          type: string
          example: "MobilePhone:3222233322;Phone:542545454;AccountNumber:12452145"
          description: String used to apply filters to the query (follow example), separate the filter type and its value with a colon, and separate the number of filters with a semicolon.
          required: false
        LIMIT:
          type: number
          description: Limit on orders to display
          required: false
        OFFSET:
          type: string
          description: used to organize information and establish a logical order
          required: false
    responses:
          200:
            body:
              application/json:
                type: !include /datatypes/response/get-customer.raml
                example: !include /examples/response/get-customer.json    
          400:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-400.json
          401:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-401.json
          404:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-404.json
          500:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-500.json
                
                
/payment/{paymentMethod}:
  uriParameters:
    paymentMethod:
      type: string
      required: true
      description: "Identificador de la pasarela de pagos"
      example: "pse"
  /banks:
    get:
      is: 
        - tibcoHeaders
      securedBy: [etb_oauth_2_0]
      displayName: Get payment banks
      description: Get payment banks
      responses:
        200:
          body:
            application/json:
              example: !include examples/response/pseBanks.json
  /payment:
    post:
      is: 
        - tibcoHeaders
      securedBy: [etb_oauth_2_0]
      displayName: Create payment transaction
      description: Create payment transaction
      body:
        application/json:
          type: object
          example: !include examples/request/post-transactionPSE.json
      responses:
        201:
          body:
            application/json:
              example: !include examples/response/post-transactionPSE.json
    /{paymentId}:
      get:
        is: 
          - tibcoHeaders
        securedBy: [etb_oauth_2_0]
#        queryParameters:
#          origin:
#            type: string
#            enum:
#              - platform
#              - etb
#            example: "etb"
#            required: false
#            default: "etb"
        displayName: Get transaction By Id
        description: Get transaction By Id
        responses:
          200:
            body:
              application/json:
      patch:
        is: 
          - tibcoHeaders
        securedBy: [etb_oauth_2_0]
        displayName: Update payment transaction
        description: Update payment transaction
        body:
          application/json:
            type: object
            example: !include examples/request/patch-payment-transaction.json
        responses:
          201:
            body:
              application/json:
