#%RAML 1.0
title: common-papi-services
baseUri:  https://common-papi-services-{env}.us-e2.cloudhub.io
description: Capa de proceso para gestion de operaciones comunes

types:
  error-response: !include datatypes/response/error.raml
  geographicAddress: !include datatypes/response/geographicAddress.raml

/geographicAddressManagement:
  /v1:
    /geographicAddress:
      /{operation}:
        uriParameters:
          operation:
            type: string
            enum: ["complements"]
            required: true
            example: "complements"
        ##is: [request_headers]
        get:
          description: |
            Retornar información de complementos asociados a una dirección actual
          queryParameters:
            address:
              type: string
              required: true
              description: Dirección actual
              example: "AK 45 108A 50"
            cityId:
              type: number
              required: true
              description: Codigo de municipio o ciudad
              example: 11001
            limit:
              type: number
              required: false
              description: Limite de complementos consultados
              example: 10
          responses:
            200:
              body:
                application/json:
                  type: geographicAddress
                  example: !include examples/response/geographicAddress-complements.json
            400:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-400.json
            401:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-401.json
            404:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-404.json
            500:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-500.json
      /coverage:
        ##is: [request_headers]
        get:
          displayName: Obtain coverage with latitude and longitude
          description: Returns information about about coverage using the information provided
          queryParameters:
            latitude:
              description: Geo latitude
              example: 4.671486484
              type: number
              required: true
            longitude:
              description: Geo longitude
              example: -74.06268689
              type: number
              required: true
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/coverageResponse.raml
                  example: !include examples/response/coverageResponse.json
            400:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-400.json
            401:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-401.json
            404:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-404.json
            500:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-500.json
      /geocodificar:
        ##is: [request_headers]
        get:
          displayName: Geocodify address using Smallworld SAPI
          description: Geocodifies an address using the Smallworld SAPI to get coordinates and additional location information
          queryParameters:
            address:
              type: string
              required: true
              description: Dirección a geocodificar
              example: "Carrera 11 67A 40 SUR"
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/geocodificarResponse.raml
                  example: !include examples/response/geocodificarResponse.json
            400:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-400.json
            401:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-401.json
            404:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-404.json
            500:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-500.json
      /georeference:
        ##is: [request_headers]
        get:
          displayName: Georeference address using Smallworld SAPI (SISEXT)
          description: Georeferences an address using SmallWorld SISEXT to get coordinates and normalized address
          queryParameters:
            address:
              type: string
              required: true
              description: Dirección a georreferenciar
              example: "CL 20 30 40"
            municipioCode:
              type: string
              required: true
              description: Código de municipio
              example: "11001"
            departamentoCode:
              type: string
              required: false
              description: Código de departamento
              example: "11"
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/georeferenceResponse.raml
                  example: !include examples/response/georeferenceResponse.json
            400:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-400.json
            401:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-401.json
            404:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-404.json
            500:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-500.json
      /geoAddress:
        ##is: [request_headers]
        post:
          displayName: manageGeoaddress
          description: Manage a geographic address in the system
          body:
            application/json:
              type: !include datatypes/request/geoDireccionRequest.raml
              example: !include examples/request/geoDireccionRequest.json
          responses:
            201:
              body:
                application/json:
                  type: !include datatypes/response/geoDireccionResponse.raml
                  example: !include examples/response/geoDireccionResponse.json
            400:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-400.json
            401:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-401.json
            500:
              body:
                application/json:
                  type: error-response
                  example: !include examples/response/error-500.json
          
    /geographicCoverage:
      get:
        description: |
          Permite consultar la cobertura de la direccion normalizada o coordenadas enviadas TMF675 v4
        queryParameters:
          address:
            type: string
            required: false
            description: Dirección a consultar
            example: "DG 159B 14A 40 IN 21"
          municipality:
            type: string
            required: false
            description: Código de Municipio asociado a la dirección
            example: "11001"
          departament:
            type: string
            required: false
            description: Código de departamento asociado a la dirección
            example: "11"
          latitude:
            type: string
            required: false
            description: Latitud asociada a la ubicacion geografica
            example: "4.653928605"
          longitude :
            type: string
            required: false
            description: Longitud asociada a la ubicacion geografica
            example: "-74.06588058"
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/coverageResponse.raml
                example: !include examples/response/coverageResponse.json
          400:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-400.json
          401:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-401.json
          404:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-404.json
          500:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-500.json
    /normalizeAddress:
      ##is: [request_headers]
      get:
        description: |
          Permite consultar direcciones vecinas luego de normalizar y georreferenciar, aplicando manejo de mensajes 
          de acuerdo con el estándar TMF673 v4
        queryParameters:
          address:
            type: string
            required: true
            description: Dirección a estandarizar
            example: "Diagonal  159B 14a 40 int 21"
          municipalityCod:
            type: string
            required: true
            description: Código de Municipio asociado a la dirección
            example: "11001"
          departamentCod:
            type: string
            required: true
            description: Código de departamento asociado a la dirección
            example: "11"
        responses:
          200:
            body:
              application/json:
                type: geographicAddress[]
          400:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-400.json
          401:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-401.json
          404:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-404.json
          500:
            body:
              application/json:
                type: error-response
                example: !include examples/response/error-500.json         
                           
      