credentials:
  client_id: "![9eMe94MhTKbQ5Hxg3Oa+Lh0EQ9DOxi8FSN7np9jJinJoKJMnpH1zuQ==]"
  client_secret: "![jFeoRrRVc0XCzRkfwHn7tJWOoDRbNecvE6doiizpYSvQDlBayo5rUA==]"

tls:
  keyPassword: "![ogSvSOVln/m/oZinVXHSOw==]"
  password: "![ogSvSOVln/m/oZinVXHSOw==]"