# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================

# --- API Client Credentials ---
api:
  clientId: "![9eMe94MhTKbQ5Hxg3Oa+Lh0EQ9DOxi8FSN7np9jJinJoKJMnpH1zuQ==]"
  clientSecret: "![jFeoRrRVc0XCzRkfwHn7tJWOoDRbNecvE6doiizpYSvQDlBayo5rUA==]"

# --- TLS Context ---  
tls:
  keyPassword: "![ogSvSOVln/m/oZinVXHSOw==]"
  password: "![ogSvSOVln/m/oZinVXHSOw==]"