https:
  host: "0.0.0.0"
  port: "443"
  
autodiscovery: "18058268"

global:
  inactivo: "INACTIVO"
  migrado: "MigradoMVNE"

configurationTimeout:
  asap-sapi: "92000"
  lisim-sapi: "122000"
  operation-papi: "72000"
  billing-papi: "62000"
  sisext-sapi: "62000"
  remedy-sapi: "62000"
  etb-mdm-sapi: "62000"
  revchain-sapi: "62000"
  oracle-sapi: "62000"
  portal-movilidad-sapi: "62000"
  service-papi: "62000"
  support-papi: "62000"
  mongo-sapi: "62000"
  
etb-mdm-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-etb-mdm-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mdm"
  tramits:
    path: "/v1/tramits"
  transferService:
    path: "/v1/notifyTransferService"
    serviceAction: "transfer"
    serviceTransferType: "0"
  trasladoServiciosCuentaClienteyFacturacion:
    path: "/v1/trasladoServiciosCuentaClienteyFacturacion"
  queryTramits:
    path: "/v1/tramits/newQuery"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
salesforce-xapi:
  basePath: "/salesforce/*"  

operation-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/operations/v1"
  path-productOrder: "/productOrder"
  path-viability: "/viability"
  path-provisioning: "/provisioning"
  source: "salesforce-xapi-services"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
billing-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-billing-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/billing"
  path:
    billing-accounts: "v1/billing_accounts"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
lisim-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-lisim-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/lisim"
  scoring:
    path: "/v1/scoring"
    
asap-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-asap-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/asap/v1"
  path:
    provisioning: "/publish"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  environment: "PROD"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
sisext-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/sisext/v1"
  connectionNumber:
    path: "/billings/{connection-number}/details"
  negativeRecord:
    path: "/negativeRecord"
  fraudQuery:
    path: "/fraudQuery"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
remedy-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-remedy-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/remedy"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  updateEntIncidentStatus:
    path: "/v1/incident/{incidence_id}"
  createEnterpriseIncident:
    path: "/v1/incident/enterprise"
  enterpriseRequest: 
    path: "/v1/enterprise/request"
  consultTaskArray:
    path: "/v1/incident/{incidence_id}/tasks"
  createIncidentNote:
    path: "/v1/incident/note"
  createNewTask:
    path: "/v1/incident/{incidence_id}/tasks"
  createRequestNote:
    path: "/v1/request/note"
  createSchedule:
    path: "/v1/schedule"
    
revchain-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-revchain-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: 
    version: "/revchain/v1"
  path:
    serviceProvisioning: "/billing/provisioning/services"
    numberAndPrice: "/numberAndPrice"
    billingAdjustment: "/billingAdjustment"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
portal-movilidad-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-portal-movilidad-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/movilidad"
  availabilityQueryOrder: 
    path: "/v1/availabilityQueryOrder"

availabilityQueryOrder:
  channel: "PORTAL MOVILIDAD"
  category: "NUMEROS ASIGNABLES"
  operation: "RESERVAR"
  subcategory: "NUMERACION MDM"

oracle-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/oracle/v1"
  path:
    homologation: "/homologation/{genericValue}/{catalog}"
  catalogs:
    catalogAQO: "CT21AQO"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
 
credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

  
service-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-service-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/services/v1"
  path:
    cambioSuscriptorLTECorp: "/cambioSuscriptorLTECorp"
    provisioningLTECorp: "/provisioningLTECorp"
    serviceManagement: "/apnPrivadoALineaLTE"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
support-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-support-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/support"
  delivery:
    path: "/v1/delivery"
  cun:
    path: "/v1/cun"
  imei:
    path: "/v1/imei"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  basepath: "/mongo"
  path:
    active-service: "/v1/active-service"