#%RAML 1.0 DataType
type: object
properties:
  TX_VALUE:
    type: object
    properties:
      value: number
      currency: string
  TX_TAX:
    type: object
    properties:
      value: number
      currency: string
  TX_TAX_RETURN_BASE:
    type: object
    properties:
      value: number
      currency: string