#%RAML 1.0
title: etb-mdm-sapi-services
baseUri: http://etb-mdm-sapi-services-dev.us-e2.cloudhub.io/mdm
description: 
mediaType: 
  - application/json
protocols:
  - HTTP

traits:
  security-client-id: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  tibcoHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.5/tibcorequestheaders.raml

uses:
  definitions: libraries/library.raml
  portability-lib: libraries/portability-library.raml
  
  


/v1:
  /pqr:
    /details:
      post:
        is:
          - security-client-id
          - tibcoHeaders
        displayName: Consult PQR
        description: Service to consult PQR
        body:
          application/json:
            type: !include datatypes/request/consultPQR.raml
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/consultPQR200.raml
          404:
            body:
              application/json:
                type: !include datatypes/response/consultPQR404.raml
    /notes:
      post:
        is:
          - security-client-id
          - tibcoHeaders
        displayName: Insert PQR Notes
        description: Service to insert notes PQR
        body:
          application/json:
            type: !include datatypes/request/pqrNotes.raml
        responses:
          200:
            body:
              application/json:
                type: !include /datatypes/response/pqrNotes.raml
    /massiveFailure: 
      post: 
        is: 
          - security-client-id 
          - tibcoHeaders 
        displayName: Register Massive PQR Failure 
        description: Service to register massive PQR failures 
        body: 
          application/json: 
            type: !include datatypes/request/pqrMassiveFailure.raml 
        responses: 
          200: 
            body: 
              application/json: 
                type: !include /datatypes/response/pqrMassiveFailure.raml
  /registerLog:
    post:
      is:
        - security-client-id
        - tibcoHeaders
      displayName: Register log to mdm
      description: 
      body:
        application/json:
          type: !include datatypes/request/registerLog.raml
          example: !include examples/request/registerLog.json
      responses:
        201:
          body:
            application/json:
                type: !include datatypes/response/registerLogResponse.raml
                example: !include examples/response/registerLogResponse.json
        202:
          body:
            application/json:
              example: !include examples/response/registerLogUnsuccessfulResponse.json
  /technician:
    patch:
      is:
        - security-client-id
        - tibcoHeaders
      displayName: Update Technician Remedy Intf
      description: 
      body:
        application/json:
          type: !include datatypes/request/updateTechnicianRemedyIntf.raml
      responses:
        202:
          body:
            application/json:
              {}
        504:
          body:
            application/json:
              type: !include datatypes/response/updateTechnicianRemedyIntf.raml
              example: !include examples/response/updateTechnicianRemedyIntf.raml
  /tramits:
    post:
      is: [tibcoHeaders, security-client-id]
      displayName: Register tramit
      description: Register tramit
      body:
        application/json:
            type: !include datatypes/request/registerTramitsType.raml
      responses:
        201:
          body:
            application/json:
              type: !include datatypes/response/registerTramitsResponse.raml
              example: !include examples/response/registerTramits201Example.raml
        202:
          body:
            application/json:
              type: !include datatypes/response/registerTramitsResponse.raml
              example: !include examples/response/registerTramits202Example.raml
    /newQuery:
      post:
        is: [security-client-id, tibcoHeaders] 
        displayName: Query tramits to siebel
        description: Service to send query tramits to siebel
        headers:
          sourceSystem:
            type: string
            example: "Siebel_NPLAY"
            required: true
            minLength: 1
          checkOrderHistory:
            type: boolean
        body: 
          application/json:
            type: !include datatypes/request/queryTramitsRequest.raml
            example: !include examples/request/tramitsRequest.json
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/queryTramitsResponse.raml
                example: !include examples/response/tramitsResponse.json
          202:
            body:
              application/json:
                type: !include datatypes/response/queryTramitsResponse.raml
                example: !include examples/response/tramitsResponse202.json
  /outboundETAdirect:
    post:
      is: [security-client-id, tibcoHeaders]
      displayName: Outbound ETA Direct
      description: Outbound ETA Direct
      body:
        application/json:
          type: !include datatypes/request/post-outboundEtaDirect.raml
      responses:
        201:
          body:
            application/json:
              type: !include datatypes/response/post-outboundEtaDirect.raml
  /trasladoServiciosCuentaClienteyFacturacion:
    post:
      is:
        - security-client-id
        - tibcoHeaders
      displayName: Notify Transfer Service Client Account and Billing
      description: Sends notification to SUMA
      body:
        application/json:
          type: !include datatypes/request/trasladoServiciosCuentaClienteyFacturacion.raml
      responses:
        200:
          body:
            application/json:
                example: !include examples/response/trasladoServiciosCuentaClienteyFacturacion.json
  /orders:
    /orderStatus:
      patch:
        is: [security-client-id,tibcoHeaders]
        body:
          application/json:
            type: !include datatypes/request/updateOrderStatus.raml
        responses:
          201:
            description: update order status returned by the method
            body:
              application/json:
                example:
                  !include /examples/response/updateOrderStatusResponse.json
          500:
            description: Response for the status 500 of the update
            body:
              application/json:
                example: !include examples/response/updateOrderStatusError.json
    /{order_id}:
      /characteristics:
        uriParameters:
          order_id:
            type: string
            example: "MDM-FIBRA-000558582"
        post:
          is:
            - security-client-id
            - tibcoHeaders
          displayName: Update order characteristics
          description: Update the characteristics from an order
          body:
            application/json:
              type: !include datatypes/request/updateOrderCharacteristics.raml
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/updateOrderCharacteristics.raml                
  /inventory:
    /{id_inventory}:
      /details:
        uriParameters:
          id_inventory:
            type: string
            minLength: 1
            example: "5dd5ed1f1a2eaf110c0ded1e"
        get:
          is: [security-client-id, tibcoHeaders]
          displayName: Consult inventory detail
          description: Service that returns inventory details.
          queryParameters:
            id_transaction:
              type: string
              required: false
              example: "Remedy"
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/consultInventoryDetail.raml
                  example: !include examples/response/consultInventoryDetail200.raml
              
  /portability:
    post:
      is:
        - security-client-id
        - tibcoHeaders
      displayName: Notify an update in portability process.
      description: This method notify an update in the portability process.
      body:
        application/json:
          type: portability-lib.portabilityRequest
      responses:
        201:
          body:
            application/json:
              type: !include datatypes/response/notifyPortabilityUpdateIntfResponse.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/notifyPortabilityUpdateIntfErrorResponseType.raml
    /idMessage:
      get:
        is: [security-client-id, tibcoHeaders]
        displayName: Get Portability id Message
        description: Get Portability id Message
        responses:
          201:
            body:
              application/json:
                example: { "status": "OK", "consecutivo":"00007202407270000005" }
    /idProcess:
      get:
        is: [security-client-id, tibcoHeaders]
        displayName: Get Portability id Process
        description: Get Portability id Process
        responses:
          201:
            body:
              application/json:
                example: { "status": "OK", "consecutivo":"00007202407270000005" }
  /billing:
    /notification:
      post:
        is: 
          - security-client-id
          - tibcoHeaders
        displayName: NotifyBillToMDM
        description: Invoice notification to MDM SOAP input
        body:
          application/json:
            type: !include datatypes/request/post-NotifyBillToMDM.raml
        responses:
          201:
            body:
              application/json:
                type: !include datatypes/response/post-NotifyBillToMDM.raml
  /process:
    post:
      is:
        - security-client-id
        - tibcoHeaders
      displayName: Process
      description: Process Order
      body:
        application/json:
          type: !include datatypes/request/processRequestType.raml
          example: !include examples/request/processRequestExample.json   
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/processResponseTypes.raml
              example: !include examples/response/processResponseExample.json
        500:
          body:
            application/json:
              type: !include datatypes/response/processResponseTypes500.raml
              example: !include examples/response/processResponseExample500.json