#%RAML 1.0 DataType
type:  
  properties:
    import:
      properties:
        BUSINESSPARTNEREXTERN?:
          properties:
              BU_TYPE?:                   
                example : "2"
              BPKIND?:                    
                example : "0003"
              BPEXT?:                    
                example : "a054y00000lClQhAAK"
              SEARCHTERM1?:                    
                example : "860002503"
              TITLE_KEY?:                    
                example : "0003"
              BUPINFOREL?:                    
                example : "2"

        CENTRALDATA_ORGAN?:
          properties:
            NAME_ORG1?:
              example: "COMPAIA DE SEGUROS BOLIVAR TRONCAL SIP M"

        CTRACCREATEINFO?:
          properties:
            LEGACY_ACCT?:
              example: "12054124652"
            BPEXT?:
              example: "a054y00000lClQhAAK"
            ACCT_NAME?:
              example: "COMPAIA DE SEGUROS BOLIVAR TRONCAL"
              
        SEL_CONTROL?:
          properties:            
            ID_TRS?:
              example : "C"
            OBJETO?: 
              example: "BP"
            CICLO?: 
              example: "96"
         
        CENTRALDATA_PERSON?:
          properties:
            NAME_FIRST?:
              example : ""
            LASTNAME?:
              example : ""
            XSEXU?: 
              example : ""
            NATIO?: 
              example : "CO"
    tables:
      properties:
        CTRACPARTNERDETAIL?:
          properties:
            row?:
              properties:
                EXVKO?:
                  example: "a054y00000lClQhAAK"
                KTOKL?:
                  example: "0005"
                EXTADDRESSNUMBER?:
                  example: "a054y00000lClQhAAK"
        DIRECCIONES?:
          properties:
            row?:
              properties:
                CITY1?:
                  example: "BOGOTÁ, D.C."
                REGION?:
                  example: "11"
                STREET?:
                  example: "KR 10 28 49 TO A PI 4"
                COUNTRY?:
                  example: "CO"
                LANGU?:
                  example: "S"
                EXTADDRESSNUMBER?:
                  example: "a054y00000lClQhAAK"
        IDENTIFICACION?:
          properties:
            row?:
              properties:
                IDENTIFICATIONCATEGORY?: 
                  example: "Z0007"
                IDENTIFICATIONNUMBER?:
                  example: "860002503"
        TELEFONOS?:
          properties:
            row?:
              properties:
                EXTADDRESSNUMBER?: 
                  example: "a054y00000lClQhAAK"
                TELEPHONE?:  
                  example: "13410077"
                TIPO?: 
                  example: "0"

        USO_DIRECCIONES?:
          properties:
            row?:
              properties:
                EXTADDRESSNUMBER?: 
                  example: "a054y00000lClQhAAK"
                ADDRESSTYPE?:  
                  example: "0003"
        
