#%RAML 1.0 DataType
type: 
  properties:
    import:
      properties:
        I_BUKRS:
          type: string
          required: true
        I_EDATE:
          type: string
          required: false
        I_LIFNR:
          type: string
          required: false
        I_SDATE:
          type: string
          required: false
        I_SESID:
          type: string
          required: false
        I_STCD1:
          type: string
          required: false
        I_STCD1_EXPO:
          type: string
          required: false
        I_WAERS:
          type: string
          required: false
        I_XMODE:
          type: string
          required: false
    tables:
      properties:    
        T_BAPIRET:
          properties:
           row:
              required: false
              properties:
                TYPE:
                  type: string
                  required: true
                ID:
                  type: string
                  required: true
                NUMBER:
                  type: string
                  required: true
                MESSAGE:
                  type: string
                  required: true
                LOG_NO:
                  type: string
                  required: true
                LOG_MSG_NO:
                  type: string
                  required: true
                MESSAGE_V1:
                  type: string
                  required: true
                MESSAGE_V2:
                  type: string
                  required: true
                MESSAGE_V3:
                  type: string
                  required: true
                MESSAGE_V4:
                  type: string
                  required: true
                PARAMETER:
                  type: string
                  required: true
                ROW:
                  type: string
                  required: true
                FIELD:
                  type: string
                  required: true
                SYSTEM:
                  type: string
                  required: true
    T_DATA_ADD:
      required: false
      properties:
        row:
          required: false
          properties:
            XBLNR:
              type: string
              required: true
            CONCEPTO:
              type: string
              required: true
            WRBTR:
              type: string
              required: true
            WAERS:
              type: string
              required: true
    T_SOLFACT:
      required: false
      properties:
         row:
          required: false
          properties:
            BUKRS:
              type: string
              required: true
            STCD1:
              type: string
              required: true
            NAME1:
              type: string
              required: true
            STRAS:
              type: string
              required: true
            TELF1:
              type: string
              required: true
            XBLNR:
              type: string
              required: true
            SKFBT:
              type: string
              required: true
            SHKZG:
              type: string
              required: true
            NETWR:
              type: string
              required: true
            WAERK:
              type: string
              required: true
            BUDAT:
              type: string
              required: true
            NETDT:
              type: string
              required: true
            ZFBDT:
              type: string
              required: true
            BLDAT:
              type: string
              required: true
            BSCHL:
              type: string
              required: true
            BELNR:
              type: string
              required: true
            BUZEI:
              type: string
              required: true
            GJAHR:
              type: string
              required: true              
   