#%RAML 1.0 DataType
properties:
  ZRFC_BP_UPDATE_DATA:
    type: object
    properties:
      COUNTRY:
        type: string 
        example: "CO"
      CTA_REVCHAIN:
        type: string 
        example: "15052904684"
      E_MAIL:
        type: string 
        example:  "nicolpineda1712@gmail.com"
      FIRSTNAME:
        type: string 
        example:  "CRISTIAM ALEJANDRO"
      LASTNAME: 
        type: string 
        example: "FAJARDO"
      RETURN?: 
        type: any
        example: null
      STREET: 
        type: string 
        example: "CL 83 BIS 23 47 AP 102"