#%RAML 1.0 DataType

description: Respuesta de recarga de saldo
type: object
properties:
  id:
    type: string
    description: Identificador de la cuenta de facturación / transacción
    example: "12345"
  status:
    type: string
    description: Estado del resultado
    example: "Successful"
