#%RAML 1.0 DataType
type: object
xml:
  name: Envelope
  wrapped: true
  prefix: soap
  namespace: http://schemas.xmlsoap.org/soap/envelope/
properties:
  Header:
    type: nil
    required: false
    xml:
      prefix: soap
      namespace: http://schemas.xmlsoap.org/soap/envelope/
  Body:
    type: object
    xml:
      prefix: soap
      namespace: http://schemas.xmlsoap.org/soap/envelope/
    properties:
      WebHook:
        type: object
        required: false
        properties:
          Id:
            xml:
              attribute: true
          Url:
            xml:
              attribute: true
          FechaHora:
            xml:
              attribute: true
          Cuenta:
            type: object
            properties:
              Id:
                xml:
                  attribute: true
              Nombre:
                xml:
                  attribute: true
          Ambito:
            type: object
            required: false
            properties:
              Id:
                xml:
                  attribute: true
              Nombre:
                xml:
                  attribute: true
              Grupo:
                type: object
                properties:
                  Id:
                    xml:
                      attribute: true
                  Nombre:
                    xml:
                      attribute: true
          Evento:
            type: object
            required: false
            properties:
              Id:
                xml:
                  attribute: true
              Nombre:
                xml:
                  attribute: true
              FechaHora:
                xml:
                  attribute: true
          AcuerdoInfo:
            type: object
            required: false
            properties:
              Id:
                xml:
                  attribute: true
              Nombre:
                xml:
                  attribute: true
              RefWebHook:
                xml:
                  attribute: true
              FechaHora:
                xml:
                  attribute: true
              UrlPostFirma:
                xml:
                  attribute: true
              FechaRecepcion:
                xml:
                  attribute: true
              FechaVencimiento:
                xml:
                  attribute: true
              FechaFinalizacion:
                xml:
                  attribute: true
              FechaFirmaDigital:
                xml:
                  attribute: true
              SegundoFacAut:
                xml:
                  attribute: true
              EstampadoCronologico:
                xml:
                  attribute: true
              NotificarRemitente:
                xml:
                  attribute: true
              Estado:
                type: object
                properties:
                  Id:
                    xml:
                      attribute: true
                  Nombre:
                    xml:
                      attribute: true
              Cuenta:
                type: object
                properties:
                  Id:
                    xml:
                      attribute: true
                  Nombre:
                    xml:
                      attribute: true
              GrupoRegistro:
                type: object
                properties:
                  Id:
                    xml:
                      attribute: true
                  Nombre:
                    xml:
                      attribute: true
              Origen:
                type: object
                properties:
                  Tipo:
                    xml:
                      attribute: true
                  Id:
                    xml:
                      attribute: true
                  Referencia:
                    xml:
                      attribute: true
              GruposPartcipantes:
                type: array
                items:
                  properties:
                    Grupo:
                      type: object
                      properties:
                        Id:
                          xml:
                            attribute: true
                        Rol:
                          xml:
                            attribute: true
                        Nombre:
                          xml:
                            attribute: true
                        Participante:
                          type: object
                          properties:
                            Id:
                              xml:
                                attribute: true
                            Email:
                              xml:
                                attribute: true
                            Firma:
                              xml:
                                attribute: true
                            Nombre:
                              xml:
                                attribute: true
                            Apellido:
                              xml:
                                attribute: true
                            TipoIdentificacion:
                              xml:
                                attribute: true
                            DocumentoIdentificacion:
                              xml:
                                attribute: true
                            Celular:
                              xml:
                                attribute: true
                            FechaEnvioParaFirma:
                              xml:
                                attribute: true
                            FechaLecturaParaFirma:
                              xml:
                                attribute: true
                            IpLecturaParaFirma:
                              xml:
                                attribute: true
                            FechaRespuesta:
                              xml:
                                attribute: true
                            IpRespuesta:
                              xml:
                                attribute: true
                            FechaEnvioDocumentoFirmado:
                              xml:
                                attribute: true
                            FechaDescargaDocumentoFirmado:
                              xml:
                                attribute: true
                            IpDescargaDocumentoFirmado:
                              xml:
                                attribute: true
                            IdentificacionEnFirma:
                              xml:
                                attribute: true
                            NombreEnFirma:
                              xml:
                                attribute: true
                            Identificacion:
                              xml:
                                attribute: true
                            Organizacion:
                              xml:
                                attribute: true
                            Cargo:
                              xml:
                                attribute: true
                            Estado:
                              type: object
                              properties:
                                Id:
                                  xml:
                                    attribute: true
                                Nombre:
                                  xml:
                                    attribute: true
                            Observacionnes: 
                              type: nil
                              required: false
              Mensaje:
                type: string
                example: "Mensaje correo"
                required: false
              Observacionnes:
                type: nil
                required: false
              Documentos:
                type: array
                required: false
                items:
                  properties:
                    Documento:
                      type: object
                      properties:
                        Id:
                          xml:
                            attribute: true
                        Naturaleza:
                          xml:
                            attribute: true
                        Size:
                          xml:
                            attribute: true
                        Nombre:
                          xml:
                            attribute: true
                        Orden:
                          xml:
                            attribute: true
                        FechaCarga:
                          xml:
                            attribute: true
                        UsuarioCarga:
                          xml:
                            attribute: true
                        AplicacionCarga:
                          xml:
                            attribute: true
                        Eliminado:
                          xml:
                            attribute: true
              Copias:
                type: nil
                required: false