#%RAML 1.0 DataType
type: object
properties:
  inputMessage:
    required: true
    properties:
      OrderFulfilment:
        type: object
        required: false
        properties:
          AltKey:
            type: array
            required: false
            items:
              properties:
                AltKeyName:
                  type: string
                  required: false
                  example: "ServiceId"
                AltKeyValue:
                  type: string
                  required: false
                  example: "a023300000ZY9zgAAD-a094y00000Y6ivQAAR"
                ActionCode:
                  type: string
                  required: false
                  example: "string"
          CustomerPartyAccount:
            type: object
            required: true
            properties:
              Address:
                type: object
                properties:
                  CityCode:
                    type: string
                    required: false
                    example: "string"
                  CityName:
                    type: string
                    required: false
                    example: "string"
                  CountryCode:
                    type: string
                    required: false
                    example: "string"
                  CountryName:
                    type: string
                    required: false
                    example: "string"
                  LineOne:
                    type: string
                    required: false
                    example: "string"
                  StateCode:
                    type: string
                    required: false
                    example: "string"
                  StateName:
                    type: string
                    required: false
                    example: "string"
                  Technology:
                    type: object
                    required: false
                    properties:
                      CoverageIndicator:
                        type: boolean
                        required: true
                        example: true
              ContactPerson:
                type: object
                required: true
                properties:
                  FirstName:
                    type: string
                    required: true
                    example: "string"
                  FamilyName:
                    type: string
                    required: true
                    example: "string"
                  CompleteNumber:
                    type: string
                    required: true
                    example: "string"
              Custom:
                type: object
                required: true
                properties:
                  DocumentType:
                    type: string
                    required: true
                    example: "string"
                  DocumentNumber:
                    type: string
                    required: true
                    example: "string"
              Identification:
                type: object
                required: true
                properties:
                  ID:
                    type: string
                    required: true
                    example: "string"
                  BusinessComponentID:
                    type: string
                    required: true
                    example: "string"
              Name:
                type: string
                required: true
                example: "string"
              TypeCode:
                type: string
                required: true
                example: "string"
          Identification:
            type: object
            required: true
            properties:
              ID:
                type: string
                required: true
                example: "string"
              BusinessComponentID:
                type: string
                required: true
                example: "string"
          SalesOrder:
            type: object
            required: true
            properties:
              DeliveryDateTime:
                type: string
                required: true
                example: "string"
              OrderDateTime:
                type: string
                required: true
                example: "string"
          SalesOrderAgent:
            type: object
            required: false
            properties:
              Name:
                type: string
                required: true
                example: "string"
              SalesChannel:
                type: string
                required: true
                example: "string"
          SalesOrderLine:
            type: array
            required: false
            items:
              properties:
                AltKey:
                  type: array
                  required: false
                  items:
                    properties:
                      AltKeyName:
                        type: string
                        required: false
                        example: "ServiceId"
                      AltKeyValue:
                        type: string
                        required: false
                        example: "a023300000ZY9zgAAD-a094y00000Y6ivQAAR"
                      ActionCode:
                        type: string
                        required: false
                        example: "string"
                Custom:
                  type: object
                  required: true
                  properties:
                    AssetIntegrationID:
                      type: string
                      required: true
                      example: "string"
                Identification:
                  type: object
                  required: true
                  properties:
                    ID:
                      type: string
                      required: true
                      example: "string"
                    BusinessComponentID:
                      type: string
                      required: true
                      example: "string"
                ItemReference:
                  type: object
                  required: true
                  properties:
                    Name:
                      type: string
                      required: true
                      example: "string"
                    PrimaryClassificationCode:
                      type: string
                      required: true
                      example: "string"
                OwnerPartyReference:
                  type: object
                  required: true
                  properties:
                    ID:
                      type: string
                      required: true
                      example: "string"
                    BusinessComponentID:
                      type: string
                      required: true
                      example: "string"
                ParentSalesOrderLineIdentification:
                  type: object
                  required: true
                  properties:
                    ID:
                      type: string
                      required: true
                      example: "string"
                    BusinessComponentID:
                      type: string
                      required: true
                      example: "string"
                ServiceActionCode:
                  type: string
                  required: true
                  example: "string"
                SpecificationGroupXA:
                  type: array
                  required: false
                  items:
                    properties:
                      ActionCode:
                        type: string
                        required: true
                        example: "string"
                      Name:
                        type: string
                        required: true
                        example: "string"
                      Value:
                        type: string
                        required: true
                        example: "string"
          Scheduling:
            type: object
            required: false
            properties:
              SubOrderType:
                type: string
                required: false
                example: "string"
              TechnicalVisitDate:
                type: string
                required: false
                example: "string"
              TimeZone:
                type: string
                required: false
                example: "string"
          Sender:
            type: object
            required: false
            properties:
              ApplicationID:
                type: string
                required: false
                example: "string"
      BillingProcess:
        type: object
        required: false
        properties:
          Customer:
            type: object
            required: false
            properties:
              ContactInfo:
                type: object
                required: false
                properties:
                  Email:
                    type: string
                    required: false
                    example: "string"
          CustomerBill:
            type: object
            required: false
            properties:
              InvoicingCycle:
                type: string
                required: false
                example: "string"
              SuscriberId:
                type: string
                required: false
                example: "string"
              BillingAccount:
                type: object
                required: false
                properties:
                  Number:
                    type: string
                    required: false
                    example: "string"