#%RAML 1.0 DataType
properties:
  FechaRadicacion:
    type: date-only
    required: true
    example: "2024-09-30"
  TipoCaso:
    type: string
    required: true
    enum: ["SOPORTE TECNICO","CASO PQR"]
    example: "CASO PQR"
  idCuenta:
    type: string
    maxLength: 50
    required: true
    pattern: ^[a-zA-Z0-9-_]+$
    example: "0014000000uczFLAAY"
  idContacto:
    type: string
    maxLength: 50
    required: true
    pattern: ^[a-zA-Z0-9-_]+$
    example: "003RT00000JkB0kYAF"
  Asunto:
    type: string
    maxLength: 250
    required: true
    example: "Registro de solicitud autoatención LEY 2300 DE 2023"
  Descripcion:
    type: string
    required: true
    example: "En atención a su solicitud de actualización de los canales que autorizó para el envío de comunicaciones de acuerdo con lo dispuesto en la Ley 2300 de 2023, le informamos que se actualizó la información en el sistema.. El contacto eliminó la información del canal de comunicacion para la Ley 2300 para ser contactado por Whatsapp al número 3057889989. . El contacto registró la información del canal de comunicacion para la Ley 2300 para ser contactado por SMS al número 3057889988."
  IdServicio:
    type: string
    maxLength: 50
    required: false
    pattern: ^[a-zA-Z0-9-_]+$
    example: "ID0002536"
  Direccion:
    type: string
    maxLength: 250
    required: false
    example: "KR 8 20 00"
  Ciudad:
    type: string
    maxLength: 250
    required: false
    example: "Bogota"
  Tipologia:
    type: string
    maxLength: 250
    required: false
    example: "Información y/o documentación"
  Causal:
    type: string
    maxLength: 250
    required: false
    example: ""
  Nivel1:
    type: string
    maxLength: 255
    required: false
    example: "Información Front"
  Nivel2:
    type: string
    maxLength: 255
    required: false
    example: "Datos"
  Nivel3:
    type: string
    maxLength: 255
    required: false
    example: "Negociado"
  Estado:
    type: string
    enum: ["Abierto","Cerrado"]
    required: true
    example: "Abierto"
  FechaInicioAfectacion:
    type: datetime
    required: false
    format: rfc3339
    example: "2024-09-03T00:00:00Z"