#%RAML 1.0 DataType
type: object
properties:
  sUsuarioETB:
    description: Usuario ETB 
    type: string
    example: MDM_Integrador
  sIMEI: 
    description: Numero IMEI
    type: string
    example: "354522058683249"
  sTipoDocumento: 
    description: Tipo de Documento
    type: string
    example: CC
  sNumDocumento: 
    description: Numero de documento
    type: string   
    
example:
  !include ../../examples/requests/RequestBDOExample.raml