#%RAML 1.0
title: portabilidad-xapi-services
version: "1"
protocols:
  - HTTPS
mediaType: 
- application/json
baseUri: https://portabilidad-xapi-services-{env}.us-e2.cloudhub.io/
types:
  reenvio-nip-request: !include datatypes/request/reenvioNIP.raml
  reenvio-nip-response: !include datatypes/response/reenvioNIP.raml
  programacion-portacion-request: !include datatypes/request/programacionPortacion.raml
  programacion-portacion-response: !include datatypes/response/programacionPortacion.raml
  respuesta-solicitud-portacion-donante-request: !include datatypes/request/requestResSolPortDon.raml
  respuesta-solicitud-portacion-donante-response: !include datatypes/response/requestResSolPortDon.raml
  solicitud-nip-request: !include datatypes/request/solicitudNIP.raml
  solicitud-nip-response: !include datatypes/response/solicitudNIP.raml
  solicitud-portacion-request: !include datatypes/request/solicitudPortacion.raml
  solicitud-portacion-response: !include datatypes/response/solicitudPortacion.raml
  solicitud-cancelacion-request: !include datatypes/request/solicitudCancelacion.raml
  solicitud-cancelacion-response: !include datatypes/response/solicitudCancelacion.raml

traits: 
  tibcoHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml

securitySchemes:
  etb_oauth_2_0: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

/v1:
  /mediafon:
    /portabilidad:
      /{numOrder}:
        post:
          securedBy: [etb_oauth_2_0] 
          displayName: Unique endpoint to handle all actions
          description: Unique endpoint to handle all actions
          queryParameters:
            accion:
              type: string
              required: true
              enum: [ 
                      SolicitudNIP,
                      ReenvioNIP,
                      ProgramacionPortacion,
                      RespuestaSolicitudPortacionDonante,
                      SolicitudPortacion,
                      SolicitudCancelacion
                    ]
            tipodoc:
              type: string
              required: false
              enum: [natural, juridico]
          body:
            type: solicitud-nip-request | reenvio-nip-request | programacion-portacion-request | respuesta-solicitud-portacion-donante-request | solicitud-portacion-request | solicitud-cancelacion-request
          responses:
            201:
              body:
                type: solicitud-nip-response | reenvio-nip-response | programacion-portacion-response | respuesta-solicitud-portacion-donante-response  | solicitud-portacion-response  | solicitud-cancelacion-response
  /OTT:
    /DTV:
      /{numOrden}:
        post:
          securedBy: [etb_oauth_2_0]
          displayName: DGO for orders
          description: DGO for orders 
          queryParameters:
            accion:
              type: string
              required: true
              enum: [
                      "AccountRegistration"
                    ]
            origen:
              type: string
              required: true
              enum: [
                      "PortalMovilidad",
                      "PortalFija" 
                    ]
            tramite:
              type: string
              required: false
            isRollback:
              type: boolean | nil
              required: false
          responses:
            200:
              body:
                type: !include datatypes/response/registerAccount.raml
    /DDTV:
      /{CuentaServicio}:
        post:
          securedBy: [etb_oauth_2_0]
          displayName: DGO for services
          description: DGO for services
          queryParameters:
            accion:
              type: string
              required: true
              enum: [
                      "AccountRegistration"
                    ]
            origen:
              type: string
              required: true
              enum: [
                      "Collections"
                    ]
            tramite:
              type: string
              required: false
          responses:
            200:
              body:
                type: !include datatypes/response/registerAccount.raml