#%RAML 1.0 DataType
type: object
properties:
  order:
    type: object
    properties:
      accountId: string
      referenceCode: string
      description: string
      language: string
      signature?: string
      notifyUrl?: string
      additionalValues:
        type: object
        properties:
          TX_VALUE:
            type: object
            properties:
              value: number
              currency: string
          TX_TAX:
            type: object
            properties:
              value: number
              currency: string
          TX_TAX_RETURN_BASE?:
            type: object
            properties:
              value?: number
              currency?: string
      buyer:
        type: object
        properties:
          merchantBuyerId?: string
          fullName: string
          emailAddress: string
          contactPhone: string
          dniNumber: string
          shippingAddress?:
            type: object
            properties:
              street1?: string
              street2?: string
              city?: string
              state?: string
              country?: string
              postalCode?: string
              phone?: string
  threeDomainSecure?:
    type: object
    properties:
      embedded: boolean
      eci: string
      cavv: string
      xid: string
      directoryServerTransactionId: string
  payer:
    type: object
    properties:
      merchantPayerId?: string
      fullName: string
      emailAddress: string
      contactPhone: string
      dniNumber: string
      billingAddress:
        type: object
        properties:
          street1: string
          street2: string
          city: string
          state?: string
          country: string
          postalCode?: string
          phone?: string 
  creditCard?:
    type: object
    properties:
      number: string
      securityCode: string
      expirationDate: string
      name: string  
  extraParameters?:
    type: object
    properties:
      INSTALLMENTS_NUMBER: number
  cookie: string
  userAgent: string
  paymentMethod: string
  paymentCountry: string
  deviceSessionId: string
  ipAddress: string