#%RAML 1.0 DataType 
type: object
properties:
  language:
    type: string
    example: es
    required: false
  command:
    type: string
    example: SUBMIT_TRANSACTION
    required: false
  merchant:
    type: object
    properties:
      apiKey:
        type: string
        example: 4Vj8eK4rloUd272L48hsrarnUA
        required: false
      apiLogin:
        type: string
        example: pRRXKOl8ikMmt9u
        required: false
  transaction:
    type: object
    properties:
      order:
        type: object
        properties:
          accountId:
            type: string
            example: '512321'
            required: false
          referenceCode:
            type: string
            example: ORDER_TEST_2025_001
            required: false
          description:
            type: string
            example: Pago de prueba unificado
            required: false
          language:
            type: string
            example: es
            required: false
          signature:
            type: string
            example: 1d6c33aed575c4974ad5c0be7c6a1c87
            required: false
          notifyUrl:
            type: string
            example: http://www.example.com/notify
            required: false
          additionalValues:
            type: object
            properties:
              TX_VALUE:
                type: object
                properties:
                  value:
                    type: integer
                    example: 65000
                    required: false
                  currency:
                    type: string
                    example: COP
                    required: false
              TX_TAX:
                type: object
                properties:
                  value:
                    type: integer
                    example: 10378
                    required: false
                  currency:
                    type: string
                    example: COP
                    required: false
              TX_TAX_RETURN_BASE:
                type: object
                properties:
                  value:
                    type: integer
                    example: 54622
                    required: false
                  currency:
                    type: string
                    example: COP
                    required: false
          buyer:
            type: object
            properties:
              merchantBuyerId:
                type: string
                example: '1'
                required: false
              fullName:
                type: string
                example: Juan Carlos Perez
                required: false
              emailAddress:
                type: string
                example: buyer@test.com
                required: false
              contactPhone:
                type: string
                example: 57 3007777777
                required: false
              dniNumber:
                type: string
                example: '123456789'
                required: false
              dniType:
                type: string
                example: CC
                required: false
              shippingAddress:
                type: object
                properties:
                  street1:
                    type: string
                    example: 'Calle 100 #15-20'
                    required: false
                  street2:
                    type: string
                    example: Apto 402
                    required: false
                  city:
                    type: string
                    example: Bogotá
                    required: false
                  state:
                    type: string
                    example: Bogotá D.C.
                    required: false
                  country:
                    type: string
                    example: CO
                    required: false
                  postalCode:
                    type: string
                    example: '110111'
                    required: false
                  phone:
                    type: string
                    example: 57 3007777777
                    required: false
          shippingAddress:
            type: object
            properties:
              street1:
                type: string
                example: 'Calle 100 #15-20'
                required: false
              street2:
                type: string
                example: Apto 402
                required: false
              city:
                type: string
                example: Bogotá
                required: false
              state:
                type: string
                example: Bogotá D.C.
                required: false
              country:
                type: string
                example: CO
                required: false
              postalCode:
                type: string
                example: '110111'
                required: false
              phone:
                type: string
                example: 57 3007777777
                required: false
      payer:
        type: object
        properties:
          merchantPayerId:
            type: string
            example: '1'
            required: false
          fullName:
            type: string
            example: Juan Carlos Perez
            required: false
          emailAddress:
            type: string
            example: payer@test.com
            required: false
          contactPhone:
            type: string
            example: 57 3007777777
            required: false
          dniNumber:
            type: string
            example: '987654321'
            required: false
          dniType:
            type: string
            example: CC
            required: false
          billingAddress:
            type: object
            properties:
              street1:
                type: string
                example: 'Carrera 23 #53-50'
                required: false
              street2:
                type: string
                example: Oficina 301
                required: false
              city:
                type: string
                example: Bogotá
                required: false
              state:
                type: string
                example: Bogotá D.C.
                required: false
              country:
                type: string
                example: CO
                required: false
              postalCode:
                type: string
                example: '110231'
                required: false
              phone:
                type: string
                example: 57 3007777777
                required: false
      creditCard:
        type: object
        properties:
          number:
            type: string
            example: '4037997623271984'
            required: false
          securityCode:
            type: string
            example: '321'
            required: false
          expirationDate:
            type: string
            example: 2030/12
            required: false
          name:
            type: string
            example: JUAN C PEREZ
            required: false
      digitalWallet:
        type: object
        required: false
        properties:
          type:
            type: string
            example: GOOGLE_PAY
            required: false
          message:
            type: string
            example: '{"example":"wallet-encrypted-message"}'
            required: false
      extraParameters:
        type: object
        properties:
          INSTALLMENTS_NUMBER:
            type: integer
            example: 1
            required: false
          RESPONSE_URL:
            type: string
            example: http://www.example.com/response
            required: false
          PSE_REFERENCE1:
            type: string
            example: 127.0.0.1
            required: false
          PSE_REFERENCE2:
            type: string
            example: CC
            required: false
          PSE_REFERENCE3:
            type: string
            example: '123456789'
            required: false
          FINANCIAL_INSTITUTION_CODE:
            type: string
            example: '1022'
            required: false
          USER_TYPE:
            type: string
            example: 'N'
            required: false
      threeDomainSecure:
        type: object
        properties:
          embedded:
            type: boolean
            example: false
            required: false
          eci:
            type: string
            example: '01'
            required: false
          cavv:
            type: string
            example: AOvG5rV058/iAAWhssPUAAADFA==
            required: false
          xid:
            type: string
            example: Nmp3VFdWMlEwZ05pWGN3SGo4TDA=
            required: false
          directoryServerTransactionId:
            type: string
            example: 00000-70000b-5cc9-0000-000000000cb
            required: false
      type:
        type: string
        example: AUTHORIZATION_AND_CAPTURE
        required: false
      paymentMethod:
        type: string
        example: VISA
        required: false
      paymentCountry:
        type: string
        example: CO
        required: false
      expirationDate:
        type: datetime-only
        example: '2025-12-31T23:59:59'
        required: false
      deviceSessionId:
        type: string
        example: vghs6tvkcle931686k1900o6e1
        required: false
      ipAddress:
        type: string
        example: 127.0.0.1
        required: false
      cookie:
        type: string
        example: pt1t38347bs6jc9ruv2ecpv7o2
        required: false
      userAgent:
        type: string
        example: Mozilla/5.0 (Windows NT 10.0; Win64; x64)
        required: false
  test:
    type: boolean
    example: true
    required: false
