#%RAML 1.0 DataType

description: Request para recarga de saldo (Usage Consumption Report)
properties:
  amount:
    type: object
    description: Monto de la recarga
    required: true
    properties:
      amount:
        type: number
        example: 20000
      currency:
        type: string
        example: "COP"
  msisdn:
    description: Número de línea (Mobile Station International Subscriber Directory Number).
    type: string
    required: true
    example: "3336025009"
  manager:
    description: Identificador del gestor / canal externo.
    type: string
    required: false
    example: "PayU"
