#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  serviceResource:
    type: array
    required: false
    items:
      type: object
      properties:
        numPqr:
          type: string
          example: string
          required: false
        service:
          type: object
          required: false
          properties:
            status:
              type: string
              example: string
              required: false
            message:
              type: string
              example: string
              required: false
        networks:
          type: array
          required: false
          items:
            type: object
            properties:
              networkName:
                type: string
                example: string
                required: false
              networkState:
                type: string
                example: string
                required: false
              macAddress:
                type: string
                example: string
                required: false
              ontSerial:
                type: string
                example: string
                required: false
              frequency:
                type: string
                example: string
                required: false
        equipment:
          type: object
          required: false
          properties:
            ontSerial:
              type: string
              example: string
              required: false
            model:
              type: string
              example: string
              required: false
            status:
              type: string
              example: string
              required: false
        status:
          type: string
          example: string
          required: false
        message:
          type: string
          example: string
          required: false
        additionalChannels:
          type: string
          example: string
          required: false
        additionalServices:
          type: string
          example: string
          required: false
        decos:
          type: string
          example: string
          required: false
        stateSubscriberId:
          type: string
          example: string
          required: false
