#%RAML 1.0 DataType 
type: array
items:
  type: object
  properties:
    id:
      type: string
      example: MDM-PQR-4156123
      required: false
    status:
      type: string
      example: pending
      required: false
    description:
      type: string
      example: Degradación del servicio de internet
      required: false
    characteristic:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            example: Causal
            required: false
          value:
            type: string
            example: FALLA INTERNET
            required: false
    affectedService:
      type: array
      items:
        type: object
        properties:
          category:
            type: string
            example: Conectividad
            required: false
          id:
            type: string
            example: svc001
            required: false
          name:
            type: string
            example: Internet Empresarial Fibra 500Mbps
            required: false
          type:
            type: string
            example: BUNDLE
            required: false
    priority:
      type: string
      example: ''
      required: false
    '@type':
      type: string
      example: ServiceProblem
      required: false