#%RAML 1.0 DataType
properties:
  wsInputCreateDispatchOrder:
    type: object
    properties:
      parameters:
        type: object
        properties:
          wsInputCreateDispatchOrder:
            type: object
            properties:
              wsRequestHeader:
                type: object
                properties:
                  property:
                    type: array
                    items:
                      type: object
                      properties:
                        NUMEROORDEN: 
                          type: string | nil
                          required: false
                        TIPOORDEN: 
                          type: string
                          minLength: 1
                          enum: ["Express", "Basica"]
                        TIPOENTREGA:
                          type: string | nil
                          required: false
                        RECAUDO:
                          type: string | nil
                          required: false
                        VALORRECAUDO:
                          type: number | nil
                          required: false
                        BARRIO:  
                          type: string | nil
                          required: false
                        BODEGA: 
                          type: string | nil
                          required: false
                        SUBTIPO:  
                          type: string
                          minLength: 1
                        NOMBRE:  
                          type: string
                          minLength: 1
                        CAMPANA:  
                          type: string
                          minLength: 1
                        REENVIO:
                          type: string | nil
                          required: false
                        INTENTOS:
                          type: string | nil
                          required: false                                       
              inputCreateDispatchOrder:
                type: object
                properties:
                  dispatchOrderHeader:
                    type: object
                    properties:
                      reserveNumber:
                        type: string | nil
                        required: false
                      priority:
                        type: string | nil
                        required: false
                      warehouseCode:
                        type: string | nil
                        required: false
                      names:  
                          type: string
                          minLength: 1
                      surnames:  
                          type: string
                          minLength: 1
                      documentType:  
                          type: string
                          minLength: 1
                      documentNumber: number
                      mobileNumber: number
                      mobileNumber2:
                        type: string | nil
                        required: false
                      phoneNumber?:
                        type: string | nil
                        required: false
                      phoneNumber2:
                        type: string | nil
                        required: false
                      email:
                        type: string | nil
                        required: false
                      address:  
                          type: string
                          minLength: 1
                      city: string
                      department: string
                      clientObservations:
                        type: string | nil
                        required: false
                      date:  
                          type: string
                          minLength: 1
                      invoiceNumber:
                        type: string | nil
                        required: false
                      invoiceDate:
                        type: string | nil
                        required: false
                      cunNumber:  
                          type: string
                          minLength: 1
                      callCenter:  
                          type: string
                          minLength: 1
                      planValue:
                        type: number | nil
                        required: false
                      planName:
                        type: string | nil
                        required: false
                      paymentsNumber:
                        type: number | nil
                        required: false
                      paymentsValue:
                        type: number | nil
                        required: false
                      portabilityNumber:
                        type: string | nil
                        required: false
                      portabilityDate:
                        type: string | nil
                        required: false
                      planType: 
                        type: string | nil
                        required: false
                      deliveryType:
                        type: string | nil
                        required: false
                  dispatchOrderDetail:
                    type: array
                    items:
                      type: object
                      properties:
                        dispatchOrderCode:
                          type: object
                          properties:
                            partNumber:  
                              type: string
                              minLength: 1
                            quantity: number
                            equipmentValue: number
