#%RAML 1.0 DataType

type: object
properties:
  BillingAccountId:
    type: string
    example: "12054231777"
  user:
    type: string
    example: "MDM_ATOMIC"
  Customer:
    type: object
    properties:
      SubscriberId:
        type: string | nil
        example: "12054231777"
        required: false
      FirstName:
        type: string | nil
        example: "Alejandro"
        required: false
      LastName:
        type: string | nil
        example: "Perez"
        required: false
      SuscriberName:
        type: string | nil
        example: "SuscriberName"
        required: false
      BillBillingName:
        type: string | nil
        example: "billName"
        required: false
      Email:
        type: string | nil
        example: "alejandro@ghjl.com"
        required: false
  Address:
    type: object
    properties:
      Address:
        type: string
        example: "KR 27G 73D 92 SUR"
      City:
        type: string
        example: "BOGOTA D.C."
      CityCode:
        type: string
        example: "11001000"
      CountryCode:
        type: string
        example: "COL"
      StateCode:
        type: string
        example: "11"
      Department:
        type: string
        example: "BOGOTA"
  InvoiceMethod:
    type: object
    properties:
      DeliveryType:
        type: string
        example: "SMS"
      MethodName:
        type: string
        example: "Cuentas LTE Detallada"
      MobilePhone:
        type: string | nil
        example: "3002496009"
        required: false