#%RAML 1.0 DataType
properties:
  statusReasonTOA?:
    type: string
  resolution?:
    type: string
    example: "DEPURACION AGENDA"
  resolutionCode?:
    type: string
    example: "CR3377- - "
  status?:
    type: string
    example: "COMPLETED"
  groupID?:
    type: string
  action?:
    type: string
    example: "CLOSE"
