#%RAML 1.0 DataType
properties:
  sumaLogsMsgInput:
    type: object
    properties:
      SUMALogIN:
        type: object
        properties:
          LogDate:
            type: string | nil
            required: false
          SourceIP:
            type: string | nil
            required: false
          User:
            type: string | nil
            required: false
          SourcePortal:
            type: string | nil
            required: false
          DocumentType:
            type: string | nil
            required: false
          DocumentNumber:
            type: string | nil
            required: false
          ConnectionNumber:
            type: string | nil
            required: false
          ServiceId:
            type: string | nil
            required: false
          CustomerFound:
            type: string | nil
            required: false
          Trace:
            type: string | nil
            required: false