#%RAML 1.0 DataType
displayName: spn pqr Logs Message Input
type: object
properties:
  SPNPQRLoggerInput:
    type: object
    properties:
      SPNPQRLoggerIN:
        type: object
        properties:
          Date:
            type: string | nil
            required: false
          PQRNumber:
            type: string | nil
            required: false
          ActivitySN1:
            type: string | nil
            required: false
          ServiceAccount:
            type: string | nil
            required: false
          Technology:
            type: string | nil
            required: false
          ModemSerial:
            type: string | nil
            required: false
          ModemMac:
            type: string | nil
            required: false
          ModemBrand:
            type: string | nil
            required: false
          ModemModel:
            type: string | nil
            required: false
          Result:
            type: string | nil
            required: false
          ClosingType:
            type: string | nil
            required: false
          CommandDate:
            type: string | nil
            required: false
          CommandType:
            type: string | nil
            required: false
          CommandDescription:
            type: string | nil
            required: false
          Command:
            type: string | nil
            required: false
          CommandResponse:
            type: string | nil
            required: false
          User:
            type: string | nil
            required: false
example: !include ../../examples/request/post-spnpqrLogs.raml