#%RAML 1.0 DataType
properties:
  id:
    type: string | nil
    required: false
    example: null
  pqrNumber: 
    type: string | nil
    required: false
    example: null
  customerDocumentType: 
    type: string | nil
    required: false
    example: null
  customerDocumentNumber: 
    type: string | nil
    required: false
    example: null
  connectionNumber:
    type: string | nil
    required: false
    example: null 
  billingAccount: 
    type: string | nil
    required: false
    example: null
  cun: 
    type: string | nil
    required: false
    example: "4347220001355902"
  assignedUser: 
    type: string | nil
    required: false
    example: null
  tipoConsulta: 
    type: string | nil
    required: false
    example: null
  tipoServicio: 
    type: string | nil
    required: false
    example: null
  canalRecepcion: 
    type: string | nil
    required: false
    example: null
  diasHabiles: 
    type: string | nil
    required: false
    example: null
  estado:
    type: string | nil
    required: false
    example: null

