#%RAML 1.0 DataType
properties:
  updateSLFServicesStatusRequest:
    type: object
    required: true
    properties:
      input:
        type: object
        required: true
        properties:
          updateSLFServicesStatusInput:
            type: object
            required: true
            properties:
              wsRequestHeader2:
                type: object
                required: true
                properties:
                  system:
                    type: object
                    properties:
                      name:
                        type: string
                        required: true
                        example: "MDM_Logic_Services"
                      correlationID:
                        type: string
                        required: true
                        example: "MDM-MOV-320831"
                      processingServer:
                        type: string
                        required: true
                        example: "PRD"
                  property:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          required: true
                          example: ""
                        value:
                          type: string
                          required: true
                          example: ""
              updates:
                type: object
                properties:
                  update:
                    type: array
                    items:                      
                      type: object
                      properties:
                        order:
                          type: object
                          required: true
                          properties:
                            subtype:
                              type: string
                              required: true
                              example: "Retiro, Portabilidad Saliente"
                        customer:
                          type: object
                          required: true
                          properties:
                            id:
                              type: string
                              required: true
                              example: "800909456"
                            idType:
                              type: string
                              required: true
                              example: "NIT"
                            service:
                              type: object
                              required: true
                              properties:
                                connectionNumber:
                                  type: string
                                  required: true
                                  example: "30570004881"