# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "20593056"

# --- Silice SAPI HTTP Requester ---
siliceSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-silice-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/v1"
  notifications:
    path: "/notifications"
    post:
      method: "POST"

# --- Oracle SAPI HTTP Requester ---
oracleSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-qa.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/oracle/v1"
  notifications:
    path: "/notifications"
    post:
      method: "POST"

# --- Mongo DB SAPI HTTP Requester ---
mongoDbSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mongo/v1"
  notificationsAudit:
    path: "/notifications/audit"
    post:
      method: "POST"
  notificationsAuditById:
    path: "/notifications/audit/{auditId}"
    patch:
      method: "PATCH"
  parametersRetention:
    path: "/parametersRetention"
    get:
      method: "GET"
  operators:
    path: "/operators"
    get:
      method: "GET"
  bussinessDays:
    path: "/bussinessDays"
    get:
      method: "GET"

# --- Azure SAPI HTTP Requester ---  
azureSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-azure-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/azure/v1"
  agreements:
    path: "/agreements"
    post:
      method: "POST"

# --- Portability Documents SAPI HTTP Requester ---  
portabilityDocumentsSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/common/v1"
  upload:
    path: "/portability/documents"
    post:
      method: "POST"