# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "20593056"

# --- Mongo DB SAPI HTTP Requester ---
mongoDbSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mongo/v1"
  collections:
    userIDP: "PORTAL_UNIFICADO_USUARIO"
  parametersRetention:
    path: "/parametersRetention"
    get:
      method: "GET"
  operators:
    path: "/operators"
    get:
      method: "GET"
  bussinessDays:
    path: "/bussinessDays"
    get:
      method: "GET"
  dynamicQuery:
    path: "/dynamicQuery"
    post:
      method: "POST"
  botChannel:
    path: "/bots/channels"
    get:
      method: "GET"
  botSystem:
    path: "/bots/systems"
    get:
      method: "GET"
  service:
    path: "/service"
    technology: "LTE"
    get:
      method: "GET"
  serviceActive:
    path: "/serviceActive"
    technology: "FTTH"
    get:
      method: "GET"
  customer:
    path: "/customer"
    get:
      method: "GET"
  pqr:
    path: "/pqrs"
    post:
      method: "POST"
  pqrCategory:
    path: "/pqrs/categories"
    get:
      method: "GET"
  pqrDuplicate:
    path: "/pqrs/duplicates"
    get:
      method: "GET"
  pqrParent:
    path: "/pqrs/parents"
    get:
      method: "GET"

google-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-google-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/v1"
  resources:  
    gcp:
      base-path: "/gcp"
      identity:
        path: "/identity"
        users:
         path: "/users"
         create:
          path: "/create"
         search:
          path: "/search"
        login:
         path: "/login"

# --- DirectTV SAPI HTTP Requester ---
directvSapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-directv-sapi-services-prod.us-e2.cloudhub.io"
  basePath: "/v1"
  customer:
    path: "/customers"
    post:
      method: "POST"
  customerId:
    path: "/customers/{customerId}"
    get:
      method: "GET"
  customerProduct:
    path: "/customers/{customerId}/products"
    post:
      method: "POST"
  customerNotification:
    path: "/customers/{customerId}/notifications/email"
    post:
      method: "POST"

# --- Azure SAPI HTTP Requester ---  
azureSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-azure-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/azure/v1"
  agreements:
    path: "/agreements"
    post:
      method: "POST"
  pqrAttachments:
    path: "/pqr/attachments/{documentNumber}/{pqrId}"
    post:
      method: "POST" 

# --- Portability Documents SAPI HTTP Requester ---  
portabilityDocumentsSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/common/v1"
  upload:
    path: "/portability/documents"
    post:
      method: "POST"  

# --- Common SAPI HTTP Requester --- 
commonSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/common/v1"
  cunAssignments:
    path: "/cun/assignments"
    post:
      method: "POST"

# --- DataLogic SAPI HTTP Requester --- 
dataLogicSapi:
  protocol: "HTTP"
  host: "mule-worker-internal-data-logic-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/v1"
  servicePqr:
    path: "/services/pqr"
    post:
      method: "POST"
