#%RAML 1.0 DataType
type: object
properties:
  ICCID:
    type: string
    required: true
    minLength: 1
  OrderId:
    type: string
    required: true
    minLength: 1
  ServiceId:
    type: string
    required: true
    minLength: 1
  MSISDN:
    type: string
    required: true
    minLength: 1
  NewMSISDN:
    type: string
    required: false
  Tramit:
    type: string
    required: true
    minLength: 1

example: !include ../../examples/request/completeInventoryExample.raml