#%RAML 1.0 DataType

properties:
  wsResponseConsultEvidentVerification:
    type: object
    properties:
      wsResponseHeader:
        type: object
        properties:
          system:
            type: object
            properties:
              name:
                type: string
                required: false
                example: "Portal"
              correlationId:
                type: string
                required: true 
                example: "MDM-LISIM-SCORING-CC-1001186322"
              source:
                type: string
                required: true 
                example: "WS.Consultas"
          service:
            type: object
            properties:
              status:
                type: string
                required: true
                example: "PASS"
      evaluation:
        type: object
        properties:
          header:
            type: object
            properties:
              code:
                type: string
                required: false
                example: "00"
              description:
                type: string
                required: false 
                example: "VALIDACION DE CUESTIONARIO OBTENIDA EXITOSAMENTE"
          body:
            type: object
            properties:
              result:
                type: string
                required: false
                example: "VALIDACION EXITOSA"
              questionnaireId:
                type: string
                required: false
                example: ""
              approval:
                type: number
                required: false
                example: 206193
              minPrgts:
                type: string
                required: false
                example: ""
              completedQuestions:
                type: string
                required: false
                example: ""
              securityCode:
                type: string
                required: false
                example: ""
              score:
                type: string
                required: false
                example: "863"
              reaccess:
                type: string
                required: false
                example: ""
              approved100PercentOK:
                type: string
                required: false
                example: "VALIDACION DE CUESTIONARIO OBTENIDA EXITOSAMENTE"