#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: OK
    required: false
  payment:
    type: object
    properties:
      id:
        type: string
        example: '20200909095004'
        required: false
      paymentTransaction:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              example: '800580037'
              required: false
            billingAccountId:
              type: string
              example: '0000012485'
              required: false
            paymentType:
              type: string
              example: ACE
              required: false
            paymentTypeDescription:
              type: string
              example: Assign cash entry
              required: false
            amount:
              type: string
              example: '-536'
              required: false
            remainingAmount:
              type: string
              example: '0'
              required: false
            currency:
              type: string
              example: USD
              required: false
            transactionDate:
              type: string
              example: '2020-01-06 08:30:10'
              required: false
            paymentDate:
              type: string
              example: '2020-01-06 08:30:10'
              required: false
            reversedPaymentId:
              type: 'null'
              example: null
              required: false
            originalAmount:
              type: string
              example: '-536'
              required: false
            originalCurrency:
              type: string
              example: USD
              required: false
            originalExchangeRate:
              type: 'null'
              example: null
              required: false
            targetExchangeRate:
              type: 'null'
              example: null
              required: false
            relatedPartyType:
              type: string
              example: F
              required: false
            relatedPartyId:
              type: string
              example: '3044336'
              required: false
            channelId:
              type: string
              example: '1'
              required: false
            paymentReference:
              type: 'null'
              example: null
              required: false
            paymentMethod:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: '1'
                    required: false
                  code:
                    type: string
                    example: PoS
                    required: false
                  name:
                    type: string
                    example: Cash
                    required: false
                  amount:
                    type: string
                    example: '536'
                    required: false
            bankCode:
              type: string
              example: '232'
              required: false
            bankAccountNumber:
              type: string
              example: '232'
              required: false
            receipt:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: '1234567'
                    required: false
                  receiptNumber:
                    type: string
                    example: '2345678'
                    required: false
                  receiptType:
                    type: string
                    example: AR
                    required: false
            adjustment:
              type: object
              properties:
                adjustmentType:
                  type: string
                  example: Waiver
                  required: false
                adjustmentLevel:
                  type: string
                  example: Account
                  required: false
                adjustmentReasonId:
                  type: string
                  example: '1'
                  required: false
                adjustmentReason:
                  type: string
                  example: test
                  required: false
                customerNumber:
                  type: string
                  example: 123424fasfda
                  required: false
                adjustmentItem:
                  type: array
                  items:
                    type: object
                    properties:
                      billingAccountItemId:
                        type: string
                        example: '1234567'
                        required: false
                      amount:
                        type: string
                        example: '12000000'
                        required: false
                      billingAccountItemTypeId:
                        type: string
                        example: '2'
                        required: false
                      billingAccountItemTypeName:
                        type: string
                        example: 4G Service
                        required: false
