#%RAML 1.0 DataType
type: object
properties:
  codeResponse:
    type: string
    example: "200"
  messageResponse:
    type: string
    example: "OK"
  transactionId:
    type: string
    example: "98875421326589"
  txnId:
    type: string
    example: "202312111"
  txnTypeId:
    type: string
    example: "1"
  amount:
    type: string
    example: "10000"