#%RAML 1.0 DataType
properties:
  Encabezado:
    type: object
    properties:
      Propiedades:
        type: nil
      Servicio:
        type: object
        properties:
          Codigo:
            type: string
            example: "O01"
          DetalleEstado:
            type: string
            example: "Proceso realizado exitosamente"
          Estado:
            type: string
            example: "OK"
          FechaRespuesta:
            type: string
            example: "2023-08-23 14:44:19"
      Sistema:
        type: object
        properties:
          IdCorrelacion:
            type: string
            example: "000001"
          Nombre:
            type: string
            example: "OrquestadorService"
          Servidor:
            type: string
            example: "AW0SDWK000007"
  Cantidad:
    type: string
    example: "1"
  Ordenes:
    type: array
    items:
      properties:
        ActivityId:
          type: string
          example: "21644708"
        Numero_Orden:
          type: string
          example: "MDM-PQR-39876386"
        Estado:
          type: string
          example: "pending"
        Posicion:
          type: string
          example: "0"
        InformacionAdicional:
          type: array
          items:
            properties:
              Nombre:
                type: string
                example: "activityId"
              Valor:
                type: string
                example: "21649475"
                          

