#%RAML 1.0 DataType 
type: object
properties:
  ObtenerDisponibilidadAgendasResponse:
    type: object
    properties:
      Resultado:
        type: object
        properties:
          Encabezado:
            type: object
            properties:
              Servicio:
                type: object
                properties:
                  Codigo:
                    type: string
                    example: O01
                    required: false
                  DetalleEstado:
                    type: string
                    example: Proceso realizado exitosamente
                    required: false
                  Estado:
                    type: string
                    example: OK
                    required: false
              Sistema:
                type: object
                properties:
                  Nombre:
                    type: string
                    example: OrquestadorService
                    required: false
                  Servidor:
                    type: string
                    example: AW0SDWK00002R
                    required: false
          fecha_agendas:
            type: object
            properties:
              DisponibilidadAgenda:
                type: array
                items:
                  type: object
                  properties:
                    Zona:
                      type: string
                      example: FONTIBON
                      required: false
                    color:
                      type: string
                      example: '4'
                      required: false
                    date:
                      type: date-only
                      example: '2026-07-01'
                      required: false
                    quota:
                      type: 'null'
                      example: null
                      required: false
                    time_slot:
                      type: 'null'
                      example: null
                      required: false
