#%RAML 1.0
title: sisext-sapi-services
baseUri: sisext-sapi-services-dev.us-e2.cloudhub.io/sisext
description: The following API will handle all the external services that the product consumes internally.
mediaType: 
- application/json
version: 1
protocols:
  - HTTP

traits: 
  security_client_id: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
  tibcoRequestHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.5/tibcorequestheaders.raml
  commonHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/commonheaders/1.0.0/commonheaders.raml
types:
  recarga-saldo: !include datatypes/request/recargar.raml
  recarga-paquetes: !include datatypes/request/recargar-paquete.raml

/v1:

  /air:
    /recharge:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        displayName: "Recharge Line"
        description: "Recharge Line in AIR"
        body:
          application/json:
            type: recarga-saldo | recarga-paquetes
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/recargar.raml

  

  /negativeRecord:
    post:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: "Insert Negative Record"
      description: "Inserts client negative record"
      body:
        application/json:
          type: !include datatypes/request/negativeRecord.raml
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/negativeRecord.raml
  /borrowing-capacities:
    post:
      is: [security_client_id, tibcoRequestHeaders]
      body:
        application/json:
          type: !include datatypes/request/consultaCupoNegLISIMInput.raml
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/consultaCupoNegLISIMResponse200.raml
              examples:
                example1: !include examples/response/consultaCupoNegLISIMResponse200-1.json
                example2: !include examples/response/consultaCupoNegLISIMResponse200-2.json
        500:
          body:
            application/json:
              type: !include datatypes/response/consultaCupoNegLISIMResponse500.raml
  /billings:
    /{connection-number}:
      /details:
        uriParameters:
          connection-number:
            example: "6012482773"
        get:
          is: [security_client_id, tibcoRequestHeaders]
          displayName: Connection number
          description: Obtain service particulars from a connection number loaded into Salesforce
          responses:
            200:
              body:
                type: !include datatypes/response/connectionNumberResponse.raml
                example: !include examples/response/connectionNumber200Response.raml
            404:
              body:
                type: !include datatypes/response/connectionNumberResponse.raml
                example: !include examples/response/connectionNumber404Response.raml
            500:
              body:
                type: !include datatypes/response/errorResponseDataType.raml
                example: !include examples/response/connectionNumber500Response.raml
  /orders:
    /{order_id}:
      /delivery:
        uriParameters:
          order_id:
            example: "MDM-MOV-2306254-OL-1"
        post:
          is: [security_client_id, tibcoRequestHeaders]
          displayName: Create Dispatch Order
          description: Create Dispatch Order
          body:
            application/json:
              type: !include datatypes/request/createDispatchOrder.raml
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/createDispatchOrderResponse.raml
            400:
              body:
                application/json:
                  type: !include datatypes/response/createDispatchOrder400.raml   
            500:
              body:
                application/json:
                  type: !include datatypes/response/createDispatchOrder500Response.raml

  /feasibility:
    get:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: Interface for operations of pre-feasibility
      description: Interface for operation of pre-feasibility consultation of fiber services (FTTH) in GIS.
      queryParameters:
        addressCode:
          description: Required code to identify the address
          example: "612802304578431600"
          minLength: 1
          type: string
          required: true
        mayorista:
          description: Required name to identify the mayorista
          example: "ETB"
          type: string
          required: false
      responses:
        200:
          body:
            application/json:
              example: !include examples/response/feasibilityResponse.raml

  /coverageGIS:
    get:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: Obtain CoverageGIS
      description: Obtain feasibility of coverage services
      queryParameters:
        Latitud:
          description: Latitude to identify the coverage
          example: "4.653928605"
          type: string
          required: true
        Longitud:
          description: Longitude to identify the coverage
          example: "-74.06588058"
          type: string
          required: true
      responses:
        200:
          body:
            type: !include datatypes/response/coverageGIS.raml
              
  /questionaries:
    /{questionarie-id}:
      /validation:
        uriParameters:
          questionarie-id:
            type: number
            example: 2652
        post:
          is: [security_client_id, tibcoRequestHeaders]
          displayName: validate Evidence LISIM
          body:
            application/json:
              type: !include datatypes/request/evidentVerificationLISIM.raml      
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/evidentVerificationLISIM.raml

  /documents:
    /validation:
      post: 
        is: [security_client_id, tibcoRequestHeaders]
        displayName: Validar
        description: Validar
        body:
          application/json:
            type: !include datatypes/request/validaIdentidadNeglisim.raml
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/validaIdentidadNeglisimResponse.raml
  /document:
    /validation:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        displayName: Verificar Documento CIFIN
        description: wsVerificaDocumentoCIFIN
        body:
          application/json:
            type: !include datatypes/request/verificaDocumentoCIFIN.raml
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/verificaDocumentoCIFIN.raml
                example: !include examples/response/verificaDocumentoCIFIN.json
  /RNE:
    get:
      is: [security_client_id, tibcoRequestHeaders]     
      displayName: Get RNE
      description: Get RNE
      queryParameters:
        sMSISDN:
          type: string
          maxLength: 10
          minLength: 1
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/GetRNE.raml
              example:
                !include examples/response/GetRNE.json

    post:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: Registrar RNE
      description: Registrar RNE
      body:
        application/json:
          type: !include datatypes/request/RegistrarRNE.raml
          example: !include examples/request/RegistrarRNE.json
      responses:
        201:
          body:
            application/json:
              properties:
                Codigo:
                  type: string
                  example: "1"
                Descripcion:
                  type: string
                  example: "RNE Creado"
  /referred:
    /{integrationId}:
      uriParameters:
        integrationId:
          type: string
          example: "5b083a77929c4e41149573b6"
      get:
        is: [security_client_id,   commonHeaders]
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/get-referredByIntegrationId.json
  /fraudQuery:
    post:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: FraudQuery
      description: Consulta fraude
      body:
        application/json:
          type: !include datatypes/request/fraudQuery.raml
      responses:
        200:
          body:
            application/json:
              example: !include examples/response/fraudQuery.json
                  
  /captcha:
    post:
      is: [security_client_id, tibcoRequestHeaders]     
      displayName: Validate Captcha
      description: Validate google captcha
      queryParameters:
        secret:
          type: string
          required: true
          minLength: 1
        token:
          type: string
          required: true
          minLength: 1
      responses:
        200:
          body:
            application/json:
              example:
                !include examples/response/captcha.json
  /getInvoice:
    post:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: Get invoice format
      description: Consulta recibo de pago
      body:
        application/json:
          type: !include datatypes/request/getInvoice.raml
      responses:
        200:
          body:
            application/json:
              example: !include examples/response/getInvoice.json
  /mediafon:
    /sendMsg:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        displayName: Send message to mediafon
        description: Send message to mediafon
        body:
          application/json:
            type: !include datatypes/request/postSendMsg.raml
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/postSendMsg.json
  /text-messages:
    post:
      is: [security_client_id, tibcoRequestHeaders]
      body:
        application/json:
          type: !include datatypes/request/sendTextMessageInput.raml
      responses:
        202:
          body:
            application/json:
              type: !include datatypes/response/sendTextMessage202.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/sendTextMessage500.raml

  /DGO:
    /subscriber:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        displayName: DGO account registration
        description: register an account in DGO by subscriber_id
        body:
          application/json:
            type: !include datatypes/request/dgoAccountRegistration.raml
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/accountRegistration.json
      /{subscriber_id}:
        get:
          is: [security_client_id, tibcoRequestHeaders]
          displayName: DGO get subscriber
          description: get subscriber from DGO by subscriber_id
          responses:
            200:
              body:
                application/json:
                  example: !include examples/response/getSubscriberInfo.json
        patch:
          is: [security_client_id, tibcoRequestHeaders]
          displayName: DGO edit subscriber
          description: edit subscriber in DGO by subscriber_id
          body:
            application/json:
              type: !include datatypes/request/dgoEditSubscriber.raml
          responses:
            200:
              body:
                application/json:
                  example: !include examples/response/getSubscriberInfo.json
        /urn:
          patch:
            is: [security_client_id, tibcoRequestHeaders]
            displayName: DGO add urns from subscriber
            description: add urns from subscriber in DGO by subscriber_id
            body:
              application/json:
                type: !include datatypes/request/urnsDgo.raml
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/getSubscriberInfo.json
        /deactivate:
          patch:
            is: [security_client_id, tibcoRequestHeaders]
            displayName: DGO deactivate subscriber
            description: deactivate a subscriber in DGO by subscriber_id
            responses:
              200:
                body:
                  application/json:
                    example: !include examples/response/deactivateUser.json
  /createAgreement:
    post:
      is: [security_client_id, tibcoRequestHeaders]
      displayName: Create Agreement in AZSign
      description: Create Agreement in AZSign
      body:
        application/json:
          type: !include /datatypes/request/post-createAgreement.raml
      responses:
        200:
          body:
            application/json:
              type: !include /datatypes/response/post-createAgreement.raml

  /atp:
    /auth:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: !include datatypes/request/atpAuth.raml   
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/atpAuth.json
    /bookingFeasibility:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: any
    /createBooking:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpCreateBooking.json
    /consultBooking:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpConsultBooking.json
    /cancelBooking:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpCancelBooking.json
    /activateOnt:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpActivateOnt.json
    /activateService:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpActivateService.json
    /deactivateOnt:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpDeactivateOnt.json
    /deactivateService:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpDeactivateService.json
    /resetONT:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpResetONT.json
    /consultLevels:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpConsultLevels.json
    /consultSpeed:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpConsultSpeed.json
    /consultState:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpConsultState.json
    /consultNeighbors:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpConsultNeighbors.json
    /serviceSuspension:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpServiceSuspension.json
    /serviceReactivation:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpServiceReactivation.json
    /speedChangeFeasibility:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpSpeedChangeFeasibility.json
    /speedChangeCreateBooking:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpSpeedChangeCreateBooking.json
    /speedChangeCancelBooking:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpSpeedChangeCancelBooking.json
    /speedChange:
      post:
        is: [security_client_id, tibcoRequestHeaders]
        body:
          application/json:
            type: any
            example: {}
        responses:
          200:
            body:
              application/json:
                type: !include examples/response/atpSpeedChange.json
