# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================
  
# --- Zsmart HTTP Requester ---
zsmart:
  billingBalanceToken: "![]"
  billingHistoryToken: "![]"
  transInfoInquiryToken: "![]"
  generateInvoiceToken: "![]"
  queryDisputeToken: "![]"
  queryInvoicePDFToken: "![]"
  billAccItemToken: "![]"
  paymentToken: "![]"
  subscriberProfileToken: "![]"
  queryBillPDFToken: "![]"
  attributeSyncToken: "![]"
  productSyncToken: "![]"
  offerSyncToken: "![]"
  offerRelaSyncToken: "![]"
  rechargeHistoryToken: "![]"
  addChargeToken: "![]"
  etbAcctStatementToken: "![]"
  magicCodeToken: "![]"
  rsa:
    secretKey: "![HN+okZzNzYmrceeDgWpRm2YQZXn3SUP2tr8DAMZxpM08OgXdHss9svqKLthAD6EvSvmeO59m/85TBvQHXJSOX/W9n8O1RSFisBLFK2co/98tcMin7H7DqDstqRcavrfS2UiErf3sGyhC1zGN03MAO1x7euYl0fm0UNZjsn6/AFugdPsb7pHr8jt7dRkV++ftIXu1wzAZMqvHTv/+PipsBKm0gLdSsZy33ccMQhp/6bBoXMl8qbLJOK7HdW1xSn0Kt0XuMz5rqAUIioNo5tK8f0TC6o2tKR/jcExRsVcG3zNsMf1nb72+ORlrkFkFDHKf8n/sFklL0w96DfVpkoLIrjaJ7WzCi+k+O0ViJ3SddGjtbvzNmLxcLSSBVe9wLrO9BLwPTiXYOgQMzmuMRB/kev3HP4okRRHAlTpwx0JuolqC1Ch1xIPYTfoL/OEQGeed7EakA4B4QbZkWU/jVbggMf/tg8swsO+zE9S4WgHhehEz+NXzLx6mPMqiQdMa0puuQYKU8OX61jaLw/soWpcsnBK+XrdG85mJDRubCBhMsyw+BNpD6kVzKzlYejtLYRx4DnHjcRiG/kSbWQkmpETiSOEKyVudJPcseukEJUCShE4QuyVGroDn82tnitokg12ftaNh0WY+5Gi/xf30iWKcCnWxc9vrAEqq99TY6cuukzgP5qul+THxcpGkg3S1U3pYQIchkWQlr4jFhEXLN1uawH8By8+xc1D2Yevb7zHQ90fx5efg+F1ZtYPz+FVFsUzMQRvz9t+bk58z2yqHSVj33yQUoc6JP79eJDjJ9Mkfd3fOjMVRzZAEM6NiJ4rJO/YJR83Q6VGYkuPe3XbzeEz3Iyt4ECdVjS7/UJoPit9XI/v+qIc3bA1gBwSiPrsfdp+r26zWr30by+PRGCLniZw+P03A1EvOLF5bqEIFOZe196HmTRTaNvQEJEG39nWA/KUktffXrAEJIrQoCXi7pT8B+K1sMtxKb5yqAF/ZyE9O7rYDZ4XF11FQo+ZMiZlNSBpeYuO8iGv/RB3TU/VyftoBAynoV9BKuEtaj/dSuIfYF0Qy85zgJgH4eGPbS0+r6iEAhEQTuXkZ8dfpCmKnAGQ3/UvXuWiAcbIpN+ek5Wtj0FYfLU6ecTS7ANc7kh89E+5zGwHJtIopM1ayyQX9tjXI6RPI1BcpSiazkcIE7zPaxAvz4VNoZigMH/6jtw5JCVaen3uvNOxMR7r3mba0UMutG7/d1kSF0bmHRLZl6/CyCeI7gNKhDZjb1PAMZUJ1eUc7HyXpinH7M6jCwmY5gFRB+Uywn/sGFEUBO2LCpV/FQU+AvVsNyaDYhnfCtH1NMPEyJ6fSMTBqaKdhCeJ/g11eEO/khYYMxBw2Ta0teLL3yfwi8ulx7140GCkVS4hsvh5ws7mAf2jQILsrHqBHyN8Iw0pxis5kbpb+kHnA9Z3AcLOsZNLu6ak2dtqBo0LnPBo7/skZ43hyZs5+m92jlx1MQeiTDbFETaNmryaORNbfVbGzJF619tkc5Bin4jl5GoKuNWLFmJv/TiLsw69faxlb2Ld/lbJvhT+30Jd8ZevfH/u4yLqX46V3aHCgo3ydvP0w0xtPmkIxDBsZLg9ENgMYt2AEhZ8GJYZtehiiv0XsDA53EiaTFJ/gX1lSh7/+sfrP3gVCQ7DEBbBah5uMyW08hNC+uKzRaS453WtKQz6YTflCWX9qpqsV/UsXvxjpooFZ+N97M1KBxUIotZy2UG18Efy7WrExg6AEpJH8lUlV4XBJm7McGVDyewTrwq93NIuRafhYwWDiFE3049HF+jySv2mGDAYjxY3oz4H7Ax6CptITSbMJ7GrhDFlHVxm0jpgO8SSKsSvTmJn5FkC8gqSO0oBLcr9zEWGuZ+CREcDDiehG+F2aY2cJDW+o2s1H87QkhHeGx6Us/nM8Z+HBqTN052elbqGp+PdLC4S7h8k8H4GRE7V3n6/2GkcOpCLs3tX2SYFdFCdImbVfuw6TrKDfnCRt1nMKNkbfZxWyKFM7d5YbbwIGrPjaHSTJOSZoEHovqRBkJhiN8YhtMBVRpf3BGUzVli3BQUi7Qxu4QZbgI4ClgBSd0ZWCjHJwaAI364XuugxsaBqXWcmqCycPckSPRumaAUrFY0hXZLcFIMhHS8SUbMhT2R4sXBTdUVDkrch2]"
  auth:
    userProfile:
      appSecret: "![7z5unqXLoB6Lf6X2oezR0cR608dT4SeB]"