# ==============================================================================
#  PROD SECURE PROPERTIES
#  Encrypt all values with the secure.key before committing.
#  Reference in XML:  ${secure::property.key}
#  Reference in DW:   p('secure::property.key')
# ==============================================================================

# --- Zsmart HTTP Requester ---
zsmart:
  userProfileToken: "![]"
  billingBalanceToken: "![]"
  billingHistoryToken: "![]"
  generateRechargeInvoiceToken: "![]"
  queryDisputeToken: "![]"
  queryInvoicePDFToken: "![]"