#%RAML 1.0 DataType 
type: object
properties:
  status:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: success
    required: false
  correlationId:
    type: string
    example: 4d7e8a21-92d5-4c61-b8b3-456789abcdef
    required: false
