#%RAML 1.0 DataType
type: object
properties:
  documentType:
    type: string
    required: true
    description: Tipo de documento del cliente destino.
    example: "NIT"
  documentNumber:
    type: string
    required: true
    description: Número de documento del cliente destino.
    example: "14589658"
  billingAccountNumber:
    type: string
    required: true
    description: ExternalID de la cuenta de facturación destino.
    example: "123456789"
  PAM:
    type: string
    required: true
    description: Ciclo OCS/cargue de recursos de la cuenta de facturación destino.
    example: "15"
  integrationId:
    type: string
    required: false
    description: Identificador único del servicio LTE del cliente.
    example: "AC-0000000"
  msisdn:
    type: string
    required: false
    description: MSISDN del cliente
    example: "3057135005"