#%RAML 1.0 DataType 
type: object
properties:
  serviceOrder:
    type: object
    properties:
      customer:
        type: object
        required: false
        properties:
          documentNumber:
            type: string
            example: '1023456789'
            required: false
          documentType:
            type: string
            example: CC
            required: false
          phone:
            type: string
            example: +57 3001234567
            required: false
      service:
        type: object
        required: false
        properties:
          serviceAccountNumber:
            type: string
            example: ACC-987654
            required: false
      orderType:
        type: string
        example: installation
        required: false
      causal:
        type: string
        example: customer request
        required: false
      operation:
        type: string
        example: create
        required: false
      detailOrder:
        type: object
        required: false
        properties:
          address:
            type: string
            example: Ciudadela colsubsidio en el conjunto residencial los Cambulos
            required: false
          city:
            type: string
            example: BOGOTA D.C.
            required: false
          contactEmail:
            type: string
            example: usuario@ejemplo.com
            required: false
          contactPhone:
            type: string
            example: '3165364514'
            required: false
          department:
            type: string
            example: CUNDINAMARCA
            required: false
          imei:
            type: string
            example: '358204101466619'
            required: false
          mail:
            type: string
            example: cliente@test.com
            required: false
          violence:
            type: boolean
            example: false
            required: false
          younger:
            type: boolean
            example: false
            required: false
          weapon:
            type: string
            example: '2'
            required: false
          suspensionPeriod:
            type: integer
            example: 30
            required: false
          codDaneCity:
            type: string
            example: '11001'
            required: false
          codDaneDepartment:
            type: string
            example: '11'
            required: false
          keepIps:
            type: boolean
            example: false
            required: false
          keepNumber:
            type: boolean
            example: false
            required: false
          mailbox:
            type: boolean
            example: false
            required: false
          latitude:
            type: number
            example: 4.697586
            required: false
          longitude:
            type: number
            example: -74.09126
            required: false
          plan:
            type: string
            example: ""
            required: false
          finishDate:
            type: datetime
            example: '2021-12-16T10:50:30.176Z'
            required: false
          initialDate:
            type: datetime
            example: '2021-12-16T10:50:30.176Z'
            required: false
          agrupationNumber:
            type: array
            required: false
            items:
              type: integer
