#%RAML 1.0 DataType
type: object
properties:
  tipoDocumento:
    type: string
    example: "CC"
    required: true
    minLength: 1
  numeroDocumento:
    type: string
    example: "1090409964"
    required: true
    minLength: 1
  referido:
    type: object
    properties:
      tipoDocumentoReferido:
        type: string
        example: "CC"
        required: true
        minLength: 1
      numeroDocumentoReferido:
        type: string
        example: "19433246"
        required: true
        minLength: 1