#%RAML 1.0 DataType
properties:
  documentType:
    type: string
    example: "NIT"
    required: true
    description: "Tipo de documento del cliente"
  documentNumber:
    type: string
    example: "14589658"
    required: true
    description: "Número de documento del cliente"
  planPackage:
    type: array
    items:
      properties:
        id:
          example: "CONTR0004925761"
          required: true
          description: "Identificador del plan/bundle"
  addonPackage:
    type: array
    required: false
    items:
      properties:
        id:
          example: "66382"
          required: false
          description: "Identificador de los Add-on o SVAs a aprovisionar en conjunto con el plan principal"
  subscriberId:
    type: string
    example: "12345"
    required: false
    description: "Identificador del suscriptor (Aplica para clientes existentes en la plataforma JSC)."
  MSISDN:
    type: string
    example: "3050000000"
    required: true
    description: "MSISDN de la línea a activar en la plataforma JSC"
  ICCID:
    type: string
    example: "8950000000000000000"
    required: true
    description: "ICCID de la línea a activar en la plataforma JSC"
  PAM:
    type: string
    example: "15"
    required: true
    description: "Ciclo OCS/cargue de recursos"
  integrationId:
    type: string
    example: "AC-0000000"
    required: true
    description: "Identificador único del servicio LTE del cliente."
  billingAccountNumber:
    type: string
    example: "123456789"
    required: true
    description: "ExternalID de la cuenta de facturación"
  parentPkgInstanceId:
    type: string
    example: "PKGID11_TS1708598971841"
    required: false
    description: "Identificador del package instance de una línea LTE padre que pertenece a una bolsa compartida (Group). Este key aplica únicamente cuando el aprovisionamiento corresponde a una línea 'Hija' de una bolsa compartida."

