#%RAML 1.0 DataType
properties:
  connectionNumber:
    type: string
    example: "CC202402211137"
    required: false
  simNumber:
    type: string
    example: "8957287000000000049"
  packageId?:
    type: string|nil
    example: "TestETBMVNE2_changeMSISDN"
  integrationId:
    type: string
    example: "1-XX,a000X,MDM-MOV-XXX"
    required: false

example: { "connectionNumber": "202402151107", "simNumber": "2135363763573", "packageId": "TestETBMVNE2_changeMSISDN", "integrationId": "a000" }