#%RAML 1.0 DataType
properties:
  addonPackage:
    type: array
    required: true
    items:
      properties:
        id:
          example: "66382"
          required: true
          description: "Identificador del Add-on o SVA a aprovisionar en conjunto con el plan principal"
        actionCode:
          example: "ADD - DELETE"
          required: true
          description: "Acción a ejecutar sobre el Add-on o SVA"
  integrationId:
    type: string
    example: "AC-0000000"
    required: false
    description: "Identificador único del servicio LTE del cliente."
  msisdn:
    type: string
    example: "3057135005"
    required: false
    description: "Identificador único del servicio LTE MSISDN del cliente."