#%RAML 1.0 DataType
type: object
xml:
  name: Envelope
  wrapped: true
properties:
  Header:
    type: nil
    required: false
  Body:
    type: object
    properties:
      doConsultarNumerosDisponibles:
        type: object
        properties:
          PeticionNumerosDisponibles:
            type: object
            properties:
              Categoria:
                type: string
                required: true
              CodigoPais:
                type: string
                required: false
              CodigoDepartamento:
                type: string
                required: false
              CodigoMunicipio:
                type: string
                required: false
              Distrito:
                type: string
                required: false
              NumeroActual:
                type: string
                required: false
              TecnologiaDestino:
                type: string
                required: false
              IdCuentaServicio:
                type: string
                required: false
              NumeroEspecifico:
                type: string
                required: false