#%RAML 1.0 DataType
properties:
  id_pqr: string
  app_consulta: string
  requiere_auditoria: boolean
  numero_solicitud_app: string
  aplicacion: string
  ip?: string
  navegador?: string
  nombre_equipo?: string
  usuario?: string