#%RAML 1.0 DataType

properties:
  getCoverageOpInput:
    type: object
    properties:
      wsRequestHeader:
        type: object
        properties:
          property:
            type: object
            properties:
              TransactionType:
                type: string | nil
                required: false
                examples: 
                  example1: "CEST"
                  example2: "PRCH"
      getCoverageRequest:
        type: object
        properties:
          address:
            type: string
            minLength: 1
            example: "CL 18A SUR 14D 102 PI 1"
          municipioCode: 
            type: string
            minLength: 1
            example: "25754"
          departamentoCode: 
            type: string
            minLength: 1
            example: "25"