#%RAML 1.0 DataType
type: object
properties:
  GeoDireccion:
    type: object
    properties:
      Chip:
        type: string
        required: true
        minLength: 1
      ClasePredio:
        type: string
        required: true
        minLength: 1
      DireccionDetallada:
        type: string
        required: true
        minLength: 1
      EstratoCatastro:
        type: number
        required: true
      FechaActualizacionDetalle:
        type: string
        required: true
        minLength: 1
      FechaModificacionAddress:
        type: string
        required: true
        minLength: 1
      IdAddress:
        type: string
        required: true
        minLength: 1
      IdBarrio:
        type: string
        required: true
        minLength: 1
      IdDepartamento:
        type: string
        required: true
      IdLocalidad:
        type: string
        required: true
      IdMunicipio:
        type: string
        required: true
      IdPredio:
        type: string
        required: true
        minLength: 1
      Latitud:
        type: number
        required: true
      Longitud:
        type: number
        required: true
      Predio:
        type: string
        required: true
        minLength: 1
      TipoAccion:
        type: string
        required: true
        minLength: 1
      TipoDistancia:
        type: string
        required: true
        minLength: 1
      Type:
        type: string
        required: true
        minLength: 1
        
example:
  !include ../../examples/request/geoDireccionExample.raml