#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: VOICEBOT
            required: false
      Duration:
        type: string
        example: '120'
        required: false
      Id_ETA:
        type: string
        example: ''
        required: false
      Id_PQR:
        type: string
        example: MDM-PQR-51471111
        required: false
      New_Date:
        type: date-only
        example: '2025-05-31'
        required: false
      Timeslot:
        type: string
        example: AM3 - 10:00 12:00
        required: false
