#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Document_Type:
        type: string
        example: CC
        required: false
      Document_Number:
        type: string
        example: '80955088'
        required: false
      Pre_Order:
        type: string
        example: string
        required: false
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: whatsapp
            required: false
