#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Customer:
        type: object
        properties:
          Document_Type:
            type: string
            example: CC
            required: false
          Document_Number:
            type: string
            example: '102000066'
            required: false
          Names:
            type: string
            example: Rodrigo
            required: false
          Lastnames:
            type: string
            example: Cadena
            required: false
          Email:
            type: string
            example: cadena@gmail.com
            required: false
          TyC:
            type: string
            example: Si
            required: false
      Access:
        type: object
        properties:
          Id:
            type: string
            example: '3219415000'
            required: false
          Name:
            type: string
            example: WhatsApp
            required: false
          Parameters:
            type: array
            items:
              type: object
              properties:
                Parameter:
                  type: string
                  example: ''
                  required: false
                Value:
                  type: string
                  example: ''
                  required: false
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: whatsapp
            required: false

