#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Audit:
        type: object
        properties:
          Browser:
            type: string
            example: Chrome
            required: false
          IP:
            type: string
            example: 192.168.1.1
            required: false
          User_Agent:
            type: string
            example: Mozilla/5.0...
            required: false
      Mail:
        type: string
        example: usuario@ejemplo.com
        required: false
      Password:
        type: string
        example: cifrado_con_tripledes_base64
        required: false

