#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: object
    properties:
      System:
        type: object
        properties:
          name:
            type: string
            example: MIETB
            required: false
          correlationID:
            type: string
            example: '{{correlationID}}'
            required: false
      Property:
        type: array
        items: {}
  WSRequestBody:
    type: object
    properties:
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: WEB
            required: false
          WhatsApp_Phone_Number:
            type: string
            example: ''
            required: false
      Departament_DANE:
        type: string
        example: '05'
        required: false
