#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Id_PQR:
        type: string
        example: MDM-PQR-4159147
        required: false
      Date:
        type: date-only
        example: '2025-07-26'
        required: false
      Timeslot:
        type: string
        example: PM2
        required: false
      Duration:
        type: string
        example: '120'
        required: false
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: Whatsapp
            required: false

