#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: WEB
            required: false
          WhatsApp_Phone_Number:
            type: string
            example: ''
            required: false
      Normalize:
        type: boolean
        example: true
        required: false
      Phone:
        type: string
        example: '6018008846'
        required: false


