#%RAML 1.0 DataType
type: !include ../billing-process-response-base.raml
discriminatorValue: CUSTOMER_UPDATE
properties:
  transactionId:
    type: string
    example: TRX20260319014567
    required: false
  processCode:
    type: string
    required: false
  status:
    type: string
    example: SUCCESS
    required: false
  updatedAt:
    type: string
    example: '2026-03-19T10:00:01Z'
    required: false
  result:
    type: object
    required: false
    properties:
      customerId:
        type: string
        example: '12345678'
        required: false
      zsmartResponseCode:
        type: string
        example: '0'
        required: false
      zsmartMessage:
        type: string
        example: Success
        required: false
