#%RAML 1.0 DataType
type: !include ../billing-process-response-base.raml
discriminatorValue: RESTORATION_FRAUD
properties:
  transactionId:
    type: string
    example: e5f6a7b8-c9d0-1234-efab-234567890123
    required: false
  processCode:
    type: string
    required: false
  status:
    type: string
    example: SUCCESS
    required: false
  updatedAt:
    type: string
    example: '2026-03-19T10:00:01Z'
    required: false
  result:
    type: object
    required: false
    properties:
      customerId:
        type: string
        example: '12345678'
        required: false
      serviceId:
        type: string
        example: '98765'
        required: false
      serviceStatus:
        type: string
        example: ACTIVE
        required: false
      zsmartResponseCode:
        type: string
        example: '0'
        required: false
      zsmartMessage:
        type: string
        example: Success
        required: false