#%RAML 1.0 DataType

properties:
    quotaCalculationResponse:
        type: object
        required: true
        properties:
            quotaCalculationResult:
                type: object
                required: true
                properties:
                    requestId:
                        type: number
                        required: true
                        example: 1245959595955.099
                    controlDate:
                        type: string
                        required: true
                    businessName:
                        type: string
                        required: false
                    nit:
                        type: string
                        required: false
                    approvedQuota:
                        type: number
                        required: true
                    score:
                        type: number
                        required: true
                    riskLevel:
                        type: string
                        required: false
                    errorId:
                        type: number
                        required: true
                    errorMessage:
                        type: string
                        required: false
                    rejectionReason:
                        type: string
                        required: false
            

