#%RAML 1.0 DataType
  properties:
    crearOrdenRequestResponse:
      required: true
      type: object
      properties:
        return:
          required: false
          type: object
          properties:
            wsResponseHeader2:
              required: true
              type: object
              properties:
                system:
                  required: true
                  type: object
                  properties:
                    name:
                      required: true
                      type: string
                      example: "InOrder"
                    correlationID:
                      required: true
                      type: string
                      example: "OPL-SUPPLADHL"
                    processingServer:
                      required: true
                      type: string
                      example: "srv-lrh-dc-inttig"
                service:
                  required: true
                  type: object
                  properties:
                    status:
                      required: true
                      type: string
                      example: "PASSS"
                    responseDate:
                      required: true
                      type: string
                      example: "2022-04-24T08:34:57.131-05:00"
                    statusDetail:
                      required: true
                      type: object
                      properties:
                        errorCode:
                          required: true
                          type: number
                          example: 0
                        errorMessage:
                          required: true
                          type: string
                          example: "El MSG se proceso Correctamentamente"
            crearOrdenIn:
              required: true
              type: object
              properties:
                recibido:
                  type: boolean
                  example: true                   

