#%RAML 1.0 DataType

properties:
  validateQuestionnaireResponse:
    type: object
    required: false
    properties:
      validateQuestionnaireResult:
        type: object
        required: false
        properties:
          validateQuestionnaire:
            type: number
            required: true
            example: 2652
          processResult:
            type: string
            required: false
            example: "CUESTIONARIO YA FUE VALIDADO"
          validationResult:
            type: string
            required: false
            example: ""
          score:
            type: string
            required: false
            example: "0"
          offer:
            type: string
            required: false
            example: ""
          controlDate:
            type: datetime
            required: false
            example: 2022-09-02T15:21:36.8799835-05:00
          identification:
            type: string
            required: false
            example: ""