#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: integer
    example: 200
    required: false
  messageResponse:
    type: string
    example: OK
    required: false
  employee:
    type: object
    properties:
      workforceID:
        type: string
        example: '10203040'
        required: false
      fullName:
        type: string
        example: Jane Smith ep Lamborgizzia
        required: false
      email:
        type: string
        example: empleado.etb@etb.com.co
        required: false
      telephoneNumber:
        type: string
        example: '3004567890'
        required: false
      status:
        type: string
        example: ACTIVO
        required: false
