#%RAML 1.0 DataType
type: object
displayName: QuestionnaireResponse
properties:
  questionnaireId:
    type: string
    required: true
  processResult:
    type: string
    required: true
  controlDate:
    type: string
    required: true
    description: ISO-8601 datetime returned by the service
    example: "2022-04-01T00:16:18.056377-05:00"
  questions:
    type: array
    required: true
    items:
      type: object
      properties:
        questionDescription:
          type: string
          required: true
        answers:
          type: array
          required: true
          items:
            type: string