#%RAML 1.0 DataType
properties:
  RNEMSISDN:
    type: array
    items:
      properties:
        Msisdn:
          type: any
        NombrePersona: 
          type: string
        TipoDocumento: 
          type: string
        NumeroDocumento: 
          type: string
        Email:
          type: string
        Solicitud:
          type: string
        SistemaOrigen:
          type: string
        ConfirmacionCrc:
          type: string
        Estado:
          type: string