properties:
  WSRegistroNegativoResponse:
    type: object
    properties:
      WSResponseHeader:
        type: object
        properties:
          System:
            type: object
            properties:
              name:
                type: string
                required: false
              correlationID:
                type: string
                required: false
              processingServer:
                type: string
                required: false
          Service:
            type: object
            properties:
              status:
                type: string
                required: false
              responseDate:
                type: string
                required: false
      RegistroNegativo:
        type: object
        properties:
          Header:
            type: object
            properties:
              Code:
                type: string
                required: true
              Desc:
                type: string
                required: true
          Body:
            type: object
            required: false
            properties:
              RegistroNegativoResponse:
                type: object
                properties:
                  RegistroNegativoResult:
                    type: number
                    required: true