#%RAML 1.0 DataType
properties:
  AcuerdoRsp:
    type: object
    properties:
      Cuenta: string
      Aplicacion: string
      AcuerdoId: string
      AcuerdoNombre: string
      Vencimiento: string
  Documentos:
    type: object
    properties:
      Id: string
      Nombre: string