#%RAML 1.0 DataType
properties:
  WSResponseVerificaDocumentoCIFIN:
    properties:
      ResponseCIFIN:
        properties:
          infoCliente:
            properties:
              sTipoIdentificacion:
                type: string | nil
                required: false
              sNumeroIdentificacion:
                type: string | nil
                required: false
              sNombreTitular:
                type: string | nil
                required: false
              sNombreCiiu:
                type: string | nil
                required: false
              sLugarExpedicion:
                type: string | nil
                required: false
              sFechaExpedicion:
                type: string | nil
                required: false
              sEstado:
                type: string | nil
                required: false
              sEstadoTitular:
                type: string | nil
                required: false
              sRangoEdad:
                type: string | nil
                required: false
              sCodigoCiiu:
                type: string | nil
                required: false
              sCodigoDepartamento:
                type: string | nil
                required: false
              sCodigoMunicipio:
                type: string | nil
                required: false
              sFecha:
                type: string | nil
                required: false
              sHora:
                type: string | nil
                required: false
              sEntidad:
                type: string | nil
                required: false
              sRespuestaConsulta:
                type: string | nil
                required: false
              sNombre1:
                type: string | nil
                required: false
              sNombre2:
                type: string | nil
                required: false
              sDe:
                type: string | nil
                required: false
              sApellido1:
                type: string | nil
                required: false
              sApellido2:
                type: string | nil
                required: false
              sGenero:
                type: string | nil
                required: false
              sCodigoEstado:
                type: string | nil
                required: false
              sReporteConsolidado:
                properties:
                  sContCuentasAhorros:
                    type: string | nil
                    required: false
                  sContCuentasCorrientes:
                    type: string | nil
                    required: false
                  sContFinanciero:
                    type: string | nil
                    required: false
                  sContSolidario:
                    type: string | nil
                    required: false
                  sContRealServicios:
                    type: string | nil
                    required: false
                  sContRealComercio:
                    type: string | nil
                    required: false