#%RAML 1.0 DataType
properties:
    UsuarioCreacion:
      type: string
    FechaCreacion:
      type: string
    TotalValoresConfig:
      type: number
    Estado:
      type: string
    Operacion:
      type: string
    ProductCodeSF:
      type: string
    Parametro:
      type: array
      items:
        properties:
          Nombre:
            type: string
          Atributo:
            type: string
          Valor:
            type: string

example:
  !include ../../examples/responses/billingHomologationResponse.json