#%RAML 1.0 DataType
properties:
  Codigo:
    type: number
    example: 1.0
  ANS_Contrato:
    type: number
    example: 0.0
  ANS_Mayorista:
    type: number
    example: 48.0
  Automatico_Remedy:
    type: boolean
    example: true
  Fecha_Creacion:
    type: string
    example: "2022-09-23T16:16:01.112Z"
  Motivo:
    type: string
    example: "CRUCE DE PUERTO LOGICO"
  Tecnologia:
    type: string
    example: "FTTH"
  Usuario_Creacion:
    type: string
    example: "juanro13"
  Usuario_Modificacion:
    type: string
    example: "juanro13"
  Id_Mayorista:
    type: number
    example: 2.0
  Grupo_Remedy:
    type: string
    example: "ALISTAMIENTO GESTION QUIEBRES"