#%RAML 1.0 DataType
properties:
  _id:
    type: string
    example: "591d21fdec96a3693730df02"
  Tipo_Documento:
    type: string
    example: "CC"
  Tipo_Cliente:
    type: string
    example: "FIBRA"
  Numero_Identificacion:
    type: string
    example: "1090409964"
  Nombre_Cliente:
    type: string
    example: "GRACE PATRICIA GONZALEZ"
  Estado:
    type: string
    example: "LOCALIDAD"
  Segmento:
    type: string
    example: "NO_MIGRADO"
  Segmento_UEN:
    type: string
    example: "NO_MIGRADO"
  UEN:
    type: string
    example: "NO_MIGRADO"
  Cliente_Valor:
    type: string
    example: ""
  Telefono_Fijo:
    type: string
    example: "00000000"
  Telefono_Movil: 
    type: string
    example: "3166300053"
  Correo_Electronico:
    type: string
    example: "GRACEGONZALEZORTIZ@GMAIL.COM"
  Direccion:
    type: string
    example: "KR 00 000 00"
  Cobertura:
    type: string
    example: "FIBRA"
  Pais:
    type: string
    example: "Colombia"
  Departamento:
    type: string
    example: "BOGOTA"
  Ciudad:
    type: string
    example: "BOGOTA D.C."
  Barrio: 
    type: string
    example: "BARRION"
  Localidad:
    type: string
    example: "LOCALIDAD"
  Estrato: 
    type: string
    example: "LOCALIDAD"
  Usuario_Creador:
    type: string
    example: "PortalLTE"
  Usuario_Modificador:
    type: string
    example: "admin"
  Autorizacion_Datacredito:
    type: string
    example: "true"
  Fecha_Expedicion_Documento:
    type: string
    example: "10/10/2018"
  Fecha_Nacimiento:
    type: string
    example: "1989-10-10"
  Genero: 
    type: string
    example: "FEMENINO"
  Rango_Edad: 
    type: string
    example: "\"\""
  Estado_Civil:
    type: string
    example: "\"\""
  Ciudad_Exp_Documento:
    type: string
    example: "\"\""
  Depto_Exp_Documento:
    type: string
    example: "\"\""
  Scoring:
    type: string
    example: "\"\""
  Tipo_Scoring:
    type: string
    example: "\"\""
  Clasificacion_Scoring:
    type: string
    example: "\"\""
  Fecha_Scoring:
    type: string
    example: "\"\""
  Fecha_Actualizacion:
    type: string
    example: "2018-10-16T11:16:27.898+0000"
  Sistema_Origen:
    type: array
    items:
      type: object
      properties:
        Id_Sistema_Origen:
          type: string
          example: "1-F0AFNUO"
        Sistema_Origen: 
          type: string
          example: "FIBRA"
  Contacto:
    type: array
    items:
      type: object
      properties:
        _id:
          type: string
          example: "000000000000000000000000"
        Tipo_Documento:
          type: string
          example: "CC"
        Numero_Documento:
          type: string
          example: "12399878"
        Nombre_Contacto: 
          type: string
          example: "daniel camilo"
        Telefono_Contacto:
          type: string
          example: "45676545"
        Movil_Contacto:
          type: string
          example: "2222222222"
        Email_Contacto:
          type: string
          example: "Dan@hotmail.com"
        Direccion_Asociada:
          type: string
          example: "fdcvbjhg"
        Pais:
          type: string
          example: ""
        Departamento:
          type: string
          example: ""
        Ciudad:
          type: string
          example: ""
        Localidad:
          type: string
          example: ""
        Barrio:
          type: string
          example: ""
        Estrato:
          type: string
          example: ""
        Autorizado:
          type: boolean
          example: false
        actualizacion_extractor:
          type: string
          example: "1"
        Nombre_Individual:
          type: string | nil
          example: null 
        Primer_Apellido:
          type: string
          example: "valbuena"
        Segundo_Apellido:
          type: string
          example: "ROZO"
        Codigo_DANE:
          type: string | nil
          example: null
  Modificado_MDM:
    type: string
    example: "0"
  Id_Cuenta_Facturacion_Salesforce:
    type: string | nil
    example: null
  Ejecutivo_Experiencia:
    type: string
    example: "MDM_PLTE"
  actualizacion_extractor: 
    type: string
    example: "05/11/2020"
  Nombres:
    type: string
    example: "GRACE"
  Primer_Apellido:
    type: string
    example: "PATRICIA"
  Segundo_Apellido:
    type: string
    example: "GONZALEZ"
  Direcciones:
    type: array
    items:
      type: object
      properties:
        Id_Direccion: 
          type: integer
          example: 2
        Tipo_Direccion:
          type: string
          example: "INSTALACION"
        Direccion_Normalizada:
          type: string
          example: "KR 23 83 41 IN 1 AP 302"
        Codigo_Direccion:
          type: string | nil
          example: "612802304578628638"
        Codigo_Departamento:
          type: string | nil
          example: "11"
        Codigo_Municipio:
          type: string | nil
          example: "11001"
        Codigo_Pais:
          type: string | nil
          example: "593b0ac99a8e4177d410df4d"
        Codigo_DANE:
          type: string | nil
          example: null
        Nombre_Direccion:
          type: string | nil
          example: null
        Estado:
          type: string | nil
          example: "A"
        Cobertura:
          type: object
          properties:
            Codigo_Lote:
              type: string | nil
              example: "11"
            Distrito:
              type: string | nil
              example: null
            Localidad:
              type: string | nil
              example: null
            Estrato:
              type: integer
              example: 4
            Latitud: 
              type: number
              example: 4.671486484
            Longitud:
              type: number
              example: -74.06268689
            Direccion_GIS:
              type: string | nil
              example: "612802304578628638"
            Molecula:
              type: string | nil
              example: null
            Proposito:
              type: string | nil
              example: "01"
            Tecnologia:
              type: string | nil
              example: "FTTH"
            Zona:
              type: string | nil
              example: "CHICO"
            Tipo_Cobertura:
              type: string | nil
              example: "MOLECULA"
            NombreCobertura:
              type: string | nil
              example: "FCO34"
  Categoria:
    type: string | nil
    example: null
  EsquemaAtencion:
    type: string | nil
    example: null
  ServiciosPS:
    type: string | nil
    example: null        





  



