#%RAML 1.0 DataType
properties:
  tipo:
    type: string
  consecutivo:
    type: string
  resultado: 
    type: string
  fecha:
    type: string
  descripcion:
    type: string

example: !include ../../examples/responses/consecutiveResponse.raml