#%RAML 1.0 DataType
type: object
properties:
  status:
    type: number
    required: true
    description: Indicates the HTTP error status code returned
  code:
    type: string
    required: true
    description: Indicates the error type code that caused it
  message:
    type: object
    properties:
      message:
        type: string
        required: true
        description: Brief description of what caused the error
  messageServer:
    type: any
    required: true
    description: Details of the error
  cause:
    type: array
    required: true
    items:
      properties:
        origin:
          type: string
          required: true
          description: Application's name
        message:
          type: string
          required: true
          description: Exception cause