#%RAML 1.0 DataType
type: object
displayName: MVNE_SMSC_EnrutadorDatos
description: Documento de la colección MVNE_SMSC_EnrutadorDatos (cola de mensajes).

properties:
  _id:
      type: string
      description: Identificador único del documento (MongoDB ObjectId).
      pattern: "^[a-fA-F0-9]{24}$"
      example: "65dc522ba22f9ee05a9be9b1"
  message:
    type: string
    description: Contenido o payload del mensaje (serializado como string).
    example: "{ \"destinations\": [\"57300111222\"], \"category\": \"REGULATORY\", \"messageText\": \"Bienvenido\", \"senderNumber\": \"3005880000\" }"

  createdAt:
    type: datetime
    description: Marca de tiempo para la creación del mensaje.
    example: "2025-03-17T01:58:59Z"

  status:
    type: string
    description: Estado del mensaje.
    enum: [pending, processing, processed]
    example: "pending"

  priority:
    type: string
    description: Prioridad del mensaje.
    example: "1"
