#%RAML 1.0 DataType
properties:
  codigo:
    type: string
    example: "400"
  titulo:
    type: string
    example: "PQR no fue encontrada"
  detalle: 
    type: string
    example: "Al consultar la PQR no fue encontrada"