#%RAML 1.0 DataType
properties:
  "_id": string
  "Actualizacion_Contraseña": boolean 
  "FechaActivacion": datetime
  "FechaExpedicion?": datetime
  "FechaModificacion": datetime
  "Estado": boolean 
  "Identificador_Peticion_Creacion": string
  "Mail": string
  "NumIdentificacion": string
  "Password": string
  "Requiere_Actualizar_Pwd": boolean
  "TipoIdentificacion": string 
  "TipoRegistro": string
  "Widgets": 
    type: array
    items:
      type: object
      properties:
        "Application_Date": datetime
        "Widget":
          type: object
          properties:
            "_id": string
            "Widget": string
  "Accesos?":
    type: array
    items:
      type: object
      properties:
        "Canal": string
        "Fecha_Ultimo_Acceso": datetime
        "IP": string 
        "Sistema": string 
  "CorreoElectronicoAlterno?": string
  "Hobbies?": string[]
  "Nivel_Educativo?": string
  "UsuarioFacebook?": string | nil
  "UsuarioTwitter?": string | nil
  "Auth_Movil?": string | nil
  "Estado_Registro?": string
  "FechaIngreso?": datetime
  "IP?": string | nil
  "Numero_Orden?": string | nil
