#%RAML 1.0 DataType
type: object
properties:
  _id:
    type: object
    properties:
      oid:
        type: string
        example: "5dd1516cc7c6a014540ed804"
  Fecha_Creacion:
    type: string
    example: "2019-11-17T08:55:56.728Z"
  Usuario_Creacion: 
    type: string
    example: "valechar"
  "Fecha_Modificacion":
    type: string
    example: "2021-04-21T14:16:30.547Z"
  "Usuario_Modificacion": 
    type: string
    example: "marilarc"
  "Id_Cuenta_Servicio": 
    type: string
    example: "CS-165153"
  "Bundle":
    type: object
    properties:
      _id:
        type: object
        properties:
          oid:
            type: string
            example: "5c351f4c06c0d40f50a27aa4"
      "Codigo_Configuracion": 
        type: string | nil
        example: null
      "Numero_Agrupacion":
        type: number
        example: 1643
      "Tipo_Producto": 
        type: string
        example: "BUNDLE"
      "Tipo_Servicio": 
        type: string
        example: "FTTC"
      "Subtipo_Servicio": 
        type: string | nil
        example: null
      "Subtipo_Producto": 
        type: string | nil
        example: null
      "Secuencia":
        type: number
        example: 0
      "Dependencia":
        type: number
        example: 0
      "Clasificacion": 
        type: string
        example: "SERVICIO"
      "Nombre": 
        type: string
        example: "DUO 10M"
      "Icono": 
        type: string | nil
        example: null
      "Display": 
        type: string | nil
        example: null
      "Estado": 
        type: string
        example: "Activo"
      "Cantidad_Minima":
        type: number
        example: 1
      "Cantidad_Maxima":
        type: number
        example: 1
      "Precio_Oferta": 
        type: array
        items:
          type: object
          properties:
            "Canal_Venta": 
              type: string | nil
              example: null
            "Precio_Sin_Iva": 
              type: number
              example: 68900.0
            "Precio_Con_Iva": 
              type: number
              example: 68900.0
            "Iva": 
              type: number
              example: 0.0
      "Caracteristicas_Producto_Oferta":
        type: array
        example: []
      "Id_Clase_Servicio":
        type: number
        example: 0
      "Disponibilidad":
        type: boolean
        example: false
      "Agendamiento":
        type: boolean
        example: false
      "Aprovisionamiento":
        type: boolean
        example: false
      "Facturacion":
        type: boolean
        example: false
      "Accion": 
        type: string | nil
        example: null
      "Id_Item": 
        type: string | nil
        example: null
      "Id_Item_Padre": 
        type: string | nil
        example: null
      "Id_Tipo_Producto":
        type: number
        example: 0
      "Id_Tipo_Servicio":
        type: number
        example: 3
      "Id_Subtipo_Servicio":
        type: number
        example: 0
      "Id_Subtipo_Producto":
        type: number
        example: 0
      "Id_Servicio": 
        type: string
        example: "CS-165153"
      "id_opcional_auxiliar": 
        type: string | nil
        example: null
      "Atributos":
        type: array
        example: []
      "tipo_adicional": 
        type: string | nil
        example: null
      "Parametros_Producto": 
        type: string | nil
        example: null
      "seleccionado":
        type: boolean
        example: false
      "deshabilitado":
        type: boolean
        example: false
      "Parametros_bundle":
        type: array
        items:
          type: object
          properties:
            "Parametro": 
              type: string
              example: "ESTRATO"
            "Tipo_Parametro": 
              type: string
              example: "Parámetro General"
            "Valor": 
              type: string
              example: "1/2"
      "Primarios":
        type: array
        items:
          type: object
          properties:
            "_id":
              type: object
              properties:
                "oid":
                  type: string
                  example: "5c3523cb06c0d40f50a27ae8"
            "Codigo_Configuracion": 
              type: string
              example:  "133240"
            "Numero_Agrupacion": 
              type: number
              example: 1643
            "Tipo_Producto": 
              type: string
              example: "Primario"
            "Tipo_Servicio": 
              type: string
              example: "FTTC"
            "Subtipo_Servicio": 
              type: string
              example: "FTTC INTERNET"
            "Subtipo_Producto":
              type: string | nil
              example: null
            "Secuencia":
              type: number
              example: 120
            "Dependencia":
              type: number
              example: 120
            "Clasificacion": 
              type: string | nil
              example: null
            "Nombre": 
              type: string
              example: "INTERNET FTTC"
            "Icono": 
              type: string | nil
              example: null
            "Display": 
              type: string | nil
              example: null
            "Estado": 
              type: string
              example: "Activo"
            "Cantidad_Minima":
              type: number
              example: 0
            "Cantidad_Maxima":
              type: number
              example: 0
            "Id_Clase_Servicio":
              type: number
              example: 1100
            "Disponibilidad":
              type: boolean
              example: true
            "Agendamiento":
              type: boolean
              example: true
            "Aprovisionamiento":
              type: boolean
              example: true
            "Facturacion":
              type: boolean
              example: false
            "Accion": 
              type: string | nil
              example: null
            "Id_Item": 
              type: string
              example: "1"
            "Id_Item_Padre": 
              type: string | nil
              example: null
            "Id_Tipo_Producto":
              type: number
              example: 1
            "Id_Tipo_Servicio":
              type: number
              example: 3
            "Id_Subtipo_Servicio":
              type: number
              example: 32
            "Id_Subtipo_Producto":
              type: number
              example: 0
            "Id_Servicio": 
              type: string
              example: "SR-3461823"
            "id_opcional_auxiliar": 
              type: string | nil
              example: null
            "Atributos": 
              type: array
              items:
                type: object
                properties:
                  "Nombre":
                    type: string
                    example: "FAMILIA"
                  "Valor":
                    type: string
                    example: "XDSL"
                  "Tipo":
                    type: string
                    example: "Agendamiento"
            "tipo_adicional": 
              type: string | nil
              example: null
            "Parametros_Producto": 
              type: string | nil
              example: null
            "seleccionado":
              type: boolean
              example: false
            "deshabilitado":
              type: boolean
              example: false
            "Secundarios":
              type: array
              items:
                type: object
                properties:
                  "_id":
                    type: object
                    properties:
                      "oid":
                        type: string
                        example: "5c3523cb06c0d40f50a27aea"
                  "Codigo_Configuracion":
                    type: string
                    example: "23323210303"
                  "Numero_Agrupacion":
                    type: number
                    example: 1643
                  "Tipo_Producto":
                    type: string
                    example: "SECUNDARIO"
                  "Tipo_Servicio":
                    type: string
                    example: "FTTC"
                  "Subtipo_Servicio":
                    type: string
                    example: "FTTC INTERNET"
                  "Subtipo_Producto":
                    type: string | nil
                    example: null,
                  "Secuencia":
                    type: number
                    example: 140
                  "Dependencia":
                    type: number
                    example: 120
                  "Clasificacion":
                    type: string | nil
                    example: null
                  "Nombre":
                    type: string
                    example: "PLAN 10M / 5M"
                  "Icono":
                    type: string | nil
                    example: null
                  "Display":
                    type: string | nil
                    example: null
                  "Estado":
                    type: string
                    example: "Activo"
                  "Cantidad_Minima":
                    type: number
                    example: 1
                  "Cantidad_Maxima":
                    type: number
                    example: 1
                  "Id_Clase_Servicio":
                    type: number
                    example: 2101
                  "Disponibilidad":
                    type: boolean
                    example: true
                  "Agendamiento":
                    type: boolean
                    example: false
                  "Aprovisionamiento":
                    type: boolean
                    example: true
                  "Facturacion":
                    type: boolean
                    example: true
                  "Accion":
                    type: string | nil
                    example: null
                  "Id_Item":
                    type: string
                    example: "2"
                  "Id_Item_Padre":
                    type: string | nil
                    example: null
                  "Id_Tipo_Producto":
                    type: number
                    example: 2
                  "Id_Tipo_Servicio":
                    type: number
                    example: 3
                  "Id_Subtipo_Servicio":
                    type: number
                    example: 32
                  "Id_Subtipo_Producto":
                    type: number
                    example: 3210
                  "Id_Servicio":
                    type: string
                    example: "SR-3461824"
                  "id_opcional_auxiliar":
                    type: string | nil
                    example: null
                  "Atributos":
                    type: array
                    items:
                      type: object
                      properties:
                        "Nombre":
                          type: string
                          example: "CAPACIDAD DE CARGA"
                        "Valor":
                          type: string
                          example: "100M"
                        "Tipo":
                          type: string
                          example: "Disponibilidad"
                  "tipo_adicional":
                    type: string | nil
                    example: null
                  "Parametros_Producto":
                    type: string | nil
                    example: null
                  "seleccionado":
                    type: boolean
                    example: false
                  "deshabilitado":
                    type: boolean
                    example: false
            "Adicionales":
              type: array
              example: []
            "Gold":
              type: string
              example: ""
            "Numero":
              type: string
              example: ""
  "Opcionales":
    type: array
    items:
      type: object
      properties:
        "_id": 
          type: object
          properties:
            "oid":
              type: string
              example: "5ba11534947dfd0c04b4c906"
        "Codigo_Configuracion":
          type: string
          example: "33313130572"
        "Numero_Agrupacion":
          type: number
          example: 0
        "Tipo_Producto":
          type: string
          example: "Opcional"
        "Tipo_Servicio":
          type: string
          example: "FTTC"
        "Subtipo_Servicio":
          type: string
          example: "FTTC VOZ"
        "Subtipo_Producto":
          type: string
          example: "FTTC VOZ - SERVICIOS SUP."
        "Secuencia":
          type: number
          example: 572
        "Dependencia":
          type: number
          example: 0
        "Clasificacion":
          type: string
          example: "SERVICIO"
        "Nombre":
          type: string
          example: "CONTESTADOR VIRTUAL"
        "Icono":
          type: string | nil
          example: null
        "Display":
          type: string | nil
          example:  null
        "Estado":
          type: string
          example: "Activo"
        "Cantidad_Minima":
          type: number
          example: 1
        "Cantidad_Maxima":
          type: number
          example: 1
        "Precio_Oferta":
          type: array
          example: []
        "Caracteristicas_Producto_Oferta":
          type: array
          example: []
        "Id_Clase_Servicio":
          type: number
          example: 2208
        "Disponibilidad":
          type: boolean
          example: false
        "Agendamiento":
          type: boolean
          example: false
        "Aprovisionamiento":
          type: boolean
          example: true
        "Facturacion":
          type: boolean
          example: false
        "Accion":
          type: string | nil
          example:  null
        "Id_Item":
          type: string
          example: "15"
        "Id_Item_Padre":
          type: string | nil
          example:  null
        "Id_Tipo_Producto":
          type: number
          example: 3
        "Id_Tipo_Servicio":
          type: number
          example: 3
        "Id_Subtipo_Servicio":
          type: number
          example: 31
        "Id_Subtipo_Producto":
          type: number
          example: 3130
        "Id_Servicio":
          type: string
          example: "SR-3461837"
        "id_opcional_auxiliar":
          type: string | nil
          example:  null
        "Atributos":
          type: array
          example:  []
        "tipo_adicional":
          type: string | nil
          example:  null
        "Parametros_Producto":
          type: array
          items:
            type: object
            properties:
              "Parametro": 
                type: string  
                example: "ESTRATO"
              "TipoParametro": 
                type: string  
                example: "Parámetro General"
              "Valor":  
                type: string  
                example: "1/2/3/4/5/6"
        "seleccionado":
          type: boolean
          example: false
        "deshabilitado":
          type: boolean
          example: false
  "Promociones":
    type: array
    example: []
  "Cliente":
    type: object
    properties: 
      "_id":
        type: object
        properties:
          "oid": 
            type: string
            example: "000000000000000000000000"
      "Fecha_Creacion":
        type: string
        example: "2019-11-17T08:55:56.728Z"
      "Usuario_Creacion":
        type: string | nil
        example: null,
      "Fecha_Modificacion":
        type: string
        example: "2019-11-17T08:55:56.728Z"
      "Id_Cuenta_Cliente":
        type: number
        example: 0
      "Tipo_Documento":
        type: string
        example: "CC"
      "Numero_Documento":
        type: string
        example: "1073716704"
  "Estado":
    type: object
    properties:
      "Principal": 
        type: object
        properties:
          "Codigo": 
            type: string
            example: "2"
          "Descripcion": 
            type: string
            example: "Pendiente"
          "Fecha": 
            type: string
            example: "2019-11-17T08:55:56.728Z"
      "Pago": 
        type: object
        properties:
          "Codigo": 
            type: string
            example: "2"
          "Descripcion": 
            type: string
            example: "Pendiente"
          "Fecha": 
            type: string
            example: "2019-11-17T08:55:56.728Z"
      "Fraude": 
        type: object
        properties:
          "Codigo": 
            type: string
            example: "2"
          "Descripcion": 
            type: string
            example: "Pendiente"
          "Fecha": 
            type: string
            example: "2019-11-17T08:55:56.728Z"
      "Tramite": 
        type: object
        properties:
          "Codigo": 
            type: string
            example: "2"
          "Descripcion": 
            type: string
            example: "Pendiente"
          "Fecha": 
            type: string
            example: "2019-11-17T08:55:56.728Z"
      "Voluntaria": 
        type: object
        properties:
          "Codigo": 
            type: string
            example: "2"
          "Descripcion": 
            type: string
            example: "Pendiente"
          "Fecha": 
            type: string
            example: "2019-11-17T08:55:56.728Z"
      "RoboPerdida": 
        type: object
        properties:
          "Codigo": 
            type: string
            example: "2"
          "Descripcion": 
            type: string
            example: "Pendiente"
          "Fecha": 
            type: string
            example: "2019-11-17T08:55:56.728Z"
  "Id_Cuenta_Facturacion":
    type: string
    example: "0"
  "Sistema_Origen":
    type: object
    properties:
      "Id_Sistema_Origen":
        type: string
        example: "CS-165153"
      "Sistema_Origen_Nombre":
        type: string
        example: "PORTALFIJA"
  "Id_Direccion_Instalacion":
    type: number
    example: 1
  "Servicios_Auxiliares":
    type: array
    example: []
  "Clausula_Permanencia":
    type: string
    example: "T"
  "Numero_Conexion_Anterior":
    type: number
    example: 0
  "Id_SalesForce":
    type: number
    example: 0
  "Integration_Id":
    type: string
    example: "CS-165153"
  "Caracteristica_Servicio":
    type: array
    example: []
  "Is_Pago_Recurrente":
    type: boolean
    example: false
  "Actualizacion_Extractor":
    type: string
    example: "18/11/2019"
  "Riesgo_Churn":
    type: object
    properties:
      "Accion_Sugerida":
        type: string
        example: ""
      "Nivel_Riesgo":
        type: string
        example: "3- ALTO"
      "Variable_Impacto":
        type: string
        example: "(FIN DE CLAUSULA)"
  "Fecha_Activacion":
    type: string
    example: "2019-11-17T08:55:56.728Z"

example : !include ../../examples/responses/getServicesByIdServiceAccount.json