#%RAML 1.0 DataType
type: object
properties:
  Resultado:
    type: object
    properties:
      code:
        type: string
        minLength: 1
        required: true
        example: "SUCCESS"
      description:
        type: string
        minLength: 1
        required: true
        example: "SUCCESS"
  Document:
    type: object
    properties:
      id:
        type: string
        minLength: 1
        required: true
        example: "61a7015e7e763b49e6d5a96b"
  registrosAfectados:
    type: number
    required: true
    example: 1
  fecha:
    type: string
    required: true
    example: "2022-05-12T19:29:41.96Z"
  descripcion:
    type: string
    required: true
    example: ""