#%RAML 1.0 DataType
type: object
properties:
  resultados:
    type: array
    items:
      properties:
        nombre: string
        estado: string
        usuario_creacion: string
        usuario_modificacion: string
        fecha_creacion: string
        fecha_modificacion: string
        descripcion: string
        valor:
          type: array
          items:
            properties:
              codigo: string
              nombre_valor: string
              estado_valor: string
              usuario_creacion_valor: string
              usuario_modificacion_valor: string
              fecha_creacion_valor: string
              fecha_modificacion_valor: string
  resultado:
    type: string
  fecha:
    type: string
  descripcion:
    type: string