#%RAML 1.0 DataType
properties:
  status:
    description: "Éxito o falla"
    type: string
    example: "success"
  messageId:
    type: string
    example: "123e4567-e89b-12d3-a456-426614174000"
  details:
    type: string
    example: "Mensaje recibido correctamente."