#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    _id:
      type: string
      example: "5bae57f128ec1681d0f43025"
    Fecha_Creacion:
      type: string
      example: "2018-08-23T22:32:54.390+0000"
    Usuario_Creacion:
      type: string
      example: "admin"
    Fecha_Modificacion:
      type: string
      example: "2018-08-23T22:32:54.390+0000"
    Usuario_Modificacion:
      type: string
      example: "admin"
    Actualizacion_Extractor:
      type: string
      example: "1"
    Automatico:
      type: boolean
      example: false
    Estados_Entrada:
      type: object
      properties:
        Comercial:
          type: string
          example: "O45"
        Servicio: 
          type: string
          example: "65"
        Activacion:
          type: string | nil
          example: null
    Estados_Salida:
      type: object
      properties:
        Comercial:
          type: string
          example: "O40"
        Servicio: 
          type: string
          example: "60"
        Activacion:
          type: string | nil
          example: null
    Estados_Error:
      type: object
      properties:
        Comercial:
          type: string | nil
          example: null
        Servicio: 
          type: string | nil
          example: null
        Activacion:
          type: string | nil
          example: null
    Estados_Salto:
      type: object
      properties:
        Comercial:
          type: string | nil
          example: null
        Servicio: 
          type: string | nil
          example: null
        Activacion:
          type: string | nil
          example: null
    Estados_Atras:
      type: object
      properties:
        Comercial:
          type: string | nil
          example: "O35"
        Servicio: 
          type: string | nil
          example: "50"
        Activacion:
          type: string | nil
          example: null
    Nivel:
      type: integer
      example: 1
    Id_Accion:
      type: number
      example: 0.0
        
  