#%RAML 1.0 DataType
displayName: Service(MDM_CD_SERVICIO) Updated Response 201
type: object
properties:
  response:
    type: object
    properties: 
      result:
        type: object
        properties:
          code:
            type: string
            required: false
            example: "SUCCESS"
          description:
            type: string
            required: false
            example: "Service updated."
      serviceAccount:
          type: string
          required: false
          example: "GPONMAY_0001"