#%RAML 1.0 DataType
type: object
properties:
  origin:
    type: string
    description: Canal origen (IP)
    example: "192.168.1.1"
    required: false
  customer:
    type: object
    required: true
    properties:
      documentNumber:
        type: string
        description: Numero Documento. Solo permite digitos.
        example: "123456789"
        pattern: "^[0-9]+$"
        required: true
      documentType:
        type: string
        description: Tipo Documento
        enum:
          - CC
          - CE
          - NIT
        example: "CC"
        required: true
      firstLastName:
        type: string
        description: Primer Apellido
        example: "PEREZ"
        required: true
      businessName:
        type: string
        description: Razon Social
        example: ""
        required: false
      dateExpedition:
        type: string
        description: Fecha Expedicion Documento (dd/mm/yyyy)
        example: "20/05/2010"
        required: true
      characteristics:
        type: array
        description: Caracteristicas Usuario / Contexto
        required: false
        items:
          type: object
          properties:
            name:
              type: string
              example: "NOMBRE"
            value:
              type: string
              example: "JUAN"
  adviser:
    type: string
    description: Modelo ante LISIM
    example: "1"
    required: false
  portal:
    type: string
    description: Identificador APP LISIM
    example: "PORTAL MOVILIDAD"
    required: false
  model:
    type: object
    required: false
    properties:
      technology:
        type: string
        description: Tecnologia
        enum:
          - LTE
          - FIJA
        example: "LTE"
        required: false
      segment:
        type: string
        description: Segmento
        enum:
          - Hogares
          - MiPymes
        example: "Hogares"
        required: false
