#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  targetUserCode:
    type: string
    example: "9090"
    description: Operator's user code requesting open ZSmart GUI.
    required: true
  targetUrl:
    type: string
    example: "modules/rolemgr/views/RoleMgr"
    description: ZSmart screen relative route 
    required: true