#%RAML 1.0 DataType
type: object
properties:
  username:
    type: string
    example: "banco_bogota_etb"
    required: true
  password:
    type: string
    example: "**********"
    required: true
  origin:
    type: string
    example: "BANCO"
    required: true
  transactionId:
    type: string
    minLength: 1
    maxLength: 60
    example: "TXN-BANCO-20260703001234"
  accountNumber:
    type: string
    minLength: 1
    maxLength: 30
    example: "ETB-0012345"
    required: true
  payAmount:
    type: string
    minLength: 1
    maxLength: 18
    example: "150000"
    required: true
  currencyCode:
    type: string
    minLength: 1
    maxLength: 30
    example: "COP"
    required: false
  channelCode:
    type: string
    minLength: 1
    maxLength: 60
    example: "BB"
    required: true
  paymentMethodCode:
    type: string
    minLength: 2
    maxLength: 2
    example: "TD"
    required: true
  bankAccountNumber:
    type: string
    minLength: 1
    maxLength: 60
    example: "988754521326545"
    required: true
  bankCode:
    type: string
    minLength: 1
    maxLength: 18
    example: "875421"
    required: true
  paymentDate:
    type: string
    minLength: 1
    maxLength: 20
    example: "2026-07-15 15:00:00"
    required: true
  partyType:
    type: string
    minLength: 1
    maxLength: 1
    example: "F"
    required: false
  partyCode:
    type: string
    minLength: 1
    maxLength: 30
    example: "FWEIR"
    required: false
  paymentParamList:
    type: array
    required: false
    items:
      type: object
      properties:
        invoiceNumber:
          type: string
          minLength: 1
          maxLength: 30
          example: "44554656"
          required: false
        settleAmount:
          type: string
          minLength: 1
          maxLength: 18
          example: "98653"
          required: false