#%RAML 1.0 DataType 
type: object
properties:
  origin:
    type: object
    properties:
      channel:
        type: string
        example: WEB
        required: false
      ipAddress:
        type: string
        example: 192.168.1.100
        required: false
      userAgent:
        type: string
        example: Mozilla/5.0
        required: false
      deviceSessionId:
        type: string
        example: vghs6tvkcle931686k1900o6e1
        required: false
      cookie:
        type: string
        example: pt1t38347bs6jc9ruv2ecpv7o2
        required: false
  gateway:
    type: object
    properties:
      gatewayName:
        type: string
        example: WOMPI
        required: false
      paymentFlow:
        type: string
        example: API
        required: false
      requiresGateway:
        type: boolean
        example: false
        required: false
  transactionId:
    type: string
    example: TX-30001
    required: false
  invoiceNumber:
    type: number
    example: 100100
    required: false
  CUS:
    type: string
    example: link_prod_8f3b9c2a1d
    required: false
  status:
    type: string
    example: PENDING
    required: false
  references:
    type: array
    items:
      type: object
      properties:
        reference:
          type: string
          example: ORDER-2024-002
          required: false
        description:
          type: string
          example: Internet service payment
          required: false
        currency:
          type: string
          example: COP
          required: false
        totalAmount:
          type: integer
          example: 120000
          required: false
        taxes:
          type: array
          required: false
          items:
            type: object
            properties:
              type:
                type: string
                example: IVA
                required: false
              value:
                type: integer
                example: 19
                required: false
  paymentMethod:
    type: object
    properties:
      type:
        type: string
        example: CARD
        required: false
      card:
        type: object
        required: false
        properties:
          cardBrand:
            type: string
            example: VISA
            required: false
          installments:
            type: integer
            example: 1
            required: false
          token:
            type: string
            example: tok_prod_ABC123456
            required: false
          cardData:
            type: object
            properties:
              cardNumber:
                type: string
                example: '4111111111111111'
                required: false
              expMonth:
                type: string
                example: '12'
                required: false
              expYear:
                type: string
                example: '29'
                required: false
              cvc:
                type: string
                example: '123'
                required: false
              cardHolder:
                type: string
                example: Juan Perez
                required: false
          threeDomainSecure:
            type: object
            required: false
            properties:
              eci:
                type: string
                example: '05'
                required: false
              cavv:
                type: string
                example: AAABBIIFmAAAAAAAAAAAAAAAAAA=
                required: false
              xid:
                type: string
                example: MDAwMDAwMDAwMDAwMDAwMzIyNzY=
                required: false
              directoryServerTransactionId:
                type: string
                example: 3d5c2c78-1234-5678
                required: false
      pse:
        type: object
        required: false
        properties:
          financialInstitutionCode:
            type: string
            example: '1007'
            required: false
      link:
        type: object
        required: false
        properties:
          singleUse:
            type: boolean
            example: false
            required: false
          collectShipping:
            type: boolean
            example: false
            required: false
          collectCustomerLegalId:
            type: boolean
            example: false
            required: false
          expirationDate:
            type: datetime-only
            example: '2040-12-10T14:30:00'
            required: false
          sku:
            type: string
            example: RENT-APT-505
            required: false
          expiresAt:
            type: datetime-only
            example: '2022-12-10T14:30:00'
            required: false
          notifyUrl:
            type: string
            example: http://www.payu.com/notify
            required: false
          redirectUrl:
            type: string
            example: https://midominio.com/result
            required: false
          imageUrl:
            type: string
            example: https://midominio.com/result
            required: false
          customFields:
            type: array
            required: false
            items:
              type: object
              properties:
                label:
                  type: string
                  example: Full Name
                  required: false
                required:
                  type: boolean
                  example: true
                  required: false
  customer:
    type: object
    properties:
      fullName:
        type: string
        example: Juan Perez
        required: true
      email:
        type: string
        example: juan@email.com
        required: true
      phoneNumber:
        type: string
        example: '3000000000'
        required: true
      documentType:
        type: string
        example: CC
        required: true
      documentNumber:
        type: string
        example: '111111111'
        required: true
      billingAddress:
        type: object
        properties:
          addressLine1:
            type: string
            example: Cr 23 No. 53-50
            required: false
          addressLine2:
            type: string
            example: Apto 505
            required: false
          city:
            type: string
            example: Bogotá
            required: false
          state:
            type: string
            example: Bogotá D.C.
            required: false
          country:
            type: string
            example: CO
            required: false
          postalCode:
            type: string
            example: '110111'
            required: false
