#%RAML 1.0 DataType 
type: object
properties:
  id:
    type: string
    example: 68ded01c7d0397ef7b0664cc
    required: false
  createdAt:
    type: datetime
    example: '2025-10-02T14:18:52.473Z'
    required: false
  updatedAt:
    type: datetime
    example: '2025-10-02T14:30:25.385Z'
    required: false
  updatedBy:
    type: string
    example: PortalLTE
    required: false
  createdBy:
    type: string
    example: PortalLTE
    required: false
  extractorUpdate:
    type: string
    example: '1'
    required: false
  orderNumber:
    type: string
    example: MDM-FIBRA-000636091
    required: false
  channel:
    type: string
    example: Ecommerce
    required: true
  description:
    type: string
    example: Error Orquestación
    required: false
  priority:
    type: string
    example: Error Orquestación
    required: false
  phase:
    type: string
    example: ORDERF
    required: false
  through:
    type: object
    properties:
      throughType:
        type: string
        example: VTA
        required: true
      throughSubtype:
        type: string
        example: ''
        required: false
      throughDate:
        type: datetime
        example: '2025-10-02T14:18:52.473Z'
        required: false
      reconnectionDate:
        type: string
        example: ''
        required: false
      suspensionDate:
        type: string
        example: ''
        required: false
      executionDate:
        type: datetime
        example: '2025-10-02T14:18:52.473Z'
        required: false
      keepConnectionNumber:
        type: boolean
        example: false
        required: false
      permanenceClause:
        type: boolean
        example: true
        required: false
      permanenceClauseValue:
        type: integer
        example: 0
        required: false
      cancellationReason:
        type: string
        example: ''
        required: false
      cancellationSubreason:
        type: string
        example: ''
        required: false
      cancellationDescription:
        type: string
        example: ''
        required: false
      orderMotives:
        type: string
        example: ''
        required: false
  category:
    type: string
    example: LTE
    required: true
  cun:
    type: string
    example: '4347250001278699'
    required: false
  requestCustomer:
    type: object
    properties:
      documentType:
        type: string
        example: CC
        required: true
      documentNumber:
        type: string
        example: '28564778'
        required: true
  requestService:
    type: object
    properties:
      bundle:
        type: object
        properties:
          id:
            type: string
            example: 68769f4c7b67fb1a1015a60a
            required: false
          productGroupingNumber:
            type: integer
            example: 6847
            required: false
          serviceType:
            type: string
            example: FTTH
            required: true
  requestProduct:
    type: object
    properties:
      code:
        type: string
        example: bundle
        required: true
  featureOrder:
    type: array
    required: false
    items:
      type: object
      properties:
        feature:
          type: string
          example: PQR_CAUSAL
          required: false
        value:
          type: string
          example: FALLA INTERNET
          required: false
  featureService:
    type: array
    required: false
    items:
      type: object
      properties:
        feature:
          type: string
          example: PQR_CAUSAL
          required: false
        value:
          type: string
          example: FALLA INTERNET
          required: false
  requestBillingAccount:
    type: object
    required: false
    properties:
      createdAt:
        type: datetime
        example: '2025-10-03T15:59:17.578Z'
        required: false
      updatedAt:
        type: datetime
        example: '2025-10-03T15:59:17.578Z'
        required: false
      updatedBy:
        type: string
        example: ''
        required: false
      createdBy:
        type: string
        example: ''
        required: false
      extractorUpdate:
        type: string
        example: ''
        required: false
      billingAccountId:
        type: string
        example: '15052963336'
        required: false
      basicCustomer:
        type: object
        properties:
          id:
            type: string
            example: '000000000000000000000000'
            required: false
          createdAt:
            type: datetime
            example: '2025-10-03T15:59:17.578Z'
            required: false
          updatedAt:
            type: datetime
            example: '2025-10-03T15:59:17.578Z'
            required: false
          updatedBy:
            type: string
            example: ''
            required: false
          createdBy:
            type: string
            example: ''
            required: false
          extractorUpdate:
            type: string
            example: ''
            required: false
          customerAccountId:
            type: integer
            example: 0
            required: false
          documentType:
            type: string
            example: CC
            required: false
          documentNumber:
            type: string
            example: '210202502'
            required: false
      status:
        type: object
        properties:
          code:
            type: string
            example: A
            required: false
          description:
            type: string
            example: ''
            required: false
          date:
            type: string
            example: ''
            required: false
          exceptionCode:
            type: integer
            example: 0
            required: false
          exception:
            type: string
            example: ''
            required: false
      billingType:
        type: string
        example: Detailed
        required: false
      invoiceType:
        type: string
        example: Detailed
        required: false
      deliveryType:
        type: string
        example: Physical
        required: false
      invoiceValue:
        type: integer
        example: 0
        required: false
      formattedInvoiceValue:
        type: string
        example: ''
        required: false
      billingEmail:
        type: string
        example: dkdi317b6z@mkzaso.com
        required: false
      billingCycle:
        type: string
        example: '34'
        required: false
      cutoffDay:
        type: integer
        example: 0
        required: false
      isOverdue:
        type: boolean
        example: false
        required: false
      billingAddressId:
        type: integer
        example: 2
        required: false
      suspensionDate:
        type: string
        example: ''
        required: false
      chargingCycle:
        type: integer
        example: 0
        required: false
      chargingCycleCode:
        type: integer
        example: 0
        required: false
      serviceAccounts:
        type: string
        example: ''
        required: false
      billingCutoffDate:
        type: string
        example: '8'
        required: false
  scheduling:
    type: object
    required: false
    properties:
      appointmentDate:
        type: datetime
        example: '2025-10-03T00:00:00.000Z'
        required: false
      appointmentSlot:
        type: string
        example: AM_2
        required: false
      workType:
        type: string
        example: F.O. (HSI/VOIP)
        required: false
      duration:
        type: string
        example: '130'
        required: false
      hasAppointment:
        type: boolean
        example: true
        required: false
      activityId:
        type: string
        example: '8848731'
        required: false
  attachments:
    type: object
    required: false
    properties:
      service:
        type: array
        items:
          type: object
          properties:
            fileName:
              type: string
              example: ANEXO_DIGITAL_DEFINITIVO_SVA
              required: false
            path:
              type: string
              example: 28564778/MDM-FIBRA-000636091/ANEXO_DIGITAL_DEFINITIVO_SVA
              required: false
            size:
              type: string
              example: '236023'
              required: false
