#%RAML 1.0
title: product-xapi-services
version: v2
protocols:
  - HTTPS
mediaType:
  - application/json
baseUri: https://product-xapi-services-{env}.us-e2.cloudhub.io/
description: Capa de experiencia (XAPI) para productos v2 – recarga de saldo, recarga de paquete y promociones.

traits:
  tibcoHeaders: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml

securitySchemes:
  etb_oauth_2_0: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

/v2:
  /getpromotions:
    post:
      is:
        - tibcoHeaders
      securedBy: [etb_oauth_2_0]
      displayName: Get promotions
      description: |
        Consulta promociones disponibles (móvil o fija).
        El campo type (movil|fijo|mobile|fixed) se reenvía a product-papi-services-v2 /getpromotions.
      body:
        application/json:
          type: !include datatypes/request/post-promotions.raml
          example: !include examples/request/post-promotions-mobile.json
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/post-promotions.raml
              example: !include examples/response/post-promotions-mobile.json
        401:
          description: Unauthorized - access token missing or invalid.
          body:
            application/json:
              type: !include datatypes/response/error.raml
        404:
          body:
            application/json:
              type: !include datatypes/response/notFoundError.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/internalServerError.raml
  /usageConsumptionReport:
    post:
      is:
        - tibcoHeaders
      securedBy: [etb_oauth_2_0]
      displayName: Recarga de saldo (Usage Consumption Report)
      description: Recarga de saldo en línea.
      body:
        application/json:
          type: !include datatypes/request/usageConsumptionReport.raml
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/usageConsumptionReport.raml
        401:
          description: Unauthorized - access token missing or invalid.
          body:
            application/json:
              type: !include datatypes/response/error.raml
        404:
          body:
            application/json:
              type: !include datatypes/response/notFoundError.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/internalServerError.raml
  /usageConsumption:
    post:
      is:
        - tibcoHeaders
      securedBy: [etb_oauth_2_0]
      displayName: Recarga de paquete (Usage Consumption)
      description: Recarga de paquete(s) en línea.
      body:
        application/json:
          type: !include datatypes/request/usageConsumption.raml
      responses:
        200:
          body:
            application/json:
              type: !include datatypes/response/usageConsumption.raml
        401:
          description: Unauthorized - access token missing or invalid.
          body:
            application/json:
              type: !include datatypes/response/error.raml
        404:
          body:
            application/json:
              type: !include datatypes/response/notFoundError.raml
        500:
          body:
            application/json:
              type: !include datatypes/response/internalServerError.raml
  /subscription:
    /{msisdn}:
      uriParameters:
        msisdn:
          type: string
          description: Mobile number (MSISDN) to query.
          example: "573001234567"
      get:
        is:
          - tibcoHeaders
        securedBy: [etb_oauth_2_0]
        displayName: Query subscription by MSISDN
        description: Experience API for subscription query; delegates to Product PAPI v2.
        queryParameters:
          ORIGIN:
            type: string
            required: false
            description: Calling channel or origin.
            example: "CATALOGO"
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/get-subscription-by-msisdn.raml
                example: !include examples/response/get-subscription-by-msisdn-200.json
          401:
            description: Unauthorized - access token missing or invalid.
            body:
              application/json:
                type: !include datatypes/response/error.raml
          404:
            body:
              application/json:
                type: !include datatypes/response/notFoundError.raml
          500:
            body:
              application/json:
                type: !include datatypes/response/internalServerError.raml
