https:
  port: "443"
  path: "/ivr/*"
  
autodiscovery: "1234"

configurationTimeout:
  service-papi: "90000"
  audits-mongo: "62000"
  mongo-sapi: "62000"
  sap-sapi: "62000"
  
service-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-service-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/services/v1"
  contactosFrecuentes:
    path: "/clientes/contactos-frecuentes"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs/"
  path: "/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
mongo-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  basepath: "/mongo"
  path:
    systems: "/v1/ms/systems/{name}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

sap-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sap-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/sap"
  path: 
    reconnectionRMCA: "/rmca/v1/process/reconnection"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"   
  
bpo:
  urls:
    COS:
      api:
        host: "etbcustomerinformation.mysoul.software"  
        path: "/customer-etb"