https:
  host: "0.0.0.0"
  port: "443"

autodiscovery: "17974307"

portal-fija-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-portal-fija-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: 
    version: "/fija/v1"
  pathAccounts: "/accounts/{account_id}/cycles"
  pathHierarchyAccounts: "/hierarchy_account"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
support:
  protocol: "HTTP"
  host: "mule-worker-internal-support-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/support"
  cun:
    path: "/v1/cun"
  imei:
    path: "/v1/imei"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
remedy-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-remedy-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/remedy/v1"
  createIncident:
    path: "/incident"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

mongo-sapi:
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  orderByOrderNumber:
    path: "/orders/{orderNumber}"
  postes:
    path: "/orders/{orderNumber}/postes/{idPoste}"
    properties:
      collection: "MDM_CD_ORDEN_COMPLETADA"
  basepath: "/mongo/v1"
  protocol: "HTTP"
  getOrder:
    path: "/orders"
  loginPosteria:
    path: "/login"
  getParametersByType:
    path: "/parameters/{typeParameter}"
    types:
      canales: "COMUNICACIONES_COBRANZA_CANALES"
      horarios: "COMUNICACIONES_COBRANZA_HORARIOS"
      obligatoriedad: "COMUNICACIONES_COBRANZA_OBLIGATORIEDAD"
  getClient:
    path: "/clients"
    channelValidation:
      path: "/clients/channels"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
audits-mongo-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/audits/v1" 
  path: "/logs/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

operations-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io" 
  port: "8091"
  basePath: "/operations/v1"
  path:
    availabilityOrder: "/availability/{orderNumber}"
    interactionCoverage: "/interaction/coverage"
    interactionCancelService: "/interaction/cancelService"
    interactionChangeSpeed: "/interaction/changeSpeed"
    interactionChangeONT: "/interaction/changeONT"
    inventory: "/inventory/{idServiceAccount}"
    incident: "/incident"
    getIncident: "/incident/{ticketNumber}"
    cancelOrder: "/cancelOrder"
    confirmProvisioning: "/provisioning/confirm"
    provisioning: "/provisionings"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

billing-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-billing-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/billing/v1"
  path:
    serviceAccounts: "/servicios/{id}/estadocuenta/certificado"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

oracle-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io" 
  port: "8091"
  basePath: "/oracle/v1"
  cancelOrder:
    path: "/cancelOrder"
  createOrder:
    path: "/order"
  nonStandardAddress:
    path: "/nonStandardAddress"
  revInvList:
    path: "/resInvList/{externalId}"
  invokeEtaDirectInbound:
    path: "/invokeETADirectInbound"
  sendMessage:
    path: "/sendMessage"
    addId: "/lists/CONTACTS_LIST/members"
    triggerEmail: "/events/CodigoLISIMEMAIL"
    triggerSms: "/events/CodigoLISIMSMS"
    fieldsEmail: "NOMBRE|MDM|EMAIL_ADDRESS_"
    fieldsSms: "NOMBRE|MDM|MOBILE_NUMBER_"
  getCapacity:
    path: "/getCapacity"

etb-mdm:
  protocol: "HTTP"
  host: "mule-worker-internal-etb-mdm-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mdm/v1"
  path:
    registerTramits: "/tramits"
    setPQR: "/orders/orderStatus"
    NotifyBillToMDM: "/billing/notification"
    process: "/process"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

credentials:
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"
  
format-date: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

posteria:
  Tipo_Intervencion: "DE"
  
customerContact:
  timeFrame: "L-V 7-7 & S 8-3"
  OS:
    ttl: "18000" #Seconds
    maxEntries: "10000"
    expiration: "18000" #Seconds
    
interaction-transactType:
  coverage: "VTAM"
  cancelService: "TESRM"
  changeSpeed: "PRCHM"
  changeONT: "ASEGM"
  
otpParams:
  osEntryttl: "300"
  osExpInterval: "10"
  nonExistent: "-1"
  
common-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/common/v1"
  path:
    logEntry: "/traceabilityLogs"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

sap-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sap-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath:
    version: "/sap/v1"
  path:
    rfc-solfact-getdata: "/rfc/solfact_getdata"
    rfc-solfact-checkdata: "/rfc/solfact_checkdata"
    rfc-block-invoice: "/rfc/block_invoice"
    rfc-change-invoice: "/rfc/change_invoice"
    rfc-payment-notif: "/rfc/payment_notif"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
configurationTimeout:
  billing-papi: "62000"
  common-sapi: "3000000"
  mdm-sapi: "62000"
  portal-fija-sapi: "62000"
  security: "62000"
  support: "62000"
  mongo-sapi: "62000"
  experience-integration: "62000"
  ivr-sapi: "62000"
  portal-movilidad-sapi: "62000"
  operations-papi: "184000"
  oracle-sapi: "62000"
  api-biometria: "62000"
  etb-mdm: "62000"
  remedy-sapi: "62000"
  audits-mongo-sapi: "62000"
  service-papi: "62000"
  sap-sapi: "62000"
  sisext-sapi: "62000"

service-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-service-papi-services-prod.us-e2.cloudhub.io" 
  port: "8091"
  basePath: "/services/v1"
  path:
    activeLines: "/referred/activeLines"
    referred: "/referred"
    quotas: "/referred/quotas"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

ivr-sapi:
  port: "8091"
  host: "mule-worker-internal-ivr-sapi-services-prod.us-e2.cloudhub.io"
  protocol: "HTTP"
  basepath: "/ivr/v1"
  positiveRecord:
    path: "/positiveRecord"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
sisext-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/sisext"
  getInvoice:
    path: "/v1/getInvoice"
  client_id: "b8665f3c588a4a709576760a1cc5a582"
  client_secret: "7417c6490e8943FDBCDB907d30e9f2f7"
  
sftp:
  host: "10.112.1.152"
  port: "22"
  user: "tibcowipro"
  pass: "Marzo2025*"
  directory: "/data"
  path:
    getInvoiceWS: "/tibco/receiptsCorp/"
    getInvoiceDefault: "/shared_tibco/"
    
mockInvoiceFormat: "false"