#%RAML 1.0 DataType 
type: object
properties:
  name:
    type: string
    example: Monthly rent - Wompi Tower Apartments
    required: true
  description:
    type: string
    example: Pay here your apartment monthly rent
    required: true
  single_use:
    type: boolean
    example: false
    required: true
  collect_shipping:
    type: boolean
    example: false
    required: true
  currency:
    type: string
    example: COP
    required: false
  amount_in_cents:    
    type: integer | nil
    example: 3000000
    required: false
  expires_at:
    type: string
    example: '2022-12-10 14:30:00'
    required: false
  redirect_url:
    type: string | nil
    description: URL donde será redirigido el cliente una vez termine el proceso de pago
    example: https://micomercio.co/tienda
    required: false
  image_url:
    type: string | nil
    description: Dirección de la imagen que quieras presentar en el link de pago
    example: https://micomercio.co/tienda/logo
    required: false
  sku:
    type: string | nil
    description: Identificador interno del producto en tu comercio. Máximo 36 caracteres
    example: CDX-812345-1ADD
    required: false
  customer_data:
    type: object
    properties:
      customer_references:
        type: array
        items:
          type: object
          properties:
            label:
              type: string
              example: 'Apartment #'
              required: false
            is_required:
              type: boolean
              example: true
              required: false
