#%RAML 1.0 DataType
properties:
  acceptance_token:
    type: string
    description: Token JWT de aceptación (ver https://docs.wompi.co/docs/en/tokens-de-aceptacion)
    example: eyJhbGciOiJIUzI1NiJ9.eyJjb250cmFjdF9pZCI6MSwicGVybWFsaW5rIjoiaHR0cHM6Ly93b21waS5jby93cC1jb250ZW50L3VwbG9hZHMvMjAxOS8wOS9URVJNSU5PUy1ZLUNPTkRJQ0lPTkVTLURFLVVTTy1VU1VBUklPUy1XT01QSS5wZGYiLCJmaWxlX2hhc2giOiIzZGNkMGM5OGU3NGFhYjk3OTdjZmY3ODExNzMxZjc3YiIsImppdCI6IjE1ODU4NDE2MTUtNDU2MTgiLCJleHAiOjE1ODU4NDUyMTV9.bwBa-RjN3euycqeXVroLWwUN1ZRY1X11I4zn1y5nMiY
    required: true
  accept_personal_auth:
    type: string
    description: Token JWT de aceptación (ver https://docs.wompi.co/docs/en/tokens-de-aceptacion)
    example: eyJhbGciOiJIUzI1NiJ9.eyJjb250cmFjdF9pZCI6MSwicGVybWFsaW5rIjoiaHR0cHM6Ly93b21waS5jby93cC1jb250ZW50L3VwbG9hZHMvMjAxOS8wOS9URVJNSU5PUy1ZLUNPTkRJQ0lPTkVTLURFLVVTTy1VU1VBUklPUy1XT01QSS5wZGYiLCJmaWxlX2hhc2giOiIzZGNkMGM5OGU3NGFhYjk3OTdjZmY3ODExNzMxZjc3YiIsImppdCI6IjE1ODU4NDE2MTUtNDU2MTgiLCJleHAiOjE1ODU4NDUyMTV9.bwBa-RjN3euycqeXVroLWwUN1ZRY1X11I4zn1y5nMiY
    required: true
  amount_in_cents:    
    type: integer
    description: Monto total en centavos de la transacción. Por ejemplo, para $1.000 se escribe 100000
    example: 3000000
    required: false
  currency:
    type: string
    description: Moneda en la que se va a realizar la transacción. Únicamente COP actualmente.
    example: COP
    enum:
    - COP
    required: false
  signature:
    type: string
    description: Hash criptográfico asimétrico para validar la integridad de la información de la transacción.
    example: sk8-438k4-xmxm392-sn2m2490000COPprod_integrity_Z5mMke9x0k8gpErbDqwrJXMqsI6SFli6
    required: false
  customer_email:
    type: string
    description: Email al cual se envía el comprobante de pago.    
    example: example@wompi.co
    required: false
  payment_method:
    type: object
    required: false
    properties:
      type:
        type: string
        example: CARD
        required: false
      token:
        type: string
        example: tok_prod_280_32326B334c47Ec49a516bf1785247ba2
        required: false
      installments:
        type: integer
        example: 2
        required: false
  payment_source_id:
    type: integer
    description: ID de fuente de pago. OBLIGATORIA si no se usa un payment_method
    example: 1234
    required: false
  redirect_url:
    type: string
    description: URL a la que se lleva al usuario después de hacer el pago.
    example: https://mitienda.com.co/pago/resultado
    required: false
  reference:
    type: string
    description: Referencia única en la base de datos de cada comercio.
    example: TUPtdnVugyU40XlkhixhhGE6uYV2gh89
    required: false
  expiration_time:
    type: string
    description: Fecha y hora en formato ISO8601 (UTC+0000), activa un contador regresivo indicando el tiempo restante para la expiración del inicio del pago.
    example: 2023-06-09T20:28:50.000Z
    required: false
  customer_data:
    type: object
    required: false
    properties:
      phone_number:
        type: string
        description: Teléfono del pagador, incluyendo código del país
        example: "+573307654321"
        required: false
      full_name:
        type: string
        description: Nombre completo del pagador (nombres y apellidos)
        example: Juan Alfonso Pérez Rodríguez
        required: false
      legal_id:
        type: string
        description: Número de documento del pagador
        example: "1234567890"
        required: false
      legal_id_type:
        type: string
        required: false
        description: Tipo de documento del pagador
        example: CC
        enum:
          - CC
          - NIT
          - PP
          - CE
          - TI
          - DNI
          - RG
          - OTHER
  shipping_address:
    type: object
    required: false
    properties:
      address_line_1:
        type: string
        example: 'Calle 34 # 56 - 78'
        required: false
      address_line_2:
        type: string
        example: Apartamento 502, Torre I
        required: false
      country:
        type: string
        example: CO
        required: false
      region:
        type: string
        example: Cundinamarca
        required: false
      city:
        type: string
        example: Bogotá
        required: false
      name:
        type: string
        example: Pepe Perez
        required: false
      phone_number:
        type: string
        example: '573109999999'
        required: false
      postal_code:
        type: string
        example: '111111'
        required: false
