#%RAML 1.0 DataType 
type: object
properties:
  firstName:
    type: string
    example: Manuel
    required: false
  secondName:
    type: string
    example: Enrique
    required: false
  lastName:
    type: string
    example: Rodriguez
    required: false
  secondLastName:
    type: string
    example: Riveros
    required: false
  documentIssueDate:
    type: datetime
    example: '2022-05-12T19:21:55.190Z'
    required: false
  documentType:
    type: string
    example: CC
    required: false
  documentNumber:
    type: string
    example: '1052418947'
    required: false
  approval:
    type: boolean
    example: true
    required: false
  segment:
    type: string
    example: hogares
    required: false
  mobilePhone:
    type: string
    example: '3125474521'
    required: false
  mail:
    type: string
    example: kikeriasd@asdaksdj.com
    required: false
  Phone:
    type: string
    example: '542545245'
    required: false
  preOrder:
    type: string
    example: ORD-5454
    required: false