#%RAML 1.0 NamedExample
value:
  -
    altKeyName: "ETB_Distrito"
    altKeyValue: "28130"
  -
    altKeyName: "SegmentoUEN"
    altKeyValue: "S1"
  -
    altKeyName: "UEN"
    altKeyValue: "Hogares"
  -
    altKeyName: "CodBarrio"
    altKeyValue: ""
  -
    altKeyName: "Estrato"
    altKeyValue: "2"
  -
    altKeyName: "Central"
    altKeyValue: "Z_SUR"
  -
    altKeyName: "User"
    altKeyValue: ""
  -
    altKeyName: "RVC TECNOLOGIA"
    altKeyValue: "CU"
  -
    altKeyName: "Price"
    altKeyValue: ""
  -
    altKeyName: "IMEI"
    altKeyValue: ""
  -
    altKeyName: "ProductId"
    altKeyValue: "1-1DUD40W"
  -
    altKeyName: "MDMAddress"
    altKeyValue: "CL 41B SUR 1F 20"
  -
    altKeyName: "MDMLatitude"
    altKeyValue: "4.552021"
  -
    altKeyName: "MDMLongitude"
    altKeyValue: "-74.100763"
  -
    altKeyName: "MDMCodigoGIS"
    altKeyValue: "612802304577533800"
  -
    altKeyName: "MDMZone"
    altKeyValue: "BOGO05"
  -
    altKeyName: "MDMCentral"
    altKeyValue: "Z_SUR"
  -
    altKeyName: "MDMMolecula"
    altKeyValue: ""
  -
    altKeyName: "MDMDistrito"
    altKeyValue: "28130"