http:
  host: "0.0.0.0"
  port: "8081"
  
autodiscovery: "17980974"

configurationTimeout:
  billing-papi: "62000"
  
billing-papi:
  accountCreationNotification:
    host: "mule-worker-internal-billing-papi-services-prod.us-e2.cloudhub.io"
    port: "8091"
    basePath: "/billing/v1"
    path: "/accounts/revchain"
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"