#%RAML 1.0 NamedExample
value:
  -
    xaId: "1-H9S9USG"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X5"
    actionCode: "NONE"
    name: "FECHA FINAL SUSPENSION (DD/MM/YYYY)"
    value: ""
  -
    xaId: "1-H9S9USH"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WR"
    actionCode: "NONE"
    name: "FECHA INICIO SUSPENSION (DD/MM/YYYY)"
    value: ""
  -
    xaId: "1-H9S9US9"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X1"
    actionCode: "NONE"
    name: "FINANCIAMIENTO"
    value: "FALSE"
  -
    xaId: "1-H9S9USF"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WS"
    actionCode: "NONE"
    name: "NOMBRE COMBO"
    value: "NA"
  -
    xaId: "1-H9S9USC"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WU"
    actionCode: "NONE"
    name: "NUMERO ANTIGUO"
    value: ""
  -
    xaId: "1-KCH7IIZ"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X6"
    actionCode: "UPDATE"
    name: "PERMANENCIA"
    value: "NA"
  -
    xaId: "1-H9SA7JZ"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X3"
    actionCode: "NONE"
    name: "RVC DESCUENTO DOS"
    value: "NA"
  -
    xaId: "1-H9SA7K0"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WT"
    actionCode: "NONE"
    name: "RVC DESCUENTO INICIAL"
    value: "NA"
  -
    xaId: "1-H9SA7K1"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X8"
    actionCode: "NONE"
    name: "RVC DESCUENTO TRES"
    value: "NA"
  -
    xaId: "1-H9SA7K2"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WZ"
    actionCode: "NONE"
    name: "RVC DURACION"
    value: ""
  -
    xaId: "1-H9S9US4"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WX"
    actionCode: "NONE"
    name: "RVC DURACION DOS"
    value: ""
  -
    xaId: "1-H9S9US5"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WQ"
    actionCode: "NONE"
    name: "RVC DURACION FECHA"
    value: ""
  -
    xaId: "1-H9S9US6"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X0"
    actionCode: "NONE"
    name: "RVC DURACION FECHA DOS"
    value: ""
  -
    xaId: "1-H9S9USI"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X2"
    actionCode: "NONE"
    name: "RVC ESTRATO"
    value: "NA"
  -
    xaId: "1-H9S9US7"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X9"
    actionCode: "NONE"
    name: "RVC PROMOCION DESCUENTO"
    value: ""
  -
    xaId: "1-H9SA7K3"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X7"
    actionCode: "NONE"
    name: "RVC USO"
    value: "'Hog'"
  -
    xaId: "1-P1YY351"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WW"
    actionCode: "NONE"
    name: "TECNOLOGIA ETB"
    value: "CU"
  -
    xaId: "1-H9S9US8"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7X4"
    actionCode: "NONE"
    name: "TIPO CUENTA"
    value: ""
  -
    xaId: "1-H9S9USA"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WY"
    actionCode: "NONE"
    name: "TIPO ORDEN"
    value: ""
  -
    xaId: "1-H9S9USN"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WP"
    actionCode: "UPDATE"
    name: "TIPO TRANSACCION"
    value: "MODIFICACION"
  -
    xaId: "1-H9S9USD"
    parentID: "1-QJPB7WO"
    id: "1-QJPB7WV"
    actionCode: "NONE"
    name: "VELOCIDAD DE BAJADA"
    value: ""