#%RAML 1.0 DataType
type: object
properties:
  identip:
    type: object
    required: false
    properties:
      channelOrigin: { type: string, required: false }
      clientIp: { type: string, required: false }
  subscriber:
    type: object
    required: true
    properties:
      documentType: { type: string, required: true }
      documentNumber: { type: string, required: true }
  agreement:
    type: object
    required: true
    properties:
      name: { type: string, required: true }
      expirationDate: { type: string, required: true }
      advisorCopyRequired: { type: string, required: false }
      advisorEmail: { type: string, required: false }
      emailMessage: { type: string, required: false }
      documents:
        type: array
        required: true
        items:
          type: object
          properties:
            fileName: { type: string, required: true }
            container: { type: string, required: true }
            mimeType: { type: string, required: false }
      recipients:
        type: array
        required: false
        items:
          type: object
          properties:
            email: { type: string, required: false }
            firstName: { type: string, required: false }
            lastName: { type: string, required: false }
            documentType: { type: string, required: false }
            documentNumber: { type: string, required: false }
            mobile: { type: string, required: false }
  procedure:
    type: object
    required: true
    properties:
      orderNumber: { type: string, required: true }
      type: { type: string, required: true }
      user: { type: string, required: true }
