#%RAML 1.0 DataType
properties:
  "action": 
    type: string
    example: "add"
  "connection_type_name": 
    type: string
    example: "Numero Telefono"
  "connection_number_type_name": 
    type: string
    example: "Numero Telefono (POTS)"
  "connection_number": 
    type: string
    example: "8899650"
  "start_date":
    type: !include start_date.raml