#%RAML 1.0 DataType
properties:
  cumplirFo:
    type: !include cumplirFoType.raml
  cumplirFoResponse:
    type: !include cumplirFoResponseType.raml
  cambioEstMig:
    type: !include cambioEstMigType.raml
  cambioEstMigResponse:
    type: !include cambioEstMigResponseType.raml