#%RAML 1.0 DataType
properties:
  EXT_MARKET_TYP?: string
  GEO_CODE1?: string
  GEO_CODE2?: string
  GEO_CODE3?: string
  ORDER_TYPE?: string
  CT_NUM?: string
  FD?: string
  CURR_CODE?: string
  INV_DAY?: string
  CONV_IND?: string
  BILL_PRNT_SUB_ID?: string
  PAYMENT_PRD?: string
  BILLABLE?: string
  DocType: string
  start_date:
    type: object
    properties:
      month?: string
      day?: string
      year?: string
  Customer?:
    type: object
    properties:
      last_name?: string
      subscriber_name?: string
      BillBillingName?: string
      ContactInfo?:
        type: object
        properties:
          PhoneNumber?: string
          ContactEmailAdd?: string
          DocumentNo?: string
  Billing_address[]?:
    type: object
    properties:
      LineOne?: string
      CityName?: string
      StateCode?: string
      DaneCode?: string
  invoice_delivery_name?: string
  OrderSubType?: string
  InvoiceMethod?: string