#%RAML 1.0 DataType
properties:
  Identification:
    type: !include IdentificationType.raml
  Name: string
  Address:
    type: !include AddressType.raml
  ContactPerson:
    type: !include ContactPersonType.raml
  TypeCode: string
  Custom:
    type: !include CustomType.raml