#%RAML 1.0 DataType
properties:
  "action":
    type: string
    example: "add"
  "feature_type_name": 
    type: string
    example: "Numeral Abreviado"
  "start_date":
    type: !include start_date.raml
  "feature_rate_plan": 
    type: object
    properties:
      "action": 
        type: string
        example: "add"
      "rate_plan_name": 
        type: string
        example: "Plan Numeral Abreviado LTE"
      "start_date":
        type: !include start_date.raml