#%RAML 1.0 DataType
properties:
  TypeName?: string
  Id?: string
  Index?: integer
  StartDate?: string
  Validity?: integer
  AcumulateValidity?: integer
  Parameter?:
    type: !include ParameterType.raml