#%RAML 1.0 DataType
properties:
  id:
    type: string
    description: id
    example: "a054y00000lCrKJAA0211202191631"
  operation:
    type: string
    description: operation
    example: "SetBillingAccount"
  requestSystem:
    type: string
    description: Request system
    example: "WS.BillingLTECorporate"
  version:
    type: string
    description: Version
    example: "1"
  type:
    type: string
    description: Type
    example: "IN"
  reqType:
    type: string
    description: Request type
    example: "SYNC"
  requestDateTime:
    type: datetime-only
    description: Request date time
    example: 2021-11-22T11:43:36
  responseDateTime:
    type: datetime-only
    description: Response date time
    example: 2021-11-22T11:43:36