#%RAML 1.0 DataType
properties:
  Identification:
    type: !include IdentificationType.raml
  OrderQuantity: string
  ServiceActionCode: string
  FulfilmentModeCode: string
  ParentSalesOrderLineIdentification:
    type: !include IdentificationType.raml
  RootParentSalesOrderLineIdentification:
    type: !include IdentificationType.raml
  StatusCode: string
  ServiceAddress: 
    type: !include AddressType.raml
  ItemReference:
    type: !include ItemReferenceType.raml
  SalesOrderSchedule: 
    type: !include SalesOrderScheduleType.raml
  OwnerPartyReference:
    type: !include IdentificationType.raml
  ScheduleOrderIndicator: string
  SupplementaryInfo?:
    type: !include SupplemantaryInfoType.raml
  ProductConfiguration?: string
  StartDateTime?: string
  Connection?:
    type: !include ConnectionType.raml
  Discounts?:
    type: !include DiscountsType.raml
  SpecificationGroupXA?:
    type: object
    properties:
  Custom:
    type: !include CustomSalesOrderLineType.raml
  Billing?:
    type: !include BillingType.raml
  AltKey?:
    type: array
    items: !include AltKeyType.raml