#%RAML 1.0 DataType
properties:
  SchedulingQuota?: string
  TechnicalVisitDate?: string
  AvailabilityFlag?: string
  ScheduledVisitFlag?: string
  ContractDeliveryMethod?: string
  SubOrderType?: string
  AssignedTechnician?: string
  TimeZone?: string