#%RAML 1.0 DataType
properties:
  ID: string
  Description: string
  IPAddress: string
  SenderMessageID: string
  TransactionCode: string
  CallingServiceName: string
  ApplicationID: string
  ApplicationVersion: string
  ContactName: string
  ContactEmail: string
  ContactPhoneNumber: string