#%RAML 1.0 DataType

properties: 
  saawQueryResponse:
    type: object
    properties:
      result:
        type: object
        properties:
          contractAccount:
            type: string
            example: ""
          error:
            type: string
            example: ""
          claimStatus: 
            type: string 
            example: "Abierto"
          claimDate:
            type: string 
            example: "2022-01-20"
          customerIdentification: 
            type: string
            example: "123456789"
          customerName:
            type: string 
            example: "PRUEBA SANITY PS"
          claimantName: 
            type: string  
            example: "PORTAFOLIO2 SUPERIOR2 CONTACTO"
          cunNumber: 
            type: string
            example: "?"
          customerSegment: 
            type: string 
            example: "MiPymes"
          claimValue: 
            type: string 
            example: "?"
