#%RAML 1.0 DataType
properties:
  id:
    type: string
    example: "003RT00000ACZU6YAP"
  tipoDocumento:
    type: string
    example: "CC"
  numeroDocumento:
      type: string
      example: "798135455"
  nombres:
    type: string
    example: "CATALINA"
  apellidos:
    type: string
    example: "SANTANTA"
  celular:
    type: string
    example: "3224569878"
  telefono:
    type: string
    example: "6017895642"
  correo:
    type: string
    example: "PRUEBA@ETB.COM"
  cargo:
    type: string
    example: "Vicepresidente"
  habeasData:
    type: string
    example: "AUTORIZA" 
  autorizado:
    type: string
    example: "No"
  integrationId:
    type: string
    example: "66a7c28c9f3a49582bb75343"