#%RAML 1.0 DataType
properties:
  WSRequestSolicitudSincronizacionABDResponse:
    type: object
    properties:
      result:
        type: object
        properties:
          strStatus:
            type: string
            example: "OK"