#%RAML 1.0 DataType
type: object
properties: 
    Id: 
      type: string
      example: "5004y00001us9etAAA"
    lstParametros: 
      type: string
      example: ""
    msgError: 
      type: object
      properties:
        codigoError:
          type: string
          example: ""            
        mensajeError:
          type: string  
          example: ""
    Name: 
      type: number
      example: 02858336
    resultado: 
      type: string
      example: "Exitoso"