#%RAML 1.0 DataType

description: Consulta de suscripción por MSISDN (mapeo desde PAPI / JSC).
type: object
properties:
  code:
    type: integer
    example: 200
  idSubscription:
    type: string
    required: false
  planName:
    type: string
    required: false
  status:
    type: string
    required: false
  billingType:
    type: string
    required: false
  balance:
    type: number
    required: false
  externalId:
    type: string
    required: false
  subscriberId:
    type: string
    required: false
