#%RAML 1.0 DataType

description: Promotions query response (normalized from sisext)
type: object
properties:
  responseDate?: string
  status?: string
  statusDetail?: string
  promotions?:
    type: array
    items:
      type: object
      properties:
        action?: string | nil
        description?: string | nil
        startDate?: string | nil
        actionDate?: string | nil
        endDate?: string | nil
        serviceTypeId?: string | nil
        id?: string | nil
        level?: string | nil
        name?: string | nil
        groupingNumber?: string | nil
        origin?: string | nil
        type?: string | nil
        applied?: any
        benefits?:
          type: array
          items: object
        characteristics?:
          type: array
          items: object
        isAccumulated?: any
        flexible?: any
        periods?: any
        percentage?: any
        firstPeriodDiscount?: any
        products?:
          type: array
          items: string
