# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
directv:
  protocol: "HTTPS"
  host: "api-gateway.dtvpan.com"
  port: "443"
  sendercountry: "CO"
  basePath: ""
  token:
    path: "/token"
    post:
      method: "POST"
  estadoCliente:
    path: "/api/partnerView/1.0/{id}"
    get:
      method: "GET"
  capturaAmazon: # --- activacion - reconexion ---
    path: "/API/ProductOrdering/14.0/productOrder"
    post:
      method: "POST"
  altaCustomer:
    path: "/API/CustomerManagement/17.0/customerAndProducts"
    post:
      method: "POST"
  refresh: # --- reenvio mail - reaprovisionamiento ---
    path: "/API/ActivationConfiguration/6.0/activate/refresh"
    post:
      method: "POST"
  cancelar: # --- cliente - amazon ---
    path: "/ProductInventoryManagement/4.0/cancelCustomerProducts"
    post:
      method: "POST"
  reconexionCustomer:
    path: "/API/ProductOrdering/14.0/productOrder/reconnect"
    post:
      method: "POST"