#%RAML 1.0 DataType
properties:
  ZFI_PAGOS_LINEA:
    type: object
    properties:
      RETURN:
        type: object
        properties:
          TYPE:
            type: string
            example: ""
          CODE:
            type: string
            example: ""
          MESSAGE:
            type: string
            example: ""
      T_FACTURAS:
        type: object
        properties:
          VBELN:
            type: string
            example: ""
          FKDAT:
            type: string
            example: ""
          NETWR:
            type: string
            example: ""
          KUNRG:
            type: string
            example: ""
          KUNAG:
            type: string
            example: ""
          ZTERM:
            type: string
            example: ""
          FEC_LIM_PAG:
            type: string
            example: ""
          NAME1:
            type: string
            example: ""
          STCD1:
            type: string
            example: ""
