#%RAML 1.0 DataType
type:  
  properties:
    Z_RM_RFC_CREATE_MASTER_DATA:
      properties:
        RETURN:
          properties:
              TYPE:
                type: string                   
                example : "S"
              CODE:
                type: string                  
                example : "000"
              MESSAGE:
                type: string
                example: "BP Modificado0024669020"                   

        CTRACPARTNERDETAIL?:
          type: any
        DIRECCIONES?:
          type: any
        EMAIL?:
          type: any
        FAX?:
          type: any
        IDENTIFICACION?:
          type: any
        RELACIONES?:
          type: any
        SECT_IND?:
          type: any
        TELEFONOS?:
          type: any
        T_ERRORES?:
          type: any
        USO_DIRECCIONES?:
          type: any

          
        
