#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    required: false
  responseMessage:
    type: string
    required: false
  penalty:
    type: object
    properties:
      billingNbr:
        type: string
        required: true
      acctId:
        type: integer
        required: true
      chargeList:
        type: array
        required: false
        items:
          type: object
          properties:
            basicCharge:
              type: string
              required: true
            acctItemTypeCode:
              type: string
              required: false
            taxList:
              type: array
              required: false
              items:
                type: object
                properties:
                  taxType:
                    type: string
                    required: true
                  taxRate:
                    type: string
                    required: true
                  taxAmount:
                    type: string
                    required: true
examples: 
  ZSMART_RESPONSE: !include ../../examples/response/get-agreement-zsmart.json