#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    required: false
  responseMessage:
    type: string
    required: false
  minimumTerm:
    type: object
    properties:
      clause:
        type: object
        properties:
          parentAccount:
            type: string
            required: false
          integrationId:
            type: string
            required: false
          internet:
            type: object
            properties:
              initialCharge:
                type: integer
                required: false
              currentBalance:
                type: integer
                required: false
              initialInstallments:
                type: integer
                required: false
              currentInstallments:
                type: integer
                required: false
              startDate:
                type: string
                required: false
              endDate:
                type: string
                required: false
              penaltyAmount:
                type: integer
                required: false
