#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: Subscriber created successfully
    required: false
  data:
    type: object
    properties:
      customerId:
        type: string
        example: '137396887'
        required: false
      partyRoleId:
        type: string
        example: >-
          {BAX}o0cRejZdEFBer4AUvetkk1RXlHSseOWngby2wjsHV2paAtcK2dSH73+3WDmgavpbVdApyhzfd/JCh+wHXL8Oyg==
        required: false
  responseMetadata:
    type: object
    properties:
      requestMetadata:
        type: object
        properties:
          systemId:
            type: string
            example: ETB
            required: false
          sender:
            type: object
            properties:
              country:
                type: string
                example: CO
                required: false
              milestone:
                type: string
                example: '123'
                required: false
          requestId:
            type: string
            example: '123123'
            required: false
          userId:
            type: string
            example: ETB
            required: false
      returnCode:
        type: string
        example: '0'
        required: false
      returnMessage:
        type: string
        example: OK
        required: false
