#%RAML 1.0 NamedExample
value:
  identification:
    id: "1-MUNC15O"
    businessComponentID: "1-MUNC15O"
    applicationObjectKeyID: "1-MUNC15O"
  lineOne: "CL 41B SUR 1F 20"
  cityName: "BOGOTA D.C."
  stateName: "BOGOTA"
  countryCode: "57"
  countryName: "Colombia"
  gisID: "612802304577533800"
  latitude: "4.552021"
  longitude: "-74.100763"
  cityCode: "11001"
  stateCode: "11"
  purposeCode: "1"
  reference: ""
  technology:
    type: "COBRE"
    coverageType: "Molecula"
    coverageIndicator: false
    coverageName: ""
    zone: "BOGO05"