#%RAML 1.0 NamedExample
value:
  gisID: "612802304577533800"
  latitude: "4.552021"
  longitude: "-74.100763"
  cityCode: "11001"
  stateCode: "11"
  purposeCode: "1"
  reference: ""
  technology:
    type: "COBRE"
    coverageType: ""
    coverageIndicator: false
    coverageName: ""
    zone: "BOGO05"