#%RAML 1.0 DataType
properties:
  status:
    type: string
    required: true
    example: "200"
  message:
    type: string
    required: true
    example: "files proccessed correctly"
  result:
    type: object
    properties:
      state:
        type: string
        required: true
        example: "success"
      tracingId:
        type: string
        required: true
        example: "ltkto0940-irui4-33k4l4-o4o5jl"
      summary:
        type: object
        properties:
          totalFiles:
            type: integer
            required: true
            example: 3
          processedFiles:
            type: integer
            required: true
            example: 2
          failedFiles:
            type: integer
            required: true
            example: 1
      details:
        type: array
        items:
          type: object
          properties:
            fileName:
              type: string
              required: true
              example: "file.pdf"
            status:
              type: string
              required: true
              example: "uploaded"
            blobPath?:
              type: string
              example: "docuNumber/pqrId/file.pdf"
            error?:
              type: string
              example: "Azure Storage Error"

example: !include ../../examples/response/post-pqr-attachments.json