#%RAML 1.0 DataType
properties:
  sim?:
    type: object
    properties:
      id:
        type: string
        example: "78901112"
      imsi:
        type: string
        example: "7321999999"
      status:
        type: string
        example: "FREE"
  msisdn?:
    type: object
    properties:
      id:
        type: string
        example: "12345631"
      status:
        type: string
        example: "FREE"