#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  serviceOrder:
    type: array
    items:
      type: object
      properties:
        service:
          type: object
          properties:
            address:
              type: object
              properties:
                city:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '11001'
                      required: false
                    name:
                      type: string
                      example: BOGOTA D.C.
                      required: false
                department:
                  type: object
                  properties:
                    id:
                      type: string
                      example: '11'
                      required: false
                    name:
                      type: string
                      example: BOGOTA
                      required: false
                coverage:
                  type: object
                  properties:
                    distanceType:
                      type: string
                      example: FE
                      required: false
                    gisAddress:
                      type: string
                      example: '612802304577522178'
                      required: false
                    idPlot:
                      type: string
                      example: '17'
                      required: false
                    latitude:
                      type: number
                      example: 4.670033966
                      required: false
                    longitude:
                      type: number
                      example: -74.11115231
                      required: false
                    molecule:
                      type: string
                      example: FFO14
                      required: false
                    name:
                      type: string
                      example: FFO14
                      required: false
                    olt:
                      type: string
                      example: BOFOZTC60107
                      required: false
                    owner:
                      type: string
                      example: ETB
                      required: false
                    district:
                      type: string
                      example: ''
                      required: false
                    locality:
                      type: string
                      example: ''
                      required: false
                    localityId:
                      type: string
                      example: '10'
                      required: false
                    stratum:
                      type: integer
                      example: 4
                      required: false
                    technology:
                      type: string
                      example: FTTH
                      required: false
                    type:
                      type: string
                      example: MOLECULA
                      required: false
                    zone:
                      type: string
                      example: FONTIBON
                      required: false
                country:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 593b0ac99a8e4177d410df4d
                      required: false
                    name:
                      type: string
                      example: ''
                      required: false
                id:
                  type: integer
                  example: 1
                  required: false
                state:
                  type: string
                  example: ACTIVO
                  required: false
                streetAddress:
                  type: string
                  example: KR 73 BIS 48 94
                  required: false
                type:
                  type: string
                  example: INSTALACION
                  required: false
            billing:
              type: object
              properties:
                address:
                  type: object
                  properties:
                    city:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '11001'
                          required: false
                        name:
                          type: string
                          example: BOGOTA D.C.
                          required: false
                    department:
                      type: object
                      properties:
                        id:
                          type: string
                          example: '11'
                          required: false
                        name:
                          type: string
                          example: BOGOTA
                          required: false
                    coverage:
                      type: object
                      properties:
                        distanceType:
                          type: string
                          example: FE
                          required: false
                        gisAddress:
                          type: string
                          example: '612802304577522178'
                          required: false
                        idPlot:
                          type: string
                          example: '17'
                          required: false
                        latitude:
                          type: number
                          example: 4.670033931732178
                          required: false
                        longitude:
                          type: number
                          example: -74.11115264892578
                          required: false
                        molecule:
                          type: string
                          example: FFO14
                          required: false
                        name:
                          type: string
                          example: FFO14
                          required: false
                        olt:
                          type: string
                          example: ''
                          required: false
                        owner:
                          type: string
                          example: ''
                          required: false
                        district:
                          type: string
                          example: ''
                          required: false
                        locality:
                          type: string
                          example: ''
                          required: false
                        localityId:
                          type: string
                          example: '10'
                          required: false
                        stratum:
                          type: integer
                          example: 4
                          required: false
                        technology:
                          type: string
                          example: FTTH
                          required: false
                        type:
                          type: string
                          example: MOLECULA
                          required: false
                        zone:
                          type: string
                          example: FONTIBON
                          required: false
                    country:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 593b0ac99a8e4177d410df4d
                          required: false
                        name:
                          type: string
                          example: ''
                          required: false
                    id:
                      type: integer
                      example: 2
                      required: false
                    state:
                      type: string
                      example: ACTIVO
                      required: false
                    streetAddress:
                      type: string
                      example: KR 73 BIS 48 94
                      required: false
                    type:
                      type: string
                      example: FACTURACION
                      required: false
                billingAccount:
                  type: string
                  example: '12052697835'
                  required: false
                billingAccountFather:
                  type: string
                  example: '12052697835'
                  required: false
                billingDueDay:
                  type: string
                  example: '0'
                  required: false
                billingDueOcsDay:
                  type: string
                  example: '30'
                  required: false
                billingDueDayUser:
                  type: string
                  example: '30'
                  required: false
                canUpdateDeliveryType:
                  type: boolean
                  example: true
                  required: false
                cycle:
                  type: string
                  example: '40'
                  required: false
                deliveryType:
                  type: string
                  example: Electronica
                  required: false
                email:
                  type: string
                  example: jaimepardo4936@gmail.com
                  required: false
                idSalesforce:
                  type: string
                  example: ''
                  required: false
                phone:
                  type: string
                  example: '3112162450'
                  required: false
                state:
                  type: string
                  example: ACTIVO
                  required: false
                stratum:
                  type: string
                  example: '4'
                  required: false
                type:
                  type: string
                  example: Detallada
                  required: false
            bundle:
              type: object
              properties:
                associated:
                  type: string
                  example: ''
                  required: false
                isbundle:
                  type: boolean
                  example: false
                  required: false
                type:
                  type: string
                  example: Sin asociar
                  required: false
            charging:
              type: string
              example: ''
              required: false
            collections:
              type: object
              properties:
                dates:
                  type: object
                  properties:
                    cancellationDate:
                      type: string
                      example: ''
                      required: false
                    reconnectionDate:
                      type: string
                      example: ''
                      required: false
                    suspensionDate:
                      type: object
                      properties:
                        date:
                          type: datetime-only
                          example: '2025-09-04T21:35:34'
                          required: false
                        format1:
                          type: string
                          example: 04/09
                          required: false
                        format2:
                          type: string
                          example: 04/09/2025
                          required: false
                        format3:
                          type: string
                          example: 04/09/2025 21:35:34
                          required: false
                        format4:
                          type: string
                          example: 04/09/2025 09:35:34 PM
                          required: false
                        day:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '04'
                              required: false
                            format2:
                              type: string
                              example: Jue.
                              required: false
                            format3:
                              type: string
                              example: Jueves
                              required: false
                        month:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '09'
                              required: false
                            format2:
                              type: string
                              example: Sept.
                              required: false
                            format3:
                              type: string
                              example: Septiembre
                              required: false
                        year:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '25'
                              required: false
                            format2:
                              type: string
                              example: '2025'
                              required: false
                            format3:
                              type: string
                              example: '02025'
                              required: false
                        hour:
                          type: object
                          properties:
                            format1:
                              type: time-only
                              example: '21:35:34'
                              required: false
                            format2:
                              type: string
                              example: 09:35:34 PM
                              required: false
                            format3:
                              type: string
                              example: '21'
                              required: false
                            format4:
                              type: string
                              example: 09 PM
                              required: false
                            format5:
                              type: string
                              example: '35'
                              required: false
                            format6:
                              type: string
                              example: '34'
                              required: false
                reason:
                  type: string
                  example: Suspendido por pago
                  required: false
                reconnectionAvailable:
                  type: boolean
                  example: true
                  required: false
                state:
                  type: string
                  example: Suspendido
                  required: false
            contractedOffer:
              type: object
              properties:
                plan:
                  type: object
                  properties:
                    home:
                      type: object
                      properties:
                        internet:
                          type: object
                          properties:
                            capacity:
                              type: string
                              example: ''
                              required: false
                            descentSpeed:
                              type: object
                              properties:
                                description:
                                  type: string
                                  example: 200M
                                  required: false
                                unity:
                                  type: string
                                  example: M
                                  required: false
                                value:
                                  type: string
                                  example: '200'
                                  required: false
                            isTwin:
                              type: boolean
                              example: true
                              required: false
                            secundary:
                              type: array
                              items:
                                type: object
                                properties:
                                  count:
                                    type: string
                                    example: ''
                                    required: false
                                  desc:
                                    type: string
                                    example: IP Dinámica
                                    required: false
                                  description:
                                    type: string
                                    example: IP Dinámica
                                    required: false
                                  icon:
                                    type: string
                                    example: ''
                                    required: false
                                  name:
                                    type: string
                                    example: IP DINÁMICA
                                    required: false
                                  type:
                                    type: string
                                    example: Secundario
                                    required: false
                            sharedCapacity:
                              type: string
                              example: ''
                              required: false
                            uploadSpeed:
                              type: object
                              properties:
                                description:
                                  type: string
                                  example: 200M
                                  required: false
                                unity:
                                  type: string
                                  example: M
                                  required: false
                                value:
                                  type: string
                                  example: '200'
                                  required: false
                        tv:
                          type: object
                          properties:
                            channels:
                              type: string
                              example: ''
                              required: false
                            numberOfChannels:
                              type: integer
                              example: 117
                              required: false
                            planType:
                              type: string
                              example: PLUS
                              required: false
                            secundary:
                              type: array
                              items:
                                type: object
                                properties:
                                  count:
                                    type: string
                                    example: ''
                                    required: false
                                  desc:
                                    type: string
                                    example: Decodificador incluido con tu plan
                                    required: false
                                  description:
                                    type: string
                                    example: Decodificador incluido con tu plan
                                    required: false
                                  icon:
                                    type: string
                                    example: >-
                                      https://strmietb.blob.core.windows.net/imagenes/flujocomercial/DECO/img-logo-deco.svg
                                    required: false
                                  name:
                                    type: string
                                    example: DECODIFICADOR 2
                                    required: false
                                  type:
                                    type: string
                                    example: SVA
                                    required: false
                        voice:
                          type: object
                          properties:
                            capacity:
                              type: object
                              properties:
                                description:
                                  type: string
                                  example: Llamadas ilimitadas
                                  required: false
                                unity:
                                  type: string
                                  example: MIN
                                  required: false
                                value:
                                  type: string
                                  example: Ilimitados
                                  required: false
                            secundary:
                              type: array
                              items:
                                type: object
                                properties:
                                  count:
                                    type: string
                                    example: ''
                                    required: false
                                  desc:
                                    type: string
                                    example: >-
                                      Identifica las llamadas entrantes cuando
                                      la línea este ocupada
                                    required: false
                                  description:
                                    type: string
                                    example: >-
                                      Identifica las llamadas entrantes cuando
                                      la línea este ocupada
                                    required: false
                                  icon:
                                    type: string
                                    example: ''
                                    required: false
                                  name:
                                    type: string
                                    example: IDENTIFICADOR DE SEGUNDA LLAMADA
                                    required: false
                                  type:
                                    type: string
                                    example: Secundario
                                    required: false
                    mobile:
                      type: string
                      example: ''
                      required: false
                    promotions:
                      type: array
                      items: {}
                    available:
                      type: boolean
                      example: false
                      required: false
                    contracted:
                      type: boolean
                      example: true
                      required: false
                    description:
                      type: array
                      items:
                        type: string
                    executionPlan:
                      type: array
                      items:
                        type: object
                        properties:
                          features:
                            type: array
                            items:
                              type: object
                              properties:
                                description:
                                  type: string
                                  example: >-
                                    Paga el valor original de tu plan TRIO 200M
                                    TV PLUS DOS DECOS $ 139,900
                                  required: false
                                differential:
                                  type: boolean
                                  example: false
                                  required: false
                                discount:
                                  type: boolean
                                  example: false
                                  required: false
                                outstanding:
                                  type: boolean
                                  example: false
                                  required: false
                                type:
                                  type: string
                                  example: Plan
                                  required: false
                          month:
                            type: integer
                            example: 1
                            required: false
                          saving:
                            type: string
                            example: ''
                            required: false
                          savingStr:
                            type: string
                            example: ''
                            required: false
                          state:
                            type: string
                            example: ''
                            required: false
                          value:
                            type: integer
                            example: 165799
                            required: false
                          valueStr:
                            type: string
                            example: $ 139.900
                            required: false
                    id:
                      type: string
                      example: '5990'
                      required: false
                    idsPackaging:
                      type: string
                      example: ''
                      required: false
                    installationCharges:
                      type: object
                      properties:
                        acceptPermanenceClause:
                          type: string
                          example: ''
                          required: false
                        installationChargesInternet:
                          type: integer
                          example: 750000
                          required: false
                        installationChargesTv:
                          type: integer
                          example: 0
                          required: false
                        installationChargesVoice:
                          type: integer
                          example: 750000
                          required: false
                        total:
                          type: integer
                          example: 2250000
                          required: false
                    isPacking:
                      type: boolean
                      example: false
                      required: false
                    isZoned:
                      type: boolean
                      example: false
                      required: false
                    name:
                      type: string
                      example: TRIO 200M TV PLUS DOS DECOS
                      required: false
                    nameTechnical:
                      type: string
                      example: TRIO 200M HOG SILVER FTTH 2 DECOS V2
                      required: false
                    outstanding:
                      type: boolean
                      example: false
                      required: false
                    price:
                      type: object
                      properties:
                        anticipatedPayment:
                          type: boolean
                          example: false
                          required: false
                        iva:
                          type: integer
                          example: 0
                          required: false
                        value:
                          type: integer
                          example: 139900
                          required: false
                        valueStr:
                          type: string
                          example: $ 139.900
                          required: false
                        valueWithoutIva:
                          type: integer
                          example: 139900
                          required: false
                        valueWithoutIvaStr:
                          type: string
                          example: $ 139.900
                          required: false
                        validity:
                          type: string
                          example: Cargo fijo mensual
                          required: false
                    retencion:
                      type: boolean
                      example: false
                      required: false
                    saving:
                      type: integer
                      example: 0
                      required: false
                    savingStr:
                      type: string
                      example: $ 0
                      required: false
                    stratum:
                      type: string
                      example: ''
                      required: false
                    subtype:
                      type: string
                      example: Internet + Telefonía + Televisión
                      required: false
                    svasFeatured:
                      type: string
                      example: ''
                      required: false
                    svasIncluded:
                      type: string
                      example: ''
                      required: false
                    technology:
                      type: string
                      example: FTTH
                      required: false
                    type:
                      type: string
                      example: TRIO
                      required: false
                    value:
                      type: integer
                      example: 139900
                      required: false
                    valueStr:
                      type: string
                      example: $ 139.900
                      required: false
                    zoned:
                      type: string
                      example: ''
                      required: false
                svas:
                  type: array
                  items:
                    type: object
                    properties:
                      mobile:
                        type: string
                        example: ''
                        required: false
                      promotions:
                        type: array
                        items: {}
                      subSvas:
                        type: string
                        example: ''
                        required: false
                      available:
                        type: boolean
                        example: false
                        required: false
                      description:
                        type: string
                        example: ''
                        required: false
                      characteristics:
                        type: array
                        items:
                          type: object
                          properties:
                            characteristic:
                              type: string
                              example: >-
                                Un decodificador adicional para que disfrutes
                                del servicio de TV
                              required: false
                            icon:
                              type: string
                              example: ''
                              required: false
                      conflicting:
                        type: array
                        items:
                          type: string
                      contracted:
                        type: boolean
                        example: true
                        required: false
                      executionPlan:
                        type: array
                        items:
                          type: object
                          properties:
                            features:
                              type: array
                              items:
                                type: object
                                properties:
                                  description:
                                    type: string
                                    example: >-
                                      Paga el valor original de tu servicio
                                      adicional DECO ADICIONAL $ 19,900
                                    required: false
                                  differential:
                                    type: boolean
                                    example: false
                                    required: false
                                  discount:
                                    type: boolean
                                    example: false
                                    required: false
                                  outstanding:
                                    type: boolean
                                    example: false
                                    required: false
                                  type:
                                    type: string
                                    example: SVA
                                    required: false
                            month:
                              type: integer
                              example: 1
                              required: false
                            saving:
                              type: string
                              example: ''
                              required: false
                            savingStr:
                              type: string
                              example: ''
                              required: false
                            state:
                              type: string
                              example: ''
                              required: false
                            value:
                              type: integer
                              example: 19900
                              required: false
                            valueStr:
                              type: string
                              example: $ 19.900
                              required: false
                      executionPlanDifferential:
                        type: string
                        example: ''
                        required: false
                      icon:
                        type: string
                        example: >-
                          https://strmietb.blob.core.windows.net/imagenes/flujocomercial/DECO/img-logo-deco.svg
                        required: false
                      id:
                        type: string
                        example: '6587'
                        required: false
                      idsOld:
                        type: array
                        items:
                          type: string
                      mandatory:
                        type: string
                        example: ''
                        required: false
                      name:
                        type: string
                        example: DECO ADICIONAL
                        required: false
                      price:
                        type: object
                        properties:
                          anticipatedPayment:
                            type: boolean
                            example: false
                            required: false
                          iva:
                            type: integer
                            example: 19
                            required: false
                          value:
                            type: integer
                            example: 19900
                            required: false
                          valueStr:
                            type: string
                            example: $ 19.900
                            required: false
                          valueWithoutIva:
                            type: integer
                            example: 16723
                            required: false
                          valueWithoutIvaStr:
                            type: string
                            example: $ 16.723
                            required: false
                          validity:
                            type: string
                            example: Cargo fijo mensual
                            required: false
                      quantity:
                        type: object
                        properties:
                          available:
                            type: integer
                            example: 2
                            required: false
                          contracted:
                            type: integer
                            example: 3
                            required: false
                      saving:
                        type: string
                        example: ''
                        required: false
                      serviceType:
                        type: string
                        example: TV
                        required: false
                      value:
                        type: integer
                        example: 19900
                        required: false
                      visibility:
                        type: object
                        properties:
                          action:
                            type: string
                            example: Nin
                            required: false
                          conditioned:
                            type: boolean
                            example: false
                            required: false
                          plans:
                            type: array
                            items:
                              type: string
                executionPlan:
                  type: array
                  items:
                    type: object
                    properties:
                      features:
                        type: array
                        items:
                          type: object
                          properties:
                            description:
                              type: string
                              example: >-
                                Paga el valor original de tu plan TRIO 200M TV
                                PLUS DOS DECOS $ 139,900
                              required: false
                            differential:
                              type: boolean
                              example: false
                              required: false
                            discount:
                              type: boolean
                              example: false
                              required: false
                            outstanding:
                              type: boolean
                              example: false
                              required: false
                            type:
                              type: string
                              example: Plan
                              required: false
                      month:
                        type: integer
                        example: 1
                        required: false
                      saving:
                        type: string
                        example: ''
                        required: false
                      savingStr:
                        type: string
                        example: ''
                        required: false
                      state:
                        type: string
                        example: ''
                        required: false
                      value:
                        type: integer
                        example: 165799
                        required: false
                      valueStr:
                        type: string
                        example: $ 139.900
                        required: false
            creationDate:
              type: object
              properties:
                date:
                  type: string
                  example: '2018-07-25T00:17:08Z'
                  required: false
                format1:
                  type: string
                  example: 25/07
                  required: false
                format2:
                  type: string
                  example: 25/07/2018
                  required: false
                format3:
                  type: string
                  example: 25/07/2018 00:17:08
                  required: false
                format4:
                  type: string
                  example: 25/07/2018 12:17:08 AM
                  required: false
                day:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '25'
                      required: false
                    format2:
                      type: string
                      example: Mié.
                      required: false
                    format3:
                      type: string
                      example: Miércoles
                      required: false
                month:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '07'
                      required: false
                    format2:
                      type: string
                      example: Jul.
                      required: false
                    format3:
                      type: string
                      example: Julio
                      required: false
                year:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '18'
                      required: false
                    format2:
                      type: string
                      example: '2018'
                      required: false
                    format3:
                      type: string
                      example: '02018'
                      required: false
                hour:
                  type: object
                  properties:
                    format1:
                      type: time-only
                      example: '00:17:08'
                      required: false
                    format2:
                      type: string
                      example: 12:17:08 AM
                      required: false
                    format3:
                      type: string
                      example: '00'
                      required: false
                    format4:
                      type: string
                      example: 12 AM
                      required: false
                    format5:
                      type: string
                      example: '17'
                      required: false
                    format6:
                      type: string
                      example: '08'
                      required: false
            customer:
              type: object
              properties:
                atdp:
                  type: object
                  properties:
                    channel:
                      type: string
                      example: V360
                      required: false
                    date:
                      type: object
                      properties:
                        date:
                          type: datetime
                          example: '2020-06-06T17:30:34.029Z'
                          required: false
                        format1:
                          type: string
                          example: 06/06
                          required: false
                        format2:
                          type: string
                          example: 06/06/2020
                          required: false
                        format3:
                          type: string
                          example: 06/06/2020 17:30:34
                          required: false
                        format4:
                          type: string
                          example: 06/06/2020 05:30:34 PM
                          required: false
                        day:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '06'
                              required: false
                            format2:
                              type: string
                              example: Sáb.
                              required: false
                            format3:
                              type: string
                              example: Sábado
                              required: false
                        month:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '06'
                              required: false
                            format2:
                              type: string
                              example: Jun.
                              required: false
                            format3:
                              type: string
                              example: Junio
                              required: false
                        year:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '20'
                              required: false
                            format2:
                              type: string
                              example: '2020'
                              required: false
                            format3:
                              type: string
                              example: '02020'
                              required: false
                        hour:
                          type: object
                          properties:
                            format1:
                              type: time-only
                              example: '17:30:34'
                              required: false
                            format2:
                              type: string
                              example: 05:30:34 PM
                              required: false
                            format3:
                              type: string
                              example: '17'
                              required: false
                            format4:
                              type: string
                              example: 05 PM
                              required: false
                            format5:
                              type: string
                              example: '30'
                              required: false
                            format6:
                              type: string
                              example: '34'
                              required: false
                    decision:
                      type: string
                      example: AUTORIZA
                      required: false
                    pqr:
                      type: string
                      example: 5edbd2b68c99497e9887d839
                      required: false
                    user:
                      type: string
                      example: sandquib
                      required: false
                birthday:
                  type: string
                  example: ''
                  required: false
                business:
                  type: string
                  example: ''
                  required: false
                collectionCommunications:
                  type: object
                  properties:
                    channels:
                      type: array
                      items:
                        type: object
                        properties:
                          channel:
                            type: string
                            example: WHATSAPP
                            required: false
                          value:
                            type: string
                            example: '3112162450'
                            required: false
                    creationDate:
                      type: object
                      properties:
                        date:
                          type: datetime
                          example: '2025-07-15T20:22:11.597Z'
                          required: false
                        format1:
                          type: string
                          example: 15/07
                          required: false
                        format2:
                          type: string
                          example: 15/07/2025
                          required: false
                        format3:
                          type: string
                          example: 15/07/2025 20:22:11
                          required: false
                        format4:
                          type: string
                          example: 15/07/2025 08:22:11 PM
                          required: false
                        day:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '15'
                              required: false
                            format2:
                              type: string
                              example: Mar.
                              required: false
                            format3:
                              type: string
                              example: Martes
                              required: false
                        month:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '07'
                              required: false
                            format2:
                              type: string
                              example: Jul.
                              required: false
                            format3:
                              type: string
                              example: Julio
                              required: false
                        year:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '25'
                              required: false
                            format2:
                              type: string
                              example: '2025'
                              required: false
                            format3:
                              type: string
                              example: '02025'
                              required: false
                        hour:
                          type: object
                          properties:
                            format1:
                              type: time-only
                              example: '20:22:11'
                              required: false
                            format2:
                              type: string
                              example: 08:22:11 PM
                              required: false
                            format3:
                              type: string
                              example: '20'
                              required: false
                            format4:
                              type: string
                              example: 08 PM
                              required: false
                            format5:
                              type: string
                              example: '22'
                              required: false
                            format6:
                              type: string
                              example: '11'
                              required: false
                    schedule:
                      type: string
                      example: L-V 7-7 & S 8-3
                      required: false
                    updateDate:
                      type: object
                      properties:
                        date:
                          type: datetime
                          example: '2025-07-15T20:22:45.097Z'
                          required: false
                        format1:
                          type: string
                          example: 15/07
                          required: false
                        format2:
                          type: string
                          example: 15/07/2025
                          required: false
                        format3:
                          type: string
                          example: 15/07/2025 20:22:45
                          required: false
                        format4:
                          type: string
                          example: 15/07/2025 08:22:45 PM
                          required: false
                        day:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '15'
                              required: false
                            format2:
                              type: string
                              example: Mar.
                              required: false
                            format3:
                              type: string
                              example: Martes
                              required: false
                        month:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '07'
                              required: false
                            format2:
                              type: string
                              example: Jul.
                              required: false
                            format3:
                              type: string
                              example: Julio
                              required: false
                        year:
                          type: object
                          properties:
                            format1:
                              type: string
                              example: '25'
                              required: false
                            format2:
                              type: string
                              example: '2025'
                              required: false
                            format3:
                              type: string
                              example: '02025'
                              required: false
                        hour:
                          type: object
                          properties:
                            format1:
                              type: time-only
                              example: '20:22:45'
                              required: false
                            format2:
                              type: string
                              example: 08:22:45 PM
                              required: false
                            format3:
                              type: string
                              example: '20'
                              required: false
                            format4:
                              type: string
                              example: 08 PM
                              required: false
                            format5:
                              type: string
                              example: '22'
                              required: false
                            format6:
                              type: string
                              example: '45'
                              required: false
                documentNumber:
                  type: string
                  example: '4933436'
                  required: false
                documentType:
                  type: string
                  example: CC
                  required: false
                email:
                  type: string
                  example: jaimepardo4936@gmail.com
                  required: false
                mobilePhone:
                  type: string
                  example: '3112162450'
                  required: false
                mobilePhone2:
                  type: string
                  example: ''
                  required: false
                name:
                  type: object
                  properties:
                    completeName:
                      type: string
                      example: JAIME ANANIAS PARDO ACOSTA
                      required: false
                    firstName:
                      type: string
                      example: JAIME
                      required: false
                    firstSurname:
                      type: string
                      example: PARDO
                      required: false
                    names:
                      type: string
                      example: JAIME ANANIAS
                      required: false
                    secondName:
                      type: string
                      example: ANANIAS
                      required: false
                    secondSurname:
                      type: string
                      example: ACOSTA
                      required: false
                    surnames:
                      type: string
                      example: PARDO ACOSTA
                      required: false
                segmentation:
                  type: object
                  properties:
                    attentionScheme:
                      type: string
                      example: ''
                      required: false
                    category:
                      type: string
                      example: PLATINO
                      required: false
                    profile:
                      type: string
                      example: ''
                      required: false
                    segment:
                      type: string
                      example: Hogares
                      required: false
                    uen:
                      type: string
                      example: Hogares y MiPymes
                      required: false
                    segmentUen:
                      type: string
                      example: Hogares
                      required: false
                validationCode:
                  type: object
                  properties:
                    isBlocked:
                      type: boolean
                      example: false
                      required: false
                    isEnabled:
                      type: boolean
                      example: false
                      required: false
                    lastTry:
                      type: string
                      example: ''
                      required: false
                    resetDate:
                      type: string
                      example: ''
                      required: false
                    retries:
                      type: string
                      example: ''
                      required: false
                    retriesRemain:
                      type: string
                      example: ''
                      required: false
            directvSubscription:
              type: object
              properties:
                countryCode:
                  type: string
                  example: ''
                  required: false
                creationDate:
                  type: string
                  example: ''
                  required: false
                email:
                  type: string
                  example: ''
                  required: false
                id:
                  type: string
                  example: ''
                  required: false
                name:
                  type: object
                  properties:
                    completeName:
                      type: string
                      example: ' '
                      required: false
                    firstName:
                      type: string
                      example: ''
                      required: false
                    firstSurname:
                      type: string
                      example: ''
                      required: false
                    names:
                      type: string
                      example: ''
                      required: false
                    secondName:
                      type: string
                      example: ''
                      required: false
                    secondSurname:
                      type: string
                      example: ''
                      required: false
                    surnames:
                      type: string
                      example: ''
                      required: false
                state:
                  type: boolean
                  example: false
                  required: false
                subscriptions:
                  type: string
                  example: ''
                  required: false
                updateDate:
                  type: string
                  example: ''
                  required: false
                username:
                  type: string
                  example: ''
                  required: false
            files:
              type: array
              items:
                type: object
                properties:
                  description:
                    type: string
                    example: ANEXO_DIGITAL_DEFINITIVO_SVA
                    required: false
                  name:
                    type: string
                    example: ANEXO_DIGITAL_DEFINITIVO_SVA
                    required: false
                  path:
                    type: string
                    example: 4933436/MDM-FIBRA-012894977/ANEXO_DIGITAL_DEFINITIVO_SVA
                    required: false
                  size:
                    type: string
                    example: ''
                    required: false
            hasFamilyAndFriends:
              type: boolean
              example: false
              required: false
            hasPasagigas:
              type: boolean
              example: false
              required: false
            home:
              type: object
              properties:
                numberDevices:
                  type: string
                  example: ''
                  required: false
                numberFloors:
                  type: integer
                  example: 2
                  required: false
                numberRooms:
                  type: integer
                  example: 2
                  required: false
                size:
                  type: integer
                  example: 0
                  required: false
                type:
                  type: string
                  example: ''
                  required: false
                usageTime:
                  type: object
                  properties:
                    entertainment:
                      type: string
                      example: ''
                      required: false
                    study:
                      type: string
                      example: ''
                      required: false
                    work:
                      type: string
                      example: ''
                      required: false
            inventory:
              type: object
              properties:
                home:
                  type: object
                  properties:
                    internet:
                      type: object
                      properties:
                        cvlanHuawei:
                          type: string
                          example: ''
                          required: false
                        devices:
                          type: array
                          items: {}
                        hasIps:
                          type: boolean
                          example: false
                          required: false
                        idServiceClass:
                          type: string
                          example: ''
                          required: false
                        idService:
                          type: string
                          example: 1-MN2EHRT
                          required: false
                        ips:
                          type: string
                          example: ''
                          required: false
                        serviceClass:
                          type: string
                          example: Broadband Service Class
                          required: false
                        speed:
                          type: object
                          properties:
                            downloadSpeed:
                              type: string
                              example: 500M
                              required: false
                            loadingCapacity:
                              type: string
                              example: ''
                              required: false
                            uploadSpeed:
                              type: string
                              example: 500M
                              required: false
                    tv:
                      type: object
                      properties:
                        devices:
                          type: array
                          items:
                            type: object
                            properties:
                              firmware:
                                type: string
                                example: ''
                                required: false
                              isAvailableSetWifi:
                                type: boolean
                                example: false
                                required: false
                              isDual:
                                type: boolean
                                example: false
                                required: false
                              isMesh:
                                type: boolean
                                example: false
                                required: false
                              isPrincipalAp:
                                type: boolean
                                example: false
                                required: false
                              networks:
                                type: string
                                example: ''
                                required: false
                              serviceClass:
                                type: string
                                example: ''
                                required: false
                              status:
                                type: boolean
                                example: false
                                required: false
                              acsModel:
                                type: string
                                example: ''
                                required: false
                              brand:
                                type: string
                                example: HUAWEI
                                required: false
                              model:
                                type: string
                                example: EC2108V5
                                required: false
                              serial:
                                type: string
                                example: 21500821467UH7357818
                                required: false
                              technology:
                                type: string
                                example: ''
                                required: false
                              type:
                                type: string
                                example: '0'
                                required: false
                        idServiceClass:
                          type: string
                          example: ''
                          required: false
                        idService:
                          type: string
                          example: 1-MN2EHRH
                          required: false
                        serviceClass:
                          type: string
                          example: Television Service Class
                          required: false
                        subscriberId:
                          type: string
                          example: '289485'
                          required: false
                lte:
                  type: string
                  example: ''
                  required: false
            mietbuser:
              type: string
              example: ''
              required: false
            ota:
              type: string
              example: ''
              required: false
            pasagigas:
              type: string
              example: ''
              required: false
            permanenceClause:
              type: array
              items:
                type: object
                properties:
                  currentBalance:
                    type: string
                    example: '0'
                    required: false
                  currentBalanceStr:
                    type: string
                    example: $0
                    required: false
                  currentInstallment:
                    type: string
                    example: '0'
                    required: false
                  discount:
                    type: string
                    example: '0'
                    required: false
                  discountStr:
                    type: string
                    example: $0
                    required: false
                  endDate:
                    type: string
                    example: 23/07/2019
                    required: false
                  initialCharge:
                    type: string
                    example: '0'
                    required: false
                  initialChargeStr:
                    type: string
                    example: $0
                    required: false
                  initialDate:
                    type: string
                    example: 24/07/2018
                    required: false
                  initialInstallment:
                    type: string
                    example: '12'
                    required: false
                  technology:
                    type: string
                    example: Television
                    required: false
            rateIncrease:
              type: object
              properties:
                rates:
                  type: array
                  items:
                    type: object
                    properties:
                      applicationDate:
                        type: object
                        properties:
                          date:
                            type: string
                            example: '2025-03-01T05:00:00Z'
                            required: false
                          format1:
                            type: string
                            example: 01/03
                            required: false
                          format2:
                            type: string
                            example: 01/03/2025
                            required: false
                          format3:
                            type: string
                            example: 01/03/2025 05:00:00
                            required: false
                          format4:
                            type: string
                            example: 01/03/2025 05:00:00 AM
                            required: false
                          day:
                            type: object
                            properties:
                              format1:
                                type: string
                                example: '01'
                                required: false
                              format2:
                                type: string
                                example: Sáb.
                                required: false
                              format3:
                                type: string
                                example: Sábado
                                required: false
                          month:
                            type: object
                            properties:
                              format1:
                                type: string
                                example: '03'
                                required: false
                              format2:
                                type: string
                                example: Mar.
                                required: false
                              format3:
                                type: string
                                example: Marzo
                                required: false
                          year:
                            type: object
                            properties:
                              format1:
                                type: string
                                example: '25'
                                required: false
                              format2:
                                type: string
                                example: '2025'
                                required: false
                              format3:
                                type: string
                                example: '02025'
                                required: false
                          hour:
                            type: object
                            properties:
                              format1:
                                type: time-only
                                example: '05:00:00'
                                required: false
                              format2:
                                type: string
                                example: 05:00:00 AM
                                required: false
                              format3:
                                type: string
                                example: '05'
                                required: false
                              format4:
                                type: string
                                example: 05 AM
                                required: false
                              format5:
                                type: string
                                example: '00'
                                required: false
                              format6:
                                type: string
                                example: '00'
                                required: false
                      id:
                        type: string
                        example: INC-TAR-000005408221
                        required: false
                      value:
                        type: object
                        properties:
                          numericalValue:
                            type: integer
                            example: 12176
                            required: false
                          valueInCurrencyFormat:
                            type: string
                            example: $ 12.176,00
                            required: false
                      valueWithoutIva:
                        type: object
                        properties:
                          numericalValue:
                            type: integer
                            example: 10232
                            required: false
                          valueInCurrencyFormat:
                            type: string
                            example: $ 10.232,00
                            required: false
                total:
                  type: object
                  properties:
                    numericalValue:
                      type: integer
                      example: 20395
                      required: false
                    valueInCurrencyFormat:
                      type: string
                      example: $ 20.395,00
                      required: false
                totalWithoutIva:
                  type: object
                  properties:
                    numericalValue:
                      type: integer
                      example: 17138
                      required: false
                    valueInCurrencyFormat:
                      type: string
                      example: $ 17.138,00
                      required: false
            updateDate:
              type: object
              properties:
                date:
                  type: datetime
                  example: '2025-09-08T12:24:24.894Z'
                  required: false
                format1:
                  type: string
                  example: 08/09
                  required: false
                format2:
                  type: string
                  example: 08/09/2025
                  required: false
                format3:
                  type: string
                  example: 08/09/2025 12:24:24
                  required: false
                format4:
                  type: string
                  example: 08/09/2025 12:24:24 PM
                  required: false
                day:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '08'
                      required: false
                    format2:
                      type: string
                      example: Lun.
                      required: false
                    format3:
                      type: string
                      example: Lunes
                      required: false
                month:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '09'
                      required: false
                    format2:
                      type: string
                      example: Sept.
                      required: false
                    format3:
                      type: string
                      example: Septiembre
                      required: false
                year:
                  type: object
                  properties:
                    format1:
                      type: string
                      example: '25'
                      required: false
                    format2:
                      type: string
                      example: '2025'
                      required: false
                    format3:
                      type: string
                      example: '02025'
                      required: false
                hour:
                  type: object
                  properties:
                    format1:
                      type: time-only
                      example: '12:24:24'
                      required: false
                    format2:
                      type: string
                      example: 12:24:24 PM
                      required: false
                    format3:
                      type: string
                      example: '12'
                      required: false
                    format4:
                      type: string
                      example: 12 PM
                      required: false
                    format5:
                      type: string
                      example: '24'
                      required: false
                    format6:
                      type: string
                      example: '24'
                      required: false
            billingAccount:
              type: string
              example: '12052697835'
              required: false
            integrationId:
              type: string
              example: 1-MN2A7LJ
              required: false
            lineType:
              type: string
              example: FTTH
              required: false
            migrated:
              type: boolean
              example: false
              required: false
            nickname:
              type: object
              properties:
                icon:
                  type: string
                  example: ''
                  required: false
                nickname:
                  type: string
                  example: ''
                  required: false
            phone:
              type: string
              example: '6014571065'
              required: false
            retencion:
              type: boolean
              example: false
              required: false
            serviceAccount:
              type: string
              example: 1-MN2A7LJ
              required: false
            state:
              type: object
              properties:
                reason:
                  type: string
                  example: Suspensión por pago
                  required: false
                state:
                  type: string
                  example: Suspendido
                  required: false
            technology:
              type: string
              example: FTTH
              required: false
