#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  detail:
    type: object
    required: false
    properties:
      state:
        type: string
        example: ''
        required: false
      resourceId:
        type: string
        example: ''
        required: false
