#%RAML 1.0 DataType
properties:
  status:
    type: number
    example: 404
  code:
     type: string
     example: "NOT_FOUND"
  message:
    type: object
    properties:
      message:
        type: string
        example: ""
        required: false
  messageServer:
    type: string
    example: "Data not found"
    required: false
  cause:
    type: array
    items:
      properties:
        origin:
          type: string
          required: false
          example: "jsc-sapi-services-qa"
        message:
          type: string
          required: false
          example: "org.mule.extension.http.api.exception.NotFoundExcecption"