#%RAML 1.0 DataType
properties:
  subscriberId:
    type: string
    example: "12345"
    description: "Identificador del suscriptor en la plataforma JSC."
  subscriptionId:
    type: string
    example: "SID1_0001"
    description: "Identificador de la suscripción del servicio del cliente en la plataforma JSC."
  parentPkgInstanceId:
    type: string
    example: "PKGID11_TS1708598971841"
    description: "Identificador del package instance de una línea LTE padre que pertenece a una bolsa compartida (Group)"
  description:
    type: string
    example: "Activación Exitosa"
    description: "Resultado del procesamiento de la solicitud."