#%RAML 1.0 DataType
type: object
properties:
  cliente:
    type: object
    properties:
      categoria:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Categoria"
      correoElectronico:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Correo_Electronico"
      nombre:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Nombre_Cliente"
      numeroDocumento:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Categoria"
      segmento:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Segmento"
      segmentoUEN:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Segmento_UEN"
      tipoDocumento:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Tipo_Identificacion"
      uen:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.UEN"              
  recuperacionExperiencia:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Recuperacion_Experiencia"
  servicios:      
    type: array
    items:
      type: object
      properties:  
        cuentaFacturacion:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Servicios.Cuenta_Facturacion"
        cuentaServicio:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Servicios.Cuenta_Servici"
        direccionInstalacion:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Servicios.Direccion_Instalacion"
        estado:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Servicios.Estado"
        numeroConexion:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Servicios.Numero_Conexion"
        subEstado:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Servicios.Sub_Estado"
        tecnologia:
          type: string
          required: false
          example: "IVR_CONTACTO_FRECUENTE.Tecnologia"         
  tipoAtencion:
        type: string
        required: false
        example: "IVR_CONTACTO_FRECUENTE.Tipo_Atencion"             