#%RAML 1.0 DataType
properties:
  cliente:
    type: object
    properties:
      numeroIdentificacion:
        type: string
        example: "numeroIdentificacion"
      tipoIdentificacion:
        type: string
        example: "tipoIdentificacion"
  encuestas:
    type: string
    example: "Resultado de la consulta a encuestas"
  recurrente:
    type: object
    properties:
      agendamientos:
        type: string
        example: "¿Recurrente por agendamientos?"
      comercial:
        type: string
        example: "¿Recurrente por trámites?"
      pqrs:
        type: string
        example: "¿Recurrente por PQRs?"
      tecnico:
        type: string
        example: " pqrs || visitas || agendamientos "
      tramites:
        type: string
        example: "¿Recurrente por trámites?"
      visitas:
        type: string
        example: "¿Recurrente por visitas?"
  tipoAtencion:
    type: string
    example: "Resultado a la consulta del tipo de atención"