#%RAML 1.0 DataType
properties:
  codigo:
    type: string
    example: "OK"
  descripcion:
    type: string
    example: "Cancelación exitosa"

example: {codigo: "OK", descripcion: "Proceso exitoso."}