#%RAML 1.0 DataType
type: object
properties:
    Resultado:
      type: string
    Codigo:
      type: number
    Descripcion:
      type: string
    Estado:
      type: string | nil
    EstadoRecurso:
      type: string | nil
    Fecha:
      type: string | nil
    ICCID:
      type: number | nil
    IMSI:
      type: number | nil
    IdPedido:
      type: string | nil
    IdServicio:
      type: string | nil
    MSISDN:
      type: number | nil
    Modelo:
      type: string | nil
    Operacion:
      type: string
    PIN:
      type: string | nil
    PIN2:
      type: string | nil
    PUK:
      type: string | nil
    PUK2:
      type: string | nil
    TipoRecurso:
      type: string | nil
    Tramite:
      type: string | nil
