#%RAML 1.0 DataType
type: object
discriminatorValue: SVA
properties:
  transactionId:
    type: string
    example: c3d4e5f6-a7b8-9012-cdef-012345678901
    required: false
  processCode:
    type: string
    required: false
  status:
    type: string
    example: SUCCESS
    required: false
  updatedAt:
    type: string
    example: '2026-03-19T10:00:01Z'
    required: false
  result:
    type: object
    required: false
    properties:
      customerId:
        type: string
        example: '12345678'
        required: false
      serviceId:
        type: string
        example: '98765'
        required: false
      added:
        type: array
        required: false
        items:
          type: object
          properties:
            itemTypeCode:
              type: string
              example: SVA_VOICEMAIL
              required: false
      removed:
        type: array
        required: false
        items:
          type: object
          properties:
            itemTypeCode:
              type: string
              example: SVA_CALLWAIT
              required: false
      zsmartResponseCode:
        type: string
        example: '0'
        required: false
      zsmartMessage:
        type: string
        example: Success
        required: false