#%RAML 1.0
title: audits-oracle-sapi-services
baseUri: audits-oracle-sapi-services.us-e2.cloudhub.io/audits
traits:
  common-headers: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml

uses:
  definitions: types/library.raml
/v1:
  /logs:
    is: [common-headers]
    displayName: Logging Service
    description: Service to save the traceability in ETB API enviroment
    /systems/{system_id}/apis/{api_id}:
      uriParameters:
        system_id:
          enum:
            - TRANSACCCIONES_OM
            - MIGRACION
            - MAYORISTAS
            - OTINICIATIVAS
          description: This subresource describe the source of the log
        api_id:
          type: string
          description: This subresource describe the source of the log  
          example:
            sap-sapi-services
      post:
        body:
          application/json:
            type: definitions.postLogsAPI
            example: !include examples/post-logs-api.json   
        responses:
          201:
            description: Created
            body:
              application/json: 
          400:
            description: Bad request
          401:
            description: Not authorized.
    /apis/{system}/{api_id}:
      uriParameters:
        system:
          type: string
          enum:
            - LOG_TRANSACCCIONES_OM
            - LOG_MIGRACION
            - LOG_MAYORISTAS
            - LOG_OTTINICIATIVAS
          description: This subresource describe the source of the log
        api_id:
          type: string
          description: This subresource describe the source of the log
          example: 
            sap-sapi-services
      get:
          is: [common-headers]
          displayName: Obtain Correlation Id
          description: Service to obtain the consecutive from the DB mongo
          queryParameters:
            http_code:
              type: string
              description: The http_code must match with the example but with any number separated with ,
              pattern: \[(\"[0-9]{3}\"(,"[0-9]{3}\")*)\]
              example: '["200","201"]'
            date:
              type: integer
              required: true
              example: 20211119
          responses:
            200:
            400:
              description: Bad request
            401:
              description: Not authorized.
  /audits:
    post:
      is: [common-headers]
      displayName: Create Audit Record
      description: Creates a new audit record in the Oracle database with the information associated with the execution of an API request or response.
      body:
        application/json:
          type: !include types/request/post-audits-request.raml
          example: !include examples/post-audits-request.json
      responses:
        201:
          description: Created
          body:
            application/json: 
              type: !include types/response/post-audits-response.raml
              example: !include examples/post-audits-response.json
        400:
          description: Bad request
        401:
          description: Not authorized.