#%RAML 1.0 DataType 
type: object
properties:
  clausula:
    type: object
    properties:
      cuenta_padre:
        type: string
        example: '15052963375'
        required: false
      integration_id:
        type: string
        example: CS-1052455
        required: false
      Internet:
        type: object
        properties:
          CargoInicial:
            type: string
            example: '750000'
            required: false
          SaldoActual:
            type: string
            example: '750000'
            required: false
          CuotasInicial:
            type: string
            example: '12'
            required: false
          CuotasActual:
            type: string
            example: '12'
            required: false
          fecha_inicio:
            type: string
            example: 06/08/2025
            required: false
          fecha_fin:
            type: string
            example: 06/08/26
            required: false
      valor_penalidad:
        type: string
        example: '750000'
        required: false
  resultado:
    type: string
    example: '0'
    required: false
  descError:
    type: string
    example: OK
    required: false
