#%RAML 1.0 DataType
type: object
displayName: hierarchyAccount
properties:
  response:
    type: object
    properties:
      Headers:
        type: object
        properties:
          status:
            type: string
          responseDate:
            type: string
      Body:
        type: object
        properties:
          HierarchyAccounts:
            type: object
            properties:
              operation:
                type: string
              result:
                type: string
              system:
                type: string
              portalData:
                type: object
                properties:
                  hierarchyAccounts:
                    type: object
                    properties:
                      invoiceDate:
                        type: string
                      state:
                        type: string
                      sourceBillingCycle:
                        type: string
                      destinationBillingCycle:
                        type: string
            

example: !include ../../examples/responses/get-HierarchyAccount200Response.json