#%RAML 1.0 DataType
properties:
  RETURN: 
    type: !include subdatatypes/return.raml
  CTRACPARTNERDETAIL: 
    type: object
    properties:
      item: 
        type: !include subdatatypes/ctracpartnerdetailItem.raml

#example:
#  !include ../../examples/responses/CreateRMCAAccountOutputExample.raml