#%RAML 1.0 DataType
properties:
  WSResponseVariacionFactura:
    type: object
    properties:
      response_code:
        type: object
        properties:
          code: string
          description: string
      variacion_factura:
        type: object
        properties:
          factura:
            type: array
            items:
              properties:
                mensaje: string
                fecha_creacion: string