#%RAML 1.0 DataType
properties:
  ordenOM:
    type: string
    example: "TEST_BILLING"
  agrupador:
    type: string
    example: "123"
  resultado:
    type: string
    example: "Positivo"
  fecha:
    type: string
    example: "2022-11-17T21:00:34.305119Z"
  descripcion:
    type: string
    example: ""
