#%RAML 1.0 DataType
properties:
  Set_BillingAccountResponse:
    type: object
    properties:
      Set_BillingAccountResult:
        type: object
        properties:
          WSResponseHeader:
            type: !include subdatatypes/WSResponseHeader.raml
          WSResponseBody:
            type: !include subdatatypes/WSResponseBody.raml

example: !include ../../examples/responses/Set_MdmAccountResponseExample.json