#%RAML 1.0 DataType
properties:
  id:
    type: string
    example: "500U100000DY3QfIAL"
  cun:
    type: string
    example: ""
  consecutivo:
      type: string
      example: "17609188"
  estado:
    type: string
    example: "En Progreso"
  asunto:
    type: string
    example: "SIN SERVICIO / ID000CI1127805 - Archivo Bogotá / Internet 26JULIO"
  fechaRadicacion:
    type: string
    example: "2024-07-26"
  tipoCaso:
    type: string
    example: "SOPORTE TECNICO"
  descripcionAvance:
    type: string
    example: "Descripcion de avance"