#%RAML 1.0 DataType
properties:
  responseHeader:
    type: object
    properties:
      system:
        type: !include objects/system.raml
        required: false
      service:
        type: !include objects/serviceStatus.raml
        required: false
      properties:
        type: array
        items: !include objects/property.raml
        required: false

  responseBody:
    type: object
    properties:
      contracted:
        type: object
        required: false  
        properties:
          plan:
            type: !include objects/plan.raml
            required: false
          svas:
            type: array
            items: !include objects/sva.raml
            required: false
          executionPlan:
            type: array
            items: !include objects/executionPlan.raml
            required: false
      suggested:
        type: object
        required: false
        properties:
          plans:
            type: array
            items: !include objects/plan.raml
            required: false
          svas:
            type: array
            items: !include objects/sva.raml
            required: false