#%RAML 1.0 DataType

properties:
  responseHeader:
    type: object
    properties:
      system:
        type: !include objects/system.raml
        required: false
      service:
        type: !include objects/serviceStatus.raml
        required: false
      properties:
        type: array
        items: !include objects/property.raml
        required: false
  responseBody:
    type: array
    items:
      type: object
      properties:
        city:
          type: string
          example: CHIGORODO
          required: false
        cityDANE:
          type: string
          example: '05172'
          required: false
        cobertures:
          type: object
          properties:
            coberture:
              type: boolean
              example: true
              required: false
            delivery:
              type: array
              items:
                type: object
                properties:
                  daysOL:
                    type: integer
                    example: 6
                    required: false
                  hoursOL:
                    type: integer
                    example: 0
                    required: false
                  type:
                    type: string
                    example: BASICA
                    required: false
            operator:
              type: string
              example: DHL
              required: false
        country:
          type: string
          example: Colombia
          required: false
        countryISO:
          type: string
          example: CO
          required: false
        departament:
          type: string
          example: ANTIOQUIA
          required: false
        departmentDANE:
          type: string
          example: '05'
          required: false
