#%RAML 1.0 DataType
type: object
properties:
  ID:
    type: string
  Numero_Whatsapp:
    type: string
  sistema_origen:
    type: string
  Fecha_hora:
    type: string
  Procesado:
    type: boolean
  Tramite:
    type: string
  Opciones_Plantilla:
    type: array
    items:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
  Numero_Orden:
    type: string
  Cuenta:
    type: string
  Numero_factura:
    type: string
  Numero_cuenta_pago:
    type: string
  Nombre_Cliente:
    type: string
  Apellido_Cliente:
    type: string
  Tipo_Documento:
    type: string
  Numero_Documento:
    type: string
  Identificador_Tramite:
    type: string
  CUN:
    type: string
  Numero_servicio:
    type: string