#%RAML 1.0 DataType
properties:
  SPNPQRLoggerOutput:
    type: object
    properties:
      WSResponseHeader2:
        type : object
        properties:
          System: !include objects/system.raml
          Service:
            type: object
            properties:
              status:
                type: string
                example: ""
              responseDate:
                type: date-only
                example: 2022-08-05
              statusDetail:
                type: object
                properties:
                  errorCode:
                    type: string
                    example: ""
                  errorMessage:
                    type: string
                    example: ""
      SPNPQRLoggerOUT:
        type: object
        properties:
          Resultado:
            type: string
            example: ""
          Descripcion:
            type: string
            example: ""