#%RAML 1.0 DataType

properties:
  responseHeader:
    type: object
    properties:
      system:
        type: !include objects/system.raml
        required: false
      service:
        type: !include objects/serviceStatus.raml
        required: false
      properties:
        type: array
        items: !include objects/property.raml
        required: false

  responseBody:
    type: object
    properties:
      totalValue: number
      totalValueStr: string