#%RAML 1.0 DataType
properties:
  responseHeader:
    type: object
    properties:
      system:
        type: !include objects/system.raml
        required: false
      service:
        type: !include objects/serviceStatus.raml
        required: false
      properties:
        type: array
        items: !include objects/property.raml
        required: false
  responseBody:
    type: object
    properties:
      agenda:
        type: string
        example: ''
        required: false
      communications:
        type: object
        properties:
          comunicacionesCanales:
            type: string
            example: SMS
            required: false
          comunicacionesHorarios:
            type: string
            example: L-V 7-7 & S 8-3
            required: false
          comunicacionesUpdate:
            type: boolean
            example: true
            required: false
      contact:
        type: string
        example: ''
        required: false
      creationDate:
        type: datetime
        example: '2025-05-21T20:48:52.007Z'
        required: false
      cun:
        type: string
        example: '4347200000263825'
        required: false
      customer:
        type: object
        properties:
          documentNumber:
            type: string
            example: '4712102'
            required: false
          documentType:
            type: string
            example: CC
            required: false
          email:
            type: string
            example: nahah46814@dlbazi.com
            required: false
          obtainedScore:
            type: string
            example: '999'
            required: false
          optionSelectedValidation:
            type: string
            example: OTP
            required: false
          phone:
            type: string
            example: '3000000000'
            required: false
          surname:
            type: string
            example: PEDRO
            required: false
      executionPlan:
        type: array
        items:
          type: object
          properties:
            features:
              type: array
              items:
                type: object
                properties:
                  description:
                    type: string
                    example: 20% de descuento en el valor de tu plan Ilimigigas
                    required: false
                  differential:
                    type: boolean
                    example: false
                    required: false
                  discount:
                    type: boolean
                    example: true
                    required: false
                  outstanding:
                    type: boolean
                    example: false
                    required: false
                  type:
                    type: string
                    example: Plan
                    required: false
            month:
              type: integer
              example: 1
              required: false
            saving:
              type: integer
              example: 39479
              required: false
            savingStr:
              type: string
              example: $ 39.479
              required: false
            state:
              type: string
              example: ''
              required: false
            value:
              type: integer
              example: 58320
              required: false
            valueStr:
              type: string
              example: $ 58.320
              required: false
      installationAddress:
        type: object
        properties:
          address:
            type: string
            example: 'Cl. 83 Bis #23, Bogotá, Colombia'
            required: false
          city:
            type: string
            example: BOGOTA D.C.
            required: false
          codCityDane:
            type: string
            example: '11001'
            required: false
          codDeptoDane:
            type: string
            example: '11'
            required: false
          department:
            type: string
            example: BOGOTA
            required: false
          latitude:
            type: string
            example: ''
            required: false
          longitude:
            type: string
            example: ''
            required: false
          stratum:
            type: string
            example: ''
            required: false
          zone:
            type: string
            example: ''
            required: false
      installationCharges:
        type: string
        example: ''
        required: false
      notifications:
        type: string
        example: ''
        required: false
      numOrder:
        type: string
        example: MDM-PLTE-022938
        required: false
      plan:
        type: object
        properties:
          internet:
            type: object
            properties:
              numberDevices:
                type: string
                example: ''
                required: false
              svas:
                type: string
                example: ''
                required: false
              usageTime:
                type: string
                example: ''
                required: false
              capacity:
                type: object
                properties:
                  description:
                    type: string
                    example: En redes 3G/4G
                    required: false
                  unity:
                    type: string
                    example: ''
                    required: false
                  value:
                    type: string
                    example: Ilimitado
                    required: false
              descentSpeed:
                type: string
                example: ''
                required: false
              isTwin:
                type: string
                example: ''
                required: false
              secundary:
                type: array
                items:
                  type: object
                  properties:
                    count:
                      type: string
                      example: ''
                      required: false
                    desc:
                      type: string
                      example: Datos ilimitados para navegar en red 3G/4G
                      required: false
                    description:
                      type: string
                      example: Datos ilimitados para navegar en red 3G/4G
                      required: false
                    icon:
                      type: string
                      example: ''
                      required: false
                    name:
                      type: string
                      example: DATOS ILIMITADOS EN 3G/4G
                      required: false
                    type:
                      type: string
                      example: Secundario
                      required: false
              sharedCapacity:
                type: string
                example: 100 Gigas para compartir
                required: false
              uploadSpeed:
                type: string
                example: ''
                required: false
          promotions:
            type: array
            items:
              type: object
              properties:
                activationDate:
                  type: datetime
                  example: '2025-05-09T08:23:29.981Z'
                  required: false
                currentMonth:
                  type: string
                  example: ''
                  required: false
                inactivationDate:
                  type: string
                  example: ''
                  required: false
                timeLeft:
                  type: string
                  example: ''
                  required: false
                benefit:
                  type: string
                  example: 20%
                  required: false
                conditioned:
                  type: boolean
                  example: false
                  required: false
                description:
                  type: string
                  example: 20% de descuento en el valor de tu plan Ilimigigas
                  required: false
                descriptionShort:
                  type: string
                  example: 20% de Descuento
                  required: false
                differential:
                  type: boolean
                  example: false
                  required: false
                discounts:
                  type: array
                  items:
                    type: object
                    properties:
                      benefit:
                        type: string
                        example: 20%
                        required: false
                      description:
                        type: string
                        example: 20% de Descuento
                        required: false
                      validity:
                        type: string
                        example: Vitalicio
                        required: false
                id:
                  type: string
                  example: 61956ae0d7083a19302ab63b
                  required: false
                isZoned:
                  type: string
                  example: ''
                  required: false
                mandatoryPlans:
                  type: string
                  example: ''
                  required: false
                name:
                  type: string
                  example: 20% de descuento en el valor de tu plan Ilimigigas
                  required: false
                outstanding:
                  type: boolean
                  example: false
                  required: false
                quantity:
                  type: string
                  example: ''
                  required: false
                stratums:
                  type: string
                  example: ''
                  required: false
                type:
                  type: string
                  example: Descuento
                  required: false
                validity:
                  type: string
                  example: Vitalicio
                  required: false
                zoned:
                  type: object
                  properties:
                    localities:
                      type: string
                      example: ''
                      required: false
                    isZoned:
                      type: string
                      example: ''
                      required: false
          rateIncrease:
            type: string
            example: ''
            required: false
          rateIncreaseTotal:
            type: string
            example: ''
            required: false
          saleOrder:
            type: string
            example: ''
            required: false
          sms:
            type: object
            properties:
              svas:
                type: string
                example: ''
                required: false
              capacity:
                type: object
                properties:
                  description:
                    type: string
                    example: ILIMITADOS
                    required: false
                  unity:
                    type: string
                    example: SMS
                    required: false
                  value:
                    type: string
                    example: Ilimitados
                    required: false
              secundary:
                type: array
                items:
                  type: object
                  properties:
                    count:
                      type: string
                      example: ''
                      required: false
                    desc:
                      type: string
                      example: SMS ilimitados
                      required: false
                    description:
                      type: string
                      example: SMS ilimitados
                      required: false
                    icon:
                      type: string
                      example: ''
                      required: false
                    name:
                      type: string
                      example: SMS ILIMITADOS
                      required: false
                    type:
                      type: string
                      example: Secundario
                      required: false
          totalDevices:
            type: integer
            example: 0
            required: false
          tv:
            type: string
            example: ''
            required: false
          voice:
            type: object
            properties:
              svas:
                type: string
                example: ''
                required: false
              capacity:
                type: object
                properties:
                  description:
                    type: string
                    example: A todo destino nacional
                    required: false
                  unity:
                    type: string
                    example: MIN
                    required: false
                  value:
                    type: string
                    example: Ilimitados
                    required: false
              secundary:
                type: array
                items:
                  type: object
                  properties:
                    count:
                      type: string
                      example: ''
                      required: false
                    desc:
                      type: string
                      example: Minutos ilimitados a todo destino nacional
                      required: false
                    description:
                      type: string
                      example: Minutos ilimitados a todo destino nacional
                      required: false
                    icon:
                      type: string
                      example: ''
                      required: false
                    name:
                      type: string
                      example: VOZ ILIMITADA
                      required: false
                    type:
                      type: string
                      example: Secundario
                      required: false
          available:
            type: boolean
            example: false
            required: false
          contracted:
            type: boolean
            example: false
            required: false
          description:
            type: array
            items:
              type: string
          executionPlan:
            type: array
            items:
              type: object
              properties:
                features:
                  type: array
                  items:
                    type: object
                    properties:
                      description:
                        type: string
                        example: 20% de descuento en el valor de tu plan Ilimigigas
                        required: false
                      differential:
                        type: boolean
                        example: false
                        required: false
                      discount:
                        type: boolean
                        example: true
                        required: false
                      outstanding:
                        type: boolean
                        example: false
                        required: false
                      type:
                        type: string
                        example: Plan
                        required: false
                month:
                  type: integer
                  example: 1
                  required: false
                saving:
                  type: integer
                  example: 14580
                  required: false
                savingStr:
                  type: string
                  example: $ 14.580
                  required: false
                state:
                  type: string
                  example: ''
                  required: false
                value:
                  type: integer
                  example: 58320
                  required: false
                valueStr:
                  type: string
                  example: $ 58.320
                  required: false
          id:
            type: string
            example: '6707'
            required: false
          idsPackaging:
            type: string
            example: ''
            required: false
          installationCharges:
            type: string
            example: ''
            required: false
          isPacking:
            type: boolean
            example: false
            required: false
          isZoned:
            type: boolean
            example: false
            required: false
          name:
            type: string
            example: Ilimigigas
            required: false
          nameTechnical:
            type: string
            example: MOVIL MIXTO ILIMIGIGAS 11
            required: false
          outstanding:
            type: boolean
            example: false
            required: false
          price:
            type: object
            properties:
              anticipatedPayment:
                type: boolean
                example: false
                required: false
              iva:
                type: integer
                example: 0
                required: false
              value:
                type: integer
                example: 72900
                required: false
              valueStr:
                type: string
                example: $ 72.900
                required: false
              valueWithoutIva:
                type: integer
                example: 72900
                required: false
              valueWithoutIvaStr:
                type: string
                example: $ 72.900
                required: false
              validity:
                type: string
                example: Cargo fijo mensual
                required: false
          retencion:
            type: boolean
            example: false
            required: false
          saving:
            type: integer
            example: 174960
            required: false
          savingStr:
            type: string
            example: $ 174,960
            required: false
          stratum:
            type: string
            example: '3'
            required: false
          subType:
            type: string
            example: Internet + Minutos + SMS
            required: false
          svasFeatured:
            type: string
            example: ''
            required: false
          svasIncluded:
            type: string
            example: ''
            required: false
          technology:
            type: string
            example: LTE
            required: false
          type:
            type: string
            example: POSPAGO
            required: false
          value:
            type: integer
            example: 72900
            required: false
          valueStr:
            type: string
            example: $ 72.900
            required: false
          zoned:
            type: string
            example: ''
            required: false
      retakeProcess:
        type: object
        properties:
          isAvailable:
            type: string
            example: ''
            required: false
          reasonState:
            type: string
            example: Actualización de la orden
            required: false
          state:
            type: string
            example: ENTREGA EN PROCESO
            required: false
          step:
            type: string
            example: Cambio de plan
            required: false
      svas:
        type: array
        items:
          type: object
          properties:
            promotions:
              type: array
              items:
                type: object
                properties:
                  activationDate:
                    type: string
                    example: ''
                    required: false
                  currentMonth:
                    type: string
                    example: ''
                    required: false
                  inactivationDate:
                    type: string
                    example: ''
                    required: false
                  timeLeft:
                    type: string
                    example: ''
                    required: false
                  benefit:
                    type: string
                    example: 100%
                    required: false
                  conditioned:
                    type: boolean
                    example: false
                    required: false
                  description:
                    type: string
                    example: >-
                      100% de descuento en el valor de tu SVA UNIVERSAL + los
                      meses1, 2
                    required: false
                  descriptionShort:
                    type: string
                    example: 100% de Descuento
                    required: false
                  differential:
                    type: boolean
                    example: false
                    required: false
                  discounts:
                    type: array
                    items:
                      type: object
                      properties:
                        benefit:
                          type: string
                          example: 100%
                          required: false
                        description:
                          type: string
                          example: 100% de descuento
                          required: false
                        validity:
                          type: string
                          example: 1, 2 meses
                          required: false
                  id:
                    type: string
                    example: 66476720d70839230047f1f8
                    required: false
                  isZoned:
                    type: string
                    example: ''
                    required: false
                  mandatoryPlans:
                    type: string
                    example: ''
                    required: false
                  name:
                    type: string
                    example: >-
                      100% de descuento en el valor de tu SVA UNIVERSAL + los
                      meses 1, 2
                    required: false
                  outstanding:
                    type: boolean
                    example: false
                    required: false
                  quantity:
                    type: string
                    example: ''
                    required: false
                  stratums:
                    type: string
                    example: ''
                    required: false
                  type:
                    type: string
                    example: Descuento
                    required: false
                  validity:
                    type: string
                    example: 1, 2 meses
                    required: false
                  zoned:
                    type: object
                    properties:
                      localities:
                        type: string
                        example: ''
                        required: false
                      isZoned:
                        type: string
                        example: ''
                        required: false
            saleOrder:
              type: string
              example: ''
              required: false
            subSvas:
              type: string
              example: ''
              required: false
            available:
              type: boolean
              example: false
              required: false
            description:
              type: string
              example: >-
                Universal + es una plataforma de streaming por suscripción, a la
                que tendrás acceso a 5 canales en vivo Universal Premiere (...)
                contenido on demand pensado para cada miembro de la familia.
              required: false
            characteristics:
              type: array
              items:
                type: object
                properties:
                  characteristic:
                    type: string
                    example: >-
                      Accede al paquete de canales premium On Demand de
                      Universal
                    required: false
                  icon:
                    type: string
                    example: ''
                    required: false
            conflicting:
              type: array
              items:
                type: string
            contracted:
              type: boolean
              example: false
              required: false
            executionPlan:
              type: array
              items:
                type: object
                properties:
                  features:
                    type: array
                    items:
                      type: object
                      properties:
                        description:
                          type: string
                          example: >-
                            100% de descuento en el valor de tu SVA UNIVERSAL +
                            los meses 1, 2 (1 de 2)
                          required: false
                        differential:
                          type: boolean
                          example: false
                          required: false
                        discount:
                          type: boolean
                          example: true
                          required: false
                        outstanding:
                          type: boolean
                          example: false
                          required: false
                        type:
                          type: string
                          example: OTT
                          required: false
                  month:
                    type: integer
                    example: 1
                    required: false
                  saving:
                    type: integer | string
                    example: 24899
                    required: false
                  savingStr:
                    type: string
                    example: $ 24.899
                    required: false
                  state:
                    type: string
                    example: ''
                    required: false
                  value:
                    type: integer
                    example: 0
                    required: false
                  valueStr:
                    type: string
                    example: $ 0
                    required: false
            executionPlanDifferential:
              type: string
              example: ''
              required: false
            icon:
              type: string
              example: >-
                https://strmietb.blob.core.windows.net/imagenes/flujocomercial/UNIVERSAL/img-logo-universal.svg
              required: false
            id:
              type: string
              example: '6442'
              required: false
            idsOld:
              type: string
              example: ''
              required: false
            mandatory:
              type: string
              example: ''
              required: false
            name:
              type: string
              example: UNIVERSAL +
              required: false
            price:
              type: object
              properties:
                anticipatedPayment:
                  type: boolean
                  example: false
                  required: false
                iva:
                  type: integer
                  example: 0
                  required: false
                value:
                  type: integer
                  example: 24899
                  required: false
                valueStr:
                  type: string
                  example: $ 24.899
                  required: false
                valueWithoutIva:
                  type: integer
                  example: 24899
                  required: false
                valueWithoutIvaStr:
                  type: string
                  example: $ 24.899
                  required: false
                validity:
                  type: string
                  example: Cargo fijo mensual
                  required: false
            quantity:
              type: object
              properties:
                available:
                  type: integer
                  example: 0
                  required: false
                contracted:
                  type: integer
                  example: 0
                  required: false
            saving:
              type: integer
              example: 49798
              required: false
            serviceType:
              type: string
              example: INTERNET
              required: false
            value:
              type: integer
              example: 24899
              required: false
            visibility:
              type: object
              properties:
                action:
                  type: string
                  example: Nin
                  required: false
                conditioned:
                  type: boolean
                  example: false
                  required: false
                plans:
                  type: string
                  example: ''
                  required: false
