#%RAML 1.0 DataType
properties:
  WSResponseConceptosFactura:
    type: object
    properties:
      response_code:
        type: object
        properties:
          code: string
          description: string
      conceptos_factura:
        type: object
        properties:
          detail:
            type: array
            items:
              properties:
                cuenta_facturacion: string
                monto_detalle: string
                numero_factura: string
                concepto_factura: string
                fecha_ini: string
                fecha_fin: string

example: !include ../examples/responses/post-billing-conceptosFactura.json