#%RAML 1.0 DataType
properties:
  ActualizarDatosCuentaFacturacion:
    type: object
    properties:
      cuentaFactuarcion:
        type: string 
        example: "15052904684"
      correo: 
        type: string 
        example: "nicolpineda1712@gmail.com"
      direccion: 
        type: string 
        example: "CL 83 BIS 23 47 AP 102"
      tipoEnvio:
        type: string 
        example: "Electronica"
      usuario: 
        type: string 
        example: "Tibco"

example: !include ../../examples/request/ActualizarDatosCuentaFacturacion.json