#%RAML 1.0 DataType
properties:
  Header:
    type: !include SubDatatypes/Header.raml
  Body:
    type: object
    properties:
      Set_BillingAccount:
        type: object
        properties:
          WSRequestHeader:
            type: !include SubDatatypes/WSRequestHeader.raml
          WSRequestBody:
            type: !include SubDatatypes/WSRequestBody.raml

example:
  !include ../../examples/request/BillingAccountCycle.raml