#%RAML 1.0 DataType
displayName: createNewTask
properties:
  accion:
    type: string
    description: Indicates the action that the task will be performing 
    required: true
    minLength: 1
  nombreTask:
    type: string
    description: Indicates the name of the task
    required: true
    minLength: 1
  resumenTask:
    type: string
    description: 
    required: true
    minLength: 1
  notasTask:
    type: string
    description: 
    required: true
    minLength: 1
  idCasoSalesforce:
    type: string
    description: 
    required: true
    minLength: 1
  idTarea:
    type: string
    description: 
    required: true
    minLength: 1
  grupoAsg:
    type: string
    description: 
    required: true
    minLength: 1
example: !include ../../examples/request/createNewTaskRequest.raml