#%RAML 1.0 DataType
type: object
displayName: createEnterpriseRequest
properties:
    accion:
      type: string
      description: 
      required: false
      minLength: 1
    idSalesforce:
      type: string
      description: 
      required: false
      minLength: 1
    idCtaCliente:
      type: string
      description: 
      required: false
      minLength: 1
    nombreCliente:
      type: string
      description: 
      required: false
      minLength: 1
    apellidosCliente:
      type: string
      description: 
      required: false
      minLength: 1
    telefonoCliente:
      type: string
      description: 
      required: false
      minLength: 1
    emailCliente:
      type: string
      description: 
      required: false
    tipoIdentificacion:
      type: string
      description: 
      required: false
      minLength: 1
    numeroIden:
      type: string
      description: 
      required: false
      minLength: 1
    ubicacion:
      type: string
      description: 
      required: false
      minLength: 1
    codPais:
      type: string
      description: 
      required: false
      minLength: 1
    servicio:
      type: string
      description: 
      required: false
      minLength: 1
    servicioAfectado:
      type: string
      description: 
      required: false
      minLength: 1
    nota:
      type: string
      description: 
      required: false
      minLength: 1
    resumen:
      type: string
      description: 
      required: false
      minLength: 1
    tipoOrden:
      type: string
      description: 
      required: false
      minLength: 1
    fuenteReportada:
      type: string
      description: 
      required: false
      minLength: 1
    nivel1:
      type: string
      description: 
      required: false
      minLength: 1
    nivel2:
      type: string
      description: 
      required: false
    nivel3:
      type: string
      description: 
      required: false
    serial:
      type: string
      description: 
      required: false
    grupoGestor:
      type: string
      description: 
      required: false
      minLength: 1
    grupoAsg:
      type: string
      description: 
      required: false
      minLength: 1
    codMunCliente:
      type: string
      description: 
      required: false
      minLength: 1
    codEdoCliente:
      type: string
      description: 
      required: false
      minLength: 1
    nroCaso:
      type: string
      description: 
      required: false
      minLength: 1
example: !include ../../examples/request/createEnterpriseRequestExample.raml