#%RAML 1.0 DataType
properties:
  CreacionAgendaRemedy: 
    type: object
    properties:
      creacionObjeto:
        type: object
        required: false
        properties: 
          ParametrosCreacion: 
            type: object
            required: false
            properties:
              ParametroCreacion:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion2:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion3:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion4:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion5:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion6:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion7:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion8:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion9:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion10:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion11:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion12:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion13:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion14:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion15:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion16:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion17:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion18:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion19:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion20:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion21:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion22:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion23:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion24:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion25:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion26:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion27:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion28:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion29:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion30:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion31:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion32:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion33:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion34:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion35:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion36:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion37:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion38:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion39:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion40:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion41:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion42:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion43:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion44:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion45:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion46:
                type: !include SubDatatypes/creationParamType.raml
                required: false
              ParametroCreacion47:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion48:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion49:
                type: !include SubDatatypes/creationParamType.raml
                required: false 
              ParametroCreacion50:
                type: !include SubDatatypes/creationParamType.raml
                required: false