#%RAML 1.0 DataType
properties:
  IncidenceId: 
    type: string | nil
    required: false
    example: "INC000004910282"
  OrderId:
    type: string | nil
    required: false
    example: "1379314971111"
  EstadoOT?:
    type: string
    example: "In Progress"
  Comentarios?:
    type: string
    example: "success"