#%RAML 1.0 DataType
properties:
  Id:
    type: string
    maxLength: 30
    pattern: ^[a-zA-Z0-9]*$
    required: false
    example: "003RT00000JkB0kYAF"
  TipoDocumento:
    type: string
    enum: ["CC","CE","TI"]
    required: true
    example: "CC"
  NumeroDocumento:
    type: string
    maxLength: 30
    pattern: ^[0-9]*$
    required: true
    example: "12334534536"
  Nombres:
    type: string
    required: false
    example: "Andrea del Pilar"
  PrimerApellido:
    type: string    
    required: false
    example: "Villanueva"
  SegundoApellido:
    type: string    
    required: false
    example: "De Angel"
  Celular:
    type: string
    pattern: ^3[0-9]{9}$
    required: false
    example: "3015808080"
  Telefono:
    type: string
    pattern: ^3[0-9]{9}$|^60[0-9]{8}$
    required: false
    example: "6015808080"
  Correo:
    type: string
    pattern: ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$
    required: false
    example: "prueba@etb.com"
  Cargo:
    type: string
    enum: [Vicepresidente, Gerente, Director, Ejecutivo, Analista, Otro]
    required: false
    example: "Otro"
  HabeasData:
    type: string
    enum: ["SUPRIMIR","REVOCATORIA","AUTORIZA"]
    required: false
    example: "AUTORIZA"
  IdCuenta:
    type: string
    maxLength: 30
    pattern: ^[a-zA-Z0-9]*$
    required: true
    example: "0014000000uczFLAAY"
  IntegrationIdCuenta:
    type: string
    maxLength: 30
    pattern: ^[a-zA-Z0-9]*$
    required: false
    example: "591d2086ec96a3693710f3e1"