#%RAML 1.0 DataType
type: object
properties:
    CreateIncidentInput:
      type: object
      properties:
        Create:
          type: object
          properties:
            ACCION:
              type: string
              required: true
              example: "Crear Incidente"
            IN_Resumen:
              type: string
              required: false
              example: "PQR"
            IN_Notas:
              type: string
              required: false
              example: "PQR | Soporte Primer Nivel:"
            IN_Nivel_1_Categoria_Operacional:
              type: string
              required: false
              example: "INTERNET"
            IN_Nivel_2_Categoria_Operacional:
              type: string
              required: false
              example: "FALLA INTERNET"
            IN_Nivel_3_Categoria_Operacional:
              type: string
              required: false
              example: "SIN SERVICIO -F"
            IN_ID_Cuenta_Cliente:
              type: string
              required: false
              example: "MDM-25052"
            IN_Nombres_Cliente:
              type: string
              required: false
              example: "LATALECA"
            IN_Apellidos_Cliente:
              type: string
              required: false
              example: "QATEST TESTING"
            IN_Telefono_Cliente:
              type: string
              required: false
              example: "6011111111"
            IN_E-Mail_Cliente:
              type: string
              required: false
              example: "documentosdigitales@etb.com.co"
            IN_VIP:
              type: string | nil
              enum: [ "Yes", "No" ]
              required: false
              example: "No"
            IN_Ubicacion_Cliente:
              type: string
              required: false
              example: "CL 83 BIS 23 47 AP 202"
            IN_Direccion_Norm_Cliente:
              type: string
              required: false
              example: "CL 83 BIS 23 47 AP 202"
            IN_Direccion_No_Norm_Cliente:
              type: string
              required: false
              example: "CL 83 BIS 23 47 AP 202"
            IN_ID_Siebel:
              type: string
              required: false
              example: "MDM-PQR-8016146"
            IN_Numero_CUN:
              type: string
              required: false
              example: "4347230001254312"
            IN_Nombre_Cuenta_Cliente:
              type: string
              required: false
              example: "LATALECA QATEST TESTING"
            IN_Tipo_Identificacion_Cliente:
              type: string
              required: false
              example: "CC"
            IN_Numero_Identificacion_Cliente:
              type: string
              required: false
              example: "25052"
            IN_Zona_Cliente:
              type: string
              required: false
              example: "FCO34"
            IN_Nombres_Contacto:
              type: string
              required: false
              example: "PRUEBA"
            IN_Apellidos_Contacto:
              type: string
              required: false
              example: "PRUEBA"
            IN_E-Mail_Contacto:
              type: string
              required: false
              example: "documentosdigitales@etb.com.co"
            IN_Telefono_Contacto:
              type: string
              required: false
              example: "6011111111"
            IN_ID_Cuenta_Servicio:
              type: string
              required: false
              example: "CS-9006924"
            IN_ID_Direccion_GIS_Servicio:
              type: string
              required: false
              example: "612802304578782437"
            IN_Ubicacion_Servicio:
              type: string
              required: false
              example: "CL 83 BIS 23 47 AP 202"
            IN_Direccion_Servicio:
              type: string
              required: false
              example: "CL 83 BIS 23 47 AP 202"
            IN_Zona_Servicio:
              type: string
              required: false
              example: "CHICO"
            IN_Latitud_Direccion_Servicio:
              type: string
              required: false
              example: "4.671102955"
            IN_Direccion_No_Norm_Servicio:
              type: string
              required: false
              example: "CL 83 BIS 23 47 AP 202"
            IN_Longitud_Direccion_Servicio:
              type: string
              required: false
              example: "-74.06212576"
            IN_Molecula:
              type: string
              required: false
              example: "FCO34"
            IN_ID_de_Servicio:
              type: string
              required: false
              example: "SR-9156491"
            IN_Codigo_Pais_Cliente:
              type: string
              required: false
              example: "57"
            IN_Codigo_Edo_Prov_Cliente:
              type: string
              required: false
              example: "11"
            IN_Codigo_Cd_Mun_Cliente:
              type: string
              required: false
              example: "11001"
            IN_Codigo_Pais_Servicio:
              type: string
              required: false
              example: "57"
            IN_Codigo_Edo_Prov_Servicio:
              type: string
              required: false
              example: "11"
            IN_Codigo_Cd_Mun_Servicio:
              type: string
              required: false
              example: "11001"
            IN_FechaPresentacion_Inc:
              type: string
              required: false
              example: "2023-02-28T07:38:43.1359206-05:00"
            IN_Fuente_Reportada:
              type: string | nil
              required: false
              example: "Otro"
            IN_Tipo_de_Incidencia:
              type: string | nil
              required: false
              example: "Petición de serv. por el usuario"
            IN_Impacto:
              type: string | nil
              enum: [ "1-Extenso/Generalizado","2-Significativo/Amplio", "3-Moderado/Limitado", "4-Menor/Localizado" ]
              required: false
              example: "4-Menor/Localizado"
            IN_Urgencia:
              type: string | nil
              required: false
              example: "4-Baja"
            IN_LTE_NumeroMovil:
              type: string
              required: false
              example: "6016718851"
            IN_Codigo_Actividad:
              type: string
              required: false
              example: "MDM-PQR-ACT-3087735"
            IN_Telefono_Activo:
              type: string
              required: false
              example: "6016718851"
            IN_Tecnologia:
              type: string | nil
              enum: ["CU" , "FO", "LTE", "FTTC"]
              required: false
              example: "FO"
            IN_UEN:
              type: string
              required: false
              example: "Hogares y MiPymes"
            IN_Segmento_UEN:
              type: string
              required: false
              example: "Hogares"
            IN_Fuente_MDM:
              type: string
              enum: ["No" , "Si"]
              required: false
              example: "Si"
            IN_FlagFallaJoven:
              type: string | nil
              required: false
              example: "Si"
            IN_Segmento:
              type: string
              required: false
              example: "Hogares"
            IN_CategoriaCliente:
              type: string
              required: false
              example: "PLATA"
            IN_TES:
              type: number
              required: false
              example: 0
            IN_Falla_Masiva_PQR:
              type: string
              required: false
              example: "0"
            IN_Prioridad_Falla_Masiva:
              type: string
              required: false
              example: "Crítica"
            IN_SubEstado_PQR:
              type: string
              required: false
              example: "0"
            IN_Recurrente:
              type: string
              required: false
              example: "0"
            IN_Propietario_Red:
              type: string
              required: false
              example: "string"
            IN_Vias_Acceso:
              type: string
              required: false
              example: "string"