#%RAML 1.0 DataType
type: object
properties:
    status:
      description:
      example: "Proposed"
      type: string
    origen:
      description:
      example: "Portafolio"
      type: string
    description:
      description:
      example: "Nota Salesforce"
      type: string
    detailDescription:
      description:
      example: "Victor Bracho. Se realiza llamda al Sr Delford Brackman,cel 3153665856, pero no contesta las llamadas y no fue posible dejarle nota de voz"
      type: string
    submitDate:
      description:
      example: "2022-01-04T17:19:40-05:00"
      type: string
    incidentNumber:
      description:
      example: "INC000006234698"
      type: string
    workLogType:
      description: action
      example: "Seguimiento"
      type: string
    viewAccess:
      description: action
      example: "Public"
      type: string
    secureWorkLog:
      description: action
      example: "No"
      type: string
  
  