#%RAML 1.0 DataType
properties:
  statusReasonTOA:
    description: 
    example: ""
    type: string
  resolution:
    description: Resolution
    example: "DEPURACION AGENDA"
    type: string
  resolutionCode:
    description: Resolution code
    example: "CR3377- - "
    type: string
  status:
    description: status
    example: "COMPLETED"
    type: string
  groupID:
    description: group id
    example: ""
    type: string
  action:
    description: action
    example: "CLOSE"
    type: string

