#%RAML 1.0 DataType
type: object
properties:
    UpdateScheduleRequest: 
      type: object
      properties: 
        Input: 
          type: object
          properties: 
            UpdateScheduleInput: 
              type: object
              properties: 
                WSRequestHeader2: 
                  type: object
                  properties: 
                    System: 
                      type: object
                      properties: 
                        name: 
                          type: string
                          required: true
                          minLength: 1
                        correlationID:
                          type: string
                          required: true
                          minLength: 1
                        processingServer:
                          type: string
                          required: true
                          minLength: 1
                Payload: 
                  type: object
                  properties:
                    Order: 
                      type: object
                      properties: 
                        id: 
                          type: string
                          required: true
                          minLength: 1
                        actionType:
                          type: string
                          required: false
                    Appointment: 
                      type: object
                      properties: 
                        date: 
                          type: date-only
                          required: true
                        timeSlot:
                          type: string
                          required: true
                          minLength: 1
                        duration:
                          type: number
                          required: true
                    Customer:
                      type: object
                      required: false
                      properties:
                        uen:
                          type: string
                          required: false
example: !include ../../examples/request/updateSchedule.json