#%RAML 1.0 DataType
type: object
properties:
  status:
    type: integer
    required: false
  code:
    type: string
    required: false
  message:
    type: object
    properties:
      message:
        type: string
        required: false
  inventoryConfiguration:
    type: object
    properties:

      serviceAccount:
        type: array
        items:
          type: object
          properties:

            id:
              type: string
              example: "CS-9012096"

            place:
              type: array
              items:
                type: object
                properties:

                  resourceAccess:
                    type: array
                    items:
                      type: object
                      properties:

                        id:
                          type: string
                          example: "180097"

                        technology:
                          type: string
                          example: "FIBER"

                        resourceRoute:
                          type: object
                          properties:
                            resource:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                                  name:
                                    type: string
                                  port?:
                                    type: string
                                  vendor?:
                                    type: string
                                  location?:
                                    type: string
                                  characteristic?:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        name: string
                                        value: string

                        characteristic:
                          type: array
                          items:
                            type: object
                            properties:
                              name: string
                              value: string

                  service:
                    type: array
                    items:
                      type: object
                      properties:

                        id:
                          type: string
                          example: "SR-9247201"

                        rootServiceId?:
                          type: string

                        parentServiceId?:
                          type: string

                        name:
                          type: string

                        state:
                          type: string

                        characteristic:
                          type: array
                          items:
                            type: object
                            properties:
                              name: string
                              value: string
                              action?:
                                type: string

                  policy:
                    type: array
                    items:
                      type: object
                      properties:

                        resourcePolicy:
                          type: array
                          items:
                            type: object
                            properties:
                              resourceType:
                                type: string
                              brand:
                                type: string
                              model?:
                                type: string
                              minQuantity:
                                type: string
                              characteristic?:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name: string
                                    value: string