#%RAML 1.0
title: appointment-admin-web-xapi-services
version: v1
baseUri:  https://appointment-admin-web-xapi-services-{env}.us-e2.cloudhub.io/{version}
description: API designed for appointment management, enabling the handling of various actions related to scheduling and agenda management.
protocols:
  - HTTPS

traits:
  tibcoHeaders: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml

mediaType: 
  - application/json
  - application/xml

securitySchemes:
  etb_oauth_2_0: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

/appointment:
  post:
      is:
            - tibcoHeaders
      securedBy: [etb_oauth_2_0]
      displayName: createAppointment
      description: |
        Create an Appointment entity.
      queryParameters:
        ORIGIN:
          type: string
          example: "WHATSAPP"
          description: "Parameter that allows the origin of the request to be identified"
      body:
        application/json:
          type: !include /datatypes/request/create-appointment.raml
          example: !include /examples/request/create-appointment.json
          description: The Appointment to be created
      responses:
        200:
          description: Created
          body:
            application/json:
              type: !include /datatypes/response/create-appointment.raml
        400:
          description: Bad Request
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-400.json
        401:
          description: Unauthorized
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-401.json
        404:
          description: Not Found
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-404.json
        500:
          description: Internal Server Error
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-500.json
  /{id}:
    is:
          - tibcoHeaders
    securedBy: [etb_oauth_2_0]
    uriParameters:
      id:
        type: string
        required: true
        description: Identifier of the Appointment
    get:
      displayName: retrieveAppointment
      description: |
        Retrieves an Appointment entity by its ID.
      responses:
        200:
          description: Success
          body:
            application/json:
              type: !include /datatypes/response/appointment.raml
              example: !include /examples/response/get-appointment.json
        400:
          description: Bad Request
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        401:
          description: Unauthorized
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        403:
          description: Forbidden
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        404:
          description: Not Found
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        405:
          description: Method Not Allowed
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        409:
          description: Conflict
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        500:
          description: Internal Server Error
          body:
            application/json:
              type: !include /datatypes/response/error.raml
    patch:
      displayName: patchAppointment
      description: |
        Updates partially an Appointment entity.
      body:
        application/json:
          type: !include /datatypes/request/update-appointment.raml
          example: !include /examples/request/update-appointment.json
          description: The Appointment to be updated
      responses:
        200:
          description: Updated
          body:
            application/json:
              type: !include /datatypes/response/appointment.raml
        400:
          description: Bad Request
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        401:
          description: Unauthorized
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        403:
          description: Forbidden
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        404:
          description: Not Found
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        405:
          description: Method Not Allowed
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        409:
          description: Conflict
          body:
            application/json:
              type: !include /datatypes/response/error.raml
        500:
          description: Internal Server Error
          body:
            application/json:
              type: !include /datatypes/response/error.raml
    

/searchTimeSlot:
  is:
          - tibcoHeaders
  securedBy: [etb_oauth_2_0]
  get:
    displayName: List or find SearchTimeSlot objects
    description: This operation lists or finds SearchTimeSlot entities
    queryParameters:
      numDays:
        type: integer
        required: false
        example: 3
      categories:
        type: string
        required: false
        example: "MPPFTTH_Plata,MPPFTTH_Oro"
        description: Lista de categorías separadas por coma
      area:
        type: string
        required: false
        example: CHICO
      date:
        type: string
        required: false
        example: 2025-05-26
    responses:
      200:
        description: Success
        body:
          application/json:
            type: !include /datatypes/response/get-searchTimeSlot.raml
            example: !include /examples/response/get-searchTimeSlot.json
      400:
        description: Bad Request
        body:
          application/json:
            type: !include /datatypes/response/error.raml
      401:
        description: Unauthorized
        body:
          application/json:
            type: !include /datatypes/response/error.raml
      403:
        description: Forbidden
        body:
          application/json:
            type: !include /datatypes/response/error.raml
      404:
        description: Not Found
        body:
          application/json:
            type: !include /datatypes/response/error.raml
      405:
        description: Method Not Allowed
        body:
          application/json:
            type: !include /datatypes/response/error.raml
      409:
        description: Conflict
        body:
          application/json:
            type: !include /datatypes/response/error.raml
      500:
        description: Internal Server Error
        body:
          application/json:
            type: !include /datatypes/response/error.raml


