cun:
  soap:
    credentials:
      mdm:
        user: "![j5VJeP+U5wRQRoej4v+Trw==]"
        pass: "![/7UoiNbt6NcqBRVwq0fxRQ==]"
      mir:
        user: "![mir]"
        pass: "![mir]"
      peticionario:
        user: "![peticionario]"
        pass: "![peticionario2013]"
      retenciones:
        user: "![retenciones]"
        pass: "![retenciones]"
      simra:
        user: "![simra]"
        pass: "![simra2013]"
      siebel:
        user: "![Siebel]"
        pass: "![Siebel]"
      gpnba:
        user: "![gpnba]"
        pass: "![gpnba2013]"
      openflex:
        user: "![open]"
        pass: "![open2013]"
      servicemanager:
        user: "![servicemanager]"
        pass: "![manager2013]"
      portales:
        user: "![portales]"
        pass: "![portales2013]"
      saaw:
        user: "![saaw]"
        pass: "![saaw2013]"
      siebel_nplay:
        user: "![SIEBELNPLAY]"
        pass: "![T3l3c0m2014]"
      infocable:
        user: "![INFOCABLE]"
        pass: "![INFOCABLE_2014]"
      salesforce:
        user: "![SALESFORCE]"
        pass: "![s4l4c0m2014]"
      contactcenter_lte:
        user: "![retencion_lte]"
        pass: "![retencion_lte]"
      financiador:
        user: "![FINDEUDA]"
        pass: "![findeuda2014]"
      kioskos:
        user: "![uKioskos]"
        pass: "![uKioskos]"
      gestiondereclamos:
        user: "![uReclamos]"
        pass: "![pReclamos]"