https:
  host: "0.0.0.0"
  port: "443"

app.name: "resource-xapi-services-v2"

autodiscovery: "20867939"

resource-papi-v2:
  protocol: "HTTP"
  host: "mule-worker-internal-resource-papi-services-v2-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/v2"
  resources:
    availability:
      path: "/availability"
      consultation:
        path: "/availability/consultation"
    configurations:
      path: "/configurations"
    eligibility:
      path: "/eligibility"
    reservations:
      path: "/reservations"
  security:
    client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"

configurationTimeout:
  resource-xapi-v2-listener: "62000"
  resource-papi-v2:
    responseTimeout: "30000"
    connectionIdleTimeout: "60000"

anypoint.platform.client_id: ""
anypoint.platform.client_secret: ""
anypoint.platform.config.analytics.agent.enabled: "false"
