#%RAML 1.0 DataType
type: object
displayName: ProductOffering
description: Simplified TMF620 v2.0.1 ProductOffering response
properties:
  id:
    type: string
    required: true
    example: "5c0012184379b104c4469539"
  name:
    type: string
    required: true
    example: "DECODIFICADOR 2"
  description:
    type: string
    required: true
    example: "DECODIFICADOR 2"
  lifecycleStatus:
    type: string
    required: true
    enum: [Active, Inactive, Obsolete]
    example: "Active"
  productSpecification:
    type: object
    required: true
    properties:
      id: string
      name: string
      tipoProducto: string
      tipoServicio: string
      subtipoServicio: string
      subtipoProducto?: string
      "@type": string
      href: string
  productOfferingPrice:
    type: array
    required: true
    items: object
    example: []
  validFor:
    type: object
    required: true
    properties:
      startDateTime?: datetime
      endDateTime?: datetime
  isBundle:
    type: boolean
    required: true
    example: false
  bundle:
    type: array
    required: true
    items: object
    example: []
  place?: array
  relatedParty?: array
  serviceCandidate?: array
  "@type":
    type: string
    required: true
    example: "ProductOffering"
  "@baseType":
    type: string
    required: true
    example: "Entity"
  href:
    type: string
    required: true
    example: "https://api.miempresa.com/tmf-api/v2/productOffering/5c0012184379b104c4469539"
  category?: array
  attachment?: array
  channel?: array
  marketSegment?: array
  productOfferingTerm?: array
  resourceCandidate?: array
  serviceLevelAgreement?: array
  agreement?: array
  characteristic:
    type: array
    required: false
    items:
      type: object
      properties:
        name: string
        value: string
