https:
  host: "0.0.0.0"
  port: "8082"
  
configurationTimeout:
  salesforce-sapi: "62000"
  operations-papi: "310000"
  billing-papi: "62000"
  sap-sapi: "62000"

billing-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-billing-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath:
    version: "/billing/v1"
  path: "/billing_accounts"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

operation-papi:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/operations/v1"
  path-processViabilityResponse: "/viability"
  path-processProvisioning: "/provisioning"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  source: "gestor-xapi-services"
  
salesforce-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-salesforce-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/salesforce/v1"
  path-updateViability: "/viability"
  path-updateProvisioning: "/provisioning"
  path-syncProduct: "/syncProduct"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
sap-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sap-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/sap/v1"
  path:
    queryMaterials: "/queryMaterials"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "7417c6490e8943FDBCDB907d30e9f2f7"
  client_id: "b8665f3c588a4a709576760a1cc5a582"
  
autodiscovery: "18058277"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"