#%RAML 1.0 DataType
type: object
properties:
  RequestReenvioNIP:
    type: object
    required: true
    properties:
      Header:
        type: object
        required: true
        properties:
          IdIntegracion:
            type: string
            required: true
            example: "MDM-MOV-3114267"
          System:
            type: string
            required: true
            example: "MDM-MOV"
      MensajeABD:
        type: object
        required: true
        properties:
          CabeceraMensaje:
            type: object
            required: true
            properties:
              IdentificadorProceso:
                type: string
                required: true
                example: "00007202405060000644"
              IdentificadorMensaje:
                type: string
                required: true
                example: "00007202405060000963"
              FechaCreacionMsg:
                type: string
                required: true
                example: "20240612090643"
              Operacion:
                type: string
                required: true
                example: "00"
              Emisor:
                type: string
                required: true
                example: "00007"
              TipoMsg:
                type: string
                required: true
                example: "0003"
              Observaciones:
                type: string
                required: true
                example: ""
          CuerpoMensaje:
            type: object
            required: true
            properties:
              SolicitudReenvioNIP:
                type: object
                required: true
                properties:
                  ListaNumeracion:
                    type: object
                    required: true
                    properties:
                      Numeracion:
                        type: array
                        required: true
                        items:
                          type: string
                          example: "3104XXX244"

example: !include ../../examples/request/reenvioNIP.json