#%RAML 1.0 DataType
type: object
properties:
  RequestSolicitudCancelacion:
    type: object
    required: true
    properties:
      Header:
        type: object
        required: true
        properties:
          IdIntegracion:
            type: string
            required: true
            example: "MDM-MOV-328963"
          System:
            type: string
            required: true
            example: "MDM-MOV"
      MensajeABD:
        type: object
        required: true
        properties:
          CabeceraMensaje:
            type: object
            required: true
            properties:
              FechaCreacionMsg:
                type: string
                required: true
                example: "20240426030407"
              TipoMsg:
                type: string
                required: true
                example: "2001"
              Emisor:
                type: string
                required: true
                example: "00007"
              Observaciones:
                type: string
                required: true
                example: ""
          CuerpoMensaje:
            type: object
            required: true
            properties:
              SolicitudCancelacion:
                type: object
                required: true
                properties:
                  Numero:
                    type: array
                    required: true
                    items:
                      type: string
                      example: "321478XXX87"
                  FechaVentanaCancelacion:
                    type: string
                    required: true
                    example: "20240426030407"