#%RAML 1.0 DataType
properties:
  RequestSolicitudNIP:
    type: object
    properties:
      Header:
        type: object
        properties:
          IdIntegracion: string
          System: string
      MensajeABD:
        type: object
        properties:
          CabeceraMensaje:
            type: object
            properties:
              IdentificadorProceso: string
              IdentificadorMensaje: string
              FechaCreacion: string
              Operacion: string
              TipoMensaje: string
              CodigoOperador: string
              Observaciones?: string | nil
          CuerpoMensaje:
            type: object
            properties:
              SolicitudNIP:
                type: object
                properties:
                  OperadorDonante: string
                  NumeroRepresentante?: string | nil
                  ListaNumeracion:
                    type: object
                    properties:
                      Numeracion: string[]