http:
  host: "0.0.0.0"
  private:
    port: "8091"
  path: "/lisim/*"
  
autodiscovery: "18157110"

lisim:
  protocol: "HTTP"
  host: "10.60.28.20"
  port: "8080"
  pathValidarIdentificacion: "/wsValida.asmx"
  usuario-rest: "1000000001"
  contrasena-rest: "3tb_0TP2206092022"
  usuario: ""
  contrasena: ""
  port-v2: ""
  path-authentication: "/Api/Authentication"
  path-identity-validation: "/Api/IdentityValidation"
  path-otp-resend: "/Api/OTP/Resend"
  path-otp-validate: "/Api/OTP/Validate"
  path-score: "/Api/Score"
  port_soap: "8080"
  base_path: "/wsValida.asmx"
  sistemaOrigen: "SIEBEL"

temDataServices:
  protocol: "HTTP"
  host: "10.60.28.20"
  port: "8080"
  path: "/wsValida.asmx"
  credentials:
    user: "EtbProduccion"
    password: "2o3tbPr0dI7*"
  sistemaOrigen: "SIEBEL"
  headers:
    content-type: "text/xml; charset=utf-8"
    SOAPAction: "http://tempuri.org/IValidaService/ValidarCuestionario"
  
EtbPymes:
  protocol: "HTTP"
  host: "10.60.28.20"
  port: "6632"
  timeout: "60000"
  path: "/wsEtbPymes.asmx?wsdl"  
  autentication:
    user: "EtbPymes2019"
    password: "*3Tb_Pyme$"
  validaIdentidadNeglisim:
    soap-action: "http://tempuri.org/ValidarIdentificacion"
  consultaCupoNegLISIM:
    soap-action: "http://tempuri.org/CalculoCupo"  

etb-mdm-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-etb-mdm-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mdm"
  registerLog:
    path: "/v1/registerLog"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
scoring:
  useMock: "false"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  
configurationTimeout:
  lisim: "60000"
  etb-mdm-sapi: "60000"
  validateQuestionnaire: "60000"