#%RAML 1.0 Library
uses: 
  order: productOrder-library.raml
types: 
  response:
    type: object
    properties:
      resultados:
        type: order.productOrder[]
      resultado: 
        type: string
      fecha:
        type: string
      descripcion:
        type: string
