#%RAML 1.0 Library
uses: 
  producto: productRecursive-library.raml
types: 
  productOrder:
    type: object
    properties:
      productOrder:
        type: object
        properties:
          correlationId:
            type: string
            minLength: 1
            required: true
          agrupador:
            description: Identificador de la petición
            type: string
            minLength: 1
            required: true
          subAgrupador:
            description: Identificador del subAgrupador, ejemplo Número de la cotización
            type: string | nil
            required: false
          canal:
            description: Canal que hizo la petición
            type: string
            minLength: 1
            required: true
          ordenOM:
            type: string
            required: false
          tipoSolicitud:
            type: string
            minLength: 1
            required: true
          subTipoSolicitud:
            type: string
            required: false
          tipoTramite:
            description: Tipo de gestión en SF
            type: string
            minLength: 1
            required: true
          subTipoTramite:
            description: Tipo de Trámite
            type: string
            required: false
          detalleSubTipoTramite:
            description: En el caso de Colombia compra eficiente sus valores segmento 1, segmento 2 y segmento 3
            type: string
            required: false
          cun:
            description: Código Único Numérico generado por el sistema CUNCENTER
            type: string
            required: false
          fecha:
            description: Fecha creación de la orden en Salesforce en formato YYYY-MM-DD HH24:mm:ss fff
            type: string
            required: false
          usuario:
            description: Usuario funcional de salesforce que realiza la petición
            type: string
            minLength: 1
            required: true
          prioridad:
            type: string
            required: false
          descripcion:
            type: string
            required: false
          comentarios:
            description: Comentarios
            type: array
            required: false
            items:
              properties:
                fecha:
                  description: Formato YYYY-MM-DD HH24:mm:ss fff
                  type: string
                  required: false
                usuario:
                  type: string
                  required: false
                comentario:
                  type: string
                  minLength: 1
                  required: true
          cliente:
            description: Datos del cliente que adquiere los servicios
            type: object
            required: true
            properties:
                tipoDocumento:
                  description: Tipo documento del cliente
                  type: string
                  minLength: 1
                  required: true
                numeroDocumento:
                  description: ID de identificación
                  type: string
                  minLength: 1
                  required: true
                dv:
                  description: Digito de verificación si es NIT o RUT
                  type: string
                  required: false
                nombres:
                  description: Nombres del cliente o empresa
                  type: string
                  minLength: 1
                  required: true
                primerApellido:
                  description: Primer apellido si es persona natural
                  type: string
                  required: false
                segundoApellido:
                  description: Segundo apellido si es persona natural
                  type: string
                  required: false
                uen:
                  description: Mercado
                  type: string
                  minLength: 1
                  required: true
                segmento:
                  type: string
                  minLength: 1
                  required: true
                subSegmento:
                  type: string | nil
                  required: false
                valor:
                  description: Valor del cliente
                  type: string
                  required: false
                telefonoFijo:
                  type: string
                  required: false
                telefonoMovil:
                  type: string
                  required: false
                email:
                  type: string
                  required: false
                esquemaAtencion:
                  type: string
                  required: false
                enfoque:
                  type: string
                  required: false
                idCuenta:
                  description: Business Account
                  type: string
                  required: false
                actividadEconomica:
                  description: Código actividad económica principal
                  type: string
                  required: false
                idDireccion:
                  description: Id de la dirección principal del cliente
                  type: string
                  required: false
                contactos:
                  type: array
                  required: false
                  items:
                    properties:
                      idContacto:
                        description: Id Contacto
                        type: string
                        minLength: 1
                        required: true
                      tipoContacto:
                        description: Tipo contacto
                        type: string
                        minLength: 1
                        required: true
                      tipoDocumento:
                        description: Tipo documento del cliente
                        type: string
                        required: false
                      numeroDocumento:
                        description: ID de identificación
                        type: string
                        required: false
                      nombres:
                        description: Nombres del cliente o empresa
                        type: string
                        minLength: 1
                        required: true
                      primerApellido:
                        description: Primer apellido si es persona natural
                        type: string
                        required: false
                      segundoApellido:
                        description: Segundo apellido si es persona natural
                        type: string
                        required: false
                      telefonoFijo:
                        type: string
                        required: false
                      telefonoMovil:
                        type: string
                        required: false
                      email:
                        type: string
                        minLength: 1
                        required: true
                      idDireccion:
                        description: Id de la dirección del contacto
                        type: string
                        required: false
                      autorizaTD:
                        description: Autorización de tratamiento de datos personales
                        type: string
                        required: false
          direcciones:
            type: array
            required: true
            items:
              properties:
                idDireccion:
                  type: string
                  minLength: 1
                  required: true
                direccionNormalizada:
                  type: string
                  required: false
                direccion:
                  description: Dirección sin normalizar
                  type: string
                  required: false
                tipoDireccion:
                  description: tipo de la dirección
                  type: string
                  minLength: 1
                  required: true
                nombreDireccion:
                  description: Descripción funcional de la dirección
                  type: string
                  required: false
                codigoPais:
                  description: Codigo DANE, valor entregado por la integración con SMW
                  type: string
                  minLength: 1
                  required: true
                codigoDepartamento:
                  description: Codigo DANE, valor entregado por la integración con SMW
                  type: string
                  minLength: 1
                  required: true
                departamento:
                  description: Nombre del departamento
                  type: string
                  minLength: 1
                  required: true
                codigoMunicipio:
                  description: Codigo DANE, valor entregado por la integración con SMW
                  type: string
                  minLength: 1
                  required: true
                municipio:
                  description: Nombre del municipio
                  type: string
                  minLength: 1
                  required: true
                cobertura:
                  description: Datos de la cobertura de la dirección
                  type: object
                  required: false
                  properties:
                    direccionGIS:
                      description: Identificador de la dirección entregado SMW
                      type: string
                      minLength: 1
                      required: true
                    tipoCobertura:
                      type: string
                      minLength: 1
                      required: true
                    codigoLote:
                      type: string
                      required: false
                    localidad:
                      type: string
                      required: false
                    estrato:
                      type: string
                      minLength: 1
                      required: true
                    latitud:
                      type: string
                      minLength: 1
                      required: true
                    longitud:
                      type: string
                      minLength: 1
                      required: true
                    nombreCobertura:
                      type: string
                      minLength: 1
                      required: true
                    proposito:
                      type: string
                      minLength: 1
                      required: true
                    tecnologia:
                      type: string
                      minLength: 1
                      required: true
                    zona:
                      type: string
                      minLength: 1
                      required: true
                    tipoDistancia:
                      type: string
                      required: false
                    tipoDistancia2:
                      type: string
                      required: false
                    distrito:
                      type: string
                      required: false
                    molecula:
                      type: string
                      required: false
                direccionEstandar:
                  type: boolean
                  required: false
          datosAdicionales:
            type: object
            required: false
            properties:
              campana:
                description: Nombre de la campaña relacionada a la oportunidad
                type: string
                required: false
              origenCampana:
                description: Clasificación comercial o regional que identifica la campaña
                type: string
                required: false
              canalExterno:
                description: Empresa aliada que atiende una caanal de venta
                type: string
                required: false
              fechaCierre:
                description: Fecha de cierre de la oportunidad Formato YYYY-MM-DD
                type: string
                required: false
              duracionDias:
                description: Estimación de la duración del contrato en días
                type: integer
                required: false
              duracionMeses:
                description: Estimación de la duración del contrato en meses
                type: integer
                required: false
              lineaNegocioPrincipal:
                description: Valores de datacenter, datos, negocios especiales
                type: string
                required: false
              valorTotalAliado:
                description: Monto estimado de la oportunidad asignado al aliado
                type: integer
                required: false
              valorTotalETB:
                description: Monto estimado de la oportunidad asignado a ETB
                type: integer
                required: false
              oportunidad:
                description: Nombre de la oportunidad
                type: string
                required: false
              codigoOportunidad:
                type: string
                required: false
              targetComercial:
                description: Valor target de la operación comercial
                type: string
                required: false
              ejecutivoExperiencia:
                description: Dato del ejecutivo experiencia.
                type: string
                required: false
              asesorComercial:
                description: Dato del asesor comercial.
                type: string
                required: false
              numeroCaso:
                description: Numero del caso.
                type: string
                required: false
          items:
            type: array
            required: false
            items:
              properties:
                idItem:
                  type: string
                  minLength: 1
                  required: true
                idServicio:
                  type: string
                  required: false
                idServicioSecundario:
                  type: string
                  required: false
                idOrigen:
                  description: Identificador del elemento que asigna el item
                  type: string | nil
                  required: false
                idRaiz:
                  description: Identificador del contenedor de la items
                  type: string | nil
                  required: false
                productos:
                  type: producto.productType
                  required: false
                contactosItem:
                  description: Id del contacto
                  type: array
                  required: false
                idDireccion:
                  description: Id de la dirección
                  type: string
                  required: false
                comentarios:
                  type: object
                  required: false
                  properties:
                    fecha:
                      description: Formato YYYY-MM-DD HH24:mm:ss fff
                      type: string
                      required: false
                    usuario:
                      type: string
                      required: false
                    comentario:
                      type: string
                      minLength: 1
                      required: true
                propiedades:
                  type: array
                  required: false
                  items:
                    properties:
                      valor:
                        type: string
                        minLength: 1
                        required: true
                      codigo:
                        type: string
                        minLength: 1
                        required: true
                      caracteristica:
                        type: string
                        required: false
                nombreCuentaServicio:
                  type: string
                  required: false
                idCuentaServicio:
                  type: string
                  required: false
                cantidad:
                  type: integer
                  required: true
                idCuentaFacturacion:
                  description: Id del arreglo de cuentas de facturación
                  type: string
                  required: false
                idAgenda:
                  description: Id del arreglo de agendas, si el item no requiere agenda puede venir nulo
                  type: string
                  required: false
                activos:
                  type: producto.itemType
                  required: false
                accion:
                  type: string
                  minLength: 1
                  required: true
                tiempoAns:
                  description: Tiempo Ans.
                  type: string
                  required: false
                tipoInstalacion:
                  description: Tipo de Instalacion.
                  type: string
                  required: false
                viabilidadRelacionada:
                  description: Dato acerca de la viabilidad relacionada.
                  type: string
                  required: false
                contrato:
                  type: object
                  required: false
                  properties:
                    numero:
                      type: string
                      minLength: 1
                      required: true
                    fechaInicio:
                      type: string
                      required: false
                    fechaFin:
                      type: string
                      required: false
                    tipoDeContrato:
                      type: string
                      required: false
                    renovacionAutomatica:
                      type: string
                      required: false
                    comentarios:
                      type: string
                      required: false
                aliadoColaborador:
                  type: string
                  required: false
                estado:
                  type: string
                  required: false
                solicitudesRelacionadas:
                  type: producto.itemType[]
                  required: false
                precios?:
                  type: object 
                  required: false
                  properties:
                    precioBaseRecurrente:
                      type: string | nil
                      required: false
                    precioNetoRecurrente:
                      type: string | nil
                      required: false
                    precioNetoRecurrenteTotal:
                      type: string | nil
                      required: false
                    precioBaseNoRecurrente:
                      type: string | nil
                      required: false
                    precioNetoNoRecurrente:
                      type: string | nil
                      required: false
                    precioNetoNoRecurrenteTotal:
                      type: string | nil
                      required: false
                    descuentoRecurrente:
                      type: string | nil
                      required: false
                    descuentoNoRecurrente:
                      type: string | nil
                      required: false
                fechaInicioFacturacion?:
                  type: string | nil
                  required: false
                numerosConexion:
                  type: array
                  description: Relaciona información de los números de conexión o identificadores del servicio de la orden.
                  required: false
                  items:
                    type: object
                    properties:
                      numero:
                        type: string
                        description: Número de conexión o identificador de conexión del servicio.
                        required: true
                      accion:
                        type: string
                        description: "[Add,Change,Disconnect,Existing,Suspend,Resume]"
                        required: false
          agendas:
            type: array
            required: false
            items:
              properties:
                idAgenda:
                  type: string
                  minLength: 1
                  required: true
                fechaAgenda:
                  type: string
                  required: false
                franjaAgenda:
                  type: string
                  required: false
                tipoActuacion:
                  type: string
                  required: false
                habilidadTrabajo:
                  type: string
                  required: false
                duracion:
                  type: string
                  required: false
                codigoInstalador:
                  type: string
                  required: false
                nombreInstalador:
                  type: string
                  required: false
                tipoActuacionII:
                  type: string
                  required: false
          cuentasFacturacion:
            type: array
            required: false
            items:
              properties:
                idCuentaFacturacion:
                  type: string
                  minLength: 1
                  required: true
                nombreCuentaFacturacion:
                  type: string
                  required: false
                cuentaFacturacion:
                  type: string
                  required: false
                cuentaPadreFacturacion:
                  type: string
                  required: false
                frecuencia:
                  type: string
                  required: false
                cicloFacturacion:
                  type: integer
                  required: false
                tipoFactura:
                  type: string
                  required: false
                tipoEntregaFactura:
                  type: string
                  required: false
                idDireccionFacturacion:
                  type: string
                  required: false
                correoElectronico:
                  type: string
                  required: false
                diaFacturacion:
                  type: integer
                  required: false
                convInd:
                  type: integer
                  required: false
                paymentPrd:
                  type: integer
                  required: false
                billiable:
                  type: boolean
                  required: false
                claimMethod:
                  type: string
                  required: false
                fechaInicioFacturacion:
                  type: string
                  required: false
                demo:
                  type: boolean
                  description: "true: cuenta de facturacion para productos demo; false: cuenta de facturacion para productos no demo"
                  required: false
          urlsRecursos:
            type: array
            required: false
            items:
              properties:
                valor:
                  type: string
                  minLength: 1
                  required: true
                codigo:
                  type: string
                  minLength: 1
                  required: true
                caracteristica:
                  type: string
                  required: false
          propiedades:
            type: array
            required: false
            items:
              properties:
                valor:
                  type: string
                  minLength: 1
                  required: true
                codigo:
                  type: string
                  minLength: 1
                  required: true
                caracteristica:
                  type: string
                  required: false