#%RAML 1.0 Library
types:
  productsProvisioningType:
    type: object
    properties:
      catalogo:
        type: string
        required: false
        example: "Catalogo producto"
      clase:
        type: string
        required: false
        example: "Clase producto"
      codigo:
        type: string
        required: true
        minLength: 1
        example: "Codigo producto"
      nombre:
        type: string
        required: true
        minLength: 1
        example: "Nombre producto"
      id:
        type: string
        required: true
        minLength: 1
        example: "Id producto"
      idItem:
        type: string
        required: true
        minLength: 1
        example: "Id Item producto"
      idRaiz:
        type: string
        required: false
        example: "Id Raiz producto"
      codigoAccion:
        type: string
        required: false
        example: "Código acción producto"
      cantidad:
        type: integer
        required: false
        example: 12
      parametros:
        type: array
        required: false
        items:
          properties:
            codigo:
              type: string
              required: true
              minLength: 1
              example: Atttr_numeroIMEI
            nombre:
              type: string
              required: true
              minLength: 1
              example: Número de IMEI
            valor:
              type: string
              required: false
              example: "98513324306"
            codigoAccion:
              type: string
              required: false
              example: Add
      subProductos:
        type: productsProvisioningType[]
        required: false