#%RAML 1.0 Library
uses: 
  responseProvisioning: provisioningResponse-library.raml
types: 
  response:
    type: object
    properties:
      resultados:
        type: responseProvisioning.provisioningResponse[]
      resultado: 
        type: string
      fecha:
        type: string
      descripcion:
        type: string