#%RAML 1.0 Library
uses: 
  responseViability: viabilityResponse-library.raml
types: 
  response:
    type: object
    properties:
      resultados:
        type: responseViability.viabilityResponse[]
      resultado: 
        type: string
      fecha:
        type: string
      descripcion:
        type: string
