http:
  private:
    port: "8091"
  
autodiscovery: "17964595"

cun:
  soap:
    protocol: "http://"
    host: "10.112.2.165"
    wsdlPath: "/ws_cuncenter/EntregaCUN.asmx?wsdl"
    service: "Service1"
    port: "Service1Soap12"
    operations: 
      asignarCun: "AsignarCUN"

vpn-health-check:
  # Unit of frequency: MINUTES
  schedulerFrequency: "5"
  credentials:
    user: ""
    pass: ""
  urlToken: "https://anypoint.mulesoft.com/accounts/login"
  urlVpnStatus: "https://anypoint.mulesoft.com/cloudhub/api/organizations/ETB/vpcs/vpc-0b9084aef7bddb7eb/ipsec/62461f5aae4e2e1da3c09838"

email:
  host: "smtp.gmail.com"
  port: "587"
  from:
    address: "muletest20@gmail.com"
    password: "nhhuojwchogrdndi"
  to:
    addresses: "miguel.sanchezv@etb.com.co, magda.santamariac@etb.com.co"
#    addresses: "eduar.dazao2@etb.com.co, mayerly.gonzalezc@etb.com.co, ruben.rodriguezv@etb.com.co"
  cc:
    addresses: "william.ortiz@globant.com"
  bcc:
     addresses: ""
  subject: "Health Check Report"
  
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"


vpnEmail:
  to: 
    addresses: "magda.santamariac@etb.com.co, samuel.rodriguezt@etb.com.co"
  cc:
    addresses: "soportefabrica-etb@globant.com, administracion_mdm@etb.com.co, gestion.incidentes.ti@etb.com.co, gestion_eventos_ti@etb.com.co"
  subject: "[IMPORTANTE] VPN Status"
  body: "La VPN del ambiente Prod está en estado DOWN y debe ser restablecida"

sftp:
  user: ""
  pass: ""
  port: "22"
  host: "" 
   
auditLogs:
  path: "/share_tibco/AuditoriaLogs/"
  file: "AuditoriaLogsSoatibprd01.log"
  regex: "regex:AuditoriaLogsSoatibprd01.log(\\.[0-9]*)?"
  filesLimit: "100"
  fileMaxSize: "20000000"
  separator: "~|"
  queue: "auditoriaLogger"
  
spnpqrLogs:
  path: "/share_tibco/SPNPQRLogs/"
  file: "SPNPQRLogsSoatibprd01.log"
  regex: "regex:SPNPQRLogsSoatibprd01.log(\\.[0-9]*)?"
  filesLimit: "100"
  fileMaxSize: "20000000"
  separator: "|-|"
  queue: "spnpqrLogger"
  
conversationLogs:
  path: "/share_tibco/BOTLogs/"
  file: "LogConversacionBotSoatibprd01.log"
  regex: "regex:LogConversacionBotSoatibprd01.log(\\.[0-9]*)?"
  filesLimit: "100"
  fileMaxSize: "20000000"
  separator: "|-|"
  queue: "conversationLogger"
  
sumaLogs:
  path: "/share_tibco/SUMALogs/"
  file: "SUMALogsSoatibprd01.log"
  regex: "regex:SUMALogsSoatibprd01.log(\\.[0-9]*)?"
  filesLimit: "100"
  fileMaxSize: "2000000"
  separator: "|-|"
  queue: "sumaLogger"
  
convertibilityLogs:
  path: "/share_tibco/ConvertibilityLogs/"
  file: "ConvertibilityLogsSoatibprd01.log"
  regex: "regex:ConvertibilityLogsSoatibprd01.log(\\.[0-9]*)?"
  filesLimit: "100"
  fileMaxSize: "5000000"
  separator: "|-|"
  queue: "convertibilityLogger"
  
traceabilityLogs:
  path: "/datos3/fuentes/uso_aplicaciones/"
  file: "trazabilidad_aplicaciones_temp.csv"
  finalFileName: "trazabilidad_aplicaciones_"
  fileFormat: ".csv"
  filesLimit: "100"
  fileMaxSize: "1000000"
  separator: "~|"
  queue: "traceabilityLogger"
  fileHeader: ["ID","NUMERO_SOLICITUD_APP", "TIPO_AUDITORIA", "APLICACION", "INICIATIVA", "IP", "NAVEGADOR", "NOMBRE_EQUIPO", "USUARIO", "OPERACION", "RESULTADO_OPERACION", "FECHA_SOLICITUD", "FECHA_RESPUESTA", "FECHA_REGISTRO"]
  identifier: "sequential_id_traceabilityLogs"
  sftp:
    user: "dwh_edrs"
    pass: "Cambiar_05"
    host: "10.40.24.4"
    port: "22"

traceabilityLogsEDR:
  path: "/data/fuentes1/LTE/rec/"
  file: "_edr_trazabilidad_aplicaciones_temp.csv"
  finalFileName: "edr_trazabilidad_aplicaciones_"
  fileFormat: ".csv"
  filesLimit: "100"
  fileMaxSize: "20000000"
  separator: ","
  queue: "traceabilityLoggerEDR"
  identifier: "sequential_id_traceabilityLogs_edr"
    
sftp-portability:
  user: "tibcowipro"
  pass: "Septiembre2024*"
  host: "10.112.1.152"
  port: "22"
  workingDir: "/"
  path: "/tibco/Portabilidad/Documentos/Entrada/"
 
template:
  processingServer: "MULESOFT"
  status: "PASS"
  portability:
    retries:
      amount: "1"
      milliseconds: "1000"
    
configurationTimeout:
  listener: "30000"