#%RAML 1.0 DataType
type: object
properties:
  AQOLTERequest:
    required: true
    properties:
      OrderId:
        type: string
        required: true
        minLength: 1
      ServiceId:
        type: string
        required: true
        minLength: 1
      AccountServiceId: 
        type: string
        required: false
      OrderType: 
        type: string
        required: true
        minLength: 1
      OrderSubtype: 
        type: string
        required: false
      ICCID: 
        type: string
        required: true
        minLength: 1
      IMEI: 
        type: string | nil
        required: false
      Number: 
        type: string | nil
        required: false
      ICCIDAnt: 
        type: string | nil
        required: false
      NumeroPortado:
        type: string | nil
        required: false
      SubCategoria: 
        type: string | nil
        required: false

example: !include ../../examples/request/availabilityQueryOrderRequest.json
