#%RAML 1.0 DataType
properties:
  identifier:
    type: string
    minLength: 1
  channel:
    type: string
    minLength: 1
  provisioningDate:
    type: string
    minLength: 1
  serviceCommand:
    type: string
    minLength: 1
  action:
    type: string
    minLength: 1
  services:
    type: array
    items:
      type: object
      properties:
        item:
          type: object
          properties:
            serviceValues:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  value:
                    type: string
example: !include ../../examples/request/provisioningUser.json