#%RAML 1.0 DataType
properties:
  CreateSystemsAccountsBody: 
    type: object
    properties:
      MarketType?:
        description: MarketType
        type: string
      GeoCode1?:
        description: GeoCode1
        type: string
      GeoCode2?:
        description: GeoCode2
        type: string
      GeoCode3?:
        description: GeoCode3
        type: string | nil
      ConectionNumber?:
        description: ConectionNumber
        type: string
      FD?:
        description: FD
        type: string | nil
      CurrCode?:
        description: CurrCode
        type: string
      InvDay?:
        description: InvDay
        type: string
      ConvInd?:
        description: ConvInd
        type: string
      SubId?:
        description: 
        type: string
      BillPrntSubId?:
        description: BillPrntSubId
        type: string
      PaymentPrd?:
        description: PaymentPrd
        type: string
      Billiable?:
        description: Billiable
        type: string
      InvoiceDeliveryName?:
        description: InvoiceDeliveryName
        type: string
      InvoiceMethod?:
        description: InvoiceMethod
        type: string
      OrderType?:
        description: OrderType
        type: string
      OrderSubType?:
        description: OrderSubType
        type: string
      SourceSystem?:
        description: SourceSystem
        type: string
      ClaimMethod?:
        description: ClaimMethod
        type: string | nil
      Segment?:
        description: Segment
        type: string
      SubSegment?:
        description: SubSegment
        type: string
      EconomicActivity?:
        description: EconomicActivity
        type: string
      State?:
        description: State
        type: string
      Market?:
        description: Market
        type: string | nil
      Frequency?:
        description: Frequency
        type: string
      PortfolioArrears?:
        description: PortfolioArrears
        type: string
      InvoiceType?:
        description: InvoiceType
        type: string
      InvoiceSupport?:
        description: InvoiceSupport
        type: string
      ChargingCycle?:
        description: ChargingCycle
        type: string | nil
      CodeChargingCycle?:
        description: CodeChargingCycle
        type: string | nil
      DateCutBilling?:
        description: DateCutBilling
        type: string | nil
      Taxes?:
        description: Taxes
        type: string | nil
      ModifiedMDM?:
        description: ModifiedMDM
        type: string
      OrderRelated?:
        description: OrderRelated
        type: string | nil
      SalesforceInvoiceId?:
        description: SalesforceInvoiceId
        type: string | nil
      SetTypeMDM?:
        description: SetTypeMDM
        type: string
      ExternalAddressNumber?:
        description: ExternalAddressNumber
        type: string
      StartDate?:
        type: object
        properties:
          Day?:
            description: Day
            type: string
          Month?:
            description: Month
            type: string
          Year?:
            description: Year
            type: string
      Customer?:
        type: object
        properties:
          BillingAccountName?: 
            description: BillingAccountName
            type: string
          FirstName?:
            description: FirstName
            type: string
          SecondName?:
            description: SecondName
            type: string | nil
          Surame?:
            description: Surame
            type: string
          Lastname?:
            description: Lastname
            type: string | nil
          SecondSurname?:
            description: SecondSurname
            type: string
          ClientAccountName?:
            description: ClientAccountName
            type: string
          DocumentNumber?:
            description: DocumentNumber
            type: string
          DocumentType?:
            description: DocumentType
            type: string
          AccountIdentificationID?:
            description: AccountIdentificationID
            type: string
          AccountTypeCode?:
            description: AccountTypeCode
            type: string
          IdentificationID?:
            description: IdentificationID
            type: string
          Email?:
            description: Email
            type: string
          ContactInfo?:
            type: object
            properties:
              PhoneNumber?:
                description: PhoneNumber
                type: string
              ContactEmail?:
                description: ContactEmail
                type: string
              DocumentNumber?:
                description: DocumentNumber
                type: string
      BillingAddress:
        type: object
        properties:
          BillAddress?:
            description: BillAddress
            type: string
          Country?:
            description: Country
            type: string
          DepartmentName?:
            description: DepartmentName
            type: string
          CityName?:
            description: CityName
            type: string
          Neighborhood?:
            description: Neighborhood
            type: string
          Location?:
            description: Location
            type: string
          StateCode?:
            description: StateCode
            type: string
          PostCode?:
            description: PostCode
            type: string
          DaneCode?:
            description: DaneCode
            type: string
          Stratum?:
            description: Stratum
            type: string
      BillingAccountData:
        type: object
        properties:
          SubscriberId?:
            description: SubscriberId
            type: string
      User:
        type: object
        properties:
          CreatorUser?:
            description: CreatorUser
            type: string
          ModifierUser?:
            description: ModifierUser
            type: string
  ProcessData:
    type: object
    properties:
      ProcessingType:
        description: ProcessingType
        type: string | nil
      RVC:
        description: RVC
        type: string | nil
      RMCA:
        description: RMCA
        type: string | nil
      MDM:
        description: MDM
        type: string | nil
example:
  !include ../../examples/request/postBillingAccounts.json