#%RAML 1.0 DataType
type: array
items: 
  type: object
  properties:
    id:
      type: string
      required: false
      example: "900150412"
    billingAccountId:
      type: string
      required: false
      example: "123456"
    serviceAccountId:
      type: string
      required: false
      example: "1-PXH0L5F"
    connectionNumber:
      type: string
      required: true
      minLength: 1
      example: "16509229"
    activationDate:
      type: string
      required: false
      example: "02/09/2021"
    idType:
      type: string | nil
      required: false
      example: "NIT"
    code:
      type: string | nil
      required: false
      example: "Cancelacion"