#%RAML 1.0 DataType
properties:
  TransferServicesSystemsBody:
    type: object
    properties:
      SubscriberId:
        type: string
        required: true
        example: "15052904018"
      SubscriberIdNew:
        type: string
        required: true
        example: "15052904678"
      ExtServiceId:
        type: string
        required: true
        example: "AC-1090209"
      CurrentClient:
        type: string
        required: false
        example: "CHRISTIAN JJHHJJ"
      NewClient:
        type: string
        required: false
        example: "JUAN CARDONA CARDONA"
      User:
        type: string
        required: false
        example: "Tibco"
      SubscriberNumber:
        type: string
        required: false
        example: ""
      NewCycle:
        type: number
        required: false
        example: 35
      IsLTEService:
        type: string
        required: false
        example: "Y"
      ClientDocumentType:
        type: string
        required: false
        example: "NIT"
      ClientDocumentTypeNew:
        type: string
        required: false
        example: "NIT"
      ClientDocumentNumber:
        type: string
        required: false
        example: "14589657"
      ClientDocumentNumberNew:
        type: string
        required: false
        example: "14589658"
  ProcessData:
    type: object
    required: false
    properties:
      ProcessingType:
        type: string
        required: false
        example: "Reenvio"
      RVC:
        type: string
        required: false
        example: "1"
      MDM:
        type: string
        required: false
        example: "1"
      OCS:
        type: string
        required: false
        example: "1"