#%RAML 1.0 DataType
properties:
  correlationId:
    type: string
    minLength: 1
    required: true
  fechaSolicitud:
    type: string
    minLength: 1
    required: true
  ordenOM:
    type: string
    minLength: 1
    required: true
  idRespuestaOrigen:
    type: string
    minLength: 1
    required: true
  origen:
    type: string
    minLength: 1
    required: true
  tipoSolicitud:
    type: string
    minLength: 1
    required: true
  items:
    type: array
    required: false
    items:
      properties:
        idItem:
          type: string
          minLength: 1
          required: true
        idOrigen:
          type: string
          minLength: 1
          required: true
        idRaiz:
          type: string
          required: false
        estadoItem:
          type: boolean
          required: false
        descripcionEstadoItem:
          type: string
          required: false
        productos:
          type: array
          required: false
          items:
            properties:
              nombre:
                type: string
                required: true
                minLength: 1
              codigo:
                type: string
                required: true
                minLength: 1
              opciones:
                type: array
                required: false
                items:
                  properties:
                    idOpcion:
                      type: string
                      required: true
                      minLength: 1
                    estadoOpcion:
                      type: boolean
                      required: true
                    descripcionEstadoOpcion:
                      type: string
                      required: false