#%RAML 1.0 DataType 
type: object
properties:
  id:
    type: integer
    example: 14219
    required: false
  type:
    type: integer
    example: 1
    required: false
  questions:
    type: 'null'
    example: null
    required: false
  otpCode:
    type: string
    example: '3765'
    required: false
  matchType:
    type: integer
    example: 1
    required: false
