envName: "Local"

app:
  apiId: "20497177"
  listener:
    host: "0.0.0.0"
    port: "8091"
    basePath: ""

sapi:
   client_id: "5aq8AX3BlJAwRlLLAbEmXH8eQPeXp3KY"
   client_secret: "ic80eX0L4hgH9DGy"   

payu-sapi:
  host: "localhost"
  port: "8092"
  fields:
    signature: ""
    notifyUrl: ""
    accountId: "512321"
    merchantId: "508029"
    apiLogin: "pRRXKOl8ikMmt9u"
    apiKey: "4Vj8eK4rloUd272L48hsrarnUA"
    publicKey: ""
    endpoint: "sandbox.api.payulatam.com"
    language: "es"
    test: "true"
    paymentMethod: "PSE"
    paymentCountry: "CO"
    type: "AUTHORIZATION_AND_CAPTURE"

wompi-sapi:
  host: "localhost"
  port: "8094"
  fields:
    singleUse: "true"
    collectShipping: "false"
    redirectUrl: ""
    imageUrl: ""

pse-sapi:
  host: "localhost"
  port: "8093"
  fields:
    entityCode: "8999991158"
    serviceCode: "181500017"
    beneficiaryEntityIdentificationType: "NIT"
    beneficiaryEntityIdentification: "8999991158"
    beneficiaryEntityName: "ETB" # Reemplazar por el nombre correcto de la entidad beneficiaria en pse
    beneficiaryEntityCIIUCategory: "4652"
    userType: "person"
    iva: "IVA"

mongo-db-sapi:
  host: "localhost"
  port: "8095"
 

