#%RAML 1.0 DataType 
type: object
properties:
  businessSegment:
    type: string
    example: ''
    required: false
  serviceAccount:
    type: string
    example: ''
    required: false
  connectionNumber:
    type: string
    example: ''
    required: false
  resourceID:
    type: string
    example: ''
    required: false
  resourceType:
    type: string
    example: ''
    required: false
  function:
    type: string
    example: ''
    required: false
  newNetworkState:
    type: boolean
    example: true
    required: false
  dual:
    type: boolean
    example: true
    required: false
  serial:
    type: string
    example: ''
    required: false
  syncUp:
    type: boolean
    example: false
    required: false
