#%RAML 1.0 DataType 
type: object
properties:
  customer:
    type: object
    properties:
      documentType:
        type: string
        example: CC
        required: false
      documentNumber:
        type: string
        example: '123456789'
        required: false
  device:
    type: object
    properties:
      imei:
        type: string
        example: '356938035643809'
        required: false
      brand:
        type: string
        example: Samsung
        required: false
      model:
        type: string
        example: Galaxy S23
        required: false
      manufacturer:
        type: string
        example: Samsung Electronics
        required: false
  mobileNumber:
    type: string
    example: '3001234567'
    required: false
  contactPhone:
    type: string
    example: ''
    required: false
  contactEmail:
    type: string
    example: ''
    required: false
  networkUpdate:
    type: boolean
    example: true
    required: false
