#%RAML 1.0 DataType 
type: object
properties:
  businessSegment:
    type: string
    example: ''
    required: false
  serviceAccount:
    type: string
    example: ''
    required: false
  connectionNumber:
    type: string
    example: ''
    required: false
  operation:
    type: object
    properties:
      type:
        type: string
        example: password
        required: false
      networkName:
        type: string
        example: faf35f4s
        required: false
      password:
        type: string
        example: faf35f4s
        required: false
      networkType:
        type: string
        example: ''
        required: false
      dual:
        type: boolean
        example: true
        required: false
      serial:
        type: string
        example: ''
        required: false
      syncUp:
        type: boolean
        example: false
        required: false
