#%RAML 1.0 DataType

properties:
  getCoverageOPOutput:
    type: object 
    properties:
      wsResponseHeader2:
        type: object
        properties:
          system:
            type: object
            properties:
              name:
                type: string 
                example: "Mulesoft"
              correlationID:
                type: string 
                example: "1"
              processingServer:
                type: string
                example: "Mulesoft"
          service: 
            type: object 
            properties:
              status: 
                type: string 
                example: "PASS"
              responseDate: 
                type: string
                example: "2022-02-01T07:08:22.553-05:00"
      getCoverageResponse:
        type: object
        properties:
          address:
            type: array
            items:
              properties:
                geoState:
                  type: string 
                  required: false
                  example: "A"
                addressCode:
                  type: string
                  required: false
                  example: "100000000000169150"
                latitude:
                  type: string
                  required: false
                  example: "4.574787151"
                length:
                  type: string
                  required: false
                  example: "-74.23776575"
                stratum: 
                  type: number
                  required: false
                  example: 3
                lotCode:
                  type: string
                  required: false
                  example: "922"
                destiny:
                  type: string 
                  required: false
                  example: "1"
                chip:
                  type: string
                  required: false
                  example: "SIN CHIP"
                district: 
                  type: string
                  required: false
                  example: "10000"
                location: 
                  type: string 
                  required: false
                  example: "0"
                distanceType: 
                  type: string 
                  required: false
                  example: "B"
                distanceType2:
                  type: string 
                  required: false
                  example: "A 200m"
          coverage:
            type: array
            items:
              properties:
                technology:
                  type: array
                  items:
                    properties:
                      type: 
                        type: string
                        required: false
                        example: "FTTC"
                      coverageType:
                        type: string 
                        required: false
                        example: "DISTRITO"
                      coverage:   
                        type: string 
                        required: false
                        example: "DISTRITO"
                      coverageName: 
                        type: string 
                        required: false
                        example: "26049" 
                      areaType:
                        type: string 
                        required: false
                        example: "CENTRAL"
                      area: 
                        type: string 
                        required: false
                        example: "SOACHA" 