#%RAML 1.0 DataType
properties:
  IdentificadorProceso:
    description: Process id
    type: string
    example: "00007202111220101137"
  IdentificadorMensaje:
    description: Message Id
    type: string
    example: "00007202111220100180"
  FechaCreacionMsg:
    description: Petition creation date - current date
    type: datetime-only
    example: 2021-11-22T11:43:36
  TipoMsg:
    description: Tipo de Mensaje
    type: string
    example: "1006"
  Emisor:
    description: Emisor
    type: string
    example: "00007"
  Observaciones:
    description: Observaciones
    type: string
    example: "Observaciones"
  FechaVentanaCambio:
    description: Change date
    type: datetime-only
    example: 2021-11-22T11:43:36