#%RAML 1.0 DataType
properties:
  ticketNumber:
    type: string
    example: "INC0001"
  status:
    type: string
    example: "Iniciado"

example: !include ../../examples/responses/postIncident.json