#%RAML 1.0 DataType
displayName: Order Availability Response Fail
type: object
properties:
  status:
    type: string
  description:
    type: string
example: !include ../../examples/responses/postAvailabilityOrderFail.raml