#%RAML 1.0 DataType
displayName: Order Availability Response
type: object
properties:
  status:
    type: string
  orderNumber:
    type: string
  idServiceAccount:
    type: string
example: !include ../../examples/responses/postCancelOrder.raml