#%RAML 1.0 DataType
properties:
  status:
    type: string
    example: "O90"
  orderNumber:
    type: string
    example: "MDM-MAY-00001"
  serviceAccount:
    type: string
    example: "GPONMAY_000001"
  description:
    type: string
    example: "OK"
  activationDate:
    type: string
    example: "2022-08-29T13:38:10.573Z"