#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: Notificación enviada exitosamente
    required: false
  detail:
    type: object
    properties:
      message:
        type: string
        example: Su notificación ha sido enviada correctamente
        required: false
