#%RAML 1.0 DataType 
type: object
properties:
  status:
    type: string
    example: OK
    required: false
  code:
    type: string
    example: OK_01
    required: false
  message:
    type: string
    example: La PQR fue creada exitosamente
    required: false
  pqr:
    type: object
    required: false
    properties:
      idPqr:
        type: string
        example: MDM-PQR-54325333
        required: false
      cun:
        type: string
        example: '4347260000121199'
        required: false
      causal:
        type: string
        example: FALLA EN CPE
        required: false
      contactDocumentNumber:
        type: string
        example: '1070589487'
        required: false
      contactDocumentType:
        type: string
        example: CC
        required: false
      creationDate:
        type: string
        example: '2026-01-27T11:01:56Z'
        required: false
      description:
        type: string
        example: Cliente reporta falla en el servicio
        required: false
      documentNumber:
        type: string
        example: '1070589487'
        required: false
      documentType:
        type: string
        example: CC
        required: false
      isSon:
        type: boolean
        example: false
        required: false
      kind:
        type: string
        example: PETICION
        required: false
      phone:
        type: string
        example: '6017926630'
        required: false
      reason:
        type: string
        example: FALLA TECNICA
        required: false
      state:
        type: string
        example: ABIERTA
        required: false
      symptom:
        type: string
        example: DAÑO EN MODEM O ELEMENTOS DEL MODEM
        required: false
      type:
        type: string
        example: PRODUCTO
        required: false
