#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: ''
    required: false
  pqrs:
    type: array
    items:
      type: object
      properties:
        agenda:
          type: 'null'
          example: null
          required: false
        agendas:
          type: 'null'
          example: null
          required: false
        activities:
          type: array
          items:
            type: object
            properties:
              assignedUser:
                type: string
                example: laurros1
                required: false
              creationUser:
                type: string
                example: laurros1
                required: false
              description:
                type: string
                example: ''
                required: false
              expirationDate:
                type: object
                properties:
                  date:
                    type: string
                    example: '2025-08-02T15:12:32Z'
                    required: false
                  format1:
                    type: string
                    example: 02/08
                    required: false
                  format2:
                    type: string
                    example: 02/08/2025
                    required: false
                  format3:
                    type: string
                    example: 02/08/2025 15:12:32
                    required: false
                  format4:
                    type: string
                    example: 02/08/2025 03:12:32 PM
                    required: false
                  day:
                    type: object
                    properties:
                      format1:
                        type: string
                        example: '02'
                        required: false
                      format2:
                        type: string
                        example: Sáb.
                        required: false
                      format3:
                        type: string
                        example: Sábado
                        required: false
                  month:
                    type: object
                    properties:
                      format1:
                        type: string
                        example: '08'
                        required: false
                      format2:
                        type: string
                        example: Ago.
                        required: false
                      format3:
                        type: string
                        example: Agosto
                        required: false
                  year:
                    type: object
                    properties:
                      format1:
                        type: string
                        example: '25'
                        required: false
                      format2:
                        type: string
                        example: '2025'
                        required: false
                      format3:
                        type: string
                        example: '02025'
                        required: false
                  hour:
                    type: object
                    properties:
                      format1:
                        type: time-only
                        example: '15:12:32'
                        required: false
                      format2:
                        type: string
                        example: 03:12:32 PM
                        required: false
                      format3:
                        type: string
                        example: '15'
                        required: false
                      format4:
                        type: string
                        example: 03 PM
                        required: false
                      format5:
                        type: string
                        example: '12'
                        required: false
                      format6:
                        type: string
                        example: '32'
                        required: false
              id:
                type: string
                example: MDM-PQR-ACT-108277393
                required: false
              management:
                type: string
                example: MIXTA
                required: false
              managementDescription:
                type: string
                example: PENDIENTE ENTREGA
                required: false
              name:
                type: string
                example: INSTANCIA ADMINISTRATIVA
                required: false
              startDate:
                type: object
                properties:
                  date:
                    type: string
                    example: '2025-07-28T15:12:32Z'
                    required: false
                  format1:
                    type: string
                    example: 28/07
                    required: false
                  format2:
                    type: string
                    example: 28/07/2025
                    required: false
                  format3:
                    type: string
                    example: 28/07/2025 15:12:32
                    required: false
                  format4:
                    type: string
                    example: 28/07/2025 03:12:32 PM
                    required: false
                  day:
                    type: object
                    properties:
                      format1:
                        type: string
                        example: '28'
                        required: false
                      format2:
                        type: string
                        example: Lun.
                        required: false
                      format3:
                        type: string
                        example: Lunes
                        required: false
                  month:
                    type: object
                    properties:
                      format1:
                        type: string
                        example: '07'
                        required: false
                      format2:
                        type: string
                        example: Jul.
                        required: false
                      format3:
                        type: string
                        example: Julio
                        required: false
                  year:
                    type: object
                    properties:
                      format1:
                        type: string
                        example: '25'
                        required: false
                      format2:
                        type: string
                        example: '2025'
                        required: false
                      format3:
                        type: string
                        example: '02025'
                        required: false
                  hour:
                    type: object
                    properties:
                      format1:
                        type: time-only
                        example: '15:12:32'
                        required: false
                      format2:
                        type: string
                        example: 03:12:32 PM
                        required: false
                      format3:
                        type: string
                        example: '15'
                        required: false
                      format4:
                        type: string
                        example: 03 PM
                        required: false
                      format5:
                        type: string
                        example: '12'
                        required: false
                      format6:
                        type: string
                        example: '32'
                        required: false
              state:
                type: string
                example: Cerrado
                required: false
        assignedUser:
          type: string
          example: laurros1
          required: false
        billingAccount:
          type: string
          example: '12054363574'
          required: false
        characteristics:
          type: array
          items:
            type: object
            properties:
              action:
                type: 'null'
                example: null
                required: false
              name:
                type: string
                example: DescripcionTipologia
                required: false
              value:
                type: string
                example: >-
                  Información con la  gestión y requisitos del trámite de 
                  cancelación de los servicios suscritos
                required: false
        contactDocumentNumber:
          type: string
          example: '52530339'
          required: false
        contactDocumentType:
          type: string
          example: CC
          required: false
        creationDate:
          type: object
          properties:
            date:
              type: string
              example: '2025-07-28T15:12:34Z'
              required: false
            format1:
              type: string
              example: 28/07
              required: false
            format2:
              type: string
              example: 28/07/2025
              required: false
            format3:
              type: string
              example: 28/07/2025 15:12:34
              required: false
            format4:
              type: string
              example: 28/07/2025 03:12:34 PM
              required: false
            day:
              type: object
              properties:
                format1:
                  type: string
                  example: '28'
                  required: false
                format2:
                  type: string
                  example: Lun.
                  required: false
                format3:
                  type: string
                  example: Lunes
                  required: false
            month:
              type: object
              properties:
                format1:
                  type: string
                  example: '07'
                  required: false
                format2:
                  type: string
                  example: Jul.
                  required: false
                format3:
                  type: string
                  example: Julio
                  required: false
            year:
              type: object
              properties:
                format1:
                  type: string
                  example: '25'
                  required: false
                format2:
                  type: string
                  example: '2025'
                  required: false
                format3:
                  type: string
                  example: '02025'
                  required: false
            hour:
              type: object
              properties:
                format1:
                  type: time-only
                  example: '15:12:34'
                  required: false
                format2:
                  type: string
                  example: 03:12:34 PM
                  required: false
                format3:
                  type: string
                  example: '15'
                  required: false
                format4:
                  type: string
                  example: 03 PM
                  required: false
                format5:
                  type: string
                  example: '12'
                  required: false
                format6:
                  type: string
                  example: '34'
                  required: false
        creationUser:
          type: string
          example: laurros1
          required: false
        isAgendaSuspended:
          type: boolean
          example: false
          required: false
        isSon:
          type: boolean
          example: false
          required: false
        notificationMedium:
          type: string
          example: TELEFONICO
          required: false
        modificationDate:
          type: object
          properties:
            date:
              type: datetime
              example: '2025-07-28T15:17:12.542Z'
              required: false
            format1:
              type: string
              example: 28/07
              required: false
            format2:
              type: string
              example: 28/07/2025
              required: false
            format3:
              type: string
              example: 28/07/2025 15:17:12
              required: false
            format4:
              type: string
              example: 28/07/2025 03:17:12 PM
              required: false
            day:
              type: object
              properties:
                format1:
                  type: string
                  example: '28'
                  required: false
                format2:
                  type: string
                  example: Lun.
                  required: false
                format3:
                  type: string
                  example: Lunes
                  required: false
            month:
              type: object
              properties:
                format1:
                  type: string
                  example: '07'
                  required: false
                format2:
                  type: string
                  example: Jul.
                  required: false
                format3:
                  type: string
                  example: Julio
                  required: false
            year:
              type: object
              properties:
                format1:
                  type: string
                  example: '25'
                  required: false
                format2:
                  type: string
                  example: '2025'
                  required: false
                format3:
                  type: string
                  example: '02025'
                  required: false
            hour:
              type: object
              properties:
                format1:
                  type: time-only
                  example: '15:17:12'
                  required: false
                format2:
                  type: string
                  example: 03:17:12 PM
                  required: false
                format3:
                  type: string
                  example: '15'
                  required: false
                format4:
                  type: string
                  example: 03 PM
                  required: false
                format5:
                  type: string
                  example: '17'
                  required: false
                format6:
                  type: string
                  example: '12'
                  required: false
        order:
          type: 'null'
          example: null
          required: false
        radicationDate:
          type: object
          properties:
            date:
              type: string
              example: '2025-07-28T15:10:07Z'
              required: false
            format1:
              type: string
              example: 28/07
              required: false
            format2:
              type: string
              example: 28/07/2025
              required: false
            format3:
              type: string
              example: 28/07/2025 15:10:07
              required: false
            format4:
              type: string
              example: 28/07/2025 03:10:07 PM
              required: false
            day:
              type: object
              properties:
                format1:
                  type: string
                  example: '28'
                  required: false
                format2:
                  type: string
                  example: Lun.
                  required: false
                format3:
                  type: string
                  example: Lunes
                  required: false
            month:
              type: object
              properties:
                format1:
                  type: string
                  example: '07'
                  required: false
                format2:
                  type: string
                  example: Jul.
                  required: false
                format3:
                  type: string
                  example: Julio
                  required: false
            year:
              type: object
              properties:
                format1:
                  type: string
                  example: '25'
                  required: false
                format2:
                  type: string
                  example: '2025'
                  required: false
                format3:
                  type: string
                  example: '02025'
                  required: false
            hour:
              type: object
              properties:
                format1:
                  type: time-only
                  example: '15:10:07'
                  required: false
                format2:
                  type: string
                  example: 03:10:07 PM
                  required: false
                format3:
                  type: string
                  example: '15'
                  required: false
                format4:
                  type: string
                  example: 03 PM
                  required: false
                format5:
                  type: string
                  example: '10'
                  required: false
                format6:
                  type: string
                  example: '07'
                  required: false
        receptionMedium:
          type: string
          example: LÍNEA TELEFÓNICA
          required: false
        service:
          type: 'null'
          example: null
          required: false
        subChannel:
          type: string
          example: TELEFÓNICO
          required: false
        suspensionDetail:
          type: 'null'
          example: null
          required: false
        solutionDate:
          type: 'null'
          example: null
          required: false
        cUN:
          type: string
          example: ''
          required: false
        cunMassiveFailure:
          type: string
          example: ''
          required: false
        cunRelated:
          type: string
          example: ''
          required: false
        customer:
          type: object
          properties:
            aTDP:
              type: 'null'
              example: null
              required: false
            birthday:
              type: 'null'
              example: null
              required: false
            business:
              type: 'null'
              example: null
              required: false
            collectionCommunications:
              type: 'null'
              example: null
              required: false
            documentNumber:
              type: string
              example: '52530339'
              required: false
            documentType:
              type: string
              example: CC
              required: false
            email:
              type: string
              example: ''
              required: false
            mobilePhone:
              type: 'null'
              example: null
              required: false
            mobilePhone2:
              type: 'null'
              example: null
              required: false
            name:
              type: object
              properties:
                completeName:
                  type: string
                  example: OLGA CAROLINA CASTILLO ROMERO
                  required: false
                firstName:
                  type: string
                  example: OLGA
                  required: false
                firstSurname:
                  type: string
                  example: CASTILLO
                  required: false
                names:
                  type: string
                  example: OLGA CAROLINA
                  required: false
                secondName:
                  type: string
                  example: CAROLINA
                  required: false
                secondSurname:
                  type: string
                  example: ROMERO
                  required: false
                surnames:
                  type: string
                  example: CASTILLO ROMERO
                  required: false
            segmentation:
              type: 'null'
              example: null
              required: false
            validationCode:
              type: 'null'
              example: null
              required: false
        description:
          type: string
          example: "NOMBRE: CAROLINA\nCEDULA: 52530339\nTEL: 3124853341 \_\nCORREO: condorcas@hotmail.com \_\nDIRRECION: CL 74C SUR 12 20\nLINEA: SR-30593591 \t\nCUENTA: 12054363574\nMOTIVO: DESEA CANCELAR Y BA  A REALIZAR LA CARTA PARA QUE NO LE COBREN EL SERVICIO POR FALLA MASIVA YA QUE AL DIA DE HOY AUN NO SE LE SOLUCIONA LA FALLA \n"
          required: false
        id:
          type: string
          example: MDM-PQR-52226815
          required: false
        idRemedy:
          type: string
          example: ''
          required: false
        isYoungFail:
          type: boolean
          example: false
          required: false
        phone:
          type: string
          example: ''
          required: false
        response:
          type: string
          example: ''
          required: false
        serviceAccount:
          type: string
          example: CS-1375757
          required: false
        serviceId:
          type: string
          example: CS-1375757
          required: false
        solution:
          type: string
          example: 'CLIENTE INDIDICA QUE SE VA  HACERCAR A UN PUNTO HACER EL TRAMITE '
          required: false
        state:
          type: string
          example: Resuelto
          required: false
        stateTechnical:
          type: string
          example: Cerrado
          required: false
        typology:
          type: object
          properties:
            causal:
              type: string
              example: REQUISITOS Y ESTADO DEL TRAMITE
              required: false
            class:
              type: string
              example: PETICION
              required: false
            cUN:
              type: boolean
              example: false
              required: false
            extension:
              type: object
              properties:
                closeType:
                  type: string
                  example: ACCEDE
                  required: false
                notificationMedium:
                  type: string
                  example: TELEFONICO
                  required: false
                operator:
                  type: string
                  example: ETB S.A. ESP
                  required: false
                operatorLsp:
                  type: string
                  example: RECEPCIÓN
                  required: false
                receptionMedium:
                  type: string
                  example: LÍNEA TELEFÓNICA
                  required: false
            product:
              type: string
              example: PAQUETE
              required: false
            reason:
              type: string
              example: INFORMACION Y/O DOCUMENTACION
              required: false
            remedy:
              type: boolean
              example: false
              required: false
            symptom:
              type: string
              example: CANCELACIÓN
              required: false
            technology:
              type: string
              example: FTTC
              required: false
            type:
              type: string
              example: PRODUCTO
              required: false
            version:
              type: string
              example: '31'
              required: false