#%RAML 1.0 DataType
type: object
displayName: geographicAddress
description: TMF673-aligned response with a list of geographic addresses
properties:
  Success:
    type: boolean
    required: true
    example: true
  DataList:
    type: any
    required: false
    example: null
  DataArray:
    type: any
    required: false
    example: null
  DataSingle:
    type: object
    properties:
      Addresses:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: Identificador único de dirección
              example: "612802304622340077"
            fullAddress:
              type: string
              description: Dirección detallada
              example: "CL 94A 67A 74 LC 18"
            Direccion_Actual:
              type: string
              description: Dirección inicial o base
              example: "CL 94A 67A 74"
            residentialType:
              type: string
              description: Estrato Catastro
              example: "6"
            municipalityCode:
              type: string
              description: Id Municipio
              example: "11001"
            latitude:
              type: string
              description: Latitud
              example: "4.53091498900005"
            longitude:
              type: string
              description: Longitud
              example: "-74.117704933"
            diraprox:
              type: string
              description: Dirección aproximada
              example: "KR 11 67A 01 S"
            tipo_direccion:
              type: string
              description: Tipo de dirección
              example: "Dirección por aproximación"
            Check:
              type: boolean
              example: false
  Message:
    type: string
    required: false
    example: ""
  Results:
    type: integer
    required: false
    example: 0
  MessageObj:
    type: any
    required: false
    example: null