#%RAML 1.0 NamedExample
value:
  Resultado: "OK"
  Codigo: 0
  Descripcion: "Proceso ejecutado con éxito"
  Estado: "A"
  EstadoRecurso: "RESERVADO"
  Fecha: 3/1/2022
  ICCID: 89571871150026603384
  IMSI: 732187104702920
  IdPedido: a094y00000Y6iu3AAB
  IdServicio: a023300000ZpLzkAAF-a094y00000Y6iu3AAB
  MSISDN: 3008255056
  Modelo: "GENERICO"
  Operacion: "COMPLETAR"
  PIN: "0000"
  PUK: "37236395"
  PIN2: "6299"
  PUK2: "72200608"
  TipoRecurso: "ICCID"
  Tramite: "CAMBIO SIM" 
