#%RAML 1.0
title: ia-xapi-services
version: 1
protocols:
  - HTTPS
mediaType: 
- application/json
baseUri: https://ia-xapi-services-{env}.us-e2.cloudhub.io/ia/

securitySchemes:
  etb_oauth_2_0: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

traits:
  tibcoHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.4/tibcorequestheaders.raml
types:
  post-billing-conceptosFactura: !include /dataTypes/request/post-billing-conceptosFactura.raml
  post-billing-variacionFactura: !include /dataTypes/request/post-billing-variacionFactura.raml
  response-billing-conceptosFactura: !include /dataTypes/response/post-billing-conceptosFactura.raml
  response-billing-variacionFactura: !include /dataTypes/response/post-billing-variacionFactura.raml

/v1:
  /billing:
    /{tipoConsulta}:
      uriParameters:
        tipoConsulta:
          type: string
      post:
        is: tibcoHeaders
        securedBy: etb_oauth_2_0
        displayName: API para obtener los conceptos de facturacion o variacion de facturas
        description: API para obtener los conceptos de facturacion o variacion de facturas
        queryParameters:
          tipoDocumento:
            type: string
            example: "CC"
            required: false
          numeroIdentificacion:
            type: string
            example: "2689845"
            required: false
        body:
          application/json: post-billing-conceptosFactura | post-billing-variacionFactura
        responses:
          200:
            body:
              application/json: 
                type: response-billing-conceptosFactura | response-billing-variacionFactura
          500:
            body:
              application/json:
                example: !include /dataTypes/examples/responses/error-500.json
