#%RAML 1.0 DataType
type: object
properties:
  response:
    type: object
    description: Respuesta de la API de Catastro Bogotá
    properties:
      data:
        type: object
        description: Datos de geocodificación
        properties:
          estado:
            type: string
            description: Estado de la geocodificación
            example: "success"
          yinput:
            type: number
            description: Coordenada Y de entrada
            example: 4.53091498900005
          lotcodigo:
            type: string
            description: Código del lote
            example: "002589010002"
          latitude:
            type: string
            description: Latitud
            example: "4.53091498900005"
          diraprox:
            type: string
            description: Dirección aproximada
            example: "KR 11 67A 01 S"
          mancodigo:
            type: string
            description: Código de manzana
            example: "002589010"
          cpocodigo:
            type: string
            description: Código CPO
            example: "110521"
          xinput:
            type: number
            description: Coordenada X de entrada
            example: -74.117704933
          codloc:
            type: string
            description: Código de localidad
            example: "05"
          dirtrad:
            type: string
            description: Dirección tradicional
            example: "KR 11 67A 01 S"
          nomupz:
            type: string
            description: Nombre de UPZ
            example: "Rafael Uribe"
          localidad:
            type: string
            description: Localidad
            example: "USME"
          dirinput:
            type: string
            description: Dirección de entrada
            example: "Carrera 11 67A 40 SUR"
          codupz:
            type: string
            description: Código de UPZ
            example: "UPL20"
          nomseccat:
            type: string
            description: Nombre de sección catastral
            example: "PORVENIR"
          tipo_direccion:
            type: string
            description: Tipo de dirección
            example: "Dirección por aproximación"
          codseccat:
            type: string
            description: Código de sección catastral
            example: "002589"
          longitude:
            type: string
            description: Longitud
            example: "-74.117704933"
      success:
        type: boolean
        description: Indica si la operación fue exitosa
        example: true
      message:
        type: string
        description: Mensaje de respuesta
        example: "Geocodificación Exitosa."
  status:
    type: boolean
    description: Estado general de la respuesta
    example: true
