http:
  private:
    port: "8091"
  
autodiscovery: "20441014"

mongo-db-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/mongo/v1"
  serviceProblem:
    base-path: "/serviceProblem"
  resource:  
    pqr: 
      path: "/pqrs"
    pqr_patch: 
      path: "/pqrs/{id}"
    orders:
      path: "/orders"
    consecutive:
      path: "/consecutive"
      serie: "PQR_ACTIVIDAD_PQR"
  parameters:
    base-path: "/parameters"

  security:
    client-id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client-secret: "8917F36fBC2c4105b72c7bC3a165740F"
    
smallworld-sapi:
  protocol: "HTTP"
  port: "8091"
  host: "mule-worker-internal-smallworld-sapi-services-prod.us-e2.cloudhub.io"
  basepath: "/smallworld/v1"
  endpoints:
    zonaAltoRiesgo:
      base-path: "/zonaAltoRiesgo"

  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

bot-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/api"
  endpoints:
    support:
      base-path: "/support"
      init: "/init/v1"
    soporte1n:
     base-path: "/soporte1n"
     getwifi: "/getwifi/v1"
     validatetv: "/validatetv/v1"
    services:
     base-path: "/services"
     reconexion: "/reconexion/v1"
     getService: "/get/v1"
      
  client-id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client-secret: "8917F36fBC2c4105b72c7bC3a165740F"

configurationTimeout:
  bot-sapi: "62000"
  smallworld-sapi: "62000"
  
audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"