#%RAML 1.0 DataType
displayName: CUN Operation Response
type: object

properties:
  code:
    type: string
    example: "201"
    required: true
  message:
    type: string
    example: "CUN operation completed correctly"
    required: true
  cun:
    type: object
    required: true
    properties:
      cunNumber:
        type: string
        example: "CUN986532"
        required: false
      cunDate:
        type: string
        example: "2026-03-16"
        required: false
      cunType:
        type: string
        example: "VTA"
        required: false
      date:
        type: string
        example: "2026-03-16"
        required: false
      system:
        type: string
        example: "MDM"
        required: false
      orderNumber:
        type: string
        example: "ORD123265"
        required: false
      identificationType:
        type: string
        example: "CC"
        required: false
      identification:
        type: string
        example: "98653212"
        required: false
      connectionNumber:
        type: string
        example: "CONN54976"
        required: false
examples:
  postCunResponse: !include ../../examples/response/post-cun-assignment.json