#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: SIM service order created successfully
    required: false
  result:
    type: object
    properties:
      subscriberId:
        type: string
        example: '12345'
        required: false
      description:
        type: string
        example: Activación Exitosa
        required: false
