#%RAML 1.0 DataType
type: object
description: Unified response for customer product operations

properties:

  code:
    type: string
    required: true
    example: "200"

  message:
    type: string
    required: true
    example: "Operation completed successfully"

  result:
    type: object
    required: false
    properties:

      action:
        type: string
        required: false
        example: "cancel"

      customer:
        type: object
        required: false
        properties:
          customerKey:
            type: string
            required: false
            example: "69978242"

      product:
        type: object
        required: false
        properties:
          name:
            type: string
            required: false
            example: "Amazon Prime"
          id:
            type: number
            required: false
            example: 449

      order:
        type: object
        required: false
        properties:

          id:
            type: string
            required: false
            example: "246040451"

          description:
            type: string
            required: false
            example: "Cancel - Amazon Prime"

          parentId:
            type: string
            required: false
            example: "0"

          status:
            type: object
            required: false
            properties:
              name:
                type: string
                required: false
                example: "Pending"
              id:
                type: string
                required: false
                example: "0"

          entity:
            type: object
            required: false
            properties:
              type:
                type: string
                required: false
                example: "24"
              id:
                type: string
                required: false
                example: "59263921"

          event:
            type: object
            required: false
            properties:
              name:
                type: string
                required: false
                example: "Cancel Product"
              id:
                type: string
                required: false
                example: "142"

          reason:
            type: object
            required: false
            properties:
              name:
                type: string
                required: false
                example: "Scheduled Month-End Cancel"
              id:
                type: string
                required: false
                example: "28"

          user:
            type: object
            required: false
            properties:
              name:
                type: string
                required: false
                example: "ESB_REGIONAL"
              id:
                type: string
                required: false
                example: "10036"

          createDatetime:
            type: string
            required: false
            example: "2020-08-10T14:15:50"

          executeDatetime:
            type: string
            required: false
            example: "2020-08-31T21:00:00"

      serviceOrder:
        type: object
        required: false
        properties:
          state:
            type: string
            required: false
            example: "COMPLETED"

  responseMetadata:
    type: object
    required: false
    properties:

      requestMetadata:
        type: object
        required: true
        properties:

          systemId:
            type: string
            required: false
            example: "ETB"

          sender:
            type: object
            required: false
            properties:
              country:
                type: string
                required: false
                example: "CO"

          requestId:
            type: any
            required: false
            example: 1234456

          userId:
            type: string
            required: false
            example: "TEST"

      returnCode:
        type: number
        required: false
        example: 0

      returnMessage:
        type: string
        required: false
        example: "SUCCESS"