<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.microsoft.com/ws/06/2004/policy/http" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" targetNamespace="http://tempuri.org/" name="IValidaService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
            <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <xsd:import namespace="http://schemas.datacontract.org/2004/07/System" />
            <xsd:element name="ValidarIdentificacion">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" maxOccurs="1" name="objSolicitud" type="tns:SolicitudValidarIdentificacion" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ValidarIdentificacionResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" maxOccurs="1" name="ValidarIdentificacionResult" type="tns:RespuestaValidarIdentificacion" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ObtenerCuestionario">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" maxOccurs="1" name="objSolicitud" type="tns:SolicitudCuestionario" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ObtenerCuestionarioResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" maxOccurs="1" name="ObtenerCuestionarioResult" type="tns:RespuestaCuestionario" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ValidarCuestionario">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" maxOccurs="1" name="objSolicitud" type="tns:SolicitudValidarCuestionario" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ValidarCuestionarioResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element minOccurs="0" maxOccurs="1" name="ValidarCuestionarioResult" type="tns:RespuestaValidarCuestionario" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:complexType name="SolicitudValidarIdentificacion">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="1" name="Usuario" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Contrasena" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="TipoIdentificacion" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Identificacion" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Apellido" type="xsd:string" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="FechaExpedicion" type="xsd:dateTime" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Modelo" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Departamento" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Ciudad" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Asesor" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="CanalVenta" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Proveedor" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Portal" type="xsd:string" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RespuestaValidarIdentificacion">
                <xsd:sequence>
                    <xsd:element minOccurs="1" maxOccurs="1" name="IdValidacion" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="ResultadoProceso" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="EstadoHomologado" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="XmlCentral" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Score" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Oferta" type="xsd:string" />
                    <xsd:element nillable="true" minOccurs="1" maxOccurs="1" name="FechaScore" type="xsd:dateTime" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="TieneScore" type="xsd:boolean" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="FechaControl" type="xsd:dateTime" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="SolicitudCuestionario">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="1" name="Usuario" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Contrasena" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="TipoIdentificacion" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Identificacion" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Apellido" type="xsd:string" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="FechaExpedicion" type="xsd:dateTime" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Modelo" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Departamento" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Ciudad" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Asesor" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="CanalVenta" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Proveedor" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Portal" type="xsd:string" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RespuestaCuestionario">
                <xsd:sequence>
                    <xsd:element minOccurs="1" maxOccurs="1" name="IdCuestionario" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="ResultadoProceso" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Cuestionario" nillable="true" type="tns:ArrayOfPregunta" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="FechaControl" type="xsd:dateTime" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="SolicitudValidarCuestionario">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="1" name="Usuario" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Contrasena" type="xsd:string" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="IdCuestionario" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Respuestas" nillable="true" type="tns:ArrayOfRespuesta" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Modelo" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Departamento" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Ciudad" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Asesor" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="CanalVenta" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Proveedor" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Portal" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="NumeroContacto" type="xsd:string" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Tipo" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="Estrato" type="xsd:int" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="CalcularScore" type="xsd:boolean" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="RespuestaValidarCuestionario">
                <xsd:sequence>
                    <xsd:element minOccurs="1" maxOccurs="1" name="ValidarCuestionario" type="xsd:int" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="ResultadoProceso" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="ResultadoValidacion" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Score" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Oferta" type="xsd:string" />
                    <xsd:element minOccurs="1" maxOccurs="1" name="FechaControl" type="xsd:dateTime" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="Identificacion" type="xsd:string" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="ArrayOfPregunta">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="Pregunta" type="tns:Pregunta" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="ArrayOfRespuesta">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="Respuesta" type="tns:Respuesta" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Pregunta">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="1" name="DescripcionPregunta" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" xmlns:q1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" name="Respuestas" nillable="true" type="q1:ArrayOfString" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Respuesta">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="1" name="DescripcionPregunta" type="xsd:string" />
                    <xsd:element minOccurs="0" maxOccurs="1" name="DescripcionRespuesta" type="xsd:string" />
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
        <xsd:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/Arrays" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
            <xsd:complexType name="ArrayOfString">
                <xsd:sequence>
                    <xsd:element minOccurs="0" maxOccurs="unbounded" nillable="true" name="string" type="xsd:string" />
                </xsd:sequence>
            </xsd:complexType>
            <xsd:element name="ArrayOfString" nillable="true" type="tns:ArrayOfString" />
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="IValidaService_ValidarIdentificacion_InputMessage">
        <wsdl:part name="parameters" element="tns:ValidarIdentificacion" />
    </wsdl:message>
    <wsdl:message name="IValidaService_ValidarIdentificacion_OutputMessage">
        <wsdl:part name="parameters" element="tns:ValidarIdentificacionResponse" />
    </wsdl:message>
    <wsdl:message name="IValidaService_ObtenerCuestionario_InputMessage">
        <wsdl:part name="parameters" element="tns:ObtenerCuestionario" />
    </wsdl:message>
    <wsdl:message name="IValidaService_ObtenerCuestionario_OutputMessage">
        <wsdl:part name="parameters" element="tns:ObtenerCuestionarioResponse" />
    </wsdl:message>
    <wsdl:message name="IValidaService_ValidarCuestionario_InputMessage">
        <wsdl:part name="parameters" element="tns:ValidarCuestionario" />
    </wsdl:message>
    <wsdl:message name="IValidaService_ValidarCuestionario_OutputMessage">
        <wsdl:part name="parameters" element="tns:ValidarCuestionarioResponse" />
    </wsdl:message>
    <wsdl:portType name="IValidaService">
        <wsdl:operation name="ValidarIdentificacion">
            <wsdl:input message="tns:IValidaService_ValidarIdentificacion_InputMessage" />
            <wsdl:output message="tns:IValidaService_ValidarIdentificacion_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="ObtenerCuestionario">
            <wsdl:input message="tns:IValidaService_ObtenerCuestionario_InputMessage" />
            <wsdl:output message="tns:IValidaService_ObtenerCuestionario_OutputMessage" />
        </wsdl:operation>
        <wsdl:operation name="ValidarCuestionario">
            <wsdl:input message="tns:IValidaService_ValidarCuestionario_InputMessage" />
            <wsdl:output message="tns:IValidaService_ValidarCuestionario_OutputMessage" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding" type="tns:IValidaService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="ValidarIdentificacion">
            <soap:operation soapAction="http://tempuri.org/IValidaService/ValidarIdentificacion" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="ObtenerCuestionario">
            <soap:operation soapAction="http://tempuri.org/IValidaService/ObtenerCuestionario" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="ValidarCuestionario">
            <soap:operation soapAction="http://tempuri.org/IValidaService/ValidarCuestionario" style="document" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="IValidaService">
        <wsdl:port name="BasicHttpBinding" binding="tns:BasicHttpBinding">
            <soap:address location="http://lisimuat.eastus.cloudapp.azure.com:8025/wsValida.asmx" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>