#%RAML 1.0 Trait
usage: Definición estándar de la tipología de un error basados en los códigos de respuesta HTTP
displayName: Definición estándar de un error
description: Definición estándar de la tipología de un error basados en los códigos de respuesta HTTP
responses:  
    400:
      description: El servidor no pudo interpretar la solicitud dada una sintaxis inválida.
      body: 
        application/json: 
          type: !include types/api-fault.raml
    401:
      description: Es necesario autenticar para obtener la respuesta solicitada.
      body:
        application/json:
          type: !include types/api-fault.raml
    403:
      description: El cliente no posee los permisos necesarios para cierto contenido, por lo que el servidor está rechazando otorgar una respuesta apropiada.
      body:
        application/json:
          type: !include types/api-fault.raml
    404:
      description: El servidor no pudo encontrar el contenido solicitado
      body: 
        application/json: 
          type: !include types/api-fault.raml
    405:
      description: El método solicitado es conocido por el servidor pero ha sido deshabilitado y no puede ser utilizado.
      body: 
        application/json: 
          type: !include types/api-fault.raml
    415:
      description: El formato multimedia de los datos solicitados no está soportado por el servidor, por lo cual el servidor rechaza la solicitud.
      body: 
        application/json: 
          type: !include types/api-fault.raml
    429:
        description: El usuario ha enviado demasiadas solicitudes en un periodo de tiempo dado.
        body:
          application/json:
            type: !include types/api-fault.raml
    500:
      description: El servidor ha encontrado una situación que no sabe cómo manejarla
      body: 
        application/json: 
          type: !include types/api-fault.raml
    503:
      description: El servidor no está listo para manejar la petición.
      body:
        application/json:
          type: !include types/api-fault.raml
    504:
      description: Esta respuesta de error es dada cuando el servidor está actuando como una puerta de enlace y no puede obtener una respuesta a tiempo.
      body:
        application/json:
          type: !include types/api-fault.raml