#%RAML 1.0 DataType


  properties:
    ZRFC_TRAMITE_RECONEXION:
      type: object
      properties:
        CANAL:
          type: string
          example: "IVR"
          required: true
        CORRELATIONID:
          type: string
          example: "REALIZAR-RECONEXION-1638335409"
          required: true
        FECHA:
          type: date-only
          example: "2021-12-01"
          required: true
        TRAMITE:
          type: integer
          example: 10197
          required: true
        VKONA: 
          type: integer
          example: 12053567662
          required: true