#%RAML 1.0
title: mdm-xapi-services
baseUri: https://mdm-xapi-services-{env}.us-e2.cloudhub.io
protocols:
  - HTTPS

traits:
  tibcoHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.4/tibcorequestheaders.raml

mediaType: 
  - application/json
  - application/xml

securitySchemes:
  etb_oauth_2_0: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

resourceTypes:
  library: libraries/collection.raml
uses:
  cancelSchedule-lib: libraries/cancelSchedule-library.raml
  createRelationPQR-lib: libraries/createRelationPQR-lib.raml

/operations:
  /v1:
    /pqr:
      /details:
        post:
          displayName: Consult PQR
          description: Service to consult PQRs
          securedBy: [etb_oauth_2_0]
          is:
            - tibcoHeaders
          body:
            application/json:
              type: !include dataTypes/request/post-consultPQR.raml
          responses:
            200:
              body:
                application/json:
                  type: !include dataTypes/response/post-consultPQR200.raml
      /compensations:
        get:
          displayName: Query Compensations
          description: Gets compensation from a pqr
          securedBy: [etb_oauth_2_0]
          is:
            - tibcoHeaders
          queryParameters:
            Tipo_Documento:
              type: string
              required: false
              example: "CC"
            Numero_Documento:
              type: string
              required: false
              example: "1033817571"
            Cuenta_Facturacion:
              type: string
              required: false
              example: "15052898260"
          responses:
            200:
              body:
                application/json:
                  type: !include dataTypes/response/getPqrCompensation.raml
                  example: !include examples/response/getPqrCompensation.json
    /schedule:
      patch:
        securedBy: [etb_oauth_2_0]
        is:
        - tibcoHeaders
        body:
          application/json:
            example: !include examples/request/updateSchedule.json
        responses:
          201:
            body:
              application/json:
                example: !include examples/response/updateSchedule.json               
                 
    /connections:
      /{misdn}:
        uriParameters:
          misdn:
            type: number
            example: 573058659690
        put:
          securedBy: [etb_oauth_2_0] 
          is: [tibcoHeaders]
          displayName: Suspensions Reconnections
          description: Suspenciones y Reconexiones de servicios
          queryParameters:
            actionRS:
              type: string
              example: "R"
            recursos:
              type: string
              example: "NA"
          responses:
            200:
              body:
                application/json:
                  type: !include dataTypes/response/suspensionsReconnections.raml
    /orders:
      /{order_id}:
        /delivery:
          uriParameters:
            order_id:
              example: "MDM-MOV-2306254-OL-1"
          post:
            securedBy: [etb_oauth_2_0]
            displayName: Create Dispatch Order
            description: Create Dispatch Order
            is:
              - tibcoHeaders
            body:
              application/json:
                type: !include dataTypes/request/createDispatchOrder.raml
                example: !include examples/request/createDispatchOrderExample.raml
            responses:
              200:
                body:
                  application/json:
                    type: !include dataTypes/response/createDispatchOrder200.raml
              400:
                body:
                  application/json:
                    type: !include dataTypes/response/createDispatchOrder400.raml             
              500:
                body:
                  application/json:
                    type: !include dataTypes/response/createDispatchOrder500.raml
        /characteristics:
          uriParameters:
            order_id:
              type: string
              example: "MDM-FIBRA-000558582"
          post:
            is:
              - tibcoHeaders
            securedBy: [etb_oauth_2_0]
            displayName: Update order characteristics
            description: Update the characteristics from an order
            body:
              application/json:
                type: !include dataTypes/request/updateOrderCharacteristics.raml
            responses:
              200:
                body:
                  application/json:
                    type: !include dataTypes/response/updateOrderCharacteristics.raml                    
    /logs:
      /audits:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoHeaders]
          displayName: Post of loggers
          description: Post new entry logs
          body:
            application/json:
              type: !include dataTypes/request/post-auditLogs.raml
          responses:
            201: 
              body:
                application/json:
                  type: !include dataTypes/response/post-auditLogs201.raml
      /spnpqr:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoHeaders]
          displayName: Post of logs PQR
          description: Post de logs PQR en soporte de primer nivel
          body:
            application/json:
              type: !include dataTypes/request/post-spnpqrLogs.raml
          responses:
            201: 
              body:
                application/json:
                  type: !include dataTypes/response/post-auditLogs201.raml
      /conversation:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoHeaders]
          displayName: Post of conversation logs
          description: Post of conversation logs
          body:
            application/json:
              type: !include dataTypes/request/post-conversationLogs.raml
          responses:
            201: 
              body:
                application/json:
                  type: !include dataTypes/response/post-auditLogs201.raml
      /suma:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoHeaders]
          displayName: Post of SUMA logs
          description: Post of SUMA logs
          body:
            application/json:
              type: !include dataTypes/request/post-sumaLogs.raml
          responses:
            201: 
              body:
                application/json:
                  type: !include dataTypes/response/post-auditLogs201.raml
      /convertibility:
        post:
          securedBy: [etb_oauth_2_0]
          is: [tibcoHeaders]
          displayName: Post of Convertibility logs
          description: Post of Convertibility logs
          body:
            application/json:
              type: !include dataTypes/request/post-convertibilityLogs.raml
          responses:
            201: 
              body:
                application/json:
                  type: !include dataTypes/response/post-auditLogs201.raml
    /materials:
      is:
        - tibcoHeaders
      put:
        securedBy: [etb_oauth_2_0]
        body:
          application/json:
            type: !include dataTypes/request/updateMaterials.raml
        responses:
          201:
            body:
              application/json:
                example: !include examples/response/updateMaterials.json
    /text-messages:
      post:
        securedBy: [etb_oauth_2_0]
        is:
          - tibcoHeaders
        body:
          application/json:
            type: !include dataTypes/request/sendTextMessageInput.raml
        responses:
          202:
            body:
              application/json:
                type: !include dataTypes/response/sendTextMessage202.raml
    /products:
      /orders:
        patch:
          securedBy: [etb_oauth_2_0] 
          is: [tibcoHeaders]
          displayName: Update SLF Services Status Intf
          description: Actualizar estado de servicio SLF
          body:
            application/json:
              type: !include dataTypes/request/updateSLFServicesStatusIntf.raml
          responses:
            200:
              body:
                application/json:
                  type: !include dataTypes/response/updateSLFServicesStatusIntfResponse200.raml                    
/fulfillment:
  /v1:
    /notifySFOrderBillingFinished:
      post:
        securedBy: [etb_oauth_2_0]
        is: [tibcoHeaders]
        displayName: Notification order billing finished
        description: Notification order billing finished
        body:
          application/xml:
            example: !include examples/request/notifySFOrderBillingFinished.xml
        responses:
          201:
            body:
              application/json:
                example: !include examples/response/notifySFOrderBillingFinished.json
          500:
            body:
              application/json:
                example: !include examples/response/notifySFOrderBillingFinishedError.json
    /incident:
      /{incidence_id}:
        /schedule:
          /{schedule_id}:
            patch:
              is:
                - tibcoHeaders
              securedBy: [etb_oauth_2_0]
              displayName: display name
              description: description
              body:
                application/json:
                  type: !include dataTypes/request/patch-updateSchedule.raml
              responses:
                201:
                  body:
                    application/json:
                      example: !include examples/response/updateScheduleResponseExample.raml
                500:
                  body:
                    application/json:
                      example: !include examples/response/updateScheduleStatus500ResponseExample.json
          /agenda/{agenda_id}:
            delete:
              is:
                - tibcoHeaders
              securedBy: [etb_oauth_2_0] 
              displayName: Cancel process rised due some incident
              description: Process responsible for canceling the ticket related with some incident.
              responses:
                200:
                  description: Response for the status 200 of the upgrade
                  body: 
                    application/xml:
                      example: !include examples/response/cancelScheduleResponse.json
        /vias:
          patch:
            is:
              - tibcoHeaders
            securedBy: [etb_oauth_2_0] 
            displayName: Update an incident path, into Remedy system.
            description: This method update an incident path.
            body:
              application/json:
                type: !include dataTypes/request/updateViasType.raml
                example:
                  !include examples/request/updateViasRequest.json
            responses:
              201:
                body:
                  application/json:
                    example: !include examples/response/updateViasResponseExample.raml
      /orders:
        patch:
          is:
            - tibcoHeaders
          securedBy: [etb_oauth_2_0]
          displayName: Update OT
          description: Actualizar ordenes de trabajo
          body:
            application/json:
              type: !include dataTypes/request/patch-updateOrder.raml
          responses:
            200:
              body:
                application/xml:
                  example: !include examples/response/updateEntIncidentStatusResponse.raml
            500:
              body:
                application/xml:
                  example: !include examples/response/updateEntIncidentErrorStatusResponse.raml
    /relation_pqr:
      post:
        securedBy: [etb_oauth_2_0] 
        is: [tibcoHeaders]
        displayName: Create relation between two people based on their incidents
        description: Based on input information, the method creates a relation between two registers and store that info into MDM
        body:
          application/json:
            type: createRelationPQR-lib.Envelope
            example:
              !include examples/request/createRelationPQRRequest.raml
        responses:
          201:
            body:
              application/json:
                example: !include examples/response/createRelationPQRResponse.json
    /tipologyRVC:
      patch:
        securedBy: [etb_oauth_2_0]
        is: [tibcoHeaders]
        body:
          application/json:
            type: !include dataTypes/request/patch-updateTipologyRVC.raml
        responses:
          200:
            body:
              application/json:
                example: !include examples/response/updateTipologyRVC.json
    /order_handling:
      /{order_id}:
        uriParameters:
          order_id:
            type: string
        /schedule:
          patch:
            securedBy: [etb_oauth_2_0] 
            is: [tibcoHeaders]
            displayName: Upgrade process
            description: Process that is responsible for updating the TOA Booklet Closing Status information.
            body:
              type: !include dataTypes/request/patch_orderHandling_Schedule.raml
            responses:
              200:
                description: Response for the status 200 of the upgrade
                body: 
                  application/json:
                    type: !include dataTypes/response/patch_orderHandling_Schedule_200.raml
              500:
                description: Response for the status 500 of the upgrade
                body:
                  application/json:
                    type: !include dataTypes/response/patch_orderHandling_Schedule_500.raml

/billing:
  /v1:  
    /portability:
      /compensations:
        patch:
          securedBy: [etb_oauth_2_0] 
          is:
            - tibcoHeaders
          body:
            application/json:
              type: !include dataTypes/request/patch-portability.raml
          responses:
            200:
              body:
                application/json:
                  type: !include dataTypes/response/patch-portability.raml
            400:
              body:
                application/json:
                  type: !include dataTypes/response/patch-portability400.raml
    /bills:
      get:
        securedBy: [etb_oauth_2_0]
        displayName: SAPBills
        description: Get SAP bills
        is: [tibcoHeaders]
        queryParameters:
          date:
            type: date-only
            example: 2022-08-01
        responses:
          200:
            body:
              application/json:
                type: !include dataTypes/response/bills_response200.raml
          500:
            body:
              application/json:
                type: !include dataTypes/response/bills_response500.raml                  
    /complaints:
      /{case-number}:
        /status:
          uriParameters:
            case-number:
              example: "02285387"
          patch:
            securedBy: [etb_oauth_2_0]
            is: [tibcoHeaders]
            displayName: Ajuste SAAW         
            body:
              application/json:
                type: !include dataTypes/request/ajusteSAAWInput.raml
            responses:
              200:
                body:
                  application/json:
                    type: !include dataTypes/response/ajusteSAAWResponse200.raml
              500:
                body: 
                  application/json:
                    type: !include dataTypes/response/ajusteSAAWResponse500.raml
          get: 
            displayName: ConsultaSAAW
            is:
              - tibcoHeaders
            securedBy: [etb_oauth_2_0]
            responses: 
              200:
                body: 
                  application/json:
                    type: !include dataTypes/response/consultaSAAWResponse200.raml
  