http:
  private:
    port: "8091"

mongoDb:
  host_list:
    host1: "VM-AZMONGOS03.etb.cloud"
    host2: "VM-AZMONGOS04.etb.cloud"
  port: "27030"
  database: "MDM"
  username: "Mule_mongo_prod"
  password: "Z*s985S8"
  collection-audits: "MDM_AUDITORIA_SERVICIOS"
  selectionTimeout: "60"
  socketTimeout: "30000"
  minPoolSize: "5"
  maxIdleTime: "30000"
  reconnect:
    frequency: "5000"
    attempts: "3"
      
  audits:
    database: "audits_mulesoft"
autodiscovery: "18058808"