#%RAML 1.0
title: payu-sapi-services
description: The following API will be in charge of create and retrive payment transaction
baseUri: payu-sapi-services-dev.us-e2.cloudhub.io
version: "v1"

protocols:
    - HTTP

uses:
    commonTypes: libraries/common-types.raml
    requestTypes: libraries/request-types.raml
    responseTypes: libraries/response-types.raml

/health-check:
    displayName: Health Check
    get:
        description: Get the current status of this API

/v1:
    /ping:
      get:
        description: check connection.                        
        responses:
          200:
            body:
              application/json:
                type: responseTypes.ping
                example: !include examples/responses/get-ping-response.json
                  
    /banks:
      get:
        description: Get the list of banks.                      
        responses:
          200:
            body:
              application/json:
                type: responseTypes.banks
                example: !include examples/responses/get-banks-response.json
    /transactions:
      post:
        description: Create payment transaction
        body:
          application/json:
            type: requestTypes.post-payment
            example: !include examples/requests/post-payment-request.json                        
        responses:
          200:
            body:
              application/json:
                type: responseTypes.post-payment-response
                example: !include examples/responses/post-payment-response.json
      /{id}:
        uriParameters:
          id:
            type: string
            example: "ee309c57-7e5d-4aeb-97f0-55864df820f1"
        get:
          description: Get payment by id transaction
          responses:
            200:
              body:
                application/json:
                  type: responseTypes.get-payment-transaction-response
                  example: !include examples/responses/get-payment-transaction-response.json