#%RAML 1.0 DataType
type: object
properties:
  WSResponseHeader: 
    type: object
    properties:
        System: 
          type: object
          properties:
            name: 
              type: string
              required: true
              example: "Mulesoft"
            correlationID: 
              type: string
              required: true
              example: "Mulesoft-20230228094859-659"
            processingServer: 
              type: string | nil
              required: true
              example: null
        Service: 
          type: object
          properties:
            status: 
              type: string
              required: true
              example: "OK"
            responseDate: 
              type: string
              required: true
              example: "2023-03-02T10:03:12.279112+00:00"
            processingServer: 
              type: string | nil
              required: true
              example: null
            statusDetail: 
              type: array
              items:
                type: object
                properties:
                  errorCode:
                    type: string
                    required: true
                    example: "OK_01"
                  errorDetailCode: 
                    type: string
                    required: true
                    example: "La solicitud fue exitosa"
                  errorMessage: 
                    type: string
                    required: true
                    example: "La solicitud Mulesoft-20230228094859-659 fue exitosa. Se generó el link de activación"
        Property: 
          type: array
          items:
          example: []
  WSResponseBody: 
    type: object
    properties:
      Url: 
        type: string
        required: true
        example: "http://microfrontsdev.portallteqa.p.azurewebsites.net///Home//ActivarRegistroMiETB?k=kGm+nsmc9xwnQj6S2wAIggg4XSz/nC6PH1tn16rI6Uf+ooQN79vCc8F5XphxXDVJBhjLOQzPCDBJEw/DEZXxTg==&Id=R9SUfS3lYZ4fPbAv2f5LntPU4tleN1NsKHhSZpPF+Dw=&From=R9SUfS3lYZ4zBCyruR/U7Q==&Canal=SmBy0j+31oI="
