#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: object
    properties:
      System:
        type: object
        properties:
          name:
            type: string
            example: MIETB
            required: false
          correlationID:
            type: string
            example: '{{correlationID}}'
            required: false
          processingServer:
            type: 'null'
            example: null
            required: false
      Service:
        type: object
        properties:
          status:
            type: string
            example: OK
            required: false
          responseDate:
            type: string
            example: '2025-06-13T09:24:36.7961517Z'
            required: false
          processingServer:
            type: 'null'
            example: null
            required: false
          statusDetail:
            type: array
            items:
              type: object
              properties:
                errorCode:
                  type: string
                  example: OK_01
                  required: false
                errorDetailCode:
                  type: string
                  example: Se consultaron las ciudades exitosamente
                  required: false
                errorMessage:
                  type: string
                  example: La solicitud {{correlationID}} fue exitosa
                  required: false
                errorMessageUser:
                  type: 'null'
                  example: null
                  required: false
      Property:
        type: array
        items: {}
  WSResponseBody:
    type: array
    items:
      type: object
      properties:
        City:
          type: string
          example: CHIGORODO
          required: false
        City_DANE:
          type: string
          example: '05172'
          required: false
        Cobertures:
          type: object
          properties:
            Coberture:
              type: boolean
              example: true
              required: false
            Delivery:
              type: array
              items:
                type: object
                properties:
                  Days_OL:
                    type: integer
                    example: 6
                    required: false
                  Hours_OL:
                    type: integer
                    example: 0
                    required: false
                  Type:
                    type: string
                    example: BASICA
                    required: false
            Operator:
              type: string
              example: DHL
              required: false
        Country:
          type: string
          example: Colombia
          required: false
        Country_ISO:
          type: string
          example: CO
          required: false
        Departament:
          type: string
          example: ANTIOQUIA
          required: false
        Department_DANE:
          type: string
          example: '05'
          required: false
