#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      MassiveFailure:
        type: object
        properties:
          Affectation:
            type: string
            example: Internet
            required: false
          CUN:
            type: string
            example: CUN12345
            required: false
          Description:
            type: string
            example: Falla masiva en la zona norte
            required: false
          Description_User:
            type: string
            example: Estamos trabajando para restablecer el servicio.
            required: false
          Description_Technical:
            type: string
            example: Corte de fibra óptica
            required: false
          End_Date:
            type: object
            properties:
              Date:
                type: string
                example: '2024-06-01T18:00:00Z'
                required: false
              Format_1:
                type: string
                example: 01/06
                required: false
              Format_2:
                type: string
                example: 01/06/2024
                required: false
              Format_3:
                type: string
                example: 01/06/2024 18:00:00
                required: false
              Format_4:
                type: string
                example: 01/06/2024 06:00:00 PM
                required: false
          Id:
            type: string
            example: PQR98765
            required: false
          Incident:
            type: string
            example: INC123456
            required: false
          Priority:
            type: integer
            example: 1
            required: false
          Product:
            type: string
            example: INTERNET
            required: false
          Start_Date:
            type: object
            properties:
              Date:
                type: string
                example: '2024-06-01T10:00:00Z'
                required: false
              Format_1:
                type: string
                example: 01/06
                required: false
              Format_2:
                type: string
                example: 01/06/2024
                required: false
              Format_3:
                type: string
                example: 01/06/2024 10:00:00
                required: false
              Format_4:
                type: string
                example: 01/06/2024 10:00:00 AM
                required: false
          TES:
            type: integer
            example: 120
            required: false
