#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: array
    items:
      type: object
      properties:
        Coverage:
          type: boolean
          example: false
          required: false
        Departament:
          type: string
          example: ANTIOQUIA
          required: false
        Departament_DANE:
          type: string
          example: '05'
          required: false
