#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Available_Coin:
        type: string
        example: string
        required: false
      Available_Coin_Value:
        type: string
        example: number
        required: false
      Promotion_Coin:
        type: string
        example: string
        required: false
      Promotion_Coin_Value:
        type: string
        example: number
        required: false
      Detailed:
        type: object
        properties:
          Detail:
            type: array
            items:
              type: object
              properties:
                Section_Name:
                  type: string
                  example: string
                  required: false
                Boxs:
                  type: array
                  items:
                    type: object
                    properties:
                      Box_Name:
                        type: string
                        example: string
                        required: false
                      Group_Name:
                        type: string
                        example: string
                        required: false
                      Unity_Type:
                        type: string
                        example: string
                        required: false
                      Available:
                        type: string
                        example: string
                        required: false
                      Consume:
                        type: string
                        example: string
                        required: false
                      Provisioned:
                        type: string
                        example: string
                        required: false
                      Offers:
                        type: array
                        items:
                          type: object
                          properties:
                            Offer_Name:
                              type: string
                              example: string
                              required: false
                            Available:
                              type: string
                              example: string
                              required: false
                            Consumed:
                              type: string
                              example: string
                              required: false
                            Provisioned:
                              type: string
                              example: string
                              required: false
                            Expiration_Date:
                              type: string
                              example: string
                              required: false
      Resume:
        type: object
        properties:
          Resource:
            type: array
            items:
              type: object
              properties:
                Name:
                  type: string
                  example: string
                  required: false
                Available:
                  type: string
                  example: string
                  required: false
                Consumed:
                  type: string
                  example: string
                  required: false
                Provisioned:
                  type: string
                  example: string
                  required: false
                Expiration_Date:
                  type: string
                  example: string
                  required: false
