#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Billing_Account:
        type: string
        example: string
        required: false
      Collection_Hours:
        type: object
        properties:
          Value:
            type: integer
            example: 0
            required: false
          Value_Str:
            type: string
            example: string
            required: false
      Default_Interest:
        type: object
        properties:
          Value:
            type: integer
            example: 0
            required: false
          Value_Str:
            type: string
            example: string
            required: false
      Link:
        type: string
        example: string
        required: false
      Pay_Point:
        type: string
        example: string
        required: false
      Pending_Balance:
        type: object
        properties:
          Value:
            type: integer
            example: 0
            required: false
          Value_Str:
            type: string
            example: string
            required: false

