#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:   
      Invoices:
        type: array
        items:
          type: object
          properties:
            Billing_Number:
              type: string
              example: '5879271031188'
              required: false
            Billing_Date:
              type: date-only
              example: '2024-12-01'
              required: false
            Due_Date:
              type: date-only
              example: '2024-12-15'
              required: false
            Status:
              type: string
              example: Pendiente
              required: false
            Value:
              type: object
              properties:
                Amount:
                  type: integer
                  example: 150000
                  required: false
                Currency:
                  type: string
                  example: COP
                  required: false
                Formatted:
                  type: string
                  example: $ 150,000
                  required: false
            Payments:
              type: array
              items:
                type: object
                properties:
                  Payment_Date:
                    type: date-only
                    example: '2024-11-10'
                    required: false
                  Amount:
                    type: integer
                    example: 145000
                    required: false
                  Type:
                    type: string
                    example: Efectivo
                    required: false
            Adjustments:
              type: array
              items: {}
