#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      BusinessDays:
        type: array
        items:
          type: object
          properties:
            Date:
              type: string
              example: '2025-06-13T21:22:59.3900454+00:00'
              required: false
            Day:
              type: string
              example: '13'
              required: false
            Month:
              type: string
              example: '06'
              required: false
            Month_Str:
              type: string
              example: Jun
              required: false
            Year:
              type: string
              example: '2025'
              required: false

