#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: web
            required: false
          Id_Device:
            type: string
            example: ''
            required: false
          SO:
            type: string
            example: ''
            required: false
          IP_Address:
            type: string
            example: ''
            required: false
          WhatsApp_Phone_Number:
            type: string
            example: ''
            required: false
      Causal:
        type: string
        example: FALLA_TECNICA
        required: false
      Contact_Document_Number:
        type: string
        example: '12345678'
        required: false
      Contact_Document_Type:
        type: string
        example: CC
        required: false
      Creation_Date:
        type: datetime-only
        example: '2024-12-19T10:30:00'
        required: false
      CUN:
        type: string
        example: CUN-2024-001234
        required: false
      Description:
        type: string
        example: No tengo conexión a internet
        required: false
      Document_Number:
        type: string
        example: '87654321'
        required: false
      Document_Type:
        type: string
        example: CC
        required: false
      Id:
        type: string
        example: PQR-2024-001234
        required: false
      Is_Son:
        type: boolean
        example: false
        required: false
      Kind:
        type: string
        example: INTERNET
        required: false
      Phone:
        type: string
        example: '3057000421'
        required: false
      Reason:
        type: string
        example: FALLA TECNICA
        required: false
      Solution_Date:
        type: string
        example: ''
        required: false
      State:
        type: string
        example: ABIERTA
        required: false
      Symptom:
        type: string
        example: SIN_CONEXION
        required: false
      Type:
        type: string
        example: FALLA_TECNICA
        required: false
