#%RAML 1.0 DataType
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: any
    required: true
    example: "pIkAfpKLrybXiO0RPqT1+m9S5J1KgMMp5wL3ZoBaUKC8qc8uM/snlMfiWo53xGR6vxXd2r47DieBJQ5K5uyTjzvPyu/ANBj00JclcYhxOHrh6vO2NmqF6OUFAwYx1AOf"