#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      PQRs:
        type: array
        items:
          type: object
          properties:
            Agenda:
              type: string
              example: ''
              required: false
            Agendas:
              type: string
              example: ''
              required: false
            Activities:
              type: array
              items:
                type: object
                properties:
                  Assigned_User:
                    type: string
                    example: laurros1
                    required: false
                  Creation_User:
                    type: string
                    example: laurros1
                    required: false
                  Description:
                    type: string
                    example: ''
                    required: false
                  Expiration_Date:
                    type: object
                    properties:
                      Date:
                        type: string | datetime
                        example: '2025-08-02T15:12:32Z'
                        required: false
                      Format_1:
                        type: string
                        example: 02/08
                        required: false
                      Format_2:
                        type: string
                        example: 02/08/2025
                        required: false
                      Format_3:
                        type: string
                        example: 02/08/2025 15:12:32
                        required: false
                      Format_4:
                        type: string
                        example: 02/08/2025 03:12:32 PM
                        required: false
                      Day:
                        type: object
                        properties:
                          Format_1:
                            type: string
                            example: '02'
                            required: false
                          Format_2:
                            type: string
                            example: Sáb.
                            required: false
                          Format_3:
                            type: string
                            example: Sábado
                            required: false
                      Month:
                        type: object
                        properties:
                          Format_1:
                            type: string
                            example: '08'
                            required: false
                          Format_2:
                            type: string
                            example: Ago.
                            required: false
                          Format_3:
                            type: string
                            example: Agosto
                            required: false
                      Year:
                        type: object
                        properties:
                          Format_1:
                            type: string
                            example: '25'
                            required: false
                          Format_2:
                            type: string
                            example: '2025'
                            required: false
                          Format_3:
                            type: string
                            example: '02025'
                            required: false
                      Hour:
                        type: object
                        properties:
                          Format_1:
                            type: time-only
                            example: '15:12:32'
                            required: false
                          Format_2:
                            type: string
                            example: 03:12:32 PM
                            required: false
                          Format_3:
                            type: string
                            example: '15'
                            required: false
                          Format_4:
                            type: string
                            example: 03 PM
                            required: false
                          Format_5:
                            type: string
                            example: '12'
                            required: false
                          Format_6:
                            type: string
                            example: '32'
                            required: false
                  Id:
                    type: string
                    example: MDM-PQR-ACT-108277393
                    required: false
                  Management:
                    type: string
                    example: MIXTA
                    required: false
                  Management_Description:
                    type: string
                    example: PENDIENTE ENTREGA
                    required: false
                  Name:
                    type: string
                    example: INSTANCIA ADMINISTRATIVA
                    required: false
                  Start_Date:
                    type: object
                    properties:
                      Date:
                        type: string | datetime
                        example: '2025-07-28T15:12:32Z'
                        required: false
                      Format_1:
                        type: string
                        example: 28/07
                        required: false
                      Format_2:
                        type: string
                        example: 28/07/2025
                        required: false
                      Format_3:
                        type: string
                        example: 28/07/2025 15:12:32
                        required: false
                      Format_4:
                        type: string
                        example: 28/07/2025 03:12:32 PM
                        required: false
                      Day:
                        type: object
                        properties:
                          Format_1:
                            type: string
                            example: '28'
                            required: false
                          Format_2:
                            type: string
                            example: Lun.
                            required: false
                          Format_3:
                            type: string
                            example: Lunes
                            required: false
                      Month:
                        type: object
                        properties:
                          Format_1:
                            type: string
                            example: '07'
                            required: false
                          Format_2:
                            type: string
                            example: Jul.
                            required: false
                          Format_3:
                            type: string
                            example: Julio
                            required: false
                      Year:
                        type: object
                        properties:
                          Format_1:
                            type: string
                            example: '25'
                            required: false
                          Format_2:
                            type: string
                            example: '2025'
                            required: false
                          Format_3:
                            type: string
                            example: '02025'
                            required: false
                      Hour:
                        type: object
                        properties:
                          Format_1:
                            type: time-only
                            example: '15:12:32'
                            required: false
                          Format_2:
                            type: string
                            example: 03:12:32 PM
                            required: false
                          Format_3:
                            type: string
                            example: '15'
                            required: false
                          Format_4:
                            type: string
                            example: 03 PM
                            required: false
                          Format_5:
                            type: string
                            example: '12'
                            required: false
                          Format_6:
                            type: string
                            example: '32'
                            required: false
                  State:
                    type: string
                    example: Cerrado
                    required: false
            Assigned_User:
              type: string
              example: laurros1
              required: false
            Billing_Account:
              type: string
              example: ''
              required: false
            Characteristics:
              type: array
              items:
                type: object
                properties:
                  Action:
                    type: string
                    example: ''
                    required: false
                  Name:
                    type: string
                    example: DescripcionTipologia
                    required: false
                  Value:
                    type: string
                    example: >-
                      Información con la  gestión y requisitos del trámite de 
                      cancelación de los servicios suscritos
                    required: false
            Contact_Document_Number:
              type: string
              example: '52530339'
              required: false
            Contact_Document_Type:
              type: string
              example: CC
              required: false
            Creation_Date:
              type: object
              properties:
                Date:
                  type: string
                  example: '2025-07-28T15:12:34Z'
                  required: false
                Format_1:
                  type: string
                  example: 28/07
                  required: false
                Format_2:
                  type: string
                  example: 28/07/2025
                  required: false
                Format_3:
                  type: string
                  example: 28/07/2025 15:12:34
                  required: false
                Format_4:
                  type: string
                  example: 28/07/2025 03:12:34 PM
                  required: false
                Day:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '28'
                      required: false
                    Format_2:
                      type: string
                      example: Lun.
                      required: false
                    Format_3:
                      type: string
                      example: Lunes
                      required: false
                Month:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '07'
                      required: false
                    Format_2:
                      type: string
                      example: Jul.
                      required: false
                    Format_3:
                      type: string
                      example: Julio
                      required: false
                Year:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '25'
                      required: false
                    Format_2:
                      type: string
                      example: '2025'
                      required: false
                    Format_3:
                      type: string
                      example: '02025'
                      required: false
                Hour:
                  type: object
                  properties:
                    Format_1:
                      type: time-only
                      example: '15:12:34'
                      required: false
                    Format_2:
                      type: string
                      example: 03:12:34 PM
                      required: false
                    Format_3:
                      type: string
                      example: '15'
                      required: false
                    Format_4:
                      type: string
                      example: 03 PM
                      required: false
                    Format_5:
                      type: string
                      example: '12'
                      required: false
                    Format_6:
                      type: string
                      example: '34'
                      required: false
            Creation_User:
              type: string
              example: laurros1
              required: false
            Is_Agenda_Suspended:
              type: boolean
              example: false
              required: false
            Is_Son:
              type: boolean
              example: false
              required: false
            Notification_Medium:
              type: string
              example: TELEFONICO
              required: false
            Modification_Date:
              type: object
              properties:
                Date:
                  type: datetime
                  example: '2025-07-28T15:17:12.542Z'
                  required: false
                Format_1:
                  type: string
                  example: 28/07
                  required: false
                Format_2:
                  type: string
                  example: 28/07/2025
                  required: false
                Format_3:
                  type: string
                  example: 28/07/2025 15:17:12
                  required: false
                Format_4:
                  type: string
                  example: 28/07/2025 03:17:12 PM
                  required: false
                Day:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '28'
                      required: false
                    Format_2:
                      type: string
                      example: Lun.
                      required: false
                    Format_3:
                      type: string
                      example: Lunes
                      required: false
                Month:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '07'
                      required: false
                    Format_2:
                      type: string
                      example: Jul.
                      required: false
                    Format_3:
                      type: string
                      example: Julio
                      required: false
                Year:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '25'
                      required: false
                    Format_2:
                      type: string
                      example: '2025'
                      required: false
                    Format_3:
                      type: string
                      example: '02025'
                      required: false
                Hour:
                  type: object
                  properties:
                    Format_1:
                      type: time-only
                      example: '15:17:12'
                      required: false
                    Format_2:
                      type: string
                      example: 03:17:12 PM
                      required: false
                    Format_3:
                      type: string
                      example: '15'
                      required: false
                    Format_4:
                      type: string
                      example: 03 PM
                      required: false
                    Format_5:
                      type: string
                      example: '17'
                      required: false
                    Format_6:
                      type: string
                      example: '12'
                      required: false
            Order:
              type: string
              example: ''
              required: false
            Radication_Date:
              type: object
              properties:
                Date:
                  type: string
                  example: '2025-07-28T15:10:07Z'
                  required: false
                Format_1:
                  type: string
                  example: 28/07
                  required: false
                Format_2:
                  type: string
                  example: 28/07/2025
                  required: false
                Format_3:
                  type: string
                  example: 28/07/2025 15:10:07
                  required: false
                Format_4:
                  type: string
                  example: 28/07/2025 03:10:07 PM
                  required: false
                Day:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '28'
                      required: false
                    Format_2:
                      type: string
                      example: Lun.
                      required: false
                    Format_3:
                      type: string
                      example: Lunes
                      required: false
                Month:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '07'
                      required: false
                    Format_2:
                      type: string
                      example: Jul.
                      required: false
                    Format_3:
                      type: string
                      example: Julio
                      required: false
                Year:
                  type: object
                  properties:
                    Format_1:
                      type: string
                      example: '25'
                      required: false
                    Format_2:
                      type: string
                      example: '2025'
                      required: false
                    Format_3:
                      type: string
                      example: '02025'
                      required: false
                Hour:
                  type: object
                  properties:
                    Format_1:
                      type: time-only
                      example: '15:10:07'
                      required: false
                    Format_2:
                      type: string
                      example: 03:10:07 PM
                      required: false
                    Format_3:
                      type: string
                      example: '15'
                      required: false
                    Format_4:
                      type: string
                      example: 03 PM
                      required: false
                    Format_5:
                      type: string
                      example: '10'
                      required: false
                    Format_6:
                      type: string
                      example: '07'
                      required: false
            Reception_Medium:
              type: string
              example: LÍNEA TELEFÓNICA
              required: false
            Service:
              type: string
              example: ''
              required: false
            Sub_Channel:
              type: string
              example: TELEFÓNICO
              required: false
            Suspension_Detail:
              type: string
              example: ''
              required: false
            Solution_Date:
              type: string
              example: ''
              required: false
            Billing__Account:
              type: string
              example: '12054363574'
              required: false
            CUN:
              type: string
              example: ''
              required: false
            CUN_Massive_Failure:
              type: string
              example: ''
              required: false
            CUN_Related:
              type: string
              example: ''
              required: false
            Customer:
              type: object
              properties:
                ATDP:
                  type: string
                  example: ''
                  required: false
                Birthday:
                  type: string
                  example: ''
                  required: false
                Business:
                  type: string
                  example: ''
                  required: false
                Collection_Communications:
                  type: string
                  example: ''
                  required: false
                Document_Number:
                  type: string
                  example: '52530339'
                  required: false
                Document_Type:
                  type: string
                  example: CC
                  required: false
                Email:
                  type: string
                  example: ''
                  required: false
                Mobile_Phone:
                  type: string
                  example: ''
                  required: false
                Mobile_Phone2:
                  type: string
                  example: ''
                  required: false
                Name:
                  type: object
                  properties:
                    Complete_Name:
                      type: string
                      example: OLGA CAROLINA CASTILLO ROMERO
                      required: false
                    First_Name:
                      type: string
                      example: OLGA
                      required: false
                    First_Surname:
                      type: string
                      example: CASTILLO
                      required: false
                    Names:
                      type: string
                      example: OLGA CAROLINA
                      required: false
                    Second_Name:
                      type: string
                      example: CAROLINA
                      required: false
                    Second_Surname:
                      type: string
                      example: ROMERO
                      required: false
                    Surnames:
                      type: string
                      example: CASTILLO ROMERO
                      required: false
                Segmentation:
                  type: string
                  example: ''
                  required: false
                Validation_Code:
                  type: string
                  example: ''
                  required: false
            Description:
              type: string
              example: "NOMBRE: CAROLINA\nCEDULA: 52530339\nTEL: 3124853341 \_\nCORREO: condorcas@hotmail.com \_\nDIRRECION: CL 74C SUR 12 20\nLINEA: SR-30593591 \t\nCUENTA: 12054363574\nMOTIVO: DESEA CANCELAR Y BA  A REALIZAR LA CARTA PARA QUE NO LE COBREN EL SERVICIO POR FALLA MASIVA YA QUE AL DIA DE HOY AUN NO SE LE SOLUCIONA LA FALLA \n"
              required: false
            Id:
              type: string
              example: MDM-PQR-52226815
              required: false
            Id_Remedy:
              type: string
              example: ''
              required: false
            Is_Young_Fail:
              type: boolean
              example: false
              required: false
            Phone:
              type: string
              example: ''
              required: false
            Response:
              type: string
              example: ''
              required: false
            Service_Account:
              type: string
              example: CS-1375757
              required: false
            Service_Id:
              type: string
              example: CS-1375757
              required: false
            Solution:
              type: string
              example: >-
                CLIENTE INDIDICA QUE SE VA  HACERCAR A UN PUNTO HACER EL
                TRAMITE 
              required: false
            State:
              type: string
              example: Resuelto
              required: false
            State_Technical:
              type: string
              example: Cerrado
              required: false
            Typology:
              type: object
              properties:
                Causal:
                  type: string
                  example: REQUISITOS Y ESTADO DEL TRAMITE
                  required: false
                Class:
                  type: string
                  example: PETICION
                  required: false
                CUN:
                  type: boolean
                  example: false
                  required: false
                Extension:
                  type: object
                  properties:
                    Close_Type:
                      type: string
                      example: ACCEDE
                      required: false
                    Notification_Medium:
                      type: string
                      example: TELEFONICO
                      required: false
                    Operator:
                      type: string
                      example: ETB S.A. ESP
                      required: false
                    Operator_LSP:
                      type: string
                      example: RECEPCIÓN
                      required: false
                    Reception_Medium:
                      type: string
                      example: LÍNEA TELEFÓNICA
                      required: false
                Product:
                  type: string
                  example: PAQUETE
                  required: false
                Reason:
                  type: string
                  example: INFORMACION Y/O DOCUMENTACION
                  required: false
                Remedy:
                  type: boolean
                  example: false
                  required: false
                Symptom:
                  type: string
                  example: CANCELACIÓN
                  required: false
                Technology:
                  type: string
                  example: FTTC
                  required: false
                Type:
                  type: string
                  example: PRODUCTO
                  required: false
                Version:
                  type: string
                  example: '31'
                  required: false
