#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Diagnostic:
        type: object
        properties:
          ONT_On:
            type: boolean
            example: true
            required: false
          Poor_Connection:
            type: boolean
            example: false
            required: false
          Speed_Fault:
            type: boolean
            example: false
            required: false
      Massive_Failure:
        type: object
        properties:
          End_Date:
            type: object
            properties:
              Date:
                type: string
                example: '2025-08-19T23:52:57.427+00:00'
                required: false
              Format_1:
                type: string
                example: 19/08
                required: false
              Format_2:
                type: string
                example: 19/08/2025
                required: false
              Format_3:
                type: string
                example: 19/08/2025 23:52:57
                required: false
              Format_4:
                type: string
                example: 19/08/2025 11:52:57 PM
                required: false
              Day:
                type: object
                properties:
                  Format_1:
                    type: string
                    example: '19'
                    required: false
                  Format_2:
                    type: string
                    example: Mar.
                    required: false
                  Format_3:
                    type: string
                    example: Martes
                    required: false
              Month:
                type: object
                properties:
                  Format_1:
                    type: string
                    example: '08'
                    required: false
                  Format_2:
                    type: string
                    example: Ago.
                    required: false
                  Format_3:
                    type: string
                    example: Agosto
                    required: false
              Year:
                type: object
                properties:
                  Format_1:
                    type: string
                    example: '25'
                    required: false
                  Format_2:
                    type: string
                    example: '2025'
                    required: false
                  Format_3:
                    type: string
                    example: '02025'
                    required: false
              Hour:
                type: object
                properties:
                  Format_1:
                    type: time-only
                    example: '23:52:57'
                    required: false
                  Format_2:
                    type: string
                    example: 11:52:57 PM
                    required: false
                  Format_3:
                    type: string
                    example: '23'
                    required: false
                  Format_4:
                    type: string
                    example: 11 PM
                    required: false
                  Format_5:
                    type: string
                    example: '52'
                    required: false
                  Format_6:
                    type: string
                    example: '57'
                    required: false
          Expected_Solution_Time:
            type: integer
            example: 6
            required: false
          Priority:
            type: integer
            example: 4
            required: false
          Product:
            type: string
            example: INTERNET
            required: false
          Num_PQR:
            type: string
            example: MDM-PQR-4163009
            required: false
          Start_Date:
            type: object
            properties:
              Date:
                type: string
                example: '2025-08-19T17:52:57.427+00:00'
                required: false
              Format_1:
                type: string
                example: 19/08
                required: false
              Format_2:
                type: string
                example: 19/08/2025
                required: false
              Format_3:
                type: string
                example: 19/08/2025 17:52:57
                required: false
              Format_4:
                type: string
                example: 19/08/2025 05:52:57 PM
                required: false
              Day:
                type: object
                properties:
                  Format_1:
                    type: string
                    example: '19'
                    required: false
                  Format_2:
                    type: string
                    example: Mar.
                    required: false
                  Format_3:
                    type: string
                    example: Martes
                    required: false
              Month:
                type: object
                properties:
                  Format_1:
                    type: string
                    example: '08'
                    required: false
                  Format_2:
                    type: string
                    example: Ago.
                    required: false
                  Format_3:
                    type: string
                    example: Agosto
                    required: false
              Year:
                type: object
                properties:
                  Format_1:
                    type: string
                    example: '25'
                    required: false
                  Format_2:
                    type: string
                    example: '2025'
                    required: false
                  Format_3:
                    type: string
                    example: '02025'
                    required: false
              Hour:
                type: object
                properties:
                  Format_1:
                    type: time-only
                    example: '17:52:57'
                    required: false
                  Format_2:
                    type: string
                    example: 05:52:57 PM
                    required: false
                  Format_3:
                    type: string
                    example: '17'
                    required: false
                  Format_4:
                    type: string
                    example: 05 PM
                    required: false
                  Format_5:
                    type: string
                    example: '52'
                    required: false
                  Format_6:
                    type: string
                    example: '57'
                    required: false
      Semaphore:
        type: object
        properties:
          Attenuation:
            type: string
            example: ''
            required: false
          Modem:
            type: string
            example: Verde
            required: false
          Noise:
            type: string
            example: ''
            required: false
          Potency:
            type: string
            example: Verde
            required: false
