#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Service:
        type: object
        properties:
          Billing_Account:
            type: string
            example: '100123456789'
            required: false
          Phone:
            type: string
            example: '6018009578'
            required: false
          Plan:
            type: string
            example: FIBRA_300_SIMETRICO
            required: false
          Service_Account:
            type: string
            example: SA-100123456789
            required: false
          Technology:
            type: string
            example: FTTH
            required: false
      Equipments:
        type: array
        items:
          type: object
          properties:
            ACS_Model:
              type: string
              example: ALCL_BGW320
              required: false
            Brand:
              type: string
              example: ALCATEL
              required: false
            Firmware:
              type: string
              example: 3.2.1.45
              required: false
            Is_Dual:
              type: boolean
              example: true
              required: false
            MAC:
              type: string
              example: 00:1A:2B:3C:4D:5E
              required: false
            Model:
              type: string
              example: BGW320-500
              required: false
            Networks:
              type: array
              items:
                type: object
                properties:
                  ACS_Model:
                    type: string
                    example: WIFI_BGW320_2G
                    required: false
                  Dual:
                    type: boolean
                    example: false
                    required: false
                  Firmware:
                    type: string
                    example: 3.2.1.45
                    required: false
                  Is_Available_Set_Network_Name:
                    type: boolean
                    example: true
                    required: false
                  Is_Available_Set_Network_Password:
                    type: boolean
                    example: true
                    required: false
                  Is_Available_Set_Network_Wifi:
                    type: boolean
                    example: true
                    required: false
                  Network_Name:
                    type: string
                    example: ETB_WiFi_2.4GHz
                    required: false
                  Network_Password:
                    type: string
                    example: MiClaveSegura2024
                    required: false
                  Network_Type:
                    type: string
                    example: '2.4'
                    required: false
                  Network_Status:
                    type: string
                    example: Encendido
                    required: false
            Serial:
              type: string
              example: ALCLB545275C
              required: false
            Status:
              type: string
              example: Encendido
              required: false
            Type:
              type: string
              example: ONT
              required: false
            Type_Modem:
              type: string
              example: Modem
              required: false

