#%RAML 1.0 Library
uses:
  producto: productUpdateRecursive-library.raml
types:
  syncProduct:
    type: object
    properties:  
      ordenOM:
        type: string
        required: true
        minLength: 1
        example: OR-12321
      fechaProcesamiento:
        type: string
        required: true
        minLength: 1
        example: 11/29/2021 10:31:19 AM
      identificador:
        type: string
        required: true
        minLength: 1
        example: OC-1438626
      tipoSolicitud:
        type: string
        required: true
        minLength: 1
        example: VIABILIDAD
      parametros:
        type: array
        required: false
        items:
          properties:
            codigo:
              type: string
              required: true
              minLength: 1
              example: Atttr_numeroIMEI
            nombre:
              type: string
              required: true
              minLength: 1
              example: Número de IMEI
            valor:
              type: string
              required: false
              example: "98513324306"
            codigoAccion:
              type: string
              required: false
              example: Add
      productos:
        type: producto.productsProvisioningType []
        required: false