#%RAML 1.0 DataType
properties:
  status:
    type: string
    example: "400"
  code:
    type: string
    example: "BAD_REQUEST"
  message:
    properties:
      message:
        type: string
        example: "HTTP GET on resource 'http://{url-api}/mongo/v1/pqrs' failed: bad request (400)."
  messageServer:
    properties:
      codigo:
        type: string
        example: "400"
      titulo:
        type: string
        example: PQR no fue encontrada
      detalle:
        type: string
        example: "Al consultar la PQR no fue encontrada"
  cause:
    type: array
    items:
      properties:
        origin:
          type: string
          example: "mietb-xapi-services"
        message:
          type: string
          example: "org.mule.extension.http.api.request.validator.ResponseValidatorTypedException"
        
  
      
             