#%RAML 1.0 DataType
properties:
  usuario:
    type: object
    properties:
      nombre:
        type: string
      usuarioPadre:
        type: string
      usuarioHijo:
        type: string
      estado:
        type: boolean
      servicios:
        type: array
        items:
          properties:
            cuenta:
              type: string
            facturas:
              type: boolean
            estado:
              type: boolean

example: !include ../../examples/responses/get-multiusuario-adv.json