#%RAML 1.0 DataType
properties:
  Identification?:
    type: !include IdentificationType.raml
  LineOne?: string
  CityName?: string
  StateName?: string
  CountryCode?: string
  CountryName?: string
  GisID?: string
  Latitude?: string
  Longitude?: string
  CityCode?: string
  StateCode?: string
  PurposeCode?: string
  Reference?: string
  Technology?:
    type: !include TechnologyType.raml
  DaneCode?: string
  Postcode?: string
  GeoGroup?: string