#%RAML 1.0 DataType
properties:
  ItemIdentification:
    type: !include IdentificationType.raml
  Name: string
  ServiceIndicator: boolean
  TypeCode: string
  NetworkIndicator: boolean
  PrimaryClassificationCode: string
  ExternalServiceId?: string