#%RAML 1.0 DataType
properties:
  OrderSumary:
    type: object
    properties:
      Id: string
      Key:
        type: object
        properties:
          ID: string
      Specification:
        type: object
        properties:
          Cartridge:
            type: object
            properties:
              Name: string
              Version: string
          Type: string
          Source: string
      State: string
      Reference: string
      CreatedDate: datetime
      Priority: string