#%RAML 1.0 DataType
properties:
  Identification:
    type: !include IdentificationType.raml
  OrderQuantity: string
  ServiceActionCode: string
  FulfilmentModeCode: string
  ParentSalesOrderLineIdentification:
    type: !include IdentificationType.raml
  RootParentSalesOrderLineIdentification:
    type: !include IdentificationType.raml
  StatusCode: string
  ServiceAddress:
    type: !include AddressType.raml
  ItemReference:
    type: !include ItemReferenceType.raml
  SalesOrderSchedule:
    type: !include SalesOrderScheduleType.raml
  OwnerPartyReference:
    type: !include IdentificationType.raml
  ScheduleOrderIndicator: string
  OrderSubType: string
  SignedDocumentsIndicator: string
  StartDateTime?: string
  Parameter?:
    type: !include ParameterType.raml
  RatePlan?:
    type: !include RatePlanType.raml
  AltKey?[]:
    type: !include AltKeyType.raml
  Discounts?:
    type: !include DiscountsType.raml
