#%RAML 1.0 DataType
type: object
properties:
  canalDifusion?: string
  tipoNotificacion?: string
  nombreObjeto?: string
  nombreLista?: string
  atributos?:
    type: array
    items:
      type: object
      properties:
        nombre?: string
        valor?: string
  envioSalesforce?: string