#%RAML 1.0 DataType
properties:
  id_tarea_remedy:
    type: string
    required: true
    example: ""
  estado_tarea_remedy:
    type: string | nil
    required: false
    example: ""
  usuario_remedy:
    type: string | nil
    required: false
    example: ""
  tipo_solicitud:
    type: string
    required: true
    example: ""
  tipo_actividad:
    type: string
    required: true
    example: ""
  zona_agenda:
    type: string
    required: true
    example: ""
  producto:
    type: string | nil
    required: true
    example: ""
  Anillo:
    type: string
    required: true
    example: ""
  nemonico_equipo:
    type: string
    required: true
    example: ""
  cable:
    type: string
    required: true
    example: ""
  hilo:
    type: number
    required: true
    example: 0
  distancia:
    type: string
    required: true
    example: ""
  direccion:
    type: string
    required: true
    example: ""
  cord_x:
    type: string | nil
    required: false
    example: ""
  cord_y:
    type: string | nil
    required: false
    example: ""
  topologia:
    type: string
    required: true
    example: ""
  nombre_orden:
    type: string
    required: true
    example: ""
  fecha_agendamiento:
    type: date-only
    required: true
    example: "2024-02-02"
  zona:
    type: string 
    required: false
    example: ""
  franja:
    type: string
    required: true
    example: ""
  duracion:
    type: string | nil
    required: false
    example: ""
  nombre_cliente:
    type: string | nil
    required: false
    example: ""
  cedula:
    type: string | nil
    required: false
    example: ""
  email:
    type: string | nil
    required: false
    example: ""
  telefono:
    type: string | nil
    required: false
    example: ""
  ciudad:
    type: string | nil
    required: false
    example: ""
  departamento:
    type: string | nil
    required: false
    example: ""
  nombre_archivo:
    type: string | nil
    required: false
    example: ""
  tipo_archivo:
    type: string | nil
    required: false
    example: ""
  codificacion_archivo:
    type: string | nil
    required: false
    example: ""
  contenido_archivo:
    type: string | nil
    required: false
    example: ""