#%RAML 1.0 DataType 
type: object
properties:
  peticionConsultaDisponibilidad:
    type: object
    properties:
      encabezadoMensaje:
        type: object
        properties:
          idDisponibilidad:
            type: string
            example: ''
            required: false
          numeroOrdenAprovisionador:
            type: string
            example: ''
            required: false
          numeroRevision:
            type: string
            example: ''
            required: false
          tecnologiaETB:
            type: string
            example: ''
            required: false
          fechaPeticionOrden:
            type: string
            example: ''
            required: false
      detalleMensaje:
        type: object
        properties:
          modoConsulta:
            type: string
            example: ''
            required: false
          tipoDisponibilidad:
            type: string
            example: ''
            required: false
          orderItems:
            type: array
            items:
              type: object
              properties:
                idProductoTecnico:
                  type: string
                  example: ''
                  required: false
                idServicio:
                  type: string
                  example: ''
                  required: false
                idServicioPadre:
                  type: string
                  example: ''
                  required: false
                idServicioRaiz:
                  type: string
                  example: ''
                  required: false
                accion:
                  type: string
                  example: ''
                  required: false
                usoServicio:
                  type: string
                  example: ''
                  required: false
                idProductoTecnicoPadre:
                  type: string
                  example: ''
                  required: false
                idProductoTecnicoRaiz:
                  type: string
                  example: ''
                  required: false
                cuentaServicio:
                  type: object
                  properties:
                    idCuentaServicio:
                      type: string
                      example: ''
                      required: false
                    direccionServicio:
                      type: array
                      items:
                        type: object
                        properties:
                          codigoUnicoDireccion:
                            type: string
                            example: ''
                            required: false
                          codigoDepartamento:
                            type: string
                            example: ''
                            required: false
                          codigoMunicipio:
                            type: string
                            example: ''
                            required: false
                          codigoPais:
                            type: string
                            example: ''
                            required: false
                          direccionNormalizada:
                            type: string
                            example: ''
                            required: false
                          latitud:
                            type: string
                            example: ''
                            required: false
                          longitud:
                            type: string
                            example: ''
                            required: false
                          tecnologias:
                            type: array
                            items:
                              type: object
                              properties:
                                nombreTecnologia:
                                  type: string
                                  example: ''
                                  required: false
                                prioridadTecnologia:
                                  type: string
                                  example: ''
                                  required: false
                                zona:
                                  type: string
                                  example: ''
                                  required: false
                                cobertura:
                                  type: object
                                  properties:
                                    tipoCobertura:
                                      type: string
                                      example: ''
                                      required: false
                                    nombreCobertura:
                                      type: string
                                      example: ''
                                      required: false
                atributos:
                  type: array
                  items:
                    type: object
                    properties:
                      atributo:
                        type: string
                        example: ''
                        required: false
                      valor:
                        type: string
                        example: ''
                        required: false
                      accion:
                        type: string
                        example: ''
                        required: false
