#%RAML 1.0 DataType
type: object
displayName: unNormalizedAddress
properties:
  inputs:
    type: object
    properties:
      inputSet:
        type: object
        properties:
          ZA:
            description: The address to be normalized
            type: string
            required: true

example: !include ../../examples/request/unNormalizedAddress.raml