#%RAML 1.0 NamedExample
{
  "GetFeasibilityFTTHOutput": {
    "WSResponseHeader2": {
      "System": {
        "name": "",
        "correlationID": "MDM-FIBRA-007856914",
        "source": "infraestructure-portal-xapi-services"
      },
      "Service": {
        "status": "OK",
        "responseDate": "2022/05/26 10:05:34",
        "statusDetail": {
          "errorDetailCode": ""
        }
      },
      "GetFeasibilityFTTHResponse": {
        "Feasibility": {
          "Factible": "FACTIBLE",
          "Tecnologia": "FIBRA",
          "Motivo": "LIBRE"
        }
      }
    }
  }
}