#%RAML 1.0 DataType 
type: object
properties:
  ObtenerDisponibilidadAgendas:
    type: object
    properties:
      solicitudDisponibilidadAgenda:
        type: object
        properties:
          Encabezado:
            type: object
            required: false
            properties:
              Propiedades:
                type: object
                properties:
                  Propiedad:
                    type: array
                    items:
                      type: object
                      properties:
                        Nombre:
                          type: string
                          example: '?'
                          required: false
                        Valor:
                          type: string
                          example: '?'
                          required: false
              Sistema:
                type: object
                properties:
                  IdCorrelacion:
                    type: string
                    example: '?'
                    required: false
                  Nombre:
                    type: string
                    example: '?'
                    required: false
                  Servidor:
                    type: string
                    example: '?'
                    required: false
          DatosSolicitud:
            type: object
            properties:
              FechaAgenda:
                type: datetime
                example: '2026-07-02T00:00:00.000Z'
                required: false
              NumeroOrden:
                type: string
                example: MDM-FIBRA-000650220
                required: false
              Usuario_Agendamiento:
                type: string
                example: '?'
                required: false
      tipoEvento:
        type: string
        example: '?'
        required: false
      procesoEvento:
        type: string
        example: '?'
        required: false
