#%RAML 1.0 DataType
type: object
properties:
  transactionId:
    type: string
    example: "7bc91f32-3a4d-4891-b1fa-9e8d7c5af021"
  status:
    type: string
    enum: [SUCCESS]
  updatedAt:
    type: datetime
    example: "2026-03-16T14:00:03Z"
  result:
    type: object
    properties:
      customerId:
        type: string
        example: "12345678"
      serviceId:
        type: string
        example: "98765"
      previousOfferCode:
        type: string
        example: "GPON_300MB_BASIC"
      newOfferCode:
        type: string
        example: "GPON_500MB_PLUS"
      zsmartResponseCode:
        type: string
        example: "0"
      zsmartMessage:
        type: string
        example: "Success"
