#%RAML 1.0 DataType

properties:
  AjusteSAAWRequest:
    type: object
    properties:
      ajuste_saaw:
        type: object
        properties:
          ajuste:
            type: object
            properties:
              fechaDelAjuste:
                type: string
                required: true
                minLength: 1
                example: "2202-02-01"
              noDelAjuste:
                type: number
                required: true
                example: 4423693
              valorAjustado:
                type: number 
                required: true
                example: -91879.00
