#%RAML 1.0 DataType
properties:
  WSRequestSolicitudSincronizacionABD:
    type: object
    required: false
    properties:
      PortabilidadMsg:
        type: object
        required: true
        properties:
          CabeceraMensaje:
            type: object
            required: true
            properties:
              Identificador:
                type: string
                required: true
              TipoDeMensaje:
                type: string
                required: true
          CuerpoMensaje:
            type: object
            required: true
            properties:
              RespuestaSolicitudPortacionDonante:
                type: object
                required: false
                properties:
                  ListaNumeracionRechazada:
                    type: object
                    required: false
                    properties:
                      NumeracionRechazada:
                        type: array
                        required: true
                        items:
                          type: object
                          properties:
                            CodigosRechazo:
                              type: object
                              required: false
                              properties:
                                CodigoRechazo:
                                  type: string[]
                                  required: false
                            DocumentoDC:
                              type: string
                              required: false
                            DocumentoFC:
                              type: string
                              required: false
                            DocumentoFR:
                              type: string
                              required: false
                            DocumentoUO:
                              type: string
                              required: false
                            Numero:
                              type: string
                              required: false
                  RespuestaABD:
                    type: string
                    required: true
              FechaMaxVentanaCambio:
                type: string | nil
                required: false
              FechaVentanaConfirmada:
                type: string | nil
                required: false
              TipoErrorDetectadoABD:
                type: object
                required: false
                properties:
                  CodigosRechazo:
                    type: object
                    required: true
                    properties:
                      CodigoRechazo:
                        type: array
                        required: true
                        items:
                          type: object
                          properties:
                            TipoCodigoCausa:
                              type: string
                              required: false
                  IdentificadorMensajeErroneo:
                    type: object
                    required: true
                    properties:
                      IdentificadorMensajeErroneo:
                        type: string
                        required: true
              NumeracionesRechazadas:
                type: object
                required: false
                properties:
                  NumeracionesRechazadas:
                    type: object
                    required: true
                    properties:
                      NumeracionRechazada:
                        type: array
                        required: true
                        items:
                          type: object
                          properties:
                            CodigosRechazo:
                              type: object
                              required: true
                              properties:
                                CodigoRechazo:
                                  type: array
                                  required: true
                                  items:
                                    type: object
                                    properties:
                                      TipoCodigoCausa:
                                        type: string
                                        required: true
                            Numero:
                              type: object
                              required: true
                              properties:
                                TipoNumero:
                                  type: string
                                  required: true
  WSRequestPortabilidadSaliente:
    type: object
    required: false
    properties:
      PortabilidadMsg:
        type: object
        required: true
        properties:
          CabeceraMensaje:
            type: object
            required: true
            properties:
              Identificador:
                type: string
                required: true
          CuerpoMensaje:
            type: object
            required: true
            properties:
              RespuestaSolicitudPortacionDonante:
                type: object
                required: true
                properties:
                  DireccionAbonado:
                    type: string
                    required: true
                  DocumentoAT:
                    type: string
                    required: false
                  DocumentoCC:
                    type: string
                    required: false
                  DocumentoID:
                    type: string
                    required: false
                  IdentificacionAbonado:
                    type: string
                    required: true
                  ListaNumeracionNip:
                    type: object
                    required: true
                    properties:
                      NumeracionNip:
                        type: array
                        required: true
                        items:
                          type: object
                          properties:
                            Numero:
                              type: string
                              required: true
                            FechaCreacionNIP:
                              type: string
                              required: true
                  NombreRazonSocialAbonado:
                    type: string
                    required: true
                  NRN:
                    type: string
                    required: true
                  SolicitudTerceros:
                    type: string
                    required: true
                  TipoServicio:
                    type: string
                    required: true
                  TipoUsuario:
                    type: string
                    required: true
