#%RAML 1.0 DataType
properties:
  Id:
    type: string
    maxLength: 50
    pattern: ^[a-zA-Z0-9-_]*$
    example: "0014000000uczFLAAY"
  Notas:
    type: array
    items:
      type: object
      properties:
        TituloNota:
          type: string
          maxLength: 255
          example: ""
        DescripcionNota:
          type: string
          example: ""