#%RAML 1.0 DataType
type: object
properties:
  orderOM:
    type: string
    required: false
  items:
    type: array
    required: false
    items:
      properties:
        idItem:
          type: string
          required: false
        idOrigen:
          type: string
          required: false
        parentId:
          type: string | nil
          required: false
        engineer:
          type: string
          required: false
        groupAssignment:
          type: string
          required: false
        statusProvisioning:
          type: string
          required: false
        comments:
          type: string
          required: false
        causalDecline:
          type: string
          required: false
        provisioningDate:
          type: string
          required: false
        idService:
          type: string
          required: false
        listaConfiguraciones: 
            type: object
            required: false
            properties:
              quantity: 
                type: string 
                required: false
              parametros:
                type: array
                required: false
                items:
                  properties:
                    atributo:
                      type: string 
                      required: false
                    valor:
                      type: string 
                      required: false




    
