#%RAML 1.0 DataType
properties:
  wm:
    type: object
    properties:
      idPlantilla:
        type: string
        example: "deg_tecnico_en_caminoaprovisionamiento_v2"
      numeroEnvio:
        type: string
        example: "3222416193"
      fechaHoraEnvio:
        type: string
        example: "2023-06-01T04:28:50.807Z"
      listconacto:
        type: array
        items:
          properties:
            nombres:
              type: string
              example: "LEANDRO"
            apellidos:
              type: string
              example: "GARCIA"
            Tipodedocumento:
              type: string
              example: "Cédula de ciudadanía"
            NumerodeIdentificacion:
              type: string
              example: "9774689"
            numeroCelular:
              type: string
              example: "3105330192"
            listFieldTemplate:
              required: false
              type: array
              items:
                properties:
                  apiField:
                    type: string
                    example: "DEG_templatefield1__c"
                  textField: 
                    type: string
                    example: "Marcos Rincon"