#%RAML 1.0 DataType
type: object
properties:
  lstObjetosHijosRelacionados:
    type: object
    required: false
    properties:      
      ObjetosHijosRelacionados:
        type: array
        items:
          properties:                        
            lstParametros:
              type: object
              required: true
              properties:
                Keys:
                  type: array
                  items:
                    properties:                                
                      Campo:
                        type: string
                        required: true
                        minLength: 1
                      Valor:
                        type: string | nil
                        required: false
            NombreRelacion:
              type: string
              required: true
              minLength: 1
  lstParametros:
    type: object
    required: true   
    properties:
      Keys:
        type: array
        items: 
          properties:                              
            Campo:
              type: string
              required: true
              minLength: 1
            Valor:
              type: string | nil
              required: false
  NombreObjeto:
    type: string
    required: true
    minLength: 1