#%RAML 1.0 DataType
uses:
  updateViability-lib: ../../libraries/updateViability-library.raml
type: object
properties:
  orderOM:
    type: string | nil
    example: "FINAL"
    required: false
  opportunityId:
    type: string | nil
    example: OR-12321
    required: false
  tipoSolicitud:
    type: string | nil
    example: "string"
    required: false
  listadeParametros:
    type: array
    required: false
    items:
      type: object
      properties:
        codigo:
          type: string
          required: false
          example: "string"
        nombre:
          type: string
          required: false
          example: "string"
        valor:
          type: string
          required: false
          example: "string"
        idOrigen:
          type: string
          required: false
          example: "string"
  listadeProduct:
    type: updateViability-lib.listofProducts
    required: false
  listadePaquetes:
    type: array
    required: false
    items:
      type: object
      properties:
        idPaquete:
          type: string
          example: "PAQUETE-001"
          required: true
        listadeProduct:
          type: updateViability-lib.listofProducts
          required: true
  listaViabilidad:
    type: array 
    required: false
    items:
      type: object
      properties:
        viabilidad:
          type: string | nil
          example: "string"
          required: false
        estadoGestor:
          type: string | nil
          example: "string"
          required: false
        estadoViabilidad:
          type: string | nil
          example: "string"
          required: false
        faseGestor:
          type: string | nil
          example: "string"
          required: false
        fechaFinalEstado:
          type: string | nil
          example: "string"
          required: false
        ingeniero:
          type: string | nil
          example: "string"
          required: false
        correoIngeniero:
          type: string | nil
          example: "string"
          required: false
        aliado:
          type: string | nil
          example: "string"
          required: false
        tipoAliado:
          type: string | nil
          example: "string"
          required: false
        causal:
          type: string | nil
          example: "string"
          required: false
        grupoAsignacion:
          type: string | nil
          example: "string"
          required: false
        archivos:
          type: array
          required: false
          items:
            properties:
              nombre:
                type: string | nil
                example: "string"
                required: false
              viabilidad:
                type: string | nil
                example: "1"
                required: false
              URL:
                type: string | nil
                example: "string"
                required: false
        respuestadeviabilidad:
          type: string | nil
          example: "string"
          required: false
        respuestaGestor:
          type: string | nil
          example: "string"
          required: false
        tipodeViabilidad:
          type: string | nil
          example: "string"
          required: false