envName: "Production"

app:
  apiId: ""
  listener:
    host: "0.0.0.0"
    port: "8091"
    basePath: ""
  
wompi:
  host: "production.wompi.co"
  port: "443"
  basePath: "v1"
  auth:
    public_key: ""
    private_key: ""
    signature: ""