#%RAML 1.0 DataType 
type: object
properties:
  customer:
    type: object
    properties:
      documentNumber:
        type: string
        example: '87654321'
        required: false
      documentType:
        type: string
        example: CC
        required: false
      phone:
        type: string
        example: '3057000421'
        required: false
      name:
        type: string
        example: USUARIO_SISTEMA
        required: false
  order:
    type: object
    properties:
      id:
        type: string
        example: '12345'
        required: false
      CUN:
        type: string
        example: CUN001122
        required: false
      orderType:
        type: string
        example: installation
        required: false
      state:
        type: string
        example: pending
        required: false
      creationDate:
        type: string
        example: '2025-07-23T10:00:00Z'
        required: false
  appointment:
    type: object
    properties:
      date:
        type: string
        example: ''
        required: false
      timeSlot:
        type: string
        example: ''
        required: false
      duration:
        type: string
        example: ''
        required: false
  pqr:
    type: object
    properties:
      id:
        type: string
        example: '454'
        required: false
  operation:
    type: string
    example: type bussiness
    required: false
