#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  responseMessage:
    type: string
    example: Consulta realizada con exito
    required: false
  totalData:
    type: integer
    example: 1542
    required: false
  productOfferings:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          example: 5bad589d929c4e3b7c9967f6
          required: false
        offerFilterGroups:
          type: array
          items:
            type: object
            properties:
              group:
                type: string
                example: SCORING CLIENTE
                required: false
              offerGroupFilters:
                type: array
                items:
                  type: object
                  properties:
                    filter:
                      type: string
                      example: BAJO
                      required: false
                    groupFilterValues:
                      type: array
                      items:
                        type: object
                        properties:
                          value:
                            type: 'null'
                            example: null
                            required: false
                          maxValue:
                            type: integer
                            example: 10000
                            required: false
                          minValue:
                            type: integer
                            example: 761
                            required: false
        filterGrouping:
          type: array
          items: {}
        file:
          type: string
          example: data:image/png;base64,iVBORw0KGgoAASFDVDFVDSFV
          required: false
        mainBundle:
          type: string
          example: ''
          required: false
        maxQuantity:
          type: integer
          example: 0
          required: false
        minQuantity:
          type: integer
          example: 0
          required: false
        productOfferingCharacteristics:
          type: array
          items:
            type: object
            properties:
              offeringCharacteristicActions:
                type: array
                items:
                  type: object
                  properties:
                    action:
                      type: string
                      example: ADD
                      required: false
              characteristic:
                type: string
                example: DESCRIPCION
                required: false
              value:
                type: string
                example: >-
                  Chat de WhatsApp que no consume de tus datos (WhatsApp
                  limitado a 250MB por mes). Una vez superes este consumo
                  descontará de los datos de tu plan.
                required: false
        classification:
          type: string
          example: ''
          required: false
        configurationCode:
          type: string
          example: '2111130026'
          required: false
        dependency:
          type: integer
          example: 10
          required: false
        planDescription:
          type: string
          example: ''
          required: false
        display:
          type: string
          example: 250MB Chat WhatsApp
          required: false
        isModification:
          type: boolean
          example: false
          required: false
        isBundleType:
          type: boolean
          example: false
          required: false
        technicalSpecification:
          type: string
          example: ''
          required: false
        billingSpecificationsUpdate:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: 5b58e28b164b7e06b4e0c1f4
                required: false
              technicalOfferingActions:
                type: array
                items:
                  type: object
                  properties:
                    action:
                      type: string
                      example: ADD
                      required: false
              status:
                type: string
                example: Pendiente
                required: false
              applicationDate:
                type: datetime
                example: '2018-07-26T05:00:00.000Z'
                required: false
              creationDate:
                type: datetime
                example: '2018-07-25T20:50:19.674Z'
                required: false
              productSpecificationId:
                type: string
                example: ''
                required: false
              parameter:
                type: string
                example: RVC PARM Cargo Voz DS
                required: false
              productSpecification:
                type: string
                example: ''
                required: false
              system:
                type: string
                example: REVCHAIN
                required: false
              specificationType:
                type: string
                example: ''
                required: false
              createdBy:
                type: string
                example: asmeparg
                required: false
              value:
                type: string
                example: '4522.56'
                required: false
        status:
          type: string
          example: Activo
          required: false
        statusUpdate:
          type: string
          example: Activo
          required: false
        phase:
          type: string
          example: T
          required: false
        phaseUpdate:
          type: string
          example: I
          required: false
        creationDate:
          type: datetime
          example: '2018-09-27T22:24:29.670Z'
          required: false
        validityEndDate:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        validityStartDate:
          type: datetime
          example: '2018-06-01T05:00:00.000Z'
          required: false
        icon:
          type: string
          example: whatsapp
          required: false
        mainBundleId:
          type: string
          example: ''
          required: false
        productId:
          type: string
          example: 59c26bf2929c4e1b0cf97c60
          required: false
        mainProductId:
          type: string
          example: 59c17cb1929c4e12bc5f2484
          required: false
        planImages:
          type: array
          items: {}
        groupNumber:
          type: integer
          example: 208
          required: false
        notes:
          type: string
          example: ''
          required: false
        bundleParameters:
          type: array
          items:
            type: object
            properties:
              parameter:
                type: string
                example: CANAL VENTA
                required: false
              parameterType:
                type: string
                example: Parámetro General
                required: false
              value:
                type: string
                example: DISTRIBUIDOR/RETAIL/MOVILIDAD/TIENDA LTE
                required: false
        maxPrice:
          type: integer
          example: 0
          required: false
        minPrice:
          type: integer
          example: 0
          required: false
        offeringPrice:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                example: 5b5b3bf4929c4e1180bcc6fb
                required: false
              salesChannel:
                type: string
                example: ''
                required: false
              status:
                type: string
                example: Inactivo
                required: false
              applicationDate:
                type: datetime
                example: '2018-07-27T05:00:00.000Z'
                required: false
              creationDate:
                type: datetime
                example: '2018-07-27T15:36:20.553Z'
                required: false
              tax:
                type: integer
                example: 19
                required: false
              priceWithTax:
                type: integer
                example: 165900
                required: false
              priceFilters:
                type: string
                example: ''
                required: false
              priceWithoutTax:
                type: integer
                example: 134379
                required: false
              service:
                type: string
                example: ''
                required: false
              createdBy:
                type: string
                example: andrruec
                required: false
        product:
          type: string
          example: SVA Whatsapp Datos 250
          required: false
        mainProduct:
          type: string
          example: LTE POSPAGO
          required: false
        insuranceRangeEnd:
          type: string
          example: ''
          required: false
        insuranceRangeStart:
          type: string
          example: ''
          required: false
        sequence:
          type: integer
          example: 50
          required: false
        serviceSubtype:
          type: string
          example: CONTROL
          required: false
        bundleType:
          type: string
          example: LTE
          required: false
        productType:
          type: string
          example: SECUNDARIO
          required: false
        serviceType:
          type: string
          example: LTE
          required: false
        blockedBy:
          type: string
          example: ''
          required: false
        createdBy:
          type: string
          example: gonzpula
          required: false
        technicalOfferingValue:
          type: array
          items:
            type: object
            properties:
              technicalOfferingActions:
                type: array
                items:
                  type: object
                  properties:
                    action:
                      type: string
                      example: ADD
                      required: false
              productSpecificationId:
                type: string
                example: ''
                required: false
              parameter:
                type: string
                example: RVC FEAT
                required: false
              productSpecification:
                type: string
                example: ''
                required: false
              system:
                type: string
                example: REVCHAIN
                required: false
              specificationType:
                type: string
                example: PARAMETRO
                required: false
              value:
                type: string
                example: SVA Chat Whatsapp LTE
                required: false
