#%RAML 1.0 DataType
properties:
  "status": 
    type: string
    example: I20
  "orderNumber": 
    type: string
    example: "MDM-MAY-000001"
  "serviceAccount":
    type: string
    example: "GPONMAY_000001"
  "description": 
    type: string
    example: "Availability OK"
