#%RAML 1.0 DataType
properties:
  status: 
    type: string
    example: "O120"
  orderNumber:
    type: string
    example: "MDM-MAY-00001"
  serviceAccount:
    type: string
    example: "GPONMAY_000001"