#%RAML 1.0 DataType
properties:
  codigo:
    type: number
    required: true
    example: 200
  res-ley-intimidad:
    type: array
    items:
      type: object
      properties:
        Registro_Contacto:
          type: array
          items:
            type: object
            properties:
              Canal:
                type: number
                description: "Canal para ser contactado"
                required: false
                example: 12345
              Valor:
                type: string
                description: "Email o teléfono"
                required: false
                example: "aaa@bbb.com"
              Autorizado:
                type: string
                description: "Si autoriza 1 no autoriza 0"
                required: false
                example: "1"
        Horario: 
          type: string
          required: false
          example: "L-V 7-7 & S 8-3"
        Fecha_Registro:
          type: string
          required: false
          example: "2024-04-04T12:00:00.000Z"
        Fecha_Modificacion:
          type: string
          required: false
          example: "2024-04-04T12:00:00.000Z"