#%RAML 1.0 DataType
properties:
  assignedGroup:
    type: string
    example: ""
  status:
    type: string
    example: ""
  observations:
    type: string
    example: ""
  priority:
    type: string
    example: ""
      
example: !include ../../examples/response/GetIncident_responseExample.json