#%RAML 1.0 DataType
displayName: Order Cancel Response
type: object
properties:
  status:
    type: string
  orderNumber:
    type: string
  idServiceAccount:
    type: string
example: !include ../../examples/response/postOrderCancel.raml