#%RAML 1.0 DataType
properties:
  NotifyBillOutput:
    properties:
      WSResponseHeader2:
        properties:
          System:
            properties:
              name:
                type: string
                example: "ETB.MDM.Payment.Interface"
              correlationID:
                type: number
                example: 7785733
              processingServer:
                type: string
                example: Tibco
          Service:
            properties:
              status:
                type: string
                example: "FAIL"
              statusDetail:
                properties:
                  errorCode:
                    type: string
                    example: "BWENGINE-100031"
                  errorMessage:
                    type: string
                    example: "Output data invalid"
      Result:
        properties:
          code:
            type: string
            example: "BWENGINE-100031"
          description:
            type: string
            example: "Output data invalid"
          