#%RAML 1.0 DataType
displayName: Cancel Order Error Response
type: object
properties:
  response:
    type: object
    properties:
      result:
        type: object
        properties:
          code:
            type: string
          description:
            type: string
      responseDate:
        type: string
      orderNumber:
        type: string
example: !include ../../examples/response/postOrderCancelFail.raml