#%RAML 1.0 DataType
type: object
properties:
  IMEI: 
    description: Numero IMEI
    type: string
    example: "354522058683249"
  Estado: 
    description: Estado de equipo
    type: string
    example: No registrado
  Marca: 
    description: Marca de equipo
    type: string   
    example: Samsung
  CodigoRespuestaListas: 
    description: Codigo respuesta
    type: string  
    example: "4"
  Modelo: 
    description: Modelo
    type: string 
    example: GT-S7562L
  RespuestaGSMA: 
    description: Respuesta GSMA
    type: string 
    example: 4G_ETB
  ProbadoRedETB: 
    description: Probado de red ETB.
    type: string 
    example: NO -
  RespuestaPruebaRedETB: 
    description: Respuesta prueba de red ETB
    type: string 
  HomologadoColombia: 
    description: Homologado colombia
    type: string 
    example: EXISTE
  TamanoSIM: 
    description: Informacion tamaño SIM
    type: string 
  PartNumberSIM: 
    description: Informacion partnumber SIM
    type: string 
  CodigoError: 
    description: Codigo Error
    type: string 
    example: "0"
  DescripcionError: 
    description: Descripcion Error
    type: string 
    
example:
  !include ../../examples/response/ResponseBDOExample.raml