#%RAML 1.0 DataType
type: object
properties:
   ZBAPI_SOLFACT_CHECKDATA_GPResponse:
      type: object
      properties:
         T_BAPIRET:
            type: object
            properties:
               item:
                  type: object
                  properties:
                     TYPE:
                        type: string
                        required: true
                        example: "?"
                     ID:
                        type: string
                        required: true
                        example: "?"
                     NUMBER:
                        type: string
                        required: true
                        example: "?"
                     MESSAGE:
                        type: string
                        required: true
                        example: "?"
                     LOG_NO:
                        type: string
                        required: true
                        example: "?"
                     LOG_MSG_NO:
                        type: string
                        required: true
                        example: "?"
                     MESSAGE_V1:
                        type: string
                        required: true
                        example: "?"
                     MESSAGE_V2:
                        type: string
                        required: true
                        example: "?"
                     MESSAGE_V3:
                        type: string
                        required: true
                        example: "?"
                     MESSAGE_V4:
                        type: string
                        required: true
                        example: "?"
                     PARAMETER:
                        type: string
                        required: true
                        example: "?"
                     ROW:
                        type: string
                        required: true
                        example: "?"
                     FIELD:
                        type: string
                        required: true
                        example: "?"
                     SYSTEM:
                        type: string
                        required: true
                        example: "?"