#%RAML 1.0 DataType 
type: object
properties:
  status:
    type: integer
    example: 400
    required: false
  code:
    type: string
    example: ''
    required: false
  message:
    type: object
    properties:
      message:
        type: string
        example: ''
        required: false
  messageServer:
    type: string
    example: ''
    required: false
  cause:
    type: array
    items:
      type: object
      properties:
        origin:
          type: string
          example: ''
          required: false
        message:
          type: string
          example: ''
          required: false
