#%RAML 1.0 DataType 
type: object
properties:
  items:
    type: array
    items:
      type: object
      properties:
        date:
          type: date-only
          example: '2025-05-26'
          required: false
        areas:
          type: array
          items:
            type: object
            properties:
              label:
                type: string
                example: CHICO
                required: false
              timeSlots:
                type: array
                items:
                  type: object
                  properties:
                    label:
                      type: string
                      example: AM
                      required: false
                    timeslot_user:
                      type: string
                      example: AM
                      required: false
                    categories:
                      type: array
                      items:
                        type: object
                        properties:
                          label:
                            type: string
                            example: MPPFTTH_Plata
                            required: false
                          quota:
                            type: integer
                            example: 12514952
                            required: false
                          used:
                            type: integer
                            example: 0
                            required: false
                    maxAvailable:
                      type: integer
                      example: 17640
                      required: false
