#%RAML 1.0 DataType

properties:
  Questionnaire:    
    properties:
      idQuestionnaire:
        example: 1
        type: number
        format: int
      processResult:
        example: Example
        type: string
      fechaControl:
        example: Example
        type: string
      questionnaire:
        items:
          example:
            strict: true
            value:
              cuestion: ¿Con cuál de las siguientes entidades usted tiene una cuenta de ahorros?
              answers:
                - BANCO POPULAR
                - BANCOLOMBIA
                - FINAMERICA -  FINANCIERA AMERICA S.A.
                - NINGUNA DE LAS ANTERIORES
          properties:
            cuestion:
              example: Example
              type: string
            answers:
              items:
                example: Example
                type: string
    example:
      strict: true
      value:
        idQuestionnaire: 3974952
        processResult: CUESTIONARIO OBTENIDO EXITOSAMENTE
        fechaControl: 2021-08-01T00:23:14.6130011-05:00
        questionnaire:
          -
            cuestion: ¿Con cuál de las siguientes entidades usted tiene una cuenta de ahorros?
            answers:
              - BANCO POPULAR
              - BANCOLOMBIA
              - FINAMERICA -  FINANCIERA AMERICA S.A.
              - NINGUNA DE LAS ANTERIORES
          -
            cuestion: ¿Con cuál de las siguientes entidades usted tiene una cuenta de ahorros?
            answers:
              - CAUCA
              - GUAINIA
              - BOLIVAR
              - NINGUNA DE LAS ANTERIORES