#%RAML 1.0 ResourceType
get?:
  displayName: List <<resourcePathName | !uppercamelcase>>
  description: List <<resourcePathName | !uppercamelcase>>
  is:
    - billing-api-services.security-clientId-trait
    - billing-api-services.RequestHeaders
    - billing-api-services.<<resourcePathName | !singularize | !uppercamelcase>>QueryParameters
  responses:
    200:
      #is:
        #- billing-api-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response[]
post?:
  displayName: Create <<resourcePathName | !singularize | !uppercamelcase>>
  description: Create <<resourcePathName | !singularize | !uppercamelcase>>
  is:
    - billing-api-services.security-clientId-trait
    - billing-api-services.RequestHeaders
    - billing-api-services.httpCodes
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response
put?:
  displayName: Update <<resourcePathName | !singularize | !uppercamelcase>>
  description: Update <<resourcePathName | !singularize | !uppercamelcase>>
  is:
    - billing-api-services.security-clientId-trait:
    - billing-api-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    201:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response