#%RAML 1.0 ResourceType
get?:
  displayName: Get <<resourcePathName | !singularize | !uppercamelcase>> By Id
  description: Get <<resourcePathName | !singularize | !uppercamelcase>> By Id
  is:
    - billing-api-services.security-clientId-trait:
    - billing-api-services.RequestHeaders:
    - billing-api-services.<<resourcePathName | !singularize | !uppercamelcase>>QueryParameters:
  responses:
    200:
      #is:
        #- billing-api-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response
patch?:
  displayName: Update <<resourcePathName | !singularize | !uppercamelcase>> Partially By Id
  description: Update <<resourcePathName | !singularize | !uppercamelcase>> Partially By Id
  is:
    - billing-api-services.security-clientId-trait:
    - billing-api-services.RequestHeaders:
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>Request
  responses:
    200:
      #is:
        #- billing-api-services.ResponseHeaders:
      body:
        type: <<resourcePathName | !singularize | !uppercamelcase>>Response