http:
  private:
    port: "8091"
    
autodiscovery: "19182023"
  
azureStorage:
  accountName: "strprtlprofija"
  accountKey: "MiwdrCT66M9XYi1l9PlRyhtF2hUcP9mtRM/lWGJWn+Nqe2EpdKooZVHaAgcT+FnKM1YjJm3f33eWdRBRAf5g1Q=="
  accountConnectionString: "DefaultEndpointsProtocol=https;AccountName=strprtlprofija;AccountKey=MiwdrCT66M9XYi1l9PlRyhtF2hUcP9mtRM/lWGJWn+Nqe2EpdKooZVHaAgcT+FnKM1YjJm3f33eWdRBRAf5g1Q==;BlobEndpoint=https://strprtlprofija.blob.core.windows.net/;TableEndpoint=https://strprtlprofija.table.core.windows.net/;QueueEndpoint=https://strprtlprofija.queue.core.windows.net/;FileEndpoint=https://strprtlprofija.file.core.windows.net/"
  blobEndpoint: "https://strprtlprofija.blob.core.windows.net/"
  bills:
    folderName: "TirillaPago/"
    accountStateFolder: "EstadoDeCuenta/"
  pqr:
    container: "esim"
    
audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

keyVault:
  client-id: ""
  client-secret: ""
  tenant-id: ""
  vault-name: ""
  uri: ""
  key-secret-name: ""
  key-captcha-name: ""
    
azure:
  protocol: "HTTPS"
  host: "dev.azure.com"
  organization: "informaticaETB"
  version: "7.0"
  path:
    getWI: "/_apis/wit/workitems/{id}"
    updateWI: "/_apis/wit/workitems/{id}?api-version=7.0"
    createWI: "/{project}/_apis/wit/workitems/{type}?api-version=7.1-preview.3"
  token: "cm3xleycnvzkrlzxnyetghi42h3kbqhrta64hbsqmyeocgdyv7mq"
  username: "admin"
  #Add '$' before WI type name to respect the URI: Ex. '$Product Backlog Item'
  typeWI: "$Epic"
  project: "GAMMA"
  
azureStorage-agreements:
  accountName: "strprtlprofija" 
  accountKey: "MiwdrCT66M9XYi1l9PlRyhtF2hUcP9mtRM/lWGJWn+Nqe2EpdKooZVHaAgcT+FnKM1YjJm3f33eWdRBRAf5g1Q=="
  accountConnectionString: "DefaultEndpointsProtocol=https;AccountName=strprtlprofija;AccountKey=MiwdrCT66M9XYi1l9PlRyhtF2hUcP9mtRM/lWGJWn+Nqe2EpdKooZVHaAgcT+FnKM1YjJm3f33eWdRBRAf5g1Q==;BlobEndpoint=https://strprtlprofija.blob.core.windows.net/;TableEndpoint=https://strprtlprofija.table.core.windows.net/;QueueEndpoint=https://strprtlprofija.queue.core.windows.net/;FileEndpoint=https://strprtlprofija.file.core.windows.net/"
  blobEndpoint: "https://strprtlprofija.blob.core.windows.net/"
  container: "esim"
  
azureStorage-esim:
  accountName: "strprtlproqa"
  accountKey: "sv=2024-11-04&ss=b&srt=co&sp=rlx&se=2027-11-15T07:47:30Z&st=2025-11-14T23:32:30Z&spr=https&sig=pEJCkmWsJgWR4Rv614VwAKIgBak79bg5IY5%2F43S8h%2Fs%3D"
  filenameroot: ""
  container: "esim"
  dpi: "100"
