#%RAML 1.0
title: lisim-xapi-services
baseUri: https://lisim-xapi-services-{env}.us-e2.cloudhub.io/lisim
protocols:
  - HTTPS
version: "1"
description: The present API has an interface for website operations about checking the user conditions.

traits:
  tibcoHeaders: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.4/tibcorequestheaders.raml

mediaType:
  - application/json

securitySchemes:
  etb_oauth_2_0: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/etb-oauth-20/1.0.1/etb-oauth-20.raml

/questionnaire/documentType/{documentTypeId}/document/{documentId}/model/{modelId}:
  securedBy: [etb_oauth_2_0]
  uriParameters:
    documentTypeId:
      description: Document Type ID
      example: 1
      type: number
      format: int
    documentId:
      description: Document ID
      example: 1
      type: number
      format: int
    modelId:
      example: 2
      type: number
      format: int
      
  get:
    displayName: questionnaire
    description: Operación que permite obtener las preguntas de validación del usuario.    
    queryParameters:
      lastName:
        description: Last name
        example: SOTO
        type: string
      documentExpeditionDate:
        description: Document issue date
        example: 1997-04-10T00:00:00-05:00
        type: string
      department?:
        example: 1
        type: number
        format: int
      city?:
        example: 1
        type: number
        format: int
      adviser?:
        example: MIETB_USER
        type: string
      salesChannel?:
        example: Web
        type: string
      supplier?:
        example: MiETB
        type: string
      portal?:
        example: MiETB
        type: string
  
    responses:
      200:
        body:
          application/json:
            type: !include exchange_modules/35a39a92-efa9-49b6-8f13-d66508fd2f35/questionnaire/1.0.1/questionnaire.raml
      429:
        description: |
          Indica que el usuario ha enviado demasiadas solicitudes en un período de tiempo determinado
        body:
          application/json:
            example:
              !include examples/questionnaire_429-Request.json

/operations:
  /v1:
    /questionaries:
      /{questionarie-id}:
        /validation:
          uriParameters:
              questionarie-id:
                type: number
                example: 2652
          post:
            is:
              - tibcoHeaders
            securedBy: [etb_oauth_2_0]
            displayName: Validate Evidence LISIM
            description: Validate Evidence LISIM
            body:
              application/json:
                type: !include datatypes/request/evidentVerificationLISIM.raml     
                example: !include examples/request/evidentVerificationLISIM.json 
            responses:
              200:
                body:
                  application/json:
                    type: !include datatypes/response/evidentVerificationLISIM.raml
    /borrowing-capacities:
      post:
        is:
          - tibcoHeaders
        securedBy: [etb_oauth_2_0]
        displayName: Consulta Cupo Neg LISIM
        description: Consulta Cupo Neg LISIM
        body:
          application/json:
            type: !include datatypes/request/consultNegQuoteLISIM.raml   
            example: !include examples/request/consultNegQuoteLISIM.raml  
        responses:
          200:
            body:
              application/json:
                type: !include datatypes/response/consultNegQuoteLISIM.raml   
    /documents:
      /validation:
        post: 
          is:
            - tibcoHeaders
          securedBy: [etb_oauth_2_0]
          displayName: Validar Identificacion Neg LISIM
          description: Validar Identificacion Neg LISIM
          body:
            application/json:
              type: !include datatypes/request/validaIdentidadNegLISIM.raml
          responses:
            200:
              body:
                application/json:
                  type: !include datatypes/response/validaIdentidadNegLISIMResponse.raml