https:
  host: "0.0.0.0"
  port: "443"
  
autodiscovery: "20441007"

audits-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
 
bot-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-bot-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/api"
  endpoints:
    pqr:
      base-path: "/pqr"
      agendaclose: "/agendaclose/v1"
      reagenda: "/reagenda/v1"
      agenda: "/agenda/v1"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
 
mongo-db-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-db-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/mongo/v1"
  resources:  
    franjas:
      base-path: "/unifiedPortalConf"
      get:
        path: ""
  nombre-franja: "FRANJA_AGENDA"

  security:
    client-id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client-secret: "8917F36fBC2c4105b72c7bC3a165740F"
      
oracle-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/oracle/v1"
  assuranceOrder:
    path: "/assurance/order/{activityId}"
  getCapacity:
    path: "/getCapacity"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  configurationTimeout: "62000"

credentials:
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
orquestador-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-orquestador-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  base-path: "/orquestador/v1"
  resources:  
    obtenerDisponibilidadAgendas:
      path: "/obtenerDisponibilidadAgendas"

  security:
    client-id: "7b167b9c389a4c0099bbf7ea34df88fc"
    client-secret: "8917F36fBC2c4105b72c7bC3a165740F"

tls:
  type: "JKS"
  path: "security/keystore.jks"
  keyPassword: "password"
  password: "password"
  
configurationTimeout:
  appointment-management-xapi-listener: "62000"
  bot-sapi: 
    responseTimeout: "60000"
    connectionIdleTimeout: "60000"
  mongo-db-sapi:
    responseTimeout: "60000"
    connectionIdleTimeout: "60000"
  oracle-sapi:
    responseTimeout: "60000"
    connectionIdleTimeout: "60000"
  orquestador-sapi:
    responseTimeout: "60000"
    connectionIdleTimeout: "60000"