#%RAML 1.0 DataType

type: object
properties:
  connectionNumber:
    type: string
    required: true
    pattern: ^[0-9]{10}$
    example: "3182097931"
    description: Parent account connection number. Only numeric values are allowed, with exactly 10 digits.
  referredConnectionNumber:
    type: string
    required: true
    pattern: ^[0-9]{10}$
    example: "3057854301"
    description: Referred subscriber connection number to add. Only numeric values are allowed, with exactly 10 digits.
