#%RAML 1.0 DataType
type:
  properties:
    sfilluminate:
      type: object
      properties:
        idRegistro:
          type: string
          example: "676133"
        resultado:
          type: string
          example: "0"
        descError:
          type: string
          example: "OK"

example:
  !include ../../examples/responses/CreateBillingOperationCompRvch.json