#%RAML 1.0 DataType
type: object
properties:
  codigo_respuesta:
    type: string
    description: "'0': Proceso ejecutado correctamente. '1': Proceso ejecutado con error."
    example: "0"
  descripcion_respuesta:
    type: string
    description: "Descripción del error generado en el proceso"
    example: "Ejecución exitosa."