#%RAML 1.0 DataType

properties: 
  portalfija_data:
    type: object
    properties:  
      idRegistro:
        type: nil
      resultado: 
        type: string
      descError:
        type: string

                  