#%RAML 1.0 DataType 
type: object
properties:
  businessSegment:
    type: string
    example: ''
    required: false
  serviceAccount:
    type: string
    example: ''
    required: false
  phone:
    type: string
    example: ''
    required: false
  resourceID:
    type: string
    example: ''
    required: false
  resourceType:
    type: string
    example: ''
    required: false
  serviceType:
    type: string
    example: ''
    required: false
  functionType:
    type: string
    example: ''
    required: false
  operation:
    type: string
    example: ''
    required: false
