#%RAML 1.0 DataType 
type: object
properties:
  aplicacion:
    type: string
    example: texto
    required: false
  ip:
    type: string
    example: '::1'
    required: false
  navegador:
    type: string
    example: Chrome 138.0
    required: false
  nombre_equipo:
    type: string
    example: '::1'
    required: false
  usuario_suma:
    type: string
    example: mrodriguez01
    required: false
  telefono_consultado:
    type: string
    example: '999'
    required: false
  archivo_descargado:
    type: string
    example: ''
    required: false
  fecha_hora_registro:
    type: datetime
    example: '2025-07-16T18:38:02.549Z'
    required: false
