#%RAML 1.0 DataType 
type: object
properties:
  customer:
    type: object
    properties:
      actualizacion_extractor:
        type: string
        example: '1'
        required: false
      Adjuntos_Cliente:
        type: array
        items:
          type: object
          properties:
            Descripcion:
              type: string
              example: Camara Comercio
              required: false
            Enviar:
              type: boolean
              example: false
              required: false
            Nombre_Archivo:
              type: string
              example: 900377449_CamaraComercio.pdf
              required: false
            Ruta:
              type: string
              example: 900377449/900377449_CamaraComercio.pdf
              required: false
            Tamano:
              type: string
              example: '0'
              required: false
      ATDP_PN:
        type: object
        properties:
          CANAL:
            type: string
            example: Portal Fija
            required: false
          FECHA:
            type: datetime
            example: '2022-05-12T19:21:55.190Z'
            required: false
          HABEAS_DATA:
            type: string
            example: 'False'
            required: false
          PQR_ASOCIADA:
            type: string
            example: 627d5e52f46b16128c378b03
            required: false
          USUARIO:
            type: string
            example: yeissuas
            required: false
      ATDP_PJ:
        type: string
        example: Autoriza
        required: false
      Autorizacion_Datacredito:
        type: string
        example: 'Y'
        required: false
      Barrio:
        type: string
        example: '008418'
        required: false
      Categoria:
        type: string
        example: PLATINO
        required: false
      Ciudad:
        type: string
        example: BOGOTA D.C.
        required: false
      Ciudad_Exp_Documento:
        type: string
        example: ''
        required: false
      Clasificacion_Scoring:
        type: string
        example: ''
        required: false
      Cliente_Valor:
        type: string
        example: ''
        required: false
      Cobertura:
        type: string
        example: COBRE
        required: false
      Contacto:
        type: array
        items:
          type: object
          properties:
            actualizacion_extractor:
              type: string
              example: '1'
              required: false
            Adjuntos_Contacto:
              type: string
              example: ''
              required: false
            Autorizado:
              type: boolean
              example: false
              required: false
            Ciudad:
              type: string
              example: ''
              required: false
            Codigo_DANE:
              type: string
              example: ''
              required: false
            Departamento:
              type: string
              example: ''
              required: false
            Direccion_Asociada:
              type: string
              example: ''
              required: false
            Email_Contacto:
              type: string
              example: ''
              required: false
            Estado:
              type: boolean
              example: false
              required: false
            Fecha_Modificacion:
              type: datetime
              example: '2022-04-21T19:25:13.580Z'
              required: false
            Fecha_Modificacion_Movil:
              type: datetime
              example: '2022-04-21T19:25:13.580Z'
              required: false
            Movil_Contacto:
              type: string
              example: ''
              required: false
            Movil_Contacto2:
              type: string
              example: ''
              required: false
            Nombre_Contacto:
              type: string
              example: JULIOCESAR DE LA ROCHE SANCHEZ
              required: false
            Nombre_Individual:
              type: string
              example: JULIOCESAR
              required: false
            Numero_Documento:
              type: string
              example: '1127945002'
              required: false
            Pais:
              type: string
              example: ''
              required: false
            Primer_Apellido:
              type: string
              example: DE LA ROCHE
              required: false
            Segundo_Apellido:
              type: string
              example: SANCHEZ
              required: false
            Telefono_Contacto:
              type: string
              example: ''
              required: false
            Tipo_Documento:
              type: string
              example: '1'
              required: false
      Correo_Electronico:
        type: string
        example: ''
        required: false
      Datos_Empresa:
        type: object
        properties:
          Balance_General:
            type: object
            properties:
              Inventarios:
                type: string
                example: '400000'
                required: false
              Total_Activo_Corriente:
                type: string
                example: '400000'
                required: false
              Total_Activos:
                type: string
                example: '400000'
                required: false
              Total_Pasivo:
                type: string
                example: '400000'
                required: false
              Total_Pasivo_Corriente:
                type: string
                example: '400000'
                required: false
              Total_Patrimonio:
                type: string
                example: '40000000'
                required: false
          Estado_Resultados:
            type: object
            properties:
              Costo_Venta:
                type: string
                example: '400000'
                required: false
              Cuentas_Por_Cobrar:
                type: string
                example: '400000'
                required: false
              Gastos_Operacionales:
                type: string
                example: '40000000'
                required: false
              Impuestos_Renta_Y_Complementarios:
                type: string
                example: '400000'
                required: false
              Ingresos_No_Operacionales_Ano_Anterior:
                type: string
                example: '4'
                required: false
              Ingresos_No_Operacionales_Ano_Corriente:
                type: string
                example: '400000'
                required: false
              Ingresos_Operacionales_Ano_Anterior:
                type: string
                example: '400000'
                required: false
              Ingresos_Operacionales_Ano_Corriente:
                type: string
                example: '400000'
                required: false
              Obligaciones_Financieras:
                type: string
                example: '400000'
                required: false
              Otros_Egresos:
                type: string
                example: '40000000'
                required: false
              Utilidad_Antes_De_Impuestos:
                type: string
                example: '4'
                required: false
              Utilidad_Neta:
                type: string
                example: '40000000'
                required: false
              Utilidades_Operacionales:
                type: string
                example: '4'
                required: false
          Informacion_Basica:
            type: object
            properties:
              Actividad_Economica:
                type: string
                example: '1'
                required: false
              Id_Solicitud:
                type: string
                example: ''
                required: false
              Plazo:
                type: integer
                example: 12
                required: false
              Razon_Social:
                type: string
                example: VCS CONSORCIO TECNOLOGICO SAS
                required: false
              Sector:
                type: integer
                example: 3
                required: false
          Representante_Legal:
            type: object
            properties:
              Fecha_Expedicion:
                type: datetime
                example: '1981-01-01T05:00:00Z'
                required: false
              Fecha_Nacimiento:
                type: datetime
                example: '1971-01-01T05:00:00Z'
                required: false
              Numero_Documento:
                type: string
                example: '1127945002'
                required: false
              Primer_Apellido:
                type: string
                example: DE LA ROCHE
                required: false
              Primer_Nombre:
                type: string
                example: JULIO
                required: false
              Segundo_Apellido:
                type: string
                example: SANCHEZ
                required: false
              Segundo_Nombre:
                type: string
                example: JULIO
                required: false
              Tipo_Documento:
                type: string
                example: '1'
                required: false
          Ubicacion:
            type: object
            properties:
              Celular:
                type: string
                example: '16289028'
                required: false
              Codigo_Departamento:
                type: string
                example: 59484c5eec96a369378eb4c8
                required: false
              Codigo_Municipio:
                type: string
                example: '11001'
                required: false
              Departamento:
                type: string
                example: 59484c5eec96a369378eb4c8
                required: false
              Direccion:
                type: string
                example: CL 83 BIS 23 47 AP 104
                required: false
              Email:
                type: string
                example: etbpruev@gmail.com
                required: false
              Estrato:
                type: integer
                example: 5762
                required: false
              Extension:
                type: string
                example: ''
                required: false
              Fecha_Constitucion:
                type: datetime
                example: '2005-04-12T05:00:00Z'
                required: false
              Municipio:
                type: string
                example: '11001'
                required: false
              Telefono:
                type: string
                example: '3204637676'
                required: false
              Tipo_Negocio:
                type: integer
                example: 1
                required: false
              Zona:
                type: integer
                example: 2
                required: false
      Departamento:
        type: string
        example: BOGOTÁ, D. C.
        required: false
      Depto_Exp_Documento:
        type: string
        example: ''
        required: false
      Direccion:
        type: string
        example: CL 106 18A 06
        required: false
      Direcciones:
        type: array
        items:
          type: object
          properties:
            Cobertura:
              type: object
              properties:
                Codigo_Lote:
                  type: string
                  example: '04'
                  required: false
                Direccion_GIS:
                  type: string
                  example: ''
                  required: false
                Distrito:
                  type: 'null'
                  example: null
                  required: false
                Estrato:
                  type: integer
                  example: 4
                  required: false
                Latitud:
                  type: number
                  example: 4.671102955
                  required: false
                Localidad:
                  type: string
                  example: '12'
                  required: false
                Longitud:
                  type: number
                  example: -74.06212576
                  required: false
                Molecula:
                  type: string
                  example: FCO34
                  required: false
                NombreCobertura:
                  type: string
                  example: FCO34
                  required: false
                Olt:
                  type: string
                  example: BOCOZTC30001
                  required: false
                Propietario:
                  type: string
                  example: ETB
                  required: false
                Proposito:
                  type: string
                  example: '05'
                  required: false
                Tecnologia:
                  type: string
                  example: FTTH
                  required: false
                Tipo_Cobertura:
                  type: string
                  example: MOLECULA
                  required: false
                TipoDistancia:
                  type: string
                  example: A
                  required: false
                Zona:
                  type: string
                  example: CHICO
                  required: false
            Codigo_DANE:
              type: 'null'
              example: null
              required: false
            Codigo_Departamento:
              type: string
              example: '11'
              required: false
            Codigo_Direccion:
              type: string
              example: ''
              required: false
            Codigo_Municipio:
              type: string
              example: '11001'
              required: false
            Codigo_Pais:
              type: string
              example: 593b0ac99a8e4177d410df4d
              required: false
            Departamento:
              type: string
              example: BOGOTA
              required: false
            Direccion_Normalizada:
              type: string
              example: CL 83 BIS 23 47 AP 104
              required: false
            Estado:
              type: string
              example: ACTIVO
              required: false
            Id_Direccion:
              type: integer
              example: 1
              required: false
            Municipio:
              type: string
              example: BOGOTA D.C.
              required: false
            Nombre_Direccion:
              type: 'null'
              example: null
              required: false
            Seleccionada:
              type: boolean
              example: false
              required: false
            Tipo_Direccion:
              type: string
              example: INSTALACION
              required: false
      EsquemaAtencion:
        type: string
        example: ''
        required: false
      Estado:
        type: string
        example: ACTIVO
        required: false
      Estado_Civil:
        type: string
        example: ''
        required: false
      Estrato:
        type: string
        example: '6'
        required: false
      Fecha_Actualizacion:
        type: datetime
        example: '2025-05-14T00:22:25.516Z'
        required: false
      Fecha_Expedicion_Documento:
        type: string
        example: 22/10/1975
        required: false
      Fecha_Nacimiento:
        type: string
        example: ''
        required: false
      Fecha_Scoring:
        type: string
        example: 30/06/2022
        required: false
      Genero:
        type: string
        example: ''
        required: false
      Localidad:
        type: string
        example: ''
        required: false
      Modificado_MDM:
        type: string
        example: '0'
        required: false
      Nombre_Cliente:
        type: string
        example: VCS CONSORCIO TECNOLOGICO SAS
        required: false
      Nombre_Corto_Empresa:
        type: string
        example: VCS
        required: false
      Nombres:
        type: string
        example: JULIOCESAR
        required: false
      Numero_Identificacion:
        type: string
        example: '900377449'
        required: false
      Pais:
        type: string
        example: COLOMBIA
        required: false
      Primer_Apellido:
        type: string
        example: DE LA ROCHE
        required: false
      Rango_Edad:
        type: string
        example: ''
        required: false
      Scoring:
        type: string
        example: ''
        required: false
      Segmento:
        type: string
        example: Microempresa
        required: false
      Segmento_UEN:
        type: string
        example: MiPymes
        required: false
      Segundo_Apellido:
        type: string
        example: SANCHEZ
        required: false
      ServiciosPS:
        type: string
        example: ''
        required: false
      Sistema_Origen:
        type: array
        items:
          type: object
          properties:
            Id_Sistema_Origen:
              type: string
              example: 1-HUC0V48
              required: false
            Sistema_Origen:
              type: string
              example: FIBRA
              required: false
      Telefono_Fijo:
        type: string
        example: '16289028'
        required: false
      Telefono_Movil:
        type: string
        example: '3125472911'
        required: false
      Tipo_Cliente:
        type: string
        example: JURIDICO
        required: false
      Tipo_Documento:
        type: string
        example: NIT
        required: false
      Tipo_Scoring:
        type: string
        example: ''
        required: false
      UEN:
        type: string
        example: Hogares y MiPymes
        required: false
      Usuario_Creador:
        type: string
        example: 1-4LFTT2D
        required: false
      Usuario_Modificador:
        type: string
        example: 1-FU8SX2E
        required: false