#%RAML 1.0 DataType
displayName: Patch Payment Transaction (PAGOS_TRANSACCIONES)
type: object
properties:
  estado_transaccion: 
    type: string
    required: true
  estados:
      type: array
      required: true

