#%RAML 1.0 DataType
displayName: POST Payment Transaction (PAGOS_TRANSACCIONES)
type: object
properties:
  _id: 
    type: object
    required: false
  CUS: 
      type: string
      required: true
  atributos_pasarela:
      type: array
      required: true
  referencia_pago:
      type: array
      required: true
  tipo_documento:
      type: string
      required: true
  numero_documento:
      type: string
      required: true
  valor_pagar:
      type: string
      required: false
  valor_impuesto:
      type: string
      required: false
  concepto:
      type: string
      required: true 
  entidad_bancaria:
      type: string
      required: true    
  pasarela_tipo:
      type: string
      required: true
  estado_transaccion:
    type: string
    required: true
  estados:
    type: array
    required: true
  fecha_registro:
    type: string
    required: true
  fecha_respuesta_pasarela:
    type: string
    required: true
  fecha_actualizacion: 
    type: string | nil
    required: true