#%RAML 1.0 DataType
displayName: Put Order(MDM_CD_ORDER) Message Input
type: object
properties:
  _id: 
    type: object
    required: false
  Fecha_Creacion: 
      type: string
      required: false
  Fecha_Modificacion:
      type: string
      required: false
  Usuario_Modificacion:
      type: string
      required: false
  Usuario_Creacion:
      type: string
      required: false
  Actualizacion_Extractor:
      type: string
      required: false
  Numero_Orden:
      type: string
      required: false
  Canal:
      type: string
      required: false
  Fase:
      type: string
      required: false 
  Estado_Orden_Comercial:
    type: object
    properties:
      Codigo:
          type: string
          required: false
      Descripcion:
          type: string
          required: false
      Fecha:
          type: string
          required: false
      Reintentos:
          type: number
          required: false
      CodigoExcepcion:
          type: number
          required: false
  Tramite:
    type: object
    required: false
    properties:
      Tipo_Tramite:
          type: string
          required: false
      Subtipo_Tramite:
          type: string | nil
          required: false
      Fecha_Tramite:
          type: string
          required: false
      Fecha_Reconexion:
          type: string | nil
          required: false
      Fecha_Suspension:
          type: string | nil
          required: false
      Fecha_Ejecucion:
          type: string
          required: false
      Conservar_Numero_Conexion:
          type: boolean
          required: false
      Clausula_Permanencia:
          type: boolean
          required: false
      Valor_Clausula_Permanencia:
          type: number
          required: false
      Causal_Cancelacion:
          type: string | nil
          required: false
      Subcausal_Cancelacion:
          type: string | nil
          required: false
      Descripcion_Cancelacion:
          type: string | nil
          required: false
      MotivosOrden:
          type: string | nil
          required: false
  Tipo_Servicio:
    type: string | nil
    required: false
  CUN:
    type: string | nil
    required: false
  Cliente_Anterior:
    type: string | nil
    required: false
  Cliente_Tramite:
    type: object
    properties: 
      _id:
        type: object
        required: false
      Fecha_Creacion:
        type: string | nil
        required: false
      Fecha_Modificacion:
        type: string | nil
        required: false
      Usuario_Modificacion:
        type: string | nil
        required: false
      Usuario_Creacion:
        type: string | nil
        required: false
      Actualizacion_Extractor:
        type: string | nil
        required: false
      Id_Cuenta_Cliente:
        type: integer
        required: false
      Tipo_Documento:
        type: string
        required: false
      Numero_Documento:
        type: string
        required: false
      Nombres:
        type: string
        required: false
      Nombre_Corto_Empresa:
        type: string
        required: false
      Primer_Apellido:
        type: string
        required: false
      Segundo_Apellido:
        type: string
        required: false
      Fecha_Expedicion:
        type: string | nil
        required: false
      Fecha_Validacion_Identidad:
        type: string | nil
        required: false
      Autoriza_Manejo_Datos_Personales:
        type: string | nil
        required: false
      Autoriza_Consulta_Centrales:
        type: string | nil
        required: false
      UEN:
        type: string
        required: false
      Segmento_UEN:
        type: string | nil
        required: false
      Segmento:
        type: string | nil
        required: false
      Scoring_Fija: 
        type: string | nil
        required: false
      Telefono_Fijo:
        type: string
        required: false
      Extension:
        type: nil | string
        required: false
      Telefono_Movil:
        type: string
        required: false
      Telefono_Movil2:
        type: string
        required: false
      Email:
        type: string
        required: false
      Contactos:
        type: array
        required: false
      Direcciones:
        type: array
        required: false
        items:
          type: object
          properties:
            Id_Direccion:
              type: integer
              required: false
            Direccion_Normalizada:
              type: string
              required: false
            Tipo_Direccion:
              type: string
              required: false
            Codigo_Direccion:
              type: string
              required: false
            Codigo_Departamento:
              type: string
              required: false
            Codigo_Municipio:
              type: string
              required: false
            Codigo_Pais:
              type: string
              required: false
            Nombre_Direccion:
              type: string | nil
              required: false
            Estado:
              type: string
              required: false
            Cobertura:
              type: object
              properties:
                Direccion_GIS:
                  type: string | nil
                  required: false
                Tecnologia:
                  type: string | nil
                  required: false
                Tipo_Cobertura:
                  type: string | nil
                  required: false
                NombreCobertura:
                  type: string | nil
                  required: false
                Zona:
                  type: string | nil
                  required: false
                Latitud:
                  type: string | integer | number
                  required: false
                Longitud:
                  type: string | integer | number
                  required: false
                Proposito:
                  type: string | nil
                  required: false
                Codigo_Lote:
                  type: string | nil
                  required: false
                Localidad:
                  type: string | nil
                  required: false
                Estrato:
                  type: string | nil | integer
                  required: false
                TipoDistancia:
                  type: string | nil
                  required: false
                Molecula:
                  type: string | nil
                  required: false
                Viable:
                  type: boolean | nil
                  required: false
                Olt:
                  type: string | nil
                  required: false
                Propietario:
                  type: string | nil
                  required: false
            Seleccionada:
              type: boolean
              required: false
            Departamento:
              type: string
              required: false
            Municipio:
              type: string
              required: false
      Cuentas_Facturacion:
        type: string | nil
        required: false
      Cuentas_Servicio:
        type: string | nil
        required: false
      Adjuntos_Cliente:
        type: array
        required: false
      Sistema_Origen:
        type: string | nil
        required: false
      Estado:
        type: string | nil
        required: false
      CarruselMotivo:
        type: string | nil
        required: false
      CarruselSubMotivo:
        type: string | nil
        required: false
      Direccion:
        type: string | nil
        required: false
      Cobertura:
        type: string | nil
        required: false
      Departamento:
        type: string | nil
        required: false
      Ciudad:
        type: string | nil
        required: false
  Servicio_Anterior:
    type: string | nil
    required: false
  Servicio_Tramite:
    type: nil
    required: false 
  Orden_Servicio:
    type: object | nil
    required: false
  Agendamiento:
    type: object
    required: false
    properties:
      Franja_Agenda:
        type: string | nil
        required: false
      Codigo_Instalador:
        type: string | nil
        required: false
      Enriquecida:
        type: boolean
        required: false
      Agenda:
        type: boolean
        required: false
      ListaCuotas:
        type: array
        required: false
  Cuenta_Facturacion_Anterior:
    type: string | nil
    required: false
  Cuenta_Facturacion_Tramite:
    type: string | nil | object
    required: false
  Orden_Requiere_Disponibilidad:
    type: boolean
    required: false
  Orden_Requiere_Agendamiento:
    type: boolean
    required: false
  Precio_Total_Orden:
    type: string | nil
    required: false
  Adjuntos_Cliente:
    type: string | nil
    required: false
  Adjuntos_Servicio:
    type: string | nil
    required: false
  Caracteristica_Orden:
    type: array
    required: false
  Otros:
    type: string | nil | object
    required: false
  Presencial:
    type: boolean
    required: false
  OfertaSugerida:
    type: array
    required: false
  Reserva:
    type: string | nil
    required: false
example: !include ../../examples/request/putOrderRequest.json