#%RAML 1.0 DataType 
type: object
properties:
  Actualizacion_Extractor:
    type: string
    example: ABCDEFGHI
    required: false
  Asignacion:
    type: object
    required: false
    properties:
      Asignaciones:
        type: array
        required: false
        items:
          type: object
          properties:
            Fecha:
              type: datetime
              example: '2024-10-26T12:00:00Z'
              required: false
            Nivel:
              type: integer
              example: 0
              required: false
            Usuario:
              type: string
              example: ABCDEFGHI
              required: false
      Usuario_Asignado:
        type: string
        example: ABCDEFGHIJKLMNOPQR
        required: false
  Cliente_Retencion:
    type: object
    required: false
    properties:
      Ciudad:
        type: string
        example: ABCDEFGHIJKLMNOPQRST
        required: false
      Departamento:
        type: string
        example: ABCD
        required: false
      Direccion:
        type: string
        example: ABCDEFGHIJKLMNOPQ
        required: false
      Direcciones:
        type: array
        required: false
        items:
          type: object
          properties:
            Cobertura:
              type: object
              properties: {}
            Codigo_DANE:
              type: string
              example: ABCDEFGHIJKLMNOPQR
              required: false
            Codigo_Departamento:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUV
              required: false
            Codigo_Direccion:
              type: string
              example: ''
              required: false
            Codigo_Municipio:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
              required: false
            Codigo_Pais:
              type: string
              example: ABCDEFGHIJK
              required: false
            Departamento:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
              required: false
            Direccion_Normalizada:
              type: string
              example: ABCDEFGH
              required: false
            Estado:
              type: string
              example: ''
              required: false
            Id_Direccion:
              type: integer
              example: 0
              required: false
            Municipio:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
              required: false
            Nombre_Direccion:
              type: string
              example: ''
              required: false
            Seleccionada:
              type: boolean
              example: false
              required: false
            Tipo_Direccion:
              type: string
              example: ABCDEFGH
              required: false
            CoberturasDisponibles:
              type: string
              example: ''
              required: false
            CodigoUso:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTU
              required: false
            TipoDistancia:
              type: string
              example: ABCDEFGHIJKLM
              required: false
      Email:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUV
        required: false
      Nombres:
        type: string
        example: ABCDEFGHIJKLMN
        required: false
      Numero_Documento:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXY
        required: false
      Telefono_Fijo:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXYZAB
        required: false
      Telefono_Movil:
        type: string
        example: ABCDEFG
        required: false
      Tipo_Documento:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWX
        required: false
      UEN:
        type: string
        example: ABCDEF
        required: false
      SegmentoUEN:
        type: string
        example: ABCDE
        required: false
  Estado_Retencion:
    type: object
    required: false
    properties:
      Codigo:
        type: integer
        example: 0
        required: false
      Descripcion:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
        required: false
      Fecha_Actualizacion:
        type: datetime
        example: '2024-10-26T12:00:00Z'
        required: false
      Fecha_Creacion:
        type: datetime
        example: '2024-10-26T12:00:00Z'
        required: false
      Observaciones:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
        required: false
      Usuario:
        type: string
        example: ABCDEFGHI
        required: false
      Fecha_Cierre:
        type: datetime
        example: '2024-10-26T12:00:00Z'
        required: false
  Fecha_Creacion:
    type: datetime
    example: '2024-10-26T12:00:00Z'
    required: false
  Fecha_Modificacion:
    type: datetime
    example: '2024-10-26T12:00:00Z'
    required: false
  Nivel:
    type: integer
    example: 0
    required: false
  Numero_Retencion:
    type: string
    example: ABCDEFG
    required: false
  Retencion:
    type: object
    required: false
    properties:
      Caracteristicas_Retencion:
        type: array
        required: false
        items:
          type: object
          properties:
            Llave:
              type: string
              example: ABCDEFGHIJKLMNOPQ
              required: false
            Valor:
              type: string
              example: ABCDEFGHIJKLMNOPQR
              required: false
      Clasificaciones:
        required: false
        type: array
      Motivo:
        type: integer
        example: 0
        required: false
      Motivo_Descripcion:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVW
        required: false
      Pasos:
        type: array
        required: false
        items:
          type: object
          properties:
            Acciones:
              type: array
              items: {}
            AccionesRetencion:
              type: array
              required: false
              items:
                type: object
                properties:
                  Actualizacion_Extractor:
                    type: string
                    example: ''
                    required: false
                  Clase:
                    type: integer
                    example: 0
                    required: false
                  Clasificacion:
                    type: integer
                    example: 0
                    required: false
                  DatosAccion:
                    type: array
                    required: false
                    items:
                      type: object
                      properties:
                        Codigo:
                          type: string
                          example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
                          required: false
                        Descripcion:
                          type: string
                          example: ABCDEFGHIJKLMNOP
                          required: false
                        Nombre:
                          type: string
                          example: ABCDEFGHIJKLMNOPQRSTUV
                          required: false
                  Descripcion:
                    type: string
                    example: ABCDEFGHIJKLMNOPQR
                    required: false
                  Fecha_Creacion:
                    type: datetime
                    example: '2024-10-26T12:00:00Z'
                    required: false
                  Fecha_Modificacion:
                    type: datetime
                    example: '2024-10-26T12:00:00Z'
                    required: false
                  Id_Accion:
                    type: integer
                    example: 0
                    required: false
                  Niveles:
                    type: array
                    required: false
                    items:
                      type: integer
                  Nombre:
                    type: string
                    example: ABCDEFGHIJKLMNOPQRS
                    required: false
                  Tipo:
                    type: integer
                    example: 0
                    required: false
                  Usuario_Creacion:
                    type: string
                    example: ''
                    required: false
                  Usuario_Modificacion:
                    type: string
                    example: ''
                    required: false
            Descripcion:
              type: string
              example: ABCDEFGHIJKLMNOPQRS
              required: false
            Estado:
              type: object
              required: false
              properties:
                Codigo:
                  type: integer
                  example: 0
                  required: false
                Descripcion:
                  type: string
                  example: ABCDEFGHIJKLMNOPQ
                  required: false
                Fecha_Accion:
                  type: datetime
                  example: '2024-10-26T12:00:00Z'
                  required: false
                Fecha_Paso:
                  type: datetime
                  example: '2024-10-26T12:00:00Z'
                  required: false
                Observaciones:
                  type: string
                  example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
                  required: false
                Usuario:
                  type: string
                  example: ABCDEFGHIJKLMNOPQRSTUVWXY
                  required: false
                Historico:
                  type: array
                  required: false
                  items:
                    type: object
                    properties:
                      Codigo:
                        type: integer
                        example: 0
                        required: false
                      Descripcion:
                        type: string
                        example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
                        required: false
                      Fecha_Accion:
                        type: datetime
                        example: '2024-10-26T12:00:00Z'
                        required: false
                      Fecha_Paso:
                        type: datetime
                        example: '2024-10-26T12:00:00Z'
                        required: false
                      Observaciones:
                        type: string
                        example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
                        required: false
                      Usuario:
                        type: string
                        example: ABCDEFGHIJKLMN
                        required: false
            ID_Paso:
              type: integer
              example: 0
              required: false
            Niveles:
              type: array
              items:
                type: integer
            Nombre:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
              required: false
            Secuencia:
              type: integer
              example: 0
              required: false
            Tipo:
              type: integer
              example: 0
              required: false
            Usuario_Creacion:
              type: string
              example: ABCDEFGHIJKLMNOPQRST
              required: false
            Usuario_Modificacion:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWX
              required: false
      Submotivo:
        type: integer
        example: 0
        required: false
      SubMotivo_Descripcion:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXY
        required: false
      Tipificaciones:
        required: false
        type: array
  Servicio_Retencion:
    type: object
    required: false
    properties:
      BarrioInstalacion:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTU
        required: false
      Calificacion_CHURN:
        type: integer
        example: 0
        required: false
      CiudadInstalacion:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
        required: false
      CodigoCiudad:
        type: string
        example: ABCDEFGHIJKLMNOP
        required: false
      CodigoDepartamento:
        type: string
        example: ''
        required: false
      Cuenta_Facturacion:
        type: string
        example: ABCDEFGH
        required: false
      DepartamentoInstalacion:
        type: string
        example: ABCDEFGHIJ
        required: false
      Direccion_Instalacion:
        type: string
        example: ABCDEFGHIJKLMN
        required: false
      Estado:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
        required: false
      Estados:
        type: array
        required: false
        items:
          type: object
          properties:
            Descripcion:
              type: string
              example: ABCDEFGHIJKLMNOPQ
              required: false
            Fecha:
              type: datetime
              example: '2024-10-26T12:00:00Z'
              required: false
            FechaReconexion:
              type: datetime
              example: '2024-10-26T12:00:00Z'
              required: false
            Tipo:
              type: string
              example: ABCDE
              required: false
      EstratoInstalacion:
        type: string
        example: ABCDEFGHIJKL
        required: false
      Fecha_Inicio_Servicio:
        type: datetime
        example: '2024-10-26T12:00:00Z'
        required: false
      Id_Cuenta_Servicio:
        type: string
        example: ABCDEFGHIJKLMNO
        required: false
      Integration_ID:
        type: string
        example: ABCDEFGHIJKLMNOPQ
        required: false
      LocalidadInstalacion:
        type: string
        example: ABCDEFGH
        required: false
      Marcas:
        type: object
        required: false
        properties:
          Antiguedad:
            type: boolean
            example: false
            required: false
          Beneficio_Retencion:
            type: boolean
            example: true
            required: false
          Beneficio_Vencimiento:
            type: array
            items: {}
          Cantidad_Suspensiones_Temporales:
            type: integer
            example: 0
            required: false
          Cuenta_Control:
            type: boolean
            example: true
            required: false
          Duo:
            type: boolean
            example: false
            required: false
          LTE:
            type: boolean
            example: false
            required: false
          Meses:
            type: integer
            example: 0
            required: false
          Plan_Retencion:
            type: boolean
            example: true
            required: false
          Single:
            type: boolean
            example: false
            required: false
          Sistema_Origen:
            type: string
            example: ABCDEFG
            required: false
          Trio:
            type: boolean
            example: true
            required: false
          Integration_Id:
            type: string
            example: ABCDEFGHIJKLMNOPQRSTU
            required: false
          MesesClausulaPermanencia:
            type: integer
            example: 0
            required: false
          Numero_Agrupacion:
            type: integer
            example: 0
            required: false
          Velocidad:
            type: integer
            example: 0
            required: false
      Numero_Conexion:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVWXYZA
        required: false
      PaisInstalacion:
        type: string
        example: ABCD
        required: false
      Promociones:
        type: array
        required: false
        items:
          type: object
          properties:
            _id:
              type: string
              example: ABCDEFGHIJKLMN
              required: false
            Adjuntos:
              type: array
              items:
                type: object
                properties: {}
            CodigoConvenio:
              type: string
              example: ABCDEFGHIJKLMNOPQR
              required: false
            Descripcion:
              type: string
              example: ABCDEFGH
              required: false
            Estado:
              type: string
              example: ''
              required: false
            Fecha:
              type: datetime
              example: '2024-10-26T12:00:00Z'
              required: false
            FechaFinal:
              type: datetime
              example: '2024-10-26T12:00:00Z'
              required: false
            FechaInicial:
              type: datetime
              example: '2024-10-26T12:00:00Z'
              required: false
            IdBeneficio:
              type: string
              example: ABCDEFGHIJK
              required: false
            Nombre:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZA
              required: false
            Codigo_Configuracion:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZA
              required: false
            ID_Tipo_Promocion:
              type: integer
              example: 0
              required: false
            Numero_Agrupacion:
              type: integer
              example: 0
              required: false
      RutaBundle:
        type: string
        example: ABCDEFGHIJKLMNOP
        required: false
      Tarifa_Actual:
        type: string
        example: ABCDEFGHIJKLM
        required: false
      Tecnologia:
        type: string
        example: ABCDEFGHIJKLMNOP
        required: false
      Tipo_Servicio:
        type: string
        example: ABCDEFGHIJKLMNOPQRSTUVW
        required: false
      UEN:
        type: string
        example: ABCDEFGHIJKLMNOPQRST
        required: false
      Convergencia:
        type: object
        required: false
        properties:
          EsConvergente:
            type: boolean
            example: true
            required: false
          TipoConvergencia:
            type: string
            example: ABCDEFGHIJKLMNOPQRSTUVWXYZA
            required: false
      Id_servicio:
        type: string
        example: ABCDEF
        required: false
  Usuario_Creacion:
    type: string
    example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
    required: false
  Usuario_Modificacion:
    type: string
    example: ABCDEFGHIJKLMNOPQRSTUVW
    required: false
  Numero_Orden:
    type: string
    example: ABCDEFGHIJKLMNOP
    required: false
