#%RAML 1.0 NamedExample
georeferenceResponse:  
  {
    "GetGeoreferenceOut": {
      "Result": {
        "status": "PASS",
        "messageCode": "OK",
        "descripcion": ""
      },
      "Address": {
        "EstadoGeo": "A",
        "CodigoDireccion": 612802304578775600,
        "Latitud": 4.734444173,
        "Longitud": -74.01456934,
        "Estrato": 1,
        "CodigoLote": 27,
        "Destino": 1,
        "Chip": "AAA0225JWHY",
        "Barrio": 8543,
        "Localidad": 1,
        "TipoDistancia": "AE"
      }
    }      
  }
