#%RAML 1.0
title: resource-papi-services
version: v1
baseUri:  https://resource-papi-services-{env}.us-e2.cloudhub.io/{version}
description: Provisioning and lifecycle management of Resource Functions
protocols:
  - HTTPS

traits:
  tibcoHeaders: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/tibcorequestheaders/1.0.6/tibcorequestheaders.raml
  security_client_id: !include exchange_module/35a39a92-efa9-49b6-8f13-d66508fd2f35/security-clientid/1.0.2/security-clientid.raml
mediaType: 
  - application/json


/resourceFunction:
  post:
    is: [security_client_id,tibcoHeaders]
    displayName: normaliceService
    description: perform an action to normalize service
    queryParameters:
      ORIGIN:
        type: string
        example: "WHATSAPP"
        description: "Parameter that allows the origin of the request to be identified"
    body:
      application/json:
        type: !include /datatypes/request/normalice-service.raml
        examples:
          example1:
            displayName: Normalize LB Request
            description: Example of a service normalization lb
            value: !include /examples/request/normalice-service.json
          example2:
            displayName: Normalize TV Request
            description: Example of a service normalization tv
            value: !include /examples/request/normalice-service-tv.json
          example3:
            displayName: Normalize INTERNET Request
            description: Example of a service normalization internet
            value: !include /examples/request/normalice-service-internet.json
          example4:
            displayName: Normalize ACCESS Request
            description: Example of a service normalization access
            value: !include /examples/request/normalice-service-access.json
    responses:
        200:
          body:
            application/json:
              type: !include /datatypes/response/normalice-service.raml
              example: !include /examples/response/normalice-service.json
        400:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-400.json
        401:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-401.json
        404:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-404.json
        500:
          body:
            application/json:
              type: !include /datatypes/response/error.raml
              example: !include /examples/response/error-500.json
  /setResourceNetwork:
    post:
      is: [security_client_id,tibcoHeaders]
      displayName: Set Resource Network
      description: Set Resource Network
      queryParameters:
        ORIGIN:
          type: string
          example: "WHATSAPP"
          description: "Parameter that allows the origin of the request to be identified"
      body:
        application/json:
          type: !include /datatypes/request/set-recurso-red.raml
          examples:
            example1:
              displayName: Set Password  Request
              description: Example for update password
              value: !include /examples/request/set-recurso-red-password.json
            example2:
              displayName: Set Networkname  Request
              description: Example for update networkname
              value: !include /examples/request/set-recurso-red-networkname.json
            example3:
              displayName: Request Complete
              description: Example of a request complete
              value: !include /examples/request/set-recurso-red.json
      responses:
          200:
            body:
              application/json:
                type: !include /datatypes/response/resource-function.raml
                example: !include /examples/response/resource-function.json
          400:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-400.json
          401:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-401.json
          404:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-404.json
          500:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-500.json
  /configureService:
    post:
      is: [security_client_id,tibcoHeaders]
      displayName: configure Service
      description: Updates the WiFi network status (enable/disable); receives network data and returns updated status.
      queryParameters:
        ORIGIN:
          type: string
          example: "WHATSAPP"
          description: "Parameter that allows the origin of the request to be identified"
      body:
        application/json:
          type: !include /datatypes/request/configure-service.raml
          example: !include /examples/request/configure-service.json
      responses:
          200:
            body:
              application/json:
                type: !include /datatypes/response/resource-function.raml
                example: !include /examples/response/resource-function.json
          400:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-400.json
          401:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-401.json
          404:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-404.json
          500:
            body:
              application/json:
                type: !include /datatypes/response/error.raml
                example: !include /examples/response/error-500.json
    /registerDevice:
      post:
        is: [security_client_id,tibcoHeaders]
        displayName: Register Device
        description: Registers a device for a customer; receives data from the device and returns registration confirmation.
        queryParameters:
          ORIGIN:
            type: string
            example: "WHATSAPP"
            description: "Parameter that allows the origin of the request to be identified"
        body:
          application/json:
            type: !include /datatypes/request/register-device.raml
            example: !include /examples/request/register-device.json
        responses:
            200:
              body:
                application/json:
                  type: !include /datatypes/response/register-device.raml
                  example: !include /examples/response/register-device.json
            400:
              body:
                application/json:
                  type: !include /datatypes/response/error.raml
                  example: !include /examples/response/error-400.json
            401:
              body:
                application/json:
                  type: !include /datatypes/response/error.raml
                  example: !include /examples/response/error-401.json
            404:
              body:
                application/json:
                  type: !include /datatypes/response/error.raml
                  example: !include /examples/response/error-404.json
            500:
              body:
                application/json:
                  type: !include /datatypes/response/error.raml
                  example: !include /examples/response/error-500.json
          