wompi:
  auth:
    public_key: "![K6CunbRW/1j2j1Vk0jwiIhkFpozq4/AHK3HelN3GhaNLNhvwT6tQip02YI/shYJj]"
    private_key: "![AmjKxzg73I5nTi7F93LsXf47Fjzb0LwWktSM3rmOuTIGG1eHetb0Sy9BSqIEP9c0]"
    signature: "![nY5D3i+iRodtjhI5W3ks1mZxy1dMNonKUwp9nAB83l7SI6HBqBNBik9W7lhvlhcr]"