#%RAML 1.0 Trait
queryParameters:
  sUsuarioETB: 
    description: Usuario ETB
    type: string | nil
    example: "MDM_Integrador"
    required: false
  sIMEI:
    description: IMEI a consultar
    type: string | nil
    example: "354522058683249"
    required: false
  sTipoDocumento:
    description: Tipo de documento asociado al IMEI
    type: string | nil
    example: "CC"
    required: false
  sNumDocumento:
    description: Número de documento asociado al tipo de identificación
    type: string | nil
    example: "93121568"
    required: false