#%RAML 1.0 DataType 
type: object
properties:
  date:
    type: datetime-only
    example: '2025-05-25T00:00:00'
    required: false
  nip:
    type: string
    example: ''
    required: false
  numOrder:
    type: string
    example: MDM-PLTE-022944
    required: false
  operator:
    type: string
    example: FAKE
    required: false
  operatorCode:
    type: string
    example: '00036'
    required: false
  planType:
    type: string
    example: '2'
    required: false
  phone:
    type: string
    example: '3000000025'
    required: false
  resend:
    type: boolean
    example: false
    required: false
  extendedMonth:
    type: boolean
    example: true
    required: false
  order:
    type: object
    properties:
      flow:
        type: string
        example: LTE
        required: false
