#%RAML 1.0 DataType 
type: object
properties:
  customer:
    type: object
    properties:
      documentType:
        type: string
        example: CC
        required: false
      documentNumber:
        type: string
        example: '1024984165'
        required: false
  order:
    type: object
    properties:
      flow:
        type: string
        example: LTE
        required: false
      lte:
        type: object
        required: false
        properties:
          Portability:
            type: boolean
            example: true
            required: false
          Preactive_Sims:
            type: integer
            example: 1
            required: false
          plan:
            type: string
            example: '6888'
            required: false
          svas:
            type: array
            items:
              type: integer
      fttx:
        type: object
        required: false
        properties:
          address:
            type: string
            example: KR 7 20 00
            required: false
          cityCode:
            type: string
            example: '11001'
            required: false
          departmentCode:
            type: string
            example: '11'
            required: false
          latitude:
            type: number
            example: 4.685688495635986
            required: false
          longitude:
            type: number
            example: -74.07262420654297
            required: false
          stratum:
            type: integer
            example: 4
            required: false
          zone:
            type: string
            example: ''
            required: false
          plan:
            type: string
            example: '6888'
            required: false
          svas:
            type: array
            items:
              type: integer
