#%RAML 1.0 DataType
properties:
  customer:
    type: object
    required: false
    properties:
      documentType:
        type: string
        enum: ["CC","CE","TI","NIT","RUT"]
        required: false
        example: "CC"
      documentNumber:
        type: string
        required: false
        example: "1234567890"
      firstName:
        type: string
        required: false
        example: "MIGUEL"
      surname:
        type: string
        required: false
        example: "SANCHEZ"
      phone:
        type: string
        required: false
        example: "3000000000"
      email:
        type: string
        required: false
        example: "notiene@gmail.com"
      communicationChannels:
        type: string
        required: false
        example: "SMS|WHATSAPP"
      communicationDays:
        type: string
        required: false
        example: "L-V 7-7 & S 8-3"
      communicationUpdate:
        type: boolean
        required: false
        example: true
      expeditionDate:
        type: string
        required: false
        example: "20/10/1956"
      answers:
        type: array
        required: false
        items:
          properties:
            question:
              type: string
              required: false
            answer:
              type: string
              required: false
  order:
    type: object
    required: false
    properties:
      orderNum:
        type: string
        required: false
        example: "MDM-FIBRA-000XXXXXX"
      flow:
        type: string
        enum: ["FIJA","LTE"]
        required: false
        example: "FIJA"
      fttx:
        type: object
        required: false
        properties:
          address:
            type: string
            required: false
          cityCode:
            type: string
            required: false
          departmentCode:
            type: string
            required: false
          latitude:
            type: number
            required: false
          longitude:
            type: number
            required: false
          stratum:
            type: integer
            required: false
          zone:
            type: string
            required: false
          plan:
            type: string
            required: false
          acceptClause:
            type: boolean
            required: false
          acceptContract:
            type: boolean
            required: false
          svas:
            type: array
            items: integer
            required: false
      otpCode:
        type: string
        required: false
        example: "1111"
      otpType:
        type: string
        required: false
        example: "SMS"
      questionnaireId:
        type: string
        required: false
        example: "MDM-FIBRA-000XXXXXX"
  schedule:
    type: object
    required: false
    properties:
      addressComment:
        type: string
        required: false
        example: "Torre 2"
      booking:
        type: boolean
        required: false
        example: true
      date:
        type: string
        required: false
        example: "2025-01-31"
      timeSlot:
        type: string
        required: false
        example: "AM"
  contact:
    type: object
    required: false
    properties:
      email:
        type: string
        required: false
        example: "notiene@gmail.com"
      firstName:
        type: string
        required: false
        example: "MIGUEL"
      phone:
        type: string
        required: false
        example: "3000000000"