autodiscovery: "17871589"
http:
  private:
    port: "8091"
  
configurationTimeout:
  ivr-sapi: "61000"
  salesforce-sapi: "61000"
  services-papi: "61000"
  operations-papi: "61000"
  mongo-sapi: "61000"
  portal-movilidad-sapi: "61000"
  oracle-sapi: "61000"
  remedy-sapi: "61000"
  azure-sapi: "61000"
  sisext-sapi: "61000"
  common-sapi: "61000"

ivr-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-ivr-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/ivr"
  imei:
    #unificar paths!
    path: "/v1/imei/{sIMEI}"
    path_get: "/v1/imei"
  path:
    positiveRecord: "/v1/positiveRecord"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "salesforce-xapi-services"

salesforce-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-salesforce-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basepath: "/salesforce"
  contact:
    path: "/v1/support/contacts"
  customer:
    path: "/v1/support/customers"
  cases:
    path: "/v1/support/cases"
  digitalRecords:
    path: "/v1/support/digitalRecord"
  businessHours:
    path: "/v1/support/businessHours"
  asset:
    path: "/v1/support/asset"
  path:
    updateSalesforceOrder: "/operations/v1/order"
  account:
    path: "/v1/support/account"
  accountEmail:
    path: "/v1/support/account/email"
  casesById:
    path: "/v1/support/cases/id"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "salesforce-xapi-services"
remedy-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-remedy-sapi-services-prod.us-e2.cloudhub.io"      
  port: "8091"
  basepath: "/remedy"
  contact:
    path: "/v1/support/contacts"
  customer:
    path: "/v1/support/customers"     
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
global:
  isProvider: "IsProvider"
  parentSva: "80006"
  parentPkgInstanceId: "ParentPkgInstanceId"
  estadoA: "ACTIVO"
  inactivo: "INACTIVO"
  deliveryMock: "false"
  noProvCase: "|CAMBIO DE ESTRATO|CESION DE CONTRATO|COBRO Y REPOSICION DE EQUIPOS|MATERIALES ADICIONALES|GENERAR CARGOS ADICIONALES|REPOSICION MUERTO EN CAJA|SUSPENDA NO APROVISIONABLE|ANULACION FINANCIAMIENTO|PROMOCION|REPOSICION GARANTIA|PAGO ANTICIPADO|DESBLOQUEO IMEI|PAGO ANTICIPADO|PAGO ANTICIPADO FRAUDE|PAGO ANTICIPADO MORA|"
  venta: "|VENTA LTE|VENTA LTE NCP|VENTA LTE CALL CENTER|VENTA LTE FINANCIADO|VENTA RETAIL|TIENDA WEB|"
  adicionSVA: "ADICION SVA"
  add: "ADD"
  delete: "DELETE"
  numero: "Numero"
  iccid: "ICCID"
  numeroAnterior: "NumeroAnterior"
  serviceClassOcs: "SERVICE CLASSE OCS"
  offerClassOcs: "OFFER CLASS OCS"
  offerClasseOcs: "OFFER CLASSE OCS"
  lteSva2PackageClass: "LTE SVA2 PACKAGE CLASS"
  lteNumberClass: "LTE Number Class"
  lteControlPlanClass: "LTE Control Plan Class"
  ltePostpaidPlanClass: "LTE Postpaid Plan Class"
  ltePrepaidPlanClass: "LTE Postpaid Plan Class"
  cambioPlan: "CAMBIO DE PLAN"
  adicionRetiroSva: "|ADICION SVA|DESACTIVACION SVA|"
  cambioSubscriptor: "CAMBIO SUSCRIPTOR"
  cancelacion: "|CANCELACION VOLUNTARIA|CANCELACION POR PAGO|CANCELACION POR ENTE REGULADOR|"
  reconexion: "|RECONEXION VOLUNTARIA|RECONEXION POR PAGO|RECONEXION POR ENTE REGULADOR|RECONEXION POR PERDIDA O ROBO|"
  suspension: "|SUSPENSION VOLUNTARIA|SUSPENSION POR ENTE REGULADOR|SUSPENSION POR PERDIDA|SUSPENSION POR ROBO|"
  renoRepo: 
    filters: "|RENOVACION EQUIPO|REPOSICION EQUIPO LTE|RENOVACION EQUIPO MAS SIM|RENOVACION SIM|REPOSICION EQUIPO MAS SIM|" 
    packageId: "ETB_ChangeSim"
  cambioNumero: "|MODIFICACION CAMBIO NUMERO LTE|CAMBIO NUMERO LTE NCP|"
  adicionBolsa: "ADICION BOLSA COMPARTIDA"
  reduccionBolsa: "REDUCCION BOLSA COMPARTIDA"
  notifMongoON: "|VENTA LTE|VENTA LTE NCP|VENTA LTE CALL CENTER|VENTA LTE FINANCIADO|VENTA RETAIL|TIENDA WEB|CAMBIO DE PLAN|ADICION SVA|DESACTIVACION SVA|CAMBIO SUSCRIPTOR|CANCELACION VOLUNTARIA|CANCELACION POR PAGO|CANCELACION POR ENTE REGULADOR|RECONEXION VOLUNTARIA|RECONEXION POR PAGO|RECONEXION POR ENTE REGULADOR|RECONEXION POR PERDIDA O ROBO|SUSPENSION VOLUNTARIA|SUSPENSION POR ENTE REGULADOR|SUSPENSION POR PERDIDA|SUSPENSION POR ROBO|RENOVACION EQUIPO|REPOSICION EQUIPO LTE|RENOVACION EQUIPO MAS SIM|RENOVACION SIM|REPOSICION EQUIPO MAS SIM|MODIFICACION CAMBIO NUMERO LTE|CAMBIO NUMERO LTE NCP|" 
  createOrder:
    usuarioMDM: "Tibco"
    passwordMDM: "TibcoPRD_MDM_2017"
    estadoOrden: "Iniciada"
    estadoServicio: "Pendiente"
    filters:
      raiz: "|CLASE PAQUETES Y COMBOS|Broadband Service Class|VoIP Service Class|Television Service Class|LTE Service Class|"
      paquete: "|CLASE PRODUCTOS ETB|CLASE PRODUCTOS ETB COBRE E1 Y E2|CLASE PRODUCTOS ETB COBRE FTTC|CLASE PRODUCTOS ETB COBRE|CLASE PRODUCTOS ETB COBRE ESTRATO3|"
      ofertas: "|VoIP Service Plan Class|High Speed Internet Service Class|LTE Postpaid Plan Class|Television Service Plan Class|LTE Control Plan Class|LTE Prepaid Plan Class|"
      numerosConexion: "|VoIP Number Class|LTE Number Class|"
  isPosPos: "isPosPos"
  isPosPre: "isPosPre"
  isPrePos: "isPrePos"
  isPrePre: "isPrePre"
  none: "None"
  ratePlan: "RATE PLAN"
  addonPackage: "|LTE VOICE PACKAGE CLASS|LTE PROMOTION CLASS|LTE DATA PACKAGE CLASS|LTE SMS PACKAGE CLASS|LTE SVA PACKAGE CLASS|"
  adicionRetiroSvaIds: "|LTE VOICE PACKAGE CLASS|LTE PROMOTION CLASS|LTE DATA PACKAGE CLASS|LTE SMS PACKAGE CLASS|LTE SVA PACKAGE CLASS|"
  renoRepoIds: "|LTE VOICE PACKAGE CLASS|LTE PROMOTION CLASS|LTE DATA PACKAGE CLASS|LTE SMS PACKAGE CLASS|LTE SVA PACKAGE CLASS|"
  invSubOrderTypes: "|VENTA LTE|VENTA LTE FINANCIADO|VENTA LTE NCP|MODIFICACION CAMBIO NUMERO LTE|CAMBIO NUMERO LTE NCP|RENOVACION EQUIPO MAS SIM|RENOVACION SIM|REPOSICION EQUIPO MAS SIM|CANCELACION VOLUNTARIA|CANCELACION POR ENTE REGULADOR|CANCELACION POR PAGO|"
  invCompleteON: "true"
  invHomologationCollection: "CT21AQO"
  invCompleteFilters:
    lteSimcardClass: "LTE Simcard Class"
    iccid: "ICCID"
    serviceId: "ServiceId"
    cancelacion: "CANCELACION"
    lteNumberClass: "LTE Number Class"
    numero: "Numero"
    subOrderType: "|Modificacion Cambio Numero LTE|Modificacion Cambio Numero LTE NCP|"
    numeroAnterior: "NumeroAnterior"
  adicionRetiroFlagMap: "true"
  ack:
    responseCode: "0"
    responseDescription: "ENVIADO"
  output:
    success: "COMPLETE"
    error:
      failed: "FAILED"
      saveInputMongo: "- Failed, unable to save the input in MONGO-DB."
      saveOutputMongo: "- Failed, unable to save the output in MONGO-DB."
      provisioning: "- Failed, problems while Provisioning."
      changePlan : "- Failed, problems while Changing Plan."
      adicionRetiroSva: "- Failed, problems while AdicionRetiroSva."
      changeSubscriptor: "- Failed, problems while Changing Subscriptor."
      cancellation: "- Failed, problems while Cancellating."
      reconnection: "- Failed, problems while Reconnecting."
      suspension: "- Failed, problems while Suspending."
      renoRepo: "- Failed, problems while RenoRepo."
      changeNumber: "- Failed, problems while Changing Number."
      inventaryComplete: "- Failed, problems while Completing Inventory."
      positiveRecord: "- Failed, problems while Inserting Positive Record."
      adicionBolsa: "- Failed, problems while AddingBag."
      reduccionBolsa: "- Failed, problems while ReducingBag."
  insertPositiveRecordON: "true"
  get-account:
    sources: "WebMailEmpresas"
  set-contact:
    sources: "WebMailEmpresas | WebChatEmpresas | WhatsappEmpresas"
  set-cases:
    sources: "WebMailEmpresas | WebChatEmpresas | WhatsappEmpresas"
  update-cases:
    validSources: "WebMailEmpresas"

audits-sapi:
  host: "audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "80"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

service-papi-services:
  protocol: "HTTP"
  host: "mule-worker-internal-service-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/services/v1"
  path:
    provisioningLTE: "/provisioningLTECorp"
    cambioSubscriptor: "/cambioSuscriptorLTECorp"
    cancelacion: "/operations/subscription/{connectionNumber}"
    reconexion: "/operations/subscription/{connectionNumber}"
    suspension: "/operations/subscription/{connectionNumber}"
    changePlan: "/replacement/planLteCorp"
    adicionRetiroSva: "/sva/corp"
    renoRepo: "/replacement"
    sva: "/sva"
    bolsaCompartida: "/bolsaCompartidaLTECorp"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "salesforce-xapi-services"   
  
operations-papi-services:
  protocol: "HTTP"
  host: "mule-worker-internal-operations-papi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/operations/v1"
  path:
    subscriptionReplacement: "/subscription/replacement"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion: "salesforce-xapi-services"
  
mongo-sapi-services:
  protocol: "HTTP"
  host: "mule-worker-internal-mongo-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/mongo/v1"
  postIntegrationMessage:
    path: "/notifySFOrderBillingFinished"
  active-service: "/active-service"
  path:
    agreements: "/agreements"
    agreements-id: "/agreements/{acuerdoId}"
    agreements-logs: "/agreements/logs"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
portal-movilidad-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-portal-movilidad-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/movilidad/v1"
  path:
    updateSalesforceOrder: "/completeInventory"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "salesforce-xapi-services"
  
oracle-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/oracle/v1"
  path:
    getHomologation: "/homologation/{genericValue}/{catalog}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  origenTransaccion": "salesforce-xapi-services"
  
azure-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-azure-sapi-services-prod.us-e2.cloudhub.io"      
  port: "8091"
  basepath: "/azure/v1"
  path:
    agreements: "agreements"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
sisext-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-sisext-sapi-services-prod.us-e2.cloudhub.io"      
  port: "8091"
  basepath: "/sisext/v1"
  path:
    agreements: "createAgreement"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  
common-sapi:
  protocol: "HTTP"
  host: "mule-worker-internal-common-sapi-services-prod.us-e2.cloudhub.io"      
  port: "8091"
  basepath: "/common/v1"
  path:
    trazabilidad: "/traceabilityLogs"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"