#%RAML 1.0 NamedExample
value:
  createRequestNoteOut:
    status: "ERROR"
    description: "ERROR (408): El tipo de datos de selección requiere una especificación de límite.; Field ID - WOI:WorkInfo &lt;7>"