http:
  host: "0.0.0.0"
  private:
    port: "8091"
  path: "/mdm/*"

autodiscovery: "1"

mdm-orchestration-service:
  protocol: "HTTP"
  host: "10.60.22.4"
  port: "81"
  basepath: "MDM_Orquestador"
  path: "MDMOrchestrationService.svc"
  action: "http://orchestration.cloud.etb.com.co/IMDMOrchestrationService/RunOrchService"
  content-type: "text/xml;charset=UTF-8"
  vars:
    externalId: "IdMulesoft"
    system: "Mulesoft"
    id: "PortalLTE_Mulesoft_Generar_Id_Portabilidad"
    version: "1"
    attribute: "TipoConsecutivo"
    value: "IdMensaje"
    valueProcess: "IdProceso"

mdm-wsdl:
  protocol: "HTTPS"
  host: "azlbiaassvc.etb.com.co"
  port: "44381"
  basepath: "/MDM_Data_Services"
  path: "/MDM_Data_Services.asmx"

registerLog:
  path: "/Service/MDM_Data_Services_V2.svc/SOAPMDMDATASERVICES2"
  headers:
    content-type: "text/xml;charset=UTF-8"
    SOAPAction: "http://www.etb.com.co/Gateway/MDM_Data_Services_V2/IMDM_Data_Services_V2/Set_LogTransaccional" 

mdm-logic:
  protocol: "HTTPS"
  host: "azlbiaassvc.etb.com.co"
  port: "44381"
  basePath: "/MDM_Logic_Services/"
  path: "/MDM_Logic_Services.asmx"
  outboundETAdirect:
    mdmFlag: "false"
    mdmString: "MDM-"
    soapAction: "http://www.etb.com.co/Gateway/MDM_Logic_Services/OSM_OFSC_Message"

  v2:
    protocol: "HTTP"
    host: "10.60.22.11"
    port: "81"
    basepath: "/MDM_Logic_Services_V2"
    path: "MDM_Logic_Services_V2.asmx"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"

mdmDataServices:
  protocol: "HTTPS"
  host: "azlbiaassvc.etb.com.co"
  port: "44381"
  basePathV2: "/MDM_Data_Services_V2"
  pathV2: "/MDM_Data_Services_V2.asmx"
  basepath: "/MDM_Data_Services"
  path: "/MDM_Data_Services.asmx"
  response:
    service:
      passCode: "PASS"
  name: "Mulesoft"
  processingServer: "Mulesoft"
  headers:
    content-type: "text/xml"
    SOAPAction: "http://www.etb.com.co/Gateway/MDM_Data_Services_V2/Reglas_Antiguedad_Query"
  registerTramits:
    path: "/ServicioCollection/services/CollectionSiebel.svc"
    headers:
      content-type: "text/xml;charset=UTF-8"
      SOAPAction: "Collection_Siebel/ConsultaFlujoEstadosMasivo"
      SOAPAction2: "Collection_Siebel/RegistroTramiteMasivo"

mdm:
  host: "10.60.22.4"
  port: "81"
  basePath: "/MDM_Operaciones"
  protocol: "HTTP"
  notifyPortability:
    path: "/MDM_ETB_Operaciones.asmx"
    credentials:
      usuarioMDM: "Tibco"
      passwordMDM: "TibcoPruebas2017"
    headers:
      content-type: "text/xml"
      SOAPAction: "'MDM_ETB/Recepcion_Mensajes_Portabilidad'"
 
manageInventory:
  protocol: "HTTP"
  host: "10.60.22.49"
  port: "82"
  basepath: "/"
  path: "GestorInventarios.svc"

configurationTimeout:
  mdm-logic: "90000"
  mdmDataServices: "60000"
  mdm-wsdl: "60000"
  svcFacturacionWs: "60000"
  manageInventory: "60000"
  mdm: "60000"
  notifyBillToMDM: "60000"
  mdmWS: "60000"
  sumaProcess: "60000"
  
svcFacturacion:
  protocol: "HTTPS"
  host: "procesossuma.app.etb.co"
  port: ""
  basePath: "Servicios/Facturacion"
  path: "/SvcFacturacion.svc"
  headers:
    soapAction: "http://tempuri.org/ISvcFacturacion/TrasladoServiciosCuentaClienteyFacturacion"
    contentType: "text/xml"

# Faltan properties de prod
mdmWS:
  protocol: "HTTP"
  host: "orquestadorfibraqa.portallteqa.p.azurewebsites.net"
  basepath: "/OFSC/OFSC.svc/ofsc"
  content: "text/xml"
  complete:
    action: "http://tempuri.org/IOFSC/CompletarOrden"
  suspend:
    action: "http://tempuri.org/IOFSC/SuspenderOrden"
  notdone:
    action: "http://tempuri.org/IOFSC/NoCompletarOrden"
    
sumaProcess:
  protocol: "HTTP"
  host: "procesossuma.app.etb.co"
  port: ""
  basepath: "/servicios"
  serviceOrder:
    path: "/ServicioOrden/svcOrden.svc"
    headers:
      contentType: "text/xml"
      soapAction: "http://tempuri.org/IsvcOrden/ActualizarCaracteristicaOrden"        