#%RAML 1.0 DataType
properties:
  name:
    type: string
    description: Name
    example: "Salesforce"
  correlationId:
    type: string
    description: Correlation ID
    example: "a054y00000lCrKJAA0211202191631"
  processingServer:
    type: string
    description: Processing Server
    example: "Tibco"