#%RAML 1.0 DataType
displayName: CUN Cancellation Response
type: object

properties:
  code:
    type: string
    example: "200"
    required: true
  message:
    type: string
    example: "CUN cancelled correctly"
    required: true
  cun:
    type: object
    required: true
    properties:
      errorCode:
        type: string
        example: "5013"
        required: false
      errorMessage:
        type: string
        example: "TRANSACCION EXITOSA"
        required: false

examples:
  cunTraceResponse: !include ../../examples/responses/patch-cun-cancellation-response.json