#%RAML 1.0 DataType
properties:
  status:
    type: string
    required: true
    example: "OK"
  description:
    type: string
    required: true
    example: "success"
  fileName:
    type: string
    required: false
    example: "000022024060632238-CC.pdf"
  fileContent:
    type: any
    required: false
    example: "Base64 content"