#%RAML 1.0 DataType
displayName: CUN History Response
type: object

properties:
  code:
    type: string
    example: "201"
    required: true
  message:
    type: string
    example: "CUN Trace Correctly"
    required: true
  cun:
    type: object
    required: true
    properties:
      history:
        type: array
        required: true
        items:
          type: object
          properties:
            cunNumber:
              type: string
              example: "CUN986532"
              required: false
            system:
              type: string
              example: "MDM"
              required: false
            orderNumber:
              type: string
              example: "MDM-FIBRA-0006481210"
              required: false
            cunDate:
              type: string
              example: "16/05/2026 14:40:09"
              required: false
            connectionNumber:
              type: string
              example: "CONN54976"
              required: false
            errorCode:
              type: string
              example: "5013"
              required: false
            errorMessage:
              type: string
              example: "TRANSACCION EXITOSA"
              required: false

examples:
  cunTraceResponse: !include ../../examples/responses/post-cun-history-response.json