#%RAML 1.0 DataType
type: object

properties:
  code:
    type: string
    required: false
  message:
    type: string
    required: false
  cun:
    type: object
    required: false
    properties:
      CodError:
        type: string
        required: false
      NomError:
        type: string
        required: false

examples:
  cunTraceResponse: !include ../../examples/responses/post-cun-trace-response.json