#%RAML 1.0 NamedExample
value:
  Header: 
    id: a054y00000lCrKJAA0211202191631,     
    operation: SetBillingAccount,
    requestSystem: WS.BillingLTECorporate,
    version: 1,
    type: IN,
    reqType: SYNC,
    requestDateTime: "2021-11-22T11:43:36"
    responseDateTime: "2021-11-22T11:43:36"
  Body: 
    Set_BillingAccount: 
      WSRequestHeader: 
        system: 
          name: Salesforce,
          correlationId: a054y00000lCrKJAA0211202191631,
          processingServer: Tibco
        property: 
            Property: 
              name: null,
              value: value
      WSRequestBody: 
        id: a054y00000lCrKJAA0, 
        document_type: NIT, 
        document_number: 900151140,
        billing_account: 12054149933, 
        parent_billing_account: null,
        state: A,
        market: JURIDICO EMPRESAS,
        frequency: null,
        creator_user: lisseth.munozr2.pr@etb.com.co,
        modifier_user: lisseth.munozr2.pr@etb.com.co,
        email: gerencia@davincitapetes.com,
        address: KR 16 50 48,
        country: Colombia,
        department: BOGOTÁ, D.C., 
        city: BOGOTÁ, D.C.,
        neighborhood: null,
        location: null,   
        stratum: null, 
        billing_cycle: 18,
        long_time: null,
        invoice_type: null,
        invoice_support: null, 
        type_delivery_invoice: Electronica, 
        charging_cycle: null, 
        code_charging_cycle: null, 
        date_cut_billing: null,
        taxes: null,      
        modified_MDM: 1,
        order_order_related: null,
        salesforce_invoice_id: a054y00000lCrKJAA0,
        set_type: I