#%RAML 1.0 NamedExample
value:
  part1:
    CancelScheduleInput:
      WSRequestHeader2:
        System:
          name: "MDM"
          correlationID: "MIETB-1112021-654652"
          processingServer: "MDM"
      CancelScheduleIN:
        IdIncidencia: "INC000006073207"
        IdAgenda: 10640276
        Estado: "Success"