#%RAML 1.0 NamedExample
value:
  accion: "CREAR REQUERIMIENTO PORTAFOLIO"
  idSalesforce: "5004y00001qgCI9AAM"
  idCtaCliente: "0014000000ucyT8AAI"
  nombreCliente: "CORPORACION UNIVERSITARIA MINU"
  apellidosCliente: "."
  telefonoCliente: "2916520"
  emailCliente: ""
  tipoIdentificacion: "0"
  numeroIden: "800116217"
  ubicacion: "DIAGONAL 83 NO. 72-55"
  codPais: "57"
  servicio: "Conectividad Avanzada IP"
  servicioAfectado: "CAV30CI996583"
  nota: "Buenas tardes,Por medio del presente solicitamos por favor.1. Anunciar en MPLS los siguientes segmentos de red"
  resumen: "Solicitud de anunciar redes en mpls y agregar una línea en la lista de acceso"
  tipoOrden: "REQ_SOLICITUD TECNICA"
  fuenteReportada: "5000"
  nivel1: "ASEGURAMIENTO"
  nivel2: ""
  nivel3: ""
  serial: ""
  grupoGestor: "HDPREMIUM_PREMIUM 3"
  grupoAsg: "HDPREMIUM_PREMIUM 3"
  codMunCliente: "11001"
  codEdoCliente: "11"
  nroCaso: "02582741"