#%RAML 1.0 DataType
type: object
properties:
  ObtenerCuestionario:
    type: object
    properties:
      objSolicitud?:
        type: object
        properties:
          TipoIdentificacion:
            type: string
            example: "CC"
          Identificacion:
            type: string
            example: "1235413456"
          RegValidacion:
            type: string
            example: "?"
          Apellido:
            type: string
            example: "PEREZ"
          FechaExpedicion:
            type: string
            example: "24/09/2008 02:40:50.3456"
            minLength: 1
          Nombre?:
            type: string | nil
            example: "JUAN"
          Modelo?:
            type: string | nil
            example: "2"
          Departamento?:
            type: integer | nil
            example: 1
          Ciudad?:
            type: integer | nil
            example: 1
          Asesor?:
            type: string | nil
            example: "?"
          CanalVenta?:
            type: string | nil
            example: "?"
          Proveedor?:
            type: string | nil
            example: "?"
          Portal?:
            type: string | nil
            example: "?"
          Tramite?:
            type: string | nil
            example: "?"
          Tipo_Consulta?:
            type: string | nil
            example: "?"
          Sistema_Origen?:
            type: string | nil
            example: "Portal"
          Numero_Contacto?:
            type: string | nil
            example: "1139383736"
          Tipo?:
            type: string | nil
            example: "?"
          Estrato?:
            type: string | nil
            example: "?"
          NivelRiesgo?:
            type: string | nil
            example: "?"
          Score?:
            type: string | nil
            example: "?"