#%RAML 1.0 DataType 
type: object
properties:
  OrderFulfilment:
    type: object
    properties:
      Identification:
        type: object
        properties:
          ID:
            type: string
            required: false
          BusinessComponentID:
            type: string
            required: false
          ApplicationObjectKeyID:
            type: string
            required: false
          RevisionNumber:
            type: string
            required: false
      SalesOrder:
        type: object
        properties:
          OrderDateTime:
            type: string
            required: false
          DeliveryDateTime:
            type: string
            required: false
          TypeCode:
            type: string
            required: false
          FulfilmentPriorityCode:
            type: string
            required: false
          FulfilmentModeCode:
            type: string
            required: false
          StatusCode:
            type: string
            required: false
      BusinessReference:
        type: object
        properties:
          Id:
            type: string
            required: false
          ComponentId:
            type: string
            required: false
          ApplicationObjectKeyId:
            type: string
            required: false
      CustomerPartyAccount:
        type: object
        properties:
          Identification:
            type: object
            properties:
              ID:
                type: string
                required: false
              BusinessComponentID:
                type: string
                required: false
              ApplicationObjectKeyID:
                type: string
                required: false
          Name:
            type: string
            required: false
          Address:
            type: object
            properties:
              Identification:
                type: object
                properties:
                  ID:
                    type: string
                    required: false
                  BusinessComponentID:
                    type: string
                    required: false
                  ApplicationObjectKeyID:
                    type: string
                    required: false
              LineOne:
                type: string
                required: false
              CityName:
                type: string
                required: false
              StateName:
                type: string
                required: false
              CountryCode:
                type: string
                required: false
              CountryName:
                type: string
                required: false
              GisID:
                type: string
                required: false
              Latitude:
                type: string
                required: false
              Longitude:
                type: string
                required: false
              CityCode:
                type: string
                required: false
              StateCode:
                type: string
                required: false
              PurposeCode:
                type: string
                required: false
              Reference:
                type: string
                required: false
              Technology:
                type: object
                properties:
                  Type:
                    type: string
                    required: false
                  CoverageType:
                    type: string
                    required: false
                  CoverageIndicator:
                    type: string
                    required: false
                  CoverageName:
                    type: string
                    required: false
                  Zone:
                    type: string
                    required: false
          ContactPerson:
            type: object
            properties:
              FirstName:
                type: string
                required: false
              FamilyName:
                type: string
                required: false
              CompleteNumber:
                type: string
                required: false
          TypeCode:
            type: string
            required: false
          Custom:
            type: object
            properties:
              DocumentType:
                type: string
                required: false
              DocumentNumber:
                type: string
                required: false
      Custom:
        type: object
        properties:
          OrderSubType:
            type: string
            required: false
          SignedDocumentIndicator:
            type: string
            required: false
      PartyIdentification:
        type: object
        properties:
          ID:
            type: string
            required: false
          BusinessComponentID:
            type: string
            required: false
          ApplicationObjectKeyID:
            type: string
            required: false
      SalesOrderLine:
        type: array
        items:          
          properties:
            Identification:
              type: object
              properties:
                ID:
                  type: string
                  required: false
                BusinessComponentID:
                  type: string
                  required: false
                ApplicationObjectKeyID:
                  type: string
                  required: false
            OrderQuantity:
              type: string
              required: false
            ServiceActionCode:
              type: string
              required: false
            FulfilmentModeCode:
              type: string
              required: false
            ParentSalesOrderLineIdentification:
              type: object
              properties:
                ID:
                  type: string
                  required: false
                BusinessComponentID:
                  type: string
                  required: false
                ApplicationObjectKeyID:
                  type: string
                  required: false
            RootParentSalesOrderLineIdentification:
              type: object
              properties:
                ID:
                  type: string
                  required: false
                BusinessComponentID:
                  type: string
                  required: false
                ApplicationObjectKeyID:
                  type: string
                  required: false
            StatusCode:
              type: string
              required: false
            ServiceAddress:
              type: object
              properties:
                Identification:
                  type: object
                  properties:
                    ID:
                      type: string
                      required: false
                    BusinessComponentID:
                      type: string
                      required: false
                    ApplicationObjectKeyID:
                      type: string
                      required: false
                LineOne:
                  type: string
                  required: false
                CityName:
                  type: string
                  required: false
                StateName:
                  type: string
                  required: false
                CountryCode:
                  type: string
                  required: false
                CountryName:
                  type: string
                  required: false
                GisID:
                  type: string
                  required: false
                Latitude:
                  type: string
                  required: false
                Longitude:
                  type: string
                  required: false
                CityCode:
                  type: string
                  required: false
                StateCode:
                  type: string
                  required: false
                PurposeCode:
                  type: string
                  required: false
                Reference:
                  type: string
                  required: false
                Technology:
                  type: object
                  properties:
                    Type:
                      type: string
                      required: false
                    CoverageType:
                      type: string
                      required: false
                    CoverageIndicator:
                      type: string
                      required: false
                    CoverageName:
                      type: string
                      required: false
                    Zone:
                      type: string
                      required: false
            ItemReference:
              type: object
              properties:
                ItemIdentification:
                  type: object
                  properties:
                    ID:
                      type: string
                      required: false
                    BusinessComponentID:
                      type: string
                      required: false
                    ApplicationObjectKeyID:
                      type: string
                      required: false
                Name:
                  type: string
                  required: false
                ServiceIndicator:
                  type: string
                  required: false
                TypeCode:
                  type: string
                  required: false
                NetworkIndicator:
                  type: string
                  required: false
                PrimaryClassificationCode:
                  type: string
                  required: false
            SalesOrderSchedule:
              type: object
              properties:
                RequestedDeliveryDate:
                  type: string
                  required: false
                ExpectedDeliveryDate:
                  type: string
                  required: false
                ShipTo:
                  type: object
                  properties:
                    GisID:
                      type: string
                      required: false
                    Latitude:
                      type: string
                      required: false
                    Longitude:
                      type: string
                      required: false
                    CityCode:
                      type: string
                      required: false
                    StateCode:
                      type: string
                      required: false
                    PurposeCode:
                      type: string
                      required: false
                    Reference:
                      type: string
                      required: false
                    Technology:
                      type: object
                      properties:
                        Type:
                          type: string
                          required: false
                        CoverageType:
                          type: string
                          required: false
                        CoverageIndicator:
                          type: string
                          required: false
                        CoverageName:
                          type: string
                          required: false
                        Zone:
                          type: string
                          required: false
            OwnerPartyReference:
              type: object
              properties:
                ID:
                  type: string
                  required: false
                BusinessComponentID:
                  type: string
                  required: false
                ApplicationObjectKeyID:
                  type: string
                  required: false
            ScheduleOrderIndicator:
              type: string
              required: false
            Discounts:
              type: string
              required: false
            SpecificationGroupXA:
              type: array
              items:
                properties:
                  XAID:
                    type: string
                    required: false
                  ParentID:
                    type: string
                    required: false
                  ID:
                    type: string
                    required: false
                  ActionCode:
                    type: string
                    required: false
                  Name:
                    type: string
                    required: false
                  Value:
                    type: string
                    required: false
            Custom:
              type: object
              properties:
                PartNumber:
                  type: string
                  required: false
                AssetIntegrationID:
                  type: string
                  required: false
      Scheduling:
        type: object
        properties:
          SubOrderType:
            type: string
            required: false
      AltKey:
        type: array
        items:
          properties:
            AltKeyName:
              type: string
              required: false
            AltKeyValue:
              type: string
              required: false
  BillingProcess:
    type: object
    properties:
      CustomerBill:
        type: object
        properties:
          InvoicingCycle:
            type: string
            required: false
