#%RAML 1.0 DataType
properties:
  cliente:
    type: object
    properties:
      email:
        type: string
        example: "testing@etb.com"
        required: true
  servicio:
    type: object
    properties:
      eid:
        type: string
        example: "CS-2203942"
        required: true
      cuentaServicio:
        type: string
        example: "CS-2203942"
        required: false
      terceros:
        type: object
        required: true
        properties:
          sku:
            type: array
            items:
              properties:
                code:
                  type: string
                  example: "PREDIR"
                amount:
                  type: integer
                  example: 1