#%RAML 1.0 DataType
properties:
  cliente:
    type: object
    properties:
      email:
        type: string
        example: "testing@etb.com"
        required: true
  servicio:
    type: object
    properties:
      eid:
        type: string
        example: "CS-2203942"
        required: true
      cuentaServicio:
        type: string
        example: "CS-2203942"
        required: false