#%RAML 1.0 DataType
properties:
  cliente:
    type: object
    properties:
      email:
        type: string
        example: "testing@etb.com"
        required: true
      nombres:
        type: string
        example: "DemoETB Test"
        required: true
      apellidos:
        type: string
        example: "Prueba Prueba"
        required: true
      direccion:
        type: string
        example: "KR 7 20 00"
        required: true
      municipio:
        type: string
        example: "BOGOTA D.C."
        required: true
      suites:
        type: string
        example: "HOG"
        required: true
  servicio:
    type: object
    properties:
      eid:
        type: string
        example: "CS-2203942"
        required: true
      cuentaServicio:
        type: string
        example: "CS-2203942"
        required: false
      terceros:
        type: object
        required: false
        properties:
          sku:
            type: array
            items:
              properties:
                code:
                  type: string
                  example: "PREDIR"
                amount:
                  type: integer
                  example: 1