#%RAML 1.0 DataType
type: object
properties:
  creationDate: 
    description: Petition creation date - current date
    type: datetime-only
    example: 2021-11-22T11:43:36
    required: true
  operatorCode:
    description: Operator code
    type: string
    example: "00007"
    required: true
    minLength: 1
  operation:
    description: Operation code
    type: string
    example: "00"
    minLength: 1
    maxLength: 2
    pattern: "[0-9]*"
    required: true
  TD:
    description: Type of Document
    type: string
    minLength: 1 
    maxLength: 2
    example: "CC"
    required: true
  ext:
    description: Extension of the document
    type: string
    minLength: 1
    example: "pdf"
    required: true