#%RAML 1.0 DataType
properties:
  orderNumber:
    type: string
    example: "MDM-MAY-00001"
  serial:
    type: string
    example: "XYZ"
  ontType:
    type: string
    example: "XYZ"
  cvlanHSI?:
    type: string
    example: "XYZ"
  cvlanTR69?:
    type: string
    example: "XYZ"
  cvlanVOIP?:
    type: string
    example: "XYZ"
  transactType:
    enum: [Commit, Rollback]
    example: "Commit"
  serialOld:
    type: string | nil
    required: false
    example: "XYZ"
  ontTypeOld:
    type: string | nil
    required: false
    example: "XYZ"
    
example: !include ../../examples/requests/ProvisioningExperience.json