#%RAML 1.0 DataType
properties:
  orderNumber:
    type: string
    example: "MDM-MAY-0040"
  speed:
    type: string
    example: "10M"
    required: false
  uploadSpeed:
    type: string
    example: "10M"
  downloadSpeed:
    type: string
    example: "100M"
  productId:
    type: string
    example: "0001"
  serviceType:
    type: string
    example: ""
