#%RAML 1.0 DataType
properties:
  numeroOrden: string
  tipo: string
  direccionPF: string
  pf: string
  coorX?: number
  coorY?: number
  latitud: number
  longitud: number
  mt: string
  bt: string
  ap: string
  tipoDeIntervencion: string
  alturaPoste: number
  longTramo: number
  tipoInfraestructura: string
  diametroCable: number
  tipoCable: string
  apoyoaUtilizar: number
  diametroApoyo: number
  configuracionApoyo: string
  instalacionReserva: string
  instalaElementoPasivo: string
  localidadMunicipio: string
  barrio: string
  observaciones?: string