#%RAML 1.0 DataType
type: object
properties:
  inbound_interface_request:
    type: object
    properties:
      head:
        type: object
        properties:
          trx_id:
            type: string
          component:
            type: string
          processing_mode:
            type: string
            required: false
          upload_type:
            type: string
          id:
            type: string
            required: false
          date:
            type: string
            required: false
          allow_change_date:
            type: string
            required: false
          appointment:
            type: array
            required: false
            items:
              properties:
                keys:
                  type: array
                  required: false
                  items:
                    type: string
                action_if_completed:
                  type: string
                  required: false
          inventory:
            type: array
            required: false
            items:
              properties:
                keys:
                  type: array
                  required: false
                  items:
                    type: string
                upload_type:
                  type: string
                  required: false
          properties_mode:
            type: string
            required: false
          provider_group:
            type: string
            required: false
          default_appointment_pool:
            type: string
            required: false
      data:
        type: object
        properties:
          commands:
            type: array
            items:
              properties:
                date:
                  type: string
                  required: false
                type: 
                  type: string
                external_id:
                  type: string
                  required: false
                fallback_external_id:
                  type: string
                  required: false
                appointment:
                  type: array
                  required: false
                  items:
                    properties:
                      appt_number:
                        type: string
                        required: false
                      team_id:
                        type: string
                        required: false
                      customer_number:
                        type: string
                        required: false
                      worktype:
                        type: string
                        required: false
                      worktype_label:
                        type: string
                        required: false
                      service_window_start:
                        type: string
                        required: false
                      service_window_end:
                        type: string
                        required: false
                      sla_window_start:
                        type: string
                        required: false
                      sla_window_end:
                        type: string
                        required: false
                      time_of_booking:
                        type: string
                        required: false
                      time_slot:
                        type: string
                        required: false
                      duration:
                        type: string
                        required: false
                      name:
                        type: string
                        required: false
                      message_methods:
                        type: string
                        required: false
                      phone:
                        type: string
                        required: false
                      email:
                        type: string
                        required: false
                      cell:
                        type: string
                        required: false
                      address:
                        type: string
                        required: false
                      city:
                        type: string
                        required: false
                      state:
                        type: string
                        required: false
                      zip:
                        type: string
                        required: false
                      language:
                        type: string
                        required: false
                      reminder_time:
                        type: string
                        required: false
                      time_zone:
                        type: string
                        required: false
                      coordx:
                        type: string
                        required: false
                      coordy:
                        type: string
                        required: false
                      points:
                        type: string
                        required: false
                      properties:
                        type: array
                        required: false
                        items:
                          properties:
                            label:
                              type: string
                            value:
                              type: string
                      inventories:
                        type: array
                        required: false
                        items:
                          properties:
                            properties:
                              type: array
                              required: false
                              items:
                                properties:
                                  label:
                                    type: string
                                  value:
                                    type: string
                            files:
                              type: array
                              required: false
                              items:
                                properties:
                                  property_label: 
                                    type: string
                                  filename:
                                    type: string
                                  mime_type:
                                    type: string
                                  encoding:
                                    type: string
                                  contents:
                                    type: string
                            userdata:
                              type: string
                              required: false
                      links:
                        type: array
                        required: false
                        items:
                          properties:
                            erase_links:
                              type: array
                              required: false
                              items:
                                type: string
                            link_start_together:
                              type: array
                              required: false
                              items:
                                properties:
                                  appt_number:
                                    type: string
                                    required: false
                                  customer_number:
                                    type: string
                                    required: false
                                  name:
                                    type: string
                                    required: false
                            link_start_after:
                              type: array
                              required: false
                              items:
                                properties:
                                  appt_number:
                                    type: string
                                    required: false
                                  customer_number:
                                    type: string
                                    required: false
                                  name:
                                    type: string
                                    required: false
                            link:
                              type: array
                              required: false
                              items:
                                properties:
                                  appt_number:
                                    type: string
                                    required: false
                                  customer_number:
                                    type: string
                                    required: false
                                  name:
                                    type: string
                                    required: false
                                  link_type:
                                    type: string
                                    required: false
                                  min_interval:
                                    type: string
                                    required: false
                                  max_interval:
                                    type: string
                                    required: false
                      files:
                        type: array
                        required: false
                        items:
                          properties:
                            property_label: 
                              type: string
                            filename:
                              type: string
                            mime_type:
                              type: string
                            encoding:
                              type: string
                            contents:
                              type: string
                      provider_preferences:
                        type: array
                        required: false
                        items:
                          properties:
                            external_id:
                              type: string
                            type:
                              type: string
                      required_inventories:
                        type: array
                        required: false
                        items:
                          properties:
                            type:
                              type: string
                            model:
                              type: string
                              required: false
                            quantity:
                              type: string
                      action_if_completed:
                        type: string
                        required: false
                      userdata:
                        type: string
                        required: false
                inventories:
                  type: array
                  required: false
                  items:
                    properties:
                      properties:
                        type: array
                        required: false
                        items:
                          properties:
                            label:
                              type: string
                            value:
                              type: string
                      files:
                        type: array
                        required: false
                        items:
                          properties:
                            property_label: 
                              type: string
                            filename:
                              type: string
                            mime_type:
                              type: string
                            encoding:
                              type: string
                            contents:
                              type: string
                      userdata:
                        type: string
                userdata:
                  type: string
                  required: false
          providers:
            type: array
            required: false
            items:
              properties:
                external_id:
                  type: string
                  required: false
                fallback_external_id:
                  type: string
                  required: false
                appointment:
                  type: array
                  required: false
                  items:
                    properties:
                      appt_number:
                        type: string
                        required: false
                      team_id:
                        type: string
                        required: false
                      customer_number:
                        type: string
                        required: false
                      worktype:
                        type: string
                        required: false
                      worktype_label:
                        type: string
                        required: false
                      service_window_start:
                        type: string
                        required: false
                      service_window_end:
                        type: string
                        required: false
                      sla_window_start:
                        type: string
                        required: false
                      sla_window_end:
                        type: string
                        required: false
                      time_of_booking:
                        type: string
                        required: false
                      time_slot:
                        type: string
                        required: false
                      duration:
                        type: string
                        required: false
                      name:
                        type: string
                        required: false
                      message_methods:
                        type: string
                        required: false
                      phone:
                        type: string
                        required: false
                      email:
                        type: string
                        required: false
                      cell:
                        type: string
                        required: false
                      address:
                        type: string
                        required: false
                      city:
                        type: string
                        required: false
                      state:
                        type: string
                        required: false
                      zip:
                        type: string
                        required: false
                      language:
                        type: string
                        required: false
                      reminder_time:
                        type: string
                        required: false
                      time_zone:
                        type: string
                        required: false
                      coordx:
                        type: string
                        required: false
                      coordy:
                        type: string
                        required: false
                      points:
                        type: string
                        required: false
                      properties:
                        type: array
                        required: false
                        items:
                          properties:
                            label:
                              type: string
                            value:
                              type: string
                      inventories:
                        type: array
                        required: false
                        items:
                          properties:
                            properties:
                              type: array
                              required: false
                              items:
                                properties:
                                  label:
                                    type: string
                                  value:
                                    type: string
                            files:
                              type: array
                              required: false
                              items:
                                properties:
                                  property_label: 
                                    type: string
                                  filename:
                                    type: string
                                  mime_type:
                                    type: string
                                  encoding:
                                    type: string
                                  contents:
                                    type: string
                            userdata:
                              type: string
                              required: false
                      links:
                        type: array
                        required: false
                        items:
                          properties:
                            erase_links:
                              type: array
                              required: false
                              items:
                                type: string
                            link_start_together:
                              type: array
                              required: false
                              items:
                                properties:
                                  appt_number:
                                    type: string
                                    required: false
                                  customer_number:
                                    type: string
                                    required: false
                                  name:
                                    type: string
                                    required: false
                            link_start_after:
                              type: array
                              required: false
                              items:
                                properties:
                                  appt_number:
                                    type: string
                                    required: false
                                  customer_number:
                                    type: string
                                    required: false
                                  name:
                                    type: string
                                    required: false
                            link:
                              type: array
                              required: false
                              items:
                                properties:
                                  appt_number:
                                    type: string
                                    required: false
                                  customer_number:
                                    type: string
                                    required: false
                                  name:
                                    type: string
                                    required: false
                                  link_type:
                                    type: string
                                  min_interval:
                                    type: string
                                    required: false
                                  max_interval:
                                    type: string
                                    required: false
                      files:
                        type: array
                        required: false
                        items:
                          properties:
                            property_label: 
                              type: string
                            filename:
                              type: string
                            mime_type:
                              type: string
                            encoding:
                              type: string
                            contents:
                              type: string
                      provider_preferences:
                        type: array
                        required: false
                        items:
                          properties:
                            external_id:
                              type: string
                            type:
                              type: string
                      required_inventories:
                        type: array
                        required: false
                        items:
                          properties:
                            type:
                              type: string
                            model:
                              type: string
                              required: false
                            quantity:
                              type: string
                      action_if_completed:
                        type: string
                        required: false
                      userdata:
                        type: string
                        required: false
                inventories:
                  type: array
                  required: false
                  items:
                    properties:
                      properties:
                        type: array
                        required: false
                        items:
                          properties:
                            label:
                              type: string
                            value:
                              type: string
                      files:
                        type: array
                        required: false
                        items:
                          properties:
                            property_label: 
                              type: string
                            filename:
                              type: string
                            mime_type:
                              type: string
                            encoding:
                              type: string
                            contents:
                              type: string
                      userdata:
                        type: string
                userdata:
                  type: string
                  required: false 