#%RAML 1.0 DataType
properties:
  tipoDocumento:
    type: string
    example: "CC"
  numeroDocumento:
    type: string
    example: "123456789"
  ip:
    type: string
    required: true
    description: "IP del cliente o servidor desde donde se realizar la tx"
    maxLength: 20
    example: ""
  navegador: 
    type: string
    required: true
    description: "Navegador desde donde se realizar la transacción"
    example: ""
  nombre_equipo: 
    type: string
    required: true
    description: "Nombre de la maquina o equipo desde donde se realiza la transacción"
    example: ""
  usuario: 
    type: string
    required: true
    description: "Usuario/Cliente que realiza el registro de datos"
    example: ""
  data:
    type: array
    minItems: 1
    items:
      type: object
      properties:
        canal: 
          type: string
          required: true
          description: "Canal para ser contactado"
          example: "123"
        valor: 
          type: string
          required: true
          description: "Email o telefono"
          example: ""
        autorizado: 
          type: boolean
          required: true
          description: "Si autoriza true, no autoriza false"
          example: true