#%RAML 1.0 DataType
properties:
  ip:
    type: string
    required: true
    description: "IP del cliente o servidor desde donde se realizar la tx"
    maxLength: 20
    example: ""
  navegador: 
    type: string
    required: true
    description: "Navegador desde donde se realizar la transacción"
    example: ""
  nombre_equipo: 
    type: string
    required: true
    description: "Nombre de la maquina o equipo desde donde se realiza la transacción"
    example: ""
  usuario: 
    type: string
    required: true
    description: "Usuario/Cliente que realiza el registro de datos"
    example: ""
  cliente:
    type: string
    required: true
    description: "numero de documento del usuario"
    example: ""
  valor_canal:
    type: string
    required: true
    description: "Email o telefono del usuario para buscar duplicado"
    example: ""