#%RAML 1.0 DataType
properties:
  documento:
    type: string
    enum: ["COMUNICACIONES_COBRANZA_CANALES", "COMUNICACIONES_COBRANZA_HORARIOS", "COMUNICACIONES_COBRANZA_OBLIGATORIEDAD"]
    required: true
    description: "Solo los 3 documentos asociado con la ley"
    example: "COMUNICACIONES_COBRANZA_CANALES"
  codigo: 
    type: number
    required: true
    description: "Si es activo 1 inactivo 0"
    example: 1
  valor: 
    type: string
    required: true
    description: "nuevo valor del código"
    example: "nuevo valor"
  descripcion: 
    type: string
    required: true
    description: "Descripcion paramtetro"
    example: "1"