#%RAML 1.0 DataType

properties:
  v1:WSRequestHeader2:
    type: object
    required: true
    properties:
      v1:System:
        type: object
        required: true
        properties:
          v1:name:
            type: string
            required: true
            minLength: 1
            example: CFG
          v1:correlationID:
            type: string
            required: true
            minLength: 1
            example: 1-QHF5AT0
          v1:processingServer:
            type: string
            required: true
            minLength: 1
            example: CFG
      v1:Property:
        type: object
        required: true
        properties:
          v1:name:
            type: string
            required: true
            minLength: 1
            example: CFG
          v1:value:
            type: string
            required: true
            minLength: 1
            example: CFG
  proc:ProcessRequest:
    type: object
    required: true
    properties:
      proc:Action:
        type: string
        required: true
        minLength: 1
        example: COMPLETE
      proc:Order:
        type: string
        required: true
        minLength: 1
        example: 1-QHF5AT0
      proc:Reason:
        type: string
        required: true
        minLength: 1
        example: CFG-2333
      proc:Comments:
        type: string
        required: false
        minLength: 1
        example: Enviado desde CFG
