#%RAML 1.0 DataType
type: object
properties:
  Origen:
    type: string
    required: true
    minLength: 1
  DatosRegistro:    
    properties:
      RequestRegistroTramiteMasivo:
        type: array
        items:
          properties:            
            Pedido:
              type: string
              required: true
              minLength: 1
            Abonado:
              type: string
              required: true
              minLength: 1
            TipoTramite:
              type: string
              required: true
              minLength: 1
            FechaIngresoTramite:
              type: string
              required: true
              minLength: 1
            TipoDocumento:
              type: string
              required: true
              minLength: 1
            NumeroDocumento:
              type: string
              required: true
              minLength: 1
            CuentaFacturacion:
              type: string
              required: true
              minLength: 1
            CuentaServicio:
              type: string | nil
              required: false
            IdTransaccion:
              type: string | nil
              required: false
            sMotivo:
              type: string | nil
              required: false
            FechaOperacion:
              type: string | nil
              required: false

example: !include ../../examples/request/registerTramitsExample.raml
