#%RAML 1.0 DataType
properties:  
  numero_solicitud_app:
    type: string
    maxLength: 50
    required: true
  tipo_auditoria:
    type: string
    enum: ["Consulta", "Actualizacion", "Insercion", "Borrado"]
    required: true
  aplicacion:
    type: string
    maxLength: 150
    required: true
  iniciativa:
    type: string
    maxLength: 20
    required: true
  ip:
    type: string
    maxLength: 20
    required: false
  navegador:
    type: string
    maxLength: 150
    required: false
  nombre_equipo:
    type: string
    maxLength: 150
    required: false
  usuario:
    type: string
    maxLength: 150
    required: false
  operacion:
    type: any
    required: false
  resultado_operacion:
    type: any
    required: false
  fecha_solicitud:
    type: datetime
    required: false