#%RAML 1.0 DataType
type: object
properties:
   ZBAPI_SOLFACT_CHECKDATA_GP:
     type: object
     properties:
      import:
        properties:
          I_MD5HS:
            type: string
            required: true
          I_SESID:
            type: string
            required: true
      tables:
        properties:        
          T_BAPIRET:
            properties:
              row:
                required: false
                properties:
                  TYPE:
                    type: string
                    required: true
                  ID:
                    type: string
                    required: true
                  NUMBER:
                    type: string
                    required: true
                  MESSAGE:
                    type: string
                    required: true
                  LOG_NO:
                    type: string
                    required: true
                  LOG_MSG_NO:
                    type: string
                    required: true
                  MESSAGE_V1:
                    type: string
                    required: true
                  MESSAGE_V2:
                    type: string
                    required: true
                  MESSAGE_V3:
                    type: string
                    required: true
                  MESSAGE_V4:
                    type: string
                    required: true
                  PARAMETER:
                    type: string
                    required: true
                  ROW:
                    type: string
                    required: true
                  FIELD:
                    type: string
                    required: true
                  SYSTEM:
                    type: string
                    required: true