http:
  private:
    port: "8091"

configurationTimeout:
  sap: "60000"
  rmca: "60000"

sap:
  host: "10.112.3.112"
  username: "TIBCONPLAY"
  password: "inicio00"
  systemNumber: "01"
  clientID: "400"

autodiscovery: "17805922"

sap-wsdl:
  protocol: "HTTP"
  host: "10.112.1.216"
  port: "8000"
  basepath: "/sap/bc/srt/rfc/sap"
  path:
    updateMaterials: "/zws_concil_mat_sap_toa/400/servicio_sap_toa/binding_sap_toa"
    queryMaterials: "/zportafolio/400/zportafolio/binding_zportafolio"
  user: "PORTASUP"
  password: "Col0418#"

rmca-sap:
  protocol: "HTTP"
  host: "10.112.1.23"
  port: "8000"
  basepath: "/sap/bc/srt/rfc/sap"
  path:
    updateMasterData: "/zws_bp_update_data/400/zws_bp_update_data/zbdn_bp_update_data"
  user: "UPBPSUMA"
  password: "ServWeb072020%"
  
sap-bills:
  host: "10.112.1.216"
  username: "TIBCOPAGOS"
  password: "Comunica2018"
  systemNumber: "00"
  clientID: "400"
  functionName: "ZFI_PAGOS_LINEA"
  
sap-affirmatum:
  host: "10.112.1.216"
  username: "USRFACTORING"
  password: "Ini2024##"
  systemNumber: "00"
  clientID: "400"

audits-sapi:
  host: "mule-worker-internal-audits-oracle-sapi-services-prod.us-e2.cloudhub.io"
  port: "8091"
  basePath: "/api/v1/logs"
  path: "/systems/{system_id}/apis/{api_id}"
  client_id: "7b167b9c389a4c0099bbf7ea34df88fc"
  client_secret: "8917F36fBC2c4105b72c7bC3a165740F"

rmca:
  protocol: "HTTP"
  host: "rmcapro.etb.com.co"
  port: "8000"
  reconnectionRMCA:
    basePath: "/sap/bc/srt/rfc/sap"
    path: "/zwsrmca_tramite_reconexion/400/zwsrmca_tramite_reconexion/zbdn_tramite_reconexion"
    headers:
      Content-Type: "text/xml"
    credentials:
      Username: "SOLRECMAX"
      Password: "MaxRec0nex%"