#%RAML 1.0 DataType 
type: object
properties:
  customer:
    type: object
    properties:
      documentNumber:
        type: string
        example: '123456789'
        required: false
      documentType:
        type: string
        example: CC
        required: false
      phone:
        type: string
        example: '+573001234567'
        required: false
      email:
        type: string
        example: cliente@correo.com
        required: false
  address:
    type: object
    required: false
    properties:
      address:
        type: string
        example: 'Calle 123 #45-67'
        required: false
      cityDane:
        type: string
        example: '11001'
        required: false
      departmentDane:
        type: string
        example: '11'
        required: false
  shippingMethod:
    type: object
    properties:
      type:
        type: string
        example: ''
        required: false
      value:
        type: string
        example: '3001234567'
        required: false
  billingType:
    type: string
    example: ''
    required: false
