#%RAML 1.0 DataType 
type: object
properties:
  customer:
    type: object
    properties:
      documentNumber:
        type: string
        example: '123456789'
        required: false
      documentType:
        type: string
        example: CC
        required: false
      phone:
        type: string
        example: '+573001234567'
        required: false
      email:
        type: string
        example: cliente@correo.com
        required: false
  category:
    type: string
    example: Portabilidad
    required: false
  description:
    type: string
    example: Solicitud de portabilidad móvil
    required: false
  orderData:
    type: object
    properties:
      portability:
        type: boolean
        example: true
        required: false
      portabilityPhone:
        type: string
        example: '3001234567'
        required: false
  characteristics:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          example: planType
          required: false
        value:
          type: string
          example: Prepago
          required: false
  creationData:
    type: object
    properties:
      user:
        type: string
        example: agente01
        required: false
      date:
        type: string
        example: '2025-10-21T10:00:00Z'
        required: false
      channel:
        type: string
        example: CRM
        required: false