envName: "Development"

app:
  apiId: "20497177"
  listener:
    host: "0.0.0.0"
    port: "8091"
    basePath: ""
  
sapi:
   client_id: "5aq8AX3BlJAwRlLLAbEmXH8eQPeXp3KY"
   client_secret: "ic80eX0L4hgH9DGy"   

payu-sapi:
  host: ""
  port: "8091"
  fields:
    accountId: "12345"
    language: ""
    signature: ""
    notifyUrl: ""

wompi-sapi:
  host: ""
  port: "8091"
  fields:
    singleUse: "true"
    collectShipping: "false"
    redirectUrl: ""
    imageUrl: ""

pse-sapi:
  host: ""
  port: "8091"
  fields:
    entityCode: "102322"
    serviceCode: "102322"
    beneficiaryEntityIdentificationType: "NIT"
    beneficiaryEntityIdentification: "8999991158"
    beneficiaryEntityName: "ETB" # Reemplazar por el nombre correcto de la entidad beneficiaria en pse
    beneficiaryEntityCIIUCategory: "4652"
    userType: "person"
    iva: "IVA"

mongo-db-sapi:
  host: ""
  port: "8091"