#%RAML 1.0 NamedExample
value:
  status: 200
  code: "OK"
  response: 
    consultInventoryDetailOutput:
      wsResponseHeader: 
        system:
          correlationId: "INC000006723328"
          name: "MULESOFT"
          processingServer: "MULESOFT" 
        service:
          responseDate: "2022-06-23T13:38:33.154-05:00"
          status: "PASS"
      bodyResponse: 
        consult_inventory_detailResponse:
          inventory_actions:
            -
              inventory_action:
                quantity: 1
                final_state: "LIBRE UTILIZACIÓN"
                initial_state: "SIN EXISTENCIA"
                provisioning_id: null
                final_state_id: null
                initial_state_id: null
                action_type_id: null
                observation: null
                action_type: "Crear"
            -
              inventory_action:
                quantity: 1
                final_state: "RESERVADO"
                initial_state: "LIBRE UTILIZACIÓN"
                provisioning_id: null
                final_state_id: null
                initial_state_id: null
                action_type_id: null
                observation: null
                action_type: "Reservar"
            -
              inventory_action:
                quantity: 1
                final_state: "LIBRE UTILIZACIÓN"
                initial_state: "RESERVADO"
                provisioning_id: null
                final_state_id: null
                initial_state_id: null
                action_type_id: null
                observation: null
                action_type: "Liberar"
          inventory_attributes:
            -
              inventory_attribute:
                description: null
                attribute_id: null
                name: "CARRIER"
                order: 1
                data_type: "1"
                value: "BONOHUNE8001"
            -
              inventory_attribute:
                description: null
                attribute_id: null
                name: "SERVICIO"
                order: 2
                data_type: "1"
                value: "INTERNET"
          cellar: "LOGICA"
          quantity: 1
          reservation_quantity: 0
          cost_center: "LOGICO"
          appreciation_class: null
          document: null
          is_active: true
          state: "LIBRE UTILIZACIÓN"
          up_date: null
          cellar_id: null
          state_id: null
          product_id: null
          batch: "LOGICO"
          client_nit: null
          position: null
          product: "VSIID"
          serial: "223380402"
          ubication: "LOGICO"
          unit_value: 0