#%RAML 1.0 DataType
type: object
properties:
  Browser:
    type: string
    required: false
    example: "Chrome"
  Browser_Id:
    type: string
    required: false
    example: "12345"
  Browser_InputType:
    type: string
    required: false
    example: "Keyboard"
  Browser_Platform:
    type: string
    required: false
    example: "Windows"
  Browser_Version:
    type: string
    required: false
    example: "89.0.4389.82"
  Encoding:
    type: string
    required: false
    example: "UTF-8"
  IP:
    type: string
    required: false
    example: "192.168.1.1"
  IP_X:
    type: string
    required: false
    example: "192.168.1.2"
  IPs:
    type: array
    items: string
    required: false
    example: ["192.168.1.1", "192.168.1.2"]
  MiETB_User:
    type: string
    required: false
    example: "user123"
  URL:
    type: string
    required: false
    example: "http://example.com"
  URL_Referrer:
    type: string
    required: false
    example: "http://referrer.com"
  User_Agent:
    type: string
    required: false
    example: "Mozilla/5.0"
  User_Name:
    type: string
    required: false
    example: "John Doe"