#%RAML 1.0 Trait

headers:
  x_civ_request:
    description: "Parámetro que debe ser incluido en la cabecera de la petición y que cumple el objetivo de des-cifrar el contenido (IV)"
    type: string
    required: true
  processname:
    description: "Parámetro que debe ser incluido en la cabecera de la petición para identificación proceso de registro en logs de auditoría"
    type: string
    required: true