#%RAML 1.0 DataType
type: object
properties:
  name:
    type: string
    required: false
    example: "EDGEN-AI"
  correlationID:
    type: string
    required: false
    example: "EDGEN-AI-001"
  processingServer:
    type: string
    required: false
    example: "EDGEN-AI"