#%RAML 1.0 Library
usage: Library that contains most common resource and traits, use them for consistency

types:
  #Request 
  Z_RM_RFC_CREATE_MASTER_DATA: !include request/Z_RM_RFC_CREATE_MASTER_DATA.raml
  ZBAPI_SOLFACT_GETDATA_GP: !include request/ZBAPI_SOLFACT_GETDATA_GP.raml
  ZBAPI_SOLFACT_CHECKDATA_GP: !include request/ZBAPI_SOLFACT_CHECKDATA_GP.raml
  ZBAPI_BLOCK_INVOICE_GP: !include request/ZBAPI_BLOCK_INVOICE_GP.raml
  ZBAPI_CHANGE_INVOICE_GP: !include request/ZBAPI_CHANGE_INVOICE_GP.raml
  ZBAPI_PAYMENT_NOTIF_GP: !include request/ZBAPI_PAYMENT_NOTIF_GP.raml
  #Response
  Z_RM_RFC_CREATE_MASTER_DATA_Response: !include response/Z_RM_RFC_CREATE_MASTER_DATA_Response.raml
  ZBAPI_SOLFACT_GETDATA_GPResponse: !include response/ZBAPI_SOLFACT_GETDATA_GPResponse.raml
  ZBAPI_SOLFACT_CHECKDATA_GPResponse: !include response/ZBAPI_SOLFACT_CHECKDATA_GPResponse.raml
  ZBAPI_BLOCK_INVOICE_GPResponse: !include response/ZBAPI_BLOCK_INVOICE_GPResponse.raml
  ZBAPI_CHANGE_INVOICE_GPResponse: !include response/ZBAPI_CHANGE_INVOICE_GPResponse.raml
  ZBAPI_PAYMENT_NOTIF_GPResponse: !include response/ZBAPI_PAYMENT_NOTIF_GPResponse.raml  
  ZRFC_BP_UPDATE_DATA: !include request/ZRFC_BP_UPDATE_DATA.raml