#%RAML 1.0 Trait
usage: Permite que una petición HTTP GET pueda referir o estar asociada a un manejo de caché 
headers:
  If-None-Match:
    type: string
    displayName: Identificador en el almacenamiento en caché
    description: |
      Identificador asociado a una petición previa que si no ha sido modificado posterior a su creación puede ser devuelto sin necesidad de ejecutar de nuevo la API solicitada 
    required: false
responses:
  200:
    description: |
      El recurso solicitado fue modificado. Las modificaciones fueron adicionadas en el contenido de la respuesta.
    headers:
      ETag:
        type: string
        description: Identificador generado por el servidor que refiere a la respuesta para su uso posterior en un mismo llamado a una API
        displayName: ETag
        example: adcab6f4-0086-4966-829a-d986a2c76aa2
      Cache-Control:
        type: string
        description: Dicta el comportamiento de la caché permitiendo saber con qué frecuencia deben actualizar los recursos almacenados en local.
        displayName: Cache-Control
        example: private, max-age=3600000
  304:
    description: |
      El recurso solicitado no ha sido modificado y por tal motivo el contenido de esta respuesta refiere a la almacenada por caché.
    headers:
      ETag:
        type: string
        description: Identificador generado por el servidor que refiere a la respuesta para su uso posterior en un mismo llamado a una API
        displayName: ETag
        example: 8b8405f6-b3e6-41a0-9f72-d7a283001a09
      Cache-Control:
        type: string
        description: Dicta el comportamiento de la caché permitiendo saber con qué frecuencia deben actualizar los recursos almacenados en local.
        displayName: Cache-Control
        example: private, max-age=3600000