#%RAML 1.0 DataType
properties:
  operationResult:
    type: string
    description: Operation result
    example: "1"
  operationResultDesc:
    type: string
    description: Operation result description
    example: "Operacion Exitosa"