#%RAML 1.0 DataType
properties:
  system:
    type: !include ../../requests/subdatatypes/WSHeader.raml
  service:
    type: object
    properties:
      status:
        type: string
        description: status
        example: "OK"
      responseDate:
        type: string
        description: Response date
        example: "2021-11-02 09:16:32"
      statusDetail:
        type: string
        description: Status detail
        example: ""
        required: false
  property:
    type: string
    description: property
    example: ""
    required: false