#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: JWKS retrieved successfully
    required: false
  result:
    type: object
    properties:
      keys:
        type: array
        items:
          type: object
          properties:
            kty:
              type: string
              example: RSA
              required: false
            alg:
              type: string
              example: RS256
              required: false
            kid:
              type: string
              example: etb-sam1-key-01
              required: false
            e:
              type: string
              example: AQAB
              required: false
            'n':
              type: string
              example: '{RSA_PUBLIC_MODULUS_KEY_01}'
              required: false
            use:
              type: string
              example: sig
              required: false
