#%RAML 1.0 DataType 
type: object
properties:
  code:
    type: string
    example: '200'
    required: false
  message:
    type: string
    example: Notification processed successfully
    required: false
  data:
    type: object
    properties:
      notificationType:
        type: string
        example: ActivateRefresh
        required: false
      responseMetadata:
        type: object
        properties:
          timeStamp:
            type: date-only
            example: '2025-12-11'
            required: false
          requestID:
            type: string
            example: '12345'
            required: false
examples: 
  directvPrime: !include ../../examples/response/post-dtv-prime-third-party-message.json