#%RAML 1.0 DataType
type: object
properties:
  code:
    type: string
    example: "201"
    required: false
  message:
    type: string
    example: "Operacion exitosa"
    required: false
  result?:
    type: object
    properties:
      cunNumber?:
        type: string
        example: "CUN986532"
        required: false
      cunDate?:
        type: string
        example: "2026-03-16"
        required: false
      pqrType?:
        type: string
        example: "PQR_TYPE"
        required: false
      pqrDate?:
        type: string
        example: "2026-03-16"
        required: false
      system?:
        type: string
        example: "TBD"
        required: false
      orderNumber?:
        type: string
        example: "ORD123265"
        required: false
      documentType?:
        type: string
        example: "CC"
        required: false
      documentNumber?:
        type: string
        example: "98653212"
        required: false
      connectionNumber?:
        type: string
        example: "CONN54976"
        required: false
  id:
    type: integer
    description: Identificador único de la base de datos
    required: false
    example: 12345
  href:
    type: string
    description: Enlace de acceso al ticket de dificultad
    required: false
    example: "/troubleTicket/12345"
  status:
    type: string
    description: Estado actual del ticket
    required: false
    enum: [acknowledged, closed]
    example: "acknowledged"
  creationDate:
    type: string
    description: Fecha y hora de creación del registro
    required: false
    example: "2026-08-18 21:34:00"
  description:
    type: string
    description: Descripción detallada de la PQR
    required: false
    example: "Falla técnica en el servicio de internet"
  characteristics:
    type: array
    required: false
    items:
      type: object
      properties:
        name:
          type: string
          description: Nombre de la característica
          required: false
          example: "CUN"
        value:
          type: any
          description: Valor asignado a la característica (puede ser texto o booleano)
          required: false
          example: "98765432176"
examples:
  CUN_RESPONSE: !include ../../examples/response/post-trouble-ticket-cun-response.json
  PQR_RESPONSE: !include ../../examples/response/post-trouble-ticket-pqr-response.json
