#%RAML 1.0 DataType
displayName: Communications Message Response
description: Represents a communication message result with message notification status and data.
example: !include ../../examples/response/post-comm-message-response.json
type: object
properties:
  code:
    type: string
    example: "201"
  message:
    type: string
    example: "Notification Sent Successfully"
  result?:
    type: object
    properties:
      state?:
        type: string
        description: The current state of the message.
        example: "intial"
        required: false
      messageChannel?:
        type: string
        description: The origin channel of the message.
        example: "WHATSAPP"
        required: false
      provider?:
        type: string
        description: The provider of the message result.
        example: "PAU"
        required: false
      notificationSendingDate?:
        type: string
        description: The date when the message was received and created.
        example: "2026-04-30"
        required: false
      notificationId?:
        type: string
        description: The notification identifier for the provider.
        example: "986532"
        required: false