#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  messageResponse:
    type: string
    example: consulta realizadaexitosamente
    required: false
  utilitys:
    type: object
    properties:
      parametersRetention:
        type: array
        required: false
        items:
          type: object
          properties:
            id:
              type: string
              example: 63aa250b68e75244f4e3621a
              required: false
            creationDate:
              type: datetime
              example: '2022-12-13T23:57:15.052Z'
              required: false
            modificationDate:
              type: datetime
              example: '2022-12-13T23:57:15.052Z'
              required: false
            modifiedByUser:
              type: string
              example: holmroda
              required: false
            createdByUser:
              type: string
              example: holmroda
              required: false
            extractorUpdate:
              type: string
              example: '1'
              required: false
            parameterType:
              type: integer
              example: 37
              required: false
            name:
              type: string
              example: Motivo_Submotivo
              required: false
            values:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                    required: false
                  status:
                    type: integer
                    example: 0
                    required: false
                  value:
                    type: string
                    example: '100'
                    required: false
                  attributeClass:
                    type: integer
                    example: 4
                    required: false
                  attributeType:
                    type: integer
                    example: 9
                    required: false
                  relations:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 1
                          required: false
                        status:
                          type: integer
                          example: 0
                          required: false
                        value:
                          type: string
                          example: '200'
                          required: false
                        attributeClass:
                          type: integer
                          example: 5
                          required: false
                        attributeType:
                          type: integer
                          example: 9
                          required: false
                        relations:
                          type: array
                          items: {}
                        rules:
                          type: array
                          items: {}
                        levels:
                          type: array
                          items:
                            type: integer
                        name:
                          type: string
                          example: MOTIVO_SUBMOTIVO
                          required: false
                  rules:
                    type: array
                    items: {}
                  levels:
                    type: array
                    items:
                      type: integer
            steps:
              type: array
              items: {}
            actions:
              type: array
              items: {}
            reasonSteps:
              type: array
              items: {}
            ruleSteps:
              type: array
              items: {}
      operators:
        type: array
        required: false
        items:
          type: object
          properties:
            code:
              type: string
              example: '00001'
              required: false
            operator:
              type: string
              example: Avantel
              required: false
            nrn:
              type: string
              example: '110'
              required: false
      businessDays:
        type: array
        required: false
        items:
          type: object
          properties:
            date:
              type: datetime-only
              example: '2024-12-19T00:00:00'
              required: false
            day:
              type: string
              example: '19'
              required: false
            month:
              type: string
              example: '12'
              required: false
            monthNameShort:
              type: string
              example: Dic
              required: false
            year:
              type: string
              example: '2024'
              required: false
      pqrActivities:
        type: array
        required: false
        items:
          type: object
          properties:
            id:
              type: string
              example: 63aa250b68e75244f4e3621a
              required: false
            actividad: 
              type: string
              example: "INSTANCIA ADMINISTRATIVA"
              required: false
            grupo_gestion:
              type: string
              example: "NO APLICA"
              required: false
            clase:
              type: string
              example: "PETICION"
              required: false
            motivo:
              type: string
              example: "DAÑOS EN INSTALACIONES"
              required: false
            descripcion:
              type: string
              example: "ES IMPORTANTE MENCIONAR QUE  CONTRA LA PRESENTA PETICION/QUEJA NO PROCEDE INSTANCIA ADMINISTRATIVA DEBIDO A QUE NO ESTÁ ENMARCADA DENTRO DE LAS CAUSALES SEÑALADAS EN EL ARTÍCULO 54 DE LA LEY 1341/11 Y ARTÍCULO 47 DE LA RESOLUCION 3066/11"
              required: false
            observaciones:
              type: string
              example: "ESTO NO QUIERE DECIR QUE NO PUEDA CREAR ESTAS ACTIVIDADES MANUALMENTE SI SE REQUIEREN"
              required: false
            tipo_actividad:
              type: string
              example: "INSTANCIA ADMINISTRATIVA"
              required: false
            permite_cerrar_pqr:
              type: string
              example: "NO"
              required: false
            estado:
              type: string
              example: "ACTIVO"
              required: false
            fecha_modificacion:
              type: string
              example: "29/12/2017 12:37:31 a.m."
              required: false
            fecha_inicio:
              type: string
              example: "2018-04-20T02:17:30.476Z"
              required: false
            fecha_fin:
              type: string
              example: "2018-04-20T02:17:30.476Z"
              required: false
            version: 
              type: integer
              example: 1  