# ==============================================================================
#  PROD ENVIRONMENT PROPERTIES
#  Used for production environment. Start with: -Denv=prod
# ==============================================================================

# --- API Manager ---
api:
  id: "0"
    
# --- Pau HTTP Requester ---
pau:
  protocol: "HTTPS"
  host: "prod_host"
  port: ""
  basePath: "/api10"
  login:
    path: "/login"
    post:
      method: "POST"
  connectorById:
    path: "/conector-by-identificador"
    post:
      method: "POST"
  notification:
    path: "/notificacion-set"
    post:
      method: "POST"