#%RAML 1.0 DataType
type: object
displayName: Aplicativo o Sistema
description: Aplicación o sistema que consume o ejecuta la API
properties:
  canal:
    type: string
    description: Canal sobre el cuál fue ejecutada la API
    displayName: Canal
    enum: 
      - Sitio web
      - Aplicación móvil
      - Aplicación web
      - Chat web
      - WhatsApp
      - Tienda física
      - Llamada telefónica
    required: true
  nombre:
    type: string
    description: Nombre del sistema o aplicativo que ejecuta la API
    displayName: Nombre
    enum:
      - MiETB
      - Luz
      - IVR
      - Ecommerce
    required: true
  sistema-operativo:
    type: string
    description: Sistema operativo del aplicativo o sistema que ejecuta la API
    displayName: Sistema operativo
    enum: 
      - Android
      - iOS
      - Chrome
      - Edge
    required: true
  version:
    type: string
    description: Versión del aplicativo o sistema que ejecuta la API
    displayName: Versión
    required: false
  
  
  