#%RAML 1.0 DataType
properties:
  PeticionOutboundETAdirect:
    type: object
    properties:
      EncabezadoMensaje:
        type: object
        properties:
          IdOrdenETAdirect:
            type: string | nil
            required: true
            example: null
          IdMensaje:
            type: string | nil
            required: true
            example: "729219784"
          FechaPeticion:
            type: string | nil
            required: true
            example: "2022-08-01T00:08:37-05:00"
      DetalleMensaje:
        type: object
        properties:
          SerialEquipo:
            type: string
            required: false
          MacEquipo:
            type: string
            required: false
          TipoEquipo:
            type: string
            required: false
          PuertoEquipo:
            type: string
            required: false
          MacEquipoPadre:
            type: string
            required: false
          SerialEquipoPadre:
            type: string
            required: false
          PuertoEquipoPadre:
            type: string
            required: false
          RevertirAccion:
            type: string
            required: false
          IdRecurso:
            type: string
            required: false
          Servicio:
            type: string
            required: true
          TipoPeticion: 
            type: string
            required: true
            example: "ACTUALIZAR_TECNICO"
          MotivoPeticion:
            type: object
            required: false
            properties:
              CodigoMotivo:
                type: string
                required: false
              Motivo:
                type: string
                required: false
              RazonMotivo:
                type: string
                required: false
          installed_equipment:
            type: array
            required: false
            items:
              type: object
              properties:
                SerialEquipo:
                  type: string
                  required: false
                MacEquipo:
                  type: string
                  required: false
                TipoEquipo:
                  type: string
                  required: false
          deinstalled_equipment:
            type: array
            required: false
            items:
              type: object
              properties:
                SerialEquipo:
                  type: string
                  required: false
                MacEquipo:
                  type: string
                  required: false
                TipoEquipo:
                  type: string
                  required: false
          Observaciones:
            type: string | nil
            required: false
  Message:
    type: string
    required: false
