#%RAML 1.0 DataType
properties:
  pqrMassiveFailure:
    type: object
    properties:
      requestHeader:
        type: object
        properties:
          system:
            type: object
            properties:
              name:
                type: string
                required: false
                example: "MDM_Data_Services"
              correlationId:
                type: string
                required: false
                example: "MDM-PQR-4091830"
              processingServer:
                type: string
                required: false
                example: ""
          property:
            type: array
            items:
              properties:
                name:
                  type: string
                  required: false
                  example: ""
                value:
                  type: string
                  required: false
                  example: ""
      requestBody:
        type: object
        properties:
          pqrNumber: 
            type: string | nil
            required: false
            example: "MDM-PQR-4091830"
          tes: 
            type: integer | nil
            required: false
            example: null
          mitigado: 
            type: boolean | nil
            required: false
            example: null
          operationType: 
            type: string | nil
            required: false
            example: null
          cierre1: 
            type: string | nil
            required: false
            example: null
          cierre2: 
            type: string | nil
            required: false
            example: null
          cierre3: 
            type: string | nil
            required: false
            example: null
          fechaSolucion: 
            type: string | nil
            required: false
            example: "2024-12-01T12:00:00"
          imputabilidad: 
            type: string | nil
            required: false
            example: null
          respuestaPQR: 
            type: string | nil
            required: false
            example: null
          codigoResolucion: 
            type: string | nil
            required: false
            example: null
          descripcionResolucion: 
            type: string | nil
            required: false
            example: null                   
          rowIdActividad: 
            type: string | nil
            required: false
            example: null    
          estadoActividad: 
            type: string | nil
            required: false
            example: null    
          comentarios: 
            type: string | nil
            required: false
            example: null    
              
example: !include ../../examples/request/pqrMassiveFailure.json