#%RAML 1.0 DataType
type: object
properties:
  Identificador_Peticion:
    type: string
    example: "MDM-LISIM-VIGENCIA-CC-1022422294"
    minLength: 1
  Tipo_Documento:
    type: string
    example: "CC"
  Numero_Identificacion:
    type: number | nil
    example: 1022422294
  Numero_Conexion:
    type: string
    example: ""
    required: false
  Tipo_Transaccion:
    type: string
    example: "Registro Log LISIM"
    minLength: 1
  Fecha_Inicio:
    type: datetime
    example:  2022-02-01T00:02:53.16-05:00
  Fecha_Fin:
    type: datetime
    example: 2022-02-01T00:02:53.16-05:00
  Estado_Transaccion:
    type: string
    example: ""
    required: false
  Sistema_Origen:
    type: string
    example: "MULESOFT"
    minLength: 1
  Atributos:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          example: "Ciudad"
          minLength: 1
        value:
          type: string
          example: "BOGOTA D.C."