#%RAML 1.0 DataType
type: object
properties:
  servicio:
    type: string
    required: true
    example: "AC-1090209"
  cuentaFacturacionOrigen:
    type: string
    required: true
    example: "15052904018"
  cuentaFacturacionDestino:
    type: string
    required: true
    example: "15052904678"
  nroDocClienteOrigen:
    type: string
    required: false
    example: "14589657"
  nroDocClienteDestino:
    type: string
    required: false
    example: "14589658"
  tipoDocumentoClienteOrigen:
    type: string
    required: false
    example: "NIT"
  tipoDocumentoClienteDestino:
    type: string
    required: false
    example: "NIT"