#%RAML 1.0 DataType
properties:
  system:
    type: object
    properties:
      name:
        type: string
        example: "TIBCO"
      correlationId:
        type: string
        example: "INC000003379399"
      processingServer:
        type: string
        example: "ETB_MDM_Integration_MDM_2"
  orderId:
    type: string
    example: "INC000003379399"
  messageId:
    type: number
    example: 407588045
  requestDate:
    type: string
    example: "2021-11-19T17:23:38.505-05:00"
  requestType:
    type: string
    example: "UPDATE_TECHNICIAN_REMEDY"
  message:
    type: object
    example: !include ../../examples/request/updateTechnicianRemedyIntf.raml
