#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Phone:
        type: string
        example: '6017643718'
        required: false
      Service_Account:
        type: string
        example: CS-1351925
        required: false
      REGISTER_LINE:
        type: object
        properties:
          Execution_Date:
            type: string
            example: '2025-09-17T14:39:29.2126701Z'
            required: false
          Semaphore:
            type: string
            example: Yellow
            required: false
          Semaphore_Description:
            type: string
            example: La plataforma no obtuvo resultado, no se puede validar
            required: false
      STATE:
        type: object
        properties:
          Execution_Date:
            type: string
            example: '2025-09-17T14:39:29.040789Z'
            required: false
          Semaphore:
            type: string
            example: Green
            required: false
          Semaphore_Description:
            type: string
            example: >-
              El estado de la plataforma es 0 y de MSS es 0. No se debe
              normalizar.
            required: false
      STATE_PROGRAMMED:
        type: object
        properties:
          Execution_Date:
            type: string
            example: '2025-09-17T14:39:29.0876682Z'
            required: false
          Semaphore:
            type: string
            example: Red
            required: false
          Semaphore_Description:
            type: string
            example: La plataforma no obtuvo resultado
            required: false
      Technology:
        type: string
        example: FTTH
        required: false
