#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      ATTENUATION:
        type: object
        properties:
          Execution_Date:
            type: datetime-only
            example: '2024-12-19T10:30:00'
            required: false
          Requires_Normalization:
            type: boolean
            example: false
            required: false
          State:
            type: string
            example: NORMAL
            required: false
          State_Description:
            type: string
            example: Atenuación dentro de parámetros normales
            required: false
      Brand:
        type: string
        example: HUAWEI
        required: false
      NOISE:
        type: object
        properties:
          Execution_Date:
            type: datetime-only
            example: '2024-12-19T10:30:00'
            required: false
          Requires_Normalization:
            type: boolean
            example: false
            required: false
          State:
            type: string
            example: NORMAL
            required: false
          State_Description:
            type: string
            example: Nivel de ruido dentro de parámetros normales
            required: false
      ONT:
        type: object
        properties:
          Execution_Date:
            type: datetime-only
            example: '2024-12-19T10:30:00'
            required: false
          Requires_Normalization:
            type: boolean
            example: false
            required: false
          State:
            type: string
            example: ONLINE
            required: false
          State_Description:
            type: string
            example: ONT operativa y conectada
            required: false
      POTENCY:
        type: object
        properties:
          Execution_Date:
            type: datetime-only
            example: '2024-12-19T10:30:00'
            required: false
          Requires_Normalization:
            type: boolean
            example: false
            required: false
          State:
            type: string
            example: NORMAL
            required: false
          State_Description:
            type: string
            example: Potencia dentro de parámetros normales
            required: false
      Phone:
        type: string
        example: '3057000421'
        required: false
      Requires_Normalization:
        type: boolean
        example: false
        required: false
      Service_Account:
        type: string
        example: ACC123456789
        required: false
      Technology:
        type: string
        example: FTTH
        required: false
