#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Equipments:
        type: array
        items:
          type: object
          properties:
            Brand:
              type: string
              example: Nokia
              required: false
            Firmware:
              type: string
              example: 3FE48xxx
              required: false
            Is_Dual:
              type: boolean
              example: true
              required: false
            MAC:
              type: string
              example: AA:BB:CC:DD:EE:FF
              required: false
            Manageable:
              type: boolean
              example: true
              required: false
            Model:
              type: string
              example: G-140W-C
              required: false
            Serial:
              type: string
              example: ALCLB1234567
              required: false
            Serial_Slaves:
              type: array
              items: {}
            Type_Modem:
              type: string
              example: Modem
              required: false
            Networks:
              type: array
              items:
                type: object
                properties:
                  Name:
                    type: string
                    example: Mi Red WiFi
                    required: false
                  Type:
                    type: string
                    example: 2.4G
                    required: false

