#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Networks:
        type: array
        items:
          type: object
          properties:
            Connected_Devices:
              type: array
              items:
                type: object
                properties:
                  Authenticated:
                    type: boolean
                    example: true
                    required: false
                  Attributes:
                    type: array
                    items:
                      type: object
                      properties:
                        Name:
                          type: string
                          example: tipo
                          required: false
                        Value:
                          type: string
                          example: wlan
                          required: false
                  Index:
                    type: string
                    example: '1'
                    required: false
                  Is_LAN:
                    type: boolean
                    example: false
                    required: false
                  Is_WLAN:
                    type: boolean
                    example: true
                    required: false
                  Ip:
                    type: string
                    example: 192.168.1.50
                    required: false
                  LinkRate:
                    type: string
                    example: '72'
                    required: false
                  Locked:
                    type: boolean
                    example: false
                    required: false
                  Mac:
                    type: string
                    example: AA:BB:CC:DD:EE:FF
                    required: false
                  Name:
                    type: string
                    example: Cliente-Tablet
                    required: false
                  Noise:
                    type: string
                    example: ''
                    required: false
                  Serial:
                    type: string
                    example: ''
                    required: false
                  State:
                    type: boolean
                    example: true
                    required: false
                  SNR:
                    type: string
                    example: ''
                    required: false
                  RRSI:
                    type: string
                    example: '-45'
                    required: false
      Total_Devices:
        type: integer
        example: 0
        required: false
      Phone:
        type: 'null'
        example: null
        required: false


