#%RAML 1.0 DataType 
type: object
properties:
  WSResponseHeader:
    type: !include objects/header.raml
    required: true
  WSResponseBody:
    type: object
    properties:
      Agenda:
        type: boolean
        example: false
        required: false
      CUN:
        type: string
        example: CUN-2024-001234
        required: false
      Num_Order:
        type: string
        example: ORD-2024-001234
        required: false
      Num_PQR:
        type: string
        example: ''
        required: false

