#%RAML 1.0 DataType 
type: object
properties:
  codeResponse:
    type: string
    example: '200'
    required: false
  responseMessage:
    type: string
    example: La solicitud fue exitosa
    required: false
  appointments:
    type: object
    properties:
      assurance:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              example: FdB8a4aecd47B4f0bAeFe6B9
              required: false
            actionType:
              type: string
              example: ABCDEFGHIJKLMN
              required: false
            address:
              type: string
              example: ABCDEFGHIJKL
              required: false
            tmrSchedules:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: 0fe5EF8dBB06c7d4eE78EB00
                    required: false
                  scheduleStatus:
                    type: string
                    example: ABCDEFGHI
                    required: false
                  creationDate:
                    type: string
                    example: ABCDEFGHIJKLMNOPQRSTUVW
                    required: false
                  scheduleStartDate:
                    type: array
                    items: {}
                  etaId:
                    type: string
                    example: ''
                    required: false
                  requestedByCustomer:
                    type: boolean
                    example: true
                    required: false
                  timeSlot:
                    type: string
                    example: ABCDEFGHIJKLMNOPQRSTUVWXY
                    required: false
                  channel:
                    type: string
                    example: ''
                    required: false
                  scheduleEndDate:
                    type: integer
                    example: 0
                    required: false
                  osmId:
                    type: string
                    example: ''
                    required: false
                  rescheduleReason:
                    type: string
                    example: ''
                    required: false
                  scheduleOpportunity:
                    type: array
                    items: {}
                  createdByUser:
                    type: string
                    example: ABCDEFGHIJKLMNOPQRSTUVWXY
                    required: false
                  modifiedByUser:
                    type: string
                    example: ABCDEFGHIJKLMNO
                    required: false
            connectionNumber:
              type: string
              example: ABCDEFGHIJKLMNOPQRS
              required: false
            cun:
              type: string
              example: ABCDEFGHIJKLMNOPQRST
              required: false
            customerDocumentNumber:
              type: string
              example: ABCDEFGHIJKLMNO
              required: false
            customerDocumentType:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
              required: false
            duration:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZABC
              required: false
            updateDate:
              type: string
              example: ABCDEFGHIJKLMNO
              required: false
            orderNumber:
              type: string
              example: ABCDEFGHIJK
              required: false
            orderType:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUV
              required: false
            originSystem:
              type: string
              example: ABCDEFGH
              required: false
            serviceType:
              type: string
              example: ABCDEFGHIJKLMNOPQRST
              required: false
            skill:
              type: string
              example: ABCDEFGHI
              required: false
            technicianDocumentNumber:
              type: string
              example: ABCDEFGHIJKLMNOPQRSTUVWXYZ
              required: false
            technicianDocumentType:
              type: string
              example: ''
              required: false
            technology:
              type: string
              example: ABCDEFGHI
              required: false
            createdBy:
              type: string
              example: ABCDEFGH
              required: false
            zone:
              type: string
              example: ABCDEFGHIJKLMNOPQRS
              required: false
      provisioning:
        type: array
        items:
          type: object
          properties:
            scheduling:
              type: object
              properties:
                scheduledDate:
                  type: datetime
                  example: '2026-01-30T05:00:00.000Z'
                  required: false
                timeSlot:
                  type: string
                  example: AM_1
                  required: false
                workType:
                  type: string
                  example: F.O. (HSI)
                  required: false
                workSkill:
                  type: string
                  example: MPPFTTH
                  required: false
                durationMinutes:
                  type: integer
                  example: 120
                  required: false
                installerCode:
                  type: string
                  example: ''
                  required: false
                isEnriched:
                  type: boolean
                  example: false
                  required: false
                isScheduled:
                  type: boolean
                  example: true
                  required: false
                activityId:
                  type: string
                  example: '88475'
                  required: false
                installmentList:
                  type: array
                  items: {}
