#%RAML 1.0 Library
usage:
types:
  processIdRequest:
    type: object
    properties:
      salesforceId:
        type: string
        required: true
        minLength: 1
      processId:
        type: string
        required: true
        minLength: 1
  processIdResponse:
    type: object
    properties:
      process:
        type: string
        required: true
      message:
        type: string
        required: true
  getProcessIdResponse:
    type: object
    properties:
      processId:
        type: string
        required: true