#%RAML 1.0 DataType
properties:
  code:
    type: string
    example: "OK"
    description: "OK or FAIL"
  description:
    type: string
    example: "Successful"
  characteristic:
    type: string
    example: "true"
    description: "true == migrado mvne, false == no migrado"