#%RAML 1.0 DataType
properties:
  "ResponseData": 
    type: object
    properties:
      "UpdateAccountDataRVCResponse": 
        type: object
        properties:
          "Code": 
            type: string 
            example: "S"
          "Description": 
            type: string 
            example: "operation is successful"
      "UpdateAccountDataRMCAResponse": 
        type: object
        properties:
          "Item":
            type: array
            items:
              properties:
                "Code":  
                  type: string 
                  example: "S"
                "Description":  
                  type: string 
                  example: "Nombre y/o email actualizado"
      "UpdateAccountDataMDMResponse":
        type: object
        properties:
          "Code": 
            type: string 
            example: "0"
          "Description": 
            type: string 
            example: "Ejecutado Exitosamente"

example: !include ../../examples/response/patch-updateAccountDataResponse.json