#%RAML 1.0 DataType
properties:
  ACK:
    type: string
    example: "orderFailEvent"
  currentState:
    type: string
    example: "open.running.suspended.failed"
  reason:
    type: string
    example: "HLR_KO:Subscriber not defined"
  eventId:
    type: number
    example: 3551