#%RAML 1.0 DataType
properties:
  responseData:
    type: object
    properties:
      createBillingAccountResponse:
        type: object
        required: false
        properties:
          code:
            type: string
          description:
            type: string
          response:
            type: object
            required: false
            properties:
              system:
                type: string
              operation:
                type: string
              result:
                type: string
              faults:
                type: object
                properties:
                  subscriber_id:
                    type: string
                    required: false
                  account_id:
                    type: string
                    required: false
                  plan_impuestos:
                    type: object
                    required: false
                    properties:
                      type_name:
                        type: string | nil
                      tax_plan_vendor:
                        type: string | nil
                  ciclo_facturacion:
                    type: string
                    required: false
                  fault_detail:
                    type: object
                    properties:
                      error_description:
                        type: string
                      error_code:
                        type: string
      createRMCAACcountResponse:
        type: object
        required: false
        properties:
          code:
            type: string
          description:
            type: string
      createMDMAccountResponse:
        type: object
        required: false
        properties:
          code:
            type: string
          description:
            type: string
example: !include ../../examples/response/postBillingAccounts.json