#%RAML 1.0 DataType
type: object
properties:
  ValidarIdentificacionResult:
    type: object
    properties:
      IdValidacion:
          type: string
          required: true
          minLength: 1
      ResultadoProceso:
          type: string
          required: true
          minLength: 1
      EstadoHomologado:
          type: string
          required: true
          minLength: 1
      XmlCentral:
          type: string
          required: false
      FechaScore:
          type: string | nil
          required: false
      TieneScore:
          type: string
          required: true
          minLength: 1
      FechaControl:
          type: string
          required: true
          minLength: 1