#%RAML 1.0 DataType
type: object
properties:
  username:
    type: string
    required: true
    example: "test@toolboxtve.com"
  country_code:
    type: string
    required: true
    example: "CO" 
  subscriber_id:
    type: string
    required: true
    example: "101123456789"   
  active:
    type: string
    required: true
    example: "true"    
  data:
    type: object
    required: true
    properties:
        name:
          type: string
          required: true
          example: "Sergio"
        lastname:
          type: string
          required: true
          example: "Perez"
        email:
          type: string
          required: true
          example: "test@toolboxtve.com"
        businessUnitType:
          type: string
          required: false
          example: "MSO-OTT"
  urn:
    type: array
    required: true     
    items:
      properties:
        urn:
          type: string
          required: false
          example: "urn:tve:dtvgo"   
  externalId:
    type: string
    required: false
    example: "5901b88f-732c-592e-9027-8d7f335e1768"