#%RAML 1.0 Library
usage:
types:
  viabilityResponseType:
    type: object
    properties:
      catalogo:
        type: string
        example: "string"
        required: false
      clase: 
        type: string
        example: "string"
        required: false
      codigo:
        type: string
        example: "string"
        minLength: 1
        required: true
      nombre:
        type: string
        example: "string"
        minLength: 1
        required: true
      id:
        type: string
        example: "string"
        minLength: 1
        required: true
      idItem:
        type: string
        example: "string"
        minLength: 1
        required: true
      idRaiz:
        type: string
        example: "string"
        required: false
      codigoAccion:
        type: string
        example: "string"
        required: false
      idDireccion:
        type: string
        example: "string"
        required: false
      idCuentaServicio:
        type: string
        example: "string"
        required: false
      cantidad:
        type: number
        example: 1
        required: false
      opciones:
        type: array
        required: false
        items:
          properties:
            idOpcion:
              type: string
              example: "string"
              required: false
            cantidadParametros:
              type: number
              example: 1
              required: true
            parametros:
              type: array
              required: true
              items:
                properties:
                  codigo:
                    type: string
                    example: "string"
                    minLength: 1
                    required: true
                  nombre:
                    type: string
                    example: "string"
                    minLength: 1
                    required: true
                  valor:
                    type: string | nil
                    example: "string"
                    required: false
                  codigoAccion:
                    type: string
                    example: "string"
                    required: false
      subProductos:
        type: viabilityResponseType[]
        required: false