#%RAML 1.0 DataType
type: object
properties:
  status:
    type: string
    required: false
    example: "OK"
  responseDate:
    type: datetime
    required: false
    example: "2025-03-31T16:38:16.6336118Z"
  processingServer:
    type: string | nil
    required: false
    example: null
  statusDetail:
    type: array
    items:
      type: object
      properties:
        errorCode:
          type: string
          required: false
          example: "OK_01"
        errorDetailCode:
          type: string
          required: false
          example: "La solicitud fue exitosa, el cliente fue consultado"
        errorMessage:
          type: string
          required: false
          example: "La solicitud EDGEN-AI-001 fue exitosa. El cliente fue consultado."
        errorMessageUser:
          type: string | nil
          required: false
          example: null