#%RAML 1.0 DataType
type: object
properties:
  Canal:
    type: string
    required: false
    example: "Canal"
  IP_Address:
    type: string
    required: false
    example: "169.60.82.89"
  IP_Latitud:
    type: string
    required: false
    example: "4.8094"
  IP_Longitude:
    type: string
    required: false
    example: "-74.0980"
  IP_City:
    type: string
    required: false
    example: "COTA"
  IP_Country:
    type: string
    required: false
    example: "COLOMBIA"
  Date:
    type: string
    required: false
    example: "2025-05-12"
  Hour:
    type: string
    required: false
    example: "14:47:23"
  WhatsApp_Phone_Number:
    type: string
    required: false
    example: ""
  Facebook_User:
    type: string
    required: false
    example: ""
  Twitter_User:
    type: string
    required: false
    example: ""