<?xml version="1.0" encoding="UTF-8"?>
  <xsd:schema elementFormDefault="qualified" targetNamespace="https://www.portabilidad.co/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="https://www.portabilidad.co/">
   <xsd:element name="receiveMessage">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="userId" type="xsd:string"/>
      <xsd:element name="password" type="xsd:string"/>
      <xsd:element name="xmlMsg" type="xsd:string"/>
     </xsd:sequence>
     <xsd:attribute name="encodingStyle" type="xsd:string" use="required"/>
    </xsd:complexType>
   </xsd:element>
   <xsd:element name="receiveMessageResponse">
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="receiveMessageReturn" type="xsd:string"/>
     </xsd:sequence>
    </xsd:complexType>
   </xsd:element>
  </xsd:schema>