<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:annotation>
        <xsd:documentation xml:lang="es">XML Schema para Mensajes ABD Colombia</xsd:documentation>
    </xsd:annotation>
   
    <!-- >>>>>>>>>>>>>>>>>>>>>> ELEMENTO RAIZ <<<<<<<<<<<<<<<<<<<<<<< --> 
    <xsd:element name="MensajeABD">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="CabeceraMensaje" type="TipoCabeceraMensaje"/>
                <xsd:element name="CuerpoMensaje"   type="TipoCuerpoMensaje" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>  
    <!-- >>>>>>>>>>>>>>>>>>>>>> TIPOS SIMPLES <<<<<<<<<<<<<<<<<<<<<<< --> 
   
   <xsd:simpleType name="TipoIdentificadorProceso">
        <xsd:annotation>
            <xsd:documentation>
                Formato: CO + yyyy + mm + dd + ti + ccccc
                    CO:       código del operador (5 digitos)
                    yyyy:     anyo (4 digitos)
                    mm:       mes (2 digitos)
                    dd:       dia (2 digits)
                    ti:       tipo de proceso(2 digitos)
                    ccccc:  secuencia  (5 digitos).
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:length value="20"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType> 
    
    <xsd:simpleType name="TipoIdentificadorMensaje">
        <xsd:annotation>
            <xsd:documentation>
                	Formato: CO + yyyy + mm + dd + ccccccc
                    CO:       código del operador (5 digitos)
                    yyyy:     anyo (4 digitos)
                    mm:       mes (2 digitos)
                    dd:       dia (2 digits)
                    ccccccc:  secuencia  (7 digitos).
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:length value="20"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoTipoMsg">
        <xsd:annotation>
            <xsd:documentation>
					 0001: Solicitud de generación y envío de NIP
            		 0002: Respuesta a la solicitud de generación y envío de NIP
            		 0003: Solicitud de reenvío de NIP
            		 0004: Respuesta a la solicitud de reenvío de NIP
            		 1001: Solicitud de portación
            		 1002: Réplica de la solicitud de portación al donante
            		 1003: Respuesta a la solicitud de portación del donante
            		 1004: Respuesta del donante replicada al receptor
            		 1005: Solicitud lista para ser programada
            		 1006: Programación de la portación
            		 1007: Confirmación de ventana de cambio programada
            		 9999: Rechazo de la solicitud de portabilidad
            		 2001: Solicitud de cancelación de numeración portada
            		 2002: Respuesta a la solicitud de cancelación de numeración portada
            		 3001: Solicitud de sincronización con el ABD
            		 3002: Respuesta a la solicitud de sincronización con el ABD
            		 9998: Error detectado por el ABD
					 4001: Solicitud de reversión a una portabilidad o cancelación de numeración
					 4002: Renvío de solicitud de reversión al operador donante
					 4003: Respuesta del operador donante a la solicitud de reversión
            		 4004: Confirmación o rechazo del donante a la solicitud de reversión
					 4999: Rechazo de la solicitud de reversion
					 5001: Solicitud de Cancelación proceso en curso
					 5002: Respuesta a la solicitud de Cancelación proceso en curso y numeración con fecha de ventana de cambio ejecutada
					 5003: Respuesta a la solicitud de Cancelación vencimiento NIP
					 5999: Rechazo de la solicitud de Cancelación proceso en curso  
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        	  <xsd:length value="4"/>
            <xsd:pattern value="0001|0002|0003|0004|1001|1002|1003|1004|1005|1006|1007|9999|2001|2002|3001|3002|9998|4001|4002|4003|4004|4999|5001|5002|5003|5999"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoCodigoOperador">
        <xsd:restriction base="xsd:string">
            <xsd:length value="5"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="TipoFechaHora">
        <xsd:annotation>
            <xsd:documentation>
                Format: YYYYMMDDHHmiss
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:length value="14"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
	
	<xsd:simpleType name="TipoFecha">
        <xsd:annotation>
            <xsd:documentation>
                Format: YYYYMMDD
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:length value="8"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoObservaciones">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="0"/>
            <xsd:maxLength value="250"/>
        </xsd:restriction>
    </xsd:simpleType>   
    
	<xsd:simpleType name="TipoTipoDocumentoIdentificacion">
        <xsd:annotation>
            <xsd:documentation>
            1: Cedula de Ciudadania
            2: Cedula de Extranjeria
			3: NIT
			4: Pasaporte
			5: PPT
			6: PEP
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        	  <xsd:length value="1"/>
            <xsd:pattern value="1|2|3|4|5|6"/>
        </xsd:restriction>
    </xsd:simpleType>
	
	<xsd:simpleType name="TipoRespuestaABD">
        <xsd:annotation>
            <xsd:documentation>
            1: Aceptada solicitud
            0: Rechazada solicitud
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        	  <xsd:length value="1"/>
            <xsd:pattern value="0|1"/>
        </xsd:restriction>
    </xsd:simpleType>

	<xsd:simpleType name="TipoSolicitudTerceros">
		<xsd:annotation>
			<xsd:documentation>
				1: Solicitud presentada por una tercera persona
				0: Solicitud NO presentada por una tercera persona
            </xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="1" />
			<xsd:pattern value="0|1" />
		</xsd:restriction>
	</xsd:simpleType>
    
    <xsd:simpleType name="TipoFlagVentanaAmpliada">
        <xsd:annotation>
            <xsd:documentation>
            0: No ampliada
            1: Ampliada
	</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        	  <xsd:length value="1"/>
            <xsd:pattern value="0|1"/>
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="TipoCodigoCausa">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="10"/>
          </xsd:restriction>
    </xsd:simpleType>
          
    <xsd:simpleType name="TipoNombreRazonSocialAbonado">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="80"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoDireccionAbonado">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="80"/>
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="TipoIdentificacionAbonado">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="20"/>
        </xsd:restriction>
    </xsd:simpleType>
     
    <xsd:simpleType name="TipoTipoUsuario">
        <xsd:annotation>
            <xsd:documentation>
            1: Natural
            2: Jurídico
           </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        	  <xsd:length value="1"/>
            <xsd:pattern value="1|2"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoTipoServicio">
        <xsd:annotation>
            <xsd:documentation>
            1: Prepago
            2: Pospago
           </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
        	  <xsd:length value="1"/>
            <xsd:pattern value="1|2"/>
        </xsd:restriction>
    </xsd:simpleType>
         
    <xsd:simpleType name="TipoNumero">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="15"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoNIP">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="5"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="TipoNRN">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="3"/>
            <xsd:pattern value="[0-9]*"/>
        </xsd:restriction>
    </xsd:simpleType>
            
    <xsd:simpleType name="TipoTipoSincronizacion">
        <xsd:annotation>
            <xsd:documentation>
                0:Fechas incremental
                1:Total
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="0|1"/>
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="TipoRutaNombreFichero">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="80"/>
        </xsd:restriction>
    </xsd:simpleType>
	
	<xsd:simpleType name="TipoNumeroCUN">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="1"/>
            <xsd:maxLength value="20"/>
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="TipoDocumentoOpcional">
     <xsd:annotation>
        <xsd:documentation>
                    Formato:     OOOOOYYYYMMDDNNNNN-TD.xxx
                    OOOOO:    Código del operador
                    YYYY:     Año
                    MM:       Mes
                    DD:       Día
                    NNNNN:    Contador diario
                    xxx:      Extensión del archivo, jpg o pdf (3 dígitos)
                    Donde TD:
                    ID:       Copia del documento de identidad del suscriptor y/o del representante legal
	    			AT:       Autorización del suscriptor y/o del representante legal
	                CC:       Certificado de la Cámara de Comercio
                    FC:       Última factura expedida por el Proveedor Donante
	                DC:       Declaración de extravío o hurto
	                FR:       Copia del documento declarativo de fraude y desactivación del número
	                UO: 	  Última obligación vencida sin pagar.
					CN: 	  Documento CUN
					CR: 	  Documento soporte rollback
					LD: 	  Línea desactivada
					LS: 	  Línea suspendida
					NA: 	  Numeración no asignada
					NI: 	  Numeración no implementada
					LA: 	  Línea prepago sin actividad en la red
         </xsd:documentation>
      </xsd:annotation>
      <xsd:restriction base="xsd:string">
            <xsd:length value="25"/>
        </xsd:restriction>
    </xsd:simpleType>
     
    <!-- >>>>>>>>>>>>>> COMPLEX TYPES <<<<<<< <<<<<<<  --> 
   
    <xsd:complexType name="TipoListaNumeracion">
        <xsd:sequence>
            <xsd:element name="Numero" type="TipoNumero" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
     <xsd:complexType name="TipoListaNumeracionRechazadaABD">
        <xsd:sequence>
            <xsd:element name="NumeracionRechazada" type="TipoNumeracionRechazadaABD"  maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoListaNumeracionNip">
        <xsd:sequence>
            <xsd:element name="NumeracionNip" type="TipoNumeracionNip"  maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoNumeracionNip">
        <xsd:sequence>
            <xsd:element name="Numero" type="TipoNumero"/>
           <xsd:element name="FechaCreacionNIP" type="TipoFechaHora"/>
        </xsd:sequence>
    </xsd:complexType>
    

     <xsd:complexType name="TipoNumeracionRechazadaABD">
        <xsd:sequence>
        	<xsd:element name="Numero" type="TipoNumero"/>
      		<xsd:element name="CodigosRechazo" type="TipoListaCodigosRechazo"/>
        </xsd:sequence>
    </xsd:complexType>
    
	<xsd:complexType name="TipoListaNumeracionRechazadaDonante">
        <xsd:sequence>
          <xsd:element name="NumeracionRechazada" type="TipoNumeracionRechazadaDonante" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    
      
    <xsd:complexType name="TipoNumeracionRechazadaDonante">
        <xsd:sequence>
            <xsd:element name="Numero" type="TipoNumero"/>
            <xsd:element name="CodigosRechazo" type="TipoListaCodigosRechazo"/>
            <xsd:element name="DocumentoFC" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoDC" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoFR" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoUO" type="TipoDocumentoOpcional" minOccurs="0" />
			<xsd:element name="DocumentoLD" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoLS" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoNA" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoNI" type="TipoDocumentoOpcional" minOccurs="0" />
			<xsd:element name="DocumentoLA" type="TipoDocumentoOpcional" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    
      
    <xsd:complexType name="TipoRangoFecha">
        <xsd:sequence>
            <xsd:element name="InicioFecha" type="TipoFechaHora"/>
            <xsd:element name="FinalFecha" type="TipoFechaHora"/>
        </xsd:sequence>
    </xsd:complexType>
  
   <xsd:complexType name="TipoListaCodigosRechazo">
        <xsd:sequence>
            <xsd:element name="CodigoRechazo" type="TipoCodigoCausa" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
  
     
    <xsd:complexType name="TipoCabeceraMensaje">
        <xsd:sequence>
            <xsd:element name="IdentificadorProceso" type="TipoIdentificadorProceso"/>
            <xsd:element name="IdentificadorMensaje" type="TipoIdentificadorMensaje"/>
            <xsd:element name="FechaCreacionMsg" type="TipoFechaHora"/>
            <xsd:element name="TipoMsg" type="TipoTipoMsg"/>
            <xsd:element name="Emisor" type="TipoCodigoOperador"/>
            <xsd:element name="Observaciones" type="TipoObservaciones" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
       
    <xsd:complexType name="TipoCuerpoMensaje">
    <xsd:annotation>
            <xsd:documentation>
                SolicitudNIP:                	              	0001
                RespuestaSolicitudNIP:              		  	0002
                SolicitudReenvioNIP:						  	0003
                RespuestaSolicitudReenvioNIP:                 	0004
                SolicitudPortacion:     			          	1001
                ReplicaSolicitudPortacion:     			      	1002
                RespuestaSolicitudPortacionDonante:      	  	1003
                ReplicaRespuestaSolicitudPortacionDonante:    	1004
                SolicitudDeProgramacionPortacion:		      	1005
                ProgramacionPortacion:                        	1006
                ConfirmacionProgramacionPortacion:		      	1007
                RechazoPortacion:				    		  	9999
                SolicitudCancelacion:			    		  	2001
                RespuestaSolicitudCancelacion:                	2002
                SolicitudSincronizacion:                      	3001
                RespuestaSolicitudSincronizacion:             	3002
                ErrorDetectadoABD:                            	9998
				SolicitudReversion:								4001
                ReplicaSolicitudReversion:						4002
				RespuestaReversion:								4003
                RespuestaSolicitudReversion:					4004
				RechazoReversion:				    			4999
				SolicitudCancelacionProcesoEnCurso:				5001
                RespuestaCancelacionProcesoEnCurso				5002
				RespuestaCancelacionProcesoEnCursoNIP:			5003
				RechazoCancelacionProcesoEnCurso:				5999
            </xsd:documentation>
        </xsd:annotation>
        <xsd:choice>
            <xsd:element name="SolicitudNIP" type="TipoSolicitudNIP"/><!-- 0001-->
            <xsd:element name="RespuestaSolicitudNIP" type="TipoRespuestaSolicitudNIP"/><!-- 0002-->
            <xsd:element name="SolicitudReenvioNIP" type="TipoSolicitudReenvioNIP"/><!-- 0003-->
            <xsd:element name="RespuestaSolicitudReenvioNIP" type="TipoRespuestaSolicitudReenvioNIP"/><!-- 0004-->
            <xsd:element name="SolicitudPortacion" type="TipoSolicitudPortacion"/><!-- 1001-->
            <xsd:element name="ReplicaSolicitudPortacion" type="TipoReplicaSolicitudPortacion"/><!-- 1002-->
            <xsd:element name="RespuestaSolicitudPortacionDonante" type="TipoRespuestaSolicitudPortacionDonante"/><!-- 1003 -->
            <xsd:element name="ReplicaRespuestaSolicitudPortacionDonante" type="TipoReplicaRespuestaSolicitudPortacionDonante"/><!-- 1004 -->
            <xsd:element name="SolicitudDeProgramacionPortacion" type="TipoSolicitudDeProgramacionPortacion"/><!-- 1005 -->
            <xsd:element name="ProgramacionPortacion" type="TipoProgramacionPortacion"/><!-- 1006-->
            <xsd:element name="ConfirmacionProgramacionPortacion" type="TipoConfirmacionProgramacionPortacion"/><!-- 1007 -->
            <xsd:element name="RechazoPortacion" type="TipoRechazoPortacion"/><!-- 9999-->
            <xsd:element name="SolicitudCancelacion" type="TipoSolicitudCancelacion"/><!-- 2001-->
            <xsd:element name="RespuestaSolicitudCancelacion" type="TipoRespuestaSolicitudCancelacion"/><!-- 2002-->
            <xsd:element name="SolicitudSincronizacion" type="TipoSolicitudSincronizacion"/><!-- 3001-->
            <xsd:element name="RespuestaSolicitudSincronizacion" type="TipoRespuestaSolicitudSincronizacion"/><!-- 3002 -->
            <xsd:element name="ErrorDetectadoABD" type="TipoErrorDetectadoABD"/><!-- 9998-->
			<xsd:element name="SolicitudReversion" type="TipoSolicitudReversion"/><!-- 4001-->			
            <xsd:element name="ReplicaSolicitudReversion" type="TipoReplicaSolicitudReversion"/><!-- 4002-->
			<xsd:element name="RespuestaReversion" type="TipoRespuestaReversion"/><!-- 4003-->
			<xsd:element name="RespuestaSolicitudReversion" type="TipoRespuestaSolicitudReversion"/><!-- 4004-->
			<xsd:element name="RechazoReversion" type="TipoRechazoReversion"/><!-- 4999-->
			<xsd:element name="SolicitudCancelacionProcesoEnCurso" type="TipoSolicitudCancelacionProcesoEnCurso"/><!-- 5001-->
			<xsd:element name="RespuestaCancelacionProcesoEnCurso" type="TipoRespuestaCancelacionProcesoEnCurso"/><!-- 5002-->
			<xsd:element name="RespuestaCancelacionProcesoEnCursoNIP" type="TipoRespuestaCancelacionProcesoEnCursoNIP"/><!-- 5003-->
			<xsd:element name="RechazoCancelacionProcesoEnCurso" type="TipoRechazoProcesoEnCurso"/><!-- 5999-->
        </xsd:choice>
    </xsd:complexType>
 
    <xsd:complexType name="TipoSolicitudNIP"><!-- 0001 -->
        <xsd:sequence>
            <xsd:element name="Donante" type="TipoCodigoOperador"/>
			<xsd:element name="NumeroRepresentante" type="TipoNumero" minOccurs="0"/>
            <xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
        </xsd:sequence>
    </xsd:complexType>
   
    <xsd:complexType name="TipoRespuestaSolicitudNIP"><!-- 0002 -->
        <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="NumeracionRechazada" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoSolicitudReenvioNIP"><!-- 0003 -->
        <xsd:sequence>
            <xsd:element name="Numero" type="TipoNumero"/>
        </xsd:sequence>
    </xsd:complexType>
   
    <xsd:complexType name="TipoRespuestaSolicitudReenvioNIP"><!-- 0004 -->
        <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="CodigosRechazo" type="TipoListaCodigosRechazo" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoSolicitudPortacion"><!-- 1001 -->
        <xsd:sequence>
            <xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado"/>
			<xsd:element name="TipoDocumentoIdentificacion" type="TipoTipoDocumentoIdentificacion" />
            <xsd:element name="DireccionAbonado" type="TipoDireccionAbonado"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado"/>
            <xsd:element name="FechaExpedicionIdentificacion" type="TipoFecha" minOccurs="0"/>
            <xsd:element name="TipoDocumentoIdentificacionRepresentanteLegal" type="TipoTipoDocumentoIdentificacion" minOccurs="0"/>
			<xsd:element name="IdentificacionRepresentanteLegal" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="FechaExpedicionIdentificacionRepresentanteLegal" type="TipoFecha" minOccurs="0"/>	
            <xsd:element name="Donante" type="TipoCodigoOperador"/>
            <xsd:element name="TipoUsuario" type="TipoTipoUsuario"/>
            <xsd:element name="TipoServicio" type="TipoTipoServicio"/>
            <xsd:element name="NIP" type="TipoNIP" minOccurs="0"/>
            <xsd:element name="FlagVentanaAmpliada" type="TipoFlagVentanaAmpliada"/>
            <xsd:element name="SolicitudTerceros" type="TipoSolicitudTerceros"/>
            <xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
            <xsd:element name="NRN" type="TipoNRN"/>
            <xsd:element name="DocumentoID" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoAT" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoCC" type="TipoDocumentoOpcional" minOccurs="0" />
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoReplicaSolicitudPortacion"><!-- 1002 -->
         <xsd:sequence>
            <xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado"/>
			<xsd:element name="TipoDocumentoIdentificacion" type="TipoTipoDocumentoIdentificacion" />
            <xsd:element name="DireccionAbonado" type="TipoDireccionAbonado"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado"/>
            <xsd:element name="FechaExpedicionIdentificacion" type="TipoFecha" minOccurs="0"/>
            <xsd:element name="TipoDocumentoIdentificacionRepresentanteLegal" type="TipoTipoDocumentoIdentificacion" minOccurs="0"/>
			<xsd:element name="IdentificacionRepresentanteLegal" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="FechaExpedicionIdentificacionRepresentanteLegal" type="TipoFecha" minOccurs="0"/>
            <xsd:element name="Donante" type="TipoCodigoOperador"/>
            <xsd:element name="TipoUsuario" type="TipoTipoUsuario"/>
            <xsd:element name="TipoServicio" type="TipoTipoServicio"/>
            <xsd:element name="SolicitudTerceros" type="TipoSolicitudTerceros"/>
			<xsd:element name="ListaNumeracionNip" type="TipoListaNumeracionNip"/>
            <xsd:element name="NRN" type="TipoNRN"/>
            <xsd:element name="DocumentoID" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoAT" type="TipoDocumentoOpcional" minOccurs="0" />
            <xsd:element name="DocumentoCC" type="TipoDocumentoOpcional" minOccurs="0" />
         </xsd:sequence>
    </xsd:complexType>
        
   <xsd:complexType name="TipoRespuestaSolicitudPortacionDonante"><!-- 1003 -->
        <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="ListaNumeracionRechazada" type="TipoListaNumeracionRechazadaDonante" minOccurs="0"/>
       </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoReplicaRespuestaSolicitudPortacionDonante"><!-- 1004 -->
        <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="ListaNumeracionRechazada" type="TipoListaNumeracionRechazadaDonante" minOccurs="0"/>
         </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoSolicitudDeProgramacionPortacion"><!-- 1005 -->
        <xsd:sequence>
            <xsd:element name="FechaVentanaMaxima" type="TipoFechaHora"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoProgramacionPortacion"> <!-- 1006 -->
       <xsd:sequence>
            <xsd:element name="FechaVentanaCambio" type="TipoFechaHora"/>
       </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoConfirmacionProgramacionPortacion"> <!-- 1007 -->
       <xsd:sequence>
            <xsd:element name="FechaVentanaCambio" type="TipoFechaHora"/>
       </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoRechazoPortacion"> <!-- 9999 -->
       <xsd:sequence>
            <xsd:element name="NumeracionesRechazadas" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
       </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoSolicitudCancelacion"> <!-- 2001 -->
       <xsd:sequence>
            <xsd:element name="ListaNumeracionCancelar" type="TipoListaNumeracion"/>
            <xsd:element name="FechaVentanaCancelacion" type="TipoFechaHora"/>
       </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoRespuestaSolicitudCancelacion"> <!-- 2002 -->
        <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="NumeracionesRechazadas" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoSolicitudSincronizacion"> <!-- 3001 -->
        <xsd:sequence>
            <xsd:element name="TipoSincronizacion" type="TipoTipoSincronizacion"/>
            <xsd:element name="RangoFecha" type="TipoRangoFecha" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
     <xsd:complexType name="TipoRespuestaSolicitudSincronizacion"> <!-- 3002 -->
         <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="CodigosRechazo" type="TipoListaCodigosRechazo" minOccurs="0"/>
            <xsd:element name="RutaNombreFichero" type="TipoRutaNombreFichero" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="TipoErrorDetectadoABD"> <!-- 9998 -->
       <xsd:sequence>
            <xsd:element name="CodigosRechazo" type="TipoListaCodigosRechazo"/>
            <xsd:element name="IdentificadorMensajeErroneo" type="TipoIdentificadorMensaje"/>
       </xsd:sequence>
    </xsd:complexType>
	
	<xsd:complexType name="TipoSolicitudReversion"><!-- 4001 -->
    	<xsd:sequence>
			<xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado" minOccurs="0"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="NumeroCUN" type="TipoNumeroCUN"/>
        	<xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
			<xsd:element name="DocumentoCR" type="TipoDocumentoOpcional" minOccurs="0" />
    	</xsd:sequence>
 	</xsd:complexType>
    
    <xsd:complexType name="TipoReplicaSolicitudReversion"><!-- 4002 -->
    	<xsd:sequence>
			<xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado" minOccurs="0"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="NumeroCUN" type="TipoNumeroCUN"/>
        	<xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
			<xsd:element name="DocumentoCR" type="TipoDocumentoOpcional" minOccurs="0" />
    	</xsd:sequence>
 	</xsd:complexType>
	
	<xsd:complexType name="TipoRespuestaReversion"><!-- 4003 -->
    	<xsd:sequence>
        	<xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="NumeracionesRechazadas" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
    	</xsd:sequence>
 	</xsd:complexType>

	<xsd:complexType name="TipoRespuestaSolicitudReversion"> <!-- 4004 -->
        <xsd:sequence>
            <xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="FechaVentanaCambio" type="TipoFechaHora" minOccurs="0"/>
            <xsd:element name="NumeracionesRechazadas" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
	
	<xsd:complexType name="TipoRechazoReversion"> <!-- 4999 -->
       <xsd:sequence>
            <xsd:element name="NumeracionesRechazadas" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
       </xsd:sequence>
    </xsd:complexType>
	
		<xsd:complexType name="TipoSolicitudCancelacionProcesoEnCurso"><!-- 5001 -->
    	<xsd:sequence>
			<xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado" minOccurs="0"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="NumeroCUN" type="TipoNumeroCUN"/>
        	<xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
			<xsd:element name="DocumentoCN" type="TipoDocumentoOpcional" minOccurs="0" />
    	</xsd:sequence>
 	</xsd:complexType>
    
    <xsd:complexType name="TipoRespuestaCancelacionProcesoEnCurso"><!-- 5002 -->
    	<xsd:sequence>
			<xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado" minOccurs="0"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="NumeroCUN" type="TipoNumeroCUN"/>
			<xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
			<xsd:element name="FechaVentanaCambio" type="TipoFechaHora" minOccurs="0"/>
        	<xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
			<xsd:element name="DocumentoCN" type="TipoDocumentoOpcional" minOccurs="0" />
    	</xsd:sequence>
 	</xsd:complexType>
	
	<xsd:complexType name="TipoRespuestaCancelacionProcesoEnCursoNIP"><!-- 5003 -->
    	<xsd:sequence>
			<xsd:element name="NombreRazonSocialAbonado" type="TipoNombreRazonSocialAbonado" minOccurs="0"/>
            <xsd:element name="IdentificacionAbonado" type="TipoIdentificacionAbonado" minOccurs="0"/>
			<xsd:element name="NumeroCUN" type="TipoNumeroCUN"/>
        	<xsd:element name="RespuestaABD" type="TipoRespuestaABD"/>
            <xsd:element name="ListaNumeracion" type="TipoListaNumeracion"/>
			<xsd:element name="DocumentoCN" type="TipoDocumentoOpcional" minOccurs="0" />
    	</xsd:sequence>
 	</xsd:complexType>
	
	<xsd:complexType name="TipoRechazoProcesoEnCurso"> <!-- 5999 -->
       <xsd:sequence>
            <xsd:element name="NumeracionesRechazadas" type="TipoListaNumeracionRechazadaABD" minOccurs="0"/>
       </xsd:sequence>
    </xsd:complexType>
      
</xsd:schema>
