#%RAML 1.0 NamedExample
auditLogsMsgInput:
  auditLogIn:
    logDate: "01/08/2022 07:17:32 PM"
    sourceIP: "190.128.222.214"
    user: "CanalesDigitales"
    sourcePortal: "CanalesDigitales"
    requestIdentifier: "LISIM-PARAMETRIZACION-FIJA-CC"
    collectionName: "MDM_AUDITORIA_SERVICIOS"
    serviceName: "ConsultasLISIM"
    operation: "CONSULTA_PARAMETRIZACION_TRAMITES-DATOS SALIDA"
    requestDate: "01/08/2022 07:17:32 PM"
    inputData: !include auditLogInputData.json
    responseDate: "01/08/2022 07:17:32 PM"
    outputData: ""
    observations: ""