#%RAML 1.0 NamedExample
SPNPQRLoggerInput:
  SPNPQRLoggerIN:
    Date: "05/10/2021 12:11:18 p. m."
    PQRNumber: "MDM-PQR-4056704"
    ActivitySN1: "MDM-PQR-ACT-2145972"
    ServiceAccount: "CS-1015072"
    Technology: "FTTH"
    ModemSerial: "ALCLDEYCDI8Y"
    ModemMac: "AAAAAAAAA228"
    ModemBrand: "ALCATEL"
    ModemModel: "I-240W-A"
    Result: null
    ClosingType: "False"
    CommandDate: "05/10/2021 12:11:40 p. m."
    CommandType: "Estado Plataforma"
    CommandDescription: "Estado Línea IMS"
    Command: "H_PR_VOIP_EST_IMS"
    CommandResponse: "reponseERRORerrorExecutionoftheMEcommandfails.ThedetailisResultResultCode101nResultResultDescGrupo_de_Redundancia_ATS-ThesubscriberisnotdefinedintheHSSorATSorservicedataisnotconfiguredforthesubscriber.n.dicerrorExecutionoftheMEcommandfails.ThedetailisResultResultCode101nResultResultDescGrupo_de_Redundancia_ATS-ThesubscriberisnotdefinedintheHSSorATSorservicedataisnotconfiguredforthesubscriber.n."
    User: "danimerg"