#%RAML 1.0 Library
types:
  WSRegistroPositivo:
    type: object
    properties:
      WSRequestHeader:
        properties:
          System:
            properties:                    
              correlationID:
                type: string
                required: true
                minLength: 1
              processingServer:
                type: string
                required: false
          Property:
            required: false
            properties:
              value:
                type: string
                required: false
                xml:
                  attribute: true
              name:
                type: string
                required: false
                xml:
                  attribute: true
      RegistroPositivo:
        properties:
          sUsuarioETB:
            description: ETB User
            type: string
            required: false
          sIMEI:
            description: IMEI number
            type: string
            required: false
          sMSISDN: 
            description: MSISDN number
            type: string               
          sNombrePropietario: 
            description: Owner's name
            type: string
            required: false
          sTipoDocPropietario: 
            description: Owner's document type
            type: string
            required: false
          sDocPropietario: 
            description: Owner's document number
            type: string 
            required: false  
          sTelContactoPropietario:
            description: Owner's contact phone
            type: string
            required: false
          sNombreContacto:
            description: Contact name
            type: string
            required: false
          sDireccionContacto:
            description: Contact address
            type: string
            required: false
          iTipoUsuarioAutorizado:
            description: Authorized user type
            type: string
            required: false
          sTipoDoAutorizado:
            description: Authorized document type
            type: string
            required: false
          sDocAutorizado:
            description: Authorized document number
            type: string
            required: false
          sTelContactoAutorizado:
            description: Authorized contact phone
            type: string
            required: false