#%RAML 1.0 Library

types:
  MensajeABD:
    type: object
    properties:
      CabeceraMensaje:
        type: TipoCabeceraMensaje
      CuerpoMensaje:
        type: object
        properties:
  TipoCabeceraMensaje:
    type: object 
    properties:
      IdentificadorProceso:
        type: string
        maxLength: 20
        pattern: "[0-9]*"
        example: "00007202109150001092"
      IdentificadorMensaje:
        type: string
        maxLength: 20
        pattern: "[0-9]*"
        example: "00007202109150001092"
      FechaCreacionMsg:
        type: string
        maxLength: 14
        pattern: "[0-9]*"
        example: "20210915190418"
      TipoMsg:
        type: string
        maxLength: 4
        enum:
          
          ["0001","0002","0003","0004","1001","1002","1003","1004","1005","1006","1007","9999","2001","2002","3001","3002","9998"]
      Emisor:
        type: string 
        maxLength: 5
        pattern: "[0-9]*"
        example: "00007"
      Observaciones:
        type:  string
        minLength: 0
        maxLength: 250
        example: ""


