#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Audit:
        type: !include objects/audit.raml
        required: false
      Document_Number:
        type: string
        example: '12345678'
        required: false
      Document_Type:
        type: string
        example: 'CC'
        required: false
      IMEI:
        type: string
        example: '863281064014329'
        required: false