#%RAML 1.0 DataType 
type: object
properties:
  WSRequestHeader:
    type: !include objects/header.raml
    required: true
  WSRequestBody:
    type: object
    properties:
      Audit:
        type: object
        properties:
          Canal:
            type: string
            example: string
            required: false
          Id_Device:
            type: string
            example: string
            required: false
          SO:
            type: string
            example: string
            required: false
          IP_Address:
            type: string
            example: string
            required: false
          WhatsApp_Phone_Number:
            type: string
            example: string
            required: false
      Customer:
        type: object
        properties:
          Document_Number:
            type: string
            example: string
            required: false
          Document_Type:
            type: string
            example: string
            required: false
      Email:
        type: string
        example: string
        required: false
      Phone:
        type: string
        example: string
        required: false
      SVA:
        type: integer
        example: 0
        required: false
